var g;g||=typeof Module != 'undefined' ? Module : {};var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,k="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,m="",ha,ia,ja;
if(fa){var fs=require("fs"),ka=require("path");m=k?ka.dirname(m)+"/":__dirname+"/";ha=(a,b)=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ja=a=>{a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a};ia=(a,b,c,d=!0)=>{a=la(a)?new URL(a):ka.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,h)=>{e?c(e):b(d?h.buffer:h)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof ma||a.context instanceof ma))throw a;});da=(a,b)=>{process.exitCode=a;throw b;}}else if(ea||k)k?m=self.location.href:"undefined"!=typeof document&&document.currentScript&&(m=document.currentScript.src),m=m.startsWith("blob:")?"":m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+1),ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},k&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);
return new Uint8Array(b.response)}),ia=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var na=g.print||console.log.bind(console),q=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var t;g.wasmBinary&&(t=g.wasmBinary);var oa,u=!1,w,pa,x,qa,ra,y,z,A,B;
function sa(){var a=oa.buffer;g.HEAP8=pa=new Int8Array(a);g.HEAP16=qa=new Int16Array(a);g.HEAPU8=x=new Uint8Array(a);g.HEAPU16=ra=new Uint16Array(a);g.HEAP32=y=new Int32Array(a);g.HEAPU32=z=new Uint32Array(a);g.HEAPF32=A=new Float32Array(a);g.HEAPF64=B=new Float64Array(a)}var ta=[],ua=[],va=[],wa=[];function xa(){var a=g.preRun.shift();ta.unshift(a)}var C=0,ya=null,za=null;
function Aa(a){g.onAbort?.(a);a="Aborted("+a+")";q(a);u=!0;w=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ba=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),D;D="atom-ui.wasm";if(!Ba(D)){var Ca=D;D=g.locateFile?g.locateFile(Ca,m):m+Ca}function Da(a){if(a==D&&t)return new Uint8Array(t);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}
function Ea(a){if(!t&&(ea||k)){if("function"==typeof fetch&&!la(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Da(a));if(ia)return new Promise((b,c)=>{ia(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Da(a))}function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{q(`failed to asynchronously prepare wasm: ${d}`);Aa(d)})}
function Ga(a,b){var c=D;t||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||la(c)||fa||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){q(`wasm streaming compile failed: ${e}`);q("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}function ma(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ha=a=>{for(;0<a.length;)a.shift()(g)},Ia=g.noExitRuntime||!0,Ja="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,E=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ja)return Ja.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ta=(a,b)=>{Ka=a;La=b;if(Ma)if(Na||=!0,0==a)F=function(){var d=Math.max(0,Oa+b-Pa())|0;setTimeout(Qa,d)};else if(1==a)F=function(){Ra(Qa)};else if(2==a){if("undefined"==typeof Sa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Sa=function(d){c.push(d);k?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),
postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}else Sa=setImmediate;F=function(){Sa(Qa)}}},Pa;Pa=()=>performance.now();
var ab=(a,b,c,d,e)=>{Ma=a;Ua=d;var h=G;Na=!1;Qa=function(){if(!u)if(0<Va.length){var f=Va.shift();f.td(f.od);if(Wa){var l=Wa,n=0==l%1?l-1:Math.floor(l);Wa=f.qd?n:(8*l+(n+.5))/9}g.setStatus&&(f=g.statusMessage||"Please wait...",l=Wa,n=Xa.sd,l?l<n?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(f):g.setStatus(""));h<G||setTimeout(Qa,0)}else if(!(h<G))if(Ya=Ya+1|0,1==Ka&&1<La&&0!=Ya%La)F();else{0==Ka&&(Oa=Pa());if(!(u||g.preMainLoop&&!1===g.preMainLoop())){if(!u)try{if(a(),!Ia)try{w=
f=w,Za(f)}catch(p){$a(p)}}catch(p){$a(p)}g.postMainLoop?.()}h<G||("object"==typeof SDL&&SDL.audio?.xd?.(),F())}};e||(b&&0<b?Ta(0,1E3/b):Ta(1,1),F());if(c)throw"unwind";},$a=a=>{a instanceof ma||"unwind"==a||da(1,a)},Za=a=>{w=a;Ia||(g.onExit?.(a),u=!0);da(a,new ma(a))},bb=a=>{w=a;Za(a)},Na=!1,F=null,G=0,Ma=null,Ua=0,Ka=0,La=0,Ya=0,Va=[];function cb(){F=null;G++}var Xa={},Oa,Qa,Wa,db=!1,eb=!1,fb=[];
function gb(){function a(){eb=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}if(!hb){hb=!0;var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!eb&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}var ib=!1,jb=void 0,H=void 0;
function kb(){if(!db)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var lb=0;function Ra(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===lb)lb=b+1E3/60;else for(;b+2>=lb;)lb+=1E3/60;setTimeout(a,Math.max(lb-b,0))}}var mb=[];function nb(){var a=g.canvas;mb.forEach(b=>b(a.width,a.height))}
function ob(a,b,c){b&&c?(a.md=b,a.jd=c):(b=a.md,c=a.jd);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var h=Math.min(screen.width/d,screen.height/e);d=Math.round(d*h);e=Math.round(e*
h)}H?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Sa,hb,rb=a=>{var b=pb();a();qb(b)},sb=0,tb=[];
function ub(){if(navigator.userActivation?navigator.userActivation.isActive:sb&&vb.Lc)for(var a=0;a<tb.length;++a){var b=tb[a];tb.splice(a,1);--a;b.Ad(...b.pd)}}var I=[];function wb(a){var b=I[a];b.target.removeEventListener(b.yc,b.Sc,b.zc);I.splice(a,1)}function J(a){if(!a.target)return-4;if(a.Ac)a.Sc=function(c){++sb;vb=a;ub();a.Bc(c);ub();--sb},a.target.addEventListener(a.yc,a.Sc,a.zc),I.push(a);else for(var b=0;b<I.length;++b)I[b].target==a.target&&I[b].yc==a.yc&&wb(b--);return 0}
function xb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var vb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?E(x,a):"":a;return Fb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Gb=a=>0>Fb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Hb=[],Ib,L=a=>{var b=Hb[a];b||(a>=Hb.length&&(Hb.length=a+1),Hb[a]=b=Ib.get(a));return b},M=(a,b,c)=>{var d=x;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var l=
a.charCodeAt(++h);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},Jb=(a,b,c,d,e,h)=>{yb||=N(256);a={target:K(a),yc:h,Ac:d,Bc:(f=event)=>{var l=f.target.id?f.target.id:"",n=yb;M(xb(f.target),n+0,128);M(l,n+128,128);L(d)(e,n,b)&&f.preventDefault()},zc:c};return J(a)},Kb=(a,
b,c,d,e,h)=>{zb||=N(176);a={target:K(a),yc:h,Ac:d,Bc:f=>{var l=zb;B[l>>3]=f.timeStamp;var n=l>>2;y[n+2]=f.location;y[n+3]=f.ctrlKey;y[n+4]=f.shiftKey;y[n+5]=f.altKey;y[n+6]=f.metaKey;y[n+7]=f.repeat;y[n+8]=f.charCode;y[n+9]=f.keyCode;y[n+10]=f.which;M(f.key||"",l+44,32);M(f.code||"",l+76,32);M(f.char||"",l+108,32);M(f.locale||"",l+140,32);L(d)(e,l,b)&&f.preventDefault()},zc:c};return J(a)},Lb=(a,b,c)=>{B[a>>3]=b.timeStamp;a>>=2;y[a+2]=b.screenX;y[a+3]=b.screenY;y[a+4]=b.clientX;y[a+5]=b.clientY;y[a+
6]=b.ctrlKey;y[a+7]=b.shiftKey;y[a+8]=b.altKey;y[a+9]=b.metaKey;qa[2*a+20]=b.button;qa[2*a+21]=b.buttons;y[a+11]=b.movementX;y[a+12]=b.movementY;c=Gb(c);y[a+13]=b.clientX-(c.left|0);y[a+14]=b.clientY-(c.top|0)},Mb=(a,b,c,d,e,h)=>{Ab||=N(72);a=K(a);return J({target:a,Lc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,yc:h,Ac:d,Bc:(f=event)=>{Lb(Ab,f,a);L(d)(e,Ab,b)&&f.preventDefault()},zc:c})},Nb=(a,b,c,d,e)=>{Bb||=N(260);return J({target:a,yc:e,Ac:d,Bc:(h=event)=>{var f=Bb,l=document.pointerLockElement||
document.Gc||document.ed||document.dd;y[f>>2]=!!l;var n=l?.id||"";M(xb(l),f+4,128);M(n,f+132,128);L(d)(20,f,b)&&h.preventDefault()},zc:c})},Ob=(a,b,c,d,e)=>J({target:a,yc:e,Ac:d,Bc:(h=event)=>{L(d)(38,0,b)&&h.preventDefault()},zc:c}),Pb=(a,b,c,d)=>{Cb||=N(36);a=K(a);return J({target:a,yc:"resize",Ac:d,Bc:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=Cb;y[f>>2]=0;y[f+4>>2]=h.clientWidth;y[f+8>>2]=h.clientHeight;y[f+12>>2]=innerWidth;y[f+16>>2]=innerHeight;y[f+20>>2]=outerWidth;y[f+24>>
2]=outerHeight;y[f+28>>2]=pageXOffset|0;y[f+32>>2]=pageYOffset|0;L(d)(10,f,b)&&e.preventDefault()}}},zc:c})},Qb=(a,b,c,d,e,h)=>{Db||=N(1696);a=K(a);return J({target:a,Lc:"touchstart"==h||"touchend"==h,yc:h,Ac:d,Bc:f=>{for(var l,n={},p=f.touches,r=0;r<p.length;++r)l=p[r],l.Tc=l.Uc=0,n[l.identifier]=l;for(r=0;r<f.changedTouches.length;++r)l=f.changedTouches[r],l.Tc=1,n[l.identifier]=l;for(r=0;r<f.targetTouches.length;++r)n[f.targetTouches[r].identifier].Uc=1;p=Db;B[p>>3]=f.timeStamp;var v=p>>2;y[v+
3]=f.ctrlKey;y[v+4]=f.shiftKey;y[v+5]=f.altKey;y[v+6]=f.metaKey;v+=7;var Tb=Gb(a),Ub=0;for(r in n)if(l=n[r],y[v]=l.identifier,y[v+1]=l.screenX,y[v+2]=l.screenY,y[v+3]=l.clientX,y[v+4]=l.clientY,y[v+5]=l.pageX,y[v+6]=l.pageY,y[v+7]=l.Tc,y[v+8]=l.Uc,y[v+9]=l.clientX-(Tb.left|0),y[v+10]=l.clientY-(Tb.top|0),v+=13,31<++Ub)break;y[p+8>>2]=Ub;L(d)(e,p,b)&&f.preventDefault()},zc:c})},Rb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},Sb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Vb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Wb=a=>{a.rd=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
Xb=a=>{a.ud=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Yb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Zb=1,$b=[],O=[],ac=[],bc=[],P=[],Q=[],cc=[],dc=[],R=[],ec={},fc=4,gc=a=>{for(var b=Zb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=S[c](),f=h&&gc(d);h?(h.name=f,d[f]=h):T||=1282;y[b+4*e>>2]=f}},ic=(a,b)=>{a.Gc||(a.Gc=a.getContext,a.getContext=function(d,e){e=a.Gc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Nc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
hc(c,b):0},hc=(a,b)=>{var c=gc(dc),d={handle:c,attributes:b,version:b.Nc,Hc:a};a.canvas&&(a.canvas.nd=d);dc[c]=d;("undefined"==typeof b.Rc||b.Rc)&&jc(d);return c},kc=a=>{V=dc[a];g.Mc=S=V?.Hc;return!(a&&!S)},jc=a=>{a||=V;if(!a.kd){a.kd=!0;var b=a.Hc;Rb(b);Sb(b);Vb(b);Wb(b);Xb(b);2<=a.version&&(b.Qc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Qc)b.Qc=b.getExtension("EXT_disjoint_timer_query");b.ld=b.getExtension("WEBGL_multi_draw");Yb(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},lc={},T,V,mc=(a,b,c,d,e,h)=>{a={target:K(a),yc:h,Ac:d,Bc:(f=event)=>{L(d)(e,0,b)&&f.preventDefault()},zc:c};J(a)},nc=(a,b,c,d)=>{Eb||=N(104);return J({target:a,Lc:!0,yc:"wheel",Ac:d,Bc:(e=event)=>{var h=Eb;Lb(h,e,a);B[h+72>>3]=e.deltaX;B[h+80>>3]=e.deltaY;B[h+88>>3]=e.deltaZ;y[h+96>>2]=e.deltaMode;L(d)(9,h,b)&&e.preventDefault()},zc:c})},oc=["default","low-power","high-performance"],pc=[null,[],[]],qc=[];
function rc(){var a=Yb(S);return a=a.concat(a.map(b=>"GL_"+b))}
var sc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=rc().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)y[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;q(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;q(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}y[b>>2]=c}else T||=1281},tc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},uc=a=>{var b=tc(a)+1,c=N(b);c&&M(a,c,b);return c},vc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),wc=a=>{a-=5120;return 0==a?pa:1==a?x:2==a?qa:4==a?y:6==a?A:5==a||28922==a||28520==a||30779==a||30782==a?z:ra},xc=(a,b,c,d,e)=>{a=wc(a);var h=fc;b=d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+h-1&-h);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=S.gd;if(b){var c=b.Fc[a];"number"==typeof c&&(b.Fc[a]=c=S.getUniformLocation(b,b.bd[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],yc=[],Ac=a=>{var b=tc(a)+1,c=zc(b);M(a,c,b);return c};
g.requestFullscreen=function(a,b){function c(){db=!1;var h=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===h?(d.exitFullscreen=kb,jb&&d.requestPointerLock(),db=!0,H?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>2]|8388608),ob(g.canvas),nb()):ob(d)):(h.parentNode.insertBefore(d,h),h.parentNode.removeChild(h),H?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>
2]&-8388609),ob(g.canvas),nb()):ob(d));g.onFullScreen?.(db);g.onFullscreen?.(db)}jb=a;H=b;"undefined"==typeof jb&&(jb=!0);"undefined"==typeof H&&(H=!1);var d=g.canvas;ib||(ib=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};g.requestAnimationFrame=Ra;g.setCanvasSize=function(a,b,c){ob(g.canvas,a,b);c||nb()};g.pauseMainLoop=cb;g.resumeMainLoop=function(){G++;var a=Ka,b=La,c=Ma;Ma=null;ab(c,0,!1,Ua,!0);Ta(a,b);F()};
g.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};g.createContext=function(a,b,c,d){if(b&&g.Mc&&a==g.canvas)return g.Mc;var e;if(b){var h={antialias:!1,alpha:!1,Nc:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var f in d)h[f]=d[f];if("undefined"!=typeof lc&&(e=ic(a,h)))var l=dc[e].Hc}else l=a.getContext("2d");if(!l)return null;c&&(g.Mc=l,b&&kc(e),g.Bd=b,fb.forEach(n=>n()),gb());return l};
for(var S,Y=0;32>Y;++Y)qc.push(Array(Y));var Bc=new Float32Array(288);for(Y=0;288>Y;++Y)X[Y]=Bc.subarray(0,Y);var Cc=new Int32Array(288);for(Y=0;288>Y;++Y)yc[Y]=Cc.subarray(0,Y);
var Rc={ma:function(){return 0},ob:function(){return 0},pb:function(){},kb:(a,b,c)=>x.copyWithin(a,b,b+c),k:()=>{Aa("")},Ua:()=>{cb();Ma=null},fa:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ha:(a,b,c)=>{a=K(a);if(!a)return-4;a=Gb(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},z:Pa,Va:()=>performance.now(),$a:(a,b)=>{function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},jb:a=>{var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+
.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-oa.buffer.byteLength+65535)/65536;try{oa.grow(e);sa();var h=1;break a}catch(f){}h=void 0}if(h)return!0}return!1},P:(a,b,c,d)=>Jb(a,b,c,d,12,"blur"),ea:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},Q:(a,b,c,d)=>Jb(a,b,c,d,13,"focus"),Z:(a,b,c,d)=>Kb(a,b,c,d,2,"keydown"),X:(a,b,c,d)=>Kb(a,b,c,d,1,"keypress"),Y:(a,b,c,d)=>Kb(a,b,c,d,3,"keyup"),ab:(a,b,c)=>{a=L(a);ab(a,b,
c)},da:(a,b,c,d)=>Mb(a,b,c,d,5,"mousedown"),aa:(a,b,c,d)=>Mb(a,b,c,d,33,"mouseenter"),$:(a,b,c,d)=>Mb(a,b,c,d,34,"mouseleave"),ba:(a,b,c,d)=>Mb(a,b,c,d,8,"mousemove"),ca:(a,b,c,d)=>Mb(a,b,c,d,6,"mouseup"),S:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Gc||document.body.ed||document.body.dd))return-1;a=K(a);if(!a)return-4;Nb(a,b,c,d,"mozpointerlockchange");Nb(a,b,c,d,"webkitpointerlockchange");Nb(a,b,c,d,"mspointerlockchange");return Nb(a,b,c,d,"pointerlockchange")},
R:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.Gc||document.body.ed||document.body.dd))return-1;a=K(a);if(!a)return-4;Ob(a,b,c,d,"mozpointerlockerror");Ob(a,b,c,d,"webkitpointerlockerror");Ob(a,b,c,d,"mspointerlockerror");return Ob(a,b,c,d,"pointerlockerror")},ga:(a,b,c,d)=>Pb(a,b,c,d),T:(a,b,c,d)=>Qb(a,b,c,d,25,"touchcancel"),U:(a,b,c,d)=>Qb(a,b,c,d,23,"touchend"),V:(a,b,c,d)=>Qb(a,b,c,d,24,"touchmove"),W:(a,b,c,d)=>Qb(a,b,c,d,22,"touchstart"),O:(a,b,c,d)=>{mc(a,b,
c,d,31,"webglcontextlost");return 0},N:(a,b,c,d)=>{mc(a,b,c,d,32,"webglcontextrestored");return 0},_:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?nc(a,b,c,d):-1:-4,_a:(a,b)=>{b>>=2;b={alpha:!!y[b],depth:!!y[b+1],stencil:!!y[b+2],antialias:!!y[b+3],premultipliedAlpha:!!y[b+4],preserveDrawingBuffer:!!y[b+5],powerPreference:oc[y[b+6]],failIfMajorPerformanceCaveat:!!y[b+7],Nc:y[b+8],vd:y[b+9],Rc:y[b+10],hd:y[b+11],wd:y[b+12],yd:y[b+13]};a=K(a);return!a||b.hd?0:ic(a,b)},Ya:(a,b)=>{a=dc[a];b=b?E(x,
b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Rb(S);"OES_vertex_array_object"==b&&Sb(S);"WEBGL_draw_buffers"==b&&Vb(S);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Wb(S);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Xb(S);"WEBGL_multi_draw"==b&&(S.ld=S.getExtension("WEBGL_multi_draw"));return!!a.Hc.getExtension(b)},Za:a=>kc(a)?0:-5,la:()=>52,nb:()=>52,ib:function(){return 70},mb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var f=z[b>>2],l=z[b+4>>2];b+=8;for(var n=
0;n<l;n++){var p=x[f+n],r=pc[a];0===p||10===p?((1===a?na:q)(E(r,0)),r.length=0):r.push(p)}e+=l}z[d>>2]=e;return 0},j:function(a,b,c){const d=a?E(x,a):"";let e;try{e=window.indexedDB.open("chips",1)}catch(h){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+h)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");e.result.createObjectStore("store")};e.onsuccess=()=>{var h=e.result;let f;try{f=h.transaction(["store"],"readwrite")}catch(p){console.log("fs_js_load_snapshot: db.transaction failed with",
p);return}h=f.objectStore("store");let l=d+"_"+b,n=h.get(l);n.onsuccess=()=>{if(void 0!==n.result){let p=n.result.length;console.log("fs_js_load_snapshot:",l,"successfully loaded",p,"bytes");let r=Dc(p);x.set(n.result,r);Ec(c,r,p)}else Ec(c,0,0)};n.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",l)};f.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},fb:function(a,b,c,d){const e=a?E(x,a):
"";console.log("fs_js_save_snapshot: called with",e,b);let h;try{h=window.indexedDB.open("chips",1)}catch(f){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+f);return}h.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");h.result.createObjectStore("store")};h.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");let f=h.result.transaction(["store"],"readwrite");var l=f.objectStore("store");let n=e+"_"+b;l=l.put(x.subarray(c,c+d),n);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",
n,"successfully stored")};l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",n)};f.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};h.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},m:a=>S.activeTexture(a),xa:(a,b)=>{S.attachShader(O[a],Q[b])},b:(a,b)=>{35051==a?S.Pc=b:35052==a&&(S.Dc=b);S.bindBuffer(a,$b[b])},o:(a,b)=>{S.bindFramebuffer(a,ac[b])},Fa:(a,b)=>{S.bindRenderbuffer(a,bc[b])},l:(a,b)=>{S.bindSampler(a,R[b])},a:(a,b)=>{S.bindTexture(a,
P[b])},M:a=>{S.bindVertexArray(cc[a])},I:(a,b,c,d)=>S.blendColor(a,b,c,d),J:(a,b)=>S.blendEquationSeparate(a,b),K:(a,b,c,d)=>S.blendFuncSeparate(a,b,c,d),tb:(a,b,c,d,e,h,f,l,n,p)=>S.blitFramebuffer(a,b,c,d,e,h,f,l,n,p),Ha:(a,b,c,d)=>{2<=V.version?c&&b?S.bufferData(a,x,d,c,b):S.bufferData(a,b,d):S.bufferData(a,c?x.subarray(c,c+b):b,d)},t:(a,b,c,d)=>{2<=V.version?c&&S.bufferSubData(a,b,x,d,c):S.bufferSubData(a,b,x.subarray(d,d+c))},ra:a=>S.checkFramebufferStatus(a),Ob:(a,b,c,d)=>S.clearBufferfi(a,b,
c,d),pa:(a,b,c)=>{S.clearBufferfv(a,b,A,c>>2)},Mb:(a,b,c)=>{S.clearBufferiv(a,b,y,c>>2)},r:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},Sb:a=>{S.compileShader(Q[a])},Ba:(a,b,c,d,e,h,f,l)=>{2<=V.version?S.Dc||!f?S.compressedTexImage2D(a,b,c,d,e,h,f,l):S.compressedTexImage2D(a,b,c,d,e,h,x,l,f):S.compressedTexImage2D(a,b,c,d,e,h,l?x.subarray(l,l+f):null)},$b:(a,b,c,d,e,h,f,l,n)=>{S.Dc?S.compressedTexImage3D(a,b,c,d,e,h,f,l,n):S.compressedTexImage3D(a,b,c,d,e,h,f,x,n,l)},Yb:()=>{var a=gc(O),b=S.createProgram();
b.name=a;b.Kc=b.Ic=b.Jc=0;b.Oc=1;O[a]=b;return a},Ub:a=>{var b=gc(Q);Q[b]=S.createShader(a);return b},F:a=>S.cullFace(a),La:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=$b[d];e&&(S.deleteBuffer(e),e.name=0,$b[d]=null,d==S.Pc&&(S.Pc=0),d==S.Dc&&(S.Dc=0))}},e:(a,b)=>{for(var c=0;c<a;++c){var d=y[b+4*c>>2],e=ac[d];e&&(S.deleteFramebuffer(e),e.name=0,ac[d]=null)}},p:a=>{if(a){var b=O[a];b?(S.deleteProgram(b),b.name=0,O[a]=null):T||=1281}},D:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=bc[d];e&&
(S.deleteRenderbuffer(e),e.name=0,bc[d]=null)}},f:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=R[d];e&&(S.deleteSampler(e),e.name=0,R[d]=null)}},C:a=>{if(a){var b=Q[a];b?(S.deleteShader(b),Q[a]=null):T||=1281}},E:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=P[d];e&&(S.deleteTexture(e),e.name=0,P[d]=null)}},Ka:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2];S.deleteVertexArray(cc[d]);cc[d]=null}},x:a=>S.depthFunc(a),w:a=>{S.depthMask(!!a)},d:a=>S.disable(a),L:a=>{S.disableVertexAttribArray(a)},
wb:(a,b,c)=>{S.drawArrays(a,b,c)},xb:(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},qa:(a,b)=>{for(var c=qc[a],d=0;d<a;d++)c[d]=y[b+4*d>>2];S.drawBuffers(c)},yb:(a,b,c,d)=>{S.drawElements(a,b,c,d)},zb:(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},i:a=>S.enable(a),Jb:a=>{S.enableVertexAttribArray(a)},sa:(a,b,c,d)=>{S.framebufferRenderbuffer(a,b,c,bc[d])},q:(a,b,c,d,e)=>{S.framebufferTexture2D(a,b,c,P[d],e)},B:(a,b,c,d,e)=>{S.framebufferTextureLayer(a,b,P[c],d,e)},G:a=>S.frontFace(a),Ia:(a,b)=>{U(a,
b,"createBuffer",$b)},ta:(a,b)=>{U(a,b,"createFramebuffer",ac)},Ga:(a,b)=>{U(a,b,"createRenderbuffer",bc)},Zb:(a,b)=>{U(a,b,"createSampler",R)},Da:(a,b)=>{U(a,b,"createTexture",P)},Ta:(a,b)=>{U(a,b,"createVertexArray",cc)},Qb:(a,b)=>S.getAttribLocation(O[a],b?E(x,b):""),c:(a,b)=>sc(a,b),Vb:(a,b,c,d)=>{a=S.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(y[c>>2]=b)},wa:(a,b,c)=>{if(c)if(a>=Zb)T||=1281;else if(a=O[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),
y[c>>2]=a.length+1;else if(35719==b){if(!a.Kc)for(b=0;b<S.getProgramParameter(a,35718);++b)a.Kc=Math.max(a.Kc,S.getActiveUniform(a,b).name.length+1);y[c>>2]=a.Kc}else if(35722==b){if(!a.Ic)for(b=0;b<S.getProgramParameter(a,35721);++b)a.Ic=Math.max(a.Ic,S.getActiveAttrib(a,b).name.length+1);y[c>>2]=a.Ic}else if(35381==b){if(!a.Jc)for(b=0;b<S.getProgramParameter(a,35382);++b)a.Jc=Math.max(a.Jc,S.getActiveUniformBlockName(a,b).length+1);y[c>>2]=a.Jc}else y[c>>2]=S.getProgramParameter(a,b);else T||=1281},
Rb:(a,b,c,d)=>{a=S.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(y[c>>2]=b)},ua:(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),y[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(Q[a]),y[c>>2]=a?a.length+1:0):y[c>>2]=S.getShaderParameter(Q[a],b):T||=1281},Qa:(a,b)=>{if(2>V.version)return T||=1282,0;var c=ec[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=rc().map(uc),c=ec[a]=c,0>b||b>=c.length?(T||=
1281,0):c[b];default:return T||=1280,0}},u:(a,b)=>{b=b?E(x,b):"";if(a=O[a]){var c=a,d=c.Fc,e=c.cd,h;if(!d)for(c.Fc=d={},c.bd={},h=0;h<S.getProgramParameter(c,35718);++h){var f=S.getActiveUniform(c,h);var l=f.name;f=f.size;var n=vc(l);n=0<n?l.slice(0,n):l;var p=c.Oc;c.Oc+=f;e[n]=[f,p];for(l=0;l<f;++l)d[p]=l,c.bd[p++]=n}c=a.Fc;d=0;e=b;h=vc(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.cd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else T||=1281;return-1},sb:(a,
b,c)=>{for(var d=qc[b],e=0;e<b;e++)d[e]=y[c+4*e>>2];S.invalidateFramebuffer(a,d)},Xb:a=>{a=O[a];S.linkProgram(a);a.Fc=0;a.cd={}},Ra:(a,b)=>{3317==a&&(fc=b);S.pixelStorei(a,b)},H:(a,b)=>S.polygonOffset(a,b),vb:a=>S.readBuffer(a),Ea:(a,b,c,d,e)=>S.renderbufferStorageMultisample(a,b,c,d,e),ya:(a,b,c)=>{S.samplerParameterf(R[a],b,c)},g:(a,b,c)=>{S.samplerParameteri(R[a],b,c)},s:(a,b,c,d)=>S.scissor(a,b,c,d),Tb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=z[c+4*h>>2])?E(x,f,d?z[d+4*h>>2]:void 0):"";
e+=f}S.shaderSource(Q[a],e)},Pa:(a,b,c)=>S.stencilFunc(a,b,c),oa:(a,b,c,d)=>S.stencilFuncSeparate(a,b,c,d),v:a=>S.stencilMask(a),Oa:(a,b,c)=>S.stencilOp(a,b,c),na:(a,b,c,d)=>S.stencilOpSeparate(a,b,c,d),Aa:(a,b,c,d,e,h,f,l,n)=>{if(2<=V.version){if(S.Dc){S.texImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var p=wc(l);n>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);S.texImage2D(a,b,c,d,e,h,f,l,p,n);return}}p=n?xc(l,f,d,e,n):null;S.texImage2D(a,b,c,d,e,h,f,l,p)},_b:(a,b,c,d,e,h,f,l,n,p)=>{if(S.Dc)S.texImage3D(a,b,
c,d,e,h,f,l,n,p);else if(p){var r=wc(n);S.texImage3D(a,b,c,d,e,h,f,l,n,r,p>>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else S.texImage3D(a,b,c,d,e,h,f,l,n,null)},Ca:(a,b,c)=>S.texParameteri(a,b,c),rb:(a,b,c,d,e,h,f,l,n)=>{if(2<=V.version){if(S.Dc){S.texSubImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var p=wc(l);S.texSubImage2D(a,b,c,d,e,h,f,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}n=n?xc(l,f,e,h,n):null;S.texSubImage2D(a,b,c,d,e,h,f,l,n)},qb:(a,b,c,d,e,h,f,l,n,p,r)=>{if(S.Dc)S.texSubImage3D(a,b,c,
d,e,h,f,l,n,p,r);else if(r){var v=wc(p);S.texSubImage3D(a,b,c,d,e,h,f,l,n,p,v,r>>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else S.texSubImage3D(a,b,c,d,e,h,f,l,n,p,null)},Ib:(a,b,c)=>{if(2<=V.version)b&&S.uniform1fv(W(a),A,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);S.uniform1fv(W(a),d)}},va:(a,b)=>{S.uniform1i(W(a),b)},Eb:(a,b,c)=>{if(2<=V.version)b&&S.uniform1iv(W(a),y,c>>2,b);else{if(288>=b)for(var d=yc[b],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>
2,c+4*b>>2);S.uniform1iv(W(a),d)}},Hb:(a,b,c)=>{if(2<=V.version)b&&S.uniform2fv(W(a),A,c>>2,2*b);else{if(144>=b)for(var d=X[2*b],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);S.uniform2fv(W(a),d)}},Db:(a,b,c)=>{if(2<=V.version)b&&S.uniform2iv(W(a),y,c>>2,2*b);else{if(144>=b)for(var d=yc[2*b],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);S.uniform2iv(W(a),d)}},Gb:(a,b,c)=>{if(2<=V.version)b&&S.uniform3fv(W(a),A,c>>
2,3*b);else{if(96>=b)for(var d=X[3*b],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);S.uniform3fv(W(a),d)}},Cb:(a,b,c)=>{if(2<=V.version)b&&S.uniform3iv(W(a),y,c>>2,3*b);else{if(96>=b)for(var d=yc[3*b],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);S.uniform3iv(W(a),d)}},Fb:(a,b,c)=>{if(2<=V.version)b&&S.uniform4fv(W(a),A,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=A;c>>=2;
for(var h=0;h<4*b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=A.subarray(c>>2,c+16*b>>2);S.uniform4fv(W(a),d)}},Bb:(a,b,c)=>{if(2<=V.version)b&&S.uniform4iv(W(a),y,c>>2,4*b);else{if(72>=b)for(var d=yc[4*b],e=0;e<4*b;e+=4)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2],d[e+3]=y[c+(4*e+12)>>2];else d=y.subarray(c>>2,c+16*b>>2);S.uniform4iv(W(a),d)}},Ab:(a,b,c,d)=>{if(2<=V.version)b&&S.uniformMatrix4fv(W(a),!!c,A,d>>2,16*b);else{if(18>=b){var e=X[16*b],
h=A;d>>=2;for(var f=0;f<16*b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=A.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(W(a),!!c,e)}},h:a=>{a=O[a];S.useProgram(a);S.gd=a},Kb:(a,b)=>{S.vertexAttribDivisor(a,b)},Lb:(a,b,c,d,e,h)=>{S.vertexAttribPointer(a,b,c,!!d,e,h)},n:(a,b,c,d)=>S.viewport(a,
b,c,d),Xa:function(){g.Vc=a=>{0!=Fc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Vc)},Sa:function(){g.ad=a=>{const b=a.clipboardData.getData("text");rb(()=>{const c=Ac(b);Gc(c)})};window.addEventListener("paste",g.ad)},Ja:function(a){g.zd=[];a=a?E(x,a):"";a=document.getElementById(a);g.Wc=b=>{b.stopPropagation();b.preventDefault()};g.Xc=b=>{b.stopPropagation();b.preventDefault()};g.Yc=b=>{b.stopPropagation();b.preventDefault()};g.Zc=b=>{b.stopPropagation();b.preventDefault();
const c=b.dataTransfer.files;g.$c=c;Hc(c.length);for(let e=0;e<c.length;e++)rb(()=>{const h=Ac(c[e].name);Ic(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Jc(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.Wc,!1);a.addEventListener("dragleave",g.Xc,!1);a.addEventListener("dragover",g.Yc,!1);a.addEventListener("drop",g.Zc,!1)},lb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},ac:function(a){const b=
g.$c;return 0>a||a>=b.length?0:b[a].size},Wb:function(a,b,c,d,e){const h=new FileReader;h.onload=f=>{f=f.target.result;f.byteLength>d?Kc(a,0,1,b,0,c,d,e):(x.set(new Uint8Array(f),c),Kc(a,1,0,b,f.byteLength,c,d,e))};h.onerror=()=>{Kc(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(g.$c[a])},Nb:function(a){a=a?E(x,a):"";g.Ec=document.getElementById(a);g.Ec||console.log("sokol_app.h: invalid target:"+a);g.Ec.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Wa:function(){window.removeEventListener("beforeunload",
g.Vc)},Na:function(){window.removeEventListener("paste",g.ad)},Pb:function(a){a=a?E(x,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.Wc);a.removeEventListener("dragleave",g.Xc);a.removeEventListener("dragover",g.Yc);a.removeEventListener("drop",g.Zc)},A:function(){g.Ec&&g.Ec.requestPointerLock&&g.Ec.requestPointerLock()},ub:function(a,b){if(g.Ec){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;
case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.Ec.style.cursor=a}},hb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(x.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";
a.href=d.toDataURL();document.head.appendChild(a)},Ma:function(a){a=a?E(x,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},bb:function(){const a=(new URLSearchParams(window.location.search)).entries();
for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];rb(()=>{const e=Ac(c),h=Ac(d);Lc(e,h)})}},db:function(){return g.Cc?g.Cc.bufferSize:0},gb:function(a,b,c){g.xc=null;g.Cc=null;"undefined"!==typeof AudioContext?g.xc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.xc=null,console.log("sokol_audio.h: no WebAudio support"));return g.xc?(console.log("sokol_audio.h: sample rate ",g.xc.sampleRate),g.Cc=g.xc.createScriptProcessor(c,0,b),g.Cc.onaudioprocess=d=>{const e=d.outputBuffer.length,
h=Mc(e);if(h){const f=d.outputBuffer.numberOfChannels;for(let l=0;l<f;l++){const n=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)n[p]=A[(h>>2)+(f*p+l)]}}},g.Cc.connect(g.xc.destination),a=()=>{g.xc&&"suspended"===g.xc.state&&g.xc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},eb:function(){return g.xc?g.xc.sampleRate:0},ka:function(){const a=g.xc;null!==a&&(g.Cc&&g.Cc.disconnect(),
a.close(),g.xc=null,g.Cc=null)},cb:function(){if(g.xc)return"suspended"===g.xc.state?1:0},y:function(a,b,c,d,e,h){b=b?E(x,b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const l=0<d;l&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!l){const n=new Uint8Array(f.response),p=n.length;p<=h?(x.set(n,e),Nc(a,d,p)):Oc(a)}else Pc(a,f.status)};f.send()},ja:function(a,b){b=
b?E(x,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");Qc(a,d)}else Pc(a,c.status)};c.send()},za:function(){return navigator.userAgent.includes("Macintosh")?1:0},ia:function(a,b){b=b?E(x,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;oa=Z.bc;sa();
Ib=Z.tc;ua.unshift(Z.cc);C--;g.monitorRunDependencies?.(C);0==C&&(null!==ya&&(clearInterval(ya),ya=null),za&&(c=za,za=null,c()));return Z}var b={a:Rc};C++;g.monitorRunDependencies?.(C);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return q(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ga(b,function(c){a(c.instance)});return{}}(),N=a=>(N=Z.dc)(a),Dc=g._fs_emsc_alloc=a=>(Dc=g._fs_emsc_alloc=Z.ec)(a),Ec=g._fs_emsc_load_snapshot_callback=(a,b,c)=>(Ec=g._fs_emsc_load_snapshot_callback=
Z.fc)(a,b,c),Gc=g.__sapp_emsc_onpaste=a=>(Gc=g.__sapp_emsc_onpaste=Z.gc)(a),Fc=g.__sapp_html5_get_ask_leave_site=()=>(Fc=g.__sapp_html5_get_ask_leave_site=Z.hc)(),Hc=g.__sapp_emsc_begin_drop=a=>(Hc=g.__sapp_emsc_begin_drop=Z.ic)(a),Ic=g.__sapp_emsc_drop=(a,b)=>(Ic=g.__sapp_emsc_drop=Z.jc)(a,b),Jc=g.__sapp_emsc_end_drop=(a,b,c)=>(Jc=g.__sapp_emsc_end_drop=Z.kc)(a,b,c),Kc=g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,f,l)=>(Kc=g.__sapp_emsc_invoke_fetch_cb=Z.lc)(a,b,c,d,e,h,f,l),Sc=g._main=(a,b)=>(Sc=
g._main=Z.mc)(a,b),Mc=g.__saudio_emsc_pull=a=>(Mc=g.__saudio_emsc_pull=Z.nc)(a),Lc=g.__sargs_add_kvp=(a,b)=>(Lc=g.__sargs_add_kvp=Z.oc)(a,b),Qc=g.__sfetch_emsc_head_response=(a,b)=>(Qc=g.__sfetch_emsc_head_response=Z.pc)(a,b),Nc=g.__sfetch_emsc_get_response=(a,b,c)=>(Nc=g.__sfetch_emsc_get_response=Z.qc)(a,b,c),Pc=g.__sfetch_emsc_failed_http_status=(a,b)=>(Pc=g.__sfetch_emsc_failed_http_status=Z.rc)(a,b),Oc=g.__sfetch_emsc_failed_buffer_too_small=a=>(Oc=g.__sfetch_emsc_failed_buffer_too_small=Z.sc)(a),
qb=a=>(qb=Z.uc)(a),zc=a=>(zc=Z.vc)(a),pb=()=>(pb=Z.wc)();g.___start_em_js=64452;g.___stop_em_js=77004;var Tc;za=function Uc(){Tc||Vc();Tc||(za=Uc)};function Wc(a=[]){var b=Sc;a.unshift(ca);var c=a.length,d=zc(4*(c+1)),e=d;a.forEach(f=>{z[e>>2]=Ac(f);e+=4});z[e>>2]=0;try{var h=b(c,d);bb(h)}catch(f){$a(f)}}
function Vc(){var a=ba;function b(){if(!Tc&&(Tc=!0,g.calledRun=!0,!u)){Ha(ua);Ha(va);if(g.onRuntimeInitialized)g.onRuntimeInitialized();Xc&&Wc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();wa.unshift(c)}Ha(wa)}}if(!(0<C)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)xa();Ha(ta);0<C||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Xc=!0;g.noInitialRun&&(Xc=!1);Vc();
