var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,da=Object.assign({},g),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs"),ka=require("path");k=__dirname+"/";ja=a=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a)};ia=a=>{a=la(a)?new URL(a):ka.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!g.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof ma||a.context instanceof ma))throw a;
});ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?"":k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=a=>la(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{(200==
d.status||0==d.status&&d.response)&&c(d.response);b(d.status)};d.onerror=b;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var na=g.print||console.log.bind(console),n=g.printErr||console.error.bind(console);Object.assign(g,da);da=null;g.arguments&&(ea=g.arguments);g.thisProgram&&(fa=g.thisProgram);g.quit&&(ha=g.quit);var q;g.wasmBinary&&(q=g.wasmBinary);var oa,r=!1,u,v,x,pa,qa,y,z,A,B;
function ra(){var a=oa.buffer;g.HEAP8=v=new Int8Array(a);g.HEAP16=pa=new Int16Array(a);g.HEAPU8=x=new Uint8Array(a);g.HEAPU16=qa=new Uint16Array(a);g.HEAP32=y=new Int32Array(a);g.HEAPU32=z=new Uint32Array(a);g.HEAPF32=A=new Float32Array(a);g.HEAPF64=B=new Float64Array(a)}var sa=[],ta=[],ua=[],va=[];function wa(){var a=g.preRun.shift();sa.unshift(a)}var C=0,xa=null,D=null;
function ya(a){g.onAbort?.(a);a="Aborted("+a+")";n(a);r=!0;u=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var za=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),Aa;function Ba(a){if(a==Aa&&q)return new Uint8Array(q);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}function Ca(a){return q?Promise.resolve().then(()=>Ba(a)):ia(a).then(b=>new Uint8Array(b),()=>Ba(a))}
function Da(a,b,c){return Ca(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{n(`failed to asynchronously prepare wasm: ${d}`);ya(d)})}function Ea(a,b){var c=Aa;q||"function"!=typeof WebAssembly.instantiateStreaming||za(c)||la(c)||ca||"function"!=typeof fetch?Da(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){n(`wasm streaming compile failed: ${e}`);n("falling back to ArrayBuffer instantiation");return Da(c,a,b)}))}
function ma(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Fa=a=>{for(;0<a.length;)a.shift()(g)},Ga=g.noExitRuntime||!0,Ha="undefined"!=typeof TextDecoder?new TextDecoder:void 0,E=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ha)return Ha.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|
e&1023))}}else d+=String.fromCharCode(e)}return d},Ra=(a,b)=>{Ia=a;Ja=b;if(Ka)if(La||=!0,0==a)F=function(){var d=Math.max(0,Ma+b-Na())|0;setTimeout(Oa,d)};else if(1==a)F=function(){Pa(Oa)};else if(2==a){if("undefined"==typeof Qa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=function(d){c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);
postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Qa=setImmediate;F=function(){Qa(Oa)}}},Na;Na=()=>performance.now();
var Za=(a,b,c,d,e)=>{Ka=a;Sa=d;var h=G;La=!1;Oa=function(){if(!r)if(0<Ta.length){var f=Ta.shift();f.ud(f.pd);if(Ua){var l=Ua,m=0==l%1?l-1:Math.floor(l);Ua=f.rd?m:(8*l+(m+.5))/9}g.setStatus&&(f=g.statusMessage||"Please wait...",l=Ua,m=Va.td,l?l<m?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(f):g.setStatus(""));h<G||setTimeout(Oa,0)}else if(!(h<G))if(Wa=Wa+1|0,1==Ia&&1<Ja&&0!=Wa%Ja)F();else{0==Ia&&(Ma=Na());if(!(r||g.preMainLoop&&!1===g.preMainLoop())){if(!r)try{if(a(),!Ga)try{u=
f=u,Xa(f)}catch(p){Ya(p)}}catch(p){Ya(p)}g.postMainLoop?.()}h<G||("object"==typeof SDL&&SDL.audio?.yd?.(),F())}};e||(b&&0<b?Ra(0,1E3/b):Ra(1,1),F());if(c)throw"unwind";},Ya=a=>{a instanceof ma||"unwind"==a||ha(1,a)},Xa=a=>{u=a;Ga||(g.onExit?.(a),r=!0);ha(a,new ma(a))},$a=a=>{u=a;Xa(a)},La=!1,F=null,G=0,Ka=null,Sa=0,Ia=0,Ja=0,Wa=0,Ta=[];function ab(){F=null;G++}var Va={},Ma,Oa,Ua,bb=!1,cb=!1,db=[];
function eb(){function a(){cb=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}if(!fb){fb=!0;var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!cb&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}var gb=!1,hb=void 0,H=void 0;
function ib(){if(!bb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var jb=0;function Pa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===jb)jb=b+1E3/60;else for(;b+2>=jb;)jb+=1E3/60;setTimeout(a,Math.max(jb-b,0))}}var kb=[];function lb(){var a=g.canvas;kb.forEach(b=>b(a.width,a.height))}
function mb(a,b,c){b&&c?(a.nd=b,a.kd=c):(b=a.nd,c=a.kd);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var h=Math.min(screen.width/d,screen.height/e);d=Math.round(d*h);e=Math.round(e*
h)}H?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Qa,fb,nb=0,ob=[];
function pb(){if(navigator.userActivation?navigator.userActivation.isActive:nb&&qb.Mc)for(var a=0;a<ob.length;++a){var b=ob[a];ob.splice(a,1);--a;b.Bd(...b.qd)}}var I=[];function rb(a){var b=I[a];b.target.removeEventListener(b.zc,b.Uc,b.Ac);I.splice(a,1)}function J(a){if(!a.target)return-4;if(a.Bc)a.Uc=function(c){++nb;qb=a;pb();a.Cc(c);pb();--nb},a.target.addEventListener(a.zc,a.Uc,a.Ac),I.push(a);else for(var b=0;b<I.length;++b)I[b].target==a.target&&I[b].zc==a.zc&&rb(b--);return 0}
function sb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var qb,tb,ub,vb,wb,xb,yb,zb,Ab=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?E(x,a):"":a;return Ab[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Bb=a=>0>Ab.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Cb=[],Db,L=a=>{var b=Cb[a];b||(a>=Cb.length&&(Cb.length=a+1),Cb[a]=b=Db.get(a));return b},M=(a,b,c)=>{var d=x;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var l=
a.charCodeAt(++h);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},Eb=(a,b,c,d,e,h)=>{tb||=N(256);a={target:K(a),zc:h,Bc:d,Cc:(f=event)=>{var l=f.target.id?f.target.id:"",m=tb;M(sb(f.target),m+0,128);M(l,m+128,128);L(d)(e,m,b)&&f.preventDefault()},Ac:c};return J(a)},Fb=(a,
b,c,d,e,h)=>{ub||=N(160);a={target:K(a),zc:h,Bc:d,Cc:f=>{var l=ub;B[l>>3]=f.timeStamp;var m=l>>2;y[m+2]=f.location;v[m+12]=f.ctrlKey;v[m+13]=f.shiftKey;v[m+14]=f.altKey;v[m+15]=f.metaKey;v[m+16]=f.repeat;y[m+5]=f.charCode;y[m+6]=f.keyCode;y[m+7]=f.which;M(f.key||"",l+32,32);M(f.code||"",l+64,32);M(f.char||"",l+96,32);M(f.locale||"",l+128,32);L(d)(e,l,b)&&f.preventDefault()},Ac:c};return J(a)},Gb=(a,b,c)=>{B[a>>3]=b.timeStamp;a>>=2;y[a+2]=b.screenX;y[a+3]=b.screenY;y[a+4]=b.clientX;y[a+5]=b.clientY;
v[a+24]=b.ctrlKey;v[a+25]=b.shiftKey;v[a+26]=b.altKey;v[a+27]=b.metaKey;pa[2*a+14]=b.button;pa[2*a+15]=b.buttons;y[a+8]=b.movementX;y[a+9]=b.movementY;c=Bb(c);y[a+10]=b.clientX-(c.left|0);y[a+11]=b.clientY-(c.top|0)},Hb=(a,b,c,d,e,h)=>{vb||=N(64);a=K(a);return J({target:a,Mc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,zc:h,Bc:d,Cc:(f=event)=>{Gb(vb,f,a);L(d)(e,vb,b)&&f.preventDefault()},Ac:c})},Ib=(a,b,c,d,e)=>{wb||=N(257);return J({target:a,zc:e,Bc:d,Cc:(h=event)=>{var f=wb,l=document.pointerLockElement||
document.Hc||document.Qc||document.gd;v[f]=!!l;var m=l?.id||"";M(sb(l),f+1,128);M(m,f+129,128);L(d)(20,f,b)&&h.preventDefault()},Ac:c})},Jb=(a,b,c,d,e)=>J({target:a,zc:e,Bc:d,Cc:(h=event)=>{L(d)(38,0,b)&&h.preventDefault()},Ac:c}),Kb=(a,b,c,d)=>{xb||=N(36);a=K(a);return J({target:a,zc:"resize",Bc:d,Cc:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=xb;y[f>>2]=0;y[f+4>>2]=h.clientWidth;y[f+8>>2]=h.clientHeight;y[f+12>>2]=innerWidth;y[f+16>>2]=innerHeight;y[f+20>>2]=outerWidth;y[f+24>>2]=
outerHeight;y[f+28>>2]=pageXOffset|0;y[f+32>>2]=pageYOffset|0;L(d)(10,f,b)&&e.preventDefault()}}},Ac:c})},Lb=(a,b,c,d,e,h)=>{yb||=N(1552);a=K(a);return J({target:a,Mc:"touchstart"==h||"touchend"==h,zc:h,Bc:d,Cc:f=>{for(var l,m={},p=f.touches,t=0;t<p.length;++t)l=p[t],l.Vc=l.Wc=0,m[l.identifier]=l;for(t=0;t<f.changedTouches.length;++t)l=f.changedTouches[t],l.Vc=1,m[l.identifier]=l;for(t=0;t<f.targetTouches.length;++t)m[f.targetTouches[t].identifier].Wc=1;p=yb;B[p>>3]=f.timeStamp;var w=p>>2;v[w+12]=
f.ctrlKey;v[w+13]=f.shiftKey;v[w+14]=f.altKey;v[w+15]=f.metaKey;w+=4;var Pb=Bb(a),Qb=0;for(t in m)if(l=m[t],y[w]=l.identifier,y[w+1]=l.screenX,y[w+2]=l.screenY,y[w+3]=l.clientX,y[w+4]=l.clientY,y[w+5]=l.pageX,y[w+6]=l.pageY,v[w+28]=l.Vc,v[w+29]=l.Wc,y[w+8]=l.clientX-(Pb.left|0),y[w+9]=l.clientY-(Pb.top|0),w+=12,31<++Qb)break;y[p+8>>2]=Qb;L(d)(e,p,b)&&f.preventDefault()},Ac:c})},Mb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},Nb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Ob=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Rb=a=>{a.sd=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
Sb=a=>{a.vd=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Tb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Ub=1,Vb=[],O=[],Wb=[],Xb=[],P=[],Q=[],Yb=[],Zb=[],R=[],$b={},ac=4,bc=0,cc=a=>{for(var b=Ub++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=S[c](),f=h&&cc(d);h?(h.name=f,d[f]=h):T||=1282;y[b+4*e>>2]=f}},ec=(a,b)=>{a.Hc||(a.Hc=a.getContext,a.getContext=function(d,e){e=a.Hc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Oc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
dc(c,b):0},dc=(a,b)=>{var c=cc(Zb),d={handle:c,attributes:b,version:b.Oc,Ic:a};a.canvas&&(a.canvas.od=d);Zb[c]=d;("undefined"==typeof b.Tc||b.Tc)&&fc(d);return c},gc=a=>{V=Zb[a];g.Nc=S=V?.Ic;return!(a&&!S)},fc=a=>{a||=V;if(!a.ld){a.ld=!0;var b=a.Ic;Mb(b);Nb(b);Ob(b);Rb(b);Sb(b);2<=a.version&&(b.Sc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Sc)b.Sc=b.getExtension("EXT_disjoint_timer_query");b.md=b.getExtension("WEBGL_multi_draw");Tb(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},hc={},T,V,ic=(a,b,c,d,e,h)=>{a={target:K(a),zc:h,Bc:d,Cc:(f=event)=>{L(d)(e,0,b)&&f.preventDefault()},Ac:c};J(a)},jc=(a,b,c,d)=>{zb||=N(96);return J({target:a,Mc:!0,zc:"wheel",Bc:d,Cc:(e=event)=>{var h=zb;Gb(h,e,a);B[h+64>>3]=e.deltaX;B[h+72>>3]=e.deltaY;B[h+80>>3]=e.deltaZ;y[h+88>>2]=e.deltaMode;L(d)(9,h,b)&&e.preventDefault()},Ac:c})},kc=["default","low-power","high-performance"],lc=[null,[],[]],mc=[];
function nc(){var a=Tb(S);return a=a.concat(a.map(b=>"GL_"+b))}
var oc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=nc().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)y[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}y[b>>2]=c}else T||=1281},pc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},qc=a=>{var b=pc(a)+1,c=N(b);c&&M(a,c,b);return c},rc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),sc=a=>{a-=5120;return 0==a?v:1==a?x:2==a?pa:4==a?y:6==a?A:5==a||28922==a||28520==a||30779==a||30782==a?z:qa},tc=(a,b,c,d,e)=>{a=sc(a);b=d*((bc||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+ac-1&-ac);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=S.hd;if(b){var c=b.Gc[a];"number"==typeof c&&(b.Gc[a]=c=S.getUniformLocation(b,b.dd[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],uc=[],wc=a=>{var b=pc(a)+1,c=vc(b);M(a,c,b);return c},zc=a=>{var b=xc();a();yc(b)};
g.requestFullscreen=function(a,b){function c(){bb=!1;var h=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===h?(d.exitFullscreen=ib,hb&&d.requestPointerLock(),bb=!0,H?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>2]|8388608),mb(g.canvas),lb()):mb(d)):(h.parentNode.insertBefore(d,h),h.parentNode.removeChild(h),H?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>
2]&-8388609),mb(g.canvas),lb()):mb(d));g.onFullScreen?.(bb);g.onFullscreen?.(bb)}hb=a;H=b;"undefined"==typeof hb&&(hb=!0);"undefined"==typeof H&&(H=!1);var d=g.canvas;gb||(gb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};g.requestAnimationFrame=Pa;g.setCanvasSize=function(a,b,c){mb(g.canvas,a,b);c||lb()};g.pauseMainLoop=ab;g.resumeMainLoop=function(){G++;var a=Ia,b=Ja,c=Ka;Ka=null;Za(c,0,!1,Sa,!0);Ra(a,b);F()};
g.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};g.createContext=function(a,b,c,d){if(b&&g.Nc&&a==g.canvas)return g.Nc;var e;if(b){var h={antialias:!1,alpha:!1,Oc:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var f in d)h[f]=d[f];if("undefined"!=typeof hc&&(e=ec(a,h)))var l=Zb[e].Ic}else l=a.getContext("2d");if(!l)return null;c&&(g.Nc=l,b&&gc(e),g.Cd=b,db.forEach(m=>m()),eb());return l};
for(var S,Y=0;32>Y;++Y)mc.push(Array(Y));var Ac=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=Ac.subarray(0,Y);var Bc=new Int32Array(288);for(Y=0;288>=Y;++Y)uc[Y]=Bc.subarray(0,Y);
var Qc={ma:function(){return 0},nb:function(){return 0},ob:function(){},pb:()=>{ya("")},jb:(a,b,c)=>x.copyWithin(a,b,b+c),Ua:()=>{ab();Ka=null},fa:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ha:(a,b,c)=>{a=K(a);if(!a)return-4;a=Bb(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},y:Na,Va:()=>performance.now(),$a:(a,b)=>{function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ib:a=>{var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*
(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-oa.buffer.byteLength+65535)/65536;try{oa.grow(e);ra();var h=1;break a}catch(f){}h=void 0}if(h)return!0}return!1},P:(a,b,c,d)=>Eb(a,b,c,d,12,"blur"),ea:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},Q:(a,b,c,d)=>Eb(a,b,c,d,13,"focus"),Z:(a,b,c,d)=>Fb(a,b,c,d,2,"keydown"),X:(a,b,c,d)=>Fb(a,b,c,d,1,"keypress"),Y:(a,b,c,d)=>Fb(a,b,c,d,3,"keyup"),ab:(a,b,c)=>{a=L(a);Za(a,
b,c)},da:(a,b,c,d)=>Hb(a,b,c,d,5,"mousedown"),aa:(a,b,c,d)=>Hb(a,b,c,d,33,"mouseenter"),$:(a,b,c,d)=>Hb(a,b,c,d,34,"mouseleave"),ba:(a,b,c,d)=>Hb(a,b,c,d,8,"mousemove"),ca:(a,b,c,d)=>Hb(a,b,c,d,6,"mouseup"),S:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Hc||document.body.Qc||document.body.gd))return-1;a=K(a);if(!a)return-4;Ib(a,b,c,d,"mozpointerlockchange");Ib(a,b,c,d,"webkitpointerlockchange");Ib(a,b,c,d,"mspointerlockchange");return Ib(a,b,c,d,"pointerlockchange")},
R:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.Hc||document.body.Qc||document.body.gd))return-1;a=K(a);if(!a)return-4;Jb(a,b,c,d,"mozpointerlockerror");Jb(a,b,c,d,"webkitpointerlockerror");Jb(a,b,c,d,"mspointerlockerror");return Jb(a,b,c,d,"pointerlockerror")},ga:(a,b,c,d)=>Kb(a,b,c,d),T:(a,b,c,d)=>Lb(a,b,c,d,25,"touchcancel"),U:(a,b,c,d)=>Lb(a,b,c,d,23,"touchend"),V:(a,b,c,d)=>Lb(a,b,c,d,24,"touchmove"),W:(a,b,c,d)=>Lb(a,b,c,d,22,"touchstart"),O:(a,b,c,d)=>{ic(a,b,
c,d,31,"webglcontextlost");return 0},N:(a,b,c,d)=>{ic(a,b,c,d,32,"webglcontextrestored");return 0},_:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?jc(a,b,c,d):-1:-4,_a:(a,b)=>{var c=b>>2;b={alpha:!!v[b+0],depth:!!v[b+1],stencil:!!v[b+2],antialias:!!v[b+3],premultipliedAlpha:!!v[b+4],preserveDrawingBuffer:!!v[b+5],powerPreference:kc[y[c+2]],failIfMajorPerformanceCaveat:!!v[b+12],Oc:y[c+4],wd:y[c+5],Tc:v[b+24],jd:v[b+25],xd:y[c+7],zd:v[b+32]};a=K(a);return!a||b.jd?0:ec(a,b)},Ya:(a,b)=>{a=Zb[a];
b=b?E(x,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Mb(S);"OES_vertex_array_object"==b&&Nb(S);"WEBGL_draw_buffers"==b&&Ob(S);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Rb(S);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Sb(S);"WEBGL_multi_draw"==b&&(S.md=S.getExtension("WEBGL_multi_draw"));return!!a.Ic.getExtension(b)},Za:a=>gc(a)?0:-5,la:()=>52,mb:()=>52,hb:function(){return 70},lb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var f=z[b>>2],l=z[b+4>>2];b+=
8;for(var m=0;m<l;m++){var p=x[f+m],t=lc[a];0===p||10===p?((1===a?na:n)(E(t,0)),t.length=0):t.push(p)}e+=l}z[d>>2]=e;return 0},k:function(a,b,c){const d=a?E(x,a):"";let e;try{e=window.indexedDB.open("chips",1)}catch(h){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+h)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");e.result.createObjectStore("store")};e.onsuccess=()=>{var h=e.result;let f;try{f=h.transaction(["store"],"readwrite")}catch(p){console.log("fs_js_load_snapshot: db.transaction failed with",
p);return}h=f.objectStore("store");let l=d+"_"+b,m=h.get(l);m.onsuccess=()=>{if(void 0!==m.result){let p=m.result.length;console.log("fs_js_load_snapshot:",l,"successfully loaded",p,"bytes");let t=Cc(p);x.set(m.result,t);Dc(c,t,p)}else Dc(c,0,0)};m.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",l)};f.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},bc:function(a,b,c,d){const e=a?E(x,a):
"";console.log("fs_js_save_snapshot: called with",e,b);let h;try{h=window.indexedDB.open("chips",1)}catch(f){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+f);return}h.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");h.result.createObjectStore("store")};h.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");let f=h.result.transaction(["store"],"readwrite");var l=f.objectStore("store");let m=e+"_"+b;l=l.put(x.subarray(c,c+d),m);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",
m,"successfully stored")};l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",m)};f.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};h.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},m:a=>S.activeTexture(a),xa:(a,b)=>{S.attachShader(O[a],Q[b])},b:(a,b)=>{35051==a?S.Rc=b:35052==a&&(S.Ec=b);S.bindBuffer(a,Vb[b])},a:(a,b,c)=>{S.bindBufferBase(a,b,Vb[c])},o:(a,b)=>{S.bindFramebuffer(a,Wb[b])},Fa:(a,b)=>{S.bindRenderbuffer(a,Xb[b])},l:(a,b)=>
{S.bindSampler(a,R[b])},c:(a,b)=>{S.bindTexture(a,P[b])},M:a=>{S.bindVertexArray(Yb[a])},I:(a,b,c,d)=>S.blendColor(a,b,c,d),J:(a,b)=>S.blendEquationSeparate(a,b),K:(a,b,c,d)=>S.blendFuncSeparate(a,b,c,d),tb:(a,b,c,d,e,h,f,l,m,p)=>S.blitFramebuffer(a,b,c,d,e,h,f,l,m,p),Ha:(a,b,c,d)=>{2<=V.version?c&&b?S.bufferData(a,x,d,c,b):S.bufferData(a,b,d):S.bufferData(a,c?x.subarray(c,c+b):b,d)},C:(a,b,c,d)=>{2<=V.version?c&&S.bufferSubData(a,b,x,d,c):S.bufferSubData(a,b,x.subarray(d,d+c))},ra:a=>S.checkFramebufferStatus(a),
Ob:(a,b,c,d)=>S.clearBufferfi(a,b,c,d),pa:(a,b,c)=>{S.clearBufferfv(a,b,A,c>>2)},Nb:(a,b,c)=>{S.clearBufferiv(a,b,y,c>>2)},r:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},Sb:a=>{S.compileShader(Q[a])},Ba:(a,b,c,d,e,h,f,l)=>{2<=V.version?S.Ec||!f?S.compressedTexImage2D(a,b,c,d,e,h,f,l):S.compressedTexImage2D(a,b,c,d,e,h,x,l,f):S.compressedTexImage2D(a,b,c,d,e,h,l?x.subarray(l,l+f):null)},$b:(a,b,c,d,e,h,f,l,m)=>{S.Ec?S.compressedTexImage3D(a,b,c,d,e,h,f,l,m):S.compressedTexImage3D(a,b,c,d,e,h,f,x,m,l)},
Yb:()=>{var a=cc(O),b=S.createProgram();b.name=a;b.Lc=b.Jc=b.Kc=0;b.Pc=1;O[a]=b;return a},Ub:a=>{var b=cc(Q);Q[b]=S.createShader(a);return b},F:a=>S.cullFace(a),La:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=Vb[d];e&&(S.deleteBuffer(e),e.name=0,Vb[d]=null,d==S.Rc&&(S.Rc=0),d==S.Ec&&(S.Ec=0))}},f:(a,b)=>{for(var c=0;c<a;++c){var d=y[b+4*c>>2],e=Wb[d];e&&(S.deleteFramebuffer(e),e.name=0,Wb[d]=null)}},p:a=>{if(a){var b=O[a];b?(S.deleteProgram(b),b.name=0,O[a]=null):T||=1281}},D:(a,b)=>{for(var c=
0;c<a;c++){var d=y[b+4*c>>2],e=Xb[d];e&&(S.deleteRenderbuffer(e),e.name=0,Xb[d]=null)}},g:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=R[d];e&&(S.deleteSampler(e),e.name=0,R[d]=null)}},B:a=>{if(a){var b=Q[a];b?(S.deleteShader(b),Q[a]=null):T||=1281}},E:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=P[d];e&&(S.deleteTexture(e),e.name=0,P[d]=null)}},Ka:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2];S.deleteVertexArray(Yb[d]);Yb[d]=null}},w:a=>S.depthFunc(a),v:a=>{S.depthMask(!!a)},e:a=>S.disable(a),
L:a=>{S.disableVertexAttribArray(a)},wb:(a,b,c)=>{S.drawArrays(a,b,c)},xb:(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},qa:(a,b)=>{for(var c=mc[a],d=0;d<a;d++)c[d]=y[b+4*d>>2];S.drawBuffers(c)},yb:(a,b,c,d)=>{S.drawElements(a,b,c,d)},zb:(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},j:a=>S.enable(a),Kb:a=>{S.enableVertexAttribArray(a)},sa:(a,b,c,d)=>{S.framebufferRenderbuffer(a,b,c,Xb[d])},q:(a,b,c,d,e)=>{S.framebufferTexture2D(a,b,c,P[d],e)},A:(a,b,c,d,e)=>{S.framebufferTextureLayer(a,b,P[c],d,
e)},G:a=>S.frontFace(a),Ia:(a,b)=>{U(a,b,"createBuffer",Vb)},ta:(a,b)=>{U(a,b,"createFramebuffer",Wb)},Ga:(a,b)=>{U(a,b,"createRenderbuffer",Xb)},Zb:(a,b)=>{U(a,b,"createSampler",R)},Da:(a,b)=>{U(a,b,"createTexture",P)},Ta:(a,b)=>{U(a,b,"createVertexArray",Yb)},Qb:(a,b)=>S.getAttribLocation(O[a],b?E(x,b):""),d:(a,b)=>oc(a,b),Vb:(a,b,c,d)=>{a=S.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(y[c>>2]=b)},wa:(a,b,c)=>{if(c)if(a>=Ub)T||=1281;else if(a=O[a],35716==b)a=S.getProgramInfoLog(a),
null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b){if(!a.Lc)for(b=0;b<S.getProgramParameter(a,35718);++b)a.Lc=Math.max(a.Lc,S.getActiveUniform(a,b).name.length+1);y[c>>2]=a.Lc}else if(35722==b){if(!a.Jc)for(b=0;b<S.getProgramParameter(a,35721);++b)a.Jc=Math.max(a.Jc,S.getActiveAttrib(a,b).name.length+1);y[c>>2]=a.Jc}else if(35381==b){if(!a.Kc)for(b=0;b<S.getProgramParameter(a,35382);++b)a.Kc=Math.max(a.Kc,S.getActiveUniformBlockName(a,b).length+1);y[c>>2]=a.Kc}else y[c>>2]=S.getProgramParameter(a,
b);else T||=1281},Rb:(a,b,c,d)=>{a=S.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(y[c>>2]=b)},ua:(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),y[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(Q[a]),y[c>>2]=a?a.length+1:0):y[c>>2]=S.getShaderParameter(Q[a],b):T||=1281},Qa:(a,b)=>{if(2>V.version)return T||=1282,0;var c=$b[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=nc().map(qc),c=$b[a]=c,0>b||
b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},t:(a,b)=>{b=b?E(x,b):"";if(a=O[a]){var c=a,d=c.Gc,e=c.ed,h;if(!d)for(c.Gc=d={},c.dd={},h=0;h<S.getProgramParameter(c,35718);++h){var f=S.getActiveUniform(c,h);var l=f.name;f=f.size;var m=rc(l);m=0<m?l.slice(0,m):l;var p=c.Pc;c.Pc+=f;e[m]=[f,p];for(l=0;l<f;++l)d[p]=l,c.dd[p++]=m}c=a.Gc;d=0;e=b;h=rc(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.ed[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else T||=1281;
return-1},sb:(a,b,c)=>{for(var d=mc[b],e=0;e<b;e++)d[e]=y[c+4*e>>2];S.invalidateFramebuffer(a,d)},Xb:a=>{a=O[a];S.linkProgram(a);a.Gc=0;a.ed={}},Ra:(a,b)=>{3317==a?ac=b:3314==a&&(bc=b);S.pixelStorei(a,b)},H:(a,b)=>S.polygonOffset(a,b),vb:a=>S.readBuffer(a),Ea:(a,b,c,d,e)=>S.renderbufferStorageMultisample(a,b,c,d,e),ya:(a,b,c)=>{S.samplerParameterf(R[a],b,c)},h:(a,b,c)=>{S.samplerParameteri(R[a],b,c)},s:(a,b,c,d)=>S.scissor(a,b,c,d),Tb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=z[c+4*h>>2])?E(x,
f,d?z[d+4*h>>2]:void 0):"";e+=f}S.shaderSource(Q[a],e)},Pa:(a,b,c)=>S.stencilFunc(a,b,c),oa:(a,b,c,d)=>S.stencilFuncSeparate(a,b,c,d),u:a=>S.stencilMask(a),Oa:(a,b,c)=>S.stencilOp(a,b,c),na:(a,b,c,d)=>S.stencilOpSeparate(a,b,c,d),Aa:(a,b,c,d,e,h,f,l,m)=>{if(2<=V.version){if(S.Ec){S.texImage2D(a,b,c,d,e,h,f,l,m);return}if(m){var p=sc(l);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);S.texImage2D(a,b,c,d,e,h,f,l,p,m);return}}p=m?tc(l,f,d,e,m):null;S.texImage2D(a,b,c,d,e,h,f,l,p)},_b:(a,b,c,d,e,h,f,l,m,p)=>
{if(S.Ec)S.texImage3D(a,b,c,d,e,h,f,l,m,p);else if(p){var t=sc(m);S.texImage3D(a,b,c,d,e,h,f,l,m,t,p>>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else S.texImage3D(a,b,c,d,e,h,f,l,m,null)},Ca:(a,b,c)=>S.texParameteri(a,b,c),rb:(a,b,c,d,e,h,f,l,m)=>{if(2<=V.version){if(S.Ec){S.texSubImage2D(a,b,c,d,e,h,f,l,m);return}if(m){var p=sc(l);S.texSubImage2D(a,b,c,d,e,h,f,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}m=m?tc(l,f,e,h,m):null;S.texSubImage2D(a,b,c,d,e,h,f,l,m)},qb:(a,b,c,d,e,h,f,l,m,p,t)=>{if(S.Ec)S.texSubImage3D(a,
b,c,d,e,h,f,l,m,p,t);else if(t){var w=sc(p);S.texSubImage3D(a,b,c,d,e,h,f,l,m,p,w,t>>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else S.texSubImage3D(a,b,c,d,e,h,f,l,m,p,null)},Jb:(a,b,c)=>{if(2<=V.version)b&&S.uniform1fv(W(a),A,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);S.uniform1fv(W(a),d)}},va:(a,b)=>{S.uniform1i(W(a),b)},Eb:(a,b,c)=>{if(2<=V.version)b&&S.uniform1iv(W(a),y,c>>2,b);else{if(288>=b)for(var d=uc[b],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=
y.subarray(c>>2,c+4*b>>2);S.uniform1iv(W(a),d)}},Ib:(a,b,c)=>{if(2<=V.version)b&&S.uniform2fv(W(a),A,c>>2,2*b);else{if(144>=b)for(var d=X[2*b],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);S.uniform2fv(W(a),d)}},Db:(a,b,c)=>{if(2<=V.version)b&&S.uniform2iv(W(a),y,c>>2,2*b);else{if(144>=b)for(var d=uc[2*b],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);S.uniform2iv(W(a),d)}},Hb:(a,b,c)=>{if(2<=V.version)b&&S.uniform3fv(W(a),
A,c>>2,3*b);else{if(96>=b)for(var d=X[3*b],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);S.uniform3fv(W(a),d)}},Cb:(a,b,c)=>{if(2<=V.version)b&&S.uniform3iv(W(a),y,c>>2,3*b);else{if(96>=b)for(var d=uc[3*b],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);S.uniform3iv(W(a),d)}},Gb:(a,b,c)=>{if(2<=V.version)b&&S.uniform4fv(W(a),A,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=A;
c>>=2;for(var h=0;h<4*b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=A.subarray(c>>2,c+16*b>>2);S.uniform4fv(W(a),d)}},Bb:(a,b,c)=>{if(2<=V.version)b&&S.uniform4iv(W(a),y,c>>2,4*b);else{if(72>=b)for(var d=uc[4*b],e=0;e<4*b;e+=4)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2],d[e+3]=y[c+(4*e+12)>>2];else d=y.subarray(c>>2,c+16*b>>2);S.uniform4iv(W(a),d)}},Ab:(a,b,c,d)=>{if(2<=V.version)b&&S.uniformMatrix4fv(W(a),!!c,A,d>>2,16*b);else{if(18>=b){var e=X[16*
b],h=A;d>>=2;for(var f=0;f<16*b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=A.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(W(a),!!c,e)}},i:a=>{a=O[a];S.useProgram(a);S.hd=a},Lb:(a,b)=>{S.vertexAttribDivisor(a,b)},Mb:(a,b,c,d,e,h)=>{S.vertexAttribPointer(a,b,c,!!d,e,h)},n:(a,b,c,d)=>S.viewport(a,
b,c,d),bb:function(){g.Xc=a=>{0!=Ec()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Xc)},Wa:function(){g.cd=a=>{const b=a.clipboardData.getData("text");zc(()=>{const c=wc(b);Fc(c)})};window.addEventListener("paste",g.cd)},Ma:function(a){g.Ad=[];a=a?E(x,a):"";a=document.getElementById(a);g.Yc=b=>{b.stopPropagation();b.preventDefault()};g.Zc=b=>{b.stopPropagation();b.preventDefault()};g.$c=b=>{b.stopPropagation();b.preventDefault()};g.ad=b=>{b.stopPropagation();b.preventDefault();
const c=b.dataTransfer.files;g.bd=c;Gc(c.length);for(let e=0;e<c.length;e++)zc(()=>{const h=wc(c[e].name);Hc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Ic(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.Yc,!1);a.addEventListener("dragleave",g.Zc,!1);a.addEventListener("dragover",g.$c,!1);a.addEventListener("drop",g.ad,!1)},ub:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ja:function(a){const b=
g.bd;return 0>a||a>=b.length?0:b[a].size},ac:function(a,b,c,d,e){const h=new FileReader;h.onload=f=>{f=f.target.result;f.byteLength>d?Jc(a,0,1,b,0,c,d,e):(x.set(new Uint8Array(f),c),Jc(a,1,0,b,f.byteLength,c,d,e))};h.onerror=()=>{Jc(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(g.bd[a])},Pb:function(a){a=a?E(x,a):"";g.Fc=document.getElementById(a);g.Fc||console.log("sokol_app.h: invalid target:"+a);g.Fc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Xa:function(){window.removeEventListener("beforeunload",
g.Xc)},Sa:function(){window.removeEventListener("paste",g.cd)},Wb:function(a){a=a?E(x,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.Yc);a.removeEventListener("dragleave",g.Zc);a.removeEventListener("dragover",g.$c);a.removeEventListener("drop",g.ad)},z:function(){g.Fc&&g.Fc.requestPointerLock&&g.Fc.requestPointerLock()},Fb:function(a,b){if(g.Fc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;
case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.Fc.style.cursor=a}},kb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(x.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";
a.href=d.toDataURL();document.head.appendChild(a)},Na:function(a){a=a?E(x,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},cb:function(){const a=(new URLSearchParams(window.location.search)).entries();
for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];zc(()=>{const e=wc(c),h=wc(d);Kc(e,h)})}},eb:function(){return g.Dc?g.Dc.bufferSize:0},gb:function(a,b,c){g.yc=null;g.Dc=null;"undefined"!==typeof AudioContext?g.yc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.yc=null,console.log("sokol_audio.h: no WebAudio support"));return g.yc?(console.log("sokol_audio.h: sample rate ",g.yc.sampleRate),g.Dc=g.yc.createScriptProcessor(c,0,b),g.Dc.onaudioprocess=d=>{const e=d.outputBuffer.length,
h=Lc(e);if(h){const f=d.outputBuffer.numberOfChannels;for(let l=0;l<f;l++){const m=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)m[p]=A[(h>>2)+(f*p+l)]}}},g.Dc.connect(g.yc.destination),a=()=>{g.yc&&"suspended"===g.yc.state&&g.yc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},fb:function(){return g.yc?g.yc.sampleRate:0},ka:function(){const a=g.yc;null!==a&&(g.Dc&&g.Dc.disconnect(),
a.close(),g.yc=null,g.Dc=null)},db:function(){if(g.yc)return"suspended"===g.yc.state?1:0},x:function(a,b,c,d,e,h){b=b?E(x,b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const l=0<d;l&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!l){const m=new Uint8Array(f.response),p=m.length;p<=h?(x.set(m,e),Mc(a,d,p)):Nc(a)}else Oc(a,f.status)};f.send()},ja:function(a,b){b=
b?E(x,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");Pc(a,d)}else Oc(a,c.status)};c.send()},za:function(){return navigator.userAgent.includes("Macintosh")?1:0},ia:function(a,b){b=b?E(x,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;oa=Z.cc;ra();
Db=Z.uc;ta.unshift(Z.dc);C--;g.monitorRunDependencies?.(C);0==C&&(null!==xa&&(clearInterval(xa),xa=null),D&&(c=D,D=null,c()));return Z}var b={a:Qc};C++;g.monitorRunDependencies?.(C);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return n(`Module.instantiateWasm callback failed with error: ${c}`),!1}Aa||=za("atom-ui.wasm")?"atom-ui.wasm":g.locateFile?g.locateFile("atom-ui.wasm",k):k+"atom-ui.wasm";Ea(b,function(c){a(c.instance)});return{}}(),N=a=>(N=Z.ec)(a),Cc=g._fs_emsc_alloc=a=>
(Cc=g._fs_emsc_alloc=Z.fc)(a),Dc=g._fs_emsc_load_snapshot_callback=(a,b,c)=>(Dc=g._fs_emsc_load_snapshot_callback=Z.gc)(a,b,c),Fc=g.__sapp_emsc_onpaste=a=>(Fc=g.__sapp_emsc_onpaste=Z.hc)(a),Ec=g.__sapp_html5_get_ask_leave_site=()=>(Ec=g.__sapp_html5_get_ask_leave_site=Z.ic)(),Gc=g.__sapp_emsc_begin_drop=a=>(Gc=g.__sapp_emsc_begin_drop=Z.jc)(a),Hc=g.__sapp_emsc_drop=(a,b)=>(Hc=g.__sapp_emsc_drop=Z.kc)(a,b),Ic=g.__sapp_emsc_end_drop=(a,b,c)=>(Ic=g.__sapp_emsc_end_drop=Z.lc)(a,b,c),Jc=g.__sapp_emsc_invoke_fetch_cb=
(a,b,c,d,e,h,f,l)=>(Jc=g.__sapp_emsc_invoke_fetch_cb=Z.mc)(a,b,c,d,e,h,f,l),Rc=g._main=(a,b)=>(Rc=g._main=Z.nc)(a,b),Lc=g.__saudio_emsc_pull=a=>(Lc=g.__saudio_emsc_pull=Z.oc)(a),Kc=g.__sargs_add_kvp=(a,b)=>(Kc=g.__sargs_add_kvp=Z.pc)(a,b),Pc=g.__sfetch_emsc_head_response=(a,b)=>(Pc=g.__sfetch_emsc_head_response=Z.qc)(a,b),Mc=g.__sfetch_emsc_get_response=(a,b,c)=>(Mc=g.__sfetch_emsc_get_response=Z.rc)(a,b,c),Oc=g.__sfetch_emsc_failed_http_status=(a,b)=>(Oc=g.__sfetch_emsc_failed_http_status=Z.sc)(a,
b),Nc=g.__sfetch_emsc_failed_buffer_too_small=a=>(Nc=g.__sfetch_emsc_failed_buffer_too_small=Z.tc)(a),yc=a=>(yc=Z.vc)(a),vc=a=>(vc=Z.wc)(a),xc=()=>(xc=Z.xc)(),Sc;D=function Tc(){Sc||Uc();Sc||(D=Tc)};function Vc(a=[]){var b=Rc;a.unshift(fa);var c=a.length,d=vc(4*(c+1)),e=d;a.forEach(f=>{z[e>>2]=wc(f);e+=4});z[e>>2]=0;try{var h=b(c,d);$a(h)}catch(f){Ya(f)}}
function Uc(){var a=ea;function b(){if(!Sc&&(Sc=!0,g.calledRun=!0,!r)){Fa(ta);Fa(ua);g.onRuntimeInitialized?.();Wc&&Vc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();va.unshift(c)}Fa(va)}}if(!(0<C)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)wa();Fa(sa);0<C||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Wc=!0;g.noInitialRun&&(Wc=!1);Uc();
