
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=[],ca="./this.program",k=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,t,u;
if(ea){var fs=require("fs"),ha=require("path");q=l?ha.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};u=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};t=(a,b,c)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",
function(a){if(!(a instanceof w))throw a;});process.on("unhandledRejection",function(a){throw a;});k=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof w||x("exiting due to exception: "+b);process.exit(a)};f.inspect=function(){return"[Emscripten Module object]"}}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;
b.open("GET",a,!1);b.send(null);return b.responseText},l&&(u=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),t=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};f.print||console.log.bind(console);var x=f.printErr||console.warn.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);
f.thisProgram&&(ca=f.thisProgram);f.quit&&(k=f.quit);var y;f.wasmBinary&&(y=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&ia("no native wasm support detected");var z,ja=!1,ka="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function A(a,b){if(a){var c=B,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&ka)a=ka.decode(c.subarray(a,b));else{for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}a=d}}else a="";return a}
function C(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function la(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var ma,B,na,oa,D,pa,E,F;function qa(){var a=z.buffer;f.HEAP8=ma=new Int8Array(a);f.HEAP16=na=new Int16Array(a);f.HEAP32=D=new Int32Array(a);f.HEAPU8=B=new Uint8Array(a);f.HEAPU16=oa=new Uint16Array(a);f.HEAPU32=pa=new Uint32Array(a);f.HEAPF32=E=new Float32Array(a);f.HEAPF64=F=new Float64Array(a)}var ra,sa=[],ta=[],ua=[],va=[],wa=[];
function xa(){var a=f.preRun.shift();sa.unshift(a)}var G=0,ya=null,H=null;function ia(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";x(a);ja=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function za(){return I.startsWith("data:application/octet-stream;base64,")}var I;I="bombjack.wasm";if(!za()){var Aa=I;I=f.locateFile?f.locateFile(Aa,q):q+Aa}
function Ba(){var a=I;try{if(a==I&&y)return new Uint8Array(y);if(u)return u(a);throw"both async and sync fetching of the wasm failed";}catch(b){ia(b)}}
function Ca(){if(!y&&(da||l)){if("function"==typeof fetch&&!I.startsWith("file://"))return fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Ba()});if(t)return new Promise(function(a,b){t(I,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ba()})}function w(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function J(a){for(;0<a.length;)a.shift()(f)}function Da(a){var b=Ea();a();Fa(b)}var Ga=0;function Ha(){for(var a=K.length-1;0<=a;--a)Ia(a);K=[];Ja=[]}var Ja=[];function Ka(){if(Ga&&La.cc)for(var a=0;a<Ja.length;++a){var b=Ja[a];Ja.splice(a,1);--a;b.Mc.apply(null,b.Cc)}}var K=[];function Ia(a){var b=K[a];b.target.removeEventListener(b.Vb,b.xc,b.Wb);K.splice(a,1)}
function L(a){function b(d){++Ga;La=a;Ka();a.Yb(d);Ka();--Ga}if(a.Xb)a.xc=b,a.target.addEventListener(a.Vb,b,a.Wb),K.push(a),Ma||(va.push(Ha),Ma=!0);else for(var c=0;c<K.length;++c)K[c].target==a.target&&K[c].Vb==a.Vb&&Ia(c--)}function Na(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var Ma,La,Oa,Pa,Qa,Ra,Sa,Ta,Ua,Va=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];
function M(a){a=2<a?A(a):a;return Va[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function Wa(a){return 0>Va.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}var Xa;Xa=ea?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var Ya=[];function N(a){var b=Ya[a];b||(a>=Ya.length&&(Ya.length=a+1),Ya[a]=b=ra.get(a));return b}
function Za(a,b,c,d,e,h){Oa||(Oa=O(256));a={target:M(a),Vb:h,Xb:d,Yb:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Oa;C(Na(g.target),B,n+0,128);C(m,B,n+128,128);N(d)(e,n,b)&&g.preventDefault()},Wb:c};L(a)}
function $a(a,b,c,d,e,h){Pa||(Pa=O(176));a={target:M(a),cc:!0,Vb:h,Xb:d,Yb:function(g){var m=Pa;F[m>>3]=g.timeStamp;var n=m>>2;D[n+2]=g.location;D[n+3]=g.ctrlKey;D[n+4]=g.shiftKey;D[n+5]=g.altKey;D[n+6]=g.metaKey;D[n+7]=g.repeat;D[n+8]=g.charCode;D[n+9]=g.keyCode;D[n+10]=g.which;C(g.key||"",B,m+44,32);C(g.code||"",B,m+76,32);C(g.char||"",B,m+108,32);C(g.locale||"",B,m+140,32);N(d)(e,m,b)&&g.preventDefault()},Wb:c};L(a)}
function ab(a,b,c){F[a>>3]=b.timeStamp;a>>=2;D[a+2]=b.screenX;D[a+3]=b.screenY;D[a+4]=b.clientX;D[a+5]=b.clientY;D[a+6]=b.ctrlKey;D[a+7]=b.shiftKey;D[a+8]=b.altKey;D[a+9]=b.metaKey;na[2*a+20]=b.button;na[2*a+21]=b.buttons;D[a+11]=b.movementX;D[a+12]=b.movementY;c=Wa(c);D[a+13]=b.clientX-c.left;D[a+14]=b.clientY-c.top}
function P(a,b,c,d,e,h){Qa||(Qa=O(72));a=M(a);L({target:a,cc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Vb:h,Xb:d,Yb:function(g){g=g||event;ab(Qa,g,a);N(d)(e,Qa,b)&&g.preventDefault()},Wb:c})}function bb(a,b,c,d,e){Ra||(Ra=O(260));L({target:a,Vb:e,Xb:d,Yb:function(h){h=h||event;var g=Ra,m=document.pointerLockElement||document.$b||document.kc||document.jc;D[g>>2]=!!m;var n=m&&m.id?m.id:"";C(Na(m),B,g+4,128);C(n,B,g+132,128);N(d)(20,g,b)&&h.preventDefault()},Wb:c})}
function cb(a,b,c,d,e){L({target:a,Vb:e,Xb:d,Yb:function(h){h=h||event;N(d)(38,0,b)&&h.preventDefault()},Wb:c})}
function db(a,b,c,d){Sa||(Sa=O(36));a=M(a);L({target:a,Vb:"resize",Xb:d,Yb:function(e){e=e||event;if(e.target==a){var h=document.body;if(h){var g=Sa;D[g>>2]=e.detail;D[g+4>>2]=h.clientWidth;D[g+8>>2]=h.clientHeight;D[g+12>>2]=innerWidth;D[g+16>>2]=innerHeight;D[g+20>>2]=outerWidth;D[g+24>>2]=outerHeight;D[g+28>>2]=pageXOffset;D[g+32>>2]=pageYOffset;N(d)(10,g,b)&&e.preventDefault()}}},Wb:c})}
function eb(a,b,c,d,e,h){Ta||(Ta=O(1696));a=M(a);L({target:a,cc:"touchstart"==h||"touchend"==h,Vb:h,Xb:d,Yb:function(g){for(var m,n={},p=g.touches,v=0;v<p.length;++v)m=p[v],m.mc=m.nc=0,n[m.identifier]=m;for(v=0;v<g.changedTouches.length;++v)m=g.changedTouches[v],m.mc=1,n[m.identifier]=m;for(v=0;v<g.targetTouches.length;++v)n[g.targetTouches[v].identifier].nc=1;p=Ta;F[p>>3]=g.timeStamp;var r=p>>2;D[r+3]=g.ctrlKey;D[r+4]=g.shiftKey;D[r+5]=g.altKey;D[r+6]=g.metaKey;r+=7;var kb=Wa(a),lb=0;for(v in n)if(m=
n[v],D[r]=m.identifier,D[r+1]=m.screenX,D[r+2]=m.screenY,D[r+3]=m.clientX,D[r+4]=m.clientY,D[r+5]=m.pageX,D[r+6]=m.pageY,D[r+7]=m.mc,D[r+8]=m.nc,D[r+9]=m.clientX-kb.left,D[r+10]=m.clientY-kb.top,r+=13,31<++lb)break;D[p+8>>2]=lb;N(d)(e,p,b)&&g.preventDefault()},Wb:c})}function fb(a,b,c,d,e,h){a={target:M(a),Vb:h,Xb:d,Yb:function(g){g=g||event;N(d)(e,0,b)&&g.preventDefault()},Wb:c};L(a)}
function gb(a,b,c,d){Ua||(Ua=O(104));L({target:a,cc:!0,Vb:"wheel",Xb:d,Yb:function(e){e=e||event;var h=Ua;ab(h,e,a);F[h+72>>3]=e.deltaX;F[h+80>>3]=e.deltaY;F[h+88>>3]=e.deltaZ;D[h+96>>2]=e.deltaMode;N(d)(9,h,b)&&e.preventDefault()},Wb:c})}
function hb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function ib(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function jb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function mb(a){a.Hc=a.getExtension("WEBGL_multi_draw")}
var nb=1,ob=[],Q=[],pb=[],R=[],S=[],T=[],qb=[],rb={};function U(a){sb||(sb=a)}function tb(a){for(var b=nb++,c=a.length;c<b;c++)a[c]=null;return b}function ub(a,b){a.$b||(a.$b=a.getContext,a.getContext=function(d,e){e=a.$b(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?vb(c,b):0}function vb(a,b){var c=tb(qb),d={Fc:c,attributes:b,version:b.Ac,hc:a};a.canvas&&(a.canvas.Bc=d);qb[c]=d;("undefined"==typeof b.lc||b.lc)&&wb(d);return c}
function wb(a){a||(a=xb);if(!a.zc){a.zc=!0;var b=a.hc;hb(b);ib(b);jb(b);b.Ec=b.getExtension("EXT_disjoint_timer_query");mb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var sb,xb,yb=["default","low-power","high-performance"];function zb(a,b,c,d){for(var e=0;e<a;e++){var h=V[c](),g=h&&tb(d);h?(h.name=g,d[g]=h):U(1282);D[b+4*e>>2]=g}}
function Ab(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=V.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=V.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:U(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)D[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U(1280);x("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:U(1280);x("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}D[b>>2]=c}else U(1281)}function Bb(a){var b=la(a)+1,c=O(b);C(a,B,c,b);return c}
function Cb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Db(a,b,c,d,e){a-=5120;a=1==a?B:4==a?D:6==a?E:5==a||28922==a?pa:oa;var h=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(e>>h,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<h)+4-1&-4)>>h)}function W(a){var b=V.wc;if(b){var c=b.bc[a];"number"==typeof c&&(b.bc[a]=c=V.getUniformLocation(b,b.uc[a]+(0<c?"["+c+"]":"")));return c}U(1282)}var X=[],Y=[];
function Eb(a){if(!noExitRuntime){if(f.onExit)f.onExit(a);ja=!0}k(a,new w(a))}function Fb(a){var b=la(a)+1,c=Gb(b);C(a,ma,c,b);return c}for(var V,Hb=new Float32Array(288),Z=0;288>Z;++Z)X[Z]=Hb.subarray(0,Z+1);var Ib=new Int32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Ib.subarray(0,Z+1);
var Ub={O:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},R:function(a,b,c){a=M(a);if(!a)return-4;a=Wa(a);F[b>>3]=a.width;F[c>>3]=a.height;return 0},C:Xa,Ya:function(a,b,c){B.copyWithin(a,b,b+c)},za:function(a,b){function c(d){N(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Xa:function(a){var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,h=e.min;d=Math.max(a,d);d+=(65536-d%65536)%
65536;a:{var g=z.buffer;try{z.grow(h.call(e,2147483648,d)-g.byteLength+65535>>>16);qa();var m=1;break a}catch(n){}m=void 0}if(m)return!0}return!1},U:function(a,b,c,d){Za(a,b,c,d,12,"blur");return 0},H:function(a,b,c){a=M(a);if(!a)return-4;a.width=b;a.height=c;return 0},V:function(a,b,c,d){Za(a,b,c,d,13,"focus");return 0},ca:function(a,b,c,d){$a(a,b,c,d,2,"keydown");return 0},aa:function(a,b,c,d){$a(a,b,c,d,1,"keypress");return 0},ba:function(a,b,c,d){$a(a,b,c,d,3,"keyup");return 0},ia:function(a,
b,c,d){P(a,b,c,d,5,"mousedown");return 0},fa:function(a,b,c,d){P(a,b,c,d,33,"mouseenter");return 0},ea:function(a,b,c,d){P(a,b,c,d,34,"mouseleave");return 0},ga:function(a,b,c,d){P(a,b,c,d,8,"mousemove");return 0},ha:function(a,b,c,d){P(a,b,c,d,6,"mouseup");return 0},X:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.$b||document.body.kc||document.body.jc))return-1;a=M(a);if(!a)return-4;bb(a,b,c,d,"pointerlockchange");bb(a,b,c,d,"mozpointerlockchange");
bb(a,b,c,d,"webkitpointerlockchange");bb(a,b,c,d,"mspointerlockchange");return 0},W:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.$b||document.body.kc||document.body.jc))return-1;a=M(a);if(!a)return-4;cb(a,b,c,d,"pointerlockerror");cb(a,b,c,d,"mozpointerlockerror");cb(a,b,c,d,"webkitpointerlockerror");cb(a,b,c,d,"mspointerlockerror");return 0},Ka:function(a,b,c,d){db(a,b,c,d);return 0},Y:function(a,b,c,d){eb(a,b,c,d,25,"touchcancel");return 0},Z:function(a,b,c,
d){eb(a,b,c,d,23,"touchend");return 0},_:function(a,b,c,d){eb(a,b,c,d,24,"touchmove");return 0},$:function(a,b,c,d){eb(a,b,c,d,22,"touchstart");return 0},T:function(a,b,c,d){fb(a,b,c,d,31,"webglcontextlost");return 0},S:function(a,b,c,d){fb(a,b,c,d,32,"webglcontextrestored");return 0},da:function(a,b,c,d){a=M(a);return"undefined"!=typeof a.onwheel?(gb(a,b,c,d),0):-1},pa:function(a,b){b>>=2;b={alpha:!!D[b],depth:!!D[b+1],stencil:!!D[b+2],antialias:!!D[b+3],premultipliedAlpha:!!D[b+4],preserveDrawingBuffer:!!D[b+
5],powerPreference:yb[D[b+6]],failIfMajorPerformanceCaveat:!!D[b+7],Ac:D[b+8],Gc:D[b+9],lc:D[b+10],yc:D[b+11],Ic:D[b+12],Jc:D[b+13]};a=M(a);return!a||b.yc?0:ub(a,b)},eb:function(a,b){a=qb[a];b=A(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&hb(V);"OES_vertex_array_object"==b&&ib(V);"WEBGL_draw_buffers"==b&&jb(V);"WEBGL_multi_draw"==b&&mb(V);return!!a.hc.getExtension(b)},ta:function(a){a>>=2;for(var b=0;14>b;++b)D[a+b]=0;D[a]=D[a+1]=D[a+3]=D[a+4]=D[a+8]=D[a+10]=1},pb:function(a){xb=
qb[a];f.Dc=V=xb&&xb.hc;return!a||V?0:-5},b:function(a){V.activeTexture(a)},G:function(a,b){V.attachShader(Q[a],T[b])},c:function(a,b){V.bindBuffer(a,ob[b])},h:function(a,b){V.bindFramebuffer(a,pb[b])},Ea:function(a,b){V.bindRenderbuffer(a,R[b])},a:function(a,b){V.bindTexture(a,S[b])},L:function(a,b,c,d){V.blendColor(a,b,c,d)},M:function(a,b){V.blendEquationSeparate(a,b)},N:function(a,b,c,d){V.blendFuncSeparate(a,b,c,d)},Ga:function(a,b,c,d){V.bufferData(a,c?B.subarray(c,c+b):b,d)},r:function(a,b,
c,d){V.bufferSubData(a,b,B.subarray(d,d+c))},m:function(a){return V.checkFramebufferStatus(a)},tb:function(a){V.clear(a)},vb:function(a,b,c,d){V.clearColor(a,b,c,d)},na:function(a){V.clearDepth(a)},ub:function(a){V.clearStencil(a)},o:function(a,b,c,d){V.colorMask(!!a,!!b,!!c,!!d)},sa:function(a){V.compileShader(T[a])},Ba:function(a,b,c,d,e,h,g,m){V.compressedTexImage2D(a,b,c,d,e,h,m?B.subarray(m,m+g):null)},ya:function(){var a=tb(Q),b=V.createProgram();b.name=a;b.fc=b.dc=b.ec=0;b.ic=1;Q[a]=b;return a},
va:function(a){var b=tb(T);T[b]=V.createShader(a);return b},I:function(a){V.cullFace(a)},Ma:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=ob[d];e&&(V.deleteBuffer(e),e.name=0,ob[d]=null)}},d:function(a,b){for(var c=0;c<a;++c){var d=D[b+4*c>>2],e=pb[d];e&&(V.deleteFramebuffer(e),e.name=0,pb[d]=null)}},s:function(a){if(a){var b=Q[a];b?(V.deleteProgram(b),b.name=0,Q[a]=null):U(1281)}},Q:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=R[d];e&&(V.deleteRenderbuffer(e),e.name=0,R[d]=null)}},
w:function(a){if(a){var b=T[a];b?(V.deleteShader(b),T[a]=null):U(1281)}},La:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=S[d];e&&(V.deleteTexture(e),e.name=0,S[d]=null)}},z:function(a){V.depthFunc(a)},y:function(a){V.depthMask(!!a)},e:function(a){V.disable(a)},P:function(a){V.disableVertexAttribArray(a)},bb:function(a,b,c){V.drawArrays(a,b,c)},cb:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},db:function(a,b,c,d){V.drawElements(a,b,c,d)},fb:function(a,b,c,d,e){V.drawElementsInstanced(a,
b,c,d,e)},i:function(a){V.enable(a)},qb:function(a){V.enableVertexAttribArray(a)},k:function(a,b,c,d){V.framebufferRenderbuffer(a,b,c,R[d])},g:function(a,b,c,d,e){V.framebufferTexture2D(a,b,c,S[d],e)},J:function(a){V.frontFace(a)},Ha:function(a,b){zb(a,b,"createBuffer",ob)},n:function(a,b){zb(a,b,"createFramebuffer",pb)},Fa:function(a,b){zb(a,b,"createRenderbuffer",R)},Ca:function(a,b){zb(a,b,"createTexture",S)},qa:function(a,b){return V.getAttribLocation(Q[a],A(b))},f:function(a,b){Ab(a,b)},wa:function(a,
b,c,d){a=V.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,B,d,b):0;c&&(D[c>>2]=b)},F:function(a,b,c){if(c)if(a>=nb)U(1281);else if(a=Q[a],35716==b)a=V.getProgramInfoLog(a),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b){if(!a.fc)for(b=0;b<V.getProgramParameter(a,35718);++b)a.fc=Math.max(a.fc,V.getActiveUniform(a,b).name.length+1);D[c>>2]=a.fc}else if(35722==b){if(!a.dc)for(b=0;b<V.getProgramParameter(a,35721);++b)a.dc=Math.max(a.dc,V.getActiveAttrib(a,b).name.length+
1);D[c>>2]=a.dc}else if(35381==b){if(!a.ec)for(b=0;b<V.getProgramParameter(a,35382);++b)a.ec=Math.max(a.ec,V.getActiveUniformBlockName(a,b).length+1);D[c>>2]=a.ec}else D[c>>2]=V.getProgramParameter(a,b);else U(1281)},ra:function(a,b,c,d){a=V.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,B,d,b):0;c&&(D[c>>2]=b)},D:function(a,b,c){c?35716==b?(a=V.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),D[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(T[a]),D[c>>2]=a?a.length+
1:0):D[c>>2]=V.getShaderParameter(T[a],b):U(1281)},Na:function(a){var b=rb[a];if(!b){switch(a){case 7939:b=V.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Bb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=V.getParameter(a))||U(1280);b=b&&Bb(b);break;case 7938:b=Bb("OpenGL ES 2.0 ("+V.getParameter(7938)+")");break;case 35724:b=V.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=
"OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Bb(b);break;default:U(1280)}rb[a]=b}return b},q:function(a,b){b=A(b);if(a=Q[a]){var c=a,d=c.bc,e=c.vc,h;if(!d)for(c.bc=d={},c.uc={},h=0;h<V.getProgramParameter(c,35718);++h){var g=V.getActiveUniform(c,h);var m=g.name;g=g.size;var n=Cb(m);n=0<n?m.slice(0,n):m;var p=c.ic;c.ic+=g;e[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.uc[p++]=n}c=a.bc;d=0;e=b;h=Cb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.vc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||V.getUniformLocation(a,
b)))return d}else U(1281);return-1},xa:function(a){a=Q[a];V.linkProgram(a);a.bc=0;a.vc={}},K:function(a,b){V.polygonOffset(a,b)},Da:function(a,b,c,d){V.renderbufferStorage(a,b,c,d)},oa:function(a,b,c,d){V.scissor(a,b,c,d)},ua:function(a,b,c,d){for(var e="",h=0;h<b;++h){var g=d?D[d+4*h>>2]:-1;e+=A(D[c+4*h>>2],0>g?void 0:g)}V.shaderSource(T[a],e)},Ja:function(a,b,c){V.stencilFunc(a,b,c)},ma:function(a,b,c,d){V.stencilFuncSeparate(a,b,c,d)},x:function(a){V.stencilMask(a)},Ia:function(a,b,c){V.stencilOp(a,
b,c)},la:function(a,b,c,d){V.stencilOpSeparate(a,b,c,d)},Aa:function(a,b,c,d,e,h,g,m,n){V.texImage2D(a,b,c,d,e,h,g,m,n?Db(m,g,d,e,n):null)},j:function(a,b,c){V.texParameteri(a,b,c)},ab:function(a,b,c,d,e,h,g,m,n){var p=null;n&&(p=Db(m,g,e,h,n));V.texSubImage2D(a,b,c,d,e,h,g,m,p)},ob:function(a,b,c){if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=E[c+4*e>>2];else d=E.subarray(c>>2,c+4*b>>2);V.uniform1fv(W(a),d)},E:function(a,b){V.uniform1i(W(a),b)},kb:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=
D[c+4*e>>2];else d=D.subarray(c>>2,c+4*b>>2);V.uniform1iv(W(a),d)},nb:function(a,b,c){if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2];else d=E.subarray(c>>2,c+8*b>>2);V.uniform2fv(W(a),d)},jb:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2];else d=D.subarray(c>>2,c+8*b>>2);V.uniform2iv(W(a),d)},mb:function(a,b,c){if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2],d[e+2]=E[c+(4*e+
8)>>2];else d=E.subarray(c>>2,c+12*b>>2);V.uniform3fv(W(a),d)},ib:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2],d[e+2]=D[c+(4*e+8)>>2];else d=D.subarray(c>>2,c+12*b>>2);V.uniform3iv(W(a),d)},lb:function(a,b,c){if(72>=b){var d=X[4*b-1],e=E;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=E.subarray(c>>2,c+16*b>>2);V.uniform4fv(W(a),d)},hb:function(a,b,c){if(72>=b)for(var d=Y[4*b-1],e=0;e<4*b;e+=
4)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2],d[e+2]=D[c+(4*e+8)>>2],d[e+3]=D[c+(4*e+12)>>2];else d=D.subarray(c>>2,c+16*b>>2);V.uniform4iv(W(a),d)},gb:function(a,b,c,d){if(18>=b){var e=X[16*b-1],h=E;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=h[m+13];e[g+14]=h[m+14];e[g+15]=h[m+15]}}else e=E.subarray(d>>2,d+64*b>>
2);V.uniformMatrix4fv(W(a),!!c,e)},l:function(a){a=Q[a];V.useProgram(a);V.wc=a},rb:function(a,b){V.vertexAttribDivisor(a,b)},sb:function(a,b,c,d,e,h){V.vertexAttribPointer(a,b,c,!!d,e,h)},p:function(a,b,c,d){V.viewport(a,b,c,d)},Va:function(){f.oc=a=>{0!=Jb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.oc)},Ua:function(){f.tc=a=>{const b=a.clipboardData.getData("text");Da(()=>{const c=Fb(b);Kb(c)})};window.addEventListener("paste",f.tc)},Ta:function(a){f.Kc=[];
a=A(a);a=document.getElementById(a);f.pc=b=>{b.stopPropagation();b.preventDefault()};f.qc=b=>{b.stopPropagation();b.preventDefault()};f.rc=b=>{b.stopPropagation();b.preventDefault()};f.sc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Lc=c;Lb(c.length);for(let d=0;d<c.length;d++)Da(()=>{const e=Fb(c[d].name);Mb(d,e)});Nb(b.clientX,b.clientY)};a.addEventListener("dragenter",f.pc,!1);a.addEventListener("dragleave",f.qc,!1);a.addEventListener("dragover",f.rc,!1);a.addEventListener("drop",
f.sc,!1)},Pa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},v:function(){const a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Ob()});document.body.append(a)},u:function(){document.getElementById("_sokol_app_input_element").focus()},Wa:function(a){a=A(a);f.ac=document.getElementById(a);f.ac||console.log("sokol_app.h: invalid target:"+a);f.ac.requestPointerLock||
console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Sa:function(){window.removeEventListener("beforeunload",f.oc)},Ra:function(){window.removeEventListener("paste",f.tc)},Qa:function(a){a=A(a);a=document.getElementById(a);a.removeEventListener("dragenter",f.pc);a.removeEventListener("dragleave",f.qc);a.removeEventListener("dragover",f.rc);a.removeEventListener("drop",f.sc)},A:function(){f.ac&&f.ac.requestPointerLock&&f.ac.requestPointerLock()},Oa:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(B.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},t:function(){document.getElementById("_sokol_app_input_element").blur()},Za:function(){return f.Zb?f.Zb.bufferSize:0},$a:function(a,b,c){f.Ub=null;f.Zb=null;"undefined"!==typeof AudioContext?f.Ub=new AudioContext({sampleRate:a,latencyHint:"interactive"}):
(f.Ub=null,console.log("sokol_audio.h: no WebAudio support"));return f.Ub?(console.log("sokol_audio.h: sample rate ",f.Ub.sampleRate),f.Zb=f.Ub.createScriptProcessor(c,0,b),f.Zb.onaudioprocess=d=>{const e=d.outputBuffer.length,h=Pb(e);if(h){const g=d.outputBuffer.numberOfChannels;for(let m=0;m<g;m++){const n=d.outputBuffer.getChannelData(m);for(let p=0;p<e;p++)n[p]=E[(h>>2)+(g*p+m)]}}},f.Zb.connect(f.Ub.destination),a=()=>{f.Ub&&"suspended"===f.Ub.state&&f.Ub.resume()},document.addEventListener("click",
a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},_a:function(){return f.Ub?f.Ub.sampleRate:0},ka:function(){const a=f.Ub;null!==a&&(f.Zb&&f.Zb.disconnect(),a.close(),f.Ub=null,f.Zb=null)},wb:function(){if(f.Ub)return"suspended"===f.Ub.state?1:0},B:function(a,b,c,d,e,h){b=A(b);const g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";const m=0<d;m&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=
function(){if(g.readyState==XMLHttpRequest.DONE)if(206==g.status||200==g.status&&!m){const n=new Uint8Array(g.response),p=n.length;p<=h?(B.set(n,e),Qb(a,d,p)):Rb(a)}else Sb(a,g.status)};g.send()},ja:function(a,b){b=A(b);const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");Tb(a,d)}else Sb(a,c.status)};c.send()}};
(function(){function a(e){f.asm=e.exports;z=f.asm.xb;qa();ra=f.asm.Qb;ta.unshift(f.asm.yb);G--;f.monitorRunDependencies&&f.monitorRunDependencies(G);0==G&&(null!==ya&&(clearInterval(ya),ya=null),H&&(e=H,H=null,e()))}function b(e){a(e.instance)}function c(e){return Ca().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(e,function(h){x("failed to asynchronously prepare wasm: "+h);ia(h)})}var d={a:Ub};G++;f.monitorRunDependencies&&f.monitorRunDependencies(G);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return x("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return y||"function"!=typeof WebAssembly.instantiateStreaming||za()||I.startsWith("file://")||ea||"function"!=typeof fetch?c(b):fetch(I,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(h){x("wasm streaming compile failed: "+h);x("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.yb).apply(null,arguments)};f._fs_emsc_alloc=function(){return(f._fs_emsc_alloc=f.asm.zb).apply(null,arguments)};var O=f._malloc=function(){return(O=f._malloc=f.asm.Ab).apply(null,arguments)};f._fs_emsc_load_snapshot_callback=function(){return(f._fs_emsc_load_snapshot_callback=f.asm.Bb).apply(null,arguments)};
var Ob=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Ob=f.__sapp_emsc_notify_keyboard_hidden=f.asm.Cb).apply(null,arguments)},Kb=f.__sapp_emsc_onpaste=function(){return(Kb=f.__sapp_emsc_onpaste=f.asm.Db).apply(null,arguments)},Jb=f.__sapp_html5_get_ask_leave_site=function(){return(Jb=f.__sapp_html5_get_ask_leave_site=f.asm.Eb).apply(null,arguments)},Lb=f.__sapp_emsc_begin_drop=function(){return(Lb=f.__sapp_emsc_begin_drop=f.asm.Fb).apply(null,arguments)},Mb=f.__sapp_emsc_drop=function(){return(Mb=
f.__sapp_emsc_drop=f.asm.Gb).apply(null,arguments)},Nb=f.__sapp_emsc_end_drop=function(){return(Nb=f.__sapp_emsc_end_drop=f.asm.Hb).apply(null,arguments)};f.__sapp_emsc_invoke_fetch_cb=function(){return(f.__sapp_emsc_invoke_fetch_cb=f.asm.Ib).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Jb).apply(null,arguments)};var Pb=f.__saudio_emsc_pull=function(){return(Pb=f.__saudio_emsc_pull=f.asm.Kb).apply(null,arguments)};
f.__sargs_add_kvp=function(){return(f.__sargs_add_kvp=f.asm.Lb).apply(null,arguments)};
var Tb=f.__sfetch_emsc_head_response=function(){return(Tb=f.__sfetch_emsc_head_response=f.asm.Mb).apply(null,arguments)},Qb=f.__sfetch_emsc_get_response=function(){return(Qb=f.__sfetch_emsc_get_response=f.asm.Nb).apply(null,arguments)},Sb=f.__sfetch_emsc_failed_http_status=function(){return(Sb=f.__sfetch_emsc_failed_http_status=f.asm.Ob).apply(null,arguments)},Rb=f.__sfetch_emsc_failed_buffer_too_small=function(){return(Rb=f.__sfetch_emsc_failed_buffer_too_small=f.asm.Pb).apply(null,arguments)},Ea=
f.stackSave=function(){return(Ea=f.stackSave=f.asm.Rb).apply(null,arguments)},Fa=f.stackRestore=function(){return(Fa=f.stackRestore=f.asm.Sb).apply(null,arguments)},Gb=f.stackAlloc=function(){return(Gb=f.stackAlloc=f.asm.Tb).apply(null,arguments)};f.___start_em_js=129888;f.___stop_em_js=142550;var Vb;H=function Wb(){Vb||Xb();Vb||(H=Wb)};
function Yb(a){var b=f._main;a=a||[];a.unshift(ca);var c=a.length,d=Gb(4*(c+1)),e=d>>2;a.forEach(g=>{D[e++]=Fb(g)});D[e]=0;try{var h=b(c,d);Eb(h)}catch(g){g instanceof w||"unwind"==g||k(1,g)}}
function Xb(){function a(){if(!Vb&&(Vb=!0,f.calledRun=!0,!ja)){J(ta);J(ua);if(f.onRuntimeInitialized)f.onRuntimeInitialized();Zb&&Yb(b);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();wa.unshift(c)}J(wa)}}var b=b||ba;if(!(0<G)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)xa();J(sa);0<G||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},
1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Zb=!0;f.noInitialRun&&(Zb=!1);Xb();
