var f;f||(f=typeof Module !== 'undefined' ? Module : {});var g={},k;for(k in f)f.hasOwnProperty(k)&&(g[k]=f[k]);var m=[],aa="./this.program";function t(a,b){throw b;}var u=!1,v=!1,ba=!1,ca=!1,da=!1;u="object"===typeof window;v="function"===typeof importScripts;ba=(ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!u&&!v;da=!u&&!ba&&!v;var x="",ea,y;
if(ba){x=__dirname+"/";var fa,ha;ea=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);a=fa.readFileSync(a);return b?a:a.toString()};y=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||z("Assertion failed: undefined");return a};1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/"));m=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=f);process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;});process.on("unhandledRejection",
z);t=function(a){process.exit(a)};f.inspect=function(){return"[Emscripten Module object]"}}else if(da)"undefined"!=typeof read&&(ea=function(a){return read(a)}),y=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||z("Assertion failed: undefined");return a},"undefined"!=typeof scriptArgs?m=scriptArgs:"undefined"!=typeof arguments&&(m=arguments),"function"===typeof quit&&(t=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===
typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(u||v)v?x=self.location.href:document.currentScript&&(x=document.currentScript.src),x=0!==x.indexOf("blob:")?x.substr(0,x.lastIndexOf("/")+1):"",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(y=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var ja=f.print||console.log.bind(console),A=f.printErr||console.warn.bind(console);for(k in g)g.hasOwnProperty(k)&&(f[k]=g[k]);g=null;f.arguments&&(m=f.arguments);f.thisProgram&&(aa=f.thisProgram);f.quit&&(t=f.quit);var B;f.wasmBinary&&(B=f.wasmBinary);var C;f.noExitRuntime&&(C=f.noExitRuntime);"object"!==typeof WebAssembly&&A("no native wasm support detected");
var D,ka=new WebAssembly.Table({initial:54,maximum:54,element:"anyfunc"}),la=!1,ma="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function na(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ma)return ma.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|l:(e&7)<<18|h<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function E(a,b){return a?na(F,a,b):""}
function G(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var l=a.charCodeAt(h);if(55296<=l&&57343>=l){var n=a.charCodeAt(++h);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function pa(a){var b=oa(a)+1,c=qa(b);G(a,ra,c,b);return c}function sa(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,ra,F,ta,ua,H,va,I,J;
function wa(a){buffer=a;f.HEAP8=ra=new Int8Array(a);f.HEAP16=ta=new Int16Array(a);f.HEAP32=H=new Int32Array(a);f.HEAPU8=F=new Uint8Array(a);f.HEAPU16=ua=new Uint16Array(a);f.HEAPU32=va=new Uint32Array(a);f.HEAPF32=I=new Float32Array(a);f.HEAPF64=J=new Float64Array(a)}var xa=f.TOTAL_MEMORY||33554432;f.wasmMemory?D=f.wasmMemory:D=new WebAssembly.Memory({initial:xa/65536});D&&(buffer=D.buffer);xa=buffer.byteLength;wa(buffer);H[2047896]=13434624;
function ya(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Pb;"number"===typeof c?void 0===b.Hb?f.dynCall_v(c):f.dynCall_vi(c,b.Hb):c(void 0===b.Hb?null:b.Hb)}}}var za=[],Aa=[],Ba=[],Ca=[],Da=[];function Ea(){var a=f.preRun.shift();za.unshift(a)}var K=0,Fa=null,L=null;f.preloadedImages={};f.preloadedAudios={};function z(a){if(f.onAbort)f.onAbort(a);ja(a);A(a);la=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}
function Ga(){var a=M;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var M="bombjack-ui.wasm";if(!Ga()){var Ha=M;M=f.locateFile?f.locateFile(Ha,x):x+Ha}function Ia(){try{if(B)return new Uint8Array(B);if(y)return y(M);throw"both async and sync fetching of the wasm failed";}catch(a){z(a)}}
function Ja(){return B||!u&&!v||"function"!==typeof fetch?new Promise(function(a){a(Ia())}):fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ia()})}Aa.push({Pb:function(){Ka()}});var La=[null,[],[]],Ma=0;function Na(){Ma+=4;return H[Ma-4>>2]}var Oa={},Pa=0,Qa=0,N=0,Ra=0,Sa=0,Ta=null,Ua=null,Va=!1;function Wa(){for(var a=O.length-1;0<=a;--a)Xa(a);O=[];Ya=[]}var Ya=[];
function Za(){if($a&&ab.zb)for(var a=0;a<Ya.length;++a){var b=Ya[a];Ya.splice(a,1);--a;b.bc.apply(this,b.Ub)}}var $a=0,ab=null,O=[];function bb(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function Xa(a){var b=O[a];b.target.removeEventListener(b.yb,b.Nb,b.Ab);O.splice(a,1)}
function P(a){function b(b){++$a;ab=a;Za();a.Cb(b);Za();--$a}if(a.Bb)a.Nb=b,a.target.addEventListener(a.yb,b,a.Ab),O.push(a),Va||(Ca.push(Wa),Va=!0);else for(var c=0;c<O.length;++c)O[c].target==a.target&&O[c].yb==a.yb&&Xa(c--)}var cb=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function R(a){try{if(!a)return window;"number"===typeof a&&(a=cb[a]||E(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?f.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function db(a){"number"===typeof a&&(a=E(a));return a&&"#canvas"!==a?"undefined"!==typeof eb&&fb[a]?fb[a]:R(a):"undefined"!==typeof eb&&fb.canvas?fb.canvas:f.canvas}
function gb(a,b,c,d,e,h){Pa||(Pa=S(164));a={target:R(a),zb:bb()?!1:!0,yb:h,Bb:d,Cb:function(a){a=a||event;var c=Pa;G(a.key?a.key:"",F,c+0,32);G(a.code?a.code:"",F,c+32,32);H[c+64>>2]=a.location;H[c+68>>2]=a.ctrlKey;H[c+72>>2]=a.shiftKey;H[c+76>>2]=a.altKey;H[c+80>>2]=a.metaKey;H[c+84>>2]=a.repeat;G(a.locale?a.locale:"",F,c+88,32);G(a.char?a.char:"",F,c+120,32);H[c+152>>2]=a.charCode;H[c+156>>2]=a.keyCode;H[c+160>>2]=a.which;T(d,e,c,b)&&a.preventDefault()},Ab:c};P(a)}
function hb(a,b,c){J[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();H[a+8>>2]=b.screenX;H[a+12>>2]=b.screenY;H[a+16>>2]=b.clientX;H[a+20>>2]=b.clientY;H[a+24>>2]=b.ctrlKey;H[a+28>>2]=b.shiftKey;H[a+32>>2]=b.altKey;H[a+36>>2]=b.metaKey;ta[a+40>>1]=b.button;ta[a+42>>1]=b.buttons;H[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-Ta;H[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-Ua;if(f.canvas){var d=f.canvas.getBoundingClientRect();
H[a+60>>2]=b.clientX-d.left;H[a+64>>2]=b.clientY-d.top}else H[a+60>>2]=0,H[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},H[a+52>>2]=b.clientX-d.left,H[a+56>>2]=b.clientY-d.top):(H[a+52>>2]=0,H[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(Ta=b.screenX,Ua=b.screenY)}
function ib(a,b,c,d,e,h){Qa||(Qa=S(72));a=R(a);c={target:a,zb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,yb:h,Bb:d,Cb:function(c){c=c||event;hb(Qa,c,a);T(d,e,Qa,b)&&c.preventDefault()},Ab:c};bb()&&"mousedown"==h&&(c.zb=!1);P(c)}
function jb(a,b,c,d){Ra||(Ra=S(36));a=R(a);P({target:a,zb:!1,yb:"resize",Bb:d,Cb:function(c){c=c||event;if(c.target==a){var e=0<pageXOffset||0<pageYOffset?[pageXOffset,pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],l=Ra;H[l>>2]=c.detail;H[l+4>>2]=document.body.clientWidth;H[l+8>>2]=document.body.clientHeight;
H[l+12>>2]=innerWidth;H[l+16>>2]=innerHeight;H[l+20>>2]=outerWidth;H[l+24>>2]=outerHeight;H[l+28>>2]=e[0];H[l+32>>2]=e[1];T(d,10,l,b)&&c.preventDefault()}},Ab:c})}
function kb(a,b,c,d,e,h){Sa||(Sa=S(1684));a=R(a);P({target:a,zb:"touchstart"==h||"touchend"==h,yb:h,Bb:d,Cb:function(c){c=c||event;for(var h={},l=0;l<c.touches.length;++l){var p=c.touches[l];p.Jb=!1;h[p.identifier]=p}for(l=0;l<c.changedTouches.length;++l)p=c.changedTouches[l],h[p.identifier]=p,p.Jb=!0;for(l=0;l<c.targetTouches.length;++l)p=c.targetTouches[l],h[p.identifier].Sb=!0;var r=p=Sa;H[r+4>>2]=c.ctrlKey;H[r+8>>2]=c.shiftKey;H[r+12>>2]=c.altKey;H[r+16>>2]=c.metaKey;r+=20;var Q=f.canvas?f.canvas.getBoundingClientRect():
void 0,ob=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},pb=0;for(l in h){var w=h[l];H[r>>2]=w.identifier;H[r+4>>2]=w.screenX;H[r+8>>2]=w.screenY;H[r+12>>2]=w.clientX;H[r+16>>2]=w.clientY;H[r+20>>2]=w.pageX;H[r+24>>2]=w.pageY;H[r+28>>2]=w.Jb;H[r+32>>2]=w.Sb;Q?(H[r+44>>2]=w.clientX-Q.left,H[r+48>>2]=w.clientY-Q.top):(H[r+44>>2]=0,H[r+48>>2]=0);H[r+36>>2]=w.clientX-ob.left;H[r+40>>2]=w.clientY-ob.top;r+=52;if(32<=++pb)break}H[p>>2]=pb;T(d,e,p,b)&&c.preventDefault()},Ab:c})}
function lb(a,b,c,d,e,h){a||(a=f.canvas);a={target:R(a),zb:!1,yb:h,Bb:d,Cb:function(a){a=a||event;T(d,e,0,b)&&a.preventDefault()},Ab:c};P(a)}
function mb(a,b,c,d,e){function h(c){c=c||event;hb(N,c,a);J[N+72>>3]=c.wheelDeltaX||0;J[N+80>>3]=-(c.wheelDeltaY||c.wheelDelta);J[N+88>>3]=0;H[N+96>>2]=0;T(d,9,N,b)&&c.preventDefault()}function l(c){c=c||event;var e=N;hb(e,c,a);J[e+72>>3]=c.deltaX;J[e+80>>3]=c.deltaY;J[e+88>>3]=c.deltaZ;H[e+96>>2]=c.deltaMode;T(d,9,e,b)&&c.preventDefault()}N||(N=S(104));P({target:a,zb:!0,yb:e,Bb:d,Cb:"wheel"==e?l:h,Ab:c})}var nb=1,qb=0,rb=[],U=[],sb=[],tb=[],ub=[],V=[],W=[],vb={},wb=null,fb={},xb={},yb={};
function X(a){qb||(qb=a)}function zb(a){for(var b=nb++,c=a.length;c<b;c++)a[c]=null;return b}var Ab=null,Y=[0];function Bb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(a,d){b.vertexAttribDivisorANGLE(a,d)},a.drawArraysInstanced=function(a,d,e,h){b.drawArraysInstancedANGLE(a,d,e,h)},a.drawElementsInstanced=function(a,d,e,h,l){b.drawElementsInstancedANGLE(a,d,e,h,l)})}
function Cb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(a){b.deleteVertexArrayOES(a)},a.bindVertexArray=function(a){b.bindVertexArrayOES(a)},a.isVertexArray=function(a){return b.isVertexArrayOES(a)})}function Db(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(a,d){b.drawBuffersWEBGL(a,d)})}
function Eb(a){a||(a=wb);if(!a.Qb){a.Qb=!0;var b=a.Gb;2>a.version&&(Bb(b),Cb(b),Db(b));b.Wb=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(a){-1!=c.indexOf(a)&&b.getExtension(a)})}}var eb={},Fb,Gb,Hb=["default","low-power","high-performance"];function Ib(a,b,c,d){for(var e=0;e<a;e++){var h=Z[c](),l=h&&zb(d);h?(h.name=l,d[l]=h):X(1282);H[b+4*e>>2]=l}}
function Jb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":X(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:X(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)H[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){X(1280);A("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:X(1280);A("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}H[b>>2]=c}else X(1281)}function Kb(a){var b=oa(a)+1,c=S(b);G(a,F,c,b);return c}
var Lb={6402:1,6406:1,6407:3,6408:4,6409:1,6410:2,35904:3,35906:4},Mb={5121:1,5123:2,5125:4,5126:4,32819:2,32820:2,33635:2,34042:4,36193:2};function Nb(a,b,c,d,e){if(b=Lb[b]*Mb[a])switch(c=e+d*(c*b+4-1&-4),a){case 5121:return F.subarray(e,c);case 5126:return I.subarray(e>>2,c>>2);case 5125:case 34042:return va.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return ua.subarray(e>>1,c>>1);default:X(1280)}else X(1280)}var Z;Ab=new Float32Array(256);
for(var Ob=0;256>Ob;Ob++)Y[Ob]=Ab.subarray(0,Ob+1);
var Tb={Za:function(){},_:function(a,b){Ma=b;return 0},cb:function(a,b){Ma=b;try{var c=E(Na()),d=Na(),e=Na();return(void 0).open(c,d,e).fd}catch(h){return z(h),-h.Lb}},bb:function(a,b){Ma=b;return 0},B:function(){},Y:function(){return devicePixelRatio||1},aa:function(a,b,c){a=a?R(a):f.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),J[b>>3]=a.right-a.left,J[c>>3]=a.bottom-a.top):(J[b>>3]=a.clientWidth,J[c>>3]=a.clientHeight);return 0},Wa:function(a,b,c){F.set(F.subarray(b,
b+c),a)},Ja:function(a,b){function c(d){Pb(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Xa:function(a){if(2147418112<a)return!1;for(var b=Math.max(ra.length,16777216);b<a;)536870912>=b?b=sa(2*b):b=Math.min(sa((3*b+2147483648)/4),2147418112);a:{try{D.grow(b-buffer.byteLength+65535>>16);wa(D.buffer);var c=1;break a}catch(d){}c=void 0}return c?!0:!1},V:function(a,b,c){a=db(a);if(!a)return-4;a.width=b;a.height=c;return 0},Sa:function(a,b,c,d){gb(a,b,c,d,2,"keydown");return 0},Qa:function(a,
b,c,d){gb(a,b,c,d,1,"keypress");return 0},Ra:function(a,b,c,d){gb(a,b,c,d,3,"keyup");return 0},qa:function(a,b,c,d){ib(a,b,c,d,5,"mousedown");return 0},_a:function(a,b,c,d){ib(a,b,c,d,33,"mouseenter");return 0},Ua:function(a,b,c,d){ib(a,b,c,d,34,"mouseleave");return 0},hb:function(a,b,c,d){ib(a,b,c,d,8,"mousemove");return 0},ga:function(a,b,c,d){ib(a,b,c,d,6,"mouseup");return 0},ib:function(a,b,c,d){jb(a,b,c,d);return 0},Ma:function(a,b,c,d){kb(a,b,c,d,25,"touchcancel");return 0},Na:function(a,b,
c,d){kb(a,b,c,d,23,"touchend");return 0},Oa:function(a,b,c,d){kb(a,b,c,d,24,"touchmove");return 0},Pa:function(a,b,c,d){kb(a,b,c,d,22,"touchstart");return 0},La:function(a,b,c,d){lb(a,b,c,d,31,"webglcontextlost");return 0},Ka:function(a,b,c,d){lb(a,b,c,d,32,"webglcontextrestored");return 0},Ta:function(a,b,c,d){a=R(a);return"undefined"!==typeof a.onwheel?(mb(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(mb(a,b,c,d,"mousewheel"),0):-1},O:function(a,b){var c={};b>>=2;c.alpha=!!H[b];c.depth=
!!H[b+1];c.stencil=!!H[b+2];c.antialias=!!H[b+3];c.premultipliedAlpha=!!H[b+4];c.preserveDrawingBuffer=!!H[b+5];c.powerPreference=Hb[H[b+6]];c.failIfMajorPerformanceCaveat=!!H[b+7];c.Rb=H[b+8];c.Zb=H[b+9];c.Kb=H[b+10];c.Ob=H[b+11];c.$b=H[b+12];c.ac=H[b+13];a=db(a);if(!a||c.Ob)c=0;else if(a=a.getContext("webgl",c)||a.getContext("experimental-webgl",c)){b=S(8);var d={handle:b,attributes:c,version:c.Rb,Gb:a};a.canvas&&(a.canvas.Tb=d);vb[b]=d;("undefined"===typeof c.Kb||c.Kb)&&Eb(d);c=b}else c=0;return c},
sa:function(a,b){a=vb[a];b=E(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b?Bb(Z):"OES_vertex_array_object"==b?Cb(Z):"WEBGL_draw_buffers"==b&&Db(Z);return!!a.Gb.getExtension(b)},Ca:function(a){a>>=2;for(var b=0;14>b;++b)H[a+b]=0;H[a]=H[a+1]=H[a+3]=H[a+4]=H[a+8]=H[a+10]=1},xa:function(a){wb=vb[a];f.Vb=Z=wb&&wb.Gb;return!a||Z?0:-5},Z:function(){return 0},$a:function(a,b,c,d){try{var e=Oa.Yb(a),h=Oa.Xb(e,b,c);H[d>>2]=h;return 0}catch(l){return z(l),l.Lb}},Va:function(){return 0},
ab:function(a,b,c,d){try{for(var e=0,h=0;h<c;h++){for(var l=H[b+8*h>>2],n=H[b+(8*h+4)>>2],q=0;q<n;q++){var p=F[l+q],r=La[a];0===p||10===p?((1===a?ja:A)(na(r,0)),r.length=0):r.push(p)}e+=n}H[d>>2]=e;return 0}catch(Q){return z(Q),Q.Lb}},g:function(a){Z.activeTexture(a)},Q:function(a,b){Z.attachShader(U[a],W[b])},b:function(a,b){Z.bindBuffer(a,rb[b])},f:function(a,b){Z.bindFramebuffer(a,sb[b])},Fa:function(a,b){Z.bindRenderbuffer(a,tb[b])},a:function(a,b){Z.bindTexture(a,ub[b])},H:function(a,b,c,d){Z.blendColor(a,
b,c,d)},I:function(a,b){Z.blendEquationSeparate(a,b)},J:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},T:function(a,b,c,d){Z.bufferData(a,c?F.subarray(c,c+b):b,d)},t:function(a,b,c,d){Z.bufferSubData(a,b,F.subarray(d,d+c))},m:function(a){return Z.checkFramebufferStatus(a)},ta:function(a){Z.clear(a)},wa:function(a,b,c,d){Z.clearColor(a,b,c,d)},va:function(a){Z.clearDepth(a)},ua:function(a){Z.clearStencil(a)},y:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},eb:function(a){Z.compileShader(W[a])},S:function(a,
b,c,d,e,h,l,n){Z.compressedTexImage2D(a,b,c,d,e,h,n?F.subarray(n,n+l):null)},Ba:function(){var a=zb(U),b=Z.createProgram();b.name=a;U[a]=b;return a},gb:function(a){var b=zb(W);W[b]=Z.createShader(a);return b},G:function(a){Z.cullFace(a)},X:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],e=rb[d];e&&(Z.deleteBuffer(e),e.name=0,rb[d]=null,d==Fb&&(Fb=0),d==Gb&&(Gb=0))}},j:function(a,b){for(var c=0;c<a;++c){var d=H[b+4*c>>2],e=sb[d];e&&(Z.deleteFramebuffer(e),e.name=0,sb[d]=null)}},A:function(a){if(a){var b=
U[a];b?(Z.deleteProgram(b),b.name=0,U[a]=null,xb[a]=null):X(1281)}},u:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],e=tb[d];e&&(Z.deleteRenderbuffer(e),e.name=0,tb[d]=null)}},z:function(a){if(a){var b=W[a];b?(Z.deleteShader(b),W[a]=null):X(1281)}},W:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],e=ub[d];e&&(Z.deleteTexture(e),e.name=0,ub[d]=null)}},w:function(a){Z.depthFunc(a)},x:function(a){Z.depthMask(!!a)},d:function(a){Z.disable(a)},C:function(a){Z.disableVertexAttribArray(a)},ha:function(a,
b,c){Z.drawArrays(a,b,c)},ia:function(a,b,c,d){Z.drawElements(a,b,c,d)},e:function(a){Z.enable(a)},oa:function(a){Z.enableVertexAttribArray(a)},k:function(a,b,c,d){Z.framebufferRenderbuffer(a,b,c,tb[d])},c:function(a,b,c,d,e){Z.framebufferTexture2D(a,b,c,ub[d],e)},F:function(a){Z.frontFace(a)},U:function(a,b){Ib(a,b,"createBuffer",rb)},n:function(a,b){Ib(a,b,"createFramebuffer",sb)},Ga:function(a,b){Ib(a,b,"createRenderbuffer",tb)},Da:function(a,b){Ib(a,b,"createTexture",ub)},ya:function(a,b){return Z.getAttribLocation(U[a],
E(b))},i:function(a,b){Jb(a,b)},za:function(a,b,c,d){a=Z.getProgramInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,F,d,b):0;c&&(H[c>>2]=b)},P:function(a,b,c){if(c)if(a>=nb)X(1281);else{var d=xb[a];if(d)if(35716==b)a=Z.getProgramInfoLog(U[a]),null===a&&(a="(unknown error)"),H[c>>2]=a.length+1;else if(35719==b)H[c>>2]=d.Ib;else if(35722==b){if(-1==d.Eb){a=U[a];var e=Z.getProgramParameter(a,35721);for(b=d.Eb=0;b<e;++b)d.Eb=Math.max(d.Eb,Z.getActiveAttrib(a,b).name.length+1)}H[c>>2]=d.Eb}else if(35381==
b){if(-1==d.Fb)for(a=U[a],e=Z.getProgramParameter(a,35382),b=d.Fb=0;b<e;++b)d.Fb=Math.max(d.Fb,Z.getActiveUniformBlockName(a,b).length+1);H[c>>2]=d.Fb}else H[c>>2]=Z.getProgramParameter(U[a],b);else X(1282)}else X(1281)},db:function(a,b,c,d){a=Z.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,F,d,b):0;c&&(H[c>>2]=b)},$:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),H[c>>2]=a.length+1):35720==b?(a=Z.getShaderSource(W[a]),H[c>>2]=null===a||
0==a.length?0:a.length+1):H[c>>2]=Z.getShaderParameter(W[a],b):X(1281)},Ha:function(a){if(yb[a])return yb[a];switch(a){case 7939:var b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(a){return"GL_"+a}));b=Kb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||X(1280);b=Kb(b);break;case 7938:b=Kb("OpenGL ES 2.0 ("+Z.getParameter(Z.VERSION)+")");break;case 35724:b=Z.getParameter(Z.SHADING_LANGUAGE_VERSION);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Kb(b);break;default:return X(1280),0}return yb[a]=b},l:function(a,b){b=E(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=xb[a]&&xb[a].Mb[b])&&0<=c&&c<a[0]?a[1]+c:-1},Aa:function(a){Z.linkProgram(U[a]);var b=U[a];a=xb[a]={Mb:{},Ib:0,Eb:-1,Fb:-1};for(var c=a.Mb,d=Z.getProgramParameter(b,35718),e=0;e<d;++e){var h=Z.getActiveUniform(b,e),l=h.name;a.Ib=
Math.max(a.Ib,l.length+1);"]"==l.slice(-1)&&(l=l.slice(0,l.lastIndexOf("[")));var n=Z.getUniformLocation(b,l);if(n){var q=zb(V);c[l]=[h.size,q];V[q]=n;for(var p=1;p<h.size;++p)n=Z.getUniformLocation(b,l+"["+p+"]"),q=zb(V),V[q]=n}}},E:function(a,b){Z.polygonOffset(a,b)},Ea:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},M:function(a,b,c,d){Z.scissor(a,b,c,d)},fb:function(a,b,c,d){for(var e="",h=0;h<b;++h){var l=d?H[d+4*h>>2]:-1;e+=E(H[c+4*h>>2],0>l?void 0:l)}Z.shaderSource(W[a],e)},fa:function(a,
b,c){Z.stencilFunc(a,b,c)},L:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},v:function(a){Z.stencilMask(a)},ea:function(a,b,c){Z.stencilOp(a,b,c)},K:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},R:function(a,b,c,d,e,h,l,n,q){Z.texImage2D(a,b,c,d,e,h,l,n,q?Nb(n,l,d,e,q):null)},h:function(a,b,c){Z.texParameteri(a,b,c)},s:function(a,b,c,d,e,h,l,n,q){var p=null;q&&(p=Nb(n,l,e,h,q));Z.texSubImage2D(a,b,c,d,e,h,l,n,p)},na:function(a,b,c){if(256>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=I[c+4*e>>2];else d=
I.subarray(c>>2,c+4*b>>2);Z.uniform1fv(V[a],d)},D:function(a,b){Z.uniform1i(V[a],b)},ma:function(a,b,c){if(256>=2*b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=I[c+4*e>>2],d[e+1]=I[c+(4*e+4)>>2];else d=I.subarray(c>>2,c+8*b>>2);Z.uniform2fv(V[a],d)},la:function(a,b,c){if(256>=3*b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=I[c+4*e>>2],d[e+1]=I[c+(4*e+4)>>2],d[e+2]=I[c+(4*e+8)>>2];else d=I.subarray(c>>2,c+12*b>>2);Z.uniform3fv(V[a],d)},ka:function(a,b,c){if(256>=4*b)for(var d=Y[4*b-1],e=0;e<4*b;e+=4)d[e]=I[c+
4*e>>2],d[e+1]=I[c+(4*e+4)>>2],d[e+2]=I[c+(4*e+8)>>2],d[e+3]=I[c+(4*e+12)>>2];else d=I.subarray(c>>2,c+16*b>>2);Z.uniform4fv(V[a],d)},ja:function(a,b,c,d){if(256>=16*b)for(var e=Y[16*b-1],h=0;h<16*b;h+=16)e[h]=I[d+4*h>>2],e[h+1]=I[d+(4*h+4)>>2],e[h+2]=I[d+(4*h+8)>>2],e[h+3]=I[d+(4*h+12)>>2],e[h+4]=I[d+(4*h+16)>>2],e[h+5]=I[d+(4*h+20)>>2],e[h+6]=I[d+(4*h+24)>>2],e[h+7]=I[d+(4*h+28)>>2],e[h+8]=I[d+(4*h+32)>>2],e[h+9]=I[d+(4*h+36)>>2],e[h+10]=I[d+(4*h+40)>>2],e[h+11]=I[d+(4*h+44)>>2],e[h+12]=I[d+(4*
h+48)>>2],e[h+13]=I[d+(4*h+52)>>2],e[h+14]=I[d+(4*h+56)>>2],e[h+15]=I[d+(4*h+60)>>2];else e=I.subarray(d>>2,d+64*b>>2);Z.uniformMatrix4fv(V[a],!!c,e)},ra:function(a){Z.useProgram(U[a])},Ya:function(a,b){Z.vertexAttribDivisor(a,b)},pa:function(a,b,c,d,e,h){Z.vertexAttribPointer(a,b,c,!!d,e,h)},N:function(a,b,c,d){Z.viewport(a,b,c,d)},memory:D,q:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Qb()});
document.body.append(a)},p:function(){document.getElementById("_sokol_app_input_element").focus()},Ia:function(){window.addEventListener("beforeunload",function(a){0!=Rb()&&(a.preventDefault(),a.returnValue=" ")})},o:function(){document.getElementById("_sokol_app_input_element").blur()},ba:function(){return f.Db?f.Db.bufferSize:0},da:function(a,b,c){f.xb=null;f.Db=null;"undefined"!==typeof AudioContext?(f.xb=new AudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created AudioContext")):
"undefined"!==typeof webkitAudioContext?(f.xb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created webkitAudioContext")):(f.xb=null,console.log("sokol_audio.h: no WebAudio support"));return f.xb?(console.log("sokol_audio.h: sample rate ",f.xb.sampleRate),f.Db=f.xb.createScriptProcessor(c,0,b),f.Db.onaudioprocess=function(a){var b=a.outputBuffer.length,c=Sb(b);if(c)for(var d=a.outputBuffer.numberOfChannels,n=0;n<d;n++)for(var q=a.outputBuffer.getChannelData(n),
p=0;p<b;p++)q[p]=I[(c>>2)+(d*p+n)]},f.Db.connect(f.xb.destination),a=function(){f.xb&&"suspended"===f.xb.state&&f.xb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},ca:function(){return f.xb?f.xb.sampleRate:0},r:function(){return performance.now()},table:ka},Ub=function(){function a(a){f.asm=a.exports;K--;f.monitorRunDependencies&&f.monitorRunDependencies(K);0==K&&(null!==Fa&&(clearInterval(Fa),
Fa=null),L&&(a=L,L=null,a()))}function b(b){a(b.instance)}function c(a){return Ja().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){A("failed to asynchronously prepare wasm: "+a);z(a)})}var d={env:Tb,wasi_unstable:Tb};K++;f.monitorRunDependencies&&f.monitorRunDependencies(K);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return A("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(B||"function"!==typeof WebAssembly.instantiateStreaming||
Ga()||"function"!==typeof fetch)return c(b);fetch(M,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){A("wasm streaming compile failed: "+a);A("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();f.asm=Ub;var Ka=f.___wasm_call_ctors=function(){return f.asm.jb.apply(null,arguments)};f._emsc_load_data=function(){return f.asm.kb.apply(null,arguments)};
var Qb=f.__sapp_emsc_notify_keyboard_hidden=function(){return f.asm.lb.apply(null,arguments)},Rb=f.__sapp_html5_get_ask_leave_site=function(){return f.asm.mb.apply(null,arguments)};f._main=function(){return f.asm.nb.apply(null,arguments)};var S=f._malloc=function(){return f.asm.ob.apply(null,arguments)};f._free=function(){return f.asm.pb.apply(null,arguments)};var Sb=f.__saudio_emsc_pull=function(){return f.asm.qb.apply(null,arguments)};f.__sargs_add_kvp=function(){return f.asm.rb.apply(null,arguments)};
var qa=f.stackAlloc=function(){return f.asm.sb.apply(null,arguments)};f.dynCall_vi=function(){return f.asm.tb.apply(null,arguments)};f.dynCall_v=function(){return f.asm.ub.apply(null,arguments)};var T=f.dynCall_iiii=function(){return f.asm.vb.apply(null,arguments)},Pb=f.dynCall_idi=function(){return f.asm.wb.apply(null,arguments)};f.asm=Ub;var Vb;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}L=function Wb(){Vb||Xb();Vb||(L=Wb)};
function Xb(a){function b(){if(!Vb&&(Vb=!0,!la)){ya(Aa);ya(Ba);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Yb){var b=a,d=f._main;b=b||[];var e=b.length+1,h=qa(4*(e+1));H[h>>2]=pa(aa);for(var l=1;l<e;l++)H[(h>>2)+l]=pa(b[l-1]);H[(h>>2)+e]=0;try{var n=d(e,h);if(!C||0!==n){if(!C&&(la=!0,f.onExit))f.onExit(n);t(n,new ia(n))}}catch(q){q instanceof ia||("SimulateInfiniteLoop"==q?C=!0:((b=q)&&"object"===typeof q&&q.stack&&(b=[q,q.stack]),A("exception thrown: "+b),t(1,q)))}finally{}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=f.postRun.shift(),Da.unshift(b);ya(Da)}}a=a||m;if(!(0<K)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ea();ya(za);0<K||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Xb;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Yb=!0;f.noInitialRun&&(Yb=!1);C=!0;Xb();
