
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var k={},l;for(l in f)f.hasOwnProperty(l)&&(k[l]=f[l]);var aa=[],ba="./this.program";function r(a,b){throw b;}var ca="object"===typeof window,t="function"===typeof importScripts,u="",da,v,ea,w,x;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)u=t?require("path").dirname(u)+"/":__dirname+"/",da=function(a,b){w||(w=require("fs"));x||(x=require("path"));a=x.normalize(a);return w.readFileSync(a,b?null:"utf8")},ea=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||y("Assertion failed: undefined");return a},v=function(a,b,c){w||(w=require("fs"));x||(x=require("path"));a=x.normalize(a);w.readFile(a,function(d,e){d?c(d):b(e.buffer)})},
1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/")),aa=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof fa))throw a;}),process.on("unhandledRejection",y),r=function(a,b){if(noExitRuntime||0<ha)throw process.exitCode=a,b;process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ca||t)t?u=self.location.href:"undefined"!==typeof document&&document.currentScript&&(u=document.currentScript.src),
u=0!==u.indexOf("blob:")?u.substr(0,u.lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),v=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};
var ia=f.print||console.log.bind(console),A=f.printErr||console.warn.bind(console);for(l in k)k.hasOwnProperty(l)&&(f[l]=k[l]);k=null;f.arguments&&(aa=f.arguments);f.thisProgram&&(ba=f.thisProgram);f.quit&&(r=f.quit);var B;f.wasmBinary&&(B=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&y("no native wasm support detected");var ja,ka=!1;
function la(a){var b=f["_"+a];b||y("Assertion failed: Cannot call unknown function "+(a+", make sure it is exported"));return b}function ma(a,b,c){var d={string:function(n){var p=0;if(null!==n&&void 0!==n&&0!==n){var q=(n.length<<2)+1;p=C(q);D(n,E,p,q)}return p},array:function(n){var p=C(n.length);na.set(n,p);return p}};a=la(a);var e=[],h=0;if(c)for(var g=0;g<c.length;g++){var m=d[b[g]];m?(0===h&&(h=oa()),e[g]=m(c[g])):e[g]=c[g]}b=a.apply(null,e);b=function(n){0!==h&&pa(h);return n}(b)}
var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ra(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&qa)return qa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function F(a,b){return a?ra(E,a,b):""}
function D(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ta(a){var b=sa(a)+1,c=C(b);D(a,na,c,b);return c}var ua,na,E,va,wa,G,xa,H,I;
function ya(){var a=ja.buffer;ua=a;f.HEAP8=na=new Int8Array(a);f.HEAP16=va=new Int16Array(a);f.HEAP32=G=new Int32Array(a);f.HEAPU8=E=new Uint8Array(a);f.HEAPU16=wa=new Uint16Array(a);f.HEAPU32=xa=new Uint32Array(a);f.HEAPF32=H=new Float32Array(a);f.HEAPF64=I=new Float64Array(a)}var J,za=[],Aa=[],Ba=[],Ca=[],Da=[],ha=0;function Ea(){var a=f.preRun.shift();za.unshift(a)}var K=0,Fa=null,L=null;f.preloadedImages={};f.preloadedAudios={};
function y(a){if(f.onAbort)f.onAbort(a);A(a);ka=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ga(){return M.startsWith("data:application/octet-stream;base64,")}var M;M="bombjack-ui.wasm";if(!Ga()){var Ha=M;M=f.locateFile?f.locateFile(Ha,u):u+Ha}function Ia(){var a=M;try{if(a==M&&B)return new Uint8Array(B);if(ea)return ea(a);throw"both async and sync fetching of the wasm failed";}catch(b){y(b)}}
function Ja(){if(!B&&(ca||t)){if("function"===typeof fetch&&!M.startsWith("file://"))return fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ia()});if(v)return new Promise(function(a,b){v(M,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ia()})}
function Ka(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Ec;"number"===typeof c?void 0===b.cc?J.get(c)():J.get(c)(b.cc):c(void 0===b.cc?null:b.cc)}}}var La=[null,[],[]],Ma={},Na=0;function Oa(){for(var a=N.length-1;0<=a;--a)Pa(a);N=[];Qa=[]}var Qa=[];function Ra(){if(Na&&Sa.Yb)for(var a=0;a<Qa.length;++a){var b=Qa[a];Qa.splice(a,1);--a;b.Nc.apply(null,b.Ac)}}var N=[];function Pa(a){var b=N[a];b.target.removeEventListener(b.Rb,b.tc,b.Sb);N.splice(a,1)}
function O(a){function b(d){++Na;Sa=a;Ra();a.Ub(d);Ra();--Na}if(a.Tb)a.tc=b,a.target.addEventListener(a.Rb,b,a.Sb),N.push(a),Ta||(Ca.push(Oa),Ta=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Rb==a.Rb&&Pa(c--)}function Ua(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var Ta,Sa,Va,Wa,Xa,Ya,Za,$a,ab,bb=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function P(a){a=2<a?F(a):a;return bb[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function cb(a){return 0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function db(a,b,c,d,e,h){Va||(Va=Q(256));a={target:P(a),Rb:h,Tb:d,Ub:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Va;D(Ua(g.target),E,n+0,128);D(m,E,n+128,128);J.get(d)(e,n,b)&&g.preventDefault()},Sb:c};O(a)}
function eb(a,b,c,d,e,h){Wa||(Wa=Q(176));a={target:P(a),Yb:!0,Rb:h,Tb:d,Ub:function(g){var m=Wa;I[m>>3]=g.timeStamp;var n=m>>2;G[n+2]=g.location;G[n+3]=g.ctrlKey;G[n+4]=g.shiftKey;G[n+5]=g.altKey;G[n+6]=g.metaKey;G[n+7]=g.repeat;G[n+8]=g.charCode;G[n+9]=g.keyCode;G[n+10]=g.which;D(g.key||"",E,m+44,32);D(g.code||"",E,m+76,32);D(g.char||"",E,m+108,32);D(g.locale||"",E,m+140,32);J.get(d)(e,m,b)&&g.preventDefault()},Sb:c};O(a)}
function fb(a,b,c){I[a>>3]=b.timeStamp;a>>=2;G[a+2]=b.screenX;G[a+3]=b.screenY;G[a+4]=b.clientX;G[a+5]=b.clientY;G[a+6]=b.ctrlKey;G[a+7]=b.shiftKey;G[a+8]=b.altKey;G[a+9]=b.metaKey;va[2*a+20]=b.button;va[2*a+21]=b.buttons;G[a+11]=b.movementX;G[a+12]=b.movementY;c=cb(c);G[a+13]=b.clientX-c.left;G[a+14]=b.clientY-c.top}
function R(a,b,c,d,e,h){Xa||(Xa=Q(72));a=P(a);O({target:a,Yb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Rb:h,Tb:d,Ub:function(g){g=g||event;fb(Xa,g,a);J.get(d)(e,Xa,b)&&g.preventDefault()},Sb:c})}function gb(a,b,c,d,e){Ya||(Ya=Q(260));O({target:a,Rb:e,Tb:d,Ub:function(h){h=h||event;var g=Ya,m=document.pointerLockElement||document.ec||document.hc||document.fc;G[g>>2]=!!m;var n=m&&m.id?m.id:"";D(Ua(m),E,g+4,128);D(n,E,g+132,128);J.get(d)(20,g,b)&&h.preventDefault()},Sb:c})}
function hb(a,b,c,d,e){O({target:a,Rb:e,Tb:d,Ub:function(h){h=h||event;J.get(d)(38,0,b)&&h.preventDefault()},Sb:c})}
function ib(a,b,c,d){Za||(Za=Q(36));a=P(a);O({target:a,Rb:"resize",Tb:d,Ub:function(e){e=e||event;if(e.target==a){var h=document.body;if(h){var g=Za;G[g>>2]=e.detail;G[g+4>>2]=h.clientWidth;G[g+8>>2]=h.clientHeight;G[g+12>>2]=innerWidth;G[g+16>>2]=innerHeight;G[g+20>>2]=outerWidth;G[g+24>>2]=outerHeight;G[g+28>>2]=pageXOffset;G[g+32>>2]=pageYOffset;J.get(d)(10,g,b)&&e.preventDefault()}}},Sb:c})}
function jb(a,b,c,d,e,h){$a||($a=Q(1696));a=P(a);O({target:a,Yb:"touchstart"==h||"touchend"==h,Rb:h,Tb:d,Ub:function(g){for(var m={},n=g.touches,p=0;p<n.length;++p){var q=n[p];m[q.identifier]=q}n=g.changedTouches;for(p=0;p<n.length;++p)q=n[p],q.wc=1,m[q.identifier]=q;n=g.targetTouches;for(p=0;p<n.length;++p)m[n[p].identifier].yc=1;n=$a;I[n>>3]=g.timeStamp;q=n>>2;G[q+3]=g.ctrlKey;G[q+4]=g.shiftKey;G[q+5]=g.altKey;G[q+6]=g.metaKey;q+=7;var lb=cb(a),mb=0;for(p in m){var z=m[p];G[q]=z.identifier;G[q+
1]=z.screenX;G[q+2]=z.screenY;G[q+3]=z.clientX;G[q+4]=z.clientY;G[q+5]=z.pageX;G[q+6]=z.pageY;G[q+7]=z.wc;G[q+8]=z.yc;G[q+9]=z.clientX-lb.left;G[q+10]=z.clientY-lb.top;q+=13;if(31<++mb)break}G[n+8>>2]=mb;J.get(d)(e,n,b)&&g.preventDefault()},Sb:c})}function kb(a,b,c,d,e,h){a={target:P(a),Rb:h,Tb:d,Ub:function(g){g=g||event;J.get(d)(e,0,b)&&g.preventDefault()},Sb:c};O(a)}
function nb(a,b,c,d){ab||(ab=Q(104));O({target:a,Yb:!0,Rb:"wheel",Tb:d,Ub:function(e){e=e||event;var h=ab;fb(h,e,a);I[h+72>>3]=e.deltaX;I[h+80>>3]=e.deltaY;I[h+88>>3]=e.deltaZ;G[h+96>>2]=e.deltaMode;J.get(d)(9,h,b)&&e.preventDefault()},Sb:c})}
function ob(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function pb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function qb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function rb(a){a.Ic=a.getExtension("WEBGL_multi_draw")}
var sb=1,tb=[],S=[],ub=[],T=[],U=[],V=[],vb=[],wb={};function W(a){xb||(xb=a)}function yb(a){for(var b=sb++,c=a.length;c<b;c++)a[c]=null;return b}function zb(a,b){a.jc||(a.jc=a.getContext,a.getContext=function(d,e){e=a.jc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Ab(c,b):0}function Ab(a,b){var c=yb(vb),d={Gc:c,attributes:b,version:b.xc,bc:a};a.canvas&&(a.canvas.zc=d);vb[c]=d;("undefined"===typeof b.ic||b.ic)&&Bb(d);return c}
function Bb(a){a||(a=Cb);if(!a.vc){a.vc=!0;var b=a.bc;ob(b);pb(b);qb(b);b.Cc=b.getExtension("EXT_disjoint_timer_query");rb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var xb,Cb,Db=["default","low-power","high-performance"];function Eb(a,b,c,d){for(var e=0;e<a;e++){var h=X[c](),g=h&&yb(d);h?(h.name=g,d[g]=h):W(1282);G[b+4*e>>2]=g}}
function Fb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=X.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=X.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:W(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)G[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){W(1280);A("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:W(1280);A("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}G[b>>2]=c}else W(1281)}function Gb(a){var b=sa(a)+1,c=Q(b);D(a,E,c,b);return c}
function Hb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Ib(a,b,c,d,e){a-=5120;a=1==a?E:4==a?G:6==a?H:5==a||28922==a?xa:wa;var h=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(e>>h,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<h)+4-1&-4)>>h)}function Y(a){var b=X.sc;if(b){var c=b.Xb[a];"number"===typeof c&&(b.Xb[a]=c=X.getUniformLocation(b,b.qc[a]+(0<c?"["+c+"]":"")));return c}W(1282)}for(var Z=[],X,Jb=new Float32Array(288),Kb=0;288>Kb;++Kb)Z[Kb]=Jb.subarray(0,Kb+1);
var Qb={ka:function(){return 0},db:function(){return 0},fb:function(){},bb:function(){y()},T:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},ca:function(a,b,c){a=P(a);if(!a)return-4;a=cb(a);I[b>>3]=a.width;I[c>>3]=a.height;return 0},$a:function(a,b,c){E.copyWithin(a,b,b+c)},La:function(a,b){function c(d){J.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ab:function(a){var b=E.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+
.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ja.grow(Math.min(2147483648,d)-ua.byteLength+65535>>>16);ya();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},W:function(a,b,c,d){db(a,b,c,d,12,"blur");return 0},R:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},X:function(a,b,c,d){db(a,b,c,d,13,"focus");return 0},fa:function(a,b,c,d){eb(a,b,c,d,2,"keydown");return 0},da:function(a,b,c,d){eb(a,b,c,d,1,"keypress");return 0},ea:function(a,
b,c,d){eb(a,b,c,d,3,"keyup");return 0},pa:function(a,b,c,d){R(a,b,c,d,5,"mousedown");return 0},ia:function(a,b,c,d){R(a,b,c,d,33,"mouseenter");return 0},ha:function(a,b,c,d){R(a,b,c,d,34,"mouseleave");return 0},ja:function(a,b,c,d){R(a,b,c,d,8,"mousemove");return 0},oa:function(a,b,c,d){R(a,b,c,d,6,"mouseup");return 0},Z:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.ec||document.body.hc||document.body.fc))return-1;a=P(a);if(!a)return-4;gb(a,b,c,
d,"pointerlockchange");gb(a,b,c,d,"mozpointerlockchange");gb(a,b,c,d,"webkitpointerlockchange");gb(a,b,c,d,"mspointerlockchange");return 0},Y:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.ec||document.body.hc||document.body.fc))return-1;a=P(a);if(!a)return-4;hb(a,b,c,d,"pointerlockerror");hb(a,b,c,d,"mozpointerlockerror");hb(a,b,c,d,"webkitpointerlockerror");hb(a,b,c,d,"mspointerlockerror");return 0},Xa:function(a,b,c,d){ib(a,b,c,d);return 0},_:function(a,b,c,d){jb(a,
b,c,d,25,"touchcancel");return 0},$:function(a,b,c,d){jb(a,b,c,d,23,"touchend");return 0},aa:function(a,b,c,d){jb(a,b,c,d,24,"touchmove");return 0},ba:function(a,b,c,d){jb(a,b,c,d,22,"touchstart");return 0},V:function(a,b,c,d){kb(a,b,c,d,31,"webglcontextlost");return 0},U:function(a,b,c,d){kb(a,b,c,d,32,"webglcontextrestored");return 0},ga:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(nb(a,b,c,d),0):-1},I:function(a,b){b>>=2;b={alpha:!!G[b],depth:!!G[b+1],stencil:!!G[b+2],antialias:!!G[b+
3],premultipliedAlpha:!!G[b+4],preserveDrawingBuffer:!!G[b+5],powerPreference:Db[G[b+6]],failIfMajorPerformanceCaveat:!!G[b+7],xc:G[b+8],Hc:G[b+9],ic:G[b+10],uc:G[b+11],Jc:G[b+12],Kc:G[b+13]};a=P(a);return!a||b.uc?0:zb(a,b)},wb:function(a,b){a=vb[a];b=F(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&ob(X);"OES_vertex_array_object"==b&&pb(X);"WEBGL_draw_buffers"==b&&qb(X);"WEBGL_multi_draw"==b&&rb(X);return!!a.bc.getExtension(b)},Ia:function(a){a>>=2;for(var b=0;14>b;++b)G[a+
b]=0;G[a]=G[a+1]=G[a+3]=G[a+4]=G[a+8]=G[a+10]=1},ua:function(a){Cb=vb[a];f.Bc=X=Cb&&Cb.bc;return!a||X?0:-5},la:function(){return 0},cb:function(a,b,c,d){a=Ma.Fc(a);b=Ma.Dc(a,b,c);G[d>>2]=b;return 0},_a:function(){},eb:function(a,b,c,d){for(var e=0,h=0;h<c;h++){for(var g=G[b+8*h>>2],m=G[b+(8*h+4)>>2],n=0;n<m;n++){var p=E[g+n],q=La[a];0===p||10===p?((1===a?ia:A)(ra(q,0)),q.length=0):q.push(p)}e+=m}G[d>>2]=e;return 0},b:function(a){X.activeTexture(a)},H:function(a,b){X.attachShader(S[a],V[b])},c:function(a,
b){X.bindBuffer(a,tb[b])},h:function(a,b){X.bindFramebuffer(a,ub[b])},Fa:function(a,b){X.bindRenderbuffer(a,T[b])},a:function(a,b){X.bindTexture(a,U[b])},N:function(a,b,c,d){X.blendColor(a,b,c,d)},O:function(a,b){X.blendEquationSeparate(a,b)},P:function(a,b,c,d){X.blendFuncSeparate(a,b,c,d)},Ha:function(a,b,c,d){X.bufferData(a,c?E.subarray(c,c+b):b,d)},J:function(a,b,c,d){X.bufferSubData(a,b,E.subarray(d,d+c))},n:function(a){return X.checkFramebufferStatus(a)},sb:function(a){X.clear(a)},vb:function(a,
b,c,d){X.clearColor(a,b,c,d)},ub:function(a){X.clearDepth(a)},tb:function(a){X.clearStencil(a)},p:function(a,b,c,d){X.colorMask(!!a,!!b,!!c,!!d)},va:function(a){X.compileShader(V[a])},Ca:function(a,b,c,d,e,h,g,m){X.compressedTexImage2D(a,b,c,d,e,h,m?E.subarray(m,m+g):null)},Aa:function(){var a=yb(S),b=X.createProgram();b.name=a;b.ac=b.Zb=b.$b=0;b.dc=1;S[a]=b;return a},xa:function(a){var b=yb(V);V[b]=X.createShader(a);return b},K:function(a){X.cullFace(a)},Oa:function(a,b){for(var c=0;c<a;c++){var d=
G[b+4*c>>2],e=tb[d];e&&(X.deleteBuffer(e),e.name=0,tb[d]=null)}},d:function(a,b){for(var c=0;c<a;++c){var d=G[b+4*c>>2],e=ub[d];e&&(X.deleteFramebuffer(e),e.name=0,ub[d]=null)}},A:function(a){if(a){var b=S[a];b?(X.deleteProgram(b),b.name=0,S[a]=null):W(1281)}},S:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],e=T[d];e&&(X.deleteRenderbuffer(e),e.name=0,T[d]=null)}},w:function(a){if(a){var b=V[a];b?(X.deleteShader(b),V[a]=null):W(1281)}},Na:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],
e=U[d];e&&(X.deleteTexture(e),e.name=0,U[d]=null)}},z:function(a){X.depthFunc(a)},y:function(a){X.depthMask(!!a)},e:function(a){X.disable(a)},Q:function(a){X.disableVertexAttribArray(a)},C:function(a,b,c){X.drawArrays(a,b,c)},D:function(a,b,c,d){X.drawElements(a,b,c,d)},i:function(a){X.enable(a)},pb:function(a){X.enableVertexAttribArray(a)},l:function(a,b,c,d){X.framebufferRenderbuffer(a,b,c,T[d])},g:function(a,b,c,d,e){X.framebufferTexture2D(a,b,c,U[d],e)},L:function(a){X.frontFace(a)},Ja:function(a,
b){Eb(a,b,"createBuffer",tb)},o:function(a,b){Eb(a,b,"createFramebuffer",ub)},Ga:function(a,b){Eb(a,b,"createRenderbuffer",T)},Da:function(a,b){Eb(a,b,"createTexture",U)},sa:function(a,b){return X.getAttribLocation(S[a],F(b))},f:function(a,b){Fb(a,b)},ya:function(a,b,c,d){a=X.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(G[c>>2]=b)},G:function(a,b,c){if(c)if(a>=sb)W(1281);else if(a=S[a],35716==b)a=X.getProgramInfoLog(a),null===a&&(a="(unknown error)"),G[c>>2]=a.length+
1;else if(35719==b){if(!a.ac)for(b=0;b<X.getProgramParameter(a,35718);++b)a.ac=Math.max(a.ac,X.getActiveUniform(a,b).name.length+1);G[c>>2]=a.ac}else if(35722==b){if(!a.Zb)for(b=0;b<X.getProgramParameter(a,35721);++b)a.Zb=Math.max(a.Zb,X.getActiveAttrib(a,b).name.length+1);G[c>>2]=a.Zb}else if(35381==b){if(!a.$b)for(b=0;b<X.getProgramParameter(a,35382);++b)a.$b=Math.max(a.$b,X.getActiveUniformBlockName(a,b).length+1);G[c>>2]=a.$b}else G[c>>2]=X.getProgramParameter(a,b);else W(1281)},ta:function(a,
b,c,d){a=X.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(G[c>>2]=b)},E:function(a,b,c){c?35716==b?(a=X.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),G[c>>2]=a?a.length+1:0):35720==b?(a=X.getShaderSource(V[a]),G[c>>2]=a?a.length+1:0):G[c>>2]=X.getShaderParameter(V[a],b):W(1281)},Pa:function(a){var b=wb[a];if(!b){switch(a){case 7939:b=X.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Gb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
X.getParameter(a))||W(1280);b=b&&Gb(b);break;case 7938:b=Gb("OpenGL ES 2.0 ("+X.getParameter(7938)+")");break;case 35724:b=X.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Gb(b);break;default:W(1280)}wb[a]=b}return b},s:function(a,b){b=F(b);if(a=S[a]){var c=a,d=c.Xb,e=c.rc,h;if(!d)for(c.Xb=d={},c.qc={},h=0;h<X.getProgramParameter(c,35718);++h){var g=X.getActiveUniform(c,h);var m=g.name;
g=g.size;var n=Hb(m);n=0<n?m.slice(0,n):m;var p=c.dc;c.dc+=g;e[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.qc[p++]=n}c=a.Xb;d=0;e=b;h=Hb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.rc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||X.getUniformLocation(a,b)))return d}else W(1281);return-1},za:function(a){a=S[a];X.linkProgram(a);a.Xb=0;a.rc={}},M:function(a,b){X.polygonOffset(a,b)},Ea:function(a,b,c,d){X.renderbufferStorage(a,b,c,d)},r:function(a,b,c,d){X.scissor(a,b,c,d)},wa:function(a,b,c,d){for(var e=
"",h=0;h<b;++h){var g=d?G[d+4*h>>2]:-1;e+=F(G[c+4*h>>2],0>g?void 0:g)}X.shaderSource(V[a],e)},Ma:function(a,b,c){X.stencilFunc(a,b,c)},ra:function(a,b,c,d){X.stencilFuncSeparate(a,b,c,d)},x:function(a){X.stencilMask(a)},Ka:function(a,b,c){X.stencilOp(a,b,c)},qa:function(a,b,c,d){X.stencilOpSeparate(a,b,c,d)},Ba:function(a,b,c,d,e,h,g,m,n){X.texImage2D(a,b,c,d,e,h,g,m,n?Ib(m,g,d,e,n):null)},j:function(a,b,c){X.texParameteri(a,b,c)},jb:function(a,b,c,d,e,h,g,m,n){var p=null;n&&(p=Ib(m,g,e,h,n));X.texSubImage2D(a,
b,c,d,e,h,g,m,p)},ob:function(a,b,c){if(288>=b)for(var d=Z[b-1],e=0;e<b;++e)d[e]=H[c+4*e>>2];else d=H.subarray(c>>2,c+4*b>>2);X.uniform1fv(Y(a),d)},F:function(a,b){X.uniform1i(Y(a),b)},nb:function(a,b,c){if(144>=b)for(var d=Z[2*b-1],e=0;e<2*b;e+=2)d[e]=H[c+4*e>>2],d[e+1]=H[c+(4*e+4)>>2];else d=H.subarray(c>>2,c+8*b>>2);X.uniform2fv(Y(a),d)},mb:function(a,b,c){if(96>=b)for(var d=Z[3*b-1],e=0;e<3*b;e+=3)d[e]=H[c+4*e>>2],d[e+1]=H[c+(4*e+4)>>2],d[e+2]=H[c+(4*e+8)>>2];else d=H.subarray(c>>2,c+12*b>>2);
X.uniform3fv(Y(a),d)},lb:function(a,b,c){if(72>=b){var d=Z[4*b-1],e=H;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=H.subarray(c>>2,c+16*b>>2);X.uniform4fv(Y(a),d)},kb:function(a,b,c,d){if(18>=b){var e=Z[16*b-1],h=H;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=
h[m+13];e[g+14]=h[m+14];e[g+15]=h[m+15]}}else e=H.subarray(d>>2,d+64*b>>2);X.uniformMatrix4fv(Y(a),!!c,e)},q:function(a){a=S[a];X.useProgram(a);X.sc=a},qb:function(a,b){X.vertexAttribDivisor(a,b)},rb:function(a,b,c,d,e,h){X.vertexAttribPointer(a,b,c,!!d,e,h)},k:function(a,b,c,d){X.viewport(a,b,c,d)},Za:function(){f.kc=function(a){0!=Lb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.kc)},Ya:function(){f.pc=function(a){a=a.clipboardData.getData("text");ma("_sapp_emsc_onpaste",
["string"],[a])};window.addEventListener("paste",f.pc)},Wa:function(a){f.Lc=[];a=F(a);a=document.getElementById(a);f.lc=function(b){b.stopPropagation();b.preventDefault()};f.mc=function(b){b.stopPropagation();b.preventDefault()};f.nc=function(b){b.stopPropagation();b.preventDefault()};f.oc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;f.Mc=c;Mb(c.length);var d;for(d=0;d<c.length;d++)ma("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Nb(b.clientX,b.clientY)};a.addEventListener("dragenter",
f.lc,!1);a.addEventListener("dragleave",f.mc,!1);a.addEventListener("dragover",f.nc,!1);a.addEventListener("drop",f.oc,!1)},Ra:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},v:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Ob()});document.body.append(a)},u:function(){document.getElementById("_sokol_app_input_element").focus()},xb:function(a){a=
F(a);f.Wb=document.getElementById(a);f.Wb||console.log("sokol_app.h: invalid target:"+a);f.Wb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Va:function(){window.removeEventListener("beforeunload",f.kc)},Ua:function(){window.removeEventListener("paste",f.pc)},Ta:function(a){a=F(a);a=document.getElementById(a);a.removeEventListener("dragenter",f.lc);a.removeEventListener("dragleave",f.mc);a.removeEventListener("dragover",f.nc);a.removeEventListener("drop",
f.oc)},B:function(){f.Wb&&f.Wb.requestPointerLock&&f.Wb.requestPointerLock()},Qa:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(E.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},t:function(){document.getElementById("_sokol_app_input_element").blur()},Sa:function(a){a=F(a);var b=document.createElement("textarea");
b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},gb:function(){return f.Vb?f.Vb.bufferSize:0},ib:function(a,b,c){f.Qb=null;f.Vb=null;"undefined"!==typeof AudioContext?f.Qb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):
"undefined"!==typeof webkitAudioContext?f.Qb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(f.Qb=null,console.log("sokol_audio.h: no WebAudio support"));return f.Qb?(console.log("sokol_audio.h: sample rate ",f.Qb.sampleRate),f.Vb=f.Qb.createScriptProcessor(c,0,b),f.Vb.onaudioprocess=function(d){var e=d.outputBuffer.length,h=Pb(e);if(h)for(var g=d.outputBuffer.numberOfChannels,m=0;m<g;m++)for(var n=d.outputBuffer.getChannelData(m),p=0;p<e;p++)n[p]=H[(h>>2)+(g*p+m)]},f.Vb.connect(f.Qb.destination),
a=function(){f.Qb&&"suspended"===f.Qb.state&&f.Qb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},hb:function(){return f.Qb?f.Qb.sampleRate:0},na:function(){null!==f.Qb&&(f.Vb&&f.Vb.disconnect(),f.Qb.close(),f.Qb=null,f.Vb=null)},ma:function(){return navigator.userAgent.includes("Macintosh")?1:0},m:function(){return performance.now()}};
(function(){function a(e){f.asm=e.exports;ja=f.asm.yb;ya();J=f.asm.Pb;Aa.unshift(f.asm.zb);K--;f.monitorRunDependencies&&f.monitorRunDependencies(K);0==K&&(null!==Fa&&(clearInterval(Fa),Fa=null),L&&(e=L,L=null,e()))}function b(e){a(e.instance)}function c(e){return Ja().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(e,function(h){A("failed to asynchronously prepare wasm: "+h);y(h)})}var d={a:Qb};K++;f.monitorRunDependencies&&f.monitorRunDependencies(K);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return A("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return B||"function"!==typeof WebAssembly.instantiateStreaming||Ga()||M.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(h){A("wasm streaming compile failed: "+h);A("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.zb).apply(null,arguments)};f._emsc_load_data=function(){return(f._emsc_load_data=f.asm.Ab).apply(null,arguments)};var Ob=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Ob=f.__sapp_emsc_notify_keyboard_hidden=f.asm.Bb).apply(null,arguments)};f.__sapp_emsc_onpaste=function(){return(f.__sapp_emsc_onpaste=f.asm.Cb).apply(null,arguments)};
var Lb=f.__sapp_html5_get_ask_leave_site=function(){return(Lb=f.__sapp_html5_get_ask_leave_site=f.asm.Db).apply(null,arguments)},Mb=f.__sapp_emsc_begin_drop=function(){return(Mb=f.__sapp_emsc_begin_drop=f.asm.Eb).apply(null,arguments)};f.__sapp_emsc_drop=function(){return(f.__sapp_emsc_drop=f.asm.Fb).apply(null,arguments)};var Nb=f.__sapp_emsc_end_drop=function(){return(Nb=f.__sapp_emsc_end_drop=f.asm.Gb).apply(null,arguments)};
f.__sapp_emsc_invoke_fetch_cb=function(){return(f.__sapp_emsc_invoke_fetch_cb=f.asm.Hb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Ib).apply(null,arguments)};var Pb=f.__saudio_emsc_pull=function(){return(Pb=f.__saudio_emsc_pull=f.asm.Jb).apply(null,arguments)};f.__sargs_add_kvp=function(){return(f.__sargs_add_kvp=f.asm.Kb).apply(null,arguments)};
var Q=f._malloc=function(){return(Q=f._malloc=f.asm.Lb).apply(null,arguments)},oa=f.stackSave=function(){return(oa=f.stackSave=f.asm.Mb).apply(null,arguments)},pa=f.stackRestore=function(){return(pa=f.stackRestore=f.asm.Nb).apply(null,arguments)},C=f.stackAlloc=function(){return(C=f.stackAlloc=f.asm.Ob).apply(null,arguments)},Rb;function fa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}L=function Sb(){Rb||Tb();Rb||(L=Sb)};
function Tb(a){function b(){if(!Rb&&(Rb=!0,f.calledRun=!0,!ka)){Ka(Aa);Ka(Ba);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Ub){var c=a,d=f._main;c=c||[];var e=c.length+1,h=C(4*(e+1));G[h>>2]=ta(ba);for(var g=1;g<e;g++)G[(h>>2)+g]=ta(c[g-1]);G[(h>>2)+e]=0;try{var m=d(e,h);if(!(noExitRuntime||0<ha)){if(f.onExit)f.onExit(m);ka=!0}r(m,new fa(m))}catch(n){c=n,c instanceof fa||"unwind"==c||(A("exception thrown: "+c),r(1,c))}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=
f.postRun.shift(),Da.unshift(c);Ka(Da)}}a=a||aa;if(!(0<K)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ea();Ka(za);0<K||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Tb;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Ub=!0;f.noInitialRun&&(Ub=!1);Tb();
