var e;e||(e=typeof Module !== 'undefined' ? Module : {});var f={},h;for(h in e)e.hasOwnProperty(h)&&(f[h]=e[h]);var q=[],aa="./this.program";function r(a,b){throw b;}var t=!1,v=!1,ba=!1,ca=!1,da=!1;t="object"===typeof window;v="function"===typeof importScripts;ba=(ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!t&&!v;da=!t&&!ba&&!v;var x="",ea,y;
if(ba){x=__dirname+"/";var fa,ha;ea=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);a=fa.readFileSync(a);return b?a:a.toString()};y=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||z("Assertion failed: undefined");return a};1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/"));q=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;});process.on("unhandledRejection",
z);r=function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"}}else if(da)"undefined"!=typeof read&&(ea=function(a){return read(a)}),y=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||z("Assertion failed: undefined");return a},"undefined"!=typeof scriptArgs?q=scriptArgs:"undefined"!=typeof arguments&&(q=arguments),"function"===typeof quit&&(r=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===
typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(t||v)v?x=self.location.href:document.currentScript&&(x=document.currentScript.src),x=0!==x.indexOf("blob:")?x.substr(0,x.lastIndexOf("/")+1):"",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(y=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var ja=e.print||console.log.bind(console),A=e.printErr||console.warn.bind(console);for(h in f)f.hasOwnProperty(h)&&(e[h]=f[h]);f=null;e.arguments&&(q=e.arguments);e.thisProgram&&(aa=e.thisProgram);e.quit&&(r=e.quit);var B;e.wasmBinary&&(B=e.wasmBinary);var C;e.noExitRuntime&&(C=e.noExitRuntime);"object"!==typeof WebAssembly&&A("no native wasm support detected");
var D,ka=new WebAssembly.Table({initial:19,maximum:19,element:"anyfunc"}),la=!1,ma="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function E(a,b){if(a){var c=F,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&ma)a=ma.decode(c.subarray(a,b));else{for(d="";a<b;){var g=c[a++];if(g&128){var k=c[a++]&63;if(192==(g&224))d+=String.fromCharCode((g&31)<<6|k);else{var l=c[a++]&63;g=224==(g&240)?(g&15)<<12|k<<6|l:(g&7)<<18|k<<12|l<<6|c[a++]&63;65536>g?d+=String.fromCharCode(g):(g-=65536,d+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else d+=String.fromCharCode(g)}a=d}}else a="";return a}
function G(a,b,c,d){if(!(0<d))return 0;var g=c;d=c+d-1;for(var k=0;k<a.length;++k){var l=a.charCodeAt(k);if(55296<=l&&57343>=l){var m=a.charCodeAt(++k);l=65536+((l&1023)<<10)|m&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-g}
function na(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function oa(a){var b=na(a)+1,c=pa(b);G(a,qa,c,b);return c}function ra(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,qa,F,sa,ta,H,ua,va,I;
function wa(a){buffer=a;e.HEAP8=qa=new Int8Array(a);e.HEAP16=sa=new Int16Array(a);e.HEAP32=H=new Int32Array(a);e.HEAPU8=F=new Uint8Array(a);e.HEAPU16=ta=new Uint16Array(a);e.HEAPU32=ua=new Uint32Array(a);e.HEAPF32=va=new Float32Array(a);e.HEAPF64=I=new Float64Array(a)}var xa=e.TOTAL_MEMORY||33554432;e.wasmMemory?D=e.wasmMemory:D=new WebAssembly.Memory({initial:xa/65536});D&&(buffer=D.buffer);xa=buffer.byteLength;wa(buffer);H[1379956]=10762896;
function ya(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Ab;"number"===typeof c?void 0===b.tb?e.dynCall_v(c):e.dynCall_vi(c,b.tb):c(void 0===b.tb?null:b.tb)}}}var za=[],Aa=[],Ba=[],Ca=[],Da=[];function Ea(){var a=e.preRun.shift();za.unshift(a)}var J=0,Ga=null,K=null;e.preloadedImages={};e.preloadedAudios={};function z(a){if(e.onAbort)e.onAbort(a);ja(a);A(a);la=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}
function Ha(){var a=L;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var L="bombjack.wasm";if(!Ha()){var Ia=L;L=e.locateFile?e.locateFile(Ia,x):x+Ia}function Ja(){try{if(B)return new Uint8Array(B);if(y)return y(L);throw"both async and sync fetching of the wasm failed";}catch(a){z(a)}}
function Ka(){return B||!t&&!v||"function"!==typeof fetch?new Promise(function(a){a(Ja())}):fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ja()})}Aa.push({Ab:function(){La()}});var Ma=0,Na=0,M=0,Oa=0,Pa=0,Qa=null,Ra=null,Sa=!1;function Ta(){for(var a=N.length-1;0<=a;--a)Ua(a);N=[];Va=[]}var Va=[];
function Wa(){if(Xa&&Ya.lb)for(var a=0;a<Va.length;++a){var b=Va[a];Va.splice(a,1);--a;b.Lb.apply(this,b.Fb)}}var Xa=0,Ya=null,N=[];function Za(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function Ua(a){var b=N[a];b.target.removeEventListener(b.kb,b.yb,b.mb);N.splice(a,1)}
function O(a){function b(b){++Xa;Ya=a;Wa();a.ob(b);Wa();--Xa}if(a.nb)a.yb=b,a.target.addEventListener(a.kb,b,a.mb),N.push(a),Sa||(Ca.push(Ta),Sa=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].kb==a.kb&&Ua(c--)}var $a=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function P(a){try{if(!a)return window;"number"===typeof a&&(a=$a[a]||E(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?e.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function ab(a){"number"===typeof a&&(a=E(a));return a&&"#canvas"!==a?"undefined"!==typeof bb&&cb[a]?cb[a]:P(a):"undefined"!==typeof bb&&cb.canvas?cb.canvas:e.canvas}
function db(a,b,c,d,g,k){Ma||(Ma=Q(164));a={target:P(a),lb:Za()?!1:!0,kb:k,nb:d,ob:function(a){a=a||event;var c=Ma;G(a.key?a.key:"",F,c+0,32);G(a.code?a.code:"",F,c+32,32);H[c+64>>2]=a.location;H[c+68>>2]=a.ctrlKey;H[c+72>>2]=a.shiftKey;H[c+76>>2]=a.altKey;H[c+80>>2]=a.metaKey;H[c+84>>2]=a.repeat;G(a.locale?a.locale:"",F,c+88,32);G(a.char?a.char:"",F,c+120,32);H[c+152>>2]=a.charCode;H[c+156>>2]=a.keyCode;H[c+160>>2]=a.which;R(d,g,c,b)&&a.preventDefault()},mb:c};O(a)}
function eb(a,b,c){I[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();H[a+8>>2]=b.screenX;H[a+12>>2]=b.screenY;H[a+16>>2]=b.clientX;H[a+20>>2]=b.clientY;H[a+24>>2]=b.ctrlKey;H[a+28>>2]=b.shiftKey;H[a+32>>2]=b.altKey;H[a+36>>2]=b.metaKey;sa[a+40>>1]=b.button;sa[a+42>>1]=b.buttons;H[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-Qa;H[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-Ra;if(e.canvas){var d=e.canvas.getBoundingClientRect();
H[a+60>>2]=b.clientX-d.left;H[a+64>>2]=b.clientY-d.top}else H[a+60>>2]=0,H[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},H[a+52>>2]=b.clientX-d.left,H[a+56>>2]=b.clientY-d.top):(H[a+52>>2]=0,H[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(Qa=b.screenX,Ra=b.screenY)}
function S(a,b,c,d,g,k){Na||(Na=Q(72));a=P(a);c={target:a,lb:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,kb:k,nb:d,ob:function(c){c=c||event;eb(Na,c,a);R(d,g,Na,b)&&c.preventDefault()},mb:c};Za()&&"mousedown"==k&&(c.lb=!1);O(c)}
function fb(a,b,c,d){Oa||(Oa=Q(36));a=P(a);O({target:a,lb:!1,kb:"resize",nb:d,ob:function(c){c=c||event;if(c.target==a){var g=0<pageXOffset||0<pageYOffset?[pageXOffset,pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],l=Oa;H[l>>2]=c.detail;H[l+4>>2]=document.body.clientWidth;H[l+8>>2]=document.body.clientHeight;
H[l+12>>2]=innerWidth;H[l+16>>2]=innerHeight;H[l+20>>2]=outerWidth;H[l+24>>2]=outerHeight;H[l+28>>2]=g[0];H[l+32>>2]=g[1];R(d,10,l,b)&&c.preventDefault()}},mb:c})}
function gb(a,b,c,d,g,k){Pa||(Pa=Q(1684));a=P(a);O({target:a,lb:"touchstart"==k||"touchend"==k,kb:k,nb:d,ob:function(c){c=c||event;for(var l={},k=0;k<c.touches.length;++k){var n=c.touches[k];n.vb=!1;l[n.identifier]=n}for(k=0;k<c.changedTouches.length;++k)n=c.changedTouches[k],l[n.identifier]=n,n.vb=!0;for(k=0;k<c.targetTouches.length;++k)n=c.targetTouches[k],l[n.identifier].Db=!0;var p=n=Pa;H[p+4>>2]=c.ctrlKey;H[p+8>>2]=c.shiftKey;H[p+12>>2]=c.altKey;H[p+16>>2]=c.metaKey;p+=20;var Fa=e.canvas?e.canvas.getBoundingClientRect():
void 0,hb=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},ib=0;for(k in l){var u=l[k];H[p>>2]=u.identifier;H[p+4>>2]=u.screenX;H[p+8>>2]=u.screenY;H[p+12>>2]=u.clientX;H[p+16>>2]=u.clientY;H[p+20>>2]=u.pageX;H[p+24>>2]=u.pageY;H[p+28>>2]=u.vb;H[p+32>>2]=u.Db;Fa?(H[p+44>>2]=u.clientX-Fa.left,H[p+48>>2]=u.clientY-Fa.top):(H[p+44>>2]=0,H[p+48>>2]=0);H[p+36>>2]=u.clientX-hb.left;H[p+40>>2]=u.clientY-hb.top;p+=52;if(32<=++ib)break}H[n>>2]=ib;R(d,g,n,b)&&c.preventDefault()},mb:c})}
function jb(a,b,c,d,g,k){a||(a=e.canvas);a={target:P(a),lb:!1,kb:k,nb:d,ob:function(a){a=a||event;R(d,g,0,b)&&a.preventDefault()},mb:c};O(a)}
function kb(a,b,c,d,g){function k(c){c=c||event;eb(M,c,a);I[M+72>>3]=c.wheelDeltaX||0;I[M+80>>3]=-(c.wheelDeltaY||c.wheelDelta);I[M+88>>3]=0;H[M+96>>2]=0;R(d,9,M,b)&&c.preventDefault()}function l(c){c=c||event;var g=M;eb(g,c,a);I[g+72>>3]=c.deltaX;I[g+80>>3]=c.deltaY;I[g+88>>3]=c.deltaZ;H[g+96>>2]=c.deltaMode;R(d,9,g,b)&&c.preventDefault()}M||(M=Q(104));O({target:a,lb:!0,kb:g,nb:d,ob:"wheel"==g?l:k,mb:c})}var lb=1,mb=0,nb=[],T=[],ob=[],U=[],V=[],W=[],X=[],pb={},qb=null,cb={},rb={},sb={};
function Y(a){mb||(mb=a)}function tb(a){for(var b=lb++,c=a.length;c<b;c++)a[c]=null;return b}function ub(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(a,d){b.vertexAttribDivisorANGLE(a,d)},a.drawArraysInstanced=function(a,d,g,k){b.drawArraysInstancedANGLE(a,d,g,k)},a.drawElementsInstanced=function(a,d,g,k,l){b.drawElementsInstancedANGLE(a,d,g,k,l)})}
function vb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(a){b.deleteVertexArrayOES(a)},a.bindVertexArray=function(a){b.bindVertexArrayOES(a)},a.isVertexArray=function(a){return b.isVertexArrayOES(a)})}function wb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(a,d){b.drawBuffersWEBGL(a,d)})}
function xb(a){a||(a=qb);if(!a.Bb){a.Bb=!0;var b=a.sb;2>a.version&&(ub(b),vb(b),wb(b));b.Hb=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(a){-1!=c.indexOf(a)&&b.getExtension(a)})}}var bb={},yb,zb,Ab=["default","low-power","high-performance"];function Bb(a,b,c,d){for(var g=0;g<a;g++){var k=Z[c](),l=k&&tb(d);k?(k.name=l,d[l]=k):Y(1282);H[b+4*g>>2]=l}}
function Cb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Y(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)H[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(g){Y(1280);A("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:Y(1280);A("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}H[b>>2]=c}else Y(1281)}function Db(a){var b=na(a)+1,c=Q(b);G(a,F,c,b);return c}
var Eb={6402:1,6406:1,6407:3,6408:4,6409:1,6410:2,35904:3,35906:4},Fb={5121:1,5123:2,5125:4,5126:4,32819:2,32820:2,33635:2,34042:4,36193:2};function Gb(a,b,c,d,g){if(b=Eb[b]*Fb[a])switch(c=g+d*(c*b+4-1&-4),a){case 5121:return F.subarray(g,c);case 5126:return va.subarray(g>>2,c>>2);case 5125:case 34042:return ua.subarray(g>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return ta.subarray(g>>1,c>>1);default:Y(1280)}else Y(1280)}for(var Z,Hb=0;256>Hb;Hb++);
var Mb={W:function(){return devicePixelRatio||1},X:function(a,b,c){a=a?P(a):e.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),I[b>>3]=a.right-a.left,I[c>>3]=a.bottom-a.top):(I[b>>3]=a.clientWidth,I[c>>3]=a.clientHeight);return 0},Sa:function(a,b,c){F.set(F.subarray(b,b+c),a)},Fa:function(a,b){function c(d){Ib(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ta:function(a){if(2147418112<a)return!1;for(var b=Math.max(qa.length,16777216);b<a;)536870912>=b?
b=ra(2*b):b=Math.min(ra((3*b+2147483648)/4),2147418112);a:{try{D.grow(b-buffer.byteLength+65535>>16);wa(D.buffer);var c=1;break a}catch(d){}c=void 0}return c?!0:!1},U:function(a,b,c){a=ab(a);if(!a)return-4;a.width=b;a.height=c;return 0},Oa:function(a,b,c,d){db(a,b,c,d,2,"keydown");return 0},Ma:function(a,b,c,d){db(a,b,c,d,1,"keypress");return 0},Na:function(a,b,c,d){db(a,b,c,d,3,"keyup");return 0},ka:function(a,b,c,d){S(a,b,c,d,5,"mousedown");return 0},Ra:function(a,b,c,d){S(a,b,c,d,33,"mouseenter");
return 0},Qa:function(a,b,c,d){S(a,b,c,d,34,"mouseleave");return 0},Va:function(a,b,c,d){S(a,b,c,d,8,"mousemove");return 0},ca:function(a,b,c,d){S(a,b,c,d,6,"mouseup");return 0},Wa:function(a,b,c,d){fb(a,b,c,d);return 0},Ia:function(a,b,c,d){gb(a,b,c,d,25,"touchcancel");return 0},Ja:function(a,b,c,d){gb(a,b,c,d,23,"touchend");return 0},Ka:function(a,b,c,d){gb(a,b,c,d,24,"touchmove");return 0},La:function(a,b,c,d){gb(a,b,c,d,22,"touchstart");return 0},Ha:function(a,b,c,d){jb(a,b,c,d,31,"webglcontextlost");
return 0},Ga:function(a,b,c,d){jb(a,b,c,d,32,"webglcontextrestored");return 0},Pa:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(kb(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(kb(a,b,c,d,"mousewheel"),0):-1},L:function(a,b){var c={};b>>=2;c.alpha=!!H[b];c.depth=!!H[b+1];c.stencil=!!H[b+2];c.antialias=!!H[b+3];c.premultipliedAlpha=!!H[b+4];c.preserveDrawingBuffer=!!H[b+5];c.powerPreference=Ab[H[b+6]];c.failIfMajorPerformanceCaveat=!!H[b+7];c.Cb=H[b+8];c.Ib=H[b+9];c.wb=
H[b+10];c.zb=H[b+11];c.Jb=H[b+12];c.Kb=H[b+13];a=ab(a);if(!a||c.zb)c=0;else if(a=a.getContext("webgl",c)||a.getContext("experimental-webgl",c)){b=Q(8);var d={handle:b,attributes:c,version:c.Cb,sb:a};a.canvas&&(a.canvas.Eb=d);pb[b]=d;("undefined"===typeof c.wb||c.wb)&&xb(d);c=b}else c=0;return c},ma:function(a,b){a=pb[a];b=E(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b?ub(Z):"OES_vertex_array_object"==b?vb(Z):"WEBGL_draw_buffers"==b&&wb(Z);return!!a.sb.getExtension(b)},xa:function(a){a>>=
2;for(var b=0;14>b;++b)H[a+b]=0;H[a]=H[a+1]=H[a+3]=H[a+4]=H[a+8]=H[a+10]=1},ra:function(a){qb=pb[a];e.Gb=Z=qb&&qb.sb;return!a||Z?0:-5},g:function(a){Z.activeTexture(a)},N:function(a,b){Z.attachShader(T[a],X[b])},d:function(a,b){Z.bindBuffer(a,nb[b])},f:function(a,b){Z.bindFramebuffer(a,ob[b])},Aa:function(a,b){Z.bindRenderbuffer(a,U[b])},a:function(a,b){Z.bindTexture(a,V[b])},F:function(a,b,c,d){Z.blendColor(a,b,c,d)},G:function(a,b){Z.blendEquationSeparate(a,b)},H:function(a,b,c,d){Z.blendFuncSeparate(a,
b,c,d)},R:function(a,b,c,d){Z.bufferData(a,c?F.subarray(c,c+b):b,d)},Q:function(a,b,c,d){Z.bufferSubData(a,b,F.subarray(d,d+c))},m:function(a){return Z.checkFramebufferStatus(a)},na:function(a){Z.clear(a)},qa:function(a,b,c,d){Z.clearColor(a,b,c,d)},pa:function(a){Z.clearDepth(a)},oa:function(a){Z.clearStencil(a)},x:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},Z:function(a){Z.compileShader(X[a])},P:function(a,b,c,d,g,k,l,m){Z.compressedTexImage2D(a,b,c,d,g,k,m?F.subarray(m,m+l):null)},wa:function(){var a=
tb(T),b=Z.createProgram();b.name=a;T[a]=b;return a},$:function(a){var b=tb(X);X[b]=Z.createShader(a);return b},E:function(a){Z.cullFace(a)},Ca:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],g=nb[d];g&&(Z.deleteBuffer(g),g.name=0,nb[d]=null,d==yb&&(yb=0),d==zb&&(zb=0))}},j:function(a,b){for(var c=0;c<a;++c){var d=H[b+4*c>>2],g=ob[d];g&&(Z.deleteFramebuffer(g),g.name=0,ob[d]=null)}},T:function(a){if(a){var b=T[a];b?(Z.deleteProgram(b),b.name=0,T[a]=null,rb[a]=null):Y(1281)}},s:function(a,b){for(var c=
0;c<a;c++){var d=H[b+4*c>>2],g=U[d];g&&(Z.deleteRenderbuffer(g),g.name=0,U[d]=null)}},y:function(a){if(a){var b=X[a];b?(Z.deleteShader(b),X[a]=null):Y(1281)}},V:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],g=V[d];g&&(Z.deleteTexture(g),g.name=0,V[d]=null)}},v:function(a){Z.depthFunc(a)},w:function(a){Z.depthMask(!!a)},c:function(a){Z.disable(a)},A:function(a){Z.disableVertexAttribArray(a)},ga:function(a,b,c){Z.drawArrays(a,b,c)},ha:function(a,b,c,d){Z.drawElements(a,b,c,d)},e:function(a){Z.enable(a)},
ia:function(a){Z.enableVertexAttribArray(a)},k:function(a,b,c,d){Z.framebufferRenderbuffer(a,b,c,U[d])},b:function(a,b,c,d,g){Z.framebufferTexture2D(a,b,c,V[d],g)},D:function(a){Z.frontFace(a)},S:function(a,b){Bb(a,b,"createBuffer",nb)},n:function(a,b){Bb(a,b,"createFramebuffer",ob)},Ba:function(a,b){Bb(a,b,"createRenderbuffer",U)},ya:function(a,b){Bb(a,b,"createTexture",V)},ta:function(a,b){return Z.getAttribLocation(T[a],E(b))},i:function(a,b){Cb(a,b)},ua:function(a,b,c,d){a=Z.getProgramInfoLog(T[a]);
null===a&&(a="(unknown error)");b=0<b&&d?G(a,F,d,b):0;c&&(H[c>>2]=b)},M:function(a,b,c){if(c)if(a>=lb)Y(1281);else{var d=rb[a];if(d)if(35716==b)a=Z.getProgramInfoLog(T[a]),null===a&&(a="(unknown error)"),H[c>>2]=a.length+1;else if(35719==b)H[c>>2]=d.ub;else if(35722==b){if(-1==d.qb){a=T[a];var g=Z.getProgramParameter(a,35721);for(b=d.qb=0;b<g;++b)d.qb=Math.max(d.qb,Z.getActiveAttrib(a,b).name.length+1)}H[c>>2]=d.qb}else if(35381==b){if(-1==d.rb)for(a=T[a],g=Z.getProgramParameter(a,35382),b=d.rb=0;b<
g;++b)d.rb=Math.max(d.rb,Z.getActiveUniformBlockName(a,b).length+1);H[c>>2]=d.rb}else H[c>>2]=Z.getProgramParameter(T[a],b);else Y(1282)}else Y(1281)},Y:function(a,b,c,d){a=Z.getShaderInfoLog(X[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,F,d,b):0;c&&(H[c>>2]=b)},z:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(X[a]),null===a&&(a="(unknown error)"),H[c>>2]=a.length+1):35720==b?(a=Z.getShaderSource(X[a]),H[c>>2]=null===a||0==a.length?0:a.length+1):H[c>>2]=Z.getShaderParameter(X[a],b):Y(1281)},
Da:function(a){if(sb[a])return sb[a];switch(a){case 7939:var b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(a){return"GL_"+a}));b=Db(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||Y(1280);b=Db(b);break;case 7938:b=Db("OpenGL ES 2.0 ("+Z.getParameter(Z.VERSION)+")");break;case 35724:b=Z.getParameter(Z.SHADING_LANGUAGE_VERSION);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+
c[1]+" ("+b+")");b=Db(b);break;default:return Y(1280),0}return sb[a]=b},l:function(a,b){b=E(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=rb[a]&&rb[a].xb[b])&&0<=c&&c<a[0]?a[1]+c:-1},va:function(a){Z.linkProgram(T[a]);var b=T[a];a=rb[a]={xb:{},ub:0,qb:-1,rb:-1};for(var c=a.xb,d=Z.getProgramParameter(b,35718),g=0;g<d;++g){var k=Z.getActiveUniform(b,g),l=k.name;a.ub=Math.max(a.ub,l.length+1);"]"==l.slice(-1)&&(l=l.slice(0,l.lastIndexOf("[")));
var m=Z.getUniformLocation(b,l);if(m){var w=tb(W);c[l]=[k.size,w];W[w]=m;for(var n=1;n<k.size;++n)m=Z.getUniformLocation(b,l+"["+n+"]"),w=tb(W),W[w]=m}}},C:function(a,b){Z.polygonOffset(a,b)},za:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},sa:function(a,b,c,d){Z.scissor(a,b,c,d)},_:function(a,b,c,d){for(var g="",k=0;k<b;++k){var l=d?H[d+4*k>>2]:-1;g+=E(H[c+4*k>>2],0>l?void 0:l)}Z.shaderSource(X[a],g)},fa:function(a,b,c){Z.stencilFunc(a,b,c)},J:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},
u:function(a){Z.stencilMask(a)},ea:function(a,b,c){Z.stencilOp(a,b,c)},I:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},O:function(a,b,c,d,g,k,l,m,w){Z.texImage2D(a,b,c,d,g,k,l,m,w?Gb(m,l,d,g,w):null)},h:function(a,b,c){Z.texParameteri(a,b,c)},r:function(a,b,c,d,g,k,l,m,w){var n=null;w&&(n=Gb(m,l,g,k,w));Z.texSubImage2D(a,b,c,d,g,k,l,m,n)},B:function(a,b){Z.uniform1i(W[a],b)},la:function(a){Z.useProgram(T[a])},Ua:function(a,b){Z.vertexAttribDivisor(a,b)},ja:function(a,b,c,d,g,k){Z.vertexAttribPointer(a,
b,c,!!d,g,k)},K:function(a,b,c,d){Z.viewport(a,b,c,d)},memory:D,q:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Jb()});document.body.append(a)},p:function(){document.getElementById("_sokol_app_input_element").focus()},Ea:function(){window.addEventListener("beforeunload",function(a){0!=Kb()&&(a.preventDefault(),a.returnValue=" ")})},o:function(){document.getElementById("_sokol_app_input_element").blur()},
aa:function(){return e.pb?e.pb.bufferSize:0},da:function(a,b,c){e.jb=null;e.pb=null;"undefined"!==typeof AudioContext?(e.jb=new AudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created AudioContext")):"undefined"!==typeof webkitAudioContext?(e.jb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created webkitAudioContext")):(e.jb=null,console.log("sokol_audio.h: no WebAudio support"));return e.jb?(console.log("sokol_audio.h: sample rate ",
e.jb.sampleRate),e.pb=e.jb.createScriptProcessor(c,0,b),e.pb.onaudioprocess=function(a){var b=a.outputBuffer.length,c=Lb(b);if(c)for(var d=a.outputBuffer.numberOfChannels,m=0;m<d;m++)for(var w=a.outputBuffer.getChannelData(m),n=0;n<b;n++)w[n]=va[(c>>2)+(d*n+m)]},e.pb.connect(e.jb.destination),a=function(){e.jb&&"suspended"===e.jb.state&&e.jb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),
1):0},ba:function(){return e.jb?e.jb.sampleRate:0},t:function(){return performance.now()},table:ka},Nb=function(){function a(a){e.asm=a.exports;J--;e.monitorRunDependencies&&e.monitorRunDependencies(J);0==J&&(null!==Ga&&(clearInterval(Ga),Ga=null),K&&(a=K,K=null,a()))}function b(b){a(b.instance)}function c(a){return Ka().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){A("failed to asynchronously prepare wasm: "+a);z(a)})}var d={env:Mb,wasi_unstable:Mb};J++;e.monitorRunDependencies&&
e.monitorRunDependencies(J);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(g){return A("Module.instantiateWasm callback failed with error: "+g),!1}(function(){if(B||"function"!==typeof WebAssembly.instantiateStreaming||Ha()||"function"!==typeof fetch)return c(b);fetch(L,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){A("wasm streaming compile failed: "+a);A("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();
e.asm=Nb;var La=e.___wasm_call_ctors=function(){return e.asm.Xa.apply(null,arguments)};e._emsc_load_data=function(){return e.asm.Ya.apply(null,arguments)};var Jb=e.__sapp_emsc_notify_keyboard_hidden=function(){return e.asm.Za.apply(null,arguments)},Kb=e.__sapp_html5_get_ask_leave_site=function(){return e.asm._a.apply(null,arguments)};e._main=function(){return e.asm.$a.apply(null,arguments)};var Q=e._malloc=function(){return e.asm.ab.apply(null,arguments)};
e._free=function(){return e.asm.bb.apply(null,arguments)};var Lb=e.__saudio_emsc_pull=function(){return e.asm.cb.apply(null,arguments)};e.__sargs_add_kvp=function(){return e.asm.db.apply(null,arguments)};var pa=e.stackAlloc=function(){return e.asm.eb.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.fb.apply(null,arguments)};e.dynCall_v=function(){return e.asm.gb.apply(null,arguments)};
var R=e.dynCall_iiii=function(){return e.asm.hb.apply(null,arguments)},Ib=e.dynCall_idi=function(){return e.asm.ib.apply(null,arguments)};e.asm=Nb;var Ob;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}K=function Pb(){Ob||Qb();Ob||(K=Pb)};
function Qb(a){function b(){if(!Ob&&(Ob=!0,!la)){ya(Aa);ya(Ba);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Rb){var b=a;b=b||[];var d=b.length+1,g=pa(4*(d+1));H[g>>2]=oa(aa);for(var k=1;k<d;k++)H[(g>>2)+k]=oa(b[k-1]);H[(g>>2)+d]=0;try{var l=e._main(d,g);if(!C||0!==l){if(!C&&(la=!0,e.onExit))e.onExit(l);r(l,new ia(l))}}catch(m){m instanceof ia||("SimulateInfiniteLoop"==m?C=!0:((b=m)&&"object"===typeof m&&m.stack&&(b=[m,m.stack]),A("exception thrown: "+b),r(1,m)))}finally{}}if(e.postRun)for("function"==
typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)b=e.postRun.shift(),Da.unshift(b);ya(Da)}}a=a||q;if(!(0<J)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ea();ya(za);0<J||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=Qb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Rb=!0;e.noInitialRun&&(Rb=!1);C=!0;Qb();
