var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs"),ka=require("path");k=__dirname+"/";ja=a=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a)};ia=a=>{a=la(a)?new URL(a):ka.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof ma||a.context instanceof ma))throw a;
});ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?"":k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=a=>la(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{(200==
d.status||0==d.status&&d.response)&&c(d.response);b(d.status)};d.onerror=b;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var na=f.print||console.log.bind(console),n=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);f.quit&&(ha=f.quit);var q;f.wasmBinary&&(q=f.wasmBinary);var oa,r=!1,t,v,x,pa,qa,y,z,A,B;
function ra(){var a=oa.buffer;f.HEAP8=v=new Int8Array(a);f.HEAP16=pa=new Int16Array(a);f.HEAPU8=x=new Uint8Array(a);f.HEAPU16=qa=new Uint16Array(a);f.HEAP32=y=new Int32Array(a);f.HEAPU32=z=new Uint32Array(a);f.HEAPF32=A=new Float32Array(a);f.HEAPF64=B=new Float64Array(a)}var sa=[],ta=[],ua=[],va=[];function wa(){var a=f.preRun.shift();sa.unshift(a)}var C=0,xa=null,ya=null;
function za(a){f.onAbort?.(a);a="Aborted("+a+")";n(a);r=!0;t=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Aa=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),Ba;function Ca(a){if(a==Ba&&q)return new Uint8Array(q);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}function Da(a){return q?Promise.resolve().then(()=>Ca(a)):ia(a).then(b=>new Uint8Array(b),()=>Ca(a))}
function Ea(a,b,c){return Da(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{n(`failed to asynchronously prepare wasm: ${d}`);za(d)})}function Fa(a,b){var c=Ba;q||"function"!=typeof WebAssembly.instantiateStreaming||Aa(c)||la(c)||ca||"function"!=typeof fetch?Ea(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){n(`wasm streaming compile failed: ${e}`);n("falling back to ArrayBuffer instantiation");return Ea(c,a,b)}))}
var Ha={98879:()=>{const a=f._webapi_input;f._webapi_input=b=>{Ga(()=>a(D(b)))}}};function ma(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ia=a=>{for(;0<a.length;)a.shift()(f)},Ja=f.noExitRuntime||!0,Ka="undefined"!=typeof TextDecoder?new TextDecoder:void 0,E=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|
e&1023))}}else d+=String.fromCharCode(e)}return d},La=[],Va=(a,b)=>{Ma=a;Na=b;if(Oa)if(Pa||=!0,0==a)F=function(){var d=Math.max(0,Qa+b-Ra())|0;setTimeout(Sa,d)};else if(1==a)F=function(){Ta(Sa)};else if(2==a){if("undefined"==typeof Ua)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ua=function(d){c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);
postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ua=setImmediate;F=function(){Ua(Sa)}}},Ra;Ra=()=>performance.now();
var cb=(a,b,c,d,e)=>{Oa=a;Wa=d;var h=G;Pa=!1;Sa=function(){if(!r)if(0<Xa.length){var g=Xa.shift();g.Td(g.Od);if(Ya){var l=Ya,m=0==l%1?l-1:Math.floor(l);Ya=g.Qd?m:(8*l+(m+.5))/9}f.setStatus&&(g=f.statusMessage||"Please wait...",l=Ya,m=Za.Sd,l?l<m?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(g):f.setStatus(""));h<G||setTimeout(Sa,0)}else if(!(h<G))if($a=$a+1|0,1==Ma&&1<Na&&0!=$a%Na)F();else{0==Ma&&(Qa=Ra());if(!(r||f.preMainLoop&&!1===f.preMainLoop())){if(!r)try{if(a(),!Ja)try{t=
g=t,ab(g)}catch(p){bb(p)}}catch(p){bb(p)}f.postMainLoop?.()}h<G||("object"==typeof SDL&&SDL.audio?.Xd?.(),F())}};e||(b&&0<b?Va(0,1E3/b):Va(1,1),F());if(c)throw"unwind";},bb=a=>{a instanceof ma||"unwind"==a||ha(1,a)},ab=a=>{t=a;Ja||(f.onExit?.(a),r=!0);ha(a,new ma(a))},db=a=>{t=a;ab(a)},Pa=!1,F=null,G=0,Oa=null,Wa=0,Ma=0,Na=0,$a=0,Xa=[];function eb(){F=null;G++}var Za={},Qa,Sa,Ya,fb=!1,gb=!1,hb=[];
function ib(){function a(){gb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!jb){jb=!0;var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!gb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}var kb=!1,lb=void 0,H=void 0;
function mb(){if(!fb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var nb=0;function Ta(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===nb)nb=b+1E3/60;else for(;b+2>=nb;)nb+=1E3/60;setTimeout(a,Math.max(nb-b,0))}}var ob=[];function pb(){var a=f.canvas;ob.forEach(b=>b(a.width,a.height))}
function qb(a,b,c){b&&c?(a.Md=b,a.Jd=c):(b=a.Md,c=a.Jd);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var h=Math.min(screen.width/d,screen.height/e);d=Math.round(d*h);e=Math.round(e*
h)}H?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Ua,jb,rb=0,sb=[];
function tb(){if(navigator.userActivation?navigator.userActivation.isActive:rb&&ub.md)for(var a=0;a<sb.length;++a){var b=sb[a];sb.splice(a,1);--a;b.$d(...b.Pd)}}var I=[];function vb(a){var b=I[a];b.target.removeEventListener(b.Yc,b.vd,b.Zc);I.splice(a,1)}function J(a){if(!a.target)return-4;if(a.$c)a.vd=function(c){++rb;ub=a;tb();a.ad(c);tb();--rb},a.target.addEventListener(a.Yc,a.vd,a.Zc),I.push(a);else for(var b=0;b<I.length;++b)I[b].target==a.target&&I[b].Yc==a.Yc&&vb(b--);return 0}
function wb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var ub,xb,yb,zb,Ab,Bb,Cb,Db,Eb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?E(x,a):"":a;return Eb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Fb=a=>0>Eb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Gb=[],Hb,L=a=>{var b=Gb[a];b||(a>=Gb.length&&(Gb.length=a+1),Gb[a]=b=Hb.get(a));return b},M=(a,b,c)=>{var d=x;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var l=
a.charCodeAt(++h);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},Ib=(a,b,c,d,e,h)=>{xb||=N(256);a={target:K(a),Yc:h,$c:d,ad:(g=event)=>{var l=g.target.id?g.target.id:"",m=xb;M(wb(g.target),m+0,128);M(l,m+128,128);L(d)(e,m,b)&&g.preventDefault()},Zc:c};return J(a)},Jb=(a,
b,c,d,e,h)=>{yb||=N(160);a={target:K(a),Yc:h,$c:d,ad:g=>{var l=yb;B[l>>3]=g.timeStamp;var m=l>>2;y[m+2]=g.location;v[m+12]=g.ctrlKey;v[m+13]=g.shiftKey;v[m+14]=g.altKey;v[m+15]=g.metaKey;v[m+16]=g.repeat;y[m+5]=g.charCode;y[m+6]=g.keyCode;y[m+7]=g.which;M(g.key||"",l+32,32);M(g.code||"",l+64,32);M(g.char||"",l+96,32);M(g.locale||"",l+128,32);L(d)(e,l,b)&&g.preventDefault()},Zc:c};return J(a)},Kb=(a,b,c)=>{B[a>>3]=b.timeStamp;a>>=2;y[a+2]=b.screenX;y[a+3]=b.screenY;y[a+4]=b.clientX;y[a+5]=b.clientY;
v[a+24]=b.ctrlKey;v[a+25]=b.shiftKey;v[a+26]=b.altKey;v[a+27]=b.metaKey;pa[2*a+14]=b.button;pa[2*a+15]=b.buttons;y[a+8]=b.movementX;y[a+9]=b.movementY;c=Fb(c);y[a+10]=b.clientX-(c.left|0);y[a+11]=b.clientY-(c.top|0)},Lb=(a,b,c,d,e,h)=>{zb||=N(64);a=K(a);return J({target:a,md:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Yc:h,$c:d,ad:(g=event)=>{Kb(zb,g,a);L(d)(e,zb,b)&&g.preventDefault()},Zc:c})},Mb=(a,b,c,d,e)=>{Ab||=N(257);return J({target:a,Yc:e,$c:d,ad:(h=event)=>{var g=Ab,l=document.pointerLockElement||
document.ed||document.rd||document.qd;v[g]=!!l;var m=l?.id||"";M(wb(l),g+1,128);M(m,g+129,128);L(d)(20,g,b)&&h.preventDefault()},Zc:c})},Nb=(a,b,c,d,e)=>J({target:a,Yc:e,$c:d,ad:(h=event)=>{L(d)(38,0,b)&&h.preventDefault()},Zc:c}),Ob=(a,b,c,d)=>{Bb||=N(36);a=K(a);return J({target:a,Yc:"resize",$c:d,ad:(e=event)=>{if(e.target==a){var h=document.body;if(h){var g=Bb;y[g>>2]=0;y[g+4>>2]=h.clientWidth;y[g+8>>2]=h.clientHeight;y[g+12>>2]=innerWidth;y[g+16>>2]=innerHeight;y[g+20>>2]=outerWidth;y[g+24>>2]=
outerHeight;y[g+28>>2]=pageXOffset|0;y[g+32>>2]=pageYOffset|0;L(d)(10,g,b)&&e.preventDefault()}}},Zc:c})},Pb=(a,b,c,d,e,h)=>{Cb||=N(1552);a=K(a);return J({target:a,md:"touchstart"==h||"touchend"==h,Yc:h,$c:d,ad:g=>{for(var l,m={},p=g.touches,u=0;u<p.length;++u)l=p[u],l.wd=l.xd=0,m[l.identifier]=l;for(u=0;u<g.changedTouches.length;++u)l=g.changedTouches[u],l.wd=1,m[l.identifier]=l;for(u=0;u<g.targetTouches.length;++u)m[g.targetTouches[u].identifier].xd=1;p=Cb;B[p>>3]=g.timeStamp;var w=p>>2;v[w+12]=
g.ctrlKey;v[w+13]=g.shiftKey;v[w+14]=g.altKey;v[w+15]=g.metaKey;w+=4;var Qb=Fb(a),Rb=0;for(u in m)if(l=m[u],y[w]=l.identifier,y[w+1]=l.screenX,y[w+2]=l.screenY,y[w+3]=l.clientX,y[w+4]=l.clientY,y[w+5]=l.pageX,y[w+6]=l.pageY,v[w+28]=l.wd,v[w+29]=l.xd,y[w+8]=l.clientX-(Qb.left|0),y[w+9]=l.clientY-(Qb.top|0),w+=12,31<++Rb)break;y[p+8>>2]=Rb;L(d)(e,p,b)&&g.preventDefault()},Zc:c})},Sb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,d,e,h,g))},Tb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Ub=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Vb=a=>{a.Rd=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
Wb=a=>{a.Ud=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Xb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Yb=1,Zb=[],O=[],$b=[],ac=[],P=[],Q=[],bc=[],cc=[],R=[],dc={},ec=4,fc=0,gc=a=>{for(var b=Yb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=S[c](),g=h&&gc(d);h?(h.name=g,d[g]=h):T||=1282;y[b+4*e>>2]=g}},ic=(a,b)=>{a.ed||(a.ed=a.getContext,a.getContext=function(d,e){e=a.ed(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.od?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
hc(c,b):0},hc=(a,b)=>{var c=gc(cc),d={handle:c,attributes:b,version:b.od,hd:a};a.canvas&&(a.canvas.Nd=d);cc[c]=d;("undefined"==typeof b.ud||b.ud)&&jc(d);return c},kc=a=>{V=cc[a];f.nd=S=V?.hd;return!(a&&!S)},jc=a=>{a||=V;if(!a.Kd){a.Kd=!0;var b=a.hd;Sb(b);Tb(b);Ub(b);Vb(b);Wb(b);2<=a.version&&(b.td=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.td)b.td=b.getExtension("EXT_disjoint_timer_query");b.Ld=b.getExtension("WEBGL_multi_draw");Xb(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},lc={},T,V,mc=(a,b,c,d,e,h)=>{a={target:K(a),Yc:h,$c:d,ad:(g=event)=>{L(d)(e,0,b)&&g.preventDefault()},Zc:c};J(a)},nc=(a,b,c,d)=>{Db||=N(96);return J({target:a,md:!0,Yc:"wheel",$c:d,ad:(e=event)=>{var h=Db;Kb(h,e,a);B[h+64>>3]=e.deltaX;B[h+72>>3]=e.deltaY;B[h+80>>3]=e.deltaZ;y[h+88>>2]=e.deltaMode;L(d)(9,h,b)&&e.preventDefault()},Zc:c})},oc=["default","low-power","high-performance"],pc=[null,[],[]],qc=[];
function rc(){var a=Xb(S);return a=a.concat(a.map(b=>"GL_"+b))}
var sc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=rc().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)y[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}y[b>>2]=c}else T||=1281},tc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},uc=a=>{var b=tc(a)+1,c=N(b);c&&M(a,c,b);return c},vc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),wc=a=>{a-=5120;return 0==a?v:1==a?x:2==a?pa:4==a?y:6==a?A:5==a||28922==a||28520==a||30779==a||30782==a?z:qa},xc=(a,b,c,d,e)=>{a=wc(a);b=d*((fc||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+ec-1&-ec);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=S.Hd;if(b){var c=b.gd[a];"number"==typeof c&&(b.gd[a]=c=S.getUniformLocation(b,b.Fd[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],yc=[],D=a=>{var b=tc(a)+1,c=zc(b);M(a,c,b);return c},Ga=a=>{var b=Ac();a();Bc(b)};
f.requestFullscreen=function(a,b){function c(){fb=!1;var h=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===h?(d.exitFullscreen=mb,lb&&d.requestPointerLock(),fb=!0,H?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>2]|8388608),qb(f.canvas),pb()):qb(d)):(h.parentNode.insertBefore(d,h),h.parentNode.removeChild(h),H?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>
2]&-8388609),qb(f.canvas),pb()):qb(d));f.onFullScreen?.(fb);f.onFullscreen?.(fb)}lb=a;H=b;"undefined"==typeof lb&&(lb=!0);"undefined"==typeof H&&(H=!1);var d=f.canvas;kb||(kb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};f.requestAnimationFrame=Ta;f.setCanvasSize=function(a,b,c){qb(f.canvas,a,b);c||pb()};f.pauseMainLoop=eb;f.resumeMainLoop=function(){G++;var a=Ma,b=Na,c=Oa;Oa=null;cb(c,0,!1,Wa,!0);Va(a,b);F()};
f.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};f.createContext=function(a,b,c,d){if(b&&f.nd&&a==f.canvas)return f.nd;var e;if(b){var h={antialias:!1,alpha:!1,od:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var g in d)h[g]=d[g];if("undefined"!=typeof lc&&(e=ic(a,h)))var l=cc[e].hd}else l=a.getContext("2d");if(!l)return null;c&&(f.nd=l,b&&kc(e),f.ae=b,hb.forEach(m=>m()),ib());return l};
for(var S,Y=0;32>Y;++Y)qc.push(Array(Y));var Cc=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=Cc.subarray(0,Y);var Dc=new Int32Array(288);for(Y=0;288>=Y;++Y)yc[Y]=Dc.subarray(0,Y);
var Sc={ma:function(){return 0},lb:function(){return 0},mb:function(){},ob:()=>{za("")},ib:(a,b,c)=>x.copyWithin(a,b,b+c),Ya:(a,b,c)=>{La.length=0;for(var d;d=x[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;La.push(112==d?z[c>>2]:105==d?y[c>>2]:B[c>>3]);c+=e?8:4}return Ha[a](...La)},Oa:()=>{eb();Oa=null},fa:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ha:(a,b,c)=>{a=K(a);if(!a)return-4;a=Fb(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},y:Ra,Pa:()=>performance.now(),Wa:(a,b)=>{function c(d){L(a)(d,
b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},hb:a=>{var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-oa.buffer.byteLength+65535)/65536;try{oa.grow(e);ra();var h=1;break a}catch(g){}h=void 0}if(h)return!0}return!1},P:(a,b,c,d)=>Ib(a,b,c,d,12,"blur"),ea:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},Q:(a,b,c,d)=>Ib(a,b,c,d,
13,"focus"),Z:(a,b,c,d)=>Jb(a,b,c,d,2,"keydown"),X:(a,b,c,d)=>Jb(a,b,c,d,1,"keypress"),Y:(a,b,c,d)=>Jb(a,b,c,d,3,"keyup"),Xa:(a,b,c)=>{a=L(a);cb(a,b,c)},da:(a,b,c,d)=>Lb(a,b,c,d,5,"mousedown"),aa:(a,b,c,d)=>Lb(a,b,c,d,33,"mouseenter"),$:(a,b,c,d)=>Lb(a,b,c,d,34,"mouseleave"),ba:(a,b,c,d)=>Lb(a,b,c,d,8,"mousemove"),ca:(a,b,c,d)=>Lb(a,b,c,d,6,"mouseup"),S:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.ed||document.body.rd||document.body.qd))return-1;a=K(a);
if(!a)return-4;Mb(a,b,c,d,"mozpointerlockchange");Mb(a,b,c,d,"webkitpointerlockchange");Mb(a,b,c,d,"mspointerlockchange");return Mb(a,b,c,d,"pointerlockchange")},R:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.ed||document.body.rd||document.body.qd))return-1;a=K(a);if(!a)return-4;Nb(a,b,c,d,"mozpointerlockerror");Nb(a,b,c,d,"webkitpointerlockerror");Nb(a,b,c,d,"mspointerlockerror");return Nb(a,b,c,d,"pointerlockerror")},ga:(a,b,c,d)=>Ob(a,b,c,d),T:(a,b,c,d)=>Pb(a,b,c,
d,25,"touchcancel"),U:(a,b,c,d)=>Pb(a,b,c,d,23,"touchend"),V:(a,b,c,d)=>Pb(a,b,c,d,24,"touchmove"),W:(a,b,c,d)=>Pb(a,b,c,d,22,"touchstart"),O:(a,b,c,d)=>{mc(a,b,c,d,31,"webglcontextlost");return 0},N:(a,b,c,d)=>{mc(a,b,c,d,32,"webglcontextrestored");return 0},_:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?nc(a,b,c,d):-1:-4,Va:(a,b)=>{var c=b>>2;b={alpha:!!v[b+0],depth:!!v[b+1],stencil:!!v[b+2],antialias:!!v[b+3],premultipliedAlpha:!!v[b+4],preserveDrawingBuffer:!!v[b+5],powerPreference:oc[y[c+
2]],failIfMajorPerformanceCaveat:!!v[b+12],od:y[c+4],Vd:y[c+5],ud:v[b+24],Id:v[b+25],Wd:y[c+7],Yd:v[b+32]};a=K(a);return!a||b.Id?0:ic(a,b)},Sa:(a,b)=>{a=cc[a];b=b?E(x,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Sb(S);"OES_vertex_array_object"==b&&Tb(S);"WEBGL_draw_buffers"==b&&Ub(S);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Vb(S);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Wb(S);"WEBGL_multi_draw"==b&&(S.Ld=S.getExtension("WEBGL_multi_draw"));
return!!a.hd.getExtension(b)},Ua:a=>kc(a)?0:-5,la:()=>52,kb:()=>52,gb:function(){return 70},jb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var g=z[b>>2],l=z[b+4>>2];b+=8;for(var m=0;m<l;m++){var p=x[g+m],u=pc[a];0===p||10===p?((1===a?na:n)(E(u,0)),u.length=0):u.push(p)}e+=l}z[d>>2]=e;return 0},k:function(a,b,c){const d=a?E(x,a):"";let e;try{e=window.indexedDB.open("chips",1)}catch(h){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+h)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");
e.result.createObjectStore("store")};e.onsuccess=()=>{var h=e.result;let g;try{g=h.transaction(["store"],"readwrite")}catch(p){console.log("fs_js_load_snapshot: db.transaction failed with",p);return}h=g.objectStore("store");let l=d+"_"+b,m=h.get(l);m.onsuccess=()=>{if(void 0!==m.result){let p=m.result.length;console.log("fs_js_load_snapshot:",l,"successfully loaded",p,"bytes");let u=Ec(p);x.set(m.result,u);Fc(c,u,p)}else Fc(c,0,0)};m.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",
l)};g.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},gc:function(a,b,c,d){const e=a?E(x,a):"";console.log("fs_js_save_snapshot: called with",e,b);let h;try{h=window.indexedDB.open("chips",1)}catch(g){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+g);return}h.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");h.result.createObjectStore("store")};h.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");
let g=h.result.transaction(["store"],"readwrite");var l=g.objectStore("store");let m=e+"_"+b;l=l.put(x.subarray(c,c+d),m);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",m,"successfully stored")};l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",m)};g.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};h.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},m:a=>S.activeTexture(a),xa:(a,b)=>{S.attachShader(O[a],Q[b])},b:(a,b)=>{35051==a?S.sd=
b:35052==a&&(S.cd=b);S.bindBuffer(a,Zb[b])},a:(a,b,c)=>{S.bindBufferBase(a,b,Zb[c])},o:(a,b)=>{S.bindFramebuffer(a,$b[b])},Aa:(a,b)=>{S.bindRenderbuffer(a,ac[b])},l:(a,b)=>{S.bindSampler(a,R[b])},c:(a,b)=>{S.bindTexture(a,P[b])},M:a=>{S.bindVertexArray(bc[a])},I:(a,b,c,d)=>S.blendColor(a,b,c,d),J:(a,b)=>S.blendEquationSeparate(a,b),K:(a,b,c,d)=>S.blendFuncSeparate(a,b,c,d),sb:(a,b,c,d,e,h,g,l,m,p)=>S.blitFramebuffer(a,b,c,d,e,h,g,l,m,p),Ca:(a,b,c,d)=>{2<=V.version?c&&b?S.bufferData(a,x,d,c,b):S.bufferData(a,
b,d):S.bufferData(a,c?x.subarray(c,c+b):b,d)},C:(a,b,c,d)=>{2<=V.version?c&&S.bufferSubData(a,b,x,d,c):S.bufferSubData(a,b,x.subarray(d,d+c))},ra:a=>S.checkFramebufferStatus(a),Nb:(a,b,c,d)=>S.clearBufferfi(a,b,c,d),pa:(a,b,c)=>{S.clearBufferfv(a,b,A,c>>2)},Mb:(a,b,c)=>{S.clearBufferiv(a,b,y,c>>2)},r:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},Rb:a=>{S.compileShader(Q[a])},bc:(a,b,c,d,e,h,g,l)=>{2<=V.version?S.cd||!g?S.compressedTexImage2D(a,b,c,d,e,h,g,l):S.compressedTexImage2D(a,b,c,d,e,h,x,l,g):
S.compressedTexImage2D(a,b,c,d,e,h,l?x.subarray(l,l+g):null)},$b:(a,b,c,d,e,h,g,l,m)=>{S.cd?S.compressedTexImage3D(a,b,c,d,e,h,g,l,m):S.compressedTexImage3D(a,b,c,d,e,h,g,x,m,l)},Xb:()=>{var a=gc(O),b=S.createProgram();b.name=a;b.ld=b.jd=b.kd=0;b.pd=1;O[a]=b;return a},Ub:a=>{var b=gc(Q);Q[b]=S.createShader(a);return b},F:a=>S.cullFace(a),Ga:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=Zb[d];e&&(S.deleteBuffer(e),e.name=0,Zb[d]=null,d==S.sd&&(S.sd=0),d==S.cd&&(S.cd=0))}},f:(a,b)=>{for(var c=0;c<
a;++c){var d=y[b+4*c>>2],e=$b[d];e&&(S.deleteFramebuffer(e),e.name=0,$b[d]=null)}},p:a=>{if(a){var b=O[a];b?(S.deleteProgram(b),b.name=0,O[a]=null):T||=1281}},D:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=ac[d];e&&(S.deleteRenderbuffer(e),e.name=0,ac[d]=null)}},g:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=R[d];e&&(S.deleteSampler(e),e.name=0,R[d]=null)}},B:a=>{if(a){var b=Q[a];b?(S.deleteShader(b),Q[a]=null):T||=1281}},E:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=P[d];e&&(S.deleteTexture(e),
e.name=0,P[d]=null)}},Ea:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2];S.deleteVertexArray(bc[d]);bc[d]=null}},w:a=>S.depthFunc(a),v:a=>{S.depthMask(!!a)},e:a=>S.disable(a),L:a=>{S.disableVertexAttribArray(a)},ub:(a,b,c)=>{S.drawArrays(a,b,c)},vb:(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},qa:(a,b)=>{for(var c=qc[a],d=0;d<a;d++)c[d]=y[b+4*d>>2];S.drawBuffers(c)},wb:(a,b,c,d)=>{S.drawElements(a,b,c,d)},xb:(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},j:a=>S.enable(a),Ib:a=>{S.enableVertexAttribArray(a)},
sa:(a,b,c,d)=>{S.framebufferRenderbuffer(a,b,c,ac[d])},q:(a,b,c,d,e)=>{S.framebufferTexture2D(a,b,c,P[d],e)},A:(a,b,c,d,e)=>{S.framebufferTextureLayer(a,b,P[c],d,e)},G:a=>S.frontFace(a),Da:(a,b)=>{U(a,b,"createBuffer",Zb)},ta:(a,b)=>{U(a,b,"createFramebuffer",$b)},Ba:(a,b)=>{U(a,b,"createRenderbuffer",ac)},Zb:(a,b)=>{U(a,b,"createSampler",R)},dc:(a,b)=>{U(a,b,"createTexture",P)},Na:(a,b)=>{U(a,b,"createVertexArray",bc)},Pb:(a,b)=>S.getAttribLocation(O[a],b?E(x,b):""),d:(a,b)=>sc(a,b),Vb:(a,b,c,d)=>
{a=S.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(y[c>>2]=b)},wa:(a,b,c)=>{if(c)if(a>=Yb)T||=1281;else if(a=O[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b){if(!a.ld)for(b=0;b<S.getProgramParameter(a,35718);++b)a.ld=Math.max(a.ld,S.getActiveUniform(a,b).name.length+1);y[c>>2]=a.ld}else if(35722==b){if(!a.jd)for(b=0;b<S.getProgramParameter(a,35721);++b)a.jd=Math.max(a.jd,S.getActiveAttrib(a,b).name.length+
1);y[c>>2]=a.jd}else if(35381==b){if(!a.kd)for(b=0;b<S.getProgramParameter(a,35382);++b)a.kd=Math.max(a.kd,S.getActiveUniformBlockName(a,b).length+1);y[c>>2]=a.kd}else y[c>>2]=S.getProgramParameter(a,b);else T||=1281},Qb:(a,b,c,d)=>{a=S.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(y[c>>2]=b)},ua:(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),y[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(Q[a]),y[c>>2]=a?a.length+1:0):y[c>>
2]=S.getShaderParameter(Q[a],b):T||=1281},La:(a,b)=>{if(2>V.version)return T||=1282,0;var c=dc[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=rc().map(uc),c=dc[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},t:(a,b)=>{b=b?E(x,b):"";if(a=O[a]){var c=a,d=c.gd,e=c.Gd,h;if(!d)for(c.gd=d={},c.Fd={},h=0;h<S.getProgramParameter(c,35718);++h){var g=S.getActiveUniform(c,h);var l=g.name;g=g.size;var m=vc(l);m=0<m?l.slice(0,m):l;var p=c.pd;c.pd+=g;e[m]=[g,
p];for(l=0;l<g;++l)d[p]=l,c.Fd[p++]=m}c=a.gd;d=0;e=b;h=vc(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Gd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else T||=1281;return-1},rb:(a,b,c)=>{for(var d=qc[b],e=0;e<b;e++)d[e]=y[c+4*e>>2];S.invalidateFramebuffer(a,d)},Wb:a=>{a=O[a];S.linkProgram(a);a.gd=0;a.Gd={}},Ma:(a,b)=>{3317==a?ec=b:3314==a&&(fc=b);S.pixelStorei(a,b)},H:(a,b)=>S.polygonOffset(a,b),tb:a=>S.readBuffer(a),ec:(a,b,c,d,e)=>S.renderbufferStorageMultisample(a,
b,c,d,e),ya:(a,b,c)=>{S.samplerParameterf(R[a],b,c)},h:(a,b,c)=>{S.samplerParameteri(R[a],b,c)},s:(a,b,c,d)=>S.scissor(a,b,c,d),Tb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var g=(g=z[c+4*h>>2])?E(x,g,d?z[d+4*h>>2]:void 0):"";e+=g}S.shaderSource(Q[a],e)},Ja:(a,b,c)=>S.stencilFunc(a,b,c),oa:(a,b,c,d)=>S.stencilFuncSeparate(a,b,c,d),u:a=>S.stencilMask(a),Ia:(a,b,c)=>S.stencilOp(a,b,c),na:(a,b,c,d)=>S.stencilOpSeparate(a,b,c,d),ac:(a,b,c,d,e,h,g,l,m)=>{if(2<=V.version){if(S.cd){S.texImage2D(a,b,c,d,e,h,
g,l,m);return}if(m){var p=wc(l);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);S.texImage2D(a,b,c,d,e,h,g,l,p,m);return}}p=m?xc(l,g,d,e,m):null;S.texImage2D(a,b,c,d,e,h,g,l,p)},_b:(a,b,c,d,e,h,g,l,m,p)=>{if(S.cd)S.texImage3D(a,b,c,d,e,h,g,l,m,p);else if(p){var u=wc(m);S.texImage3D(a,b,c,d,e,h,g,l,m,u,p>>>31-Math.clz32(u.BYTES_PER_ELEMENT))}else S.texImage3D(a,b,c,d,e,h,g,l,m,null)},cc:(a,b,c)=>S.texParameteri(a,b,c),qb:(a,b,c,d,e,h,g,l,m)=>{if(2<=V.version){if(S.cd){S.texSubImage2D(a,b,c,d,e,h,g,l,m);return}if(m){var p=
wc(l);S.texSubImage2D(a,b,c,d,e,h,g,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}m=m?xc(l,g,e,h,m):null;S.texSubImage2D(a,b,c,d,e,h,g,l,m)},pb:(a,b,c,d,e,h,g,l,m,p,u)=>{if(S.cd)S.texSubImage3D(a,b,c,d,e,h,g,l,m,p,u);else if(u){var w=wc(p);S.texSubImage3D(a,b,c,d,e,h,g,l,m,p,w,u>>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else S.texSubImage3D(a,b,c,d,e,h,g,l,m,p,null)},Hb:(a,b,c)=>{if(2<=V.version)b&&S.uniform1fv(W(a),A,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>
2,c+4*b>>2);S.uniform1fv(W(a),d)}},va:(a,b)=>{S.uniform1i(W(a),b)},Db:(a,b,c)=>{if(2<=V.version)b&&S.uniform1iv(W(a),y,c>>2,b);else{if(288>=b)for(var d=yc[b],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);S.uniform1iv(W(a),d)}},Gb:(a,b,c)=>{if(2<=V.version)b&&S.uniform2fv(W(a),A,c>>2,2*b);else{if(144>=b)for(var d=X[2*b],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);S.uniform2fv(W(a),d)}},Cb:(a,b,c)=>{if(2<=V.version)b&&S.uniform2iv(W(a),y,c>>
2,2*b);else{if(144>=b)for(var d=yc[2*b],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);S.uniform2iv(W(a),d)}},Fb:(a,b,c)=>{if(2<=V.version)b&&S.uniform3fv(W(a),A,c>>2,3*b);else{if(96>=b)for(var d=X[3*b],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);S.uniform3fv(W(a),d)}},Bb:(a,b,c)=>{if(2<=V.version)b&&S.uniform3iv(W(a),y,c>>2,3*b);else{if(96>=b)for(var d=yc[3*b],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>
2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);S.uniform3iv(W(a),d)}},Eb:(a,b,c)=>{if(2<=V.version)b&&S.uniform4fv(W(a),A,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=A;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=A.subarray(c>>2,c+16*b>>2);S.uniform4fv(W(a),d)}},Ab:(a,b,c)=>{if(2<=V.version)b&&S.uniform4iv(W(a),y,c>>2,4*b);else{if(72>=b)for(var d=yc[4*b],e=0;e<4*b;e+=4)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+
2]=y[c+(4*e+8)>>2],d[e+3]=y[c+(4*e+12)>>2];else d=y.subarray(c>>2,c+16*b>>2);S.uniform4iv(W(a),d)}},zb:(a,b,c,d)=>{if(2<=V.version)b&&S.uniformMatrix4fv(W(a),!!c,A,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=A;d>>=2;for(var g=0;g<16*b;g+=16){var l=d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=A.subarray(d>>
2,d+64*b>>2);S.uniformMatrix4fv(W(a),!!c,e)}},i:a=>{a=O[a];S.useProgram(a);S.Hd=a},Kb:(a,b)=>{S.vertexAttribDivisor(a,b)},Lb:(a,b,c,d,e,h)=>{S.vertexAttribPointer(a,b,c,!!d,e,h)},n:(a,b,c,d)=>S.viewport(a,b,c,d),Ha:function(){f.yd=a=>{0!=Gc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.yd)},fc:function(){f.Ed=a=>{const b=a.clipboardData.getData("text");Ga(()=>{const c=D(b);Hc(c)})};window.addEventListener("paste",f.Ed)},Ob:function(a){f.Zd=[];a=a?E(x,a):"";a=
document.getElementById(a);f.zd=b=>{b.stopPropagation();b.preventDefault()};f.Ad=b=>{b.stopPropagation();b.preventDefault()};f.Bd=b=>{b.stopPropagation();b.preventDefault()};f.Cd=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Dd=c;Ic(c.length);for(let e=0;e<c.length;e++)Ga(()=>{const h=D(c[e].name);Jc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Kc(b.clientX,b.clientY,d)};a.addEventListener("dragenter",f.zd,!1);a.addEventListener("dragleave",
f.Ad,!1);a.addEventListener("dragover",f.Bd,!1);a.addEventListener("drop",f.Cd,!1)},db:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Jb:function(a){const b=f.Dd;return 0>a||a>=b.length?0:b[a].size},yb:function(a,b,c,d,e){const h=new FileReader;h.onload=g=>{g=g.target.result;g.byteLength>d?Lc(a,0,1,b,0,c,d,e):(x.set(new Uint8Array(g),c),Lc(a,1,0,b,g.byteLength,c,d,e))};h.onerror=()=>{Lc(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(f.Dd[a])},fb:function(a){a=
a?E(x,a):"";f.dd=document.getElementById(a);f.dd||console.log("sokol_app.h: invalid target:"+a);f.dd.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Fa:function(){window.removeEventListener("beforeunload",f.yd)},Yb:function(){window.removeEventListener("paste",f.Ed)},nb:function(a){a=a?E(x,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",f.zd);a.removeEventListener("dragleave",f.Ad);a.removeEventListener("dragover",f.Bd);a.removeEventListener("drop",
f.Cd)},z:function(){f.dd&&f.dd.requestPointerLock&&f.dd.requestPointerLock()},eb:function(a,b){if(f.dd){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.dd.style.cursor=a}},cb:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(x.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Sb:function(a){a=a?E(x,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";
b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},Za:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];Ga(()=>{const e=D(c),h=D(d);Mc(e,h)})}},$a:function(){return f.bd?f.bd.bufferSize:0},bb:function(a,b,c){f.Xc=null;f.bd=null;"undefined"!==typeof AudioContext?f.Xc=new AudioContext({sampleRate:a,
latencyHint:"interactive"}):(f.Xc=null,console.log("sokol_audio.h: no WebAudio support"));return f.Xc?(console.log("sokol_audio.h: sample rate ",f.Xc.sampleRate),f.bd=f.Xc.createScriptProcessor(c,0,b),f.bd.onaudioprocess=d=>{const e=d.outputBuffer.length,h=Nc(e);if(h){const g=d.outputBuffer.numberOfChannels;for(let l=0;l<g;l++){const m=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)m[p]=A[(h>>2)+(g*p+l)]}}},f.bd.connect(f.Xc.destination),a=()=>{f.Xc&&"suspended"===f.Xc.state&&f.Xc.resume()},
document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},ab:function(){return f.Xc?f.Xc.sampleRate:0},ka:function(){const a=f.Xc;null!==a&&(f.bd&&f.bd.disconnect(),a.close(),f.Xc=null,f.bd=null)},_a:function(){if(f.Xc)return"suspended"===f.Xc.state?1:0},x:function(a,b,c,d,e,h){b=b?E(x,b):"";const g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";const l=0<d;l&&g.setRequestHeader("Range",
"bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(g.readyState==XMLHttpRequest.DONE)if(206==g.status||200==g.status&&!l){const m=new Uint8Array(g.response),p=m.length;p<=h?(x.set(m,e),Oc(a,d,p)):Pc(a)}else Qc(a,g.status)};g.send()},ja:function(a,b){b=b?E(x,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");Rc(a,d)}else Qc(a,c.status)};c.send()},za:function(){return navigator.userAgent.includes("Macintosh")?
1:0},ia:function(a,b){b=b?E(x,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Ra:function(){console.log("webapi_js_event_continued()");f.webapi_onContinued?f.webapi_onContinued():console.log("no Module.webapi_onContinued function")},Qa:function(){console.log("webapi_js_event_reboot()");f.webapi_onReboot?f.webapi_onReboot():console.log("no Module.webapi_onReboot function")},Ka:function(){console.log("webapi_js_event_reset()");
f.webapi_onReset?f.webapi_onReset():console.log("no Module.webapi_onReset function")},Ta:function(a,b){console.log("webapi_js_event_stopped()");f.webapi_onStopped?f.webapi_onStopped(a,b):console.log("no Module.webapi_onStopped function")}},Z=function(){function a(c){Z=c.exports;oa=Z.hc;ra();Hb=Z.Tc;ta.unshift(Z.ic);C--;f.monitorRunDependencies?.(C);0==C&&(null!==xa&&(clearInterval(xa),xa=null),ya&&(c=ya,ya=null,c()));return Z}var b={a:Sc};C++;f.monitorRunDependencies?.(C);if(f.instantiateWasm)try{return f.instantiateWasm(b,
a)}catch(c){return n(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ba||=Aa("c64-ui.wasm")?"c64-ui.wasm":f.locateFile?f.locateFile("c64-ui.wasm",k):k+"c64-ui.wasm";Fa(b,function(c){a(c.instance)});return{}}(),N=a=>(N=Z.jc)(a),Ec=f._fs_emsc_alloc=a=>(Ec=f._fs_emsc_alloc=Z.kc)(a),Fc=f._fs_emsc_load_snapshot_callback=(a,b,c)=>(Fc=f._fs_emsc_load_snapshot_callback=Z.lc)(a,b,c);f._webapi_dbg_connect=()=>(f._webapi_dbg_connect=Z.mc)();
f._webapi_dbg_disconnect=()=>(f._webapi_dbg_disconnect=Z.nc)();f._webapi_alloc=a=>(f._webapi_alloc=Z.oc)(a);f._webapi_free=a=>(f._webapi_free=Z.pc)(a);f._webapi_boot=()=>(f._webapi_boot=Z.qc)();f._webapi_reset=()=>(f._webapi_reset=Z.rc)();f._webapi_ready=()=>(f._webapi_ready=Z.sc)();f._webapi_load=(a,b)=>(f._webapi_load=Z.tc)(a,b);f._webapi_load_snapshot=a=>(f._webapi_load_snapshot=Z.uc)(a);f._webapi_save_snapshot=a=>(f._webapi_save_snapshot=Z.vc)(a);
f._webapi_dbg_add_breakpoint=a=>(f._webapi_dbg_add_breakpoint=Z.wc)(a);f._webapi_dbg_remove_breakpoint=a=>(f._webapi_dbg_remove_breakpoint=Z.xc)(a);f._webapi_dbg_break=()=>(f._webapi_dbg_break=Z.yc)();f._webapi_dbg_continue=()=>(f._webapi_dbg_continue=Z.zc)();f._webapi_dbg_step_next=()=>(f._webapi_dbg_step_next=Z.Ac)();f._webapi_dbg_step_into=()=>(f._webapi_dbg_step_into=Z.Bc)();f._webapi_dbg_cpu_state=()=>(f._webapi_dbg_cpu_state=Z.Cc)();
f._webapi_dbg_request_disassembly=(a,b,c)=>(f._webapi_dbg_request_disassembly=Z.Dc)(a,b,c);f._webapi_dbg_read_memory=(a,b)=>(f._webapi_dbg_read_memory=Z.Ec)(a,b);f._webapi_input=a=>(f._webapi_input=Z.Fc)(a);
var Hc=f.__sapp_emsc_onpaste=a=>(Hc=f.__sapp_emsc_onpaste=Z.Gc)(a),Gc=f.__sapp_html5_get_ask_leave_site=()=>(Gc=f.__sapp_html5_get_ask_leave_site=Z.Hc)(),Ic=f.__sapp_emsc_begin_drop=a=>(Ic=f.__sapp_emsc_begin_drop=Z.Ic)(a),Jc=f.__sapp_emsc_drop=(a,b)=>(Jc=f.__sapp_emsc_drop=Z.Jc)(a,b),Kc=f.__sapp_emsc_end_drop=(a,b,c)=>(Kc=f.__sapp_emsc_end_drop=Z.Kc)(a,b,c),Lc=f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,g,l)=>(Lc=f.__sapp_emsc_invoke_fetch_cb=Z.Lc)(a,b,c,d,e,h,g,l),Tc=f._main=(a,b)=>(Tc=f._main=Z.Mc)(a,
b),Nc=f.__saudio_emsc_pull=a=>(Nc=f.__saudio_emsc_pull=Z.Nc)(a),Mc=f.__sargs_add_kvp=(a,b)=>(Mc=f.__sargs_add_kvp=Z.Oc)(a,b),Rc=f.__sfetch_emsc_head_response=(a,b)=>(Rc=f.__sfetch_emsc_head_response=Z.Pc)(a,b),Oc=f.__sfetch_emsc_get_response=(a,b,c)=>(Oc=f.__sfetch_emsc_get_response=Z.Qc)(a,b,c),Qc=f.__sfetch_emsc_failed_http_status=(a,b)=>(Qc=f.__sfetch_emsc_failed_http_status=Z.Rc)(a,b),Pc=f.__sfetch_emsc_failed_buffer_too_small=a=>(Pc=f.__sfetch_emsc_failed_buffer_too_small=Z.Sc)(a),Bc=a=>(Bc=
Z.Uc)(a),zc=a=>(zc=Z.Vc)(a),Ac=()=>(Ac=Z.Wc)(),Uc;ya=function Vc(){Uc||Wc();Uc||(ya=Vc)};function Xc(a=[]){var b=Tc;a.unshift(fa);var c=a.length,d=zc(4*(c+1)),e=d;a.forEach(g=>{z[e>>2]=D(g);e+=4});z[e>>2]=0;try{var h=b(c,d);db(h)}catch(g){bb(g)}}
function Wc(){var a=ea;function b(){if(!Uc&&(Uc=!0,f.calledRun=!0,!r)){Ia(ta);Ia(ua);f.onRuntimeInitialized?.();Yc&&Xc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();va.unshift(c)}Ia(va)}}if(!(0<C)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)wa();Ia(sa);0<C||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Yc=!0;f.noInitialRun&&(Yc=!1);Wc();
