var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs"),ka=require("path");k=__dirname+"/";ja=a=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a)};ia=a=>{a=la(a)?new URL(a):ka.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof ma||a.context instanceof ma))throw a;
});ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?"":k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=a=>la(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{(200==
d.status||0==d.status&&d.response)&&c(d.response);b(d.status)};d.onerror=b;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var na=f.print||console.log.bind(console),n=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);f.quit&&(ha=f.quit);var q;f.wasmBinary&&(q=f.wasmBinary);var oa,r=!1,pa,t,u,qa,ra,w,x,y,z;
function sa(){var a=oa.buffer;f.HEAP8=t=new Int8Array(a);f.HEAP16=qa=new Int16Array(a);f.HEAPU8=u=new Uint8Array(a);f.HEAPU16=ra=new Uint16Array(a);f.HEAP32=w=new Int32Array(a);f.HEAPU32=x=new Uint32Array(a);f.HEAPF32=y=new Float32Array(a);f.HEAPF64=z=new Float64Array(a)}var ta=[],ua=[],va=[],wa=[];function xa(){var a=f.preRun.shift();ta.unshift(a)}var A=0,ya=null,za=null;
function Aa(a){f.onAbort?.(a);a="Aborted("+a+")";n(a);r=!0;pa=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ba=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),Ca;function Da(a){if(a==Ca&&q)return new Uint8Array(q);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}function Ea(a){return q?Promise.resolve().then(()=>Da(a)):ia(a).then(b=>new Uint8Array(b),()=>Da(a))}
function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{n(`failed to asynchronously prepare wasm: ${d}`);Aa(d)})}function Ga(a,b){var c=Ca;q||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||la(c)||ca||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){n(`wasm streaming compile failed: ${e}`);n("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}
var Ia={98879:()=>{const a=f._webapi_input;f._webapi_input=b=>{Ha(()=>a(B(b)))}}};function ma(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ja=a=>{for(;0<a.length;)a.shift()(f)},Ka=f.noExitRuntime||!0,La="undefined"!=typeof TextDecoder?new TextDecoder:void 0,C=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&La)return La.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|
e&1023))}}else d+=String.fromCharCode(e)}return d},Ma=[],Wa=(a,b)=>{Na=a;Oa=b;if(Pa)if(Qa||=!0,0==a)D=function(){var d=Math.max(0,Ra+b-Sa())|0;setTimeout(Ta,d)};else if(1==a)D=function(){Ua(Ta)};else if(2==a){if("undefined"==typeof Va)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Va=function(d){c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);
postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Va=setImmediate;D=function(){Va(Ta)}}},Sa;Sa=()=>performance.now();
var db=(a,b,c,d,e)=>{Pa=a;Xa=d;var h=E;Qa=!1;Ta=function(){if(!r)if(0<Ya.length){var g=Ya.shift();g.Vd(g.Qd);if(Za){var l=Za,m=0==l%1?l-1:Math.floor(l);Za=g.Sd?m:(8*l+(m+.5))/9}f.setStatus&&(g=f.statusMessage||"Please wait...",l=Za,m=$a.Ud,l?l<m?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(g):f.setStatus(""));h<E||setTimeout(Ta,0)}else if(!(h<E))if(ab=ab+1|0,1==Na&&1<Oa&&0!=ab%Oa)D();else{0==Na&&(Ra=Sa());if(!(r||f.preMainLoop&&!1===f.preMainLoop())){if(!r)try{if(a(),!Ka)try{pa=
g=pa,bb(g)}catch(p){cb(p)}}catch(p){cb(p)}f.postMainLoop?.()}h<E||("object"==typeof SDL&&SDL.audio?.Zd?.(),D())}};e||(b&&0<b?Wa(0,1E3/b):Wa(1,1),D());if(c)throw"unwind";},cb=a=>{a instanceof ma||"unwind"==a||ha(1,a)},bb=a=>{pa=a;Ka||(f.onExit?.(a),r=!0);ha(a,new ma(a))},eb=a=>{pa=a;bb(a)},Qa=!1,D=null,E=0,Pa=null,Xa=0,Na=0,Oa=0,ab=0,Ya=[];function fb(){D=null;E++}var $a={},Ra,Ta,Za,gb=!1,hb=!1,ib=[];
function jb(){function a(){hb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!kb){kb=!0;var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!hb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}var lb=!1,mb=void 0,G=void 0;
function nb(){if(!gb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var ob=0;function Ua(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ob)ob=b+1E3/60;else for(;b+2>=ob;)ob+=1E3/60;setTimeout(a,Math.max(ob-b,0))}}var pb=[];function qb(){var a=f.canvas;pb.forEach(b=>b(a.width,a.height))}
function rb(a,b,c){b&&c?(a.Od=b,a.Ld=c):(b=a.Od,c=a.Ld);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var h=Math.min(screen.width/d,screen.height/e);d=Math.round(d*h);e=Math.round(e*
h)}G?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Va,kb,sb=0,tb=[];
function ub(){if(navigator.userActivation?navigator.userActivation.isActive:sb&&vb.od){var a=tb;tb=[];for(var b of a)b.be(...b.Rd)}}var H=[];function wb(a){var b=H[a];b.target.removeEventListener(b.$c,b.xd,b.ad);H.splice(a,1)}function I(a){if(!a.target)return-4;if(a.bd)a.xd=function(c){++sb;vb=a;ub();a.cd(c);ub();--sb},a.target.addEventListener(a.$c,a.xd,a.ad),H.push(a);else for(var b=0;b<H.length;++b)H[b].target==a.target&&H[b].$c==a.$c&&wb(b--);return 0}
function xb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var vb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],J=a=>{a=2<a?a?C(u,a):"":a;return Fb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Gb=a=>0>Fb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Hb=[],Ib,K=a=>{var b=Hb[a];b||(a>=Hb.length&&(Hb.length=a+1),Hb[a]=b=Ib.get(a));return b},L=(a,b,c)=>{var d=u;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var l=
a.charCodeAt(++h);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},Jb=(a,b,c,d,e,h)=>{yb||=M(256);a={target:J(a),$c:h,bd:d,cd:(g=event)=>{var l=g.target.id?g.target.id:"",m=yb;L(xb(g.target),m+0,128);L(l,m+128,128);K(d)(e,m,b)&&g.preventDefault()},ad:c};return I(a)},Kb=(a,
b,c,d,e,h)=>{zb||=M(160);a={target:J(a),$c:h,bd:d,cd:g=>{var l=zb;z[l>>3]=g.timeStamp;var m=l>>2;w[m+2]=g.location;t[l+12]=g.ctrlKey;t[l+13]=g.shiftKey;t[l+14]=g.altKey;t[l+15]=g.metaKey;t[l+16]=g.repeat;w[m+5]=g.charCode;w[m+6]=g.keyCode;w[m+7]=g.which;L(g.key||"",l+32,32);L(g.code||"",l+64,32);L(g.char||"",l+96,32);L(g.locale||"",l+128,32);K(d)(e,l,b)&&g.preventDefault()},ad:c};return I(a)},Lb=(a,b,c)=>{z[a>>3]=b.timeStamp;var d=a>>2;w[d+2]=b.screenX;w[d+3]=b.screenY;w[d+4]=b.clientX;w[d+5]=b.clientY;
t[a+24]=b.ctrlKey;t[a+25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;qa[2*d+14]=b.button;qa[2*d+15]=b.buttons;w[d+8]=b.movementX;w[d+9]=b.movementY;a=Gb(c);w[d+10]=b.clientX-(a.left|0);w[d+11]=b.clientY-(a.top|0)},Mb=(a,b,c,d,e,h)=>{Ab||=M(64);a=J(a);return I({target:a,od:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,$c:h,bd:d,cd:(g=event)=>{Lb(Ab,g,a);K(d)(e,Ab,b)&&g.preventDefault()},ad:c})},Nb=(a,b,c,d,e)=>{Bb||=M(257);return I({target:a,$c:e,bd:d,cd:(h=event)=>{var g=Bb,l=document.pointerLockElement||
document.hd||document.td||document.sd;t[g]=!!l;var m=l?.id||"";L(xb(l),g+1,128);L(m,g+129,128);K(d)(20,g,b)&&h.preventDefault()},ad:c})},Ob=(a,b,c,d,e)=>I({target:a,$c:e,bd:d,cd:(h=event)=>{K(d)(38,0,b)&&h.preventDefault()},ad:c}),Pb=(a,b,c,d)=>{Cb||=M(36);a=J(a);return I({target:a,$c:"resize",bd:d,cd:(e=event)=>{if(e.target==a){var h=document.body;if(h){var g=Cb;w[g>>2]=0;w[g+4>>2]=h.clientWidth;w[g+8>>2]=h.clientHeight;w[g+12>>2]=innerWidth;w[g+16>>2]=innerHeight;w[g+20>>2]=outerWidth;w[g+24>>2]=
outerHeight;w[g+28>>2]=pageXOffset|0;w[g+32>>2]=pageYOffset|0;K(d)(10,g,b)&&e.preventDefault()}}},ad:c})},Qb=(a,b,c,d,e,h)=>{Db||=M(1552);a=J(a);return I({target:a,od:"touchstart"==h||"touchend"==h,$c:h,bd:d,cd:g=>{var l={},m=g.touches;for(var p of m)p.yd=p.zd=0,l[p.identifier]=p;for(var v of g.changedTouches)v.yd=1,l[v.identifier]=v;for(var P of g.targetTouches)l[P.identifier].zd=1;m=Db;z[m>>3]=g.timeStamp;t[m+12]=g.ctrlKey;t[m+13]=g.shiftKey;t[m+14]=g.altKey;t[m+15]=g.metaKey;p=m+16;v=Gb(a);P=0;
for(let F of Object.values(l))if(l=p>>2,w[l]=F.identifier,w[l+1]=F.screenX,w[l+2]=F.screenY,w[l+3]=F.clientX,w[l+4]=F.clientY,w[l+5]=F.pageX,w[l+6]=F.pageY,t[p+28]=F.yd,t[p+29]=F.zd,w[l+8]=F.clientX-(v.left|0),w[l+9]=F.clientY-(v.top|0),p+=48,31<++P)break;w[m+8>>2]=P;K(d)(e,m,b)&&g.preventDefault()},ad:c})},Rb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=
(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,d,e,h,g))},Sb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Tb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Ub=a=>{a.Td=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},Vb=a=>{a.Wd=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},
Wb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Xb=1,Yb=[],N=[],Zb=[],$b=[],O=[],Q=[],ac=[],bc=[],R=[],cc={},dc=4,ec=0,fc=a=>{for(var b=Xb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=S[c](),g=h&&fc(d);h?(h.name=g,d[g]=h):T||=1282;w[b+4*e>>2]=g}},hc=(a,b)=>{a.hd||(a.hd=a.getContext,a.getContext=function(d,e){e=a.hd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.qd?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
gc(c,b):0},gc=(a,b)=>{var c=fc(bc),d={handle:c,attributes:b,version:b.qd,kd:a};a.canvas&&(a.canvas.Pd=d);bc[c]=d;("undefined"==typeof b.wd||b.wd)&&ic(d);return c},jc=a=>{V=bc[a];f.pd=S=V?.kd;return!(a&&!S)},ic=a=>{a||=V;if(!a.Md){a.Md=!0;var b=a.kd;Rb(b);Sb(b);Tb(b);Ub(b);Vb(b);2<=a.version&&(b.vd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.vd)b.vd=b.getExtension("EXT_disjoint_timer_query");b.Nd=b.getExtension("WEBGL_multi_draw");Wb(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},kc={},T,V,lc=(a,b,c,d,e,h)=>{a={target:J(a),$c:h,bd:d,cd:(g=event)=>{K(d)(e,0,b)&&g.preventDefault()},ad:c};I(a)},mc=(a,b,c,d)=>{Eb||=M(96);return I({target:a,od:!0,$c:"wheel",bd:d,cd:(e=event)=>{var h=Eb;Lb(h,e,a);z[h+64>>3]=e.deltaX;z[h+72>>3]=e.deltaY;z[h+80>>3]=e.deltaZ;w[h+88>>2]=e.deltaMode;K(d)(9,h,b)&&e.preventDefault()},ad:c})},nc=["default","low-power","high-performance"],oc=[null,[],[]],pc=[];
function qc(){var a=Wb(S);return a=a.concat(a.map(b=>"GL_"+b))}
var rc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=qc().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}w[b>>2]=c}else T||=1281},sc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},tc=a=>{var b=sc(a)+1,c=M(b);c&&L(a,c,b);return c},uc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),vc=a=>{a-=5120;return 0==a?t:1==a?u:2==a?qa:4==a?w:6==a?y:5==a||28922==a||28520==a||30779==a||30782==a?x:ra},wc=(a,b,c,d,e)=>{a=vc(a);b=d*((ec||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+dc-1&-dc);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=S.Jd;if(b){var c=b.jd[a];"number"==typeof c&&(b.jd[a]=c=S.getUniformLocation(b,b.Hd[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],xc=[],B=a=>{var b=sc(a)+1,c=yc(b);L(a,c,b);return c},Ha=a=>{var b=zc();a();Ac(b)};
f.requestFullscreen=function(a,b){function c(){gb=!1;var h=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===h?(d.exitFullscreen=nb,mb&&d.requestPointerLock(),gb=!0,G?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]|8388608),rb(f.canvas),qb()):rb(d)):(h.parentNode.insertBefore(d,h),h.parentNode.removeChild(h),G?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>
2]&-8388609),rb(f.canvas),qb()):rb(d));f.onFullScreen?.(gb);f.onFullscreen?.(gb)}mb=a;G=b;"undefined"==typeof mb&&(mb=!0);"undefined"==typeof G&&(G=!1);var d=f.canvas;lb||(lb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};f.requestAnimationFrame=Ua;f.setCanvasSize=function(a,b,c){rb(f.canvas,a,b);c||qb()};f.pauseMainLoop=fb;f.resumeMainLoop=function(){E++;var a=Na,b=Oa,c=Pa;Pa=null;db(c,0,!1,Xa,!0);Wa(a,b);D()};
f.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};f.createContext=function(a,b,c,d){if(b&&f.pd&&a==f.canvas)return f.pd;var e;if(b){var h={antialias:!1,alpha:!1,qd:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var g in d)h[g]=d[g];if("undefined"!=typeof kc&&(e=hc(a,h)))var l=bc[e].kd}else l=a.getContext("2d");if(!l)return null;c&&(f.pd=l,b&&jc(e),f.ce=b,ib.forEach(m=>m()),jb());return l};
for(var S,Y=0;32>Y;++Y)pc.push(Array(Y));var Bc=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=Bc.subarray(0,Y);var Cc=new Int32Array(288);for(Y=0;288>=Y;++Y)xc[Y]=Cc.subarray(0,Y);
var Rc={na:function(){return 0},lb:function(){return 0},mb:function(){},nb:()=>{Aa("")},ib:(a,b,c)=>u.copyWithin(a,b,b+c),Ya:(a,b,c)=>{Ma.length=0;for(var d;d=u[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Ma.push(112==d?x[c>>2]:105==d?w[c>>2]:z[c>>3]);c+=e?8:4}return Ia[a](...Ma)},Pa:()=>{fb();Pa=null},ga:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ia:(a,b,c)=>{a=J(a);if(!a)return-4;a=Gb(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},z:Sa,Qa:()=>performance.now(),Wa:(a,b)=>{function c(d){K(a)(d,
b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},hb:a=>{var b=u.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-oa.buffer.byteLength+65535)/65536;try{oa.grow(e);sa();var h=1;break a}catch(g){}h=void 0}if(h)return!0}return!1},Q:(a,b,c,d)=>Jb(a,b,c,d,12,"blur"),fa:(a,b,c)=>{a=J(a);if(!a)return-4;a.width=b;a.height=c;return 0},R:(a,b,c,d)=>Jb(a,b,c,d,
13,"focus"),_:(a,b,c,d)=>Kb(a,b,c,d,2,"keydown"),Y:(a,b,c,d)=>Kb(a,b,c,d,1,"keypress"),Z:(a,b,c,d)=>Kb(a,b,c,d,3,"keyup"),Xa:(a,b,c)=>{a=K(a);db(a,b,c)},ea:(a,b,c,d)=>Mb(a,b,c,d,5,"mousedown"),ba:(a,b,c,d)=>Mb(a,b,c,d,33,"mouseenter"),aa:(a,b,c,d)=>Mb(a,b,c,d,34,"mouseleave"),ca:(a,b,c,d)=>Mb(a,b,c,d,8,"mousemove"),da:(a,b,c,d)=>Mb(a,b,c,d,6,"mouseup"),T:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.hd||document.body.td||document.body.sd))return-1;a=J(a);
if(!a)return-4;Nb(a,b,c,d,"mozpointerlockchange");Nb(a,b,c,d,"webkitpointerlockchange");Nb(a,b,c,d,"mspointerlockchange");return Nb(a,b,c,d,"pointerlockchange")},S:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.hd||document.body.td||document.body.sd))return-1;a=J(a);if(!a)return-4;Ob(a,b,c,d,"mozpointerlockerror");Ob(a,b,c,d,"webkitpointerlockerror");Ob(a,b,c,d,"mspointerlockerror");return Ob(a,b,c,d,"pointerlockerror")},ha:(a,b,c,d)=>Pb(a,b,c,d),U:(a,b,c,d)=>Qb(a,b,c,
d,25,"touchcancel"),V:(a,b,c,d)=>Qb(a,b,c,d,23,"touchend"),W:(a,b,c,d)=>Qb(a,b,c,d,24,"touchmove"),X:(a,b,c,d)=>Qb(a,b,c,d,22,"touchstart"),P:(a,b,c,d)=>{lc(a,b,c,d,31,"webglcontextlost");return 0},O:(a,b,c,d)=>{lc(a,b,c,d,32,"webglcontextrestored");return 0},$:(a,b,c,d)=>(a=J(a))?"undefined"!=typeof a.onwheel?mc(a,b,c,d):-1:-4,Va:(a,b)=>{var c=b>>2;b={alpha:!!t[b+0],depth:!!t[b+1],stencil:!!t[b+2],antialias:!!t[b+3],premultipliedAlpha:!!t[b+4],preserveDrawingBuffer:!!t[b+5],powerPreference:nc[w[c+
2]],failIfMajorPerformanceCaveat:!!t[b+12],qd:w[c+4],Xd:w[c+5],wd:t[b+24],Kd:t[b+25],Yd:w[c+7],$d:t[b+32]};a=J(a);return!a||b.Kd?0:hc(a,b)},Ta:(a,b)=>{a=bc[a];b=b?C(u,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Rb(S);"OES_vertex_array_object"==b&&Sb(S);"WEBGL_draw_buffers"==b&&Tb(S);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Ub(S);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Vb(S);"WEBGL_multi_draw"==b&&(S.Nd=S.getExtension("WEBGL_multi_draw"));
return!!a.kd.getExtension(b)},Ua:a=>jc(a)?0:-5,ma:()=>52,kb:()=>52,fb:function(){return 70},jb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var g=x[b>>2],l=x[b+4>>2];b+=8;for(var m=0;m<l;m++){var p=u[g+m],v=oc[a];0===p||10===p?((1===a?na:n)(C(v,0)),v.length=0):v.push(p)}e+=l}x[d>>2]=e;return 0},k:function(a,b,c){const d=a?C(u,a):"";let e;try{e=window.indexedDB.open("chips",1)}catch(h){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+h)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");
e.result.createObjectStore("store")};e.onsuccess=()=>{var h=e.result;let g;try{g=h.transaction(["store"],"readwrite")}catch(p){console.log("fs_js_load_snapshot: db.transaction failed with",p);return}h=g.objectStore("store");let l=d+"_"+b,m=h.get(l);m.onsuccess=()=>{if(void 0!==m.result){let p=m.result.length;console.log("fs_js_load_snapshot:",l,"successfully loaded",p,"bytes");let v=Dc(p);u.set(m.result,v);Ec(c,v,p)}else Ec(c,0,0)};m.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",
l)};g.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},ic:function(a,b,c,d){const e=a?C(u,a):"";console.log("fs_js_save_snapshot: called with",e,b);let h;try{h=window.indexedDB.open("chips",1)}catch(g){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+g);return}h.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");h.result.createObjectStore("store")};h.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");
let g=h.result.transaction(["store"],"readwrite");var l=g.objectStore("store");let m=e+"_"+b;l=l.put(u.subarray(c,c+d),m);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",m,"successfully stored")};l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",m)};g.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};h.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},m:a=>S.activeTexture(a),ya:(a,b)=>{S.attachShader(N[a],Q[b])},b:(a,b)=>{35051==a?S.ud=
b:35052==a&&(S.ed=b);S.bindBuffer(a,Yb[b])},a:(a,b,c)=>{S.bindBufferBase(a,b,Yb[c])},o:(a,b)=>{S.bindFramebuffer(a,Zb[b])},Ba:(a,b)=>{S.bindRenderbuffer(a,$b[b])},l:(a,b)=>{S.bindSampler(a,R[b])},c:(a,b)=>{S.bindTexture(a,O[b])},N:a=>{S.bindVertexArray(ac[a])},J:(a,b,c,d)=>S.blendColor(a,b,c,d),K:(a,b)=>S.blendEquationSeparate(a,b),L:(a,b,c,d)=>S.blendFuncSeparate(a,b,c,d),sb:(a,b,c,d,e,h,g,l,m,p)=>S.blitFramebuffer(a,b,c,d,e,h,g,l,m,p),Da:(a,b,c,d)=>{2<=V.version?c&&b?S.bufferData(a,u,d,c,b):S.bufferData(a,
b,d):S.bufferData(a,c?u.subarray(c,c+b):b,d)},D:(a,b,c,d)=>{2<=V.version?c&&S.bufferSubData(a,b,u,d,c):S.bufferSubData(a,b,u.subarray(d,d+c))},sa:a=>S.checkFramebufferStatus(a),Nb:(a,b,c,d)=>S.clearBufferfi(a,b,c,d),qa:(a,b,c)=>{S.clearBufferfv(a,b,y,c>>2)},Mb:(a,b,c)=>{S.clearBufferiv(a,b,w,c>>2)},r:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},Rb:a=>{S.compileShader(Q[a])},bc:(a,b,c,d,e,h,g,l)=>{2<=V.version?S.ed||!g?S.compressedTexImage2D(a,b,c,d,e,h,g,l):S.compressedTexImage2D(a,b,c,d,e,h,u,l,g):
S.compressedTexImage2D(a,b,c,d,e,h,l?u.subarray(l,l+g):null)},$b:(a,b,c,d,e,h,g,l,m)=>{S.ed?S.compressedTexImage3D(a,b,c,d,e,h,g,l,m):S.compressedTexImage3D(a,b,c,d,e,h,g,u,m,l)},Xb:()=>{var a=fc(N),b=S.createProgram();b.name=a;b.nd=b.ld=b.md=0;b.rd=1;N[a]=b;return a},Tb:a=>{var b=fc(Q);Q[b]=S.createShader(a);return b},G:a=>S.cullFace(a),Ha:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Yb[d];e&&(S.deleteBuffer(e),e.name=0,Yb[d]=null,d==S.ud&&(S.ud=0),d==S.ed&&(S.ed=0))}},f:(a,b)=>{for(var c=0;c<
a;++c){var d=w[b+4*c>>2],e=Zb[d];e&&(S.deleteFramebuffer(e),e.name=0,Zb[d]=null)}},p:a=>{if(a){var b=N[a];b?(S.deleteProgram(b),b.name=0,N[a]=null):T||=1281}},E:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=$b[d];e&&(S.deleteRenderbuffer(e),e.name=0,$b[d]=null)}},g:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=R[d];e&&(S.deleteSampler(e),e.name=0,R[d]=null)}},C:a=>{if(a){var b=Q[a];b?(S.deleteShader(b),Q[a]=null):T||=1281}},F:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=O[d];e&&(S.deleteTexture(e),
e.name=0,O[d]=null)}},Fa:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2];S.deleteVertexArray(ac[d]);ac[d]=null}},w:a=>S.depthFunc(a),v:a=>{S.depthMask(!!a)},e:a=>S.disable(a),M:a=>{S.disableVertexAttribArray(a)},ub:(a,b,c)=>{S.drawArrays(a,b,c)},vb:(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},ra:(a,b)=>{for(var c=pc[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];S.drawBuffers(c)},wb:(a,b,c,d)=>{S.drawElements(a,b,c,d)},xb:(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},j:a=>S.enable(a),Ib:a=>{S.enableVertexAttribArray(a)},
ta:(a,b,c,d)=>{S.framebufferRenderbuffer(a,b,c,$b[d])},q:(a,b,c,d,e)=>{S.framebufferTexture2D(a,b,c,O[d],e)},B:(a,b,c,d,e)=>{S.framebufferTextureLayer(a,b,O[c],d,e)},H:a=>S.frontFace(a),Ea:(a,b)=>{U(a,b,"createBuffer",Yb)},ua:(a,b)=>{U(a,b,"createFramebuffer",Zb)},Ca:(a,b)=>{U(a,b,"createRenderbuffer",$b)},Zb:(a,b)=>{U(a,b,"createSampler",R)},fc:(a,b)=>{U(a,b,"createTexture",O)},Oa:(a,b)=>{U(a,b,"createVertexArray",ac)},Pb:(a,b)=>S.getAttribLocation(N[a],b?C(u,b):""),d:(a,b)=>rc(a,b),Vb:(a,b,c,d)=>
{a=S.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(w[c>>2]=b)},xa:(a,b,c)=>{if(c)if(a>=Xb)T||=1281;else if(a=N[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.nd)for(b=0;b<S.getProgramParameter(a,35718);++b)a.nd=Math.max(a.nd,S.getActiveUniform(a,b).name.length+1);w[c>>2]=a.nd}else if(35722==b){if(!a.ld)for(b=0;b<S.getProgramParameter(a,35721);++b)a.ld=Math.max(a.ld,S.getActiveAttrib(a,b).name.length+
1);w[c>>2]=a.ld}else if(35381==b){if(!a.md)for(b=0;b<S.getProgramParameter(a,35382);++b)a.md=Math.max(a.md,S.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.md}else w[c>>2]=S.getProgramParameter(a,b);else T||=1281},Qb:(a,b,c,d)=>{a=S.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(w[c>>2]=b)},va:(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(Q[a]),w[c>>2]=a?a.length+1:0):w[c>>
2]=S.getShaderParameter(Q[a],b):T||=1281},Ma:(a,b)=>{if(2>V.version)return T||=1282,0;var c=cc[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=qc().map(tc),c=cc[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},t:(a,b)=>{b=b?C(u,b):"";if(a=N[a]){var c=a,d=c.jd,e=c.Id,h;if(!d)for(c.jd=d={},c.Hd={},h=0;h<S.getProgramParameter(c,35718);++h){var g=S.getActiveUniform(c,h);var l=g.name;g=g.size;var m=uc(l);m=0<m?l.slice(0,m):l;var p=c.rd;c.rd+=g;e[m]=[g,
p];for(l=0;l<g;++l)d[p]=l,c.Hd[p++]=m}c=a.jd;d=0;e=b;h=uc(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Id[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else T||=1281;return-1},rb:(a,b,c)=>{for(var d=pc[b],e=0;e<b;e++)d[e]=w[c+4*e>>2];S.invalidateFramebuffer(a,d)},Wb:a=>{a=N[a];S.linkProgram(a);a.jd=0;a.Id={}},Na:(a,b)=>{3317==a?dc=b:3314==a&&(ec=b);S.pixelStorei(a,b)},I:(a,b)=>S.polygonOffset(a,b),tb:a=>S.readBuffer(a),gc:(a,b,c,d,e)=>S.renderbufferStorageMultisample(a,
b,c,d,e),za:(a,b,c)=>{S.samplerParameterf(R[a],b,c)},h:(a,b,c)=>{S.samplerParameteri(R[a],b,c)},s:(a,b,c,d)=>S.scissor(a,b,c,d),Sb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var g=(g=x[c+4*h>>2])?C(u,g,d?x[d+4*h>>2]:void 0):"";e+=g}S.shaderSource(Q[a],e)},Ka:(a,b,c)=>S.stencilFunc(a,b,c),pa:(a,b,c,d)=>S.stencilFuncSeparate(a,b,c,d),u:a=>S.stencilMask(a),Ja:(a,b,c)=>S.stencilOp(a,b,c),oa:(a,b,c,d)=>S.stencilOpSeparate(a,b,c,d),ac:(a,b,c,d,e,h,g,l,m)=>{if(2<=V.version){if(S.ed){S.texImage2D(a,b,c,d,e,h,
g,l,m);return}if(m){var p=vc(l);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);S.texImage2D(a,b,c,d,e,h,g,l,p,m);return}}p=m?wc(l,g,d,e,m):null;S.texImage2D(a,b,c,d,e,h,g,l,p)},_b:(a,b,c,d,e,h,g,l,m,p)=>{if(S.ed)S.texImage3D(a,b,c,d,e,h,g,l,m,p);else if(p){var v=vc(m);S.texImage3D(a,b,c,d,e,h,g,l,m,v,p>>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else S.texImage3D(a,b,c,d,e,h,g,l,m,null)},ec:(a,b,c)=>S.texParameteri(a,b,c),dc:(a,b,c,d,e)=>S.texStorage2D(a,b,c,d,e),cc:(a,b,c,d,e,h)=>S.texStorage3D(a,b,c,d,e,h),
qb:(a,b,c,d,e,h,g,l,m)=>{if(2<=V.version){if(S.ed){S.texSubImage2D(a,b,c,d,e,h,g,l,m);return}if(m){var p=vc(l);S.texSubImage2D(a,b,c,d,e,h,g,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}m=m?wc(l,g,e,h,m):null;S.texSubImage2D(a,b,c,d,e,h,g,l,m)},ob:(a,b,c,d,e,h,g,l,m,p,v)=>{if(S.ed)S.texSubImage3D(a,b,c,d,e,h,g,l,m,p,v);else if(v){var P=vc(p);S.texSubImage3D(a,b,c,d,e,h,g,l,m,p,P,v>>>31-Math.clz32(P.BYTES_PER_ELEMENT))}else S.texSubImage3D(a,b,c,d,e,h,g,l,m,p,null)},Hb:(a,b,c)=>{if(2<=V.version)b&&
S.uniform1fv(W(a),y,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);S.uniform1fv(W(a),d)}},wa:(a,b)=>{S.uniform1i(W(a),b)},Db:(a,b,c)=>{if(2<=V.version)b&&S.uniform1iv(W(a),w,c>>2,b);else{if(288>=b)for(var d=xc[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);S.uniform1iv(W(a),d)}},Gb:(a,b,c)=>{if(2<=V.version)b&&S.uniform2fv(W(a),y,c>>2,2*b);else{if(144>=b)for(var d=X[2*b],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=
y.subarray(c>>2,c+8*b>>2);S.uniform2fv(W(a),d)}},Cb:(a,b,c)=>{if(2<=V.version)b&&S.uniform2iv(W(a),w,c>>2,2*b);else{if(144>=b)for(var d=xc[2*b],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);S.uniform2iv(W(a),d)}},Fb:(a,b,c)=>{if(2<=V.version)b&&S.uniform3fv(W(a),y,c>>2,3*b);else{if(96>=b)for(var d=X[3*b],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);S.uniform3fv(W(a),d)}},Bb:(a,b,c)=>{if(2<=
V.version)b&&S.uniform3iv(W(a),w,c>>2,3*b);else{if(96>=b)for(var d=xc[3*b],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);S.uniform3iv(W(a),d)}},Eb:(a,b,c)=>{if(2<=V.version)b&&S.uniform4fv(W(a),y,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=y;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=y.subarray(c>>2,c+16*b>>2);S.uniform4fv(W(a),d)}},zb:(a,b,c)=>{if(2<=V.version)b&&S.uniform4iv(W(a),
w,c>>2,4*b);else{if(72>=b)for(var d=xc[4*b],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);S.uniform4iv(W(a),d)}},yb:(a,b,c,d)=>{if(2<=V.version)b&&S.uniformMatrix4fv(W(a),!!c,y,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=y;d>>=2;for(var g=0;g<16*b;g+=16){var l=d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+
10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=y.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(W(a),!!c,e)}},i:a=>{a=N[a];S.useProgram(a);S.Jd=a},Jb:(a,b)=>{S.vertexAttribDivisor(a,b)},Kb:(a,b,c,d,e,h)=>{S.vertexAttribPointer(a,b,c,!!d,e,h)},n:(a,b,c,d)=>S.viewport(a,b,c,d),Ia:function(){f.Ad=a=>{0!=Fc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Ad)},hc:function(){f.Gd=a=>{const b=a.clipboardData.getData("text");Ha(()=>
{const c=B(b);Gc(c)})};window.addEventListener("paste",f.Gd)},Ob:function(a){f.ae=[];a=a?C(u,a):"";a=document.getElementById(a);f.Bd=b=>{b.stopPropagation();b.preventDefault()};f.Cd=b=>{b.stopPropagation();b.preventDefault()};f.Dd=b=>{b.stopPropagation();b.preventDefault()};f.Ed=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Fd=c;Hc(c.length);for(let e=0;e<c.length;e++)Ha(()=>{const h=B(c[e].name);Ic(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&
(d|=8);Jc(b.clientX,b.clientY,d)};a.addEventListener("dragenter",f.Bd,!1);a.addEventListener("dragleave",f.Cd,!1);a.addEventListener("dragover",f.Dd,!1);a.addEventListener("drop",f.Ed,!1)},db:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Lb:function(a){const b=f.Fd;return 0>a||a>=b.length?0:b[a].size},Ab:function(a,b,c,d,e){const h=new FileReader;h.onload=g=>{g=g.target.result;g.byteLength>d?Kc(a,0,1,b,0,c,d,e):(u.set(new Uint8Array(g),c),Kc(a,1,
0,b,g.byteLength,c,d,e))};h.onerror=()=>{Kc(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(f.Fd[a])},gb:function(a){a=a?C(u,a):"";f.gd=document.getElementById(a);f.gd||console.log("sokol_app.h: invalid target:"+a);f.gd.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Ga:function(){window.removeEventListener("beforeunload",f.Ad)},Yb:function(){window.removeEventListener("paste",f.Gd)},pb:function(a){a=a?C(u,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",
f.Bd);a.removeEventListener("dragleave",f.Cd);a.removeEventListener("dragover",f.Dd);a.removeEventListener("drop",f.Ed)},A:function(){f.gd&&f.gd.requestPointerLock&&f.gd.requestPointerLock()},eb:function(a,b){if(f.gd){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";
break;case 10:a="not-allowed";break;default:a="auto"}f.gd.style.cursor=a}},cb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(u.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ub:function(a){a=a?C(u,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");
b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},Za:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];Ha(()=>{const e=B(c),h=B(d);Lc(e,h)})}},$a:function(){return f.dd?
f.dd.bufferSize:0},bb:function(a,b,c){f.Zc=null;f.dd=null;"undefined"!==typeof AudioContext?f.Zc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(f.Zc=null,console.log("sokol_audio.h: no WebAudio support"));return f.Zc?(console.log("sokol_audio.h: sample rate ",f.Zc.sampleRate),f.dd=f.Zc.createScriptProcessor(c,0,b),f.dd.onaudioprocess=d=>{const e=d.outputBuffer.length,h=Mc(e);if(h){const g=d.outputBuffer.numberOfChannels;for(let l=0;l<g;l++){const m=d.outputBuffer.getChannelData(l);for(let p=
0;p<e;p++)m[p]=y[(h>>2)+(g*p+l)]}}},f.dd.connect(f.Zc.destination),a=()=>{f.Zc&&"suspended"===f.Zc.state&&f.Zc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},ab:function(){return f.Zc?f.Zc.sampleRate:0},la:function(){const a=f.Zc;null!==a&&(f.dd&&f.dd.disconnect(),a.close(),f.Zc=null,f.dd=null)},_a:function(){if(f.Zc)return"suspended"===f.Zc.state?1:0},y:function(a,b,c,d,e,h){b=b?C(u,
b):"";const g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";const l=0<d;l&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(g.readyState==XMLHttpRequest.DONE)if(206==g.status||200==g.status&&!l){const m=new Uint8Array(g.response),p=m.length;p<=h?(u.set(m,e),Nc(a,d,p)):Oc(a)}else Pc(a,g.status)};g.send()},ka:function(a,b){b=b?C(u,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==
c.status){const d=c.getResponseHeader("Content-Length");Qc(a,d)}else Pc(a,c.status)};c.send()},Aa:function(){return navigator.userAgent.includes("Macintosh")?1:0},ja:function(a,b){b=b?C(u,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Sa:function(){console.log("webapi_js_event_continued()");f.webapi_onContinued?f.webapi_onContinued():console.log("no Module.webapi_onContinued function")},Ra:function(){console.log("webapi_js_event_reboot()");
f.webapi_onReboot?f.webapi_onReboot():console.log("no Module.webapi_onReboot function")},La:function(){console.log("webapi_js_event_reset()");f.webapi_onReset?f.webapi_onReset():console.log("no Module.webapi_onReset function")},x:function(a,b){console.log("webapi_js_event_stopped()");f.webapi_onStopped?f.webapi_onStopped(a,b):console.log("no Module.webapi_onStopped function")}},Z=function(){function a(c){Z=c.exports;oa=Z.jc;sa();Ib=Z.Vc;ua.unshift(Z.kc);A--;f.monitorRunDependencies?.(A);0==A&&(null!==
ya&&(clearInterval(ya),ya=null),za&&(c=za,za=null,c()));return Z}var b={a:Rc};A++;f.monitorRunDependencies?.(A);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return n(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ca||=Ba("c64-ui.wasm")?"c64-ui.wasm":f.locateFile?f.locateFile("c64-ui.wasm",k):k+"c64-ui.wasm";Ga(b,function(c){a(c.instance)});return{}}(),M=a=>(M=Z.lc)(a),Dc=f._fs_emsc_alloc=a=>(Dc=f._fs_emsc_alloc=Z.mc)(a),Ec=f._fs_emsc_load_snapshot_callback=(a,b,c)=>
(Ec=f._fs_emsc_load_snapshot_callback=Z.nc)(a,b,c);f._webapi_dbg_connect=()=>(f._webapi_dbg_connect=Z.oc)();f._webapi_dbg_disconnect=()=>(f._webapi_dbg_disconnect=Z.pc)();f._webapi_alloc=a=>(f._webapi_alloc=Z.qc)(a);f._webapi_free=a=>(f._webapi_free=Z.rc)(a);f._webapi_boot=()=>(f._webapi_boot=Z.sc)();f._webapi_reset=()=>(f._webapi_reset=Z.tc)();f._webapi_ready=()=>(f._webapi_ready=Z.uc)();f._webapi_load=(a,b)=>(f._webapi_load=Z.vc)(a,b);f._webapi_load_snapshot=a=>(f._webapi_load_snapshot=Z.wc)(a);
f._webapi_save_snapshot=a=>(f._webapi_save_snapshot=Z.xc)(a);f._webapi_dbg_add_breakpoint=a=>(f._webapi_dbg_add_breakpoint=Z.yc)(a);f._webapi_dbg_remove_breakpoint=a=>(f._webapi_dbg_remove_breakpoint=Z.zc)(a);f._webapi_dbg_break=()=>(f._webapi_dbg_break=Z.Ac)();f._webapi_dbg_continue=()=>(f._webapi_dbg_continue=Z.Bc)();f._webapi_dbg_step_next=()=>(f._webapi_dbg_step_next=Z.Cc)();f._webapi_dbg_step_into=()=>(f._webapi_dbg_step_into=Z.Dc)();f._webapi_dbg_cpu_state=()=>(f._webapi_dbg_cpu_state=Z.Ec)();
f._webapi_dbg_request_disassembly=(a,b,c)=>(f._webapi_dbg_request_disassembly=Z.Fc)(a,b,c);f._webapi_dbg_read_memory=(a,b)=>(f._webapi_dbg_read_memory=Z.Gc)(a,b);f._webapi_input=a=>(f._webapi_input=Z.Hc)(a);
var Gc=f.__sapp_emsc_onpaste=a=>(Gc=f.__sapp_emsc_onpaste=Z.Ic)(a),Fc=f.__sapp_html5_get_ask_leave_site=()=>(Fc=f.__sapp_html5_get_ask_leave_site=Z.Jc)(),Hc=f.__sapp_emsc_begin_drop=a=>(Hc=f.__sapp_emsc_begin_drop=Z.Kc)(a),Ic=f.__sapp_emsc_drop=(a,b)=>(Ic=f.__sapp_emsc_drop=Z.Lc)(a,b),Jc=f.__sapp_emsc_end_drop=(a,b,c)=>(Jc=f.__sapp_emsc_end_drop=Z.Mc)(a,b,c),Kc=f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,g,l)=>(Kc=f.__sapp_emsc_invoke_fetch_cb=Z.Nc)(a,b,c,d,e,h,g,l),Sc=f._main=(a,b)=>(Sc=f._main=Z.Oc)(a,
b),Mc=f.__saudio_emsc_pull=a=>(Mc=f.__saudio_emsc_pull=Z.Pc)(a),Lc=f.__sargs_add_kvp=(a,b)=>(Lc=f.__sargs_add_kvp=Z.Qc)(a,b),Qc=f.__sfetch_emsc_head_response=(a,b)=>(Qc=f.__sfetch_emsc_head_response=Z.Rc)(a,b),Nc=f.__sfetch_emsc_get_response=(a,b,c)=>(Nc=f.__sfetch_emsc_get_response=Z.Sc)(a,b,c),Pc=f.__sfetch_emsc_failed_http_status=(a,b)=>(Pc=f.__sfetch_emsc_failed_http_status=Z.Tc)(a,b),Oc=f.__sfetch_emsc_failed_buffer_too_small=a=>(Oc=f.__sfetch_emsc_failed_buffer_too_small=Z.Uc)(a),Ac=a=>(Ac=
Z.Wc)(a),yc=a=>(yc=Z.Xc)(a),zc=()=>(zc=Z.Yc)(),Tc;za=function Uc(){Tc||Vc();Tc||(za=Uc)};function Wc(a=[]){var b=Sc;a.unshift(fa);var c=a.length,d=yc(4*(c+1)),e=d;a.forEach(g=>{x[e>>2]=B(g);e+=4});x[e>>2]=0;try{var h=b(c,d);eb(h)}catch(g){cb(g)}}
function Vc(){var a=ea;function b(){if(!Tc&&(Tc=!0,f.calledRun=!0,!r)){Ja(ua);Ja(va);f.onRuntimeInitialized?.();Xc&&Wc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();wa.unshift(c)}Ja(wa)}}if(!(0<A)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)xa();Ja(ta);0<A||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Xc=!0;f.noInitialRun&&(Xc=!1);Vc();
