var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),n,q=!1,na,la=a=>a.startsWith("file://"),oa,r,t,pa,qa,v,w,x,y,ra;
function sa(){var a=oa.buffer;r=new Int8Array(a);pa=new Int16Array(a);t=new Uint8Array(a);qa=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}var z=0,A=null;function ta(a){f.onAbort?.(a);a="Aborted("+a+")";k(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!n)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&n)a=new Uint8Array(n);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function xa(a){var b=ua;if(!n&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=a=>{for(;0<a.length;)a.shift()(f)},Aa=[],Ba=[],Ca=()=>{var a=f.preRun.shift();Ba.push(a)},Da=!0,Ea="undefined"!=typeof TextDecoder?new TextDecoder:void 0,B=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ea)return Ea.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,
c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Fa=0,C={},Ga=a=>{a instanceof ya||"unwind"==a||fa(1,a)},Ha=a=>{na=a;Da||0<Fa||(f.onExit?.(a),q=!0);fa(a,new ya(a))},Ia=a=>{na=a;Ha(a)},Ja=()=>{if(!(Da||0<Fa))try{var a=na;na=a;Ha(a)}catch(b){Ga(b)}},Ka=a=>{if(!q)try{a(),Ja()}catch(b){Ga(b)}},La=[],Ua=(a,b)=>{Ma=a;Na=b;if(Oa)if(Pa||=!0,0==a)D=function(){setTimeout(Qa,Math.max(0,Ra+b-performance.now())|0)};else if(1==a)D=function(){Sa(Qa)};else if(2==a){if("undefined"==
typeof Ta)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ta=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ta=setImmediate;D=function(){Ta(Qa)}}},cb=(a,b,c,d,e)=>{function g(){return h<Va?(Ja(),!1):!0}Oa=a;Wa=d;var h=Va;Pa=!1;Qa=function(){if(!q)if(0<
Xa.length){var l=Xa.shift();l.pe(l.ee);if(Ya){var m=Ya,p=0==m%1?m-1:Math.floor(m);Ya=l.ge?p:(8*m+(p+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",m=Ya??0,p=Za.le??0,m?m<p?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));g()&&setTimeout(Qa,0)}else if(g())if($a=$a+1|0,1==Ma&&1<Na&&0!=$a%Na)D();else{0==Ma&&(Ra=performance.now());a:if(!q){for(l of ab)if(!1===l())break a;Ka(a);for(m of bb)m()}g()&&D()}};e||(0<b?Ua(0,1E3/b):Ua(1,1),D());if(c)throw"unwind";
},Pa=!1,D=null,Va=0,Oa=null,Wa=0,Ma=0,Na=0,$a=0,Xa=[],ab=[],bb=[];function db(){D=null;Va++}var eb=0;function Sa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===eb)eb=b+1E3/60;else for(;b+2>=eb;)eb+=1E3/60;setTimeout(a,Math.max(eb-b,0))}}
var Za={},Ra,Qa,Ta,Ya,fb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],G=a=>{a=2<a?a?B(t,a):"":a;return fb[a]||("undefined"!=typeof document?document.querySelector(a):null)},gb=a=>0>fb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},hb=[],ib,H=a=>{var b=hb[a];b||(hb[a]=b=ib.get(a));return b};function jb(a){var b=I.jd[a];b.target.removeEventListener(b.hd,b.Ld,b.kd);I.jd.splice(a,1)}
function kb(){if(navigator.userActivation?navigator.userActivation.isActive:I.yd&&I.$d.wd){var a=I.pd;I.pd=[];for(var b of a)b.Bd(...b.Hd)}}function J(a){if(!a.target)return-4;if(a.ld)a.Ld=function(c){++I.yd;I.$d=a;kb();a.md(c);kb();--I.yd},a.target.addEventListener(a.hd,a.Ld,a.kd),I.jd.push(a);else for(var b=0;b<I.jd.length;++b)I.jd[b].target==a.target&&I.jd[b].hd==a.hd&&jb(b--);return 0}function lb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var I={fe:0,qe:0,zd:0,vd:0,Fd:0,Dd:0,xd:0,je:0,ve:0,ie:0,oe:0,Ad:0,De:0,Cd:0,se(a,b,c){r.set(r.subarray(b,b+c),a)},xe(){for(;I.jd.length;)jb(I.jd.length-1);I.pd=[]},yd:0,pd:[],he(a,b,c){function d(g,h){if(g.length!=h.length)return!1;for(var l in g)if(g[l]!=h[l])return!1;return!0}for(var e of I.pd)if(e.Bd==a&&d(e.Hd,c))return;I.pd.push({Bd:a,Qd:b,Hd:c});I.pd.sort((g,h)=>g.Qd<h.Qd)},ze(a){I.pd=I.pd.filter(b=>b.Bd!=a)},jd:[],ye:(a,b)=>{for(var c=0;c<I.jd.length;++c)I.jd[c].target!=a||b&&b!=I.jd[c].hd||
jb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},K=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;g++}}d[b]=0;return b-
e},mb=(a,b,c,d,e,g)=>{I.xd||(I.xd=L(256));a={target:G(a),hd:g,ld:d,md:(h=event)=>{var l=h.target.id?h.target.id:"",m=I.xd;K(lb(h.target),m+0,128);K(l,m+128,128);H(d)(e,m,b)&&h.preventDefault()},kd:c};return J(a)},nb=(a,b,c,d,e,g)=>{I.zd||(I.zd=L(160));a={target:G(a),hd:g,ld:d,md:h=>{var l=I.zd;y[l>>3]=h.timeStamp;var m=l>>2;v[m+2]=h.location;r[l+12]=h.ctrlKey;r[l+13]=h.shiftKey;r[l+14]=h.altKey;r[l+15]=h.metaKey;r[l+16]=h.repeat;v[m+5]=h.charCode;v[m+6]=h.keyCode;v[m+7]=h.which;K(h.key||"",l+32,32);
K(h.code||"",l+64,32);K(h.char||"",l+96,32);K(h.locale||"",l+128,32);H(d)(e,l,b)&&h.preventDefault()},kd:c};return J(a)},ob=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=gb(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},pb=(a,b,c,d,e,g)=>{I.vd||(I.vd=L(64));a=G(a);return J({target:a,
wd:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,hd:g,ld:d,md:(h=event)=>{ob(I.vd,h,a);H(d)(e,I.vd,b)&&h.preventDefault()},kd:c})},qb=(a,b,c,d)=>{I.Ad||(I.Ad=L(257));return J({target:a,hd:"pointerlockchange",ld:d,md:(e=event)=>{var g=I.Ad,h=document.pointerLockElement;r[g]=!!h;var l=h?.id||"";K(lb(h),g+1,128);K(l,g+129,128);H(d)(20,g,b)&&e.preventDefault()},kd:c})},rb=(a,b,c,d)=>J({target:a,hd:"pointerlockerror",ld:d,md:(e=event)=>{H(d)(38,0,b)&&e.preventDefault()},kd:c}),sb=(a,b,c,d)=>{I.Dd||
(I.Dd=L(36));a=G(a);return J({target:a,hd:"resize",ld:d,md:(e=event)=>{if(e.target==a){var g=document.body;if(g){var h=I.Dd;v[h>>2]=0;v[h+4>>2]=g.clientWidth;v[h+8>>2]=g.clientHeight;v[h+12>>2]=innerWidth;v[h+16>>2]=innerHeight;v[h+20>>2]=outerWidth;v[h+24>>2]=outerHeight;v[h+28>>2]=pageXOffset|0;v[h+32>>2]=pageYOffset|0;H(d)(10,h,b)&&e.preventDefault()}}},kd:c})},tb=(a,b,c,d,e,g)=>{I.Cd||(I.Cd=L(1552));a=G(a);return J({target:a,wd:"touchstart"==g||"touchend"==g,hd:g,ld:d,md:h=>{var l={},m=h.touches;
for(var p of m)p.Nd=p.Pd=0,l[p.identifier]=p;for(var u of h.changedTouches)u.Nd=1,l[u.identifier]=u;for(var E of h.targetTouches)l[E.identifier].Pd=1;m=I.Cd;y[m>>3]=h.timeStamp;r[m+12]=h.ctrlKey;r[m+13]=h.shiftKey;r[m+14]=h.altKey;r[m+15]=h.metaKey;p=m+16;u=gb(a);E=0;for(let F of Object.values(l))if(l=p>>2,v[l]=F.identifier,v[l+1]=F.screenX,v[l+2]=F.screenY,v[l+3]=F.clientX,v[l+4]=F.clientY,v[l+5]=F.pageX,v[l+6]=F.pageY,r[p+28]=F.Nd,r[p+29]=F.Pd,v[l+8]=F.clientX-(u.left|0),v[l+9]=F.clientY-(u.top|
0),p+=48,31<++E)break;v[m+8>>2]=E;H(d)(e,m,b)&&h.preventDefault()},kd:c})},M,ub=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,h)=>b.drawElementsInstancedANGLE(c,d,e,g,h))},vb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},wb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},xb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},yb=1,N=[],O=[],zb=[],Ab=[],P=[],Q=[],Bb=[],Cb=[],R=[],Db={},Eb=4,Fb=0,Gb=a=>{for(var b=yb++,c=a.length;c<b;c++)a[c]=null;return b},T=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=M[c](),h=g&&Gb(d);g?(g.name=h,d[h]=g):S||=1282;v[b+4*e>>2]=h}},Ib=(a,b)=>{a.Md||(a.Md=a.getContext,a.getContext=function(d,e){e=a.Md(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Od?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Hb(c,b):0},Hb=(a,b)=>{var c=Gb(Cb),d={handle:c,attributes:b,version:b.Od,Gd:a};a.canvas&&(a.canvas.de=d);Cb[c]=d;("undefined"==typeof b.Kd||b.Kd)&&Jb(d);return c},Jb=a=>{a||=U;if(!a.ce){a.ce=!0;var b=a.Gd;b.ue=b.getExtension("WEBGL_multi_draw");b.ne=b.getExtension("EXT_polygon_offset_clamp");b.me=b.getExtension("EXT_clip_control");b.Ee=b.getExtension("WEBGL_polygon_mode");ub(b);vb(b);wb(b);b.ke=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.re=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Jd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Jd)b.Jd=b.getExtension("EXT_disjoint_timer_query");xb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},S,U,Kb=(a,b,c,d,e,g)=>{a={target:G(a),hd:g,ld:d,md:(h=event)=>{H(d)(e,0,b)&&h.preventDefault()},kd:c};J(a)},Lb=(a,b,c,d)=>{I.Fd||(I.Fd=L(96));return J({target:a,wd:!0,hd:"wheel",ld:d,md:(e=event)=>{var g=I.Fd;ob(g,e,a);y[g+64>>3]=e.deltaX;y[g+72>>3]=e.deltaY;y[g+80>>3]=e.deltaZ;
v[g+88>>2]=e.deltaMode;H(d)(9,g,b)&&e.preventDefault()},kd:c})},Mb=["default","low-power","high-performance"],Nb={},Pb=()=>{if(!Ob){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Nb)void 0===Nb[b]?delete a[b]:a[b]=Nb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ob=c}return Ob},Ob,Qb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=
d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Rb=[null,[],[]],Sb=[],Tb=()=>{var a=xb(M);return a=a.concat(a.map(b=>"GL_"+b))},Ub=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=M.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>U.version){S||=1282;return}c=Tb().length;break;case 33307:case 33308:if(2>U.version){S||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=M.getParameter(a),typeof d){case "number":c=
d;break;case "boolean":c=d?1:0;break;case "string":S||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:S||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){S||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:S||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else S||=1281},Vb=a=>{var b=Qb(a)+1,c=L(b);c&&K(a,c,b);return c},Wb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Xb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==
a?w:qa},V=a=>{var b=M.ae;if(b){var c=b.rd[a];"number"==typeof c&&(b.rd[a]=c=M.getUniformLocation(b,b.Yd[a]+(0<c?`[${c}]`:"")));return c}S||=1282},W=[],Yb=[],X=a=>{var b=Qb(a)+1,c=Zb(b);K(a,c,b);return c},bc=a=>{var b=$b();a();ac(b)};f.requestAnimationFrame=Sa;f.pauseMainLoop=db;f.resumeMainLoop=function(){Va++;var a=Ma,b=Na,c=Oa;Oa=null;cb(c,0,!1,Wa,!0);Ua(a,b);D()};f.preMainLoop&&ab.push(f.preMainLoop);f.postMainLoop&&bb.push(f.postMainLoop);for(let a=0;32>a;++a)Sb.push(Array(a));
for(var cc=new Float32Array(288),Y=0;288>=Y;++Y)W[Y]=cc.subarray(0,Y);var dc=new Int32Array(288);for(Y=0;288>=Y;++Y)Yb[Y]=dc.subarray(0,Y);f.noExitRuntime&&(Da=f.noExitRuntime);f.print&&(ma=f.print);f.printErr&&(k=f.printErr);f.wasmBinary&&(n=f.wasmBinary);f.arguments&&(da=f.arguments);f.thisProgram&&(ea=f.thisProgram);
var ec={131645:()=>{f._webapi_input=a=>{bc(()=>f._webapi_input_internal(X(a)))};f._webapi_load_file=a=>{bc(()=>f._webapi_load_file_internal(X(a)))}}},L,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,ac,Zb,$b,wc={pa:function(){return 0},nb:function(){return 0},ob:function(){},rb:()=>ta(""),gb:()=>{Da=!1;Fa=0},hb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ka(()=>vc(a,performance.now()))},b);C[a]={id:c,Ce:b};return 0},cb:function(a){if(void 0===
window.localStorage)return 0;a=a?B(t,a):"";return(a=window.localStorage.getItem(a))?Vb(a):0},mc:function(a,b){void 0!==window.localStorage&&(a=a?B(t,a):"",b=b?B(t,b):"",window.localStorage.setItem(a,b))},Qa:(a,b,c)=>{La.length=0;for(var d;d=t[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;La.push(112==d?w[c>>2]:106==d?ra[c>>3]:105==d?v[c>>2]:y[c>>3]);c+=e?8:4}return ec[a](...La)},Oa:()=>{db();Oa=null},ia:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ka:(a,b,c)=>{a=G(a);if(!a)return-4;a=
gb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},B:()=>performance.now(),Pa:()=>performance.now(),Ta:(a,b)=>{function c(d){H(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ib:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},S:(a,b,c,d)=>
mb(a,b,c,d,12,"blur"),ha:(a,b,c)=>{a=G(a);if(!a)return-4;a.width=b;a.height=c;return 0},T:(a,b,c,d)=>mb(a,b,c,d,13,"focus"),aa:(a,b,c,d)=>nb(a,b,c,d,2,"keydown"),_:(a,b,c,d)=>nb(a,b,c,d,1,"keypress"),$:(a,b,c,d)=>nb(a,b,c,d,3,"keyup"),Ua:(a,b,c)=>{a=H(a);cb(a,b,c)},ga:(a,b,c,d)=>pb(a,b,c,d,5,"mousedown"),da:(a,b,c,d)=>pb(a,b,c,d,33,"mouseenter"),ca:(a,b,c,d)=>pb(a,b,c,d,34,"mouseleave"),ea:(a,b,c,d)=>pb(a,b,c,d,8,"mousemove"),fa:(a,b,c,d)=>pb(a,b,c,d,6,"mouseup"),V:(a,b,c,d)=>document.body?.requestPointerLock?
(a=G(a))?qb(a,b,c,d):-4:-1,U:(a,b,c,d)=>document.body?.requestPointerLock?(a=G(a))?rb(a,b,c,d):-4:-1,ja:(a,b,c,d)=>sb(a,b,c,d),W:(a,b,c,d)=>tb(a,b,c,d,25,"touchcancel"),X:(a,b,c,d)=>tb(a,b,c,d,23,"touchend"),Y:(a,b,c,d)=>tb(a,b,c,d,24,"touchmove"),Z:(a,b,c,d)=>tb(a,b,c,d,22,"touchstart"),R:(a,b,c,d)=>{Kb(a,b,c,d,31,"webglcontextlost");return 0},Q:(a,b,c,d)=>{Kb(a,b,c,d,32,"webglcontextrestored");return 0},ba:(a,b,c,d)=>(a=G(a))?"undefined"!=typeof a.onwheel?Lb(a,b,c,d):-1:-4,Sa:(a,b)=>{var c=b>>2;
b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Mb[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Od:v[c+4],te:v[c+5],Kd:r[b+24],be:r[b+25],we:v[c+7],Ae:r[b+32]};a=G(a);return!a||b.be?0:Ib(a,b)},Ra:a=>{U=Cb[a];f.ctx=M=U?.Gd;return!a||M?0:-5},pb:(a,b)=>{var c=0,d=0,e;for(e of Pb()){var g=b+c;w[a+d>>2]=g;c+=K(e,g,Infinity)+1;d+=4}return 0},qb:(a,b)=>{var c=Pb();w[a>>2]=c.length;a=0;for(var d of c)a+=Qb(d)+
1;w[b>>2]=a;return 0},oa:()=>52,mb:()=>52,jb:function(){return 70},lb:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var h=w[b>>2],l=w[b+4>>2];b+=8;for(var m=0;m<l;m++){var p=a,u=t[h+m],E=Rb[p];0===u||10===u?((1===p?ma:k)(B(E)),E.length=0):E.push(u)}e+=l}w[d>>2]=e;return 0},j:function(a,b,c){const d=a?B(t,a):"";let e;try{e=window.indexedDB.open("chips",1)}catch(g){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+g)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");e.result.createObjectStore("store")};
e.onsuccess=()=>{var g=e.result;let h;try{h=g.transaction(["store"],"readwrite")}catch(p){console.log("fs_js_load_snapshot: db.transaction failed with",p);return}g=h.objectStore("store");const l=d+"_"+b,m=g.get(l);m.onsuccess=()=>{if(void 0!==m.result){const p=m.result.length;console.log("fs_js_load_snapshot:",l,"successfully loaded",p,"bytes");const u=fc(p);t.set(m.result,u);gc(c,u,p)}else gc(c,0,0)};m.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",l)};h.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};
e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},Wa:function(a,b,c,d){const e=a?B(t,a):"";console.log("fs_js_save_snapshot: called with",e,b);let g;try{g=window.indexedDB.open("chips",1)}catch(h){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+h);return}g.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");g.result.createObjectStore("store")};g.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");const h=g.result.transaction(["store"],
"readwrite");var l=h.objectStore("store");const m=e+"_"+b;l=l.put(t.subarray(c,c+d),m);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",m,"successfully stored")};l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",m)};h.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};g.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},r:a=>M.activeTexture(a),E:(a,b)=>{M.attachShader(O[a],Q[b])},b:(a,b)=>{35051==a?M.Id=b:35052==a&&(M.qd=b);M.bindBuffer(a,
N[b])},a:(a,b,c)=>{M.bindBufferBase(a,b,N[c])},Kb:(a,b,c,d,e)=>{M.bindBufferRange(a,b,N[c],d,e)},l:(a,b)=>{M.bindFramebuffer(a,zb[b])},Vb:(a,b)=>{M.bindRenderbuffer(a,Ab[b])},q:(a,b)=>{M.bindSampler(a,R[b])},d:(a,b)=>{M.bindTexture(a,P[b])},P:a=>{M.bindVertexArray(Bb[a])},K:(a,b,c,d)=>M.blendColor(a,b,c,d),L:(a,b)=>M.blendEquationSeparate(a,b),M:(a,b,c,d)=>M.blendFuncSeparate(a,b,c,d),ub:(a,b,c,d,e,g,h,l,m,p)=>M.blitFramebuffer(a,b,c,d,e,g,h,l,m,p),Ca:(a,b,c,d)=>{2<=U.version?c&&b?M.bufferData(a,
t,d,c,b):M.bufferData(a,b,d):M.bufferData(a,c?t.subarray(c,c+b):b,d)},F:(a,b,c,d)=>{2<=U.version?c&&M.bufferSubData(a,b,t,d,c):M.bufferSubData(a,b,t.subarray(d,d+c))},Sb:a=>M.checkFramebufferStatus(a),Rb:(a,b,c,d)=>M.clearBufferfi(a,b,c,d),sa:(a,b,c)=>{M.clearBufferfv(a,b,x,c>>2)},Qb:(a,b,c)=>{M.clearBufferiv(a,b,v,c>>2)},s:(a,b,c,d)=>{M.colorMask(!!a,!!b,!!c,!!d)},Zb:a=>{M.compileShader(Q[a])},hc:(a,b,c,d,e,g,h,l,m)=>{2<=U.version?M.qd||!l?M.compressedTexSubImage2D(a,b,c,d,e,g,h,l,m):M.compressedTexSubImage2D(a,
b,c,d,e,g,h,t,m,l):M.compressedTexSubImage2D(a,b,c,d,e,g,h,t.subarray(m,m+l))},gc:(a,b,c,d,e,g,h,l,m,p,u)=>{M.qd?M.compressedTexSubImage3D(a,b,c,d,e,g,h,l,m,p,u):M.compressedTexSubImage3D(a,b,c,d,e,g,h,l,m,t,u,p)},dc:()=>{var a=Gb(O),b=M.createProgram();b.name=a;b.ud=b.sd=b.td=0;b.Ed=1;O[a]=b;return a},ac:a=>{var b=Gb(Q);Q[b]=M.createShader(a);return b},H:a=>M.cullFace(a),Ga:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=N[d];e&&(M.deleteBuffer(e),e.name=0,N[d]=null,d==M.Id&&(M.Id=0),d==M.qd&&(M.qd=
0))}},w:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=zb[d];e&&(M.deleteFramebuffer(e),e.name=0,zb[d]=null)}},p:a=>{if(a){var b=O[a];b?(M.deleteProgram(b),b.name=0,O[a]=null):S||=1281}},G:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Ab[d];e&&(M.deleteRenderbuffer(e),e.name=0,Ab[d]=null)}},f:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=R[d];e&&(M.deleteSampler(e),e.name=0,R[d]=null)}},u:a=>{if(a){var b=Q[a];b?(M.deleteShader(b),Q[a]=null):S||=1281}},m:(a,b)=>{for(var c=0;c<a;c++){var d=
v[b+4*c>>2],e=P[d];e&&(M.deleteTexture(e),e.name=0,P[d]=null)}},Ea:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];M.deleteVertexArray(Bb[d]);Bb[d]=null}},y:a=>M.depthFunc(a),x:a=>{M.depthMask(!!a)},e:a=>M.disable(a),N:a=>{M.disableVertexAttribArray(a)},wb:(a,b,c)=>{M.drawArrays(a,b,c)},xb:(a,b,c,d)=>{M.drawArraysInstanced(a,b,c,d)},ua:(a,b)=>{for(var c=Sb[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];M.drawBuffers(c)},yb:(a,b,c,d)=>{M.drawElements(a,b,c,d)},zb:(a,b,c,d,e)=>{M.drawElementsInstanced(a,b,c,d,e)},
i:a=>M.enable(a),Lb:a=>{M.enableVertexAttribArray(a)},ta:(a,b,c,d)=>{M.framebufferRenderbuffer(a,b,c,Ab[d])},n:(a,b,c,d,e)=>{M.framebufferTexture2D(a,b,c,P[d],e)},D:(a,b,c,d,e)=>{M.framebufferTextureLayer(a,b,P[c],d,e)},I:a=>M.frontFace(a),Da:(a,b)=>{T(a,b,"createBuffer",N)},O:(a,b)=>{T(a,b,"createFramebuffer",zb)},Wb:(a,b)=>{T(a,b,"createRenderbuffer",Ab)},fc:(a,b)=>{T(a,b,"createSampler",R)},kc:(a,b)=>{T(a,b,"createTexture",P)},Na:(a,b)=>{T(a,b,"createVertexArray",Bb)},Xb:(a,b)=>M.getAttribLocation(O[a],
b?B(t,b):""),c:(a,b)=>Ub(a,b),cc:(a,b,c,d)=>{a=M.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(v[c>>2]=b)},xa:(a,b,c)=>{if(c)if(a>=yb)S||=1281;else if(a=O[a],35716==b)a=M.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.ud){var d=M.getProgramParameter(a,35718);for(b=0;b<d;++b)a.ud=Math.max(a.ud,M.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.ud}else if(35722==b){if(!a.sd)for(d=M.getProgramParameter(a,35721),b=0;b<d;++b)a.sd=
Math.max(a.sd,M.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.sd}else if(35381==b){if(!a.td)for(d=M.getProgramParameter(a,35382),b=0;b<d;++b)a.td=Math.max(a.td,M.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.td}else v[c>>2]=M.getProgramParameter(a,b);else S||=1281},Yb:(a,b,c,d)=>{a=M.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(v[c>>2]=b)},va:(a,b,c)=>{c?35716==b?(a=M.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=
M.getShaderSource(Q[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=M.getShaderParameter(Q[a],b):S||=1281},La:(a,b)=>{if(2>U.version)return S||=1282,0;var c=Db[a];if(c)return 0>b||b>=c.length?(S||=1281,0):c[b];switch(a){case 7939:return c=Tb().map(Vb),c=Db[a]=c,0>b||b>=c.length?(S||=1281,0):c[b];default:return S||=1280,0}},wa:(a,b)=>{b=b?B(t,b):"";if(a=O[a]){var c=a,d=c.rd,e=c.Zd,g;if(!d){c.rd=d={};c.Yd={};var h=M.getProgramParameter(c,35718);for(g=0;g<h;++g){var l=M.getActiveUniform(c,g);var m=l.name;l=l.size;
var p=Wb(m);p=0<p?m.slice(0,p):m;var u=c.Ed;c.Ed+=l;e[p]=[l,u];for(m=0;m<l;++m)d[u]=m,c.Yd[u++]=p}}c=a.rd;d=0;e=b;g=Wb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Zd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||M.getUniformLocation(a,b)))return d}else S||=1281;return-1},sb:(a,b,c)=>{for(var d=Sb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];M.invalidateFramebuffer(a,d)},ya:a=>{a=O[a];M.linkProgram(a);a.rd=0;a.Zd={}},Ma:(a,b)=>{3317==a?Eb=b:3314==a&&(Fb=b);M.pixelStorei(a,b)},J:(a,b)=>M.polygonOffset(a,b),
vb:a=>M.readBuffer(a),Ub:(a,b,c,d,e)=>M.renderbufferStorageMultisample(a,b,c,d,e),za:(a,b,c)=>{M.samplerParameterf(R[a],b,c)},h:(a,b,c)=>{M.samplerParameteri(R[a],b,c)},t:(a,b,c,d)=>M.scissor(a,b,c,d),$b:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var h=(h=w[c+4*g>>2])?B(t,h,d?w[d+4*g>>2]:void 0):"";e+=h}M.shaderSource(Q[a],e)},Ja:(a,b,c)=>M.stencilFunc(a,b,c),ra:(a,b,c,d)=>M.stencilFuncSeparate(a,b,c,d),v:a=>M.stencilMask(a),Ia:(a,b,c)=>M.stencilOp(a,b,c),qa:(a,b,c,d)=>M.stencilOpSeparate(a,b,c,d),jc:(a,
b,c,d,e)=>M.texStorage2D(a,b,c,d,e),ic:(a,b,c,d,e,g)=>M.texStorage3D(a,b,c,d,e,g),g:(a,b,c,d,e,g,h,l,m)=>{if(2<=U.version){if(M.qd){M.texSubImage2D(a,b,c,d,e,g,h,l,m);return}if(m){var p=Xb(l);M.texSubImage2D(a,b,c,d,e,g,h,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}if(m){p=Xb(l);var u=g*((Fb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[h-6402]||1)*p.BYTES_PER_ELEMENT+Eb-1&-Eb);m=p.subarray(m>>>31-Math.clz32(p.BYTES_PER_ELEMENT),m+u>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else m=
null;M.texSubImage2D(a,b,c,d,e,g,h,l,m)},Aa:(a,b,c,d,e,g,h,l,m,p,u)=>{if(M.qd)M.texSubImage3D(a,b,c,d,e,g,h,l,m,p,u);else if(u){var E=Xb(p);M.texSubImage3D(a,b,c,d,e,g,h,l,m,p,E,u>>>31-Math.clz32(E.BYTES_PER_ELEMENT))}else M.texSubImage3D(a,b,c,d,e,g,h,l,m,p,null)},Jb:(a,b,c)=>{if(2<=U.version)b&&M.uniform1fv(V(a),x,c>>2,b);else{if(288>=b)for(var d=W[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);M.uniform1fv(V(a),d)}},bc:(a,b)=>{M.uniform1i(V(a),b)},Fb:(a,b,c)=>{if(2<=U.version)b&&
M.uniform1iv(V(a),v,c>>2,b);else{if(288>=b)for(var d=Yb[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);M.uniform1iv(V(a),d)}},Ib:(a,b,c)=>{if(2<=U.version)b&&M.uniform2fv(V(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=W[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);M.uniform2fv(V(a),d)}},Db:(a,b,c)=>{if(2<=U.version)b&&M.uniform2iv(V(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Yb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=
v.subarray(c>>2,c+8*b>>2);M.uniform2iv(V(a),d)}},Hb:(a,b,c)=>{if(2<=U.version)b&&M.uniform3fv(V(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=W[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);M.uniform3fv(V(a),d)}},Cb:(a,b,c)=>{if(2<=U.version)b&&M.uniform3iv(V(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Yb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);M.uniform3iv(V(a),
d)}},Gb:(a,b,c)=>{if(2<=U.version)b&&M.uniform4fv(V(a),x,c>>2,4*b);else{if(72>=b){var d=W[4*b],e=x;c>>=2;b*=4;for(var g=0;g<b;g+=4){var h=c+g;d[g]=e[h];d[g+1]=e[h+1];d[g+2]=e[h+2];d[g+3]=e[h+3]}}else d=x.subarray(c>>2,c+16*b>>2);M.uniform4fv(V(a),d)}},Bb:(a,b,c)=>{if(2<=U.version)b&&M.uniform4iv(V(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Yb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);M.uniform4iv(V(a),
d)}},Ab:(a,b,c,d)=>{if(2<=U.version)b&&M.uniformMatrix4fv(V(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=W[16*b],g=x;d>>=2;b*=16;for(var h=0;h<b;h+=16){var l=d+h;e[h]=g[l];e[h+1]=g[l+1];e[h+2]=g[l+2];e[h+3]=g[l+3];e[h+4]=g[l+4];e[h+5]=g[l+5];e[h+6]=g[l+6];e[h+7]=g[l+7];e[h+8]=g[l+8];e[h+9]=g[l+9];e[h+10]=g[l+10];e[h+11]=g[l+11];e[h+12]=g[l+12];e[h+13]=g[l+13];e[h+14]=g[l+14];e[h+15]=g[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);M.uniformMatrix4fv(V(a),!!c,e)}},o:a=>{a=O[a];M.useProgram(a);M.ae=a},Mb:(a,
b)=>{M.vertexAttribDivisor(a,b)},Nb:(a,b,c,d,e)=>{M.vertexAttribIPointer(a,b,c,d,e)},Ob:(a,b,c,d,e,g)=>{M.vertexAttribPointer(a,b,c,!!d,e,g)},k:(a,b,c,d)=>M.viewport(a,b,c,d),fb:Ha,lc:function(){f.Rd=a=>{0!=ic()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Rd)},_b:function(){f.Xd=a=>{const b=a.clipboardData.getData("text");bc(()=>{const c=X(b);hc(c)})};window.addEventListener("paste",f.Xd)},Eb:function(){f.Be=[];f.Sd=b=>{b.stopPropagation();b.preventDefault()};
f.Td=b=>{b.stopPropagation();b.preventDefault()};f.Ud=b=>{b.stopPropagation();b.preventDefault()};f.Vd=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Wd=c;jc(c.length);for(let e=0;e<c.length;e++)bc(()=>{const g=X(c[e].name);kc(e,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);lc(b.clientX,b.clientY,d)};const a=f.nd;a.addEventListener("dragenter",f.Sd,!1);a.addEventListener("dragleave",f.Td,!1);a.addEventListener("dragover",f.Ud,!1);a.addEventListener("drop",
f.Vd,!1)},ab:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},tb:function(a){const b=f.Wd;return 0>a||a>=b.length?0:b[a].size},kb:function(a,b,c,d,e){const g=new FileReader;g.onload=h=>{h=h.target.result;h.byteLength>d?mc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(h),c),mc(a,1,0,b,h.byteLength,c,d,e))};g.onerror=()=>{mc(a,0,2,b,0,c,d,e)};g.readAsArrayBuffer(f.Wd[a])},db:function(a,b){0!==b&&(document.title=b?B(t,b):"");a=a?B(t,a):"";void 0!==f.canvas&&("object"===
typeof f.canvas?fb[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.nd=G(a);f.nd||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.nd.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},ec:function(){window.removeEventListener("beforeunload",f.Rd)},Tb:function(){window.removeEventListener("paste",f.Xd)},eb:function(){const a=f.nd;a.removeEventListener("dragenter",f.Sd);a.removeEventListener("dragleave",
f.Td);a.removeEventListener("dragover",f.Ud);a.removeEventListener("drop",f.Vd)},C:function(){f.nd&&f.nd.requestPointerLock&&f.nd.requestPointerLock()},bb:function(a,b){if(f.nd){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;
default:a="auto"}f.nd.style.cursor=a}},$a:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,b);g.data.set(t.subarray(c,c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Pb:function(a){a=a?B(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");
b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},Va:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];bc(()=>{const e=X(c),g=X(d);pc(e,g)})}},Ya:function(){return f.od?f.od.bufferSize:0},_a:function(a,
b,c){f.gd=null;f.od=null;"undefined"!==typeof AudioContext?f.gd=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(f.gd=null,console.log("sokol_audio.h: no WebAudio support"));return f.gd?(console.log("sokol_audio.h: sample rate ",f.gd.sampleRate),f.od=f.gd.createScriptProcessor(c,0,b),f.od.onaudioprocess=d=>{const e=d.outputBuffer.length,g=oc(e);if(g){const h=d.outputBuffer.numberOfChannels;for(let l=0;l<h;l++){const m=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)m[p]=x[(g>>2)+(h*
p+l)]}}},f.od.connect(f.gd.destination),a=()=>{f.gd&&"suspended"===f.gd.state&&f.gd.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},Za:function(){return f.gd?f.gd.sampleRate:0},na:function(){const a=f.gd;null!==a&&(f.od&&f.od.disconnect(),a.close(),f.gd=null,f.od=null)},Xa:function(){if(f.gd)return"suspended"===f.gd.state?1:0},A:function(a,b,c,d,e,g){const h=b?B(t,b):"";b=new Headers;
0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(h,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>{m=new Uint8Array(m);m.length<=g?(t.set(m,e),rc(a,d,m.length)):tc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${h} failed with: `,m);uc(a)}):sc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${h} failed with: `,l);uc(a)})},ma:function(a,b){const c=b?B(t,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),
uc(a)):qc(a,Number(d))):sc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);uc(a)})},Ba:function(){return navigator.userAgent.includes("Macintosh")?1:0},la:function(a,b){b=b?B(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Ka:function(){console.log("webapi_js_event_continued()");f.webapi_onContinued?f.webapi_onContinued():console.log("no Module.webapi_onContinued function")},Ha:function(){console.log("webapi_js_event_reboot()");
f.webapi_onReboot?f.webapi_onReboot():console.log("no Module.webapi_onReboot function")},Fa:function(){console.log("webapi_js_event_reset()");f.webapi_onReset?f.webapi_onReset():console.log("no Module.webapi_onReset function")},z:function(a,b){console.log("webapi_js_event_stopped()");f.webapi_onStopped?f.webapi_onStopped(a,b):console.log("no Module.webapi_onStopped function")}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.nc;sa();ib=Z.ad;c=Z;L=c.pc;f._fs_emsc_alloc=fc=c.qc;f._fs_emsc_load_snapshot_callback=gc=c.rc;f._webapi_dbg_connect=c.sc;f._webapi_dbg_disconnect=c.tc;f._webapi_alloc=c.uc;f._webapi_free=c.vc;f._webapi_boot=c.wc;f._webapi_reset=c.xc;f._webapi_ready=c.yc;f._webapi_load=c.zc;f._webapi_load_file_internal=c.Ac;f._webapi_unload_file=c.Bc;f._webapi_load_snapshot=c.Cc;f._webapi_save_snapshot=c.Dc;f._webapi_dbg_add_breakpoint=c.Ec;f._webapi_dbg_remove_breakpoint=
c.Fc;f._webapi_dbg_break=c.Gc;f._webapi_dbg_continue=c.Hc;f._webapi_dbg_step_next=c.Ic;f._webapi_dbg_step_into=c.Jc;f._webapi_dbg_cpu_state=c.Kc;f._webapi_dbg_request_disassembly=c.Lc;f._webapi_dbg_read_memory=c.Mc;f._webapi_input_internal=c.Nc;f.__sapp_emsc_onpaste=hc=c.Oc;f.__sapp_html5_get_ask_leave_site=ic=c.Pc;f.__sapp_emsc_begin_drop=jc=c.Qc;f.__sapp_emsc_drop=kc=c.Rc;f.__sapp_emsc_end_drop=lc=c.Sc;f.__sapp_emsc_invoke_fetch_cb=mc=c.Tc;f._main=nc=c.Uc;f.__saudio_emsc_pull=oc=c.Vc;f.__sargs_add_kvp=
pc=c.Wc;f.__sfetch_emsc_head_response=qc=c.Xc;f.__sfetch_emsc_get_response=rc=c.Yc;f.__sfetch_emsc_failed_http_status=sc=c.Zc;f.__sfetch_emsc_failed_buffer_too_small=tc=c._c;f.__sfetch_emsc_failed_other=uc=c.$c;vc=c.bd;ac=c.cd;Zb=c.dd;$b=c.ed;z--;f.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;f.monitorRunDependencies?.(z);var b={a:wc};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ua??=f.locateFile?f.locateFile("c64-ui.wasm",ia):ia+"c64-ui.wasm";
return a((await xa(b)).instance)})();function xc(a=[]){var b=nc;a.unshift(ea);var c=a.length,d=Zb(4*(c+1)),e=d;a.forEach(h=>{w[e>>2]=X(h);e+=4});w[e>>2]=0;try{var g=b(c,d);Ia(g)}catch(h){Ga(h)}}
function yc(a=da){function b(){f.calledRun=!0;if(!q){Z.oc();f.onRuntimeInitialized?.();f.noInitialRun||xc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();Aa.push(c)}za(Aa)}}if(0<z)A=yc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ca();za(Ba);0<z?A=yc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();yc();
