var f;f||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),n,q=!1,na,la=a=>a.startsWith("file://"),r,t,oa,pa,v,w,x,y,qa;
function ra(){var a=sa.buffer;r=new Int8Array(a);oa=new Int16Array(a);t=new Uint8Array(a);pa=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}function ta(a){f.onAbort?.(a);a="Aborted("+a+")";k(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!n)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&n)a=new Uint8Array(n);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function xa(a){var b=ua;if(!n&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=a=>{for(;0<a.length;)a.shift()(f)},Aa=[],Ba=[],Ca=()=>{var a=f.preRun.shift();Ba.push(a)},z=0,A=null,Da=!0,Ea=globalThis.TextDecoder&&new TextDecoder,B=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ea)return Ea.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,
c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Fa=0,C={},Ga=a=>{a instanceof ya||"unwind"==a||fa(1,a)},Ha=a=>{na=a;Da||0<Fa||(f.onExit?.(a),q=!0);fa(a,new ya(a))},Ia=a=>{na=a;Ha(a)},Ja=()=>{if(!(Da||0<Fa))try{var a=na;na=a;Ha(a)}catch(b){Ga(b)}},Ka=a=>{if(!q)try{a(),Ja()}catch(b){Ga(b)}},La=[],Ta=(a,b)=>{Ma=a;Na=b;if(D)if(Oa||=!0,0==a)G=function(){setTimeout(Pa,Math.max(0,Qa+b-performance.now())|0)};else if(1==a)G=function(){Ra(Pa)};else if(2==a){if(!Sa)if(globalThis.setImmediate)Sa=
setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Sa=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}G=function(){Sa(Pa)}}},bb=(a,b,c,d,e)=>{function h(){return g<Ua?(Ja(),!1):!0}D=a;Va=d;var g=Ua;Oa=!1;Pa=function(){if(!q)if(0<Wa.length){var l=Wa.shift();l.ve(l.je);if(Xa){var m=
Xa,p=0==m%1?m-1:Math.floor(m);Xa=l.me?p:(8*m+(p+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",m=Xa??0,p=Ya.se??0,m?m<p?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));h()&&setTimeout(Pa,0)}else if(h())if(Za=Za+1|0,1==Ma&&1<Na&&0!=Za%Na)G();else{0==Ma&&(Qa=performance.now());a:if(!q){for(l of $a)if(!1===l())break a;Ka(a);for(m of ab)m()}h()&&G()}};e||(0<b?Ta(0,1E3/b):Ta(1,1),G());if(c)throw"unwind";},Oa=!1,G=null,Ua=0,D=null,Va=0,Ma=0,Na=0,Za=
0,Wa=[],$a=[],ab=[];function cb(){G=null;Ua++}var db=0;function Ra(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===db)db=b+1E3/60;else for(;b+2>=db;)db+=1E3/60;setTimeout(a,Math.max(db-b,0))}}
var Ya={},Qa,Pa,Sa,Xa,eb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],H=a=>{a=2<a?a?B(t,a):"":a;return eb[a]||("undefined"!=typeof document?document.querySelector(a):null)},fb=a=>0>eb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},gb=[],I=a=>{var b=gb[a];b||(gb[a]=b=hb.get(a));return b};function ib(a){var b=J.ld[a];b.target.removeEventListener(b.kd,b.Pd,b.md);J.ld.splice(a,1)}
function jb(){if(navigator.userActivation?navigator.userActivation.isActive:J.Cd&&J.de.zd){var a=J.rd;J.rd=[];for(var b of a)b.Fd(...b.Ld)}}function K(a){if(!a.target)return-4;if(a.nd)a.Pd=function(c){++J.Cd;J.de=a;jb();a.od(c);jb();--J.Cd},a.target.addEventListener(a.kd,a.Pd,a.md),J.ld.push(a);else for(var b=0;b<J.ld.length;++b)J.ld[b].target==a.target&&J.ld[b].kd==a.kd&&ib(b--);return 0}function kb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var J={ke:0,we:0,Dd:0,xd:0,Jd:0,Hd:0,Ad:0,qe:0,Be:0,pe:0,Bd:0,Ed:0,Je:0,Gd:0,ye(a,b,c){r.set(r.subarray(b,b+c),a)},De(){for(;J.ld.length;)ib(J.ld.length-1);J.rd=[]},Cd:0,rd:[],oe(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var l in h)if(h[l]!=g[l])return!1;return!0}for(var e of J.rd)if(e.Fd==a&&d(e.Ld,c))return;J.rd.push({Fd:a,Ud:b,Ld:c});J.rd.sort((h,g)=>h.Ud<g.Ud)},Fe(a){J.rd=J.rd.filter(b=>b.Fd!=a)},ld:[],Ee:(a,b)=>{for(var c=0;c<J.ld.length;++c)J.ld[c].target!=a||b&&b!=J.ld[c].kd||
ib(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},L=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;h++}}d[b]=0;return b-
e},lb=(a,b,c,d,e,h)=>{J.Ad||(J.Ad=M(256));a={target:H(a),kd:h,nd:d,od:(g=event)=>{var l=g.target.id?g.target.id:"",m=J.Ad;L(kb(g.target),m+0,128);L(l,m+128,128);I(d)(e,m,b)&&g.preventDefault()},md:c};return K(a)},mb=(a,b,c,d,e)=>{J.Bd||(J.Bd=M(276));return K({target:a,kd:e,nd:d,od:(h=event)=>{var g=J.Bd,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,m=!!l;r[g]=m;r[g+1]=J.fullscreenEnabled();
var p=m?l:J.he,u=p?.id||"";L(kb(p),g+2,128);L(u,g+130,128);v[g+260>>2]=p?p.clientWidth:0;v[g+264>>2]=p?p.clientHeight:0;v[g+268>>2]=screen.width;v[g+272>>2]=screen.height;m&&(J.he=l);I(d)(19,g,b)&&h.preventDefault()},md:c})},nb=(a,b,c,d,e,h)=>{J.Dd||(J.Dd=M(160));a={target:H(a),kd:h,nd:d,od:g=>{var l=J.Dd;y[l>>3]=g.timeStamp;var m=l>>2;v[m+2]=g.location;r[l+12]=g.ctrlKey;r[l+13]=g.shiftKey;r[l+14]=g.altKey;r[l+15]=g.metaKey;r[l+16]=g.repeat;v[m+5]=g.charCode;v[m+6]=g.keyCode;v[m+7]=g.which;L(g.key||
"",l+32,32);L(g.code||"",l+64,32);L(g.char||"",l+96,32);L(g.locale||"",l+128,32);I(d)(e,l,b)&&g.preventDefault()},md:c};return K(a)},ob=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=fb(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},pb=(a,b,c,d,e,h)=>{J.xd||(J.xd=M(64));a=
H(a);return K({target:a,zd:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,kd:h,nd:d,od:(g=event)=>{ob(J.xd,g,a);I(d)(e,J.xd,b)&&g.preventDefault()},md:c})},qb=(a,b,c,d)=>{J.Ed||(J.Ed=M(257));return K({target:a,kd:"pointerlockchange",nd:d,od:(e=event)=>{var h=J.Ed,g=document.pointerLockElement;r[h]=!!g;var l=g?.id||"";L(kb(g),h+1,128);L(l,h+129,128);I(d)(20,h,b)&&e.preventDefault()},md:c})},rb=(a,b,c,d)=>K({target:a,kd:"pointerlockerror",nd:d,od:(e=event)=>{I(d)(38,0,b)&&e.preventDefault()},md:c}),
sb=(a,b,c,d)=>{J.Hd||(J.Hd=M(36));a=H(a);return K({target:a,kd:"resize",nd:d,od:(e=event)=>{if(e.target==a){var h=document.body;if(h){var g=J.Hd;v[g>>2]=0;v[g+4>>2]=h.clientWidth;v[g+8>>2]=h.clientHeight;v[g+12>>2]=innerWidth;v[g+16>>2]=innerHeight;v[g+20>>2]=outerWidth;v[g+24>>2]=outerHeight;v[g+28>>2]=pageXOffset|0;v[g+32>>2]=pageYOffset|0;I(d)(10,g,b)&&e.preventDefault()}}},md:c})},tb=(a,b,c,d,e,h)=>{J.Gd||(J.Gd=M(1552));a=H(a);return K({target:a,zd:"touchstart"==h||"touchend"==h,kd:h,nd:d,od:g=>
{var l={},m=g.touches;for(var p of m)p.Qd=p.Td=0,l[p.identifier]=p;for(var u of g.changedTouches)u.Qd=1,l[u.identifier]=u;for(var E of g.targetTouches)l[E.identifier].Td=1;m=J.Gd;y[m>>3]=g.timeStamp;r[m+12]=g.ctrlKey;r[m+13]=g.shiftKey;r[m+14]=g.altKey;r[m+15]=g.metaKey;p=m+16;u=fb(a);E=0;for(let F of Object.values(l))if(l=p>>2,v[l]=F.identifier,v[l+1]=F.screenX,v[l+2]=F.screenY,v[l+3]=F.clientX,v[l+4]=F.clientY,v[l+5]=F.pageX,v[l+6]=F.pageY,r[p+28]=F.Qd,r[p+29]=F.Td,v[l+8]=F.clientX-(u.left|0),v[l+
9]=F.clientY-(u.top|0),p+=48,31<++E)break;v[m+8>>2]=E;I(d)(e,m,b)&&g.preventDefault()},md:c})},N,ub=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,d,e,h,g))},vb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},wb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},xb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},yb=1,O=[],P=[],zb=[],Ab=[],Q=[],R=[],Bb=[],Cb=[],S=[],Db={},Eb=4,Fb=0,Gb=a=>{for(var b=yb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=N[c](),g=h&&Gb(d);h?(h.name=g,d[g]=h):T||=1282;v[b+4*e>>2]=g}},Ib=(a,b)=>{a.Rd||(a.Rd=a.getContext,a.getContext=function(d,e){e=a.Rd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Sd?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Hb(c,b):0},Hb=(a,b)=>{var c=Gb(Cb),d={handle:c,attributes:b,version:b.Sd,Kd:a};a.canvas&&(a.canvas.ie=d);Cb[c]=d;("undefined"==typeof b.Od||b.Od)&&Jb(d);return c},Jb=a=>{a||=V;if(!a.ge){a.ge=!0;var b=a.Kd;b.Ae=b.getExtension("WEBGL_multi_draw");b.ue=b.getExtension("EXT_polygon_offset_clamp");b.te=b.getExtension("EXT_clip_control");b.Ke=b.getExtension("WEBGL_polygon_mode");ub(b);vb(b);wb(b);b.re=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.xe=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Nd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Nd)b.Nd=b.getExtension("EXT_disjoint_timer_query");xb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Kb=(a,b,c,d,e,h)=>{a={target:H(a),kd:h,nd:d,od:(g=event)=>{I(d)(e,0,b)&&g.preventDefault()},md:c};K(a)},Lb=(a,b,c,d)=>{J.Jd||(J.Jd=M(96));return K({target:a,zd:!0,kd:"wheel",nd:d,od:(e=event)=>{var h=J.Jd;ob(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+80>>3]=e.deltaZ;
v[h+88>>2]=e.deltaMode;I(d)(9,h,b)&&e.preventDefault()},md:c})},Mb=["default","low-power","high-performance"],Nb={},Pb=()=>{if(!Ob){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Nb)void 0===Nb[b]?delete a[b]:a[b]=Nb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ob=c}return Ob},Ob,Qb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=
d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Rb=[null,[],[]],Sb=[],Tb=()=>{var a=xb(N);return a=a.concat(a.map(b=>"GL_"+b))},Ub=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=N.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Tb().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=N.getParameter(a),typeof d){case "number":c=
d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else T||=1281},Vb=a=>{var b=Qb(a)+1,c=M(b);c&&L(a,c,b);return c},Wb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Xb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?oa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==
a?w:pa},W=a=>{var b=N.ee;if(b){var c=b.td[a];"number"==typeof c&&(b.td[a]=c=N.getUniformLocation(b,b.be[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],Yb=[],Y=a=>{var b=Qb(a)+1,c=Zb(b);L(a,c,b);return c},bc=a=>{var b=$b();a();ac(b)};f.requestAnimationFrame=Ra;f.pauseMainLoop=cb;f.resumeMainLoop=function(){Ua++;var a=Ma,b=Na,c=D;D=null;bb(c,0,!1,Va,!0);Ta(a,b);G()};f.preMainLoop&&$a.push(f.preMainLoop);f.postMainLoop&&ab.push(f.postMainLoop);for(let a=0;32>a;++a)Sb.push(Array(a));
for(var cc=new Float32Array(288),Z=0;288>=Z;++Z)X[Z]=cc.subarray(0,Z);var dc=new Int32Array(288);for(Z=0;288>=Z;++Z)Yb[Z]=dc.subarray(0,Z);f.noExitRuntime&&(Da=f.noExitRuntime);f.print&&(ma=f.print);f.printErr&&(k=f.printErr);f.wasmBinary&&(n=f.wasmBinary);f.arguments&&(da=f.arguments);f.thisProgram&&(ea=f.thisProgram);if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();
var ec={215820:()=>{f._webapi_input=a=>{bc(()=>f._webapi_input_internal(Y(a)))};f._webapi_load_file=a=>{bc(()=>f._webapi_load_file_internal(Y(a)))}}},M,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,ac,Zb,$b,sa,hb,wc={ra:function(){return 0},ob:function(){return 0},pb:function(){},sb:()=>ta(""),hb:()=>{Da=!1;Fa=0},ib:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ka(()=>vc(a,performance.now()))},b);C[a]={id:c,Ie:b};return 0},db:function(a){if(void 0===
window.localStorage)return 0;a=a?B(t,a):"";return(a=window.localStorage.getItem(a))?Vb(a):0},oc:function(a,b){void 0!==window.localStorage&&(a=a?B(t,a):"",b=b?B(t,b):"",window.localStorage.setItem(a,b))},Ra:(a,b,c)=>{La.length=0;for(var d;d=t[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;La.push(112==d?w[c>>2]:106==d?qa[c>>3]:105==d?v[c>>2]:y[c>>3]);c+=e?8:4}return ec[a](...La)},Pa:()=>{cb();D=null},ja:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,la:(a,b,c)=>{a=H(a);if(!a)return-4;a=fb(a);
y[b>>3]=a.width;y[c>>3]=a.height;return 0},y:()=>performance.now(),Qa:()=>performance.now(),Ua:(a,b)=>{function c(d){I(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},jb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-sa.buffer.byteLength+65535)/65536|0;try{sa.grow(d);ra();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},S:(a,b,c,d)=>lb(a,
b,c,d,12,"blur"),ia:(a,b,c)=>{a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},U:(a,b,c,d)=>lb(a,b,c,d,13,"focus"),R:(a,b,c,d)=>{if(!J.fullscreenEnabled())return-1;a=H(a);if(!a)return-4;mb(a,b,c,d,"webkitfullscreenchange");return mb(a,b,c,d,"fullscreenchange")},ba:(a,b,c,d)=>nb(a,b,c,d,2,"keydown"),$:(a,b,c,d)=>nb(a,b,c,d,1,"keypress"),aa:(a,b,c,d)=>nb(a,b,c,d,3,"keyup"),Va:(a,b,c)=>{a=I(a);bb(a,b,c)},ha:(a,b,c,d)=>pb(a,b,c,d,5,"mousedown"),ea:(a,b,c,d)=>pb(a,b,c,d,33,"mouseenter"),da:(a,b,c,
d)=>pb(a,b,c,d,34,"mouseleave"),fa:(a,b,c,d)=>pb(a,b,c,d,8,"mousemove"),ga:(a,b,c,d)=>pb(a,b,c,d,6,"mouseup"),W:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?qb(a,b,c,d):-4:-1,V:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?rb(a,b,c,d):-4:-1,ka:(a,b,c,d)=>sb(a,b,c,d),X:(a,b,c,d)=>tb(a,b,c,d,25,"touchcancel"),Y:(a,b,c,d)=>tb(a,b,c,d,23,"touchend"),Z:(a,b,c,d)=>tb(a,b,c,d,24,"touchmove"),_:(a,b,c,d)=>tb(a,b,c,d,22,"touchstart"),Q:(a,b,c,d)=>{Kb(a,b,c,d,31,"webglcontextlost");return 0},
P:(a,b,c,d)=>{Kb(a,b,c,d,32,"webglcontextrestored");return 0},ca:(a,b,c,d)=>(a=H(a))?"undefined"!=typeof a.onwheel?Lb(a,b,c,d):-1:-4,Ta:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Mb[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Sd:v[c+4],ze:v[c+5],Od:r[b+24],fe:r[b+25],Ce:v[c+7],Ge:r[b+32]};a=H(a);return!a||b.fe?0:Ib(a,b)},Sa:a=>{V=Cb[a];f.ctx=N=V?.Kd;return!a||N?0:-5},qb:(a,b)=>
{var c=0,d=0,e;for(e of Pb()){var h=b+c;w[a+d>>2]=h;c+=L(e,h,Infinity)+1;d+=4}return 0},rb:(a,b)=>{var c=Pb();w[a>>2]=c.length;a=0;for(var d of c)a+=Qb(d)+1;w[b>>2]=a;return 0},qa:()=>52,nb:()=>52,kb:function(){return 70},lb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var g=w[b>>2],l=w[b+4>>2];b+=8;for(var m=0;m<l;m++){var p=a,u=t[g+m],E=Rb[p];0===u||10===u?((1===p?ma:k)(B(E)),E.length=0):E.push(u)}e+=l}w[d>>2]=e;return 0},g:function(a,b,c){const d=a?B(t,a):"";let e;try{e=window.indexedDB.open("chips",1)}catch(h){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+
h)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");e.result.createObjectStore("store")};e.onsuccess=()=>{var h=e.result;let g;try{g=h.transaction(["store"],"readwrite")}catch(p){console.log("fs_js_load_snapshot: db.transaction failed with",p);return}h=g.objectStore("store");const l=d+"_"+b,m=h.get(l);m.onsuccess=()=>{if(void 0!==m.result){const p=m.result.length;console.log("fs_js_load_snapshot:",l,"successfully loaded",p,"bytes");const u=fc(p);t.set(m.result,u);gc(c,u,p)}else gc(c,
0,0)};m.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",l)};g.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},Ya:function(a,b,c,d){const e=a?B(t,a):"";console.log("fs_js_save_snapshot: called with",e,b);let h;try{h=window.indexedDB.open("chips",1)}catch(g){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+g);return}h.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");
h.result.createObjectStore("store")};h.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");const g=h.result.transaction(["store"],"readwrite");var l=g.objectStore("store");const m=e+"_"+b;l=l.put(t.subarray(c,c+d),m);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",m,"successfully stored")};l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",m)};g.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};h.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},
o:a=>N.activeTexture(a),B:(a,b)=>{N.attachShader(P[a],R[b])},a:(a,b)=>{35051==a?N.Md=b:35052==a&&(N.sd=b);N.bindBuffer(a,O[b])},u:(a,b,c)=>{N.bindBufferBase(a,b,O[c])},Lb:(a,b,c,d,e)=>{N.bindBufferRange(a,b,O[c],d,e)},i:(a,b)=>{N.bindFramebuffer(a,zb[b])},Wb:(a,b)=>{N.bindRenderbuffer(a,Ab[b])},n:(a,b)=>{N.bindSampler(a,S[b])},c:(a,b)=>{N.bindTexture(a,Q[b])},O:a=>{N.bindVertexArray(Bb[a])},J:(a,b,c,d)=>N.blendColor(a,b,c,d),K:(a,b)=>N.blendEquationSeparate(a,b),L:(a,b,c,d)=>N.blendFuncSeparate(a,
b,c,d),ub:(a,b,c,d,e,h,g,l,m,p)=>N.blitFramebuffer(a,b,c,d,e,h,g,l,m,p),mc:(a,b,c,d)=>{2<=V.version?c&&b?N.bufferData(a,t,d,c,b):N.bufferData(a,b,d):N.bufferData(a,c?t.subarray(c,c+b):b,d)},Ca:(a,b,c,d)=>{2<=V.version?c&&N.bufferSubData(a,b,t,d,c):N.bufferSubData(a,b,t.subarray(d,d+c))},Tb:a=>N.checkFramebufferStatus(a),Sb:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),ua:(a,b,c)=>{N.clearBufferfv(a,b,x,c>>2)},Rb:(a,b,c)=>{N.clearBufferiv(a,b,v,c>>2)},p:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},_b:a=>{N.compileShader(R[a])},
D:(a,b,c,d,e,h,g,l,m)=>{2<=V.version?N.sd||!l?N.compressedTexSubImage2D(a,b,c,d,e,h,g,l,m):N.compressedTexSubImage2D(a,b,c,d,e,h,g,t,m,l):N.compressedTexSubImage2D(a,b,c,d,e,h,g,t.subarray(m,m+l))},ic:(a,b,c,d,e,h,g,l,m,p,u)=>{N.sd?N.compressedTexSubImage3D(a,b,c,d,e,h,g,l,m,p,u):N.compressedTexSubImage3D(a,b,c,d,e,h,g,l,m,t,u,p)},ec:()=>{var a=Gb(P),b=N.createProgram();b.name=a;b.wd=b.ud=b.vd=0;b.Id=1;P[a]=b;return a},ac:a=>{var b=Gb(R);R[b]=N.createShader(a);return b},G:a=>N.cullFace(a),Ga:(a,b)=>
{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=O[d];e&&(N.deleteBuffer(e),e.name=0,O[d]=null,d==N.Md&&(N.Md=0),d==N.sd&&(N.sd=0))}},t:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=zb[d];e&&(N.deleteFramebuffer(e),e.name=0,zb[d]=null)}},m:a=>{if(a){var b=P[a];b?(N.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},E:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Ab[d];e&&(N.deleteRenderbuffer(e),e.name=0,Ab[d]=null)}},F:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(N.deleteSampler(e),e.name=
0,S[d]=null)}},r:a=>{if(a){var b=R[a];b?(N.deleteShader(b),R[a]=null):T||=1281}},j:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(N.deleteTexture(e),e.name=0,Q[d]=null)}},Fa:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];N.deleteVertexArray(Bb[d]);Bb[d]=null}},w:a=>N.depthFunc(a),v:a=>{N.depthMask(!!a)},d:a=>N.disable(a),M:a=>{N.disableVertexAttribArray(a)},xb:(a,b,c)=>{N.drawArrays(a,b,c)},yb:(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},wa:(a,b)=>{for(var c=Sb[a],d=0;d<a;d++)c[d]=v[b+4*
d>>2];N.drawBuffers(c)},zb:(a,b,c,d)=>{N.drawElements(a,b,c,d)},Ab:(a,b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},f:a=>N.enable(a),Mb:a=>{N.enableVertexAttribArray(a)},va:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,Ab[d])},k:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,Q[d],e)},A:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,Q[c],d,e)},H:a=>N.frontFace(a),Ea:(a,b)=>{U(a,b,"createBuffer",O)},N:(a,b)=>{U(a,b,"createFramebuffer",zb)},Xb:(a,b)=>{U(a,b,"createRenderbuffer",Ab)},gc:(a,b)=>{U(a,b,"createSampler",
S)},lc:(a,b)=>{U(a,b,"createTexture",Q)},Oa:(a,b)=>{U(a,b,"createVertexArray",Bb)},Yb:(a,b)=>N.getAttribLocation(P[a],b?B(t,b):""),b:(a,b)=>Ub(a,b),dc:(a,b,c,d)=>{a=N.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(v[c>>2]=b)},za:(a,b,c)=>{if(c)if(a>=yb)T||=1281;else if(a=P[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.wd){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.wd=Math.max(a.wd,N.getActiveUniform(a,
b).name.length+1)}v[c>>2]=a.wd}else if(35722==b){if(!a.ud)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.ud=Math.max(a.ud,N.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.ud}else if(35381==b){if(!a.vd)for(d=N.getProgramParameter(a,35382),b=0;b<d;++b)a.vd=Math.max(a.vd,N.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.vd}else v[c>>2]=N.getProgramParameter(a,b);else T||=1281},Zb:(a,b,c,d)=>{a=N.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(v[c>>2]=b)},xa:(a,b,
c)=>{c?35716==b?(a=N.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(R[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=N.getShaderParameter(R[a],b):T||=1281},La:(a,b)=>{if(2>V.version)return T||=1282,0;var c=Db[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Tb().map(Vb),c=Db[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},ya:(a,b)=>{b=b?B(t,b):"";if(a=P[a]){var c=a,d=c.td,e=c.ce,h;if(!d){c.td=d={};
c.be={};var g=N.getProgramParameter(c,35718);for(h=0;h<g;++h){var l=N.getActiveUniform(c,h);var m=l.name;l=l.size;var p=Wb(m);p=0<p?m.slice(0,p):m;var u=c.Id;c.Id+=l;e[p]=[l,u];for(m=0;m<l;++m)d[u]=m,c.be[u++]=p}}c=a.td;d=0;e=b;h=Wb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.ce[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T||=1281;return-1},tb:(a,b,c)=>{for(var d=Sb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];N.invalidateFramebuffer(a,d)},Aa:a=>{a=P[a];N.linkProgram(a);
a.td=0;a.ce={}},Na:(a,b)=>{3317==a?Eb=b:3314==a&&(Fb=b);N.pixelStorei(a,b)},I:(a,b)=>N.polygonOffset(a,b),vb:a=>N.readBuffer(a),Vb:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,b,c,d,e),Ba:(a,b,c)=>{N.samplerParameterf(S[a],b,c)},e:(a,b,c)=>{N.samplerParameteri(S[a],b,c)},q:(a,b,c,d)=>N.scissor(a,b,c,d),$b:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var g=(g=w[c+4*h>>2])?B(t,g,d?w[d+4*h>>2]:void 0):"";e+=g}N.shaderSource(R[a],e)},Ka:(a,b,c)=>N.stencilFunc(a,b,c),ta:(a,b,c,d)=>N.stencilFuncSeparate(a,
b,c,d),s:a=>N.stencilMask(a),Ja:(a,b,c)=>N.stencilOp(a,b,c),sa:(a,b,c,d)=>N.stencilOpSeparate(a,b,c,d),kc:(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),jc:(a,b,c,d,e,h)=>N.texStorage3D(a,b,c,d,e,h),C:(a,b,c,d,e,h,g,l,m)=>{if(2<=V.version){if(N.sd){N.texSubImage2D(a,b,c,d,e,h,g,l,m);return}if(m){var p=Xb(l);N.texSubImage2D(a,b,c,d,e,h,g,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}if(m){p=Xb(l);var u=h*((Fb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*p.BYTES_PER_ELEMENT+
Eb-1&-Eb);m=p.subarray(m>>>31-Math.clz32(p.BYTES_PER_ELEMENT),m+u>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else m=null;N.texSubImage2D(a,b,c,d,e,h,g,l,m)},hc:(a,b,c,d,e,h,g,l,m,p,u)=>{if(N.sd)N.texSubImage3D(a,b,c,d,e,h,g,l,m,p,u);else if(u){var E=Xb(p);N.texSubImage3D(a,b,c,d,e,h,g,l,m,p,E,u>>>31-Math.clz32(E.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,b,c,d,e,h,g,l,m,p,null)},Kb:(a,b,c)=>{if(2<=V.version)b&&N.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=
x.subarray(c>>2,c+4*b>>2);N.uniform1fv(W(a),d)}},cc:(a,b)=>{N.uniform1i(W(a),b)},Fb:(a,b,c)=>{if(2<=V.version)b&&N.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=Yb[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);N.uniform1iv(W(a),d)}},Jb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);N.uniform2fv(W(a),d)}},Eb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2iv(W(a),
v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Yb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);N.uniform2iv(W(a),d)}},Ib:(a,b,c)=>{if(2<=V.version)b&&N.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);N.uniform3fv(W(a),d)}},Db:(a,b,c)=>{if(2<=V.version)b&&N.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Yb[b],e=0;e<b;e+=3)d[e]=
v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);N.uniform3iv(W(a),d)}},Gb:(a,b,c)=>{if(2<=V.version)b&&N.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);N.uniform4fv(W(a),d)}},Cb:(a,b,c)=>{if(2<=V.version)b&&N.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Yb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+
(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);N.uniform4iv(W(a),d)}},Bb:(a,b,c,d)=>{if(2<=V.version)b&&N.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=x;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=
x.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(W(a),!!c,e)}},l:a=>{a=P[a];N.useProgram(a);N.ee=a},Nb:(a,b)=>{N.vertexAttribDivisor(a,b)},Ob:(a,b,c,d,e)=>{N.vertexAttribIPointer(a,b,c,d,e)},Pb:(a,b,c,d,e,h)=>{N.vertexAttribPointer(a,b,c,!!d,e,h)},h:(a,b,c,d)=>N.viewport(a,b,c,d),gb:Ha,nc:function(){f.Vd=a=>{0!=ic()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Vd)},bc:function(){f.ae=a=>{const b=a.clipboardData.getData("text");bc(()=>{const c=Y(b);hc(c)})};window.addEventListener("paste",
f.ae)},Hb:function(){f.He=[];f.Wd=b=>{b.stopPropagation();b.preventDefault()};f.Xd=b=>{b.stopPropagation();b.preventDefault()};f.Yd=b=>{b.stopPropagation();b.preventDefault()};f.Zd=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.$d=c;jc(c.length);for(let e=0;e<c.length;e++)bc(()=>{const h=Y(c[e].name);kc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);lc(b.clientX,b.clientY,d)};const a=f.pd;a.addEventListener("dragenter",f.Wd,!1);a.addEventListener("dragleave",
f.Xd,!1);a.addEventListener("dragover",f.Yd,!1);a.addEventListener("drop",f.Zd,!1)},bb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},cb:function(a){f.yd&&(URL.revokeObjectURL(f.yd[a].le),f.yd[a]=null)},wb:function(a){const b=f.$d;return 0>a||a>=b.length?0:b[a].size},mb:function(a,b,c,d,e){const h=new FileReader;h.onload=g=>{g=g.target.result;g.byteLength>d?mc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(g),c),mc(a,1,0,b,g.byteLength,c,d,e))};h.onerror=
()=>{mc(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(f.$d[a])},eb:function(a,b){0!==b&&(document.title=b?B(t,b):"");a=a?B(t,a):"";void 0!==f.canvas&&("object"===typeof f.canvas?eb[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.pd=H(a);f.pd||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.pd.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},fc:function(){window.removeEventListener("beforeunload",f.Vd)},
Ub:function(){window.removeEventListener("paste",f.ae)},fb:function(){const a=f.pd;a.removeEventListener("dragenter",f.Wd);a.removeEventListener("dragleave",f.Xd);a.removeEventListener("dragover",f.Yd);a.removeEventListener("drop",f.Zd)},z:function(){f.pd&&f.pd.requestPointerLock&&f.pd.requestPointerLock()},pa:function(a,b,c){if(f.pd){if(0===b)a="none";else if(0!=c)a=f.yd[a].ne;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a=
"pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.pd.style.cursor=a}},ab:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(t.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=
d.toDataURL();document.head.appendChild(a)},Qb:function(a){a=a?B(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},Wa:function(){const a=(new URLSearchParams(window.location.search)).entries();
for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];bc(()=>{const e=Y(c),h=Y(d);pc(e,h)})}},Za:function(){return f.qd?f.qd.bufferSize:0},$a:function(a,b,c){f.jd=null;f.qd=null;"undefined"!==typeof AudioContext?f.jd=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(f.jd=null,console.log("sokol_audio.h: no WebAudio support"));return f.jd?(console.log("sokol_audio.h: sample rate ",f.jd.sampleRate),f.qd=f.jd.createScriptProcessor(c,0,b),f.qd.onaudioprocess=d=>{const e=d.outputBuffer.length,
h=oc(e);if(h){const g=d.outputBuffer.numberOfChannels;for(let l=0;l<g;l++){const m=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)m[p]=x[(h>>2)+(g*p+l)]}}},f.qd.connect(f.jd.destination),a=()=>{f.jd&&"suspended"===f.jd.state&&f.jd.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},_a:function(){return f.jd?f.jd.sampleRate:0},oa:function(){const a=f.jd;null!==a&&(f.qd&&f.qd.disconnect(),
a.close(),f.jd=null,f.qd=null)},Xa:function(){if(f.jd)return"suspended"===f.jd.state?1:0},x:function(a,b,c,d,e,h){const g=b?B(t,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(g,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>{m=new Uint8Array(m);m.length<=h?(t.set(m,e),rc(a,d,m.length)):tc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${g} failed with: `,m);uc(a)}):sc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${g} failed with: `,l);uc(a)})},
na:function(a,b){const c=b?B(t,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),uc(a)):qc(a,Number(d))):sc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);uc(a)})},Da:function(){return navigator.userAgent.includes("Macintosh")?1:0},ma:function(a,b){b=b?B(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);
break;default:console.info(b)}},Ma:function(){console.log("webapi_js_event_continued()");f.webapi_onContinued?f.webapi_onContinued():console.log("no Module.webapi_onContinued function")},Ia:function(){console.log("webapi_js_event_reboot()");f.webapi_onReboot?f.webapi_onReboot():console.log("no Module.webapi_onReboot function")},Ha:function(){console.log("webapi_js_event_reset()");f.webapi_onReset?f.webapi_onReset():console.log("no Module.webapi_onReset function")},T:function(a,b){console.log("webapi_js_event_stopped()");
f.webapi_onStopped?f.webapi_onStopped(a,b):console.log("no Module.webapi_onStopped function")}};function xc(a=[]){var b=nc;a.unshift(ea);var c=a.length,d=Zb(4*(c+1)),e=d;a.forEach(g=>{w[e>>2]=Y(g);e+=4});w[e>>2]=0;try{var h=b(c,d);Ia(h)}catch(g){Ga(g)}}
function yc(a=da){function b(){f.calledRun=!0;if(!q){zc.qc();f.onRuntimeInitialized?.();f.noInitialRun||xc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();Aa.push(c)}za(Aa)}}if(0<z)A=yc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ca();za(Ba);0<z?A=yc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}var zc;
(async function(){function a(c){c=zc=c.exports;M=c.rc;fc=f._fs_emsc_alloc=c.sc;gc=f._fs_emsc_load_snapshot_callback=c.tc;f._webapi_dbg_connect=c.uc;f._webapi_dbg_disconnect=c.vc;f._webapi_alloc=c.wc;f._webapi_free=c.xc;f._webapi_boot=c.yc;f._webapi_reset=c.zc;f._webapi_ready=c.Ac;f._webapi_load=c.Bc;f._webapi_load_file_internal=c.Cc;f._webapi_unload_file=c.Dc;f._webapi_load_snapshot=c.Ec;f._webapi_save_snapshot=c.Fc;f._webapi_dbg_add_breakpoint=c.Gc;f._webapi_dbg_remove_breakpoint=c.Hc;f._webapi_dbg_break=
c.Ic;f._webapi_dbg_continue=c.Jc;f._webapi_dbg_step_next=c.Kc;f._webapi_dbg_step_into=c.Lc;f._webapi_dbg_cpu_state=c.Mc;f._webapi_dbg_request_disassembly=c.Nc;f._webapi_dbg_read_memory=c.Oc;f._webapi_input_internal=c.Pc;hc=f.__sapp_emsc_onpaste=c.Qc;ic=f.__sapp_html5_get_ask_leave_site=c.Rc;jc=f.__sapp_emsc_begin_drop=c.Sc;kc=f.__sapp_emsc_drop=c.Tc;lc=f.__sapp_emsc_end_drop=c.Uc;mc=f.__sapp_emsc_invoke_fetch_cb=c.Vc;f.__sapp_emsc_set_fullscreen_flag=c.Wc;nc=f._main=c.Xc;oc=f.__saudio_emsc_pull=c.Yc;
pc=f.__sargs_add_kvp=c.Zc;qc=f.__sfetch_emsc_head_response=c._c;rc=f.__sfetch_emsc_get_response=c.$c;sc=f.__sfetch_emsc_failed_http_status=c.ad;tc=f.__sfetch_emsc_failed_buffer_too_small=c.bd;uc=f.__sfetch_emsc_failed_other=c.cd;vc=c.ed;ac=c.fd;Zb=c.gd;$b=c.hd;sa=c.pc;hb=c.dd;ra();z--;f.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return zc}z++;f.monitorRunDependencies?.(z);var b={a:wc};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ua??=f.locateFile?
f.locateFile("cpc-ui.wasm",ia):ia+"cpc-ui.wasm";return a((await xa(b)).instance)})();yc();
