var e;e||(e=typeof Module !== 'undefined' ? Module : {});var g={},h;for(h in e)e.hasOwnProperty(h)&&(g[h]=e[h]);var r=[],aa="./this.program";function t(a,b){throw b;}var u=!1,w=!1,ba=!1,ca=!1,da=!1;u="object"===typeof window;w="function"===typeof importScripts;ba=(ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!u&&!w;da=!u&&!ba&&!w;var x="",ea,y,fa,ha;
if(ba)x=__dirname+"/",ea=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,b?null:"utf8")},y=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),r=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;}),process.on("unhandledRejection",ja),t=function(a){process.exit(a)},
e.inspect=function(){return"[Emscripten Module object]"};else if(da)"undefined"!=typeof read&&(ea=function(a){return read(a)}),y=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?r=scriptArgs:"undefined"!=typeof arguments&&(r=arguments),"function"===typeof quit&&(t=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=
console.error="undefined"!==typeof printErr?printErr:print);else if(u||w)w?x=self.location.href:document.currentScript&&(x=document.currentScript.src),x=0!==x.indexOf("blob:")?x.substr(0,x.lastIndexOf("/")+1):"",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},w&&(y=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var ka=e.print||console.log.bind(console),z=e.printErr||console.warn.bind(console);for(h in g)g.hasOwnProperty(h)&&(e[h]=g[h]);g=null;e.arguments&&(r=e.arguments);e.thisProgram&&(aa=e.thisProgram);e.quit&&(t=e.quit);var A;e.wasmBinary&&(A=e.wasmBinary);var B;e.noExitRuntime&&(B=e.noExitRuntime);"object"!==typeof WebAssembly&&z("no native wasm support detected");var C,la=new WebAssembly.Table({initial:30,maximum:30,element:"anyfunc"}),ma=!1;function assert(a,b){a||ja("Assertion failed: "+b)}
function na(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function oa(a,b,c,d){var f={string:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=D(c);E(a,F,b,c)}return b},array:function(a){var b=D(a.length);pa.set(a,b);return b}},l=na(a),k=[];a=0;if(d)for(var m=0;m<d.length;m++){var p=f[c[m]];p?(0===a&&(a=qa()),k[m]=p(d[m])):k[m]=d[m]}c=l.apply(null,k);c=function(a){return"string"===b?G(a):"boolean"===b?!!a:a}(c);0!==a&&ra(a);return c}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function G(a,b){if(a){var c=F,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&sa)a=sa.decode(c.subarray(a,b));else{for(d="";a<b;){var f=c[a++];if(f&128){var l=c[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|l);else{var k=c[a++]&63;f=224==(f&240)?(f&15)<<12|l<<6|k:(f&7)<<18|l<<12|k<<6|c[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}a=d}}else a="";return a}
function E(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var l=0;l<a.length;++l){var k=a.charCodeAt(l);if(55296<=k&&57343>=k){var m=a.charCodeAt(++l);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ua(a){var b=ta(a)+1,c=D(b);E(a,pa,c,b);return c}var buffer,pa,F,va,wa,H,xa,ya,I;
function za(a){buffer=a;e.HEAP8=pa=new Int8Array(a);e.HEAP16=va=new Int16Array(a);e.HEAP32=H=new Int32Array(a);e.HEAPU8=F=new Uint8Array(a);e.HEAPU16=wa=new Uint16Array(a);e.HEAPU32=xa=new Uint32Array(a);e.HEAPF32=ya=new Float32Array(a);e.HEAPF64=I=new Float64Array(a)}var Aa=e.TOTAL_MEMORY||33554432;e.wasmMemory?C=e.wasmMemory:C=new WebAssembly.Memory({initial:Aa/65536});C&&(buffer=C.buffer);Aa=buffer.byteLength;za(buffer);H[1697500]=12033040;
function Ba(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Ub;"number"===typeof c?void 0===b.Nb?e.dynCall_v(c):e.dynCall_vi(c,b.Nb):c(void 0===b.Nb?null:b.Nb)}}}var Ca=[],Da=[],Ea=[],Fa=[],Ga=[];function Ha(){var a=e.preRun.shift();Ca.unshift(a)}var J=0,Ia=null,K=null;e.preloadedImages={};e.preloadedAudios={};function ja(a){if(e.onAbort)e.onAbort(a);ka(a);z(a);ma=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function Ja(){var a=L;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var L="cpc.wasm";if(!Ja()){var Ka=L;L=e.locateFile?e.locateFile(Ka,x):x+Ka}function Ma(){try{if(A)return new Uint8Array(A);if(y)return y(L);throw"both async and sync fetching of the wasm failed";}catch(a){ja(a)}}
function Na(){return A||!u&&!w||"function"!==typeof fetch?new Promise(function(a){a(Ma())}):fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ma()})}Da.push({Ub:function(){Oa()}});var Pa=0,Qa=0,M=0,Ra=0,Sa=0,Ta=null,Ua=null,Va=!1;function Wa(){for(var a=N.length-1;0<=a;--a)Xa(a);N=[];Ya=[]}var Ya=[];
function Za(){if($a&&ab.Lb)for(var a=0;a<Ya.length;++a){var b=Ya[a];Ya.splice(a,1);--a;b.ec.apply(this,b.Zb)}}var $a=0,ab=null,N=[];function Xa(a){var b=N[a];b.target.removeEventListener(b.Eb,b.Sb,b.Fb);N.splice(a,1)}function O(a){function b(b){++$a;ab=a;Za();a.Hb(b);Za();--$a}if(a.Gb)a.Sb=b,a.target.addEventListener(a.Eb,b,a.Fb),N.push(a),Va||(Fa.push(Wa),Va=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Eb==a.Eb&&Xa(c--)}function bb(a){return a===a+0?G(a):a}
var cb=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function P(a){return cb[a]||("undefined"!==typeof document?document.querySelector(bb(a)):void 0)}
function db(a,b,c,d,f,l){Pa||(Pa=Q(164));a={target:P(a),Lb:!0,Eb:l,Gb:d,Hb:function(a){a=a||event;var c=Pa;E(a.key?a.key:"",F,c+0,32);E(a.code?a.code:"",F,c+32,32);H[c+64>>2]=a.location;H[c+68>>2]=a.ctrlKey;H[c+72>>2]=a.shiftKey;H[c+76>>2]=a.altKey;H[c+80>>2]=a.metaKey;H[c+84>>2]=a.repeat;E(a.locale?a.locale:"",F,c+88,32);E(a.char?a.char:"",F,c+120,32);H[c+152>>2]=a.charCode;H[c+156>>2]=a.keyCode;H[c+160>>2]=a.which;R(d,f,c,b)&&a.preventDefault()},Fb:c};O(a)}
function eb(a,b,c){H[a>>2]=b.screenX;H[a+4>>2]=b.screenY;H[a+8>>2]=b.clientX;H[a+12>>2]=b.clientY;H[a+16>>2]=b.ctrlKey;H[a+20>>2]=b.shiftKey;H[a+24>>2]=b.altKey;H[a+28>>2]=b.metaKey;va[a+32>>1]=b.button;va[a+34>>1]=b.buttons;var d=b.movementY||b.screenY-Ua;H[a+36>>2]=b.movementX||b.screenX-Ta;H[a+40>>2]=d;c=0>cb.indexOf(c)?c.getBoundingClientRect():{left:0,top:0};H[a+44>>2]=b.clientX-c.left;H[a+48>>2]=b.clientY-c.top;"wheel"!==b.type&&"mousewheel"!==b.type&&(Ta=b.screenX,Ua=b.screenY)}
function S(a,b,c,d,f,l){Qa||(Qa=Q(64));a=P(a);O({target:a,Lb:"mousemove"!=l&&"mouseenter"!=l&&"mouseleave"!=l,Eb:l,Gb:d,Hb:function(c){c=c||event;eb(Qa,c,a);R(d,f,Qa,b)&&c.preventDefault()},Fb:c})}
function fb(a,b,c,d){Ra||(Ra=Q(36));a=P(a);O({target:a,Eb:"resize",Gb:d,Hb:function(c){c=c||event;if(c.target==a){var f=Ra,k=document.body;H[f>>2]=c.detail;H[f+4>>2]=k.clientWidth;H[f+8>>2]=k.clientHeight;H[f+12>>2]=innerWidth;H[f+16>>2]=innerHeight;H[f+20>>2]=outerWidth;H[f+24>>2]=outerHeight;H[f+28>>2]=pageXOffset;H[f+32>>2]=pageYOffset;R(d,10,f,b)&&c.preventDefault()}},Fb:c})}
function gb(a,b,c,d,f,l){Sa||(Sa=Q(1684));a=P(a);O({target:a,Lb:"touchstart"==l||"touchend"==l,Eb:l,Gb:d,Hb:function(c){c=c||event;for(var l={},k=0;k<c.touches.length;++k){var n=c.touches[k];n.Pb=!1;l[n.identifier]=n}for(k=0;k<c.changedTouches.length;++k)n=c.changedTouches[k],l[n.identifier]=n,n.Pb=!0;for(k=0;k<c.targetTouches.length;++k)n=c.targetTouches[k],l[n.identifier].Xb=!0;var q=n=Sa;H[q+4>>2]=c.ctrlKey;H[q+8>>2]=c.shiftKey;H[q+12>>2]=c.altKey;H[q+16>>2]=c.metaKey;q+=20;var La=a.getBoundingClientRect(),
ib=0;for(k in l){var v=l[k];H[q>>2]=v.identifier;H[q+4>>2]=v.screenX;H[q+8>>2]=v.screenY;H[q+12>>2]=v.clientX;H[q+16>>2]=v.clientY;H[q+20>>2]=v.pageX;H[q+24>>2]=v.pageY;H[q+28>>2]=v.Pb;H[q+32>>2]=v.Xb;H[q+36>>2]=v.clientX-La.left;H[q+40>>2]=v.clientY-La.top;q+=52;if(32<=++ib)break}H[n>>2]=ib;R(d,f,n,b)&&c.preventDefault()},Fb:c})}function hb(a,b,c,d,f,l){a={target:P(a),Eb:l,Gb:d,Hb:function(a){a=a||event;R(d,f,0,b)&&a.preventDefault()},Fb:c};O(a)}
function jb(a,b,c,d,f){function l(c){c=c||event;eb(M,c,a);I[M+64>>3]=c.wheelDeltaX||0;I[M+72>>3]=-(c.wheelDeltaY||c.wheelDelta);I[M+80>>3]=0;H[M+88>>2]=0;R(d,9,M,b)&&c.preventDefault()}function k(c){c=c||event;var f=M;eb(f,c,a);I[f+64>>3]=c.deltaX;I[f+72>>3]=c.deltaY;I[f+80>>3]=c.deltaZ;H[f+88>>2]=c.deltaMode;R(d,9,f,b)&&c.preventDefault()}M||(M=Q(96));O({target:a,Lb:!0,Eb:f,Gb:d,Hb:"wheel"==f?k:l,Fb:c})}
function kb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(a,d){b.vertexAttribDivisorANGLE(a,d)},a.drawArraysInstanced=function(a,d,f,l){b.drawArraysInstancedANGLE(a,d,f,l)},a.drawElementsInstanced=function(a,d,f,l,k){b.drawElementsInstancedANGLE(a,d,f,l,k)})}
function lb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(a){b.deleteVertexArrayOES(a)},a.bindVertexArray=function(a){b.bindVertexArrayOES(a)},a.isVertexArray=function(a){return b.isVertexArrayOES(a)})}function mb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(a,d){b.drawBuffersWEBGL(a,d)})}var nb=1,ob=0,pb=[],T=[],qb=[],U=[],V=[],W=[],X=[],rb={},sb=null,tb={},ub={};
function Y(a){ob||(ob=a)}function vb(a){for(var b=nb++,c=a.length;c<b;c++)a[c]=null;return b}
function wb(a){a||(a=sb);if(!a.Vb){a.Vb=!0;var b=a.Mb;2>a.version&&(kb(b),lb(b),mb(b));b.ac=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(a){-1!=c.indexOf(a)&&b.getExtension(a)})}}var xb,yb,zb=["default","low-power","high-performance"];function Ab(a,b,c,d){for(var f=0;f<a;f++){var l=Z[c](),k=l&&vb(d);l?(l.name=k,d[k]=l):Y(1282);H[b+4*f>>2]=k}}
function Bb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Y(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)H[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){Y(1280);z("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:Y(1280);z("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}H[b>>2]=c}else Y(1281)}function Cb(a){var b=ta(a)+1,c=Q(b);E(a,F,c,b);return c}
function Db(a,b,c,d,f){a-=5120;a=1==a?F:4==a?H:6==a?ya:5==a||28922==a?xa:wa;var l=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(f>>l,f+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<l)+4-1&-4)>>l)}for(var Z,Eb=0;256>Eb;Eb++);for(Eb=0;256>Eb;Eb++);
var Jb={Za:function(){console.log("fs.h: registering Module['ccall']");e.ccall=oa},_a:function(a){var b=G(a),c=new XMLHttpRequest;c.open("GET",b);c.responseType="arraybuffer";c.onload=function(){var a=new Uint8Array(c.response);oa("emsc_load_data","int",["string","array","number"],[b,a,a.length])};c.send()},N:function(){return devicePixelRatio||1},W:function(a,b,c){a=P(a);if(!a)return-4;a=a.getBoundingClientRect();I[b>>3]=a.width;I[c>>3]=a.height;return 0},Sa:function(a,b,c){F.set(F.subarray(b,b+
c),a)},Ba:function(a,b){function c(d){Fb(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ta:function(a){var b=pa.length;if(2147418112<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{C.grow(Math.min(2147418112,d)-buffer.byteLength+65535>>16);za(C.buffer);var f=1;break a}catch(l){}f=void 0}if(f)return!0}return!1},L:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},La:function(a,
b,c,d){db(a,b,c,d,2,"keydown");return 0},Ja:function(a,b,c,d){db(a,b,c,d,1,"keypress");return 0},Ka:function(a,b,c,d){db(a,b,c,d,3,"keyup");return 0},Ra:function(a,b,c,d){S(a,b,c,d,5,"mousedown");return 0},Oa:function(a,b,c,d){S(a,b,c,d,33,"mouseenter");return 0},Na:function(a,b,c,d){S(a,b,c,d,34,"mouseleave");return 0},Pa:function(a,b,c,d){S(a,b,c,d,8,"mousemove");return 0},Qa:function(a,b,c,d){S(a,b,c,d,6,"mouseup");return 0},va:function(a,b,c,d){fb(a,b,c,d);return 0},Ea:function(a,b,c,d){gb(a,
b,c,d,25,"touchcancel");return 0},Fa:function(a,b,c,d){gb(a,b,c,d,23,"touchend");return 0},Ga:function(a,b,c,d){gb(a,b,c,d,24,"touchmove");return 0},Ha:function(a,b,c,d){gb(a,b,c,d,22,"touchstart");return 0},Da:function(a,b,c,d){hb(a,b,c,d,31,"webglcontextlost");return 0},Ca:function(a,b,c,d){hb(a,b,c,d,32,"webglcontextrestored");return 0},Ma:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(jb(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(jb(a,b,c,d,"mousewheel"),0):-1},C:function(a,
b){var c={};b>>=2;c.alpha=!!H[b];c.depth=!!H[b+1];c.stencil=!!H[b+2];c.antialias=!!H[b+3];c.premultipliedAlpha=!!H[b+4];c.preserveDrawingBuffer=!!H[b+5];c.powerPreference=zb[H[b+6]];c.failIfMajorPerformanceCaveat=!!H[b+7];c.Wb=H[b+8];c.bc=H[b+9];c.Qb=H[b+10];c.Tb=H[b+11];c.cc=H[b+12];c.dc=H[b+13];a=P(a);if(!a||c.Tb)c=0;else if(a=a.getContext("webgl",c)){b=Q(8);var d={handle:b,attributes:c,version:c.Wb,Mb:a};a.canvas&&(a.canvas.Yb=d);rb[b]=d;("undefined"===typeof c.Qb||c.Qb)&&wb(d);c=b}else c=0;return c},
Ya:function(a,b){a=rb[a];b=G(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b?kb(Z):"OES_vertex_array_object"==b?lb(Z):"WEBGL_draw_buffers"==b&&mb(Z);return!!a.Mb.getExtension(b)},ka:function(a){a>>=2;for(var b=0;14>b;++b)H[a+b]=0;H[a]=H[a+1]=H[a+3]=H[a+4]=H[a+8]=H[a+10]=1},ba:function(a){sb=rb[a];e.$b=Z=sb&&sb.Mb;return!a||Z?0:-5},g:function(a){Z.activeTexture(a)},O:function(a,b){Z.attachShader(T[a],X[b])},d:function(a,b){Z.bindBuffer(a,pb[b])},f:function(a,b){Z.bindFramebuffer(a,
qb[b])},wa:function(a,b){Z.bindRenderbuffer(a,U[b])},a:function(a,b){Z.bindTexture(a,V[b])},F:function(a,b,c,d){Z.blendColor(a,b,c,d)},G:function(a,b){Z.blendEquationSeparate(a,b)},H:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},S:function(a,b,c,d){Z.bufferData(a,c?F.subarray(c,c+b):b,d)},R:function(a,b,c,d){Z.bufferSubData(a,b,F.subarray(d,d+c))},m:function(a){return Z.checkFramebufferStatus(a)},ja:function(a){Z.clear(a)},na:function(a,b,c,d){Z.clearColor(a,b,c,d)},ma:function(a){Z.clearDepth(a)},
la:function(a){Z.clearStencil(a)},x:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},Wa:function(a){Z.compileShader(X[a])},Q:function(a,b,c,d,f,l,k,m){Z.compressedTexImage2D(a,b,c,d,f,l,m?F.subarray(m,m+k):null)},sa:function(){var a=vb(T),b=Z.createProgram();b.name=a;T[a]=b;return a},Y:function(a){var b=vb(X);X[b]=Z.createShader(a);return b},E:function(a){Z.cullFace(a)},ya:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],f=pb[d];f&&(Z.deleteBuffer(f),f.name=0,pb[d]=null,d==xb&&(xb=0),d==yb&&(yb=
0))}},j:function(a,b){for(var c=0;c<a;++c){var d=H[b+4*c>>2],f=qb[d];f&&(Z.deleteFramebuffer(f),f.name=0,qb[d]=null)}},U:function(a){if(a){var b=T[a];b?(Z.deleteProgram(b),b.name=0,T[a]=null,tb[a]=null):Y(1281)}},s:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],f=U[d];f&&(Z.deleteRenderbuffer(f),f.name=0,U[d]=null)}},y:function(a){if(a){var b=X[a];b?(Z.deleteShader(b),X[a]=null):Y(1281)}},V:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],f=V[d];f&&(Z.deleteTexture(f),f.name=0,V[d]=null)}},
v:function(a){Z.depthFunc(a)},w:function(a){Z.depthMask(!!a)},c:function(a){Z.disable(a)},z:function(a){Z.disableVertexAttribArray(a)},ea:function(a,b,c){Z.drawArrays(a,b,c)},fa:function(a,b,c,d){Z.drawElements(a,b,c,d)},e:function(a){Z.enable(a)},ga:function(a){Z.enableVertexAttribArray(a)},k:function(a,b,c,d){Z.framebufferRenderbuffer(a,b,c,U[d])},b:function(a,b,c,d,f){Z.framebufferTexture2D(a,b,c,V[d],f)},D:function(a){Z.frontFace(a)},T:function(a,b){Ab(a,b,"createBuffer",pb)},n:function(a,b){Ab(a,
b,"createFramebuffer",qb)},xa:function(a,b){Ab(a,b,"createRenderbuffer",U)},ta:function(a,b){Ab(a,b,"createTexture",V)},pa:function(a,b){return Z.getAttribLocation(T[a],G(b))},i:function(a,b){Bb(a,b)},qa:function(a,b,c,d){a=Z.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,F,d,b):0;c&&(H[c>>2]=b)},M:function(a,b,c){if(c)if(a>=nb)Y(1281);else{var d=tb[a];if(d)if(35716==b)a=Z.getProgramInfoLog(T[a]),null===a&&(a="(unknown error)"),H[c>>2]=a.length+1;else if(35719==b)H[c>>2]=d.Ob;
else if(35722==b){if(-1==d.Jb){a=T[a];var f=Z.getProgramParameter(a,35721);for(b=d.Jb=0;b<f;++b)d.Jb=Math.max(d.Jb,Z.getActiveAttrib(a,b).name.length+1)}H[c>>2]=d.Jb}else if(35381==b){if(-1==d.Kb)for(a=T[a],f=Z.getProgramParameter(a,35382),b=d.Kb=0;b<f;++b)d.Kb=Math.max(d.Kb,Z.getActiveUniformBlockName(a,b).length+1);H[c>>2]=d.Kb}else H[c>>2]=Z.getProgramParameter(T[a],b);else Y(1282)}else Y(1281)},Va:function(a,b,c,d){a=Z.getShaderInfoLog(X[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,F,d,b):
0;c&&(H[c>>2]=b)},X:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(X[a]),null===a&&(a="(unknown error)"),H[c>>2]=a.length+1):35720==b?(a=Z.getShaderSource(X[a]),H[c>>2]=null===a||0==a.length?0:a.length+1):H[c>>2]=Z.getShaderParameter(X[a],b):Y(1281)},za:function(a){if(ub[a])return ub[a];switch(a){case 7939:var b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(a){return"GL_"+a}));b=Cb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||Y(1280);b=Cb(b);break;
case 7938:b=Cb("OpenGL ES 2.0 ("+Z.getParameter(7938)+")");break;case 35724:b=Z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Cb(b);break;default:return Y(1280),0}return ub[a]=b},l:function(a,b){b=G(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=tb[a]&&tb[a].Rb[b])&&0<=c&&c<a[0]?a[1]+c:-1},ra:function(a){Z.linkProgram(T[a]);
var b=T[a];a=tb[a]={Rb:{},Ob:0,Jb:-1,Kb:-1};for(var c=a.Rb,d=Z.getProgramParameter(b,35718),f=0;f<d;++f){var l=Z.getActiveUniform(b,f),k=l.name;a.Ob=Math.max(a.Ob,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,k.lastIndexOf("[")));var m=Z.getUniformLocation(b,k);if(m){var p=vb(W);c[k]=[l.size,p];W[p]=m;for(var n=1;n<l.size;++n)m=Z.getUniformLocation(b,k+"["+n+"]"),p=vb(W),W[p]=m}}},B:function(a,b){Z.polygonOffset(a,b)},ua:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},oa:function(a,b,c,d){Z.scissor(a,
b,c,d)},Xa:function(a,b,c,d){for(var f="",l=0;l<b;++l){var k=d?H[d+4*l>>2]:-1;f+=G(H[c+4*l>>2],0>k?void 0:k)}Z.shaderSource(X[a],f)},da:function(a,b,c){Z.stencilFunc(a,b,c)},J:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},u:function(a){Z.stencilMask(a)},ca:function(a,b,c){Z.stencilOp(a,b,c)},I:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},P:function(a,b,c,d,f,l,k,m,p){Z.texImage2D(a,b,c,d,f,l,k,m,p?Db(m,k,d,f,p):null)},h:function(a,b,c){Z.texParameteri(a,b,c)},r:function(a,b,c,d,f,l,k,m,p){var n=
null;p&&(n=Db(m,k,f,l,p));Z.texSubImage2D(a,b,c,d,f,l,k,m,n)},A:function(a,b){Z.uniform1i(W[a],b)},ia:function(a){Z.useProgram(T[a])},Ua:function(a,b){Z.vertexAttribDivisor(a,b)},ha:function(a,b,c,d,f,l){Z.vertexAttribPointer(a,b,c,!!d,f,l)},K:function(a,b,c,d){Z.viewport(a,b,c,d)},memory:C,q:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Gb()});document.body.append(a)},p:function(){document.getElementById("_sokol_app_input_element").focus()},
Aa:function(){window.addEventListener("beforeunload",function(a){0!=Hb()&&(a.preventDefault(),a.returnValue=" ")})},Ia:function(){window.addEventListener("paste",function(a){a=a.clipboardData.getData("text");oa("_sapp_emsc_onpaste","void",["string"],[a])})},o:function(){document.getElementById("_sokol_app_input_element").blur()},Z:function(){for(var a=(new URLSearchParams(window.location.search)).entries(),b=a.next();!b.done;b=a.next())oa("_sargs_add_kvp","void",["string","string"],[b.value[0],b.value[1]])},
_:function(){return e.Ib?e.Ib.bufferSize:0},aa:function(a,b,c){e.Db=null;e.Ib=null;"undefined"!==typeof AudioContext?(e.Db=new AudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created AudioContext")):"undefined"!==typeof webkitAudioContext?(e.Db=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created webkitAudioContext")):(e.Db=null,console.log("sokol_audio.h: no WebAudio support"));return e.Db?(console.log("sokol_audio.h: sample rate ",
e.Db.sampleRate),e.Ib=e.Db.createScriptProcessor(c,0,b),e.Ib.onaudioprocess=function(a){var b=a.outputBuffer.length,c=Ib(b);if(c)for(var d=a.outputBuffer.numberOfChannels,m=0;m<d;m++)for(var p=a.outputBuffer.getChannelData(m),n=0;n<b;n++)p[n]=ya[(c>>2)+(d*n+m)]},e.Ib.connect(e.Db.destination),a=function(){e.Db&&"suspended"===e.Db.state&&e.Db.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),
1):0},$:function(){return e.Db?e.Db.sampleRate:0},t:function(){return performance.now()},table:la},Kb=function(){function a(a){e.asm=a.exports;J--;e.monitorRunDependencies&&e.monitorRunDependencies(J);0==J&&(null!==Ia&&(clearInterval(Ia),Ia=null),K&&(a=K,K=null,a()))}function b(b){a(b.instance)}function c(a){return Na().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){z("failed to asynchronously prepare wasm: "+a);ja(a)})}var d={env:Jb,wasi_snapshot_preview1:Jb};J++;e.monitorRunDependencies&&
e.monitorRunDependencies(J);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return z("Module.instantiateWasm callback failed with error: "+f),!1}(function(){if(A||"function"!==typeof WebAssembly.instantiateStreaming||Ja()||"function"!==typeof fetch)return c(b);fetch(L,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){z("wasm streaming compile failed: "+a);z("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();
e.asm=Kb;var Oa=e.___wasm_call_ctors=function(){return(Oa=e.___wasm_call_ctors=e.asm.$a).apply(null,arguments)};e._emsc_load_data=function(){return(e._emsc_load_data=e.asm.ab).apply(null,arguments)};e.___em_js__emsc_fs_init=function(){return(e.___em_js__emsc_fs_init=e.asm.bb).apply(null,arguments)};e.___em_js__emsc_load_file=function(){return(e.___em_js__emsc_load_file=e.asm.cb).apply(null,arguments)};
var Gb=e.__sapp_emsc_notify_keyboard_hidden=function(){return(Gb=e.__sapp_emsc_notify_keyboard_hidden=e.asm.db).apply(null,arguments)};e.___em_js__sapp_js_create_textfield=function(){return(e.___em_js__sapp_js_create_textfield=e.asm.eb).apply(null,arguments)};e.___em_js__sapp_js_focus_textfield=function(){return(e.___em_js__sapp_js_focus_textfield=e.asm.fb).apply(null,arguments)};e.___em_js__sapp_js_unfocus_textfield=function(){return(e.___em_js__sapp_js_unfocus_textfield=e.asm.gb).apply(null,arguments)};
e.__sapp_emsc_onpaste=function(){return(e.__sapp_emsc_onpaste=e.asm.hb).apply(null,arguments)};var Hb=e.__sapp_html5_get_ask_leave_site=function(){return(Hb=e.__sapp_html5_get_ask_leave_site=e.asm.ib).apply(null,arguments)};e.___em_js__sapp_js_hook_beforeunload=function(){return(e.___em_js__sapp_js_hook_beforeunload=e.asm.jb).apply(null,arguments)};e.___em_js__sapp_js_init_clipboard=function(){return(e.___em_js__sapp_js_init_clipboard=e.asm.kb).apply(null,arguments)};
e.___em_js__sapp_js_write_clipboard=function(){return(e.___em_js__sapp_js_write_clipboard=e.asm.lb).apply(null,arguments)};e._main=function(){return(e._main=e.asm.mb).apply(null,arguments)};var Q=e._malloc=function(){return(Q=e._malloc=e.asm.nb).apply(null,arguments)};e._free=function(){return(e._free=e.asm.ob).apply(null,arguments)};e.___em_js__stm_js_perfnow=function(){return(e.___em_js__stm_js_perfnow=e.asm.pb).apply(null,arguments)};
var Ib=e.__saudio_emsc_pull=function(){return(Ib=e.__saudio_emsc_pull=e.asm.qb).apply(null,arguments)};e.___em_js__saudio_js_init=function(){return(e.___em_js__saudio_js_init=e.asm.rb).apply(null,arguments)};e.___em_js__saudio_js_sample_rate=function(){return(e.___em_js__saudio_js_sample_rate=e.asm.sb).apply(null,arguments)};e.___em_js__saudio_js_buffer_frames=function(){return(e.___em_js__saudio_js_buffer_frames=e.asm.tb).apply(null,arguments)};
e.__sargs_add_kvp=function(){return(e.__sargs_add_kvp=e.asm.ub).apply(null,arguments)};e.___em_js__sargs_js_parse_url=function(){return(e.___em_js__sargs_js_parse_url=e.asm.vb).apply(null,arguments)};
var qa=e.stackSave=function(){return(qa=e.stackSave=e.asm.wb).apply(null,arguments)},D=e.stackAlloc=function(){return(D=e.stackAlloc=e.asm.xb).apply(null,arguments)},ra=e.stackRestore=function(){return(ra=e.stackRestore=e.asm.yb).apply(null,arguments)},R=e.dynCall_iiii=function(){return(R=e.dynCall_iiii=e.asm.zb).apply(null,arguments)};e.dynCall_vi=function(){return(e.dynCall_vi=e.asm.Ab).apply(null,arguments)};e.dynCall_v=function(){return(e.dynCall_v=e.asm.Bb).apply(null,arguments)};
var Fb=e.dynCall_idi=function(){return(Fb=e.dynCall_idi=e.asm.Cb).apply(null,arguments)};e.asm=Kb;var Lb;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}K=function Mb(){Lb||Nb();Lb||(K=Mb)};
function Nb(a){function b(){if(!Lb&&(Lb=!0,!ma)){Ba(Da);Ba(Ea);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Ob){var b=a,d=e._main;b=b||[];var f=b.length+1,l=D(4*(f+1));H[l>>2]=ua(aa);for(var k=1;k<f;k++)H[(l>>2)+k]=ua(b[k-1]);H[(l>>2)+f]=0;try{var m=d(f,l);if(!B||0!==m){if(!B&&(ma=!0,e.onExit))e.onExit(m);t(m,new ia(m))}}catch(p){p instanceof ia||("unwind"==p?B=!0:((b=p)&&"object"===typeof p&&p.stack&&(b=[p,p.stack]),z("exception thrown: "+b),t(1,p)))}finally{}}if(e.postRun)for("function"==
typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)b=e.postRun.shift(),Ga.unshift(b);Ba(Ga)}}a=a||r;if(!(0<J)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ha();Ba(Ca);0<J||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=Nb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Ob=!0;e.noInitialRun&&(Ob=!1);B=!0;Nb();
