
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var h={},l;for(l in e)e.hasOwnProperty(l)&&(h[l]=e[l]);var r=[],aa="./this.program";function t(a,b){throw b;}var ba=!1,u=!1,ca=!1,da=!1;ba="object"===typeof window;u="function"===typeof importScripts;ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;da=!ba&&!ca&&!u;var v="",ea,fa,w,ha,ia;
if(ca)v=u?require("path").dirname(v)+"/":__dirname+"/",ea=function(a,b){ha||(ha=require("fs"));ia||(ia=require("path"));a=ia.normalize(a);return ha.readFileSync(a,b?null:"utf8")},w=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),r=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",function(a){if(!(a instanceof ja))throw a;}),process.on("unhandledRejection",
x),t=function(a){process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(da)"undefined"!=typeof read&&(ea=function(a){return read(a)}),w=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?r=scriptArgs:"undefined"!=typeof arguments&&(r=arguments),"function"===typeof quit&&(t=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ba||u)u?v=self.location.href:"undefined"!==typeof document&&document.currentScript&&(v=document.currentScript.src),v=0!==v.indexOf("blob:")?v.substr(0,v.lastIndexOf("/")+1):"",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(w=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
fa=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};e.print||console.log.bind(console);var z=e.printErr||console.warn.bind(console);for(l in h)h.hasOwnProperty(l)&&(e[l]=h[l]);h=null;e.arguments&&(r=e.arguments);e.thisProgram&&(aa=e.thisProgram);e.quit&&(t=e.quit);var A;e.wasmBinary&&(A=e.wasmBinary);var noExitRuntime;e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);
"object"!==typeof WebAssembly&&x("no native wasm support detected");var ka,la=!1;function assert(a,b){a||x("Assertion failed: "+b)}function ma(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function B(a,b,c,d){var f={string:function(p){var q=0;if(null!==p&&void 0!==p&&0!==p){var T=(p.length<<2)+1;q=C(T);D(p,E,q,T)}return q},array:function(p){var q=C(p.length);na.set(p,q);return q}},k=ma(a),g=[];a=0;if(d)for(var m=0;m<d.length;m++){var n=f[c[m]];n?(0===a&&(a=oa()),g[m]=n(d[m])):g[m]=d[m]}c=k.apply(null,g);c=function(p){return"string"===b?F(p):"boolean"===b?!!p:p}(c);0!==a&&pa(a);return c}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function F(a,b){if(a){var c=E,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&qa)a=qa.decode(c.subarray(a,b));else{for(d="";a<b;){var f=c[a++];if(f&128){var k=c[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|k);else{var g=c[a++]&63;f=224==(f&240)?(f&15)<<12|k<<6|g:(f&7)<<18|k<<12|g<<6|c[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}a=d}}else a="";return a}
function D(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var k=0;k<a.length;++k){var g=a.charCodeAt(k);if(55296<=g&&57343>=g){var m=a.charCodeAt(++k);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}
function ra(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function sa(a){var b=ra(a)+1,c=C(b);D(a,na,c,b);return c}var ta,na,E,ua,va,G,wa,xa,H;
function ya(){var a=ka.buffer;ta=a;e.HEAP8=na=new Int8Array(a);e.HEAP16=ua=new Int16Array(a);e.HEAP32=G=new Int32Array(a);e.HEAPU8=E=new Uint8Array(a);e.HEAPU16=va=new Uint16Array(a);e.HEAPU32=wa=new Uint32Array(a);e.HEAPF32=xa=new Float32Array(a);e.HEAPF64=H=new Float64Array(a)}var I,za=[],Aa=[],Ba=[],Ca=[],Da=[];Aa.push({xc:function(){Ea()}});function Fa(){var a=e.preRun.shift();za.unshift(a)}var J=0,Ga=null,K=null;e.preloadedImages={};e.preloadedAudios={};
function x(a){if(e.onAbort)e.onAbort(a);z(a);la=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ha(a){var b=L;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ia(){return Ha("data:application/octet-stream;base64,")}var L="cpc.wasm";if(!Ia()){var Ja=L;L=e.locateFile?e.locateFile(Ja,v):v+Ja}
function Ka(){var a=L;try{if(a==L&&A)return new Uint8Array(A);if(w)return w(a);throw"both async and sync fetching of the wasm failed";}catch(b){x(b)}}
function La(){if(!A&&(ba||u)){if("function"===typeof fetch&&!Ha("file://"))return fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ka()});if(fa)return new Promise(function(a,b){fa(L,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ka()})}
function Ma(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.xc;"number"===typeof c?void 0===b.ic?I.get(c)():I.get(c)(b.ic):c(void 0===b.ic?null:b.ic)}}}var Na=0;function Oa(){for(var a=M.length-1;0<=a;--a)Pa(a);M=[];Qa=[]}var Qa=[];function Ra(){if(Na&&Sa.fc)for(var a=0;a<Qa.length;++a){var b=Qa[a];Qa.splice(a,1);--a;b.Nc.apply(null,b.Dc)}}var M=[];function Pa(a){var b=M[a];b.target.removeEventListener(b.Yb,b.vc,b.Zb);M.splice(a,1)}
function N(a){function b(d){++Na;Sa=a;Ra();a.bc(d);Ra();--Na}if(a.ac)a.vc=b,a.target.addEventListener(a.Yb,b,a.Zb),M.push(a),Ta||(Ca.push(Oa),Ta=!0);else for(var c=0;c<M.length;++c)M[c].target==a.target&&M[c].Yb==a.Yb&&Pa(c--)}var Ta,Sa,Ua,Va,Wa,Xa,Ya,Za,$a=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function O(a){a=2<a?F(a):a;return $a[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function ab(a){return 0>$a.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function bb(a,b,c,d,f,k){Ua||(Ua=P(164));a={target:O(a),fc:!0,Yb:k,ac:d,bc:function(g){var m=Ua,n=m>>2;G[n]=g.location;G[n+1]=g.ctrlKey;G[n+2]=g.shiftKey;G[n+3]=g.altKey;G[n+4]=g.metaKey;G[n+5]=g.repeat;G[n+6]=g.charCode;G[n+7]=g.keyCode;G[n+8]=g.which;D(g.key||"",E,m+36,32);D(g.code||"",E,m+68,32);D(g.char||"",E,m+100,32);D(g.locale||"",E,m+132,32);I.get(d)(f,m,b)&&g.preventDefault()},Zb:c};N(a)}
function cb(a,b,c){a>>=2;G[a]=b.screenX;G[a+1]=b.screenY;G[a+2]=b.clientX;G[a+3]=b.clientY;G[a+4]=b.ctrlKey;G[a+5]=b.shiftKey;G[a+6]=b.altKey;G[a+7]=b.metaKey;ua[2*a+16]=b.button;ua[2*a+17]=b.buttons;G[a+9]=b.movementX;G[a+10]=b.movementY;c=ab(c);G[a+11]=b.clientX-c.left;G[a+12]=b.clientY-c.top}function Q(a,b,c,d,f,k){Va||(Va=P(64));a=O(a);N({target:a,fc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Yb:k,ac:d,bc:function(g){g=g||event;cb(Va,g,a);I.get(d)(f,Va,b)&&g.preventDefault()},Zb:c})}
function db(a,b,c,d,f){Wa||(Wa=P(260));N({target:a,Yb:f,ac:d,bc:function(k){k=k||event;var g=Wa,m=document.pointerLockElement||document.kc||document.mc||document.lc;G[g>>2]=!!m;var n=m&&m.id?m.id:"";D(m?m==window?"#window":m==screen?"#screen":m&&m.nodeName?m.nodeName:"":"",E,g+4,128);D(n,E,g+132,128);I.get(d)(20,g,b)&&k.preventDefault()},Zb:c})}function eb(a,b,c,d,f){N({target:a,Yb:f,ac:d,bc:function(k){k=k||event;I.get(d)(38,0,b)&&k.preventDefault()},Zb:c})}
function fb(a,b,c,d){Xa||(Xa=P(36));a=O(a);N({target:a,Yb:"resize",ac:d,bc:function(f){f=f||event;if(f.target==a){var k=document.body;if(k){var g=Xa;G[g>>2]=f.detail;G[g+4>>2]=k.clientWidth;G[g+8>>2]=k.clientHeight;G[g+12>>2]=innerWidth;G[g+16>>2]=innerHeight;G[g+20>>2]=outerWidth;G[g+24>>2]=outerHeight;G[g+28>>2]=pageXOffset;G[g+32>>2]=pageYOffset;I.get(d)(10,g,b)&&f.preventDefault()}}},Zb:c})}
function gb(a,b,c,d,f,k){Ya||(Ya=P(1684));a=O(a);N({target:a,fc:"touchstart"==k||"touchend"==k,Yb:k,ac:d,bc:function(g){for(var m={},n=g.touches,p=0;p<n.length;++p){var q=n[p];m[q.identifier]=q}n=g.changedTouches;for(p=0;p<n.length;++p)q=n[p],q.zc=1,m[q.identifier]=q;n=g.targetTouches;for(p=0;p<n.length;++p)m[n[p].identifier].Bc=1;n=Ya;q=n>>2;G[q+1]=g.ctrlKey;G[q+2]=g.shiftKey;G[q+3]=g.altKey;G[q+4]=g.metaKey;q+=5;var T=ab(a),kb=0;for(p in m){var y=m[p];G[q]=y.identifier;G[q+1]=y.screenX;G[q+2]=y.screenY;
G[q+3]=y.clientX;G[q+4]=y.clientY;G[q+5]=y.pageX;G[q+6]=y.pageY;G[q+7]=y.zc;G[q+8]=y.Bc;G[q+9]=y.clientX-T.left;G[q+10]=y.clientY-T.top;q+=13;if(31<++kb)break}G[n>>2]=kb;I.get(d)(f,n,b)&&g.preventDefault()},Zb:c})}function hb(a,b,c,d,f,k){a={target:O(a),Yb:k,ac:d,bc:function(g){g=g||event;I.get(d)(f,0,b)&&g.preventDefault()},Zb:c};N(a)}
function ib(a,b,c,d){Za||(Za=P(96));N({target:a,fc:!0,Yb:"wheel",ac:d,bc:function(f){f=f||event;var k=Za;cb(k,f,a);H[k+64>>3]=f.deltaX;H[k+72>>3]=f.deltaY;H[k+80>>3]=f.deltaZ;G[k+88>>2]=f.deltaMode;I.get(d)(9,k,b)&&f.preventDefault()},Zb:c})}
function jb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,k){b.drawArraysInstancedANGLE(c,d,f,k)},a.drawElementsInstanced=function(c,d,f,k,g){b.drawElementsInstancedANGLE(c,d,f,k,g)})}
function lb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function mb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function nb(a){a.Ic=a.getExtension("WEBGL_multi_draw")}
var ob=1,pb=[],R=[],qb=[],S=[],U=[],V=[],W=[],rb=[],sb={},tb={};function X(a){ub||(ub=a)}function Y(a){for(var b=ob++,c=a.length;c<b;c++)a[c]=null;return b}function vb(a){a||(a=wb);if(!a.yc){a.yc=!0;var b=a.hc;jb(b);lb(b);mb(b);b.Fc=b.getExtension("EXT_disjoint_timer_query");nb(b);(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var ub,wb,xb=["default","low-power","high-performance"];
function yb(a,b,c,d){for(var f=0;f<a;f++){var k=Z[c](),g=k&&Y(d);k?(k.name=g,d[g]=k):X(1282);G[b+4*f>>2]=g}}
function zb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":X(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:X(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)G[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){X(1280);z("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:X(1280);z("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}G[b>>2]=c}else X(1281)}function Ab(a){var b=ra(a)+1,c=P(b);D(a,E,c,b);return c}
function Bb(a,b,c,d,f){a-=5120;a=1==a?E:4==a?G:6==a?xa:5==a||28922==a?wa:va;var k=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(f>>k,f+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<k)+4-1&-4)>>k)}
var Z,Hb={gb:function(){console.log("fs.h: registering Module['ccall']");e.ccall=B},hb:function(a){var b=F(a),c=new XMLHttpRequest;c.open("GET",b);c.responseType="arraybuffer";c.onload=function(){var d=new Uint8Array(c.response);B("emsc_load_data","int",["string","array","number"],[b,d,d.length])};c.send()},I:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},T:function(a,b,c){a=O(a);if(!a)return-4;a=ab(a);H[b>>3]=a.width;H[c>>3]=a.height;return 0},Xa:function(a,b,c){E.copyWithin(a,
b,b+c)},va:function(a,b){function c(d){I.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ya:function(a){a>>>=0;var b=E.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ka.grow(Math.min(2147483648,d)-ta.byteLength+65535>>>16);ya();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},E:function(a,b,c){a=O(a);if(!a)return-4;a.width=b;a.height=c;return 0},ea:function(a,
b,c,d){bb(a,b,c,d,2,"keydown");return 0},ca:function(a,b,c,d){bb(a,b,c,d,1,"keypress");return 0},da:function(a,b,c,d){bb(a,b,c,d,3,"keyup");return 0},ka:function(a,b,c,d){Q(a,b,c,d,5,"mousedown");return 0},ha:function(a,b,c,d){Q(a,b,c,d,33,"mouseenter");return 0},ga:function(a,b,c,d){Q(a,b,c,d,34,"mouseleave");return 0},ia:function(a,b,c,d){Q(a,b,c,d,8,"mousemove");return 0},ja:function(a,b,c,d){Q(a,b,c,d,6,"mouseup");return 0},Z:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||
document.body.kc||document.body.mc||document.body.lc))return-1;a=O(a);if(!a)return-4;db(a,b,c,d,"pointerlockchange");db(a,b,c,d,"mozpointerlockchange");db(a,b,c,d,"webkitpointerlockchange");db(a,b,c,d,"mspointerlockchange");return 0},Y:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.kc||document.body.mc||document.body.lc))return-1;a=O(a);if(!a)return-4;eb(a,b,c,d,"pointerlockerror");eb(a,b,c,d,"mozpointerlockerror");eb(a,b,c,d,"webkitpointerlockerror");eb(a,b,c,d,
"mspointerlockerror");return 0},Ha:function(a,b,c,d){fb(a,b,c,d);return 0},_:function(a,b,c,d){gb(a,b,c,d,25,"touchcancel");return 0},$:function(a,b,c,d){gb(a,b,c,d,23,"touchend");return 0},aa:function(a,b,c,d){gb(a,b,c,d,24,"touchmove");return 0},ba:function(a,b,c,d){gb(a,b,c,d,22,"touchstart");return 0},X:function(a,b,c,d){hb(a,b,c,d,31,"webglcontextlost");return 0},W:function(a,b,c,d){hb(a,b,c,d,32,"webglcontextrestored");return 0},fa:function(a,b,c,d){a=O(a);return"undefined"!==typeof a.onwheel?
(ib(a,b,c,d),0):-1},ma:function(a,b){b>>=2;b={alpha:!!G[b],depth:!!G[b+1],stencil:!!G[b+2],antialias:!!G[b+3],premultipliedAlpha:!!G[b+4],preserveDrawingBuffer:!!G[b+5],powerPreference:xb[G[b+6]],failIfMajorPerformanceCaveat:!!G[b+7],Ac:G[b+8],Hc:G[b+9],nc:G[b+10],wc:G[b+11],Jc:G[b+12],Kc:G[b+13]};a=O(a);if(!a||b.wc)b=0;else if(a=a.getContext("webgl",b)){var c=Y(rb),d={Gc:c,attributes:b,version:b.Ac,hc:a};a.canvas&&(a.canvas.Cc=d);rb[c]=d;("undefined"===typeof b.nc||b.nc)&&vb(d);b=c}else b=0;return b},
Va:function(a,b){a=rb[a];b=F(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&jb(Z);"OES_vertex_array_object"==b&&lb(Z);"WEBGL_draw_buffers"==b&&mb(Z);"WEBGL_multi_draw"==b&&nb(Z);return!!a.hc.getExtension(b)},fb:function(a){a>>=2;for(var b=0;14>b;++b)G[a+b]=0;G[a]=G[a+1]=G[a+3]=G[a+4]=G[a+8]=G[a+10]=1},Wa:function(a){wb=rb[a];e.Ec=Z=wb&&wb.hc;return!a||Z?0:-5},b:function(a){Z.activeTexture(a)},F:function(a,b){Z.attachShader(R[a],W[b])},e:function(a,b){Z.bindBuffer(a,pb[b])},g:function(a,
b){Z.bindFramebuffer(a,qb[b])},Fa:function(a,b){Z.bindRenderbuffer(a,S[b])},a:function(a,b){Z.bindTexture(a,U[b])},P:function(a,b,c,d){Z.blendColor(a,b,c,d)},Q:function(a,b){Z.blendEquationSeparate(a,b)},R:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},K:function(a,b,c,d){Z.bufferData(a,c?E.subarray(c,c+b):b,d)},J:function(a,b,c,d){Z.bufferSubData(a,b,E.subarray(d,d+c))},m:function(a){return Z.checkFramebufferStatus(a)},db:function(a){Z.clear(a)},sa:function(a,b,c,d){Z.clearColor(a,b,c,d)},ra:function(a){Z.clearDepth(a)},
eb:function(a){Z.clearStencil(a)},v:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},xa:function(a){Z.compileShader(W[a])},H:function(a,b,c,d,f,k,g,m){Z.compressedTexImage2D(a,b,c,d,f,k,m?E.subarray(m,m+g):null)},Ca:function(){var a=Y(R),b=Z.createProgram();b.name=a;R[a]=b;return a},za:function(a){var b=Y(W);W[b]=Z.createShader(a);return b},M:function(a){Z.cullFace(a)},La:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],f=pb[d];f&&(Z.deleteBuffer(f),f.name=0,pb[d]=null)}},d:function(a,b){for(var c=
0;c<a;++c){var d=G[b+4*c>>2],f=qb[d];f&&(Z.deleteFramebuffer(f),f.name=0,qb[d]=null)}},U:function(a){if(a){var b=R[a];b?(Z.deleteProgram(b),b.name=0,R[a]=null,sb[a]=null):X(1281)}},V:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],f=S[d];f&&(Z.deleteRenderbuffer(f),f.name=0,S[d]=null)}},u:function(a){if(a){var b=W[a];b?(Z.deleteShader(b),W[a]=null):X(1281)}},Ka:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],f=U[d];f&&(Z.deleteTexture(f),f.name=0,U[d]=null)}},y:function(a){Z.depthFunc(a)},
x:function(a){Z.depthMask(!!a)},f:function(a){Z.disable(a)},S:function(a){Z.disableVertexAttribArray(a)},na:function(a,b,c){Z.drawArrays(a,b,c)},oa:function(a,b,c,d){Z.drawElements(a,b,c,d)},i:function(a){Z.enable(a)},bb:function(a){Z.enableVertexAttribArray(a)},k:function(a,b,c,d){Z.framebufferRenderbuffer(a,b,c,S[d])},c:function(a,b,c,d,f){Z.framebufferTexture2D(a,b,c,U[d],f)},N:function(a){Z.frontFace(a)},L:function(a,b){yb(a,b,"createBuffer",pb)},n:function(a,b){yb(a,b,"createFramebuffer",qb)},
Ga:function(a,b){yb(a,b,"createRenderbuffer",S)},Da:function(a,b){yb(a,b,"createTexture",U)},ua:function(a,b){return Z.getAttribLocation(R[a],F(b))},h:function(a,b){zb(a,b)},Aa:function(a,b,c,d){a=Z.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(G[c>>2]=b)},D:function(a,b,c){if(c)if(a>=ob)X(1281);else{var d=sb[a];if(d)if(35716==b)a=Z.getProgramInfoLog(R[a]),null===a&&(a="(unknown error)"),G[c>>2]=a.length+1;else if(35719==b)G[c>>2]=d.jc;else if(35722==b){if(-1==
d.cc){a=R[a];var f=Z.getProgramParameter(a,35721);for(b=d.cc=0;b<f;++b)d.cc=Math.max(d.cc,Z.getActiveAttrib(a,b).name.length+1)}G[c>>2]=d.cc}else if(35381==b){if(-1==d.dc)for(a=R[a],f=Z.getProgramParameter(a,35382),b=d.dc=0;b<f;++b)d.dc=Math.max(d.dc,Z.getActiveUniformBlockName(a,b).length+1);G[c>>2]=d.dc}else G[c>>2]=Z.getProgramParameter(R[a],b);else X(1282)}else X(1281)},wa:function(a,b,c,d){a=Z.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(G[c>>2]=b)},B:function(a,
b,c){c?35716==b?(a=Z.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),G[c>>2]=a?a.length+1:0):35720==b?(a=Z.getShaderSource(W[a]),G[c>>2]=a?a.length+1:0):G[c>>2]=Z.getShaderParameter(W[a],b):X(1281)},Ma:function(a){if(tb[a])return tb[a];switch(a){case 7939:var b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Ab(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||X(1280);b=Ab(b);break;case 7938:b=Ab("OpenGL ES 2.0 ("+Z.getParameter(7938)+
")");break;case 35724:b=Z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Ab(b);break;default:return X(1280),0}return tb[a]=b},o:function(a,b){b=F(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=sb[a]&&sb[a].uc[b])&&0<=c&&c<a[0]?a[1]+c:-1},Ba:function(a){Z.linkProgram(R[a]);var b=R[a];a=sb[a]={uc:{},jc:0,cc:-1,
dc:-1};for(var c=a.uc,d=Z.getProgramParameter(b,35718),f=0;f<d;++f){var k=Z.getActiveUniform(b,f),g=k.name;a.jc=Math.max(a.jc,g.length+1);"]"==g.slice(-1)&&(g=g.slice(0,g.lastIndexOf("[")));var m=Z.getUniformLocation(b,g);if(m){var n=Y(V);c[g]=[k.size,n];V[n]=m;for(var p=1;p<k.size;++p)m=Z.getUniformLocation(b,g+"["+p+"]"),n=Y(V),V[n]=m}}},O:function(a,b){Z.polygonOffset(a,b)},Ea:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},ta:function(a,b,c,d){Z.scissor(a,b,c,d)},ya:function(a,b,c,d){for(var f=
"",k=0;k<b;++k){var g=d?G[d+4*k>>2]:-1;f+=F(G[c+4*k>>2],0>g?void 0:g)}Z.shaderSource(W[a],f)},Ja:function(a,b,c){Z.stencilFunc(a,b,c)},qa:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},w:function(a){Z.stencilMask(a)},Ia:function(a,b,c){Z.stencilOp(a,b,c)},pa:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},G:function(a,b,c,d,f,k,g,m,n){Z.texImage2D(a,b,c,d,f,k,g,m,n?Bb(m,g,d,f,n):null)},j:function(a,b,c){Z.texParameteri(a,b,c)},l:function(a,b,c,d,f,k,g,m,n){var p=null;n&&(p=Bb(m,g,f,k,n));Z.texSubImage2D(a,
b,c,d,f,k,g,m,p)},C:function(a,b){Z.uniform1i(V[a],b)},p:function(a){Z.useProgram(R[a])},Za:function(a,b){Z.vertexAttribDivisor(a,b)},cb:function(a,b,c,d,f,k){Z.vertexAttribPointer(a,b,c,!!d,f,k)},t:function(a,b,c,d){Z.viewport(a,b,c,d)},Ua:function(){e.oc=function(a){0!=Cb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.oc)},Sa:function(){e.tc=function(a){a=a.clipboardData.getData("text");B("_sapp_emsc_onpaste","void",["string"],[a])};window.addEventListener("paste",
e.tc)},Ra:function(a){e.Lc=[];a=F(a);a=document.getElementById(a);e.pc=function(b){b.stopPropagation();b.preventDefault()};e.qc=function(b){b.stopPropagation();b.preventDefault()};e.rc=function(b){b.stopPropagation();b.preventDefault()};e.sc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;e.Mc=c;Db(c.length);var d;for(d=0;d<c.length;d++)B("_sapp_emsc_drop","void",["number","string"],[d,c[d].name]);Eb(b.clientX,b.clientY)};a.addEventListener("dragenter",e.pc,!1);a.addEventListener("dragleave",
e.qc,!1);a.addEventListener("dragover",e.rc,!1);a.addEventListener("drop",e.sc,!1)},s:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Fb()});document.body.append(a)},r:function(){document.getElementById("_sokol_app_input_element").focus()},Oa:function(a){a=F(a);e.ec=document.getElementById(a);e.ec||console.log("sokol_app.h: invalid target:"+a);e.ec.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+
a)},Qa:function(){window.removeEventListener("beforeunload",e.oc)},Pa:function(){window.removeEventListener("paste",e.tc)},Na:function(a){a=F(a);a=document.getElementById(a);a.removeEventListener("dragenter",e.pc);a.removeEventListener("dragleave",e.qc);a.removeEventListener("dragover",e.rc);a.removeEventListener("drop",e.sc)},z:function(){e.ec&&e.ec.requestPointerLock&&e.ec.requestPointerLock()},q:function(){document.getElementById("_sokol_app_input_element").blur()},Ta:function(){for(var a=(new URLSearchParams(window.location.search)).entries(),
b=a.next();!b.done;b=a.next())B("_sargs_add_kvp","void",["string","string"],[b.value[0],b.value[1]])},_a:function(){return e.$b?e.$b.bufferSize:0},ab:function(a,b,c){e.Xb=null;e.$b=null;"undefined"!==typeof AudioContext?e.Xb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?e.Xb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(e.Xb=null,console.log("sokol_audio.h: no WebAudio support"));return e.Xb?(console.log("sokol_audio.h: sample rate ",
e.Xb.sampleRate),e.$b=e.Xb.createScriptProcessor(c,0,b),e.$b.onaudioprocess=function(d){var f=d.outputBuffer.length,k=Gb(f);if(k)for(var g=d.outputBuffer.numberOfChannels,m=0;m<g;m++)for(var n=d.outputBuffer.getChannelData(m),p=0;p<f;p++)n[p]=xa[(k>>2)+(g*p+m)]},e.$b.connect(e.Xb.destination),a=function(){e.Xb&&"suspended"===e.Xb.state&&e.Xb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),
1):0},$a:function(){return e.Xb?e.Xb.sampleRate:0},la:function(){null!==e.Xb&&(e.$b&&e.$b.disconnect(),e.Xb.close(),e.Xb=null,e.$b=null)},A:function(){return performance.now()}};
(function(){function a(f){e.asm=f.exports;ka=e.asm.ib;ya();I=e.asm.jb;J--;e.monitorRunDependencies&&e.monitorRunDependencies(J);0==J&&(null!==Ga&&(clearInterval(Ga),Ga=null),K&&(f=K,K=null,f()))}function b(f){a(f.instance)}function c(f){return La().then(function(k){return WebAssembly.instantiate(k,d)}).then(f,function(k){z("failed to asynchronously prepare wasm: "+k);x(k)})}var d={a:Hb};J++;e.monitorRunDependencies&&e.monitorRunDependencies(J);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return z("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){return A||"function"!==typeof WebAssembly.instantiateStreaming||Ia()||Ha("file://")||"function"!==typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(k){z("wasm streaming compile failed: "+k);z("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var Ea=e.___wasm_call_ctors=function(){return(Ea=e.___wasm_call_ctors=e.asm.kb).apply(null,arguments)};
e._emsc_load_data=function(){return(e._emsc_load_data=e.asm.lb).apply(null,arguments)};e.___em_js__emsc_fs_init=function(){return(e.___em_js__emsc_fs_init=e.asm.mb).apply(null,arguments)};e.___em_js__emsc_load_file=function(){return(e.___em_js__emsc_load_file=e.asm.nb).apply(null,arguments)};var Fb=e.__sapp_emsc_notify_keyboard_hidden=function(){return(Fb=e.__sapp_emsc_notify_keyboard_hidden=e.asm.ob).apply(null,arguments)};
e.__sapp_emsc_onpaste=function(){return(e.__sapp_emsc_onpaste=e.asm.pb).apply(null,arguments)};var Cb=e.__sapp_html5_get_ask_leave_site=function(){return(Cb=e.__sapp_html5_get_ask_leave_site=e.asm.qb).apply(null,arguments)},Db=e.__sapp_emsc_begin_drop=function(){return(Db=e.__sapp_emsc_begin_drop=e.asm.rb).apply(null,arguments)};e.__sapp_emsc_drop=function(){return(e.__sapp_emsc_drop=e.asm.sb).apply(null,arguments)};
var Eb=e.__sapp_emsc_end_drop=function(){return(Eb=e.__sapp_emsc_end_drop=e.asm.tb).apply(null,arguments)};e.__sapp_emsc_invoke_fetch_cb=function(){return(e.__sapp_emsc_invoke_fetch_cb=e.asm.ub).apply(null,arguments)};e.___em_js__sapp_js_create_textfield=function(){return(e.___em_js__sapp_js_create_textfield=e.asm.vb).apply(null,arguments)};e.___em_js__sapp_js_focus_textfield=function(){return(e.___em_js__sapp_js_focus_textfield=e.asm.wb).apply(null,arguments)};
e.___em_js__sapp_js_unfocus_textfield=function(){return(e.___em_js__sapp_js_unfocus_textfield=e.asm.xb).apply(null,arguments)};e.___em_js__sapp_js_add_beforeunload_listener=function(){return(e.___em_js__sapp_js_add_beforeunload_listener=e.asm.yb).apply(null,arguments)};e.___em_js__sapp_js_remove_beforeunload_listener=function(){return(e.___em_js__sapp_js_remove_beforeunload_listener=e.asm.zb).apply(null,arguments)};
e.___em_js__sapp_js_add_clipboard_listener=function(){return(e.___em_js__sapp_js_add_clipboard_listener=e.asm.Ab).apply(null,arguments)};e.___em_js__sapp_js_remove_clipboard_listener=function(){return(e.___em_js__sapp_js_remove_clipboard_listener=e.asm.Bb).apply(null,arguments)};e.___em_js__sapp_js_write_clipboard=function(){return(e.___em_js__sapp_js_write_clipboard=e.asm.Cb).apply(null,arguments)};
e.___em_js__sapp_js_add_dragndrop_listeners=function(){return(e.___em_js__sapp_js_add_dragndrop_listeners=e.asm.Db).apply(null,arguments)};e.___em_js__sapp_js_dropped_file_size=function(){return(e.___em_js__sapp_js_dropped_file_size=e.asm.Eb).apply(null,arguments)};e.___em_js__sapp_js_fetch_dropped_file=function(){return(e.___em_js__sapp_js_fetch_dropped_file=e.asm.Fb).apply(null,arguments)};
e.___em_js__sapp_js_remove_dragndrop_listeners=function(){return(e.___em_js__sapp_js_remove_dragndrop_listeners=e.asm.Gb).apply(null,arguments)};e.___em_js__sapp_js_pointer_init=function(){return(e.___em_js__sapp_js_pointer_init=e.asm.Hb).apply(null,arguments)};e.___em_js__sapp_js_request_pointerlock=function(){return(e.___em_js__sapp_js_request_pointerlock=e.asm.Ib).apply(null,arguments)};
e.___em_js__sapp_js_exit_pointerlock=function(){return(e.___em_js__sapp_js_exit_pointerlock=e.asm.Jb).apply(null,arguments)};e._main=function(){return(e._main=e.asm.Kb).apply(null,arguments)};e.___em_js__stm_js_perfnow=function(){return(e.___em_js__stm_js_perfnow=e.asm.Lb).apply(null,arguments)};var Gb=e.__saudio_emsc_pull=function(){return(Gb=e.__saudio_emsc_pull=e.asm.Mb).apply(null,arguments)};e.___em_js__saudio_js_init=function(){return(e.___em_js__saudio_js_init=e.asm.Nb).apply(null,arguments)};
e.___em_js__saudio_js_shutdown=function(){return(e.___em_js__saudio_js_shutdown=e.asm.Ob).apply(null,arguments)};e.___em_js__saudio_js_sample_rate=function(){return(e.___em_js__saudio_js_sample_rate=e.asm.Pb).apply(null,arguments)};e.___em_js__saudio_js_buffer_frames=function(){return(e.___em_js__saudio_js_buffer_frames=e.asm.Qb).apply(null,arguments)};e.__sargs_add_kvp=function(){return(e.__sargs_add_kvp=e.asm.Rb).apply(null,arguments)};
e.___em_js__sargs_js_parse_url=function(){return(e.___em_js__sargs_js_parse_url=e.asm.Sb).apply(null,arguments)};var P=e._malloc=function(){return(P=e._malloc=e.asm.Tb).apply(null,arguments)},oa=e.stackSave=function(){return(oa=e.stackSave=e.asm.Ub).apply(null,arguments)},pa=e.stackRestore=function(){return(pa=e.stackRestore=e.asm.Vb).apply(null,arguments)},C=e.stackAlloc=function(){return(C=e.stackAlloc=e.asm.Wb).apply(null,arguments)},Ib;
function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}K=function Jb(){Ib||Kb();Ib||(K=Jb)};
function Kb(a){function b(){if(!Ib&&(Ib=!0,e.calledRun=!0,!la)){Ma(Aa);Ma(Ba);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Lb){var c=a,d=e._main;c=c||[];var f=c.length+1,k=C(4*(f+1));G[k>>2]=sa(aa);for(var g=1;g<f;g++)G[(k>>2)+g]=sa(c[g-1]);G[(k>>2)+f]=0;try{var m=d(f,k);if(!noExitRuntime||0!==m){if(!noExitRuntime){if(e.onExit)e.onExit(m);la=!0}t(m,new ja(m))}}catch(n){n instanceof ja||("unwind"==n?noExitRuntime=!0:((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),z("exception thrown: "+
c),t(1,n)))}finally{}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),Da.unshift(c);Ma(Da)}}a=a||r;if(!(0<J)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Fa();Ma(za);0<J||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=Kb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();
var Lb=!0;e.noInitialRun&&(Lb=!1);noExitRuntime=!0;Kb();
