
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign,ba=aa({},e),ca=[],da="./this.program";function k(a,b){throw b;}var ea="object"===typeof window,l="function"===typeof importScripts,fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,q="",ha,u,v,fs,ia,ja;
if(fa)q=l?require("path").dirname(q)+"/":__dirname+"/",ja=function(){fs||(fs=require("fs"),ia=require("path"))},ha=function(a,b){ja();a=ia.normalize(a);return fs.readFileSync(a,b?null:"utf8")},v=function(a){a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a},u=function(a,b,c){ja();a=ia.normalize(a);fs.readFile(a,function(d,f){d?c(d):b(f.buffer)})},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",
function(a){if(!(a instanceof w))throw a;}),process.on("unhandledRejection",function(a){throw a;}),k=function(a,b){if(noExitRuntime||0<ka)throw process.exitCode=a,b;b instanceof w||x("exiting due to exception: "+b);process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(ea||l)l?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ha=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(v=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};e.print||console.log.bind(console);var x=e.printErr||console.warn.bind(console);aa(e,ba);
ba=null;e.arguments&&(ca=e.arguments);e.thisProgram&&(da=e.thisProgram);e.quit&&(k=e.quit);var y;e.wasmBinary&&(y=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&la("no native wasm support detected");var ma,na=!1;
function oa(a,b,c){var d={string:function(n){var p=0;if(null!==n&&void 0!==n&&0!==n){var t=(n.length<<2)+1;p=z(t);A(n,B,p,t)}return p},array:function(n){var p=z(n.length);pa.set(n,p);return p}};a=e["_"+a];var f=[],h=0;if(c)for(var g=0;g<c.length;g++){var m=d[b[g]];m?(0===h&&(h=qa()),f[g]=m(c[g])):f[g]=c[g]}b=a.apply(null,f);b=function(n){0!==h&&ra(h);return n}(b)}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function C(a,b){if(a){var c=B,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&sa)a=sa.decode(c.subarray(a,b));else{for(d="";a<b;){var f=c[a++];if(f&128){var h=c[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var g=c[a++]&63;f=224==(f&240)?(f&15)<<12|h<<6|g:(f&7)<<18|h<<12|g<<6|c[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}a=d}}else a="";return a}
function A(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ua(a){var b=ta(a)+1,c=z(b);A(a,pa,c,b);return c}var va,pa,B,wa,xa,D,ya,za,E;
function Aa(){var a=ma.buffer;va=a;e.HEAP8=pa=new Int8Array(a);e.HEAP16=wa=new Int16Array(a);e.HEAP32=D=new Int32Array(a);e.HEAPU8=B=new Uint8Array(a);e.HEAPU16=xa=new Uint16Array(a);e.HEAPU32=ya=new Uint32Array(a);e.HEAPF32=za=new Float32Array(a);e.HEAPF64=E=new Float64Array(a)}var Ba,Ca=[],Da=[],Ea=[],Fa=[],Ga=[],ka=0;function Ha(){var a=e.preRun.shift();Ca.unshift(a)}var F=0,Ia=null,G=null;e.preloadedImages={};e.preloadedAudios={};
function la(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";x(a);na=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ja(){return H.startsWith("data:application/octet-stream;base64,")}var H;H="kc854.wasm";if(!Ja()){var Ka=H;H=e.locateFile?e.locateFile(Ka,q):q+Ka}function La(){var a=H;try{if(a==H&&y)return new Uint8Array(y);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){la(b)}}
function Ma(){if(!y&&(ea||l)){if("function"===typeof fetch&&!H.startsWith("file://"))return fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return La()});if(u)return new Promise(function(a,b){u(H,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return La()})}
function I(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.xc;"number"===typeof c?void 0===b.Wb?J(c)():J(c)(b.Wb):c(void 0===b.Wb?null:b.Wb)}}}var K=[];function J(a){var b=K[a];b||(a>=K.length&&(K.length=a+1),K[a]=b=Ba.get(a));return b}var Na=0;function Oa(){for(var a=L.length-1;0<=a;--a)Pa(a);L=[];M=[]}var M=[];function Qa(){if(Na&&Ra.Rb)for(var a=0;a<M.length;++a){var b=M[a];M.splice(a,1);--a;b.Ec.apply(null,b.uc)}}var L=[];
function Pa(a){var b=L[a];b.target.removeEventListener(b.Kb,b.pc,b.Lb);L.splice(a,1)}function N(a){function b(d){++Na;Ra=a;Qa();a.Nb(d);Qa();--Na}if(a.Mb)a.pc=b,a.target.addEventListener(a.Kb,b,a.Lb),L.push(a),Sa||(Fa.push(Oa),Sa=!0);else for(var c=0;c<L.length;++c)L[c].target==a.target&&L[c].Kb==a.Kb&&Pa(c--)}function Ta(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Sa,Ra,Ua,Va,O,Wa,Xa,Ya,Za,$a=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function P(a){a=2<a?C(a):a;return $a[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function ab(a){return 0>$a.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function bb(a,b,c,d,f,h){Ua||(Ua=Q(256));a={target:P(a),Kb:h,Mb:d,Nb:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Ua;A(Ta(g.target),B,n+0,128);A(m,B,n+128,128);J(d)(f,n,b)&&g.preventDefault()},Lb:c};N(a)}
function cb(a,b,c,d,f,h){Va||(Va=Q(176));a={target:P(a),Rb:!0,Kb:h,Mb:d,Nb:function(g){var m=Va;E[m>>3]=g.timeStamp;var n=m>>2;D[n+2]=g.location;D[n+3]=g.ctrlKey;D[n+4]=g.shiftKey;D[n+5]=g.altKey;D[n+6]=g.metaKey;D[n+7]=g.repeat;D[n+8]=g.charCode;D[n+9]=g.keyCode;D[n+10]=g.which;A(g.key||"",B,m+44,32);A(g.code||"",B,m+76,32);A(g.char||"",B,m+108,32);A(g.locale||"",B,m+140,32);J(d)(f,m,b)&&g.preventDefault()},Lb:c};N(a)}
function db(a,b,c){E[a>>3]=b.timeStamp;a>>=2;D[a+2]=b.screenX;D[a+3]=b.screenY;D[a+4]=b.clientX;D[a+5]=b.clientY;D[a+6]=b.ctrlKey;D[a+7]=b.shiftKey;D[a+8]=b.altKey;D[a+9]=b.metaKey;wa[2*a+20]=b.button;wa[2*a+21]=b.buttons;D[a+11]=b.movementX;D[a+12]=b.movementY;c=ab(c);D[a+13]=b.clientX-c.left;D[a+14]=b.clientY-c.top}
function R(a,b,c,d,f,h){O||(O=Q(72));a=P(a);N({target:a,Rb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Kb:h,Mb:d,Nb:function(g){g=g||event;db(O,g,a);J(d)(f,O,b)&&g.preventDefault()},Lb:c})}function S(a,b,c,d,f){Wa||(Wa=Q(260));N({target:a,Kb:f,Mb:d,Nb:function(h){h=h||event;var g=Wa,m=document.pointerLockElement||document.Zb||document.ac||document.$b;D[g>>2]=!!m;var n=m&&m.id?m.id:"";A(Ta(m),B,g+4,128);A(n,B,g+132,128);J(d)(20,g,b)&&h.preventDefault()},Lb:c})}
function T(a,b,c,d,f){N({target:a,Kb:f,Mb:d,Nb:function(h){h=h||event;J(d)(38,0,b)&&h.preventDefault()},Lb:c})}
function eb(a,b,c,d){Xa||(Xa=Q(36));a=P(a);N({target:a,Kb:"resize",Mb:d,Nb:function(f){f=f||event;if(f.target==a){var h=document.body;if(h){var g=Xa;D[g>>2]=f.detail;D[g+4>>2]=h.clientWidth;D[g+8>>2]=h.clientHeight;D[g+12>>2]=innerWidth;D[g+16>>2]=innerHeight;D[g+20>>2]=outerWidth;D[g+24>>2]=outerHeight;D[g+28>>2]=pageXOffset;D[g+32>>2]=pageYOffset;J(d)(10,g,b)&&f.preventDefault()}}},Lb:c})}
function fb(a,b,c,d,f,h){Ya||(Ya=Q(1696));a=P(a);N({target:a,Rb:"touchstart"==h||"touchend"==h,Kb:h,Mb:d,Nb:function(g){for(var m,n={},p=g.touches,t=0;t<p.length;++t)m=p[t],m.dc=m.ec=0,n[m.identifier]=m;for(t=0;t<g.changedTouches.length;++t)m=g.changedTouches[t],m.dc=1,n[m.identifier]=m;for(t=0;t<g.targetTouches.length;++t)n[g.targetTouches[t].identifier].ec=1;p=Ya;E[p>>3]=g.timeStamp;var r=p>>2;D[r+3]=g.ctrlKey;D[r+4]=g.shiftKey;D[r+5]=g.altKey;D[r+6]=g.metaKey;r+=7;var lb=ab(a),mb=0;for(t in n)if(m=
n[t],D[r]=m.identifier,D[r+1]=m.screenX,D[r+2]=m.screenY,D[r+3]=m.clientX,D[r+4]=m.clientY,D[r+5]=m.pageX,D[r+6]=m.pageY,D[r+7]=m.dc,D[r+8]=m.ec,D[r+9]=m.clientX-lb.left,D[r+10]=m.clientY-lb.top,r+=13,31<++mb)break;D[p+8>>2]=mb;J(d)(f,p,b)&&g.preventDefault()},Lb:c})}function gb(a,b,c,d,f,h){a={target:P(a),Kb:h,Mb:d,Nb:function(g){g=g||event;J(d)(f,0,b)&&g.preventDefault()},Lb:c};N(a)}
function hb(a,b,c,d){Za||(Za=Q(104));N({target:a,Rb:!0,Kb:"wheel",Mb:d,Nb:function(f){f=f||event;var h=Za;db(h,f,a);E[h+72>>3]=f.deltaX;E[h+80>>3]=f.deltaY;E[h+88>>3]=f.deltaZ;D[h+96>>2]=f.deltaMode;J(d)(9,h,b)&&f.preventDefault()},Lb:c})}
function ib(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,h){b.drawArraysInstancedANGLE(c,d,f,h)},a.drawElementsInstanced=function(c,d,f,h,g){b.drawElementsInstancedANGLE(c,d,f,h,g)})}
function jb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function kb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function nb(a){a.Ac=a.getExtension("WEBGL_multi_draw")}
var ob=1,pb=[],U=[],qb=[],V=[],W=[],X=[],rb=[],sb={};function Y(a){tb||(tb=a)}function ub(a){for(var b=ob++,c=a.length;c<b;c++)a[c]=null;return b}function vb(a,b){a.cc||(a.cc=a.getContext,a.getContext=function(d,f){f=a.cc(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?wb(c,b):0}function wb(a,b){var c=ub(rb),d={yc:c,attributes:b,version:b.sc,Vb:a};a.canvas&&(a.canvas.tc=d);rb[c]=d;("undefined"===typeof b.bc||b.bc)&&xb(d);return c}
function xb(a){a||(a=yb);if(!a.rc){a.rc=!0;var b=a.Vb;ib(b);jb(b);kb(b);b.wc=b.getExtension("EXT_disjoint_timer_query");nb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var tb,yb,zb=["default","low-power","high-performance"];function Ab(a,b,c,d){for(var f=0;f<a;f++){var h=Z[c](),g=h&&ub(d);h?(h.name=g,d[g]=h):Y(1282);D[b+4*f>>2]=g}}
function Bb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Y(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)D[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){Y(1280);x("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:Y(1280);x("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}D[b>>2]=c}else Y(1281)}function Cb(a){var b=ta(a)+1,c=Q(b);A(a,B,c,b);return c}
function Db(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Eb(a,b,c,d,f){a-=5120;a=1==a?B:4==a?D:6==a?za:5==a||28922==a?ya:xa;var h=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(f>>h,f+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<h)+4-1&-4)>>h)}
var Z,Pb={K:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},R:function(a,b,c){a=P(a);if(!a)return-4;a=ab(a);E[b>>3]=a.width;E[c>>3]=a.height;return 0},o:fa?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()},Za:function(a,b,c){B.copyWithin(a,b,b+c)},lb:function(a,b){function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},_a:function(a){var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=
2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ma.grow(Math.min(2147483648,d)-va.byteLength+65535>>>16);Aa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},W:function(a,b,c,d){bb(a,b,c,d,12,"blur");return 0},G:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},X:function(a,b,c,d){bb(a,b,c,d,13,"focus");return 0},ea:function(a,b,c,d){cb(a,b,c,d,2,"keydown");return 0},ca:function(a,b,c,d){cb(a,b,c,d,1,"keypress");return 0},
da:function(a,b,c,d){cb(a,b,c,d,3,"keyup");return 0},ka:function(a,b,c,d){R(a,b,c,d,5,"mousedown");return 0},ha:function(a,b,c,d){R(a,b,c,d,33,"mouseenter");return 0},ga:function(a,b,c,d){R(a,b,c,d,34,"mouseleave");return 0},ia:function(a,b,c,d){R(a,b,c,d,8,"mousemove");return 0},ja:function(a,b,c,d){R(a,b,c,d,6,"mouseup");return 0},Z:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Zb||document.body.ac||document.body.$b))return-1;a=P(a);if(!a)return-4;
S(a,b,c,d,"pointerlockchange");S(a,b,c,d,"mozpointerlockchange");S(a,b,c,d,"webkitpointerlockchange");S(a,b,c,d,"mspointerlockchange");return 0},Y:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Zb||document.body.ac||document.body.$b))return-1;a=P(a);if(!a)return-4;T(a,b,c,d,"pointerlockerror");T(a,b,c,d,"mozpointerlockerror");T(a,b,c,d,"webkitpointerlockerror");T(a,b,c,d,"mspointerlockerror");return 0},Ha:function(a,b,c,d){eb(a,b,c,d);return 0},_:function(a,b,c,
d){fb(a,b,c,d,25,"touchcancel");return 0},$:function(a,b,c,d){fb(a,b,c,d,23,"touchend");return 0},aa:function(a,b,c,d){fb(a,b,c,d,24,"touchmove");return 0},ba:function(a,b,c,d){fb(a,b,c,d,22,"touchstart");return 0},V:function(a,b,c,d){gb(a,b,c,d,31,"webglcontextlost");return 0},U:function(a,b,c,d){gb(a,b,c,d,32,"webglcontextrestored");return 0},fa:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(hb(a,b,c,d),0):-1},la:function(a,b){b>>=2;b={alpha:!!D[b],depth:!!D[b+1],stencil:!!D[b+2],
antialias:!!D[b+3],premultipliedAlpha:!!D[b+4],preserveDrawingBuffer:!!D[b+5],powerPreference:zb[D[b+6]],failIfMajorPerformanceCaveat:!!D[b+7],sc:D[b+8],zc:D[b+9],bc:D[b+10],qc:D[b+11],Bc:D[b+12],Cc:D[b+13]};a=P(a);return!a||b.qc?0:vb(a,b)},Xa:function(a,b){a=rb[a];b=C(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&ib(Z);"OES_vertex_array_object"==b&&jb(Z);"WEBGL_draw_buffers"==b&&kb(Z);"WEBGL_multi_draw"==b&&nb(Z);return!!a.Vb.getExtension(b)},fb:function(a){a>>=2;for(var b=
0;14>b;++b)D[a+b]=0;D[a]=D[a+1]=D[a+3]=D[a+4]=D[a+8]=D[a+10]=1},Ya:function(a){yb=rb[a];e.vc=Z=yb&&yb.Vb;return!a||Z?0:-5},b:function(a){Z.activeTexture(a)},J:function(a,b){Z.attachShader(U[a],X[b])},c:function(a,b){Z.bindBuffer(a,pb[b])},h:function(a,b){Z.bindFramebuffer(a,qb[b])},Da:function(a,b){Z.bindRenderbuffer(a,V[b])},a:function(a,b){Z.bindTexture(a,W[b])},O:function(a,b,c,d){Z.blendColor(a,b,c,d)},P:function(a,b){Z.blendEquationSeparate(a,b)},Q:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,
d)},Fa:function(a,b,c,d){Z.bufferData(a,c?B.subarray(c,c+b):b,d)},r:function(a,b,c,d){Z.bufferSubData(a,b,B.subarray(d,d+c))},p:function(a){return Z.checkFramebufferStatus(a)},hb:function(a){Z.clear(a)},jb:function(a,b,c,d){Z.clearColor(a,b,c,d)},qa:function(a){Z.clearDepth(a)},ib:function(a){Z.clearStencil(a)},m:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},ta:function(a){Z.compileShader(X[a])},Aa:function(a,b,c,d,f,h,g,m){Z.compressedTexImage2D(a,b,c,d,f,h,m?B.subarray(m,m+g):null)},ya:function(){var a=
ub(U),b=Z.createProgram();b.name=a;b.Ub=b.Sb=b.Tb=0;b.Yb=1;U[a]=b;return a},va:function(a){var b=ub(X);X[b]=Z.createShader(a);return b},L:function(a){Z.cullFace(a)},Ma:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],f=pb[d];f&&(Z.deleteBuffer(f),f.name=0,pb[d]=null)}},d:function(a,b){for(var c=0;c<a;++c){var d=D[b+4*c>>2],f=qb[d];f&&(Z.deleteFramebuffer(f),f.name=0,qb[d]=null)}},z:function(a){if(a){var b=U[a];b?(Z.deleteProgram(b),b.name=0,U[a]=null):Y(1281)}},T:function(a,b){for(var c=0;c<a;c++){var d=
D[b+4*c>>2],f=V[d];f&&(Z.deleteRenderbuffer(f),f.name=0,V[d]=null)}},v:function(a){if(a){var b=X[a];b?(Z.deleteShader(b),X[a]=null):Y(1281)}},Ka:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],f=W[d];f&&(Z.deleteTexture(f),f.name=0,W[d]=null)}},y:function(a){Z.depthFunc(a)},x:function(a){Z.depthMask(!!a)},e:function(a){Z.disable(a)},S:function(a){Z.disableVertexAttribArray(a)},C:function(a,b,c){Z.drawArrays(a,b,c)},D:function(a,b,c,d){Z.drawElements(a,b,c,d)},i:function(a){Z.enable(a)},db:function(a){Z.enableVertexAttribArray(a)},
k:function(a,b,c,d){Z.framebufferRenderbuffer(a,b,c,V[d])},g:function(a,b,c,d,f){Z.framebufferTexture2D(a,b,c,W[d],f)},M:function(a){Z.frontFace(a)},Ga:function(a,b){Ab(a,b,"createBuffer",pb)},l:function(a,b){Ab(a,b,"createFramebuffer",qb)},Ea:function(a,b){Ab(a,b,"createRenderbuffer",V)},Ba:function(a,b){Ab(a,b,"createTexture",W)},ra:function(a,b){return Z.getAttribLocation(U[a],C(b))},f:function(a,b){Bb(a,b)},wa:function(a,b,c,d){a=Z.getProgramInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&
d?A(a,B,d,b):0;c&&(D[c>>2]=b)},I:function(a,b,c){if(c)if(a>=ob)Y(1281);else if(a=U[a],35716==b)a=Z.getProgramInfoLog(a),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b){if(!a.Ub)for(b=0;b<Z.getProgramParameter(a,35718);++b)a.Ub=Math.max(a.Ub,Z.getActiveUniform(a,b).name.length+1);D[c>>2]=a.Ub}else if(35722==b){if(!a.Sb)for(b=0;b<Z.getProgramParameter(a,35721);++b)a.Sb=Math.max(a.Sb,Z.getActiveAttrib(a,b).name.length+1);D[c>>2]=a.Sb}else if(35381==b){if(!a.Tb)for(b=0;b<Z.getProgramParameter(a,
35382);++b)a.Tb=Math.max(a.Tb,Z.getActiveUniformBlockName(a,b).length+1);D[c>>2]=a.Tb}else D[c>>2]=Z.getProgramParameter(a,b);else Y(1281)},sa:function(a,b,c,d){a=Z.getShaderInfoLog(X[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,B,d,b):0;c&&(D[c>>2]=b)},F:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(X[a]),null===a&&(a="(unknown error)"),D[c>>2]=a?a.length+1:0):35720==b?(a=Z.getShaderSource(X[a]),D[c>>2]=a?a.length+1:0):D[c>>2]=Z.getShaderParameter(X[a],b):Y(1281)},Na:function(a){var b=sb[a];
if(!b){switch(a){case 7939:b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Cb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||Y(1280);b=b&&Cb(b);break;case 7938:b=Cb("OpenGL ES 2.0 ("+Z.getParameter(7938)+")");break;case 35724:b=Z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Cb(b);break;default:Y(1280)}sb[a]=b}return b},
q:function(a,b){b=C(b);if(a=U[a]){var c=a,d=c.Qb,f=c.nc,h;if(!d)for(c.Qb=d={},c.mc={},h=0;h<Z.getProgramParameter(c,35718);++h){var g=Z.getActiveUniform(c,h);var m=g.name;g=g.size;var n=Db(m);n=0<n?m.slice(0,n):m;var p=c.Yb;c.Yb+=g;f[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.mc[p++]=n}c=a.Qb;d=0;f=b;h=Db(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,f=b.slice(0,h));if((f=a.nc[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||Z.getUniformLocation(a,b)))return d}else Y(1281);return-1},xa:function(a){a=U[a];Z.linkProgram(a);a.Qb=0;
a.nc={}},N:function(a,b){Z.polygonOffset(a,b)},Ca:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},kb:function(a,b,c,d){Z.scissor(a,b,c,d)},ua:function(a,b,c,d){for(var f="",h=0;h<b;++h){var g=d?D[d+4*h>>2]:-1;f+=C(D[c+4*h>>2],0>g?void 0:g)}Z.shaderSource(X[a],f)},Ja:function(a,b,c){Z.stencilFunc(a,b,c)},pa:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},w:function(a){Z.stencilMask(a)},Ia:function(a,b,c){Z.stencilOp(a,b,c)},oa:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},za:function(a,b,c,d,
f,h,g,m,n){Z.texImage2D(a,b,c,d,f,h,g,m,n?Eb(m,g,d,f,n):null)},j:function(a,b,c){Z.texParameteri(a,b,c)},cb:function(a,b,c,d,f,h,g,m,n){var p=null;n&&(p=Eb(m,g,f,h,n));Z.texSubImage2D(a,b,c,d,f,h,g,m,p)},H:function(a,b){var c=Z,d=c.uniform1i;var f=Z.oc;if(f){var h=f.Qb[a];"number"===typeof h&&(f.Qb[a]=h=Z.getUniformLocation(f,f.mc[a]+(0<h?"["+h+"]":"")));a=h}else Y(1282),a=void 0;d.call(c,a,b)},n:function(a){a=U[a];Z.useProgram(a);Z.oc=a},eb:function(a,b){Z.vertexAttribDivisor(a,b)},gb:function(a,
b,c,d,f,h){Z.vertexAttribPointer(a,b,c,!!d,f,h)},E:function(a,b,c,d){Z.viewport(a,b,c,d)},Va:function(){e.fc=function(a){0!=Fb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.fc)},Ua:function(){e.lc=function(a){a=a.clipboardData.getData("text");oa("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",e.lc)},Ta:function(a){e.Dc=[];a=C(a);a=document.getElementById(a);e.hc=function(b){b.stopPropagation();b.preventDefault()};e.ic=function(b){b.stopPropagation();
b.preventDefault()};e.jc=function(b){b.stopPropagation();b.preventDefault()};e.kc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;e.Xb=c;Gb(c.length);var d;for(d=0;d<c.length;d++)oa("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Hb(b.clientX,b.clientY)};a.addEventListener("dragenter",e.hc,!1);a.addEventListener("dragleave",e.ic,!1);a.addEventListener("dragover",e.jc,!1);a.addEventListener("drop",e.kc,!1)},Pa:function(){var a=document.getElementById("sokol-app-favicon");
a&&document.head.removeChild(a)},u:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Ib()});document.body.append(a)},nb:function(a){return 0>a||a>=e.Xb.length?0:e.Xb[a].size},mb:function(a,b,c,d,f){var h=new FileReader;h.onload=function(g){g=g.target.result;g.byteLength>d?Jb(a,0,1,b,0,c,d,f):(B.set(new Uint8Array(g),c),Jb(a,1,0,b,g.byteLength,c,d,f))};h.onerror=function(){Jb(a,0,2,b,0,c,d,
f)};h.readAsArrayBuffer(e.Xb[a])},t:function(){document.getElementById("_sokol_app_input_element").focus()},La:function(a){a=C(a);e.Pb=document.getElementById(a);e.Pb||console.log("sokol_app.h: invalid target:"+a);e.Pb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Sa:function(){window.removeEventListener("beforeunload",e.fc)},Ra:function(){window.removeEventListener("paste",e.lc)},Qa:function(a){a=C(a);a=document.getElementById(a);a.removeEventListener("dragenter",
e.hc);a.removeEventListener("dragleave",e.ic);a.removeEventListener("dragover",e.jc);a.removeEventListener("drop",e.kc)},B:function(){e.Pb&&e.Pb.requestPointerLock&&e.Pb.requestPointerLock()},Oa:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(B.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},
s:function(){document.getElementById("_sokol_app_input_element").blur()},Wa:function(){for(var a=(new URLSearchParams(window.location.search)).entries(),b=a.next();!b.done;b=a.next())oa("_sargs_add_kvp",["string","string"],[b.value[0],b.value[1]])},$a:function(){return e.Ob?e.Ob.bufferSize:0},bb:function(a,b,c){e.Jb=null;e.Ob=null;"undefined"!==typeof AudioContext?e.Jb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?e.Jb=new webkitAudioContext({sampleRate:a,
latencyHint:"interactive"}):(e.Jb=null,console.log("sokol_audio.h: no WebAudio support"));return e.Jb?(console.log("sokol_audio.h: sample rate ",e.Jb.sampleRate),e.Ob=e.Jb.createScriptProcessor(c,0,b),e.Ob.onaudioprocess=function(d){var f=d.outputBuffer.length,h=Kb(f);if(h)for(var g=d.outputBuffer.numberOfChannels,m=0;m<g;m++)for(var n=d.outputBuffer.getChannelData(m),p=0;p<f;p++)n[p]=za[(h>>2)+(g*p+m)]},e.Ob.connect(e.Jb.destination),a=function(){e.Jb&&"suspended"===e.Jb.state&&e.Jb.resume()},document.addEventListener("click",
a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},ab:function(){return e.Jb?e.Jb.sampleRate:0},na:function(){null!==e.Jb&&(e.Ob&&e.Ob.disconnect(),e.Jb.close(),e.Jb=null,e.Ob=null)},A:function(a,b,c,d,f,h){b=C(b);var g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";var m=0<d;m&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(this.readyState==this.DONE)if(206==this.status||200==
this.status&&!m){var n=new Uint8Array(g.response),p=n.length;p<=h?(B.set(n,f),Lb(a,d,p)):Mb(a)}else Nb(a,this.status)};g.send()},ma:function(a,b){b=C(b);var c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(this.readyState==this.DONE)if(200==this.status){var d=this.getResponseHeader("Content-Length");Ob(a,d)}else Nb(a,this.status)};c.send()}};
(function(){function a(f){e.asm=f.exports;ma=e.asm.ob;Aa();Ba=e.asm.Ib;Da.unshift(e.asm.pb);F--;e.monitorRunDependencies&&e.monitorRunDependencies(F);0==F&&(null!==Ia&&(clearInterval(Ia),Ia=null),G&&(f=G,G=null,f()))}function b(f){a(f.instance)}function c(f){return Ma().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(f,function(h){x("failed to asynchronously prepare wasm: "+h);la(h)})}var d={a:Pb};F++;e.monitorRunDependencies&&e.monitorRunDependencies(F);if(e.instantiateWasm)try{return e.instantiateWasm(d,
a)}catch(f){return x("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return y||"function"!==typeof WebAssembly.instantiateStreaming||Ja()||H.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(H,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(h){x("wasm streaming compile failed: "+h);x("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.pb).apply(null,arguments)};var Ib=e.__sapp_emsc_notify_keyboard_hidden=function(){return(Ib=e.__sapp_emsc_notify_keyboard_hidden=e.asm.qb).apply(null,arguments)};e.__sapp_emsc_onpaste=function(){return(e.__sapp_emsc_onpaste=e.asm.rb).apply(null,arguments)};
var Fb=e.__sapp_html5_get_ask_leave_site=function(){return(Fb=e.__sapp_html5_get_ask_leave_site=e.asm.sb).apply(null,arguments)},Gb=e.__sapp_emsc_begin_drop=function(){return(Gb=e.__sapp_emsc_begin_drop=e.asm.tb).apply(null,arguments)};e.__sapp_emsc_drop=function(){return(e.__sapp_emsc_drop=e.asm.ub).apply(null,arguments)};
var Hb=e.__sapp_emsc_end_drop=function(){return(Hb=e.__sapp_emsc_end_drop=e.asm.vb).apply(null,arguments)},Jb=e.__sapp_emsc_invoke_fetch_cb=function(){return(Jb=e.__sapp_emsc_invoke_fetch_cb=e.asm.wb).apply(null,arguments)};e._main=function(){return(e._main=e.asm.xb).apply(null,arguments)};var Kb=e.__saudio_emsc_pull=function(){return(Kb=e.__saudio_emsc_pull=e.asm.yb).apply(null,arguments)};e.__sargs_add_kvp=function(){return(e.__sargs_add_kvp=e.asm.zb).apply(null,arguments)};
var Ob=e.__sfetch_emsc_head_response=function(){return(Ob=e.__sfetch_emsc_head_response=e.asm.Ab).apply(null,arguments)},Lb=e.__sfetch_emsc_get_response=function(){return(Lb=e.__sfetch_emsc_get_response=e.asm.Bb).apply(null,arguments)},Nb=e.__sfetch_emsc_failed_http_status=function(){return(Nb=e.__sfetch_emsc_failed_http_status=e.asm.Cb).apply(null,arguments)},Mb=e.__sfetch_emsc_failed_buffer_too_small=function(){return(Mb=e.__sfetch_emsc_failed_buffer_too_small=e.asm.Db).apply(null,arguments)},Q=
e._malloc=function(){return(Q=e._malloc=e.asm.Eb).apply(null,arguments)},qa=e.stackSave=function(){return(qa=e.stackSave=e.asm.Fb).apply(null,arguments)},ra=e.stackRestore=function(){return(ra=e.stackRestore=e.asm.Gb).apply(null,arguments)},z=e.stackAlloc=function(){return(z=e.stackAlloc=e.asm.Hb).apply(null,arguments)},Qb;function w(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}G=function Rb(){Qb||Sb();Qb||(G=Rb)};
function Sb(a){function b(){if(!Qb&&(Qb=!0,e.calledRun=!0,!na)){I(Da);I(Ea);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Tb){var c=a,d=e._main;c=c||[];var f=c.length+1,h=z(4*(f+1));D[h>>2]=ua(da);for(var g=1;g<f;g++)D[(h>>2)+g]=ua(c[g-1]);D[(h>>2)+f]=0;try{var m=d(f,h);if(!(noExitRuntime||0<ka)){if(e.onExit)e.onExit(m);na=!0}k(m,new w(m))}catch(n){n instanceof w||"unwind"==n||k(1,n)}finally{}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),
Ga.unshift(c);I(Ga)}}a=a||ca;if(!(0<F)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ha();I(Ca);0<F||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=Sb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Tb=!0;e.noInitialRun&&(Tb=!1);Sb();
