var h;h||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer",da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;typeof __filename!="undefined"?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.length>1&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);typeof module!="undefined"&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{e.status==200||e.status==0&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),m=!1,na,la=a=>a.startsWith("file://");
function oa(){if(!p?.buffer?.resizable){var a=pa.buffer;p=new Int8Array(a);qa=new Int16Array(a);t=new Uint8Array(a);ra=new Uint16Array(a);u=new Int32Array(a);v=new Uint32Array(a);w=new Float32Array(a);x=new Float64Array(a);sa=new BigInt64Array(a)}}function ta(){var a=h.preRun;a&&(typeof a=="function"&&(a=[a]),ua.push(...a));for(a=ua;a.length>0;)a.shift()(h)}function va(){var a=h.postRun;a&&(typeof a=="function"&&(a=[a]),wa.push(...a));for(a=wa;a.length>0;)a.shift()(h)}
function xa(a){h.onAbort?.(a);a=`Aborted(${a})`;k(a);m=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ya;async function za(a){try{var b=await ja(a);return new Uint8Array(b)}catch{}if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function Aa(a,b){try{var c=await za(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),xa(d)}}
async function Ba(a){var b=ya;if(!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return Aa(b,a)}class Ca{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var p,wa=[],ua=[],Da=!0,Ea=globalThis.TextDecoder&&new TextDecoder,y=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(d-b>16&&a.buffer&&Ea)return Ea.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=(e&240)==224?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},
t,z=(a,b)=>a?y(t,a,b):"",Fa=0,Ga=[0,31,60,91,121,152,182,213,244,274,305,335],Ha=[0,31,59,90,120,151,181,212,243,273,304,334],u,A={},Ia=a=>{a instanceof Ca||a=="unwind"||fa(1,a)},Ja=a=>{na=a;Da||Fa>0||(h.onExit?.(a),m=!0);fa(a,new Ca(a))},Ka=()=>{if(!(Da||Fa>0))try{var a=na;na=a;Ja(a)}catch(b){Ia(b)}},La=a=>{if(!m)try{a()}catch(b){Ia(b)}finally{Ka()}},B=(a,b,c)=>{var d=t;if(!(c>0))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(b>=c)break;d[b++]=g}else if(g<=
2047){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(g<=65535){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},v,Ma=[],x,sa,Sa=(a,b)=>{Na=a;Oa=b;if(C)if(a==0)F=function(){setTimeout(G,Math.max(0,Pa+b-performance.now())|0)};else if(a==1)F=function(){Qa(G)};else{if(!Ra)if(globalThis.scheduler)Ra=scheduler.postTask.bind(scheduler);else if(globalThis.setImmediate)Ra=
setImmediate;else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);Ra=d=>{c.push(d);ba?postMessage("setimmediate"):postMessage("setimmediate","*")}}F=function(){Ra(G)}}},ab=(a,b,c,d,e)=>{function f(){return g<Ta?(Ka(),!1):!0}C=a;Ua=d;var g=Ta;G=function(){if(!m)if(Va.length>0){var l=Va.shift();l.ze(l.ne);if(Wa){var n=Wa,q=n%1==0?n-1:Math.floor(n);Wa=l.qe?q:(8*n+(q+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=Wa??0,q=Xa.we??0,n?n<
q?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));f()&&setTimeout(G,0)}else if(f())if(Ya=Ya+1|0,Na==1&&Oa>1&&Ya%Oa!=0)F();else{Na==0&&(Pa=performance.now());a:if(!m){for(l of Za)if(l()===!1)break a;La(a);for(n of $a)n()}f()&&F()}};e||(b>0?Sa(0,1E3/b):Sa(1,1),F());if(c)throw"unwind";},C=null,F=null,Ta=0,Ua=0,Na=0,Oa=0,Ya=0,Va=[],Za=[],$a=[];function bb(){F&&(F=null,Ta++)}var cb=0;
function Qa(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(cb)for(;b+2>=cb;)cb+=1E3/60;else cb=b+1E3/60;setTimeout(a,Math.max(cb-b,0))}}var Xa={},Pa,G,Ra,Wa,db=[0,globalThis.document??0,globalThis.window??0],H=a=>{a=a>2?a?y(t,a):"":a;return db[a]||globalThis.document?.querySelector(a)},eb=a=>db.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},fb=[],I=a=>{var b=fb[a];b||(fb[a]=b=gb.get(a));return b};
function hb(a){var b=J.nd[a];b.target.removeEventListener(b.md,b.Td,b.qd);J.nd.splice(a,1)}function ib(){if(navigator.userActivation?navigator.userActivation.isActive:J.Gd&&J.he.Dd){var a=J.vd;J.vd=[];for(var b of a)b.Jd(...b.Pd)}}function K(a){if(!a.target)return-4;if(a.od)a.Td=function(c){++J.Gd;J.he=a;ib();a.sd(c);ib();--J.Gd},a.target.addEventListener(a.md,a.Td,a.qd),J.nd.push(a);else for(var b=0;b<J.nd.length;++b)J.nd[b].target==a.target&&J.nd[b].md==a.md&&hb(b--);return 0}
function jb(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var J={oe:0,Ae:0,Hd:0,Bd:0,Nd:0,Ld:0,Ed:0,ue:0,Ee:0,te:0,Fd:0,Id:0,Ne:0,Kd:0,Ge(){for(;J.nd.length;)hb(J.nd.length-1);J.vd=[]},Gd:0,vd:[],se(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l=0;l<f.length;l++)if(f[l]!=g[l])return!1;return!0}for(var e of J.vd)if(e.Jd==a&&d(e.Pd,c))return;J.vd.push({Jd:a,Yd:b,Pd:c});J.vd.sort((f,g)=>f.Yd-g.Yd)},Ie(a){J.vd=J.vd.filter(b=>b.Jd!=a)},nd:[],He:(a,b)=>{for(var c=0;c<J.nd.length;++c)J.nd[c].target!=a||b&&b!=J.nd[c].md||hb(c--)},Je(a){var b=!1;
for(let c=0;c<J.nd.length;++c){let d=J.nd[c];d.target===a.target&&d.pd===a.pd&&d.od===a.od&&d.rd===a.rd&&(hb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled??document.webkitFullscreenEnabled}},kb=(a,b,c,d,e,f)=>{J.Ed||(J.Ed=L(256));a={target:H(a),md:f,pd:e,rd:b,od:d,sd:g=>{var l=g.target.id??"",n=J.Ed;B(jb(g.target),n+0,128);B(l,n+128,128);I(d)(e,n,b)&&g.preventDefault()},qd:c};return K(a)},lb=(a,b,c,d,e)=>{J.Fd||(J.Fd=L(276));return K({target:a,md:e,pd:19,rd:b,od:d,
sd:f=>{var g=J.Fd,l=document.fullscreenElement??document.webkitFullscreenElement,n=!!l;p[g]=n;p[g+1]=J.fullscreenEnabled();var q=n?l:J.le,r=q?.id??"";B(jb(q),g+2,128);B(r,g+130,128);u[g+260>>2]=q?.clientWidth??0;u[g+264>>2]=q?.clientHeight??0;u[g+268>>2]=screen.width;u[g+272>>2]=screen.height;n&&(J.le=l);I(d)(19,g,b)&&f.preventDefault()},qd:c})},mb=(a,b,c,d,e,f)=>{J.Hd||(J.Hd=L(160));a={target:H(a),md:f,pd:e,rd:b,od:d,sd:g=>{var l=J.Hd;x[l>>3]=g.timeStamp;var n=l>>2;u[n+2]=g.location;p[l+12]=g.ctrlKey;
p[l+13]=g.shiftKey;p[l+14]=g.altKey;p[l+15]=g.metaKey;p[l+16]=g.repeat;u[n+5]=g.charCode;u[n+6]=g.keyCode;u[n+7]=g.which;B(g.key??"",l+32,32);B(g.code??"",l+64,32);B(g.char??"",l+96,32);B(g.locale??"",l+128,32);I(d)(e,l,b)&&g.preventDefault()},qd:c};return K(a)},qa,nb=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;p[a+24]=b.ctrlKey;p[a+25]=b.shiftKey;p[a+26]=b.altKey;p[a+27]=b.metaKey;qa[d*2+14]=b.button;qa[d*2+15]=b.buttons;u[d+8]=b.movementX;
u[d+9]=b.movementY;a=eb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},ob=(a,b,c,d,e,f)=>{J.Bd||(J.Bd=L(64));a=H(a);return K({target:a,Dd:f!="mousemove"&&f!="mouseenter"&&f!="mouseleave",md:f,pd:e,rd:b,od:d,sd:g=>{nb(J.Bd,g,a);I(d)(e,J.Bd,b)&&g.preventDefault()},qd:c})},pb=(a,b,c,d)=>{J.Id||(J.Id=L(257));return K({target:a,md:"pointerlockchange",pd:20,rd:b,od:d,sd:e=>{var f=J.Id,g=document.pointerLockElement;p[f]=!!g;var l=g?.id??"";B(jb(g),f+1,128);B(l,f+129,128);I(d)(20,f,b)&&e.preventDefault()},
qd:c})},qb=(a,b,c,d)=>K({target:a,md:"pointerlockerror",pd:38,rd:b,od:d,sd:e=>{I(d)(38,0,b)&&e.preventDefault()},qd:c}),rb=(a,b,c,d)=>{J.Ld||(J.Ld=L(36));a=H(a);return K({target:a,md:"resize",pd:10,rd:b,od:d,sd:e=>{if(e.target==a){var f=document.body;if(f){var g=J.Ld;u[g>>2]=0;u[g+4>>2]=f.clientWidth;u[g+8>>2]=f.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;I(d)(10,g,b)&&e.preventDefault()}}},
qd:c})},sb=(a,b,c,d,e,f)=>{J.Kd||(J.Kd=L(1552));a=H(a);return K({target:a,Dd:f=="touchstart"||f=="touchend",md:f,pd:e,rd:b,od:d,sd:g=>{var l={},n=g.touches;for(var q of n)q.Ud=q.Xd=0,l[q.identifier]=q;for(var r of g.changedTouches)r.Ud=1,l[r.identifier]=r;for(var D of g.targetTouches)l[D.identifier].Xd=1;n=J.Kd;x[n>>3]=g.timeStamp;p[n+12]=g.ctrlKey;p[n+13]=g.shiftKey;p[n+14]=g.altKey;p[n+15]=g.metaKey;q=n+16;r=eb(a);D=0;for(let E of Object.values(l))if(l=q>>2,u[l]=E.identifier,u[l+1]=E.screenX,u[l+
2]=E.screenY,u[l+3]=E.clientX,u[l+4]=E.clientY,u[l+5]=E.pageX,u[l+6]=E.pageY,p[q+28]=E.Ud,p[q+29]=E.Xd,u[l+8]=E.clientX-(r.left|0),u[l+9]=E.clientY-(r.top|0),q+=48,++D>31)break;u[n+8>>2]=D;I(d)(e,n,b)&&g.preventDefault()},qd:c})},M,tb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},ub=
a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},vb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},wb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},xb=1,N=[],O=[],yb=[],zb=[],P=[],Q=[],Ab=[],Bb=[],R=[],Cb={},Db=4,Eb=0,Fb=a=>{for(var b=xb++,c=a.length;c<b;c++)a[c]=null;return b},T=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=M[c](),g=f&&Fb(d);f?(f.name=g,d[g]=f):S||=1282;u[b+e*4>>2]=g}},Hb=(a,b)=>{a.Vd||(a.Vd=a.getContext,a.getContext=function(d,e){e=a.Vd(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=b.Wd>1?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Gb(c,b):0},Gb=(a,b)=>{var c=Fb(Bb),d={handle:c,attributes:b,version:b.Wd,Od:a};a.canvas&&(a.canvas.me=d);Bb[c]=d;if(typeof b.Sd=="undefined"||b.Sd)if((a=d)||(a=U),!a.ke){a.ke=!0;b=a.Od;b.De=b.getExtension("WEBGL_multi_draw");b.ye=b.getExtension("EXT_polygon_offset_clamp");b.xe=b.getExtension("EXT_clip_control");b.Oe=b.getExtension("WEBGL_polygon_mode");tb(b);ub(b);vb(b);b.ve=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Be=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
a.version>=2&&(b.Rd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(a.version<2||!b.Rd)b.Rd=b.getExtension("EXT_disjoint_timer_query");for(var e of wb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},S,U,Ib=(a,b,c,d,e,f)=>{a={target:H(a),md:f,pd:e,rd:b,od:d,sd:g=>{I(d)(e,0,b)&&g.preventDefault()},qd:c};K(a)},Jb=(a,b,c,d)=>{J.Nd||(J.Nd=L(96));return K({target:a,Dd:!0,md:"wheel",pd:9,rd:b,od:d,sd:e=>{var f=J.Nd;nb(f,e,a);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+
80>>3]=e.deltaZ;u[f+88>>2]=e.deltaMode;I(d)(9,f,b)&&e.preventDefault()},qd:c})},Kb=["default","low-power","high-performance"],Lb={},Nb=()=>{if(!Mb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea},b;for(b in Lb)Lb[b]===void 0?delete a[b]:a[b]=Lb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Mb=c}return Mb},Mb,Ob=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=
2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},Pb=[null,[],[]],w,Qb=[],Rb=()=>{var a=wb(M);return a=a.concat(a.map(b=>"GL_"+b))},Sb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=M.getParameter(34467);c=d?d.length:0;break;case 33309:if(U.version<2){S||=1282;return}c=Rb().length;break;case 33307:case 33308:if(U.version<2){S||=1280;return}c=a==33307?3:0}if(c===void 0)switch(d=M.getParameter(a),typeof d){case "number":c=d;
break;case "boolean":c=d?1:0;break;case "string":S||=1280;return;case "object":if(d===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:S||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+a*4>>2]=d[a];return}try{c=
d.name|0}catch(e){S||=1280;k(`GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:S||=1280;k(`GL_INVALID_ENUM in glGet0v: Native code calling glGet0v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else S||=1281},Tb=a=>{var b=Ob(a)+1,c=L(b);c&&B(a,c,b);return c},Ub=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),ra,Vb=a=>{a-=5120;return a==0?p:a==1?t:a==2?qa:a==4?u:a==6?w:a==5||a==28922||a==28520||a==30779||a==30782?v:
ra},V=a=>{var b=M.ie;if(b){var c=b.xd[a];typeof c=="number"&&(b.xd[a]=c=M.getUniformLocation(b,b.fe[a]+(c>0?`[${c}]`:"")));return c}S||=1282},W=[],Wb=[],X=a=>{var b=Ob(a)+1,c=Xb(b);B(a,c,b);return c},$b=a=>{var b=Yb();a();Zb(b)};h.requestAnimationFrame=Qa;h.pauseMainLoop=bb;h.resumeMainLoop=function(){Ta++;var a=Na,b=Oa,c=C;C=null;ab(c,0,!1,Ua,!0);Sa(a,b);F()};for(let a=0;a<32;++a)Qb.push(Array(a));for(var ac=new Float32Array(288),Y=0;Y<=288;++Y)W[Y]=ac.subarray(0,Y);var bc=new Int32Array(288);
for(Y=0;Y<=288;++Y)Wb[Y]=bc.subarray(0,Y);h.noExitRuntime&&(Da=h.noExitRuntime);h.print&&(ma=h.print);h.printErr&&(k=h.printErr);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);var Z=h.preInit;if(Z)for(typeof Z=="function"&&(h.preInit=Z=[Z]);Z.length>0;)Z.shift()();
var cc={137847:()=>{h._webapi_input=a=>{$b(()=>h._webapi_input_internal(X(a)))};h._webapi_load_file=a=>{$b(()=>h._webapi_load_file_internal(X(a)))}}},L,dc,ec,fc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,Zb,Xb,Yb,pa,gb,vc={va:function(){return 0},sb:function(){return 0},tb:function(){},xb:()=>xa(""),lb:()=>{Da=!1;Fa=0},mb:function(a,b){a=a<-9007199254740992||a>9007199254740992?NaN:Number(a);a=new Date(a*1E3);if(isNaN(a.getTime()))return 1;u[b>>2]=a.getSeconds();u[b+4>>2]=a.getMinutes();u[b+8>>2]=a.getHours();
u[b+12>>2]=a.getDate();u[b+16>>2]=a.getMonth();u[b+20>>2]=a.getFullYear()-1900;u[b+24>>2]=a.getDay();var c=a.getFullYear();u[b+28>>2]=(c%4!==0||c%100===0&&c%400!==0?Ha:Ga)[a.getMonth()]+a.getDate()-1|0;u[b+36>>2]=-(a.getTimezoneOffset()*60);c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();u[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;return 0},ib:(a,b)=>{A[a]&&(clearTimeout(A[a].id),delete A[a]);if(!b)return 0;var c=setTimeout(()=>
{delete A[a];La(()=>uc(a,performance.now()))},b);A[a]={id:c,Me:b};return 0},nb:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();v[a>>2]=Math.max(f,e)*60;u[b>>2]=Number(f!=e);b=g=>{var l=Math.abs(g);return`UTC${g>=0?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(B(a,c,17),B(b,d,17)):(B(a,d,17),B(b,c,17))},Db:function(a){if(window.localStorage===void 0)return 0;a=a?y(t,
a):"";return(a=window.localStorage.getItem(a))?Tb(a):0},Eb:function(a,b){window.localStorage!==void 0&&(a=a?y(t,a):"",b=b?y(t,b):"",window.localStorage.setItem(a,b))},Bb:(a,b,c)=>{Ma.length=0;for(var d;d=t[b++];){var e=d!=105;e&=d!=112;c+=e&&c%8?4:0;Ma.push(d==112?v[c>>2]:d==106?sa[c>>3]:d==105?u[c>>2]:x[c>>3]);c+=e?8:4}return cc[a](...Ma)},Wa:()=>{bb();C=null},wb:()=>Date.now(),oa:()=>globalThis.devicePixelRatio??1,qa:(a,b,c)=>{a=H(a);if(!a)return-4;a=eb(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},
C:()=>performance.now(),Xa:()=>performance.now(),ab:(a,b)=>{function c(d){I(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},jb:a=>{var b=t.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-pa.buffer.byteLength+65535)/65536|0;try{pa.grow(d);oa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Y:(a,b,c,d)=>kb(a,b,c,d,12,"blur"),na:(a,b,c)=>{a=H(a);if(!a)return-4;
a.width=b;a.height=c;return 0},Z:(a,b,c,d)=>kb(a,b,c,d,13,"focus"),X:(a,b,c,d)=>{if(!J.fullscreenEnabled())return-1;a=H(a);if(!a)return-4;lb(a,b,c,d,"webkitfullscreenchange");return lb(a,b,c,d,"fullscreenchange")},ga:(a,b,c,d)=>mb(a,b,c,d,2,"keydown"),ea:(a,b,c,d)=>mb(a,b,c,d,1,"keypress"),fa:(a,b,c,d)=>mb(a,b,c,d,3,"keyup"),bb:(a,b,c)=>{a=I(a);ab(a,b,c)},ma:(a,b,c,d)=>ob(a,b,c,d,5,"mousedown"),ja:(a,b,c,d)=>ob(a,b,c,d,33,"mouseenter"),ia:(a,b,c,d)=>ob(a,b,c,d,34,"mouseleave"),ka:(a,b,c,d)=>ob(a,
b,c,d,8,"mousemove"),la:(a,b,c,d)=>ob(a,b,c,d,6,"mouseup"),$:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?pb(a,b,c,d):-4:-1,_:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?qb(a,b,c,d):-4:-1,pa:(a,b,c,d)=>rb(a,b,c,d),aa:(a,b,c,d)=>sb(a,b,c,d,25,"touchcancel"),ba:(a,b,c,d)=>sb(a,b,c,d,23,"touchend"),ca:(a,b,c,d)=>sb(a,b,c,d,24,"touchmove"),da:(a,b,c,d)=>sb(a,b,c,d,22,"touchstart"),W:(a,b,c,d)=>{Ib(a,b,c,d,31,"webglcontextlost");return 0},V:(a,b,c,d)=>{Ib(a,b,c,d,32,"webglcontextrestored");
return 0},ha:(a,b,c,d)=>(a=H(a))?typeof a.onwheel!="undefined"?Jb(a,b,c,d):-1:-4,$a:(a,b)=>{var c=b>>2;b={alpha:!!p[b+0],depth:!!p[b+1],stencil:!!p[b+2],antialias:!!p[b+3],premultipliedAlpha:!!p[b+4],preserveDrawingBuffer:!!p[b+5],powerPreference:Kb[u[c+2]],failIfMajorPerformanceCaveat:!!p[b+12],desynchronized:!!p[b+33],Wd:u[c+4],Ce:u[c+5],Sd:p[b+24],je:p[b+25],Fe:u[c+7],Ke:p[b+32]};a=H(a);return!a||b.je?0:Hb(a,b)},_a:a=>{U=Bb[a];h.ctx=M=U?.Od;return!a||M?0:-5},ub:(a,b)=>{var c=0,d=0,e;for(e of Nb()){var f=
b+c;v[a+d>>2]=f;c+=B(e,f,Infinity)+1;d+=4}return 0},vb:(a,b)=>{var c=Nb();v[a>>2]=c.length;a=0;for(var d of c)a+=Ob(d)+1;v[b>>2]=a;return 0},ua:()=>52,qb:()=>52,ob:function(){return 70},pb:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=v[b>>2],l=v[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=a,r=t[g+n],D=Pb[q];r&&r!==10?D.push(r):((q===1?ma:k)(y(D)),D.length=0)}e+=l}v[d>>2]=e;return 0},h:function(a,b,c){var d=a?y(t,a):"";try{var e=window.indexedDB.open("chips",1)}catch(f){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+
f)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");e.result.createObjectStore("store")};e.onsuccess=()=>{var f=e.result;try{var g=f.transaction(["store"],"readwrite")}catch(q){console.log("fs_js_load_snapshot: db.transaction failed with",q);return}f=g.objectStore("store");var l=d+"_"+b,n=f.get(l);n.onsuccess=()=>{if(n.result!==void 0){let q=n.result.length;console.log("fs_js_load_snapshot:",l,"successfully loaded",q,"bytes");let r=sc(q);t.set(n.result,r);tc(c,r,q)}else tc(c,
0,0)};n.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",l)};g.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},Cb:function(a,b,c,d){var e=a?y(t,a):"";console.log("fs_js_save_snapshot: called with",e,b);try{var f=window.indexedDB.open("chips",1)}catch(g){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+g);return}f.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");
f.result.createObjectStore("store")};f.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");var g=f.result.transaction(["store"],"readwrite"),l=g.objectStore("store"),n=e+"_"+b;l=l.put(t.subarray(c,c+d),n);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",n,"successfully stored")};l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",n)};g.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};f.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},
o:a=>M.activeTexture(a),G:(a,b)=>{M.attachShader(O[a],Q[b])},a:(a,b)=>{a==35051?M.Qd=b:a==35052&&(M.wd=b);M.bindBuffer(a,N[b])},y:(a,b,c)=>{M.bindBufferBase(a,b,N[c])},Xb:(a,b,c,d,e)=>{M.bindBufferRange(a,b,N[c],d,e)},j:(a,b)=>{M.bindFramebuffer(a,yb[b])},fc:(a,b)=>{M.bindRenderbuffer(a,zb[b])},n:(a,b)=>{M.bindSampler(a,R[b])},c:(a,b)=>{M.bindTexture(a,P[b])},U:a=>{M.bindVertexArray(Ab[a])},P:(a,b,c,d)=>M.blendColor(a,b,c,d),Q:(a,b)=>M.blendEquationSeparate(a,b),R:(a,b,c,d)=>M.blendFuncSeparate(a,
b,c,d),Gb:(a,b,c,d,e,f,g,l,n,q)=>M.blitFramebuffer(a,b,c,d,e,f,g,l,n,q),Ka:(a,b,c,d)=>{U.version>=2?c&&b?M.bufferData(a,t,d,c,b):M.bufferData(a,b,d):M.bufferData(a,c?t.subarray(c,c+b):b,d)},J:(a,b,c,d)=>{var e=t;U.version>=2?c&&M.bufferSubData(a,b,e,d,c):M.bufferSubData(a,b,e.subarray(d,d+c))},dc:a=>M.checkFramebufferStatus(a),cc:(a,b,c,d)=>M.clearBufferfi(a,b,c,d),ya:(a,b,c)=>{M.clearBufferfv(a,b,w,c>>2)},ac:(a,b,c)=>{M.clearBufferiv(a,b,u,c>>2)},p:(a,b,c,d)=>{M.colorMask(!!a,!!b,!!c,!!d)},jc:a=>
{M.compileShader(Q[a])},w:(a,b,c,d,e,f,g,l,n)=>{U.version>=2?M.wd||!l?M.compressedTexSubImage2D(a,b,c,d,e,f,g,l,n):M.compressedTexSubImage2D(a,b,c,d,e,f,g,t,n,l):M.compressedTexSubImage2D(a,b,c,d,e,f,g,t.subarray(n,n+l))},I:(a,b,c,d,e,f,g,l,n,q,r)=>{M.wd?M.compressedTexSubImage3D(a,b,c,d,e,f,g,l,n,q,r):M.compressedTexSubImage3D(a,b,c,d,e,f,g,l,n,t,r,q)},oc:()=>{var a=Fb(O),b=M.createProgram();b.name=a;b.Ad=b.yd=b.zd=0;b.Md=1;O[a]=b;return a},lc:a=>{var b=Fb(Q);Q[b]=M.createShader(a);return b},M:a=>
M.cullFace(a),Oa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=N[d];e&&(M.deleteBuffer(e),e.name=0,N[d]=null,d==M.Qd&&(M.Qd=0),d==M.wd&&(M.wd=0))}},x:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+c*4>>2],e=yb[d];e&&(M.deleteFramebuffer(e),e.name=0,yb[d]=null)}},t:a=>{if(a){var b=O[a];b?(M.deleteProgram(b),b.name=0,O[a]=null):S||=1281}},K:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=zb[d];e&&(M.deleteRenderbuffer(e),e.name=0,zb[d]=null)}},L:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=R[d];e&&
(M.deleteSampler(e),e.name=0,R[d]=null)}},s:a=>{if(a){var b=Q[a];b?(M.deleteShader(b),Q[a]=null):S||=1281}},k:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=P[d];e&&(M.deleteTexture(e),e.name=0,P[d]=null)}},Na:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2];M.deleteVertexArray(Ab[d]);Ab[d]=null}},A:a=>M.depthFunc(a),z:a=>{M.depthMask(!!a)},d:a=>M.disable(a),S:a=>{M.disableVertexAttribArray(a)},Ib:(a,b,c)=>{M.drawArrays(a,b,c)},Kb:(a,b,c,d)=>{M.drawArraysInstanced(a,b,c,d)},za:(a,b)=>{for(var c=Qb[a],
d=0;d<a;d++)c[d]=u[b+d*4>>2];M.drawBuffers(c)},Lb:(a,b,c,d)=>{M.drawElements(a,b,c,d)},Mb:(a,b,c,d,e)=>{M.drawElementsInstanced(a,b,c,d,e)},g:a=>M.enable(a),Yb:a=>{M.enableVertexAttribArray(a)},l:(a,b,c,d)=>{M.framebufferRenderbuffer(a,b,c,zb[d])},e:(a,b,c,d,e)=>{M.framebufferTexture2D(a,b,c,P[d],e)},E:(a,b,c,d,e)=>{M.framebufferTextureLayer(a,b,P[c],d,e)},N:a=>M.frontFace(a),La:(a,b)=>{T(a,b,"createBuffer",N)},T:(a,b)=>{T(a,b,"createFramebuffer",yb)},gc:(a,b)=>{T(a,b,"createRenderbuffer",zb)},pc:(a,
b)=>{T(a,b,"createSampler",R)},Ja:(a,b)=>{T(a,b,"createTexture",P)},Va:(a,b)=>{T(a,b,"createVertexArray",Ab)},hc:(a,b)=>M.getAttribLocation(O[a],b?y(t,b):""),b:(a,b)=>Sb(a,b),nc:(a,b,c,d)=>{a=M.getProgramInfoLog(O[a]);a===null&&(a="(unknown error)");b=b>0&&d?B(a,d,b):0;c&&(u[c>>2]=b)},Da:(a,b,c)=>{if(c)if(a>=xb)S||=1281;else if(a=O[a],b==35716)a=M.getProgramInfoLog(a),a===null&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(b==35719){if(!a.Ad){var d=M.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Ad=
Math.max(a.Ad,M.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.Ad}else if(b==35722){if(!a.yd)for(d=M.getProgramParameter(a,35721),b=0;b<d;++b)a.yd=Math.max(a.yd,M.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.yd}else if(b==35381){if(!a.zd)for(d=M.getProgramParameter(a,35382),b=0;b<d;++b)a.zd=Math.max(a.zd,M.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.zd}else u[c>>2]=M.getProgramParameter(a,b);else S||=1281},ic:(a,b,c,d)=>{a=M.getShaderInfoLog(Q[a]);a===null&&(a="(unknown error)");b=b>0&&d?
B(a,d,b):0;c&&(u[c>>2]=b)},Ba:(a,b,c)=>{c?b==35716?(a=M.getShaderInfoLog(Q[a]),a===null&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):b==35720?(a=M.getShaderSource(Q[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=M.getShaderParameter(Q[a],b):S||=1281},Ta:(a,b)=>{if(U.version<2)return S||=1282,0;var c=Cb[a];if(c)return b<0||b>=c.length?(S||=1281,0):c[b];switch(a){case 7939:return c=Rb().map(Tb),c=Cb[a]=c,b<0||b>=c.length?(S||=1281,0):c[b];default:return S||=1280,0}},Ca:(a,b)=>{b=b?y(t,b):"";if(a=O[a]){var c=
a,d=c.xd,e=c.ge,f;if(!d){c.xd=d={};c.fe={};var g=M.getProgramParameter(c,35718);for(f=0;f<g;++f){var l=M.getActiveUniform(c,f);var n=l.name;l=l.size;var q=Ub(n);q=q>0?n.slice(0,q):n;var r=c.Md;c.Md+=l;e[q]=[l,r];for(n=0;n<l;++n)d[r]=n,c.fe[r++]=q}}c=a.xd;d=0;f=b;e=Ub(b);e>0&&(d=b.slice(e+1),d=parseInt(d)>>>0,f=b.slice(0,e));if((e=a.ge[f])&&d<e[0]&&(d+=e[1],c[d]=c[d]||M.getUniformLocation(a,b)))return d}else S||=1281;return-1},Fb:(a,b,c)=>{for(var d=Qb[b],e=0;e<b;e++)d[e]=u[c+e*4>>2];M.invalidateFramebuffer(a,
d)},Ea:a=>{a=O[a];M.linkProgram(a);a.xd=0;a.ge={}},q:(a,b)=>{a==3317?Db=b:a==3314&&(Eb=b);M.pixelStorei(a,b)},O:(a,b)=>M.polygonOffset(a,b),Hb:a=>M.readBuffer(a),ec:(a,b,c,d,e)=>M.renderbufferStorageMultisample(a,b,c,d,e),Fa:(a,b,c)=>{M.samplerParameterf(R[a],b,c)},f:(a,b,c)=>{M.samplerParameteri(R[a],b,c)},r:(a,b,c,d)=>M.scissor(a,b,c,d),kc:(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=z(v[c+f*4>>2],d?v[d+f*4>>2]:void 0);M.shaderSource(Q[a],e)},Sa:(a,b,c)=>M.stencilFunc(a,b,c),xa:(a,b,c,d)=>M.stencilFuncSeparate(a,
b,c,d),u:a=>M.stencilMask(a),Ra:(a,b,c)=>M.stencilOp(a,b,c),wa:(a,b,c,d)=>M.stencilOpSeparate(a,b,c,d),Ia:(a,b,c,d,e)=>M.texStorage2D(a,b,c,d,e),Ha:(a,b,c,d,e,f)=>M.texStorage3D(a,b,c,d,e,f),v:(a,b,c,d,e,f,g,l,n)=>{if(U.version>=2){if(M.wd){M.texSubImage2D(a,b,c,d,e,f,g,l,n);return}if(n){var q=Vb(l);M.texSubImage2D(a,b,c,d,e,f,g,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=Vb(l);var r=f*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT*
(Eb||e)+Db-1&-Db);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+r>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;M.texSubImage2D(a,b,c,d,e,f,g,l,n)},H:(a,b,c,d,e,f,g,l,n,q,r)=>{if(M.wd)M.texSubImage3D(a,b,c,d,e,f,g,l,n,q,r);else if(r){var D=Vb(q);M.texSubImage3D(a,b,c,d,e,f,g,l,n,q,D,r>>>31-Math.clz32(D.BYTES_PER_ELEMENT))}else M.texSubImage3D(a,b,c,d,e,f,g,l,n,q,null)},Wb:(a,b,c)=>{if(U.version>=2)b&&M.uniform1fv(V(a),w,c>>2,b);else{if(b<=288)for(var d=W[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];
else d=w.subarray(c>>2,c+b*4>>2);M.uniform1fv(V(a),d)}},mc:(a,b)=>{M.uniform1i(V(a),b)},Rb:(a,b,c)=>{if(U.version>=2)b&&M.uniform1iv(V(a),u,c>>2,b);else{if(b<=288)for(var d=Wb[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+b*4>>2);M.uniform1iv(V(a),d)}},Vb:(a,b,c)=>{if(U.version>=2)b&&M.uniform2fv(V(a),w,c>>2,b*2);else{if(b<=144){b*=2;for(var d=W[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+b*8>>2);M.uniform2fv(V(a),d)}},Qb:(a,b,c)=>{if(U.version>=2)b&&
M.uniform2iv(V(a),u,c>>2,b*2);else{if(b<=144){b*=2;for(var d=Wb[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+b*8>>2);M.uniform2iv(V(a),d)}},Tb:(a,b,c)=>{if(U.version>=2)b&&M.uniform3fv(V(a),w,c>>2,b*3);else{if(b<=96){b*=3;for(var d=W[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+b*12>>2);M.uniform3fv(V(a),d)}},Pb:(a,b,c)=>{if(U.version>=2)b&&M.uniform3iv(V(a),u,c>>2,b*3);else{if(b<=96){b*=3;for(var d=Wb[b],
e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+b*12>>2);M.uniform3iv(V(a),d)}},Sb:(a,b,c)=>{if(U.version>=2)b&&M.uniform4fv(V(a),w,c>>2,b*4);else{if(b<=72){var d=W[4*b],e=w;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+b*16>>2);M.uniform4fv(V(a),d)}},Ob:(a,b,c)=>{if(U.version>=2)b&&M.uniform4iv(V(a),u,c>>2,b*4);else{if(b<=72){b*=4;for(var d=Wb[b],e=0;e<b;e+=4)d[e]=u[c+4*
e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+b*16>>2);M.uniform4iv(V(a),d)}},Nb:(a,b,c,d)=>{if(U.version>=2)b&&M.uniformMatrix4fv(V(a),!!c,w,d>>2,b*16);else{if(b<=18){var e=W[16*b],f=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];
e[g+15]=f[l+15]}}else e=w.subarray(d>>2,d+b*64>>2);M.uniformMatrix4fv(V(a),!!c,e)}},m:a=>{a=O[a];M.useProgram(a);M.ie=a},Zb:(a,b)=>{M.vertexAttribDivisor(a,b)},_b:(a,b,c,d,e)=>{M.vertexAttribIPointer(a,b,c,d,e)},$b:(a,b,c,d,e,f)=>{M.vertexAttribPointer(a,b,c,!!d,e,f)},i:(a,b,c,d)=>M.viewport(a,b,c,d),kb:Ja,rc:function(){h.Zd=a=>{ec()!=0&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.Zd)},cb:function(){h.ee=a=>{var b=a.clipboardData.getData("text");$b(()=>{var c=
X(b);dc(c)})};window.addEventListener("paste",h.ee)},Ua:function(){h.Le=[];h.$d=b=>{b.stopPropagation();b.preventDefault()};h.ae=b=>{b.stopPropagation();b.preventDefault()};h.be=b=>{b.stopPropagation();b.preventDefault()};h.ce=b=>{b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;h.de=c;fc(c.length);for(let e=0;e<c.length;e++)$b(()=>{var f=X(c[e].name);hc(e,f)});var d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);ic(b.clientX,b.clientY,d)};var a=h.td;a.addEventListener("dragenter",
h.$d,!1);a.addEventListener("dragleave",h.ae,!1);a.addEventListener("dragover",h.be,!1);a.addEventListener("drop",h.ce,!1)},Ub:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},bc:function(a){h.Cd&&(URL.revokeObjectURL(h.Cd[a].pe),h.Cd[a]=null)},Qa:function(a){var b=h.de;return a<0||a>=b.length?0:b[a].size},Pa:function(a,b,c,d,e){var f=new FileReader;f.onload=g=>{g=g.target.result;g.byteLength>d?jc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(g),c),jc(a,1,0,
b,g.byteLength,c,d,e))};f.onerror=()=>{jc(a,0,2,b,0,c,d,e)};f.readAsArrayBuffer(h.de[a])},qc:function(a,b){b!==0&&(document.title=z(Number(b)));a=z(Number(a));h.canvas!==void 0&&(typeof h.canvas==="object"?db[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.td=H(a);h.td||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.td.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},gb:function(){window.removeEventListener("beforeunload",
h.Zd)},Za:function(){window.removeEventListener("paste",h.ee)},Ma:function(){var a=h.td;a.removeEventListener("dragenter",h.$d);a.removeEventListener("dragleave",h.ae);a.removeEventListener("dragover",h.be);a.removeEventListener("drop",h.ce)},F:function(){h.td&&h.td.requestPointerLock&&h.td.requestPointerLock()},Aa:function(a,b,c){if(h.td){if(b===0)a="none";else if(c!=0)a=h.Cd[a].re;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a=
"pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.td.style.cursor=a}},Jb:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),f=e.createImageData(a,b);f.data.set(t.subarray(c,c+a*b*4));e.putImageData(f,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();
document.head.appendChild(a)},Ya:function(a){a=z(Number(a));var b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},db:function(){var a=(new URLSearchParams(window.location.search)).entries();
for(let b=a.next();!b.done;b=a.next()){let c=b.value[0],d=b.value[1];$b(()=>{var e=X(c),f=X(d);mc(e,f)})}},fb:function(){return h.ud?h.ud.bufferSize:0},rb:function(a,b,c){h.ld=null;h.ud=null;typeof AudioContext!=="undefined"?h.ld=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(h.ld=null,console.log("sokol_audio.h: no WebAudio support"));if(h.ld){console.log("sokol_audio.h: sample rate ",h.ld.sampleRate);h.ud=h.ld.createScriptProcessor(c,0,b);h.ud.onaudioprocess=e=>{var f=e.outputBuffer.length,
g=lc(f);if(g){let l=e.outputBuffer.numberOfChannels;for(let n=0;n<l;n++){let q=e.outputBuffer.getChannelData(n);for(let r=0;r<f;r++)q[r]=w[(g>>2)+(l*r+n)]}}};h.ud.connect(h.ld.destination);let d=()=>{if(h.ld){let e=h.ld.state;e!=="suspended"&&e!=="interrupted"||h.ld.resume().catch(()=>{console.warn("sokol_audio.h: webaudio resume failed")})}};h.ld.onstatechange=d;document.addEventListener("visibilitychange",()=>{document.visibilityState==="visible"&&d()});document.addEventListener("click",d,{once:!0});
document.addEventListener("touchend",d,{once:!0});document.addEventListener("keydown",d,{once:!0});return 1}return 0},hb:function(){return h.ld?h.ld.sampleRate:0},ta:function(){var a=h.ld;a!==null&&(h.ud&&h.ud.disconnect(),a.close(),h.ld=null,h.ud=null)},eb:function(){if(h.ld){let a=h.ld.state;return a==="suspended"||a==="interrupted"?1:0}return 0},B:function(a,b,c,d,e,f){var g=z(Number(b));b=new Headers;d>0&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(g,{method:"GET",headers:b}).then(l=>{l.ok?
l.arrayBuffer().then(n=>{n=new Uint8Array(n);n.length<=f?(t.set(n,e),oc(a,d,n.length)):qc(a)}).catch(n=>{console.error(`sokol_fetch.h: GET ${g} failed with: `,n);rc(a)}):pc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${g} failed with: `,l);rc(a)})},sa:function(a,b){var c=z(Number(b));fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),d===null?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),rc(a)):nc(a,Number(d))):pc(a,d.status)}).catch(d=>
{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);rc(a)})},Ga:function(){return navigator.userAgent.includes("Macintosh")?1:0},ra:function(a,b){b=z(Number(b));switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Ab:function(){console.log("webapi_js_event_continued()");h.webapi_onContinued?h.webapi_onContinued():console.log("no Module.webapi_onContinued function")},zb:function(){console.log("webapi_js_event_reboot()");
h.webapi_onReboot?h.webapi_onReboot():console.log("no Module.webapi_onReboot function")},yb:function(){console.log("webapi_js_event_reset()");h.webapi_onReset?h.webapi_onReset():console.log("no Module.webapi_onReset function")},D:function(a,b){console.log("webapi_js_event_stopped()");h.webapi_onStopped?h.webapi_onStopped(a,b):console.log("no Module.webapi_onStopped function")}};
function wc(a=[]){var b=kc;a.unshift(ea);var c=a.length,d=Xb((c+1)*4),e=d,f;for(f of a)v[e>>2]=X(f),e+=4;v[e>>2]=0;try{var g=b(c,d);na=g;Ja(g)}catch(l){Ia(l)}}async function xc(){var a=da;ta();var b=h.setStatus;b&&(b("Running..."),await new Promise(c=>setTimeout(c,1)),setTimeout(b,1,""));m||(yc.tc(),h.onRuntimeInitialized?.(),h.noInitialRun||wc(a),va())}var yc;
(async function(){function a(d){d=yc=d.exports;L=d.uc;dc=h.__sapp_emsc_onpaste=d.vc;ec=h.__sapp_html5_get_ask_leave_site=d.wc;fc=h.__sapp_emsc_begin_drop=d.xc;hc=h.__sapp_emsc_drop=d.yc;ic=h.__sapp_emsc_end_drop=d.zc;jc=h.__sapp_emsc_invoke_fetch_cb=d.Ac;h.__sapp_emsc_set_fullscreen_flag=d.Bc;kc=h._main=d.Cc;lc=h.__saudio_emsc_pull=d.Dc;mc=h.__sargs_add_kvp=d.Ec;nc=h.__sfetch_emsc_head_response=d.Fc;oc=h.__sfetch_emsc_get_response=d.Gc;pc=h.__sfetch_emsc_failed_http_status=d.Hc;qc=h.__sfetch_emsc_failed_buffer_too_small=
d.Ic;rc=h.__sfetch_emsc_failed_other=d.Jc;sc=h._fs_emsc_alloc=d.Kc;tc=h._fs_emsc_load_snapshot_callback=d.Lc;h._webapi_dbg_connect=d.Mc;h._webapi_dbg_disconnect=d.Nc;h._webapi_alloc=d.Oc;h._webapi_free=d.Pc;h._webapi_boot=d.Qc;h._webapi_reset=d.Rc;h._webapi_ready=d.Sc;h._webapi_load=d.Tc;h._webapi_load_file_internal=d.Uc;h._webapi_unload_file=d.Vc;h._webapi_load_snapshot=d.Wc;h._webapi_save_snapshot=d.Xc;h._webapi_dbg_add_breakpoint=d.Yc;h._webapi_dbg_remove_breakpoint=d.Zc;h._webapi_dbg_break=d._c;
h._webapi_dbg_continue=d.$c;h._webapi_dbg_step_next=d.ad;h._webapi_dbg_step_into=d.bd;h._webapi_dbg_cpu_state=d.cd;h._webapi_dbg_request_disassembly=d.dd;h._webapi_dbg_read_memory=d.ed;h._webapi_input_internal=d.fd;uc=d.hd;Zb=d.id;Xb=d.jd;Yb=d.kd;pa=d.sc;gb=d.gd;oa();return yc}var b={a:vc},c=h.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});ya??=h.locateFile?h.locateFile("kc853-ui.wasm",ia):ia+"kc853-ui.wasm";return function(d){return a(d.instance)}(await Ba(b))})().then(()=>xc());
