
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign,ba=aa({},f),ca=[],da="./this.program";function k(a,b){throw b;}var ea="object"===typeof window,l="function"===typeof importScripts,fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,q="",ha,u,v,fs,ia,ja;
if(fa)q=l?require("path").dirname(q)+"/":__dirname+"/",ja=function(){fs||(fs=require("fs"),ia=require("path"))},ha=function(a,b){ja();a=ia.normalize(a);return fs.readFileSync(a,b?null:"utf8")},v=function(a){a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a},u=function(a,b,c){ja();a=ia.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",
function(a){if(!(a instanceof w))throw a;}),process.on("unhandledRejection",function(a){throw a;}),k=function(a,b){if(noExitRuntime||0<ka)throw process.exitCode=a,b;b instanceof w||x("exiting due to exception: "+b);process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ea||l)l?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ha=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(v=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var la=f.print||console.log.bind(console),x=f.printErr||console.warn.bind(console);aa(f,ba);
ba=null;f.arguments&&(ca=f.arguments);f.thisProgram&&(da=f.thisProgram);f.quit&&(k=f.quit);var y;f.wasmBinary&&(y=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&z("no native wasm support detected");var ma,na=!1;
function oa(a,b,c){var d={string:function(n){var p=0;if(null!==n&&void 0!==n&&0!==n){var r=(n.length<<2)+1;p=A(r);B(n,C,p,r)}return p},array:function(n){var p=A(n.length);pa.set(n,p);return p}};a=f["_"+a];var e=[],h=0;if(c)for(var g=0;g<c.length;g++){var m=d[b[g]];m?(0===h&&(h=qa()),e[g]=m(c[g])):e[g]=c[g]}b=a.apply(null,e);b=function(n){0!==h&&ra(h);return n}(b)}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ta(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a,b){return a?ta(C,a,b):""}
function B(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function va(a){var b=ua(a)+1,c=A(b);B(a,pa,c,b);return c}var wa,pa,C,xa,ya,E,za,F,G;
function Aa(){var a=ma.buffer;wa=a;f.HEAP8=pa=new Int8Array(a);f.HEAP16=xa=new Int16Array(a);f.HEAP32=E=new Int32Array(a);f.HEAPU8=C=new Uint8Array(a);f.HEAPU16=ya=new Uint16Array(a);f.HEAPU32=za=new Uint32Array(a);f.HEAPF32=F=new Float32Array(a);f.HEAPF64=G=new Float64Array(a)}var Ba,Ca=[],Da=[],Ea=[],Fa=[],Ga=[],ka=0;function Ha(){var a=f.preRun.shift();Ca.unshift(a)}var H=0,Ia=null,I=null;f.preloadedImages={};f.preloadedAudios={};
function z(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";x(a);na=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ja(){return J.startsWith("data:application/octet-stream;base64,")}var J;J="kc852-ui.wasm";if(!Ja()){var Ka=J;J=f.locateFile?f.locateFile(Ka,q):q+Ka}function La(){var a=J;try{if(a==J&&y)return new Uint8Array(y);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Ma(){if(!y&&(ea||l)){if("function"===typeof fetch&&!J.startsWith("file://"))return fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return La()});if(u)return new Promise(function(a,b){u(J,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return La()})}
function K(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Pc;"number"===typeof c?void 0===b.nc?L(c)():L(c)(b.nc):c(void 0===b.nc?null:b.nc)}}}var M=[];function L(a){var b=M[a];b||(a>=M.length&&(M.length=a+1),M[a]=b=Ba.get(a));return b}var Na=[null,[],[]],Oa={},Pa=0;function Qa(){for(var a=N.length-1;0<=a;--a)Ra(a);N=[];Sa=[]}var Sa=[];function Ta(){if(Pa&&Ua.ic)for(var a=0;a<Sa.length;++a){var b=Sa[a];Sa.splice(a,1);--a;b.Xc.apply(null,b.Lc)}}var N=[];
function Ra(a){var b=N[a];b.target.removeEventListener(b.ac,b.Gc,b.bc);N.splice(a,1)}function O(a){function b(d){++Pa;Ua=a;Ta();a.dc(d);Ta();--Pa}if(a.cc)a.Gc=b,a.target.addEventListener(a.ac,b,a.bc),N.push(a),Va||(Fa.push(Qa),Va=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].ac==a.ac&&Ra(c--)}function Wa(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Va,Ua,Xa,Ya,Za,$a,ab,bb,cb,db=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function P(a){a=2<a?D(a):a;return db[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function eb(a){return 0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}var fb;fb=fa?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()};
function gb(a,b,c,d,e,h){Xa||(Xa=Q(256));a={target:P(a),ac:h,cc:d,dc:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Xa;B(Wa(g.target),C,n+0,128);B(m,C,n+128,128);L(d)(e,n,b)&&g.preventDefault()},bc:c};O(a)}
function hb(a,b,c,d,e,h){Ya||(Ya=Q(176));a={target:P(a),ic:!0,ac:h,cc:d,dc:function(g){var m=Ya;G[m>>3]=g.timeStamp;var n=m>>2;E[n+2]=g.location;E[n+3]=g.ctrlKey;E[n+4]=g.shiftKey;E[n+5]=g.altKey;E[n+6]=g.metaKey;E[n+7]=g.repeat;E[n+8]=g.charCode;E[n+9]=g.keyCode;E[n+10]=g.which;B(g.key||"",C,m+44,32);B(g.code||"",C,m+76,32);B(g.char||"",C,m+108,32);B(g.locale||"",C,m+140,32);L(d)(e,m,b)&&g.preventDefault()},bc:c};O(a)}
function ib(a,b,c){G[a>>3]=b.timeStamp;a>>=2;E[a+2]=b.screenX;E[a+3]=b.screenY;E[a+4]=b.clientX;E[a+5]=b.clientY;E[a+6]=b.ctrlKey;E[a+7]=b.shiftKey;E[a+8]=b.altKey;E[a+9]=b.metaKey;xa[2*a+20]=b.button;xa[2*a+21]=b.buttons;E[a+11]=b.movementX;E[a+12]=b.movementY;c=eb(c);E[a+13]=b.clientX-c.left;E[a+14]=b.clientY-c.top}
function R(a,b,c,d,e,h){Za||(Za=Q(72));a=P(a);O({target:a,ic:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ac:h,cc:d,dc:function(g){g=g||event;ib(Za,g,a);L(d)(e,Za,b)&&g.preventDefault()},bc:c})}function jb(a,b,c,d,e){$a||($a=Q(260));O({target:a,ac:e,cc:d,dc:function(h){h=h||event;var g=$a,m=document.pointerLockElement||document.qc||document.sc||document.rc;E[g>>2]=!!m;var n=m&&m.id?m.id:"";B(Wa(m),C,g+4,128);B(n,C,g+132,128);L(d)(20,g,b)&&h.preventDefault()},bc:c})}
function kb(a,b,c,d,e){O({target:a,ac:e,cc:d,dc:function(h){h=h||event;L(d)(38,0,b)&&h.preventDefault()},bc:c})}
function lb(a,b,c,d){ab||(ab=Q(36));a=P(a);O({target:a,ac:"resize",cc:d,dc:function(e){e=e||event;if(e.target==a){var h=document.body;if(h){var g=ab;E[g>>2]=e.detail;E[g+4>>2]=h.clientWidth;E[g+8>>2]=h.clientHeight;E[g+12>>2]=innerWidth;E[g+16>>2]=innerHeight;E[g+20>>2]=outerWidth;E[g+24>>2]=outerHeight;E[g+28>>2]=pageXOffset;E[g+32>>2]=pageYOffset;L(d)(10,g,b)&&e.preventDefault()}}},bc:c})}
function mb(a,b,c,d,e,h){bb||(bb=Q(1696));a=P(a);O({target:a,ic:"touchstart"==h||"touchend"==h,ac:h,cc:d,dc:function(g){for(var m,n={},p=g.touches,r=0;r<p.length;++r)m=p[r],m.vc=m.wc=0,n[m.identifier]=m;for(r=0;r<g.changedTouches.length;++r)m=g.changedTouches[r],m.vc=1,n[m.identifier]=m;for(r=0;r<g.targetTouches.length;++r)n[g.targetTouches[r].identifier].wc=1;p=bb;G[p>>3]=g.timeStamp;var t=p>>2;E[t+3]=g.ctrlKey;E[t+4]=g.shiftKey;E[t+5]=g.altKey;E[t+6]=g.metaKey;t+=7;var rb=eb(a),sb=0;for(r in n)if(m=
n[r],E[t]=m.identifier,E[t+1]=m.screenX,E[t+2]=m.screenY,E[t+3]=m.clientX,E[t+4]=m.clientY,E[t+5]=m.pageX,E[t+6]=m.pageY,E[t+7]=m.vc,E[t+8]=m.wc,E[t+9]=m.clientX-rb.left,E[t+10]=m.clientY-rb.top,t+=13,31<++sb)break;E[p+8>>2]=sb;L(d)(e,p,b)&&g.preventDefault()},bc:c})}function nb(a,b,c,d,e,h){a={target:P(a),ac:h,cc:d,dc:function(g){g=g||event;L(d)(e,0,b)&&g.preventDefault()},bc:c};O(a)}
function ob(a,b,c,d){cb||(cb=Q(104));O({target:a,ic:!0,ac:"wheel",cc:d,dc:function(e){e=e||event;var h=cb;ib(h,e,a);G[h+72>>3]=e.deltaX;G[h+80>>3]=e.deltaY;G[h+88>>3]=e.deltaZ;E[h+96>>2]=e.deltaMode;L(d)(9,h,b)&&e.preventDefault()},bc:c})}
function pb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function qb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function tb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function ub(a){a.Tc=a.getExtension("WEBGL_multi_draw")}
var vb=1,wb=[],S=[],xb=[],T=[],U=[],V=[],yb=[],zb={};function W(a){Ab||(Ab=a)}function Bb(a){for(var b=vb++,c=a.length;c<b;c++)a[c]=null;return b}function Cb(a,b){a.uc||(a.uc=a.getContext,a.getContext=function(d,e){e=a.uc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Db(c,b):0}function Db(a,b){var c=Bb(yb),d={Rc:c,attributes:b,version:b.Jc,mc:a};a.canvas&&(a.canvas.Kc=d);yb[c]=d;("undefined"===typeof b.tc||b.tc)&&Eb(d);return c}
function Eb(a){a||(a=Fb);if(!a.Ic){a.Ic=!0;var b=a.mc;pb(b);qb(b);tb(b);b.Nc=b.getExtension("EXT_disjoint_timer_query");ub(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Ab,Fb,Gb=["default","low-power","high-performance"];function Hb(a,b,c,d){for(var e=0;e<a;e++){var h=X[c](),g=h&&Bb(d);h?(h.name=g,d[g]=h):W(1282);E[b+4*e>>2]=g}}
function Ib(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=X.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=X.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:W(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)E[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){W(1280);x("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:W(1280);x("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}E[b>>2]=c}else W(1281)}function Jb(a){var b=ua(a)+1,c=Q(b);B(a,C,c,b);return c}
function Kb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Lb(a,b,c,d,e){a-=5120;a=1==a?C:4==a?E:6==a?F:5==a||28922==a?za:ya;var h=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(e>>h,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<h)+4-1&-4)>>h)}function Y(a){var b=X.Fc;if(b){var c=b.hc[a];"number"===typeof c&&(b.hc[a]=c=X.getUniformLocation(b,b.Dc[a]+(0<c?"["+c+"]":"")));return c}W(1282)}for(var Z=[],X,Mb=new Float32Array(288),Nb=0;288>Nb;++Nb)Z[Nb]=Mb.subarray(0,Nb+1);
var Yb={ja:function(){return 0},gb:function(){return 0},ib:function(){},eb:function(){z("")},G:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},M:function(a,b,c){a=P(a);if(!a)return-4;a=eb(a);G[b>>3]=a.width;G[c>>3]=a.height;return 0},n:fb,cb:function(a,b,c){C.copyWithin(a,b,b+c)},Ab:function(a,b){function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},db:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+
.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ma.grow(Math.min(2147483648,d)-wa.byteLength+65535>>>16);Aa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},U:function(a,b,c,d){gb(a,b,c,d,12,"blur");return 0},sa:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},V:function(a,b,c,d){gb(a,b,c,d,13,"focus");return 0},ca:function(a,b,c,d){hb(a,b,c,d,2,"keydown");return 0},aa:function(a,b,c,d){hb(a,b,c,d,1,"keypress");return 0},ba:function(a,
b,c,d){hb(a,b,c,d,3,"keyup");return 0},ia:function(a,b,c,d){R(a,b,c,d,5,"mousedown");return 0},fa:function(a,b,c,d){R(a,b,c,d,33,"mouseenter");return 0},ea:function(a,b,c,d){R(a,b,c,d,34,"mouseleave");return 0},ga:function(a,b,c,d){R(a,b,c,d,8,"mousemove");return 0},ha:function(a,b,c,d){R(a,b,c,d,6,"mouseup");return 0},X:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.qc||document.body.sc||document.body.rc))return-1;a=P(a);if(!a)return-4;jb(a,b,c,
d,"pointerlockchange");jb(a,b,c,d,"mozpointerlockchange");jb(a,b,c,d,"webkitpointerlockchange");jb(a,b,c,d,"mspointerlockchange");return 0},W:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.qc||document.body.sc||document.body.rc))return-1;a=P(a);if(!a)return-4;kb(a,b,c,d,"pointerlockerror");kb(a,b,c,d,"mozpointerlockerror");kb(a,b,c,d,"webkitpointerlockerror");kb(a,b,c,d,"mspointerlockerror");return 0},Ea:function(a,b,c,d){lb(a,b,c,d);return 0},Y:function(a,b,c,d){mb(a,
b,c,d,25,"touchcancel");return 0},Z:function(a,b,c,d){mb(a,b,c,d,23,"touchend");return 0},_:function(a,b,c,d){mb(a,b,c,d,24,"touchmove");return 0},$:function(a,b,c,d){mb(a,b,c,d,22,"touchstart");return 0},T:function(a,b,c,d){nb(a,b,c,d,31,"webglcontextlost");return 0},S:function(a,b,c,d){nb(a,b,c,d,32,"webglcontextrestored");return 0},da:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(ob(a,b,c,d),0):-1},la:function(a,b){b>>=2;b={alpha:!!E[b],depth:!!E[b+1],stencil:!!E[b+2],antialias:!!E[b+
3],premultipliedAlpha:!!E[b+4],preserveDrawingBuffer:!!E[b+5],powerPreference:Gb[E[b+6]],failIfMajorPerformanceCaveat:!!E[b+7],Jc:E[b+8],Sc:E[b+9],tc:E[b+10],Hc:E[b+11],Uc:E[b+12],Vc:E[b+13]};a=P(a);return!a||b.Hc?0:Cb(a,b)},$a:function(a,b){a=yb[a];b=D(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&pb(X);"OES_vertex_array_object"==b&&qb(X);"WEBGL_draw_buffers"==b&&tb(X);"WEBGL_multi_draw"==b&&ub(X);return!!a.mc.getExtension(b)},qb:function(a){a>>=2;for(var b=0;14>b;++b)E[a+
b]=0;E[a]=E[a+1]=E[a+3]=E[a+4]=E[a+8]=E[a+10]=1},bb:function(a){Fb=yb[a];f.Mc=X=Fb&&Fb.mc;return!a||X?0:-5},ka:function(){return 0},fb:function(a,b,c,d){a=Oa.Qc(a);b=Oa.Oc(a,b,c);E[d>>2]=b;return 0},ab:function(){},hb:function(a,b,c,d){for(var e=0,h=0;h<c;h++){var g=E[b>>2],m=E[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=C[g+n],r=Na[a];0===p||10===p?((1===a?la:x)(ta(r,0)),r.length=0):r.push(p)}e+=m}E[d>>2]=e;return 0},b:function(a){X.activeTexture(a)},I:function(a,b){X.attachShader(S[a],V[b])},c:function(a,
b){X.bindBuffer(a,wb[b])},g:function(a,b){X.bindFramebuffer(a,xb[b])},Ga:function(a,b){X.bindRenderbuffer(a,T[b])},a:function(a,b){X.bindTexture(a,U[b])},N:function(a,b,c,d){X.blendColor(a,b,c,d)},O:function(a,b){X.blendEquationSeparate(a,b)},P:function(a,b,c,d){X.blendFuncSeparate(a,b,c,d)},Ia:function(a,b,c,d){X.bufferData(a,c?C.subarray(c,c+b):b,d)},k:function(a,b,c,d){X.bufferSubData(a,b,C.subarray(d,d+c))},t:function(a){return X.checkFramebufferStatus(a)},Bb:function(a){X.clear(a)},Db:function(a,
b,c,d){X.clearColor(a,b,c,d)},ra:function(a){X.clearDepth(a)},Cb:function(a){X.clearStencil(a)},q:function(a,b,c,d){X.colorMask(!!a,!!b,!!c,!!d)},va:function(a){X.compileShader(V[a])},Ca:function(a,b,c,d,e,h,g,m){X.compressedTexImage2D(a,b,c,d,e,h,m?C.subarray(m,m+g):null)},Aa:function(){var a=Bb(S),b=X.createProgram();b.name=a;b.lc=b.jc=b.kc=0;b.pc=1;S[a]=b;return a},xa:function(a){var b=Bb(V);V[b]=X.createShader(a);return b},J:function(a){X.cullFace(a)},Oa:function(a,b){for(var c=0;c<a;c++){var d=
E[b+4*c>>2],e=wb[d];e&&(X.deleteBuffer(e),e.name=0,wb[d]=null)}},d:function(a,b){for(var c=0;c<a;++c){var d=E[b+4*c>>2],e=xb[d];e&&(X.deleteFramebuffer(e),e.name=0,xb[d]=null)}},r:function(a){if(a){var b=S[a];b?(X.deleteProgram(b),b.name=0,S[a]=null):W(1281)}},R:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=T[d];e&&(X.deleteRenderbuffer(e),e.name=0,T[d]=null)}},y:function(a){if(a){var b=V[a];b?(X.deleteShader(b),V[a]=null):W(1281)}},Na:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],
e=U[d];e&&(X.deleteTexture(e),e.name=0,U[d]=null)}},B:function(a){X.depthFunc(a)},A:function(a){X.depthMask(!!a)},e:function(a){X.disable(a)},Q:function(a){X.disableVertexAttribArray(a)},nb:function(a,b,c){X.drawArrays(a,b,c)},ob:function(a,b,c,d){X.drawArraysInstanced(a,b,c,d)},pb:function(a,b,c,d){X.drawElements(a,b,c,d)},rb:function(a,b,c,d,e){X.drawElementsInstanced(a,b,c,d,e)},i:function(a){X.enable(a)},xb:function(a){X.enableVertexAttribArray(a)},o:function(a,b,c,d){X.framebufferRenderbuffer(a,
b,c,T[d])},h:function(a,b,c,d,e){X.framebufferTexture2D(a,b,c,U[d],e)},K:function(a){X.frontFace(a)},Ja:function(a,b){Hb(a,b,"createBuffer",wb)},p:function(a,b){Hb(a,b,"createFramebuffer",xb)},Ha:function(a,b){Hb(a,b,"createRenderbuffer",T)},Da:function(a,b){Hb(a,b,"createTexture",U)},ta:function(a,b){return X.getAttribLocation(S[a],D(b))},f:function(a,b){Ib(a,b)},ya:function(a,b,c,d){a=X.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,C,d,b):0;c&&(E[c>>2]=b)},H:function(a,b,
c){if(c)if(a>=vb)W(1281);else if(a=S[a],35716==b)a=X.getProgramInfoLog(a),null===a&&(a="(unknown error)"),E[c>>2]=a.length+1;else if(35719==b){if(!a.lc)for(b=0;b<X.getProgramParameter(a,35718);++b)a.lc=Math.max(a.lc,X.getActiveUniform(a,b).name.length+1);E[c>>2]=a.lc}else if(35722==b){if(!a.jc)for(b=0;b<X.getProgramParameter(a,35721);++b)a.jc=Math.max(a.jc,X.getActiveAttrib(a,b).name.length+1);E[c>>2]=a.jc}else if(35381==b){if(!a.kc)for(b=0;b<X.getProgramParameter(a,35382);++b)a.kc=Math.max(a.kc,
X.getActiveUniformBlockName(a,b).length+1);E[c>>2]=a.kc}else E[c>>2]=X.getProgramParameter(a,b);else W(1281)},ua:function(a,b,c,d){a=X.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,C,d,b):0;c&&(E[c>>2]=b)},E:function(a,b,c){c?35716==b?(a=X.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),E[c>>2]=a?a.length+1:0):35720==b?(a=X.getShaderSource(V[a]),E[c>>2]=a?a.length+1:0):E[c>>2]=X.getShaderParameter(V[a],b):W(1281)},Pa:function(a){var b=zb[a];if(!b){switch(a){case 7939:b=
X.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Jb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=X.getParameter(a))||W(1280);b=b&&Jb(b);break;case 7938:b=Jb("OpenGL ES 2.0 ("+X.getParameter(7938)+")");break;case 35724:b=X.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Jb(b);break;default:W(1280)}zb[a]=b}return b},u:function(a,b){b=D(b);
if(a=S[a]){var c=a,d=c.hc,e=c.Ec,h;if(!d)for(c.hc=d={},c.Dc={},h=0;h<X.getProgramParameter(c,35718);++h){var g=X.getActiveUniform(c,h);var m=g.name;g=g.size;var n=Kb(m);n=0<n?m.slice(0,n):m;var p=c.pc;c.pc+=g;e[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.Dc[p++]=n}c=a.hc;d=0;e=b;h=Kb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Ec[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||X.getUniformLocation(a,b)))return d}else W(1281);return-1},za:function(a){a=S[a];X.linkProgram(a);a.hc=0;a.Ec={}},L:function(a,b){X.polygonOffset(a,
b)},Fa:function(a,b,c,d){X.renderbufferStorage(a,b,c,d)},s:function(a,b,c,d){X.scissor(a,b,c,d)},wa:function(a,b,c,d){for(var e="",h=0;h<b;++h){var g=d?E[d+4*h>>2]:-1;e+=D(E[c+4*h>>2],0>g?void 0:g)}X.shaderSource(V[a],e)},La:function(a,b,c){X.stencilFunc(a,b,c)},qa:function(a,b,c,d){X.stencilFuncSeparate(a,b,c,d)},z:function(a){X.stencilMask(a)},Ka:function(a,b,c){X.stencilOp(a,b,c)},pa:function(a,b,c,d){X.stencilOpSeparate(a,b,c,d)},Ba:function(a,b,c,d,e,h,g,m,n){X.texImage2D(a,b,c,d,e,h,g,m,n?Lb(m,
g,d,e,n):null)},j:function(a,b,c){X.texParameteri(a,b,c)},mb:function(a,b,c,d,e,h,g,m,n){var p=null;n&&(p=Lb(m,g,e,h,n));X.texSubImage2D(a,b,c,d,e,h,g,m,p)},wb:function(a,b,c){if(288>=b)for(var d=Z[b-1],e=0;e<b;++e)d[e]=F[c+4*e>>2];else d=F.subarray(c>>2,c+4*b>>2);X.uniform1fv(Y(a),d)},F:function(a,b){X.uniform1i(Y(a),b)},vb:function(a,b,c){if(144>=b)for(var d=Z[2*b-1],e=0;e<2*b;e+=2)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2];else d=F.subarray(c>>2,c+8*b>>2);X.uniform2fv(Y(a),d)},ub:function(a,b,c){if(96>=
b)for(var d=Z[3*b-1],e=0;e<3*b;e+=3)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2];else d=F.subarray(c>>2,c+12*b>>2);X.uniform3fv(Y(a),d)},tb:function(a,b,c){if(72>=b){var d=Z[4*b-1],e=F;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=F.subarray(c>>2,c+16*b>>2);X.uniform4fv(Y(a),d)},sb:function(a,b,c,d){if(18>=b){var e=Z[16*b-1],h=F;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+
4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=h[m+13];e[g+14]=h[m+14];e[g+15]=h[m+15]}}else e=F.subarray(d>>2,d+64*b>>2);X.uniformMatrix4fv(Y(a),!!c,e)},l:function(a){a=S[a];X.useProgram(a);X.Fc=a},yb:function(a,b){X.vertexAttribDivisor(a,b)},zb:function(a,b,c,d,e,h){X.vertexAttribPointer(a,b,c,!!d,e,h)},m:function(a,b,c,d){X.viewport(a,b,c,d)},Za:function(){f.xc=function(a){0!=Ob()&&(a.preventDefault(),a.returnValue=
" ")};window.addEventListener("beforeunload",f.xc)},Ya:function(){f.Cc=function(a){a=a.clipboardData.getData("text");oa("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",f.Cc)},Xa:function(a){f.Wc=[];a=D(a);a=document.getElementById(a);f.yc=function(b){b.stopPropagation();b.preventDefault()};f.zc=function(b){b.stopPropagation();b.preventDefault()};f.Ac=function(b){b.stopPropagation();b.preventDefault()};f.Bc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;
f.oc=c;Pb(c.length);var d;for(d=0;d<c.length;d++)oa("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Qb(b.clientX,b.clientY)};a.addEventListener("dragenter",f.yc,!1);a.addEventListener("dragleave",f.zc,!1);a.addEventListener("dragover",f.Ac,!1);a.addEventListener("drop",f.Bc,!1)},Ra:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},x:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";
a.addEventListener("focusout",function(){Rb()});document.body.append(a)},Fb:function(a){return 0>a||a>=f.oc.length?0:f.oc[a].size},Eb:function(a,b,c,d,e){var h=new FileReader;h.onload=function(g){g=g.target.result;g.byteLength>d?Sb(a,0,1,b,0,c,d,e):(C.set(new Uint8Array(g),c),Sb(a,1,0,b,g.byteLength,c,d,e))};h.onerror=function(){Sb(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(f.oc[a])},w:function(){document.getElementById("_sokol_app_input_element").focus()},Ma:function(a){a=D(a);f.fc=document.getElementById(a);
f.fc||console.log("sokol_app.h: invalid target:"+a);f.fc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Va:function(){window.removeEventListener("beforeunload",f.xc)},Ua:function(){window.removeEventListener("paste",f.Cc)},Ta:function(a){a=D(a);a=document.getElementById(a);a.removeEventListener("dragenter",f.yc);a.removeEventListener("dragleave",f.zc);a.removeEventListener("dragover",f.Ac);a.removeEventListener("drop",f.Bc)},D:function(){f.fc&&f.fc.requestPointerLock&&
f.fc.requestPointerLock()},Qa:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(C.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},v:function(){document.getElementById("_sokol_app_input_element").blur()},Sa:function(a){a=D(a);var b=document.createElement("textarea");b.setAttribute("autocomplete",
"off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},Wa:function(){for(var a=(new URLSearchParams(window.location.search)).entries(),b=a.next();!b.done;b=a.next())oa("_sargs_add_kvp",["string","string"],[b.value[0],b.value[1]])},jb:function(){return f.ec?
f.ec.bufferSize:0},lb:function(a,b,c){f.$b=null;f.ec=null;"undefined"!==typeof AudioContext?f.$b=new AudioContext({sampleRate:a,latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?f.$b=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(f.$b=null,console.log("sokol_audio.h: no WebAudio support"));return f.$b?(console.log("sokol_audio.h: sample rate ",f.$b.sampleRate),f.ec=f.$b.createScriptProcessor(c,0,b),f.ec.onaudioprocess=function(d){var e=d.outputBuffer.length,h=
Tb(e);if(h)for(var g=d.outputBuffer.numberOfChannels,m=0;m<g;m++)for(var n=d.outputBuffer.getChannelData(m),p=0;p<e;p++)n[p]=F[(h>>2)+(g*p+m)]},f.ec.connect(f.$b.destination),a=function(){f.$b&&"suspended"===f.$b.state&&f.$b.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},kb:function(){return f.$b?f.$b.sampleRate:0},oa:function(){null!==f.$b&&(f.ec&&f.ec.disconnect(),f.$b.close(),f.$b=
null,f.ec=null)},_a:function(){if(f.$b)return"suspended"===f.$b.state?1:0},C:function(a,b,c,d,e,h){b=D(b);var g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";var m=0<d;m&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(this.readyState==this.DONE)if(206==this.status||200==this.status&&!m){var n=new Uint8Array(g.response),p=n.length;p<=h?(C.set(n,e),Ub(a,d,p)):Vb(a)}else Wb(a,this.status)};g.send()},na:function(a,b){b=D(b);var c=new XMLHttpRequest;
c.open("HEAD",b);c.onreadystatechange=function(){if(this.readyState==this.DONE)if(200==this.status){var d=this.getResponseHeader("Content-Length");Xb(a,d)}else Wb(a,this.status)};c.send()},ma:function(){return navigator.userAgent.includes("Macintosh")?1:0}};
(function(){function a(e){f.asm=e.exports;ma=f.asm.Gb;Aa();Ba=f.asm._b;Da.unshift(f.asm.Hb);H--;f.monitorRunDependencies&&f.monitorRunDependencies(H);0==H&&(null!==Ia&&(clearInterval(Ia),Ia=null),I&&(e=I,I=null,e()))}function b(e){a(e.instance)}function c(e){return Ma().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(e,function(h){x("failed to asynchronously prepare wasm: "+h);z(h)})}var d={a:Yb};H++;f.monitorRunDependencies&&f.monitorRunDependencies(H);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return x("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return y||"function"!==typeof WebAssembly.instantiateStreaming||Ja()||J.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(h){x("wasm streaming compile failed: "+h);x("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.Hb).apply(null,arguments)};var Rb=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Rb=f.__sapp_emsc_notify_keyboard_hidden=f.asm.Ib).apply(null,arguments)};f.__sapp_emsc_onpaste=function(){return(f.__sapp_emsc_onpaste=f.asm.Jb).apply(null,arguments)};
var Ob=f.__sapp_html5_get_ask_leave_site=function(){return(Ob=f.__sapp_html5_get_ask_leave_site=f.asm.Kb).apply(null,arguments)},Pb=f.__sapp_emsc_begin_drop=function(){return(Pb=f.__sapp_emsc_begin_drop=f.asm.Lb).apply(null,arguments)};f.__sapp_emsc_drop=function(){return(f.__sapp_emsc_drop=f.asm.Mb).apply(null,arguments)};
var Qb=f.__sapp_emsc_end_drop=function(){return(Qb=f.__sapp_emsc_end_drop=f.asm.Nb).apply(null,arguments)},Sb=f.__sapp_emsc_invoke_fetch_cb=function(){return(Sb=f.__sapp_emsc_invoke_fetch_cb=f.asm.Ob).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Pb).apply(null,arguments)};var Tb=f.__saudio_emsc_pull=function(){return(Tb=f.__saudio_emsc_pull=f.asm.Qb).apply(null,arguments)};f.__sargs_add_kvp=function(){return(f.__sargs_add_kvp=f.asm.Rb).apply(null,arguments)};
var Xb=f.__sfetch_emsc_head_response=function(){return(Xb=f.__sfetch_emsc_head_response=f.asm.Sb).apply(null,arguments)},Ub=f.__sfetch_emsc_get_response=function(){return(Ub=f.__sfetch_emsc_get_response=f.asm.Tb).apply(null,arguments)},Wb=f.__sfetch_emsc_failed_http_status=function(){return(Wb=f.__sfetch_emsc_failed_http_status=f.asm.Ub).apply(null,arguments)},Vb=f.__sfetch_emsc_failed_buffer_too_small=function(){return(Vb=f.__sfetch_emsc_failed_buffer_too_small=f.asm.Vb).apply(null,arguments)},Q=
f._malloc=function(){return(Q=f._malloc=f.asm.Wb).apply(null,arguments)},qa=f.stackSave=function(){return(qa=f.stackSave=f.asm.Xb).apply(null,arguments)},ra=f.stackRestore=function(){return(ra=f.stackRestore=f.asm.Yb).apply(null,arguments)},A=f.stackAlloc=function(){return(A=f.stackAlloc=f.asm.Zb).apply(null,arguments)},Zb;function w(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}I=function $b(){Zb||ac();Zb||(I=$b)};
function ac(a){function b(){if(!Zb&&(Zb=!0,f.calledRun=!0,!na)){K(Da);K(Ea);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(bc){var c=a,d=f._main;c=c||[];var e=c.length+1,h=A(4*(e+1));E[h>>2]=va(da);for(var g=1;g<e;g++)E[(h>>2)+g]=va(c[g-1]);E[(h>>2)+e]=0;try{var m=d(e,h);if(!(noExitRuntime||0<ka)){if(f.onExit)f.onExit(m);na=!0}k(m,new w(m))}catch(n){n instanceof w||"unwind"==n||k(1,n)}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),
Ga.unshift(c);K(Ga)}}a=a||ca;if(!(0<H)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ha();K(Ca);0<H||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=ac;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var bc=!0;f.noInitialRun&&(bc=!1);ac();
