var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=[],ca="./this.program",k=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,r="",fa,t,v;
if(ea){var fs=require("fs"),ha=require("path");r=l?ha.dirname(r)+"/":__dirname+"/";fa=(a,b)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};t=(a,b,c)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})};!f.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=
f);process.on("uncaughtException",function(a){if(!("unwind"===a||a instanceof w||a.context instanceof w))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",function(a){throw a;});k=(a,b)=>{process.exitCode=a;throw b;};f.inspect=function(){return"[Emscripten Module object]"}}else if(da||l)l?r=self.location.href:"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src),r=0!==r.indexOf("blob:")?r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+
1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),t=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};f.print||console.log.bind(console);var x=f.printErr||console.warn.bind(console);
Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);f.thisProgram&&(ca=f.thisProgram);f.quit&&(k=f.quit);var y;f.wasmBinary&&(y=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&z("no native wasm support detected");var ia,ja=!1,A,ka,la,B,ma,C,D;
function na(){var a=ia.buffer;f.HEAP8=new Int8Array(a);f.HEAP16=ka=new Int16Array(a);f.HEAP32=B=new Int32Array(a);f.HEAPU8=A=new Uint8Array(a);f.HEAPU16=la=new Uint16Array(a);f.HEAPU32=ma=new Uint32Array(a);f.HEAPF32=C=new Float32Array(a);f.HEAPF64=D=new Float64Array(a)}var oa,pa=[],qa=[],ra=[],sa=[],ta=[];function ua(){var a=f.preRun.shift();pa.unshift(a)}var E=0,va=null,F=null;
function z(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";x(a);ja=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function wa(a){return a.startsWith("data:application/octet-stream;base64,")}var G;G="kc852.wasm";if(!wa(G)){var xa=G;G=f.locateFile?f.locateFile(xa,r):r+xa}function ya(a){try{if(a==G&&y)return new Uint8Array(y);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function za(a){if(!y&&(da||l)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return ya(a)});if(t)return new Promise(function(b,c){t(a,function(d){b(new Uint8Array(d))},c)})}return Promise.resolve().then(function(){return ya(a)})}
function Aa(a,b,c){return za(a).then(function(d){return WebAssembly.instantiate(d,b)}).then(function(d){return d}).then(c,function(d){x("failed to asynchronously prepare wasm: "+d);z(d)})}
function Ba(a,b){var c=G;y||"function"!=typeof WebAssembly.instantiateStreaming||wa(c)||c.startsWith("file://")||ea||"function"!=typeof fetch?Aa(c,a,b):fetch(c,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,a).then(b,function(e){x("wasm streaming compile failed: "+e);x("falling back to ArrayBuffer instantiation");return Aa(c,a,b)})})}function w(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Ca(a){for(;0<a.length;)a.shift()(f)}function Da(a){var b=Ea();a();Fa(b)}var Ga=0;function Ha(){for(var a=H.length-1;0<=a;--a)Ia(a);H=[];Ja=[]}var Ja=[];function Ka(){if(Ga&&La.jc)for(var a=0;a<Ja.length;++a){var b=Ja[a];Ja.splice(a,1);--a;b.Sc.apply(null,b.Jc)}}var H=[];function Ia(a){var b=H[a];b.target.removeEventListener(b.ac,b.Ec,b.bc);H.splice(a,1)}
function I(a){function b(d){++Ga;La=a;Ka();a.dc(d);Ka();--Ga}if(a.cc)a.Ec=b,a.target.addEventListener(a.ac,b,a.bc),H.push(a),Ma||(sa.push(Ha),Ma=!0);else for(var c=0;c<H.length;++c)H[c].target==a.target&&H[c].ac==a.ac&&Ia(c--)}function Na(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var Ma,La,Oa,Pa,Qa,Ra,Sa,Ta,Ua,Va="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function J(a,b){if(a){var c=A,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&Va)a=Va.decode(c.subarray(a,b));else{for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}a=d}}else a="";return a}
var Wa=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];function K(a){a=2<a?J(a):a;return Wa[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function Xa(a){return 0>Wa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}var Ya;Ya=ea?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var Za=[];function L(a){var b=Za[a];b||(a>=Za.length&&(Za.length=a+1),Za[a]=b=oa.get(a));return b}
function M(a,b,c){var d=A;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e}
function $a(a,b,c,d,e,h){Oa||(Oa=N(256));a={target:K(a),ac:h,cc:d,dc:function(g=event){var m=g.target.id?g.target.id:"",n=Oa;M(Na(g.target),n+0,128);M(m,n+128,128);L(d)(e,n,b)&&g.preventDefault()},bc:c};I(a)}
function ab(a,b,c,d,e,h){Pa||(Pa=N(176));a={target:K(a),jc:!0,ac:h,cc:d,dc:function(g){var m=Pa;D[m>>3]=g.timeStamp;var n=m>>2;B[n+2]=g.location;B[n+3]=g.ctrlKey;B[n+4]=g.shiftKey;B[n+5]=g.altKey;B[n+6]=g.metaKey;B[n+7]=g.repeat;B[n+8]=g.charCode;B[n+9]=g.keyCode;B[n+10]=g.which;M(g.key||"",m+44,32);M(g.code||"",m+76,32);M(g.char||"",m+108,32);M(g.locale||"",m+140,32);L(d)(e,m,b)&&g.preventDefault()},bc:c};I(a)}
function bb(a,b,c){D[a>>3]=b.timeStamp;a>>=2;B[a+2]=b.screenX;B[a+3]=b.screenY;B[a+4]=b.clientX;B[a+5]=b.clientY;B[a+6]=b.ctrlKey;B[a+7]=b.shiftKey;B[a+8]=b.altKey;B[a+9]=b.metaKey;ka[2*a+20]=b.button;ka[2*a+21]=b.buttons;B[a+11]=b.movementX;B[a+12]=b.movementY;c=Xa(c);B[a+13]=b.clientX-c.left;B[a+14]=b.clientY-c.top}
function O(a,b,c,d,e,h){Qa||(Qa=N(72));a=K(a);I({target:a,jc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ac:h,cc:d,dc:function(g=event){bb(Qa,g,a);L(d)(e,Qa,b)&&g.preventDefault()},bc:c})}function cb(a,b,c,d,e){Ra||(Ra=N(260));I({target:a,ac:e,cc:d,dc:function(h=event){var g=Ra,m=document.pointerLockElement||document.fc||document.qc||document.pc;B[g>>2]=!!m;var n=m&&m.id?m.id:"";M(Na(m),g+4,128);M(n,g+132,128);L(d)(20,g,b)&&h.preventDefault()},bc:c})}
function db(a,b,c,d,e){I({target:a,ac:e,cc:d,dc:function(h=event){L(d)(38,0,b)&&h.preventDefault()},bc:c})}function eb(a,b,c,d){Sa||(Sa=N(36));a=K(a);I({target:a,ac:"resize",cc:d,dc:function(e=event){if(e.target==a){var h=document.body;if(h){var g=Sa;B[g>>2]=e.detail;B[g+4>>2]=h.clientWidth;B[g+8>>2]=h.clientHeight;B[g+12>>2]=innerWidth;B[g+16>>2]=innerHeight;B[g+20>>2]=outerWidth;B[g+24>>2]=outerHeight;B[g+28>>2]=pageXOffset;B[g+32>>2]=pageYOffset;L(d)(10,g,b)&&e.preventDefault()}}},bc:c})}
function fb(a,b,c,d,e,h){Ta||(Ta=N(1696));a=K(a);I({target:a,jc:"touchstart"==h||"touchend"==h,ac:h,cc:d,dc:function(g){for(var m,n={},p=g.touches,u=0;u<p.length;++u)m=p[u],m.sc=m.tc=0,n[m.identifier]=m;for(u=0;u<g.changedTouches.length;++u)m=g.changedTouches[u],m.sc=1,n[m.identifier]=m;for(u=0;u<g.targetTouches.length;++u)n[g.targetTouches[u].identifier].tc=1;p=Ta;D[p>>3]=g.timeStamp;var q=p>>2;B[q+3]=g.ctrlKey;B[q+4]=g.shiftKey;B[q+5]=g.altKey;B[q+6]=g.metaKey;q+=7;var kb=Xa(a),lb=0;for(u in n)if(m=
n[u],B[q]=m.identifier,B[q+1]=m.screenX,B[q+2]=m.screenY,B[q+3]=m.clientX,B[q+4]=m.clientY,B[q+5]=m.pageX,B[q+6]=m.pageY,B[q+7]=m.sc,B[q+8]=m.tc,B[q+9]=m.clientX-kb.left,B[q+10]=m.clientY-kb.top,q+=13,31<++lb)break;B[p+8>>2]=lb;L(d)(e,p,b)&&g.preventDefault()},bc:c})}function gb(a,b,c,d,e,h){a={target:K(a),ac:h,cc:d,dc:function(g=event){L(d)(e,0,b)&&g.preventDefault()},bc:c};I(a)}
function hb(a,b,c,d){Ua||(Ua=N(104));I({target:a,jc:!0,ac:"wheel",cc:d,dc:function(e=event){var h=Ua;bb(h,e,a);D[h+72>>3]=e.deltaX;D[h+80>>3]=e.deltaY;D[h+88>>3]=e.deltaZ;B[h+96>>2]=e.deltaMode;L(d)(9,h,b)&&e.preventDefault()},bc:c})}
function ib(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function jb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function mb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function nb(a){a.Oc=a.getExtension("WEBGL_multi_draw")}
var ob=1,pb=[],P=[],qb=[],Q=[],R=[],S=[],rb=[],sb={},tb=4;function T(a){ub||(ub=a)}function vb(a){for(var b=ob++,c=a.length;c<b;c++)a[c]=null;return b}function wb(a,b){a.fc||(a.fc=a.getContext,a.getContext=function(d,e){e=a.fc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?xb(c,b):0}function xb(a,b){var c=vb(rb),d={Mc:c,attributes:b,version:b.Hc,nc:a};a.canvas&&(a.canvas.Ic=d);rb[c]=d;("undefined"==typeof b.rc||b.rc)&&yb(d);return c}
function yb(a){a||(a=zb);if(!a.Gc){a.Gc=!0;var b=a.nc;ib(b);jb(b);mb(b);b.Lc=b.getExtension("EXT_disjoint_timer_query");nb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var ub,zb,Ab=["default","low-power","high-performance"];function Bb(a,b,c,d){for(var e=0;e<a;e++){var h=U[c](),g=h&&vb(d);h?(h.name=g,d[g]=h):T(1282);B[b+4*e>>2]=g}}
function Cb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=U.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=U.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:T(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)B[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T(1280);x("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:T(1280);x("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}B[b>>2]=c}else T(1281)}
function Db(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}function Eb(a){var b=Db(a)+1,c=N(b);c&&M(a,c,b);return c}function Fb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Gb(a,b,c,d,e){a-=5120;a=1==a?A:4==a?B:6==a?C:5==a||28922==a?ma:la;var h=31-Math.clz32(a.BYTES_PER_ELEMENT),g=tb;return a.subarray(e>>h,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<h)+g-1&-g)>>h)}
function V(a){var b=U.Dc;if(b){var c=b.ic[a];"number"==typeof c&&(b.ic[a]=c=U.getUniformLocation(b,b.Bc[a]+(0<c?"["+c+"]":"")));return c}T(1282)}var W=[],X=[];function Hb(a){if(!noExitRuntime){if(f.onExit)f.onExit(a);ja=!0}k(a,new w(a))}function Y(a){var b=Db(a)+1,c=Ib(b);M(a,c,b);return c}for(var U,Jb=new Float32Array(288),Z=0;288>Z;++Z)W[Z]=Jb.subarray(0,Z+1);var Kb=new Int32Array(288);for(Z=0;288>Z;++Z)X[Z]=Kb.subarray(0,Z+1);
var Yb={j:function(){z("")},ia:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},ja:function(a,b,c){a=K(a);if(!a)return-4;a=Xa(a);D[b>>3]=a.width;D[c>>3]=a.height;return 0},C:Ya,bb:function(a,b,c){A.copyWithin(a,b,b+c)},Ta:function(a,b){function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ab:function(a){var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,h=e.min;d=Math.max(a,
d);d+=(65536-d%65536)%65536;a:{var g=ia.buffer;try{ia.grow(h.call(e,2147483648,d)-g.byteLength+65535>>>16);na();var m=1;break a}catch(n){}m=void 0}if(m)return!0}return!1},R:function(a,b,c,d){$a(a,b,c,d,12,"blur");return 0},ha:function(a,b,c){a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},S:function(a,b,c,d){$a(a,b,c,d,13,"focus");return 0},$:function(a,b,c,d){ab(a,b,c,d,2,"keydown");return 0},Z:function(a,b,c,d){ab(a,b,c,d,1,"keypress");return 0},_:function(a,b,c,d){ab(a,b,c,d,3,"keyup");return 0},
fa:function(a,b,c,d){O(a,b,c,d,5,"mousedown");return 0},ca:function(a,b,c,d){O(a,b,c,d,33,"mouseenter");return 0},ba:function(a,b,c,d){O(a,b,c,d,34,"mouseleave");return 0},da:function(a,b,c,d){O(a,b,c,d,8,"mousemove");return 0},ea:function(a,b,c,d){O(a,b,c,d,6,"mouseup");return 0},U:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.fc||document.body.qc||document.body.pc))return-1;a=K(a);if(!a)return-4;cb(a,b,c,d,"pointerlockchange");cb(a,b,c,d,"mozpointerlockchange");
cb(a,b,c,d,"webkitpointerlockchange");cb(a,b,c,d,"mspointerlockchange");return 0},T:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.fc||document.body.qc||document.body.pc))return-1;a=K(a);if(!a)return-4;db(a,b,c,d,"pointerlockerror");db(a,b,c,d,"mozpointerlockerror");db(a,b,c,d,"webkitpointerlockerror");db(a,b,c,d,"mspointerlockerror");return 0},Va:function(a,b,c,d){eb(a,b,c,d);return 0},V:function(a,b,c,d){fb(a,b,c,d,25,"touchcancel");return 0},W:function(a,b,c,
d){fb(a,b,c,d,23,"touchend");return 0},X:function(a,b,c,d){fb(a,b,c,d,24,"touchmove");return 0},Y:function(a,b,c,d){fb(a,b,c,d,22,"touchstart");return 0},Q:function(a,b,c,d){gb(a,b,c,d,31,"webglcontextlost");return 0},P:function(a,b,c,d){gb(a,b,c,d,32,"webglcontextrestored");return 0},aa:function(a,b,c,d){a=K(a);return"undefined"!=typeof a.onwheel?(hb(a,b,c,d),0):-1},ga:function(a,b){b>>=2;b={alpha:!!B[b],depth:!!B[b+1],stencil:!!B[b+2],antialias:!!B[b+3],premultipliedAlpha:!!B[b+4],preserveDrawingBuffer:!!B[b+
5],powerPreference:Ab[B[b+6]],failIfMajorPerformanceCaveat:!!B[b+7],Hc:B[b+8],Nc:B[b+9],rc:B[b+10],Fc:B[b+11],Pc:B[b+12],Qc:B[b+13]};a=K(a);return!a||b.Fc?0:wb(a,b)},Qa:function(a,b){a=rb[a];b=J(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&ib(U);"OES_vertex_array_object"==b&&jb(U);"WEBGL_draw_buffers"==b&&mb(U);"WEBGL_multi_draw"==b&&nb(U);return!!a.nc.getExtension(b)},Sa:function(a){a>>=2;for(var b=0;14>b;++b)B[a+b]=0;B[a]=B[a+1]=B[a+3]=B[a+4]=B[a+8]=B[a+10]=1},Ra:function(a){zb=
rb[a];f.Kc=U=zb&&zb.nc;return!a||U?0:-5},f:function(a){U.activeTexture(a)},G:function(a,b){U.attachShader(P[a],S[b])},b:function(a,b){U.bindBuffer(a,pb[b])},h:function(a,b){U.bindFramebuffer(a,qb[b])},Ba:function(a,b){U.bindRenderbuffer(a,Q[b])},a:function(a,b){U.bindTexture(a,R[b])},K:function(a,b,c,d){U.blendColor(a,b,c,d)},L:function(a,b){U.blendEquationSeparate(a,b)},M:function(a,b,c,d){U.blendFuncSeparate(a,b,c,d)},Da:function(a,b,c,d){U.bufferData(a,c?A.subarray(c,c+b):b,d)},r:function(a,b,
c,d){U.bufferSubData(a,b,A.subarray(d,d+c))},o:function(a){return U.checkFramebufferStatus(a)},ub:function(a){U.clear(a)},wb:function(a,b,c,d){U.clearColor(a,b,c,d)},pa:function(a){U.clearDepth(a)},vb:function(a){U.clearStencil(a)},m:function(a,b,c,d){U.colorMask(!!a,!!b,!!c,!!d)},Ab:function(a){U.compileShader(S[a])},ya:function(a,b,c,d,e,h,g,m){U.compressedTexImage2D(a,b,c,d,e,h,m?A.subarray(m,m+g):null)},va:function(){var a=vb(P),b=U.createProgram();b.name=a;b.mc=b.kc=b.lc=0;b.oc=1;P[a]=b;return a},
sa:function(a){var b=vb(S);S[b]=U.createShader(a);return b},H:function(a){U.cullFace(a)},Ma:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=pb[d];e&&(U.deleteBuffer(e),e.name=0,pb[d]=null)}},c:function(a,b){for(var c=0;c<a;++c){var d=B[b+4*c>>2],e=qb[d];e&&(U.deleteFramebuffer(e),e.name=0,qb[d]=null)}},A:function(a){if(a){var b=P[a];b?(U.deleteProgram(b),b.name=0,P[a]=null):T(1281)}},O:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Q[d];e&&(U.deleteRenderbuffer(e),e.name=0,Q[d]=null)}},
w:function(a){if(a){var b=S[a];b?(U.deleteShader(b),S[a]=null):T(1281)}},La:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=R[d];e&&(U.deleteTexture(e),e.name=0,R[d]=null)}},z:function(a){U.depthFunc(a)},y:function(a){U.depthMask(!!a)},d:function(a){U.disable(a)},N:function(a){U.disableVertexAttribArray(a)},db:function(a,b,c){U.drawArrays(a,b,c)},eb:function(a,b,c,d){U.drawArraysInstanced(a,b,c,d)},fb:function(a,b,c,d){U.drawElements(a,b,c,d)},gb:function(a,b,c,d,e){U.drawElementsInstanced(a,
b,c,d,e)},i:function(a){U.enable(a)},rb:function(a){U.enableVertexAttribArray(a)},l:function(a,b,c,d){U.framebufferRenderbuffer(a,b,c,Q[d])},g:function(a,b,c,d,e){U.framebufferTexture2D(a,b,c,R[d],e)},I:function(a){U.frontFace(a)},Ea:function(a,b){Bb(a,b,"createBuffer",pb)},p:function(a,b){Bb(a,b,"createFramebuffer",qb)},Ca:function(a,b){Bb(a,b,"createRenderbuffer",Q)},za:function(a,b){Bb(a,b,"createTexture",R)},yb:function(a,b){return U.getAttribLocation(P[a],J(b))},e:function(a,b){Cb(a,b)},ta:function(a,
b,c,d){a=U.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(B[c>>2]=b)},F:function(a,b,c){if(c)if(a>=ob)T(1281);else if(a=P[a],35716==b)a=U.getProgramInfoLog(a),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b){if(!a.mc)for(b=0;b<U.getProgramParameter(a,35718);++b)a.mc=Math.max(a.mc,U.getActiveUniform(a,b).name.length+1);B[c>>2]=a.mc}else if(35722==b){if(!a.kc)for(b=0;b<U.getProgramParameter(a,35721);++b)a.kc=Math.max(a.kc,U.getActiveAttrib(a,b).name.length+
1);B[c>>2]=a.kc}else if(35381==b){if(!a.lc)for(b=0;b<U.getProgramParameter(a,35382);++b)a.lc=Math.max(a.lc,U.getActiveUniformBlockName(a,b).length+1);B[c>>2]=a.lc}else B[c>>2]=U.getProgramParameter(a,b);else T(1281)},zb:function(a,b,c,d){a=U.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(B[c>>2]=b)},ra:function(a,b,c){c?35716==b?(a=U.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),B[c>>2]=a?a.length+1:0):35720==b?(a=U.getShaderSource(S[a]),B[c>>2]=a?a.length+
1:0):B[c>>2]=U.getShaderParameter(S[a],b):T(1281)},Na:function(a){var b=sb[a];if(!b){switch(a){case 7939:b=U.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Eb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=U.getParameter(a))||T(1280);b=b&&Eb(b);break;case 7938:b=Eb("OpenGL ES 2.0 ("+U.getParameter(7938)+")");break;case 35724:b=U.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=
"OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Eb(b);break;default:T(1280)}sb[a]=b}return b},q:function(a,b){b=J(b);if(a=P[a]){var c=a,d=c.ic,e=c.Cc,h;if(!d)for(c.ic=d={},c.Bc={},h=0;h<U.getProgramParameter(c,35718);++h){var g=U.getActiveUniform(c,h);var m=g.name;g=g.size;var n=Fb(m);n=0<n?m.slice(0,n):m;var p=c.oc;c.oc+=g;e[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.Bc[p++]=n}c=a.ic;d=0;e=b;h=Fb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Cc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||U.getUniformLocation(a,
b)))return d}else T(1281);return-1},ua:function(a){a=P[a];U.linkProgram(a);a.ic=0;a.Cc={}},Ja:function(a,b){3317==a&&(tb=b);U.pixelStorei(a,b)},J:function(a,b){U.polygonOffset(a,b)},Aa:function(a,b,c,d){U.renderbufferStorage(a,b,c,d)},qa:function(a,b,c,d){U.scissor(a,b,c,d)},Bb:function(a,b,c,d){for(var e="",h=0;h<b;++h){var g=d?B[d+4*h>>2]:-1;e+=J(B[c+4*h>>2],0>g?void 0:g)}U.shaderSource(S[a],e)},Ha:function(a,b,c){U.stencilFunc(a,b,c)},oa:function(a,b,c,d){U.stencilFuncSeparate(a,b,c,d)},x:function(a){U.stencilMask(a)},
Ga:function(a,b,c){U.stencilOp(a,b,c)},na:function(a,b,c,d){U.stencilOpSeparate(a,b,c,d)},wa:function(a,b,c,d,e,h,g,m,n){U.texImage2D(a,b,c,d,e,h,g,m,n?Gb(m,g,d,e,n):null)},k:function(a,b,c){U.texParameteri(a,b,c)},cb:function(a,b,c,d,e,h,g,m,n){var p=null;n&&(p=Gb(m,g,e,h,n));U.texSubImage2D(a,b,c,d,e,h,g,m,p)},qb:function(a,b,c){if(288>=b)for(var d=W[b-1],e=0;e<b;++e)d[e]=C[c+4*e>>2];else d=C.subarray(c>>2,c+4*b>>2);U.uniform1fv(V(a),d)},E:function(a,b){U.uniform1i(V(a),b)},mb:function(a,b,c){if(288>=
b)for(var d=X[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);U.uniform1iv(V(a),d)},pb:function(a,b,c){if(144>=b)for(var d=W[2*b-1],e=0;e<2*b;e+=2)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2];else d=C.subarray(c>>2,c+8*b>>2);U.uniform2fv(V(a),d)},lb:function(a,b,c){if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);U.uniform2iv(V(a),d)},ob:function(a,b,c){if(96>=b)for(var d=W[3*b-1],e=0;e<3*b;e+=3)d[e]=C[c+4*e>>2],d[e+
1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2];else d=C.subarray(c>>2,c+12*b>>2);U.uniform3fv(V(a),d)},kb:function(a,b,c){if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);U.uniform3iv(V(a),d)},nb:function(a,b,c){if(72>=b){var d=W[4*b-1],e=C;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=C.subarray(c>>2,c+16*b>>2);U.uniform4fv(V(a),d)},jb:function(a,b,c){if(72>=
b)for(var d=X[4*b-1],e=0;e<4*b;e+=4)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2],d[e+3]=B[c+(4*e+12)>>2];else d=B.subarray(c>>2,c+16*b>>2);U.uniform4iv(V(a),d)},ib:function(a,b,c,d){if(18>=b){var e=W[16*b-1],h=C;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=h[m+13];e[g+14]=h[m+14];e[g+15]=h[m+15]}}else e=
C.subarray(d>>2,d+64*b>>2);U.uniformMatrix4fv(V(a),!!c,e)},n:function(a){a=P[a];U.useProgram(a);U.Dc=a},sb:function(a,b){U.vertexAttribDivisor(a,b)},tb:function(a,b,c,d,e,h){U.vertexAttribPointer(a,b,c,!!d,e,h)},t:function(a,b,c,d){U.viewport(a,b,c,d)},Ua:function(){f.uc=a=>{0!=Lb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.uc)},Oa:function(){f.Ac=a=>{const b=a.clipboardData.getData("text");Da(()=>{const c=Y(b);Mb(c)})};window.addEventListener("paste",f.Ac)},
Ia:function(a){f.Rc=[];a=J(a);a=document.getElementById(a);f.vc=b=>{b.stopPropagation();b.preventDefault()};f.wc=b=>{b.stopPropagation();b.preventDefault()};f.xc=b=>{b.stopPropagation();b.preventDefault()};f.yc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.zc=c;Nb(c.length);for(let d=0;d<c.length;d++)Da(()=>{const e=Y(c[d].name);Ob(d,e)});Pb(b.clientX,b.clientY)};a.addEventListener("dragenter",f.vc,!1);a.addEventListener("dragleave",f.wc,!1);a.addEventListener("dragover",
f.xc,!1);a.addEventListener("drop",f.yc,!1)},hb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},v:function(){const a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Qb()});document.body.append(a)},Fa:function(a){const b=f.zc;return 0>a||a>=b.length?0:b[a].size},xa:function(a,b,c,d,e){const h=new FileReader;h.onload=g=>{g=g.target.result;g.byteLength>d?Rb(a,
0,1,b,0,c,d,e):(A.set(new Uint8Array(g),c),Rb(a,1,0,b,g.byteLength,c,d,e))};h.onerror=()=>{Rb(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(f.zc[a])},u:function(){document.getElementById("_sokol_app_input_element").focus()},xb:function(a){a=J(a);f.hc=document.getElementById(a);f.hc||console.log("sokol_app.h: invalid target:"+a);f.hc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Pa:function(){window.removeEventListener("beforeunload",f.uc)},Ka:function(){window.removeEventListener("paste",
f.Ac)},Cb:function(a){a=J(a);a=document.getElementById(a);a.removeEventListener("dragenter",f.vc);a.removeEventListener("dragleave",f.wc);a.removeEventListener("dragover",f.xc);a.removeEventListener("drop",f.yc)},D:function(){f.hc&&f.hc.requestPointerLock&&f.hc.requestPointerLock()},$a:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(A.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");
a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},s:function(){document.getElementById("_sokol_app_input_element").blur()},Wa:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];Da(()=>{const e=Y(c),h=Y(d);Sb(e,h)})}},Ya:function(){return f.ec?f.ec.bufferSize:0},_a:function(a,b,c){f.$b=null;f.ec=null;"undefined"!==typeof AudioContext?f.$b=new AudioContext({sampleRate:a,
latencyHint:"interactive"}):(f.$b=null,console.log("sokol_audio.h: no WebAudio support"));return f.$b?(console.log("sokol_audio.h: sample rate ",f.$b.sampleRate),f.ec=f.$b.createScriptProcessor(c,0,b),f.ec.onaudioprocess=d=>{const e=d.outputBuffer.length,h=Tb(e);if(h){const g=d.outputBuffer.numberOfChannels;for(let m=0;m<g;m++){const n=d.outputBuffer.getChannelData(m);for(let p=0;p<e;p++)n[p]=C[(h>>2)+(g*p+m)]}}},f.ec.connect(f.$b.destination),a=()=>{f.$b&&"suspended"===f.$b.state&&f.$b.resume()},
document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},Za:function(){return f.$b?f.$b.sampleRate:0},ma:function(){const a=f.$b;null!==a&&(f.ec&&f.ec.disconnect(),a.close(),f.$b=null,f.ec=null)},Xa:function(){if(f.$b)return"suspended"===f.$b.state?1:0},B:function(a,b,c,d,e,h){b=J(b);const g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";const m=0<d;m&&g.setRequestHeader("Range","bytes="+
c+"-"+(c+d-1));g.onreadystatechange=function(){if(g.readyState==XMLHttpRequest.DONE)if(206==g.status||200==g.status&&!m){const n=new Uint8Array(g.response),p=n.length;p<=h?(A.set(n,e),Ub(a,d,p)):Vb(a)}else Wb(a,g.status)};g.send()},la:function(a,b){b=J(b);const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");Xb(a,d)}else Wb(a,c.status)};c.send()},ka:function(a,b){b=J(b);switch(a){case 0:console.error(b);
break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};
(function(){function a(c){c=c.exports;f.asm=c;ia=f.asm.Db;na();oa=f.asm.Wb;qa.unshift(f.asm.Eb);E--;f.monitorRunDependencies&&f.monitorRunDependencies(E);if(0==E&&(null!==va&&(clearInterval(va),va=null),F)){var d=F;F=null;d()}return c}var b={a:Yb};E++;f.monitorRunDependencies&&f.monitorRunDependencies(E);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return x("Module.instantiateWasm callback failed with error: "+c),!1}Ba(b,function(c){a(c.instance)});return{}})();
f._fs_emsc_alloc=function(){return(f._fs_emsc_alloc=f.asm.Fb).apply(null,arguments)};function N(){return(N=f.asm.Gb).apply(null,arguments)}f._fs_emsc_load_snapshot_callback=function(){return(f._fs_emsc_load_snapshot_callback=f.asm.Hb).apply(null,arguments)};
var Qb=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Qb=f.__sapp_emsc_notify_keyboard_hidden=f.asm.Ib).apply(null,arguments)},Mb=f.__sapp_emsc_onpaste=function(){return(Mb=f.__sapp_emsc_onpaste=f.asm.Jb).apply(null,arguments)},Lb=f.__sapp_html5_get_ask_leave_site=function(){return(Lb=f.__sapp_html5_get_ask_leave_site=f.asm.Kb).apply(null,arguments)},Nb=f.__sapp_emsc_begin_drop=function(){return(Nb=f.__sapp_emsc_begin_drop=f.asm.Lb).apply(null,arguments)},Ob=f.__sapp_emsc_drop=function(){return(Ob=
f.__sapp_emsc_drop=f.asm.Mb).apply(null,arguments)},Pb=f.__sapp_emsc_end_drop=function(){return(Pb=f.__sapp_emsc_end_drop=f.asm.Nb).apply(null,arguments)},Rb=f.__sapp_emsc_invoke_fetch_cb=function(){return(Rb=f.__sapp_emsc_invoke_fetch_cb=f.asm.Ob).apply(null,arguments)},Zb=f._main=function(){return(Zb=f._main=f.asm.Pb).apply(null,arguments)},Tb=f.__saudio_emsc_pull=function(){return(Tb=f.__saudio_emsc_pull=f.asm.Qb).apply(null,arguments)},Sb=f.__sargs_add_kvp=function(){return(Sb=f.__sargs_add_kvp=
f.asm.Rb).apply(null,arguments)},Xb=f.__sfetch_emsc_head_response=function(){return(Xb=f.__sfetch_emsc_head_response=f.asm.Sb).apply(null,arguments)},Ub=f.__sfetch_emsc_get_response=function(){return(Ub=f.__sfetch_emsc_get_response=f.asm.Tb).apply(null,arguments)},Wb=f.__sfetch_emsc_failed_http_status=function(){return(Wb=f.__sfetch_emsc_failed_http_status=f.asm.Ub).apply(null,arguments)},Vb=f.__sfetch_emsc_failed_buffer_too_small=function(){return(Vb=f.__sfetch_emsc_failed_buffer_too_small=f.asm.Vb).apply(null,
arguments)};function Ea(){return(Ea=f.asm.Xb).apply(null,arguments)}function Fa(){return(Fa=f.asm.Yb).apply(null,arguments)}function Ib(){return(Ib=f.asm.Zb).apply(null,arguments)}f.___start_em_js=23344;f.___stop_em_js=36238;var $b;F=function ac(){$b||bc();$b||(F=ac)};function cc(a=[]){var b=Zb;a.unshift(ca);var c=a.length,d=Ib(4*(c+1)),e=d>>2;a.forEach(g=>{B[e++]=Y(g)});B[e]=0;try{var h=b(c,d);Hb(h)}catch(g){g instanceof w||"unwind"==g||k(1,g)}}
function bc(){var a=ba;function b(){if(!$b&&($b=!0,f.calledRun=!0,!ja)){Ca(qa);Ca(ra);if(f.onRuntimeInitialized)f.onRuntimeInitialized();dc&&cc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();ta.unshift(c)}Ca(ta)}}if(!(0<E)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ua();Ca(pa);0<E||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},
1)):b())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var dc=!0;f.noInitialRun&&(dc=!1);bc();
