
var d;d||(d=typeof Module !== 'undefined' ? Module : {});var h={},l;for(l in d)d.hasOwnProperty(l)&&(h[l]=d[l]);var r=[],aa="./this.program";function t(a,b){throw b;}var ba=!1,u=!1,ca=!1,da=!1;ba="object"===typeof window;u="function"===typeof importScripts;ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;da=!ba&&!ca&&!u;var v="",ea,w,fa,ha;
if(ca)v=u?require("path").dirname(v)+"/":__dirname+"/",ea=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,b?null:"utf8")},w=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),r=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=d),process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;}),process.on("unhandledRejection",
x),t=function(a){process.exit(a)},d.inspect=function(){return"[Emscripten Module object]"};else if(da)"undefined"!=typeof read&&(ea=function(a){return read(a)}),w=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?r=scriptArgs:"undefined"!=typeof arguments&&(r=arguments),"function"===typeof quit&&(t=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ba||u)u?v=self.location.href:"undefined"!==typeof document&&document.currentScript&&(v=document.currentScript.src),v=0!==v.indexOf("blob:")?v.substr(0,v.lastIndexOf("/")+1):"",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(w=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
d.print||console.log.bind(console);var z=d.printErr||console.warn.bind(console);for(l in h)h.hasOwnProperty(l)&&(d[l]=h[l]);h=null;d.arguments&&(r=d.arguments);d.thisProgram&&(aa=d.thisProgram);d.quit&&(t=d.quit);var A;d.wasmBinary&&(A=d.wasmBinary);var noExitRuntime;d.noExitRuntime&&(noExitRuntime=d.noExitRuntime);"object"!==typeof WebAssembly&&x("no native wasm support detected");var B,ja=!1;function assert(a,b){a||x("Assertion failed: "+b)}
function ka(a){var b=d["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}function la(a,b,c){var e={string:function(m){var p=0;if(null!==m&&void 0!==m&&0!==m){var q=(m.length<<2)+1;p=C(q);D(m,E,p,q)}return p},array:function(m){var p=C(m.length);ma.set(m,p);return p}};a=ka(a);var f=[],k=0;if(c)for(var g=0;g<c.length;g++){var n=e[b[g]];n?(0===k&&(k=na()),f[g]=n(c[g])):f[g]=c[g]}a.apply(null,f);0!==k&&oa(k)}
var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function F(a,b){if(a){var c=E,e=a+b;for(b=a;c[b]&&!(b>=e);)++b;if(16<b-a&&c.subarray&&pa)a=pa.decode(c.subarray(a,b));else{for(e="";a<b;){var f=c[a++];if(f&128){var k=c[a++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|k);else{var g=c[a++]&63;f=224==(f&240)?(f&15)<<12|k<<6|g:(f&7)<<18|k<<12|g<<6|c[a++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}a=e}}else a="";return a}
function D(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var k=0;k<a.length;++k){var g=a.charCodeAt(k);if(55296<=g&&57343>=g){var n=a.charCodeAt(++k);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(c>=e)break;b[c++]=g}else{if(2047>=g){if(c+1>=e)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=e)break;b[c++]=224|g>>12}else{if(c+3>=e)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}
function qa(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}function ra(a){var b=qa(a)+1,c=C(b);D(a,ma,c,b);return c}var G,ma,E,sa,ta,H,ua,va,I;
function wa(a){G=a;d.HEAP8=ma=new Int8Array(a);d.HEAP16=sa=new Int16Array(a);d.HEAP32=H=new Int32Array(a);d.HEAPU8=E=new Uint8Array(a);d.HEAPU16=ta=new Uint16Array(a);d.HEAPU32=ua=new Uint32Array(a);d.HEAPF32=va=new Float32Array(a);d.HEAPF64=I=new Float64Array(a)}var xa=d.INITIAL_MEMORY||33554432;d.wasmMemory?B=d.wasmMemory:B=new WebAssembly.Memory({initial:xa/65536,maximum:32768});B&&(G=B.buffer);xa=G.byteLength;wa(G);var J,ya=[],za=[],Aa=[],Ba=[],Ca=[];
function Da(){var a=d.preRun.shift();ya.unshift(a)}var K=0,Ea=null,L=null;d.preloadedImages={};d.preloadedAudios={};function x(a){if(d.onAbort)d.onAbort(a);z(a);ja=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Fa(a){var b=M;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ga(){return Fa("data:application/octet-stream;base64,")}var M="pengo.wasm";if(!Ga()){var Ha=M;M=d.locateFile?d.locateFile(Ha,v):v+Ha}
function Ia(){try{if(A)return new Uint8Array(A);if(w)return w(M);throw"both async and sync fetching of the wasm failed";}catch(a){x(a)}}function Ja(){return A||!ba&&!u||"function"!==typeof fetch||Fa("file://")?Promise.resolve().then(Ia):fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ia()})}
function Ka(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.uc;"number"===typeof c?void 0===b.ec?J.get(c)():J.get(c)(b.ec):c(void 0===b.ec?null:b.ec)}}}var La=0;function Ma(){for(var a=N.length-1;0<=a;--a)Na(a);N=[];Oa=[]}var Oa=[];function Pa(){if(La&&Qa.cc)for(var a=0;a<Oa.length;++a){var b=Oa[a];Oa.splice(a,1);--a;b.Kc.apply(null,b.Ac)}}var N=[];function Na(a){var b=N[a];b.target.removeEventListener(b.Vb,b.sc,b.Wb);N.splice(a,1)}
function O(a){function b(e){++La;Qa=a;Pa();a.Zb(e);Pa();--La}if(a.Yb)a.sc=b,a.target.addEventListener(a.Vb,b,a.Wb),N.push(a),Ra||(Ba.push(Ma),Ra=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Vb==a.Vb&&Na(c--)}var Ra,Qa,Sa,Ta,Ua,Va,Wa,Xa,Ya=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function P(a){a=2<a?F(a):a;return Ya[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Za(a){return 0>Ya.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function $a(a,b,c,e,f,k){Sa||(Sa=Q(164));a={target:P(a),cc:!0,Vb:k,Yb:e,Zb:function(g){var n=Sa,m=n>>2;H[m]=g.location;H[m+1]=g.ctrlKey;H[m+2]=g.shiftKey;H[m+3]=g.altKey;H[m+4]=g.metaKey;H[m+5]=g.repeat;H[m+6]=g.charCode;H[m+7]=g.keyCode;H[m+8]=g.which;D(g.key||"",E,n+36,32);D(g.code||"",E,n+68,32);D(g.char||"",E,n+100,32);D(g.locale||"",E,n+132,32);J.get(e)(f,n,b)&&g.preventDefault()},Wb:c};O(a)}
function ab(a,b,c){a>>=2;H[a]=b.screenX;H[a+1]=b.screenY;H[a+2]=b.clientX;H[a+3]=b.clientY;H[a+4]=b.ctrlKey;H[a+5]=b.shiftKey;H[a+6]=b.altKey;H[a+7]=b.metaKey;sa[2*a+16]=b.button;sa[2*a+17]=b.buttons;H[a+9]=b.movementX;H[a+10]=b.movementY;c=Za(c);H[a+11]=b.clientX-c.left;H[a+12]=b.clientY-c.top}function R(a,b,c,e,f,k){Ta||(Ta=Q(64));a=P(a);O({target:a,cc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Vb:k,Yb:e,Zb:function(g){g=g||event;ab(Ta,g,a);J.get(e)(f,Ta,b)&&g.preventDefault()},Wb:c})}
function bb(a,b,c,e,f){Ua||(Ua=Q(260));O({target:a,Vb:f,Yb:e,Zb:function(k){k=k||event;var g=Ua,n=document.pointerLockElement||document.hc||document.jc||document.ic;H[g>>2]=!!n;var m=n&&n.id?n.id:"";D(n?n==window?"#window":n==screen?"#screen":n&&n.nodeName?n.nodeName:"":"",E,g+4,128);D(m,E,g+132,128);J.get(e)(20,g,b)&&k.preventDefault()},Wb:c})}function cb(a,b,c,e,f){O({target:a,Vb:f,Yb:e,Zb:function(k){k=k||event;J.get(e)(38,0,b)&&k.preventDefault()},Wb:c})}
function db(a,b,c,e){Va||(Va=Q(36));a=P(a);O({target:a,Vb:"resize",Yb:e,Zb:function(f){f=f||event;if(f.target==a){var k=document.body;if(k){var g=Va;H[g>>2]=f.detail;H[g+4>>2]=k.clientWidth;H[g+8>>2]=k.clientHeight;H[g+12>>2]=innerWidth;H[g+16>>2]=innerHeight;H[g+20>>2]=outerWidth;H[g+24>>2]=outerHeight;H[g+28>>2]=pageXOffset;H[g+32>>2]=pageYOffset;J.get(e)(10,g,b)&&f.preventDefault()}}},Wb:c})}
function eb(a,b,c,e,f,k){Wa||(Wa=Q(1684));a=P(a);O({target:a,cc:"touchstart"==k||"touchend"==k,Vb:k,Yb:e,Zb:function(g){for(var n={},m=g.touches,p=0;p<m.length;++p){var q=m[p];n[q.identifier]=q}m=g.changedTouches;for(p=0;p<m.length;++p)q=m[p],q.wc=1,n[q.identifier]=q;m=g.targetTouches;for(p=0;p<m.length;++p)n[m[p].identifier].yc=1;m=Wa;q=m>>2;H[q+1]=g.ctrlKey;H[q+2]=g.shiftKey;H[q+3]=g.altKey;H[q+4]=g.metaKey;q+=5;var ib=Za(a),jb=0;for(p in n){var y=n[p];H[q]=y.identifier;H[q+1]=y.screenX;H[q+2]=
y.screenY;H[q+3]=y.clientX;H[q+4]=y.clientY;H[q+5]=y.pageX;H[q+6]=y.pageY;H[q+7]=y.wc;H[q+8]=y.yc;H[q+9]=y.clientX-ib.left;H[q+10]=y.clientY-ib.top;q+=13;if(31<++jb)break}H[m>>2]=jb;J.get(e)(f,m,b)&&g.preventDefault()},Wb:c})}function fb(a,b,c,e,f,k){a={target:P(a),Vb:k,Yb:e,Zb:function(g){g=g||event;J.get(e)(f,0,b)&&g.preventDefault()},Wb:c};O(a)}
function gb(a,b,c,e){Xa||(Xa=Q(96));O({target:a,cc:!0,Vb:"wheel",Yb:e,Zb:function(f){f=f||event;var k=Xa;ab(k,f,a);I[k+64>>3]=f.deltaX;I[k+72>>3]=f.deltaY;I[k+80>>3]=f.deltaZ;H[k+88>>2]=f.deltaMode;J.get(e)(9,k,b)&&f.preventDefault()},Wb:c})}
function hb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,e){b.vertexAttribDivisorANGLE(c,e)},a.drawArraysInstanced=function(c,e,f,k){b.drawArraysInstancedANGLE(c,e,f,k)},a.drawElementsInstanced=function(c,e,f,k,g){b.drawElementsInstancedANGLE(c,e,f,k,g)})}
function kb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function lb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,e){b.drawBuffersWEBGL(c,e)})}function mb(a){a.Fc=a.getExtension("WEBGL_multi_draw")}
var nb=1,ob=[],S=[],pb=[],T=[],U=[],V=[],W=[],qb=[],rb={},sb={};function X(a){tb||(tb=a)}function Y(a){for(var b=nb++,c=a.length;c<b;c++)a[c]=null;return b}
function ub(a){a||(a=vb);if(!a.vc){a.vc=!0;var b=a.dc;hb(b);kb(b);lb(b);b.Cc=b.getExtension("EXT_disjoint_timer_query");mb(b);var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(e){-1!=c.indexOf(e)&&b.getExtension(e)})}}var tb,vb,wb=["default","low-power","high-performance"];function xb(a,b,c,e){for(var f=0;f<a;f++){var k=Z[c](),g=k&&Y(e);k?(k.name=g,e[g]=k):X(1282);H[b+4*f>>2]=g}}
function yb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var e=Z.getParameter(34467);c=e?e.length:0}if(void 0===c)switch(e=Z.getParameter(a),typeof e){case "number":c=e;break;case "boolean":c=e?1:0;break;case "string":X(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:X(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||
e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)H[b+4*a>>2]=e[a];return}try{c=e.name|0}catch(f){X(1280);z("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:X(1280);z("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+e+" of type "+typeof e+"!");return}H[b>>2]=c}else X(1281)}function zb(a){var b=qa(a)+1,c=Q(b);D(a,E,c,b);return c}
function Ab(a,b,c,e,f){a-=5120;a=1==a?E:4==a?H:6==a?va:5==a||28922==a?ua:ta;var k=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(f>>k,f+e*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<k)+4-1&-4)>>k)}var Z;za.push({uc:function(){Bb()}});
var Hb={X:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},ea:function(a,b,c){a=P(a);if(!a)return-4;a=Za(a);I[b>>3]=a.width;I[c>>3]=a.height;return 0},Ya:function(a,b,c){E.copyWithin(a,b,b+c)},La:function(a,b){function c(e){J.get(a)(e,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Za:function(a){a>>>=0;var b=E.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);e=Math.max(16777216,a,e);0<e%65536&&(e+=65536-e%65536);
a:{try{B.grow(Math.min(2147483648,e)-G.byteLength+65535>>>16);wa(B.buffer);var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},T:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},ha:function(a,b,c,e){$a(a,b,c,e,2,"keydown");return 0},fa:function(a,b,c,e){$a(a,b,c,e,1,"keypress");return 0},ga:function(a,b,c,e){$a(a,b,c,e,3,"keyup");return 0},na:function(a,b,c,e){R(a,b,c,e,5,"mousedown");return 0},ka:function(a,b,c,e){R(a,b,c,e,33,"mouseenter");return 0},ja:function(a,b,c,
e){R(a,b,c,e,34,"mouseleave");return 0},la:function(a,b,c,e){R(a,b,c,e,8,"mousemove");return 0},ma:function(a,b,c,e){R(a,b,c,e,6,"mouseup");return 0},$:function(a,b,c,e){if(!document||!document.body||!(document.body.requestPointerLock||document.body.hc||document.body.jc||document.body.ic))return-1;a=P(a);if(!a)return-4;bb(a,b,c,e,"pointerlockchange");bb(a,b,c,e,"mozpointerlockchange");bb(a,b,c,e,"webkitpointerlockchange");bb(a,b,c,e,"mspointerlockchange");return 0},_:function(a,b,c,e){if(!document||
!(document.body.requestPointerLock||document.body.hc||document.body.jc||document.body.ic))return-1;a=P(a);if(!a)return-4;cb(a,b,c,e,"pointerlockerror");cb(a,b,c,e,"mozpointerlockerror");cb(a,b,c,e,"webkitpointerlockerror");cb(a,b,c,e,"mspointerlockerror");return 0},Ua:function(a,b,c,e){db(a,b,c,e);return 0},aa:function(a,b,c,e){eb(a,b,c,e,25,"touchcancel");return 0},ba:function(a,b,c,e){eb(a,b,c,e,23,"touchend");return 0},ca:function(a,b,c,e){eb(a,b,c,e,24,"touchmove");return 0},da:function(a,b,c,
e){eb(a,b,c,e,22,"touchstart");return 0},Z:function(a,b,c,e){fb(a,b,c,e,31,"webglcontextlost");return 0},Y:function(a,b,c,e){fb(a,b,c,e,32,"webglcontextrestored");return 0},ia:function(a,b,c,e){a=P(a);return"undefined"!==typeof a.onwheel?(gb(a,b,c,e),0):-1},F:function(a,b){b>>=2;b={alpha:!!H[b],depth:!!H[b+1],stencil:!!H[b+2],antialias:!!H[b+3],premultipliedAlpha:!!H[b+4],preserveDrawingBuffer:!!H[b+5],powerPreference:wb[H[b+6]],failIfMajorPerformanceCaveat:!!H[b+7],xc:H[b+8],Ec:H[b+9],kc:H[b+10],
tc:H[b+11],Gc:H[b+12],Hc:H[b+13]};a=P(a);if(!a||b.tc)b=0;else if(a=a.getContext("webgl",b)){var c=Y(qb),e={Dc:c,attributes:b,version:b.xc,dc:a};a.canvas&&(a.canvas.zc=e);qb[c]=e;("undefined"===typeof b.kc||b.kc)&&ub(e);b=c}else b=0;return b},eb:function(a,b){a=qb[a];b=F(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&hb(Z);"OES_vertex_array_object"==b&&kb(Z);"WEBGL_draw_buffers"==b&&lb(Z);"WEBGL_multi_draw"==b&&mb(Z);return!!a.dc.getExtension(b)},Ha:function(a){a>>=2;for(var b=
0;14>b;++b)H[a+b]=0;H[a]=H[a+1]=H[a+3]=H[a+4]=H[a+8]=H[a+10]=1},xa:function(a){vb=qb[a];d.Bc=Z=vb&&vb.dc;return!a||Z?0:-5},c:function(a){Z.activeTexture(a)},H:function(a,b){Z.attachShader(S[a],W[b])},f:function(a,b){Z.bindBuffer(a,ob[b])},h:function(a,b){Z.bindFramebuffer(a,pb[b])},Ja:function(a,b){Z.bindRenderbuffer(a,T[b])},b:function(a,b){Z.bindTexture(a,U[b])},Q:function(a,b,c,e){Z.blendColor(a,b,c,e)},R:function(a,b){Z.blendEquationSeparate(a,b)},S:function(a,b,c,e){Z.blendFuncSeparate(a,b,c,
e)},L:function(a,b,c,e){Z.bufferData(a,c?E.subarray(c,c+b):b,e)},K:function(a,b,c,e){Z.bufferSubData(a,b,E.subarray(e,e+c))},n:function(a){return Z.checkFramebufferStatus(a)},sa:function(a){Z.clear(a)},va:function(a,b,c,e){Z.clearColor(a,b,c,e)},ua:function(a){Z.clearDepth(a)},ta:function(a){Z.clearStencil(a)},w:function(a,b,c,e){Z.colorMask(!!a,!!b,!!c,!!e)},Aa:function(a){Z.compileShader(W[a])},J:function(a,b,c,e,f,k,g,n){Z.compressedTexImage2D(a,b,c,e,f,k,n?E.subarray(n,n+g):null)},Fa:function(){var a=
Y(S),b=Z.createProgram();b.name=a;S[a]=b;return a},Ca:function(a){var b=Y(W);W[b]=Z.createShader(a);return b},N:function(a){Z.cullFace(a)},Pa:function(a,b){for(var c=0;c<a;c++){var e=H[b+4*c>>2],f=ob[e];f&&(Z.deleteBuffer(f),f.name=0,ob[e]=null)}},e:function(a,b){for(var c=0;c<a;++c){var e=H[b+4*c>>2],f=pb[e];f&&(Z.deleteFramebuffer(f),f.name=0,pb[e]=null)}},V:function(a){if(a){var b=S[a];b?(Z.deleteProgram(b),b.name=0,S[a]=null,rb[a]=null):X(1281)}},W:function(a,b){for(var c=0;c<a;c++){var e=H[b+
4*c>>2],f=T[e];f&&(Z.deleteRenderbuffer(f),f.name=0,T[e]=null)}},v:function(a){if(a){var b=W[a];b?(Z.deleteShader(b),W[a]=null):X(1281)}},Oa:function(a,b){for(var c=0;c<a;c++){var e=H[b+4*c>>2],f=U[e];f&&(Z.deleteTexture(f),f.name=0,U[e]=null)}},z:function(a){Z.depthFunc(a)},y:function(a){Z.depthMask(!!a)},g:function(a){Z.disable(a)},U:function(a){Z.disableVertexAttribArray(a)},pa:function(a,b,c){Z.drawArrays(a,b,c)},qa:function(a,b,c,e){Z.drawElements(a,b,c,e)},j:function(a){Z.enable(a)},cb:function(a){Z.enableVertexAttribArray(a)},
l:function(a,b,c,e){Z.framebufferRenderbuffer(a,b,c,T[e])},d:function(a,b,c,e,f){Z.framebufferTexture2D(a,b,c,U[e],f)},O:function(a){Z.frontFace(a)},M:function(a,b){xb(a,b,"createBuffer",ob)},o:function(a,b){xb(a,b,"createFramebuffer",pb)},Ka:function(a,b){xb(a,b,"createRenderbuffer",T)},Ga:function(a,b){xb(a,b,"createTexture",U)},ya:function(a,b){return Z.getAttribLocation(S[a],F(b))},i:function(a,b){yb(a,b)},Da:function(a,b,c,e){a=Z.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&
e?D(a,E,e,b):0;c&&(H[c>>2]=b)},G:function(a,b,c){if(c)if(a>=nb)X(1281);else{var e=rb[a];if(e)if(35716==b)a=Z.getProgramInfoLog(S[a]),null===a&&(a="(unknown error)"),H[c>>2]=a.length+1;else if(35719==b)H[c>>2]=e.fc;else if(35722==b){if(-1==e.$b){a=S[a];var f=Z.getProgramParameter(a,35721);for(b=e.$b=0;b<f;++b)e.$b=Math.max(e.$b,Z.getActiveAttrib(a,b).name.length+1)}H[c>>2]=e.$b}else if(35381==b){if(-1==e.ac)for(a=S[a],f=Z.getProgramParameter(a,35382),b=e.ac=0;b<f;++b)e.ac=Math.max(e.ac,Z.getActiveUniformBlockName(a,
b).length+1);H[c>>2]=e.ac}else H[c>>2]=Z.getProgramParameter(S[a],b);else X(1282)}else X(1281)},za:function(a,b,c,e){a=Z.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");b=0<b&&e?D(a,E,e,b):0;c&&(H[c>>2]=b)},D:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),H[c>>2]=a?a.length+1:0):35720==b?(a=Z.getShaderSource(W[a]),H[c>>2]=a?a.length+1:0):H[c>>2]=Z.getShaderParameter(W[a],b):X(1281)},Qa:function(a){if(sb[a])return sb[a];switch(a){case 7939:var b=Z.getSupportedExtensions()||
[];b=b.concat(b.map(function(e){return"GL_"+e}));b=zb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||X(1280);b=zb(b);break;case 7938:b=zb("OpenGL ES 2.0 ("+Z.getParameter(7938)+")");break;case 35724:b=Z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=zb(b);break;default:return X(1280),0}return sb[a]=b},p:function(a,b){b=F(b);var c=0;if("]"==b[b.length-
1]){var e=b.lastIndexOf("[");c="]"!=b[e+1]?parseInt(b.slice(e+1)):0;b=b.slice(0,e)}return(a=rb[a]&&rb[a].rc[b])&&0<=c&&c<a[0]?a[1]+c:-1},Ea:function(a){Z.linkProgram(S[a]);var b=S[a];a=rb[a]={rc:{},fc:0,$b:-1,ac:-1};for(var c=a.rc,e=Z.getProgramParameter(b,35718),f=0;f<e;++f){var k=Z.getActiveUniform(b,f),g=k.name;a.fc=Math.max(a.fc,g.length+1);"]"==g.slice(-1)&&(g=g.slice(0,g.lastIndexOf("[")));var n=Z.getUniformLocation(b,g);if(n){var m=Y(V);c[g]=[k.size,m];V[m]=n;for(var p=1;p<k.size;++p)n=Z.getUniformLocation(b,
g+"["+p+"]"),m=Y(V),V[m]=n}}},P:function(a,b){Z.polygonOffset(a,b)},Ia:function(a,b,c,e){Z.renderbufferStorage(a,b,c,e)},wa:function(a,b,c,e){Z.scissor(a,b,c,e)},Ba:function(a,b,c,e){for(var f="",k=0;k<b;++k){var g=e?H[e+4*k>>2]:-1;f+=F(H[c+4*k>>2],0>g?void 0:g)}Z.shaderSource(W[a],f)},Na:function(a,b,c){Z.stencilFunc(a,b,c)},C:function(a,b,c,e){Z.stencilFuncSeparate(a,b,c,e)},x:function(a){Z.stencilMask(a)},Ma:function(a,b,c){Z.stencilOp(a,b,c)},ra:function(a,b,c,e){Z.stencilOpSeparate(a,b,c,e)},
I:function(a,b,c,e,f,k,g,n,m){Z.texImage2D(a,b,c,e,f,k,g,n,m?Ab(n,g,e,f,m):null)},k:function(a,b,c){Z.texParameteri(a,b,c)},m:function(a,b,c,e,f,k,g,n,m){var p=null;m&&(p=Ab(n,g,f,k,m));Z.texSubImage2D(a,b,c,e,f,k,g,n,p)},E:function(a,b){Z.uniform1i(V[a],b)},q:function(a){Z.useProgram(S[a])},_a:function(a,b){Z.vertexAttribDivisor(a,b)},db:function(a,b,c,e,f,k){Z.vertexAttribPointer(a,b,c,!!e,f,k)},u:function(a,b,c,e){Z.viewport(a,b,c,e)},a:B,Xa:function(){d.lc=function(a){0!=Cb()&&(a.preventDefault(),
a.returnValue=" ")};window.addEventListener("beforeunload",d.lc)},Wa:function(){d.qc=function(a){a=a.clipboardData.getData("text");la("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",d.qc)},Va:function(a){d.Ic=[];a=F(a);a=document.getElementById(a);d.mc=function(b){b.stopPropagation();b.preventDefault()};d.nc=function(b){b.stopPropagation();b.preventDefault()};d.oc=function(b){b.stopPropagation();b.preventDefault()};d.pc=function(b){b.stopPropagation();b.preventDefault();var c=
b.dataTransfer.files;d.Jc=c;Db(c.length);var e;for(e=0;e<c.length;e++)la("_sapp_emsc_drop",["number","string"],[e,c[e].name]);Eb(b.clientX,b.clientY)};a.addEventListener("dragenter",d.mc,!1);a.addEventListener("dragleave",d.nc,!1);a.addEventListener("dragover",d.oc,!1);a.addEventListener("drop",d.pc,!1)},t:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Fb()});document.body.append(a)},s:function(){document.getElementById("_sokol_app_input_element").focus()},
fb:function(a){a=F(a);d.bc=document.getElementById(a);d.bc||console.log("sokol_app.h: invalid target:"+a);d.bc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Ta:function(){window.removeEventListener("beforeunload",d.lc)},Sa:function(){window.removeEventListener("paste",d.qc)},Ra:function(a){a=F(a);a=document.getElementById(a);a.removeEventListener("dragenter",d.mc);a.removeEventListener("dragleave",d.nc);a.removeEventListener("dragover",d.oc);a.removeEventListener("drop",
d.pc)},A:function(){d.bc&&d.bc.requestPointerLock&&d.bc.requestPointerLock()},r:function(){document.getElementById("_sokol_app_input_element").blur()},$a:function(){return d.Xb?d.Xb.bufferSize:0},bb:function(a,b,c){d.Ub=null;d.Xb=null;"undefined"!==typeof AudioContext?d.Ub=new AudioContext({sampleRate:a,latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?d.Ub=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(d.Ub=null,console.log("sokol_audio.h: no WebAudio support"));
return d.Ub?(console.log("sokol_audio.h: sample rate ",d.Ub.sampleRate),d.Xb=d.Ub.createScriptProcessor(c,0,b),d.Xb.onaudioprocess=function(e){var f=e.outputBuffer.length,k=Gb(f);if(k)for(var g=e.outputBuffer.numberOfChannels,n=0;n<g;n++)for(var m=e.outputBuffer.getChannelData(n),p=0;p<f;p++)m[p]=va[(k>>2)+(g*p+n)]},d.Xb.connect(d.Ub.destination),a=function(){d.Ub&&"suspended"===d.Ub.state&&d.Ub.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),
document.addEventListener("keydown",a,{once:!0}),1):0},ab:function(){return d.Ub?d.Ub.sampleRate:0},oa:function(){null!==d.Ub&&(d.Xb&&d.Xb.disconnect(),d.Ub.close(),d.Ub=null,d.Xb=null)},B:function(){return performance.now()}};
(function(){function a(f){d.asm=f.exports;J=d.asm.gb;K--;d.monitorRunDependencies&&d.monitorRunDependencies(K);0==K&&(null!==Ea&&(clearInterval(Ea),Ea=null),L&&(f=L,L=null,f()))}function b(f){a(f.instance)}function c(f){return Ja().then(function(k){return WebAssembly.instantiate(k,e)}).then(f,function(k){z("failed to asynchronously prepare wasm: "+k);x(k)})}var e={a:Hb};K++;d.monitorRunDependencies&&d.monitorRunDependencies(K);if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(f){return z("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){return A||"function"!==typeof WebAssembly.instantiateStreaming||Ga()||Fa("file://")||"function"!==typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(k){z("wasm streaming compile failed: "+k);z("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var Bb=d.___wasm_call_ctors=function(){return(Bb=d.___wasm_call_ctors=d.asm.hb).apply(null,arguments)};
d._emsc_load_data=function(){return(d._emsc_load_data=d.asm.ib).apply(null,arguments)};d.___em_js__emsc_fs_init=function(){return(d.___em_js__emsc_fs_init=d.asm.jb).apply(null,arguments)};d.___em_js__emsc_load_file=function(){return(d.___em_js__emsc_load_file=d.asm.kb).apply(null,arguments)};var Fb=d.__sapp_emsc_notify_keyboard_hidden=function(){return(Fb=d.__sapp_emsc_notify_keyboard_hidden=d.asm.lb).apply(null,arguments)};
d.__sapp_emsc_onpaste=function(){return(d.__sapp_emsc_onpaste=d.asm.mb).apply(null,arguments)};var Cb=d.__sapp_html5_get_ask_leave_site=function(){return(Cb=d.__sapp_html5_get_ask_leave_site=d.asm.nb).apply(null,arguments)},Db=d.__sapp_emsc_begin_drop=function(){return(Db=d.__sapp_emsc_begin_drop=d.asm.ob).apply(null,arguments)};d.__sapp_emsc_drop=function(){return(d.__sapp_emsc_drop=d.asm.pb).apply(null,arguments)};
var Eb=d.__sapp_emsc_end_drop=function(){return(Eb=d.__sapp_emsc_end_drop=d.asm.qb).apply(null,arguments)};d.__sapp_emsc_invoke_fetch_cb=function(){return(d.__sapp_emsc_invoke_fetch_cb=d.asm.rb).apply(null,arguments)};d.___em_js__sapp_js_create_textfield=function(){return(d.___em_js__sapp_js_create_textfield=d.asm.sb).apply(null,arguments)};d.___em_js__sapp_js_focus_textfield=function(){return(d.___em_js__sapp_js_focus_textfield=d.asm.tb).apply(null,arguments)};
d.___em_js__sapp_js_unfocus_textfield=function(){return(d.___em_js__sapp_js_unfocus_textfield=d.asm.ub).apply(null,arguments)};d.___em_js__sapp_js_add_beforeunload_listener=function(){return(d.___em_js__sapp_js_add_beforeunload_listener=d.asm.vb).apply(null,arguments)};d.___em_js__sapp_js_remove_beforeunload_listener=function(){return(d.___em_js__sapp_js_remove_beforeunload_listener=d.asm.wb).apply(null,arguments)};
d.___em_js__sapp_js_add_clipboard_listener=function(){return(d.___em_js__sapp_js_add_clipboard_listener=d.asm.xb).apply(null,arguments)};d.___em_js__sapp_js_remove_clipboard_listener=function(){return(d.___em_js__sapp_js_remove_clipboard_listener=d.asm.yb).apply(null,arguments)};d.___em_js__sapp_js_write_clipboard=function(){return(d.___em_js__sapp_js_write_clipboard=d.asm.zb).apply(null,arguments)};
d.___em_js__sapp_js_add_dragndrop_listeners=function(){return(d.___em_js__sapp_js_add_dragndrop_listeners=d.asm.Ab).apply(null,arguments)};d.___em_js__sapp_js_dropped_file_size=function(){return(d.___em_js__sapp_js_dropped_file_size=d.asm.Bb).apply(null,arguments)};d.___em_js__sapp_js_fetch_dropped_file=function(){return(d.___em_js__sapp_js_fetch_dropped_file=d.asm.Cb).apply(null,arguments)};
d.___em_js__sapp_js_remove_dragndrop_listeners=function(){return(d.___em_js__sapp_js_remove_dragndrop_listeners=d.asm.Db).apply(null,arguments)};d.___em_js__sapp_js_pointer_init=function(){return(d.___em_js__sapp_js_pointer_init=d.asm.Eb).apply(null,arguments)};d.___em_js__sapp_js_request_pointerlock=function(){return(d.___em_js__sapp_js_request_pointerlock=d.asm.Fb).apply(null,arguments)};
d.___em_js__sapp_js_exit_pointerlock=function(){return(d.___em_js__sapp_js_exit_pointerlock=d.asm.Gb).apply(null,arguments)};d._main=function(){return(d._main=d.asm.Hb).apply(null,arguments)};d.___em_js__stm_js_perfnow=function(){return(d.___em_js__stm_js_perfnow=d.asm.Ib).apply(null,arguments)};var Gb=d.__saudio_emsc_pull=function(){return(Gb=d.__saudio_emsc_pull=d.asm.Jb).apply(null,arguments)};d.___em_js__saudio_js_init=function(){return(d.___em_js__saudio_js_init=d.asm.Kb).apply(null,arguments)};
d.___em_js__saudio_js_shutdown=function(){return(d.___em_js__saudio_js_shutdown=d.asm.Lb).apply(null,arguments)};d.___em_js__saudio_js_sample_rate=function(){return(d.___em_js__saudio_js_sample_rate=d.asm.Mb).apply(null,arguments)};d.___em_js__saudio_js_buffer_frames=function(){return(d.___em_js__saudio_js_buffer_frames=d.asm.Nb).apply(null,arguments)};d.__sargs_add_kvp=function(){return(d.__sargs_add_kvp=d.asm.Ob).apply(null,arguments)};
d.___em_js__sargs_js_parse_url=function(){return(d.___em_js__sargs_js_parse_url=d.asm.Pb).apply(null,arguments)};var Q=d._malloc=function(){return(Q=d._malloc=d.asm.Qb).apply(null,arguments)},na=d.stackSave=function(){return(na=d.stackSave=d.asm.Rb).apply(null,arguments)},oa=d.stackRestore=function(){return(oa=d.stackRestore=d.asm.Sb).apply(null,arguments)},C=d.stackAlloc=function(){return(C=d.stackAlloc=d.asm.Tb).apply(null,arguments)},Ib;
function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}L=function Jb(){Ib||Kb();Ib||(L=Jb)};
function Kb(a){function b(){if(!Ib&&(Ib=!0,d.calledRun=!0,!ja)){Ka(za);Ka(Aa);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(Lb){var c=a,e=d._main;c=c||[];var f=c.length+1,k=C(4*(f+1));H[k>>2]=ra(aa);for(var g=1;g<f;g++)H[(k>>2)+g]=ra(c[g-1]);H[(k>>2)+f]=0;try{var n=e(f,k);if(!noExitRuntime||0!==n){if(!noExitRuntime){if(d.onExit)d.onExit(n);ja=!0}t(n,new ia(n))}}catch(m){m instanceof ia||("unwind"==m?noExitRuntime=!0:((c=m)&&"object"===typeof m&&m.stack&&(c=[m,m.stack]),z("exception thrown: "+
c),t(1,m)))}finally{}}if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;)c=d.postRun.shift(),Ca.unshift(c);Ka(Ca)}}a=a||r;if(!(0<K)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Da();Ka(ya);0<K||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);b()},1)):b())}}d.run=Kb;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();
var Lb=!0;d.noInitialRun&&(Lb=!1);noExitRuntime=!0;Kb();
