
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=[],ca="./this.program",k=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,u,v,fs,w,ha;
if(ea)q=l?require("path").dirname(q)+"/":__dirname+"/",ha=()=>{w||(fs=require("fs"),w=require("path"))},fa=function(a,b){ha();a=w.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},v=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a},u=(a,b,c)=>{ha();a=w.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!=typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof
x))throw a;}),process.on("unhandledRejection",function(a){throw a;}),k=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof x||y("exiting due to exception: "+b);process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);
b.send(null);return b.responseText},l&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ia=f.print||console.log.bind(console),y=f.printErr||console.warn.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);
f.thisProgram&&(ca=f.thisProgram);f.quit&&(k=f.quit);var z;f.wasmBinary&&(z=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&ja("no native wasm support detected");var ka,la=!1;
function ma(a,b,c){var d={string:function(n){var p=0;if(null!==n&&void 0!==n&&0!==n){var r=(n.length<<2)+1;p=A(r);B(n,C,p,r)}return p},array:function(n){var p=A(n.length);na.set(n,p);return p}};a=f["_"+a];var e=[],h=0;if(c)for(var g=0;g<c.length;g++){var m=d[b[g]];m?(0===h&&(h=oa()),e[g]=m(c[g])):e[g]=c[g]}b=a.apply(null,e);b=function(n){0!==h&&pa(h);return n}(b)}var qa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ra(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&qa)return qa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a,b){return a?ra(C,a,b):""}
function B(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ta(a){var b=sa(a)+1,c=A(b);B(a,na,c,b);return c}var ua,na,C,va,wa,E,xa,F,G;
function ya(){var a=ka.buffer;ua=a;f.HEAP8=na=new Int8Array(a);f.HEAP16=va=new Int16Array(a);f.HEAP32=E=new Int32Array(a);f.HEAPU8=C=new Uint8Array(a);f.HEAPU16=wa=new Uint16Array(a);f.HEAPU32=xa=new Uint32Array(a);f.HEAPF32=F=new Float32Array(a);f.HEAPF64=G=new Float64Array(a)}var za,Aa=[],Ba=[],Ca=[],Da=[],Ea=[];function Fa(){var a=f.preRun.shift();Aa.unshift(a)}var H=0,Ga=null,I=null;
function ja(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";y(a);la=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ha(){return J.startsWith("data:application/octet-stream;base64,")}var J;J="pengo-ui.wasm";if(!Ha()){var Ia=J;J=f.locateFile?f.locateFile(Ia,q):q+Ia}function Ja(){var a=J;try{if(a==J&&z)return new Uint8Array(z);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){ja(b)}}
function Ka(){if(!z&&(da||l)){if("function"==typeof fetch&&!J.startsWith("file://"))return fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Ja()});if(u)return new Promise(function(a,b){u(J,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ja()})}
function La(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Mc;"number"==typeof c?void 0===b.oc?K(c)():K(c)(b.oc):c(void 0===b.oc?null:b.oc)}}}var Ma=[];function K(a){var b=Ma[a];b||(a>=Ma.length&&(Ma.length=a+1),Ma[a]=b=za.get(a));return b}var Na=0;function Oa(){for(var a=L.length-1;0<=a;--a)Pa(a);L=[];Qa=[]}var Qa=[];function Ra(){if(Na&&Sa.jc)for(var a=0;a<Qa.length;++a){var b=Qa[a];Qa.splice(a,1);--a;b.Uc.apply(null,b.Jc)}}var L=[];
function Pa(a){var b=L[a];b.target.removeEventListener(b.ac,b.Ec,b.bc);L.splice(a,1)}function M(a){function b(d){++Na;Sa=a;Ra();a.dc(d);Ra();--Na}if(a.cc)a.Ec=b,a.target.addEventListener(a.ac,b,a.bc),L.push(a),Ta||(Da.push(Oa),Ta=!0);else for(var c=0;c<L.length;++c)L[c].target==a.target&&L[c].ac==a.ac&&Pa(c--)}function Ua(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Ta,Sa,Va,Wa,Xa,Ya,Za,$a,ab,bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];function N(a){a=2<a?D(a):a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function cb(a){return 0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}var db;db=ea?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();
function eb(a,b,c,d,e,h){Va||(Va=O(256));a={target:N(a),ac:h,cc:d,dc:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Va;B(Ua(g.target),C,n+0,128);B(m,C,n+128,128);K(d)(e,n,b)&&g.preventDefault()},bc:c};M(a)}
function fb(a,b,c,d,e,h){Wa||(Wa=O(176));a={target:N(a),jc:!0,ac:h,cc:d,dc:function(g){var m=Wa;G[m>>3]=g.timeStamp;var n=m>>2;E[n+2]=g.location;E[n+3]=g.ctrlKey;E[n+4]=g.shiftKey;E[n+5]=g.altKey;E[n+6]=g.metaKey;E[n+7]=g.repeat;E[n+8]=g.charCode;E[n+9]=g.keyCode;E[n+10]=g.which;B(g.key||"",C,m+44,32);B(g.code||"",C,m+76,32);B(g.char||"",C,m+108,32);B(g.locale||"",C,m+140,32);K(d)(e,m,b)&&g.preventDefault()},bc:c};M(a)}
function gb(a,b,c){G[a>>3]=b.timeStamp;a>>=2;E[a+2]=b.screenX;E[a+3]=b.screenY;E[a+4]=b.clientX;E[a+5]=b.clientY;E[a+6]=b.ctrlKey;E[a+7]=b.shiftKey;E[a+8]=b.altKey;E[a+9]=b.metaKey;va[2*a+20]=b.button;va[2*a+21]=b.buttons;E[a+11]=b.movementX;E[a+12]=b.movementY;c=cb(c);E[a+13]=b.clientX-c.left;E[a+14]=b.clientY-c.top}
function P(a,b,c,d,e,h){Xa||(Xa=O(72));a=N(a);M({target:a,jc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ac:h,cc:d,dc:function(g){g=g||event;gb(Xa,g,a);K(d)(e,Xa,b)&&g.preventDefault()},bc:c})}function hb(a,b,c,d,e){Ya||(Ya=O(260));M({target:a,ac:e,cc:d,dc:function(h){h=h||event;var g=Ya,m=document.pointerLockElement||document.fc||document.rc||document.qc;E[g>>2]=!!m;var n=m&&m.id?m.id:"";B(Ua(m),C,g+4,128);B(n,C,g+132,128);K(d)(20,g,b)&&h.preventDefault()},bc:c})}
function ib(a,b,c,d,e){M({target:a,ac:e,cc:d,dc:function(h){h=h||event;K(d)(38,0,b)&&h.preventDefault()},bc:c})}
function jb(a,b,c,d){Za||(Za=O(36));a=N(a);M({target:a,ac:"resize",cc:d,dc:function(e){e=e||event;if(e.target==a){var h=document.body;if(h){var g=Za;E[g>>2]=e.detail;E[g+4>>2]=h.clientWidth;E[g+8>>2]=h.clientHeight;E[g+12>>2]=innerWidth;E[g+16>>2]=innerHeight;E[g+20>>2]=outerWidth;E[g+24>>2]=outerHeight;E[g+28>>2]=pageXOffset;E[g+32>>2]=pageYOffset;K(d)(10,g,b)&&e.preventDefault()}}},bc:c})}
function kb(a,b,c,d,e,h){$a||($a=O(1696));a=N(a);M({target:a,jc:"touchstart"==h||"touchend"==h,ac:h,cc:d,dc:function(g){for(var m,n={},p=g.touches,r=0;r<p.length;++r)m=p[r],m.tc=m.uc=0,n[m.identifier]=m;for(r=0;r<g.changedTouches.length;++r)m=g.changedTouches[r],m.tc=1,n[m.identifier]=m;for(r=0;r<g.targetTouches.length;++r)n[g.targetTouches[r].identifier].uc=1;p=$a;G[p>>3]=g.timeStamp;var t=p>>2;E[t+3]=g.ctrlKey;E[t+4]=g.shiftKey;E[t+5]=g.altKey;E[t+6]=g.metaKey;t+=7;var nb=cb(a),ob=0;for(r in n)if(m=
n[r],E[t]=m.identifier,E[t+1]=m.screenX,E[t+2]=m.screenY,E[t+3]=m.clientX,E[t+4]=m.clientY,E[t+5]=m.pageX,E[t+6]=m.pageY,E[t+7]=m.tc,E[t+8]=m.uc,E[t+9]=m.clientX-nb.left,E[t+10]=m.clientY-nb.top,t+=13,31<++ob)break;E[p+8>>2]=ob;K(d)(e,p,b)&&g.preventDefault()},bc:c})}function lb(a,b,c,d,e,h){a={target:N(a),ac:h,cc:d,dc:function(g){g=g||event;K(d)(e,0,b)&&g.preventDefault()},bc:c};M(a)}
function mb(a,b,c,d){ab||(ab=O(104));M({target:a,jc:!0,ac:"wheel",cc:d,dc:function(e){e=e||event;var h=ab;gb(h,e,a);G[h+72>>3]=e.deltaX;G[h+80>>3]=e.deltaY;G[h+88>>3]=e.deltaZ;E[h+96>>2]=e.deltaMode;K(d)(9,h,b)&&e.preventDefault()},bc:c})}
function pb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function qb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function rb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function sb(a){a.Pc=a.getExtension("WEBGL_multi_draw")}
var tb=1,ub=[],Q=[],vb=[],R=[],S=[],T=[],wb=[],xb={};function U(a){yb||(yb=a)}function zb(a){for(var b=tb++,c=a.length;c<b;c++)a[c]=null;return b}function Ab(a,b){a.fc||(a.fc=a.getContext,a.getContext=function(d,e){e=a.fc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Bb(c,b):0}function Bb(a,b){var c=zb(wb),d={Nc:c,attributes:b,version:b.Hc,nc:a};a.canvas&&(a.canvas.Ic=d);wb[c]=d;("undefined"==typeof b.sc||b.sc)&&Cb(d);return c}
function Cb(a){a||(a=Db);if(!a.Gc){a.Gc=!0;var b=a.nc;pb(b);qb(b);rb(b);b.Lc=b.getExtension("EXT_disjoint_timer_query");sb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var yb,Db,Eb=["default","low-power","high-performance"],Fb=[null,[],[]];function Gb(a,b,c,d){for(var e=0;e<a;e++){var h=V[c](),g=h&&zb(d);h?(h.name=g,d[g]=h):U(1282);E[b+4*e>>2]=g}}
function Hb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=V.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=V.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:U(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)E[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U(1280);y("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:U(1280);y("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}E[b>>2]=c}else U(1281)}function Ib(a){var b=sa(a)+1,c=O(b);B(a,C,c,b);return c}
function Jb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Kb(a,b,c,d,e){a-=5120;a=1==a?C:4==a?E:6==a?F:5==a||28922==a?xa:wa;var h=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(e>>h,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<h)+4-1&-4)>>h)}function W(a){var b=V.Dc;if(b){var c=b.ic[a];"number"==typeof c&&(b.ic[a]=c=V.getUniformLocation(b,b.Bc[a]+(0<c?"["+c+"]":"")));return c}U(1282)}for(var X=[],Y=[],V,Lb=new Float32Array(288),Z=0;288>Z;++Z)X[Z]=Lb.subarray(0,Z+1);
var Mb=new Int32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Mb.subarray(0,Z+1);
var Sb={ja:function(){return 0},db:function(){return 0},eb:function(){},_a:function(){ja("")},Q:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},U:function(a,b,c){a=N(a);if(!a)return-4;a=cb(a);G[b>>3]=a.width;G[c>>3]=a.height;return 0},C:db,ab:function(a,b,c){C.copyWithin(a,b,b+c)},Ia:function(a,b){function c(d){K(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},$a:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+
.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);e=e.min.call(e,2147483648,d+(65536-d%65536)%65536);a:{try{ka.grow(e-ua.byteLength+65535>>>16);ya();var h=1;break a}catch(g){}h=void 0}if(h)return!0}return!1},V:function(a,b,c,d){eb(a,b,c,d,12,"blur");return 0},O:function(a,b,c){a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},W:function(a,b,c,d){eb(a,b,c,d,13,"focus");return 0},da:function(a,b,c,d){fb(a,b,c,d,2,"keydown");return 0},ba:function(a,b,c,d){fb(a,b,c,d,1,"keypress");return 0},
ca:function(a,b,c,d){fb(a,b,c,d,3,"keyup");return 0},na:function(a,b,c,d){P(a,b,c,d,5,"mousedown");return 0},ga:function(a,b,c,d){P(a,b,c,d,33,"mouseenter");return 0},fa:function(a,b,c,d){P(a,b,c,d,34,"mouseleave");return 0},ha:function(a,b,c,d){P(a,b,c,d,8,"mousemove");return 0},ka:function(a,b,c,d){P(a,b,c,d,6,"mouseup");return 0},Y:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.fc||document.body.rc||document.body.qc))return-1;a=N(a);if(!a)return-4;
hb(a,b,c,d,"pointerlockchange");hb(a,b,c,d,"mozpointerlockchange");hb(a,b,c,d,"webkitpointerlockchange");hb(a,b,c,d,"mspointerlockchange");return 0},X:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.fc||document.body.rc||document.body.qc))return-1;a=N(a);if(!a)return-4;ib(a,b,c,d,"pointerlockerror");ib(a,b,c,d,"mozpointerlockerror");ib(a,b,c,d,"webkitpointerlockerror");ib(a,b,c,d,"mspointerlockerror");return 0},Sa:function(a,b,c,d){jb(a,b,c,d);return 0},Z:function(a,
b,c,d){kb(a,b,c,d,25,"touchcancel");return 0},_:function(a,b,c,d){kb(a,b,c,d,23,"touchend");return 0},$:function(a,b,c,d){kb(a,b,c,d,24,"touchmove");return 0},aa:function(a,b,c,d){kb(a,b,c,d,22,"touchstart");return 0},T:function(a,b,c,d){lb(a,b,c,d,31,"webglcontextlost");return 0},S:function(a,b,c,d){lb(a,b,c,d,32,"webglcontextrestored");return 0},ea:function(a,b,c,d){a=N(a);return"undefined"!=typeof a.onwheel?(mb(a,b,c,d),0):-1},E:function(a,b){b>>=2;b={alpha:!!E[b],depth:!!E[b+1],stencil:!!E[b+
2],antialias:!!E[b+3],premultipliedAlpha:!!E[b+4],preserveDrawingBuffer:!!E[b+5],powerPreference:Eb[E[b+6]],failIfMajorPerformanceCaveat:!!E[b+7],Hc:E[b+8],Oc:E[b+9],sc:E[b+10],Fc:E[b+11],Qc:E[b+12],Rc:E[b+13]};a=N(a);return!a||b.Fc?0:Ab(a,b)},wb:function(a,b){a=wb[a];b=D(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&pb(V);"OES_vertex_array_object"==b&&qb(V);"WEBGL_draw_buffers"==b&&rb(V);"WEBGL_multi_draw"==b&&sb(V);return!!a.nc.getExtension(b)},za:function(a){a>>=2;for(var b=
0;14>b;++b)E[a+b]=0;E[a]=E[a+1]=E[a+3]=E[a+4]=E[a+8]=E[a+10]=1},Db:function(a){Db=wb[a];f.Kc=V=Db&&Db.nc;return!a||V?0:-5},ia:function(){return 52},cb:function(){return 52},Za:function(){return 70},bb:function(a,b,c,d){for(var e=0,h=0;h<c;h++){var g=xa[b>>2],m=xa[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=C[g+n],r=Fb[a];0===p||10===p?((1===a?ia:y)(ra(r,0)),r.length=0):r.push(p)}e+=m}E[d>>2]=e;return 0},b:function(a){V.activeTexture(a)},H:function(a,b){V.attachShader(Q[a],T[b])},c:function(a,b){V.bindBuffer(a,
ub[b])},h:function(a,b){V.bindFramebuffer(a,vb[b])},Ea:function(a,b){V.bindRenderbuffer(a,R[b])},a:function(a,b){V.bindTexture(a,S[b])},L:function(a,b,c,d){V.blendColor(a,b,c,d)},M:function(a,b){V.blendEquationSeparate(a,b)},N:function(a,b,c,d){V.blendFuncSeparate(a,b,c,d)},Ga:function(a,b,c,d){V.bufferData(a,c?C.subarray(c,c+b):b,d)},p:function(a,b,c,d){V.bufferSubData(a,b,C.subarray(d,d+c))},n:function(a){return V.checkFramebufferStatus(a)},Ab:function(a){V.clear(a)},Cb:function(a,b,c,d){V.clearColor(a,
b,c,d)},qa:function(a){V.clearDepth(a)},Bb:function(a){V.clearStencil(a)},q:function(a,b,c,d){V.colorMask(!!a,!!b,!!c,!!d)},ta:function(a){V.compileShader(T[a])},Ba:function(a,b,c,d,e,h,g,m){V.compressedTexImage2D(a,b,c,d,e,h,m?C.subarray(m,m+g):null)},ya:function(){var a=zb(Q),b=V.createProgram();b.name=a;b.mc=b.kc=b.lc=0;b.pc=1;Q[a]=b;return a},va:function(a){var b=zb(T);T[b]=V.createShader(a);return b},I:function(a){V.cullFace(a)},Ma:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=ub[d];
e&&(V.deleteBuffer(e),e.name=0,ub[d]=null)}},d:function(a,b){for(var c=0;c<a;++c){var d=E[b+4*c>>2],e=vb[d];e&&(V.deleteFramebuffer(e),e.name=0,vb[d]=null)}},r:function(a){if(a){var b=Q[a];b?(V.deleteProgram(b),b.name=0,Q[a]=null):U(1281)}},R:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=R[d];e&&(V.deleteRenderbuffer(e),e.name=0,R[d]=null)}},x:function(a){if(a){var b=T[a];b?(V.deleteShader(b),T[a]=null):U(1281)}},La:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=S[d];e&&(V.deleteTexture(e),
e.name=0,S[d]=null)}},A:function(a){V.depthFunc(a)},z:function(a){V.depthMask(!!a)},e:function(a){V.disable(a)},P:function(a){V.disableVertexAttribArray(a)},jb:function(a,b,c){V.drawArrays(a,b,c)},kb:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},lb:function(a,b,c,d){V.drawElements(a,b,c,d)},mb:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},i:function(a){V.enable(a)},xb:function(a){V.enableVertexAttribArray(a)},m:function(a,b,c,d){V.framebufferRenderbuffer(a,b,c,R[d])},g:function(a,b,
c,d,e){V.framebufferTexture2D(a,b,c,S[d],e)},J:function(a){V.frontFace(a)},Ha:function(a,b){Gb(a,b,"createBuffer",ub)},o:function(a,b){Gb(a,b,"createFramebuffer",vb)},Fa:function(a,b){Gb(a,b,"createRenderbuffer",R)},Ca:function(a,b){Gb(a,b,"createTexture",S)},ra:function(a,b){return V.getAttribLocation(Q[a],D(b))},f:function(a,b){Hb(a,b)},wa:function(a,b,c,d){a=V.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,C,d,b):0;c&&(E[c>>2]=b)},G:function(a,b,c){if(c)if(a>=tb)U(1281);else if(a=
Q[a],35716==b)a=V.getProgramInfoLog(a),null===a&&(a="(unknown error)"),E[c>>2]=a.length+1;else if(35719==b){if(!a.mc)for(b=0;b<V.getProgramParameter(a,35718);++b)a.mc=Math.max(a.mc,V.getActiveUniform(a,b).name.length+1);E[c>>2]=a.mc}else if(35722==b){if(!a.kc)for(b=0;b<V.getProgramParameter(a,35721);++b)a.kc=Math.max(a.kc,V.getActiveAttrib(a,b).name.length+1);E[c>>2]=a.kc}else if(35381==b){if(!a.lc)for(b=0;b<V.getProgramParameter(a,35382);++b)a.lc=Math.max(a.lc,V.getActiveUniformBlockName(a,b).length+
1);E[c>>2]=a.lc}else E[c>>2]=V.getProgramParameter(a,b);else U(1281)},sa:function(a,b,c,d){a=V.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,C,d,b):0;c&&(E[c>>2]=b)},D:function(a,b,c){c?35716==b?(a=V.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),E[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(T[a]),E[c>>2]=a?a.length+1:0):E[c>>2]=V.getShaderParameter(T[a],b):U(1281)},Na:function(a){var b=xb[a];if(!b){switch(a){case 7939:b=V.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+
d}));b=Ib(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=V.getParameter(a))||U(1280);b=b&&Ib(b);break;case 7938:b=Ib("OpenGL ES 2.0 ("+V.getParameter(7938)+")");break;case 35724:b=V.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Ib(b);break;default:U(1280)}xb[a]=b}return b},t:function(a,b){b=D(b);if(a=Q[a]){var c=a,d=c.ic,e=c.Cc,h;if(!d)for(c.ic=d={},c.Bc={},h=0;h<V.getProgramParameter(c,
35718);++h){var g=V.getActiveUniform(c,h);var m=g.name;g=g.size;var n=Jb(m);n=0<n?m.slice(0,n):m;var p=c.pc;c.pc+=g;e[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.Bc[p++]=n}c=a.ic;d=0;e=b;h=Jb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Cc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||V.getUniformLocation(a,b)))return d}else U(1281);return-1},xa:function(a){a=Q[a];V.linkProgram(a);a.ic=0;a.Cc={}},K:function(a,b){V.polygonOffset(a,b)},Da:function(a,b,c,d){V.renderbufferStorage(a,b,c,d)},s:function(a,b,c,
d){V.scissor(a,b,c,d)},ua:function(a,b,c,d){for(var e="",h=0;h<b;++h){var g=d?E[d+4*h>>2]:-1;e+=D(E[c+4*h>>2],0>g?void 0:g)}V.shaderSource(T[a],e)},Ka:function(a,b,c){V.stencilFunc(a,b,c)},pa:function(a,b,c,d){V.stencilFuncSeparate(a,b,c,d)},y:function(a){V.stencilMask(a)},Ja:function(a,b,c){V.stencilOp(a,b,c)},oa:function(a,b,c,d){V.stencilOpSeparate(a,b,c,d)},Aa:function(a,b,c,d,e,h,g,m,n){V.texImage2D(a,b,c,d,e,h,g,m,n?Kb(m,g,d,e,n):null)},k:function(a,b,c){V.texParameteri(a,b,c)},ib:function(a,
b,c,d,e,h,g,m,n){var p=null;n&&(p=Kb(m,g,e,h,n));V.texSubImage2D(a,b,c,d,e,h,g,m,p)},vb:function(a,b,c){if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=F[c+4*e>>2];else d=F.subarray(c>>2,c+4*b>>2);V.uniform1fv(W(a),d)},F:function(a,b){V.uniform1i(W(a),b)},rb:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=E[c+4*e>>2];else d=E.subarray(c>>2,c+4*b>>2);V.uniform1iv(W(a),d)},ub:function(a,b,c){if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2];else d=F.subarray(c>>
2,c+8*b>>2);V.uniform2fv(W(a),d)},qb:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2];else d=E.subarray(c>>2,c+8*b>>2);V.uniform2iv(W(a),d)},tb:function(a,b,c){if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2];else d=F.subarray(c>>2,c+12*b>>2);V.uniform3fv(W(a),d)},pb:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2],d[e+2]=E[c+(4*e+8)>>2];else d=
E.subarray(c>>2,c+12*b>>2);V.uniform3iv(W(a),d)},sb:function(a,b,c){if(72>=b){var d=X[4*b-1],e=F;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=F.subarray(c>>2,c+16*b>>2);V.uniform4fv(W(a),d)},ob:function(a,b,c){if(72>=b)for(var d=Y[4*b-1],e=0;e<4*b;e+=4)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2],d[e+2]=E[c+(4*e+8)>>2],d[e+3]=E[c+(4*e+12)>>2];else d=E.subarray(c>>2,c+16*b>>2);V.uniform4iv(W(a),d)},nb:function(a,b,c,d){if(18>=b){var e=X[16*b-1],h=F;
d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=h[m+13];e[g+14]=h[m+14];e[g+15]=h[m+15]}}else e=F.subarray(d>>2,d+64*b>>2);V.uniformMatrix4fv(W(a),!!c,e)},l:function(a){a=Q[a];V.useProgram(a);V.Dc=a},yb:function(a,b){V.vertexAttribDivisor(a,b)},zb:function(a,b,c,d,e,h){V.vertexAttribPointer(a,b,c,!!d,e,h)},j:function(a,
b,c,d){V.viewport(a,b,c,d)},Xa:function(){f.vc=function(a){0!=Nb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.vc)},Wa:function(){f.Ac=function(a){a=a.clipboardData.getData("text");ma("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",f.Ac)},Va:function(a){f.Sc=[];a=D(a);a=document.getElementById(a);f.wc=function(b){b.stopPropagation();b.preventDefault()};f.xc=function(b){b.stopPropagation();b.preventDefault()};f.yc=function(b){b.stopPropagation();
b.preventDefault()};f.zc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;f.Tc=c;Ob(c.length);var d;for(d=0;d<c.length;d++)ma("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Pb(b.clientX,b.clientY)};a.addEventListener("dragenter",f.wc,!1);a.addEventListener("dragleave",f.xc,!1);a.addEventListener("dragover",f.yc,!1);a.addEventListener("drop",f.zc,!1)},Pa:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},w:function(){var a=
document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Qb()});document.body.append(a)},v:function(){document.getElementById("_sokol_app_input_element").focus()},Ya:function(a){a=D(a);f.hc=document.getElementById(a);f.hc||console.log("sokol_app.h: invalid target:"+a);f.hc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Ua:function(){window.removeEventListener("beforeunload",
f.vc)},Ta:function(){window.removeEventListener("paste",f.Ac)},Ra:function(a){a=D(a);a=document.getElementById(a);a.removeEventListener("dragenter",f.wc);a.removeEventListener("dragleave",f.xc);a.removeEventListener("dragover",f.yc);a.removeEventListener("drop",f.zc)},B:function(){f.hc&&f.hc.requestPointerLock&&f.hc.requestPointerLock()},Oa:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(C.subarray(c,c+a*b*4));
e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},u:function(){document.getElementById("_sokol_app_input_element").blur()},Qa:function(a){a=D(a);var b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=
1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},fb:function(){return f.ec?f.ec.bufferSize:0},hb:function(a,b,c){f.$b=null;f.ec=null;"undefined"!==typeof AudioContext?f.$b=new AudioContext({sampleRate:a,latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?f.$b=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(f.$b=null,console.log("sokol_audio.h: no WebAudio support"));return f.$b?(console.log("sokol_audio.h: sample rate ",
f.$b.sampleRate),f.ec=f.$b.createScriptProcessor(c,0,b),f.ec.onaudioprocess=function(d){var e=d.outputBuffer.length,h=Rb(e);if(h)for(var g=d.outputBuffer.numberOfChannels,m=0;m<g;m++)for(var n=d.outputBuffer.getChannelData(m),p=0;p<e;p++)n[p]=F[(h>>2)+(g*p+m)]},f.ec.connect(f.$b.destination),a=function(){f.$b&&"suspended"===f.$b.state&&f.$b.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),
1):0},gb:function(){return f.$b?f.$b.sampleRate:0},ma:function(){null!==f.$b&&(f.ec&&f.ec.disconnect(),f.$b.close(),f.$b=null,f.ec=null)},Eb:function(){if(f.$b)return"suspended"===f.$b.state?1:0},la:function(){return navigator.userAgent.includes("Macintosh")?1:0}};
(function(){function a(e){f.asm=e.exports;ka=f.asm.Fb;ya();za=f.asm.Wb;Ba.unshift(f.asm.Gb);H--;f.monitorRunDependencies&&f.monitorRunDependencies(H);0==H&&(null!==Ga&&(clearInterval(Ga),Ga=null),I&&(e=I,I=null,e()))}function b(e){a(e.instance)}function c(e){return Ka().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(e,function(h){y("failed to asynchronously prepare wasm: "+h);ja(h)})}var d={a:Sb};H++;f.monitorRunDependencies&&f.monitorRunDependencies(H);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return y("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return z||"function"!=typeof WebAssembly.instantiateStreaming||Ha()||J.startsWith("file://")||"function"!=typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(h){y("wasm streaming compile failed: "+h);y("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.Gb).apply(null,arguments)};var Qb=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Qb=f.__sapp_emsc_notify_keyboard_hidden=f.asm.Hb).apply(null,arguments)};f.__sapp_emsc_onpaste=function(){return(f.__sapp_emsc_onpaste=f.asm.Ib).apply(null,arguments)};
var Nb=f.__sapp_html5_get_ask_leave_site=function(){return(Nb=f.__sapp_html5_get_ask_leave_site=f.asm.Jb).apply(null,arguments)},Ob=f.__sapp_emsc_begin_drop=function(){return(Ob=f.__sapp_emsc_begin_drop=f.asm.Kb).apply(null,arguments)};f.__sapp_emsc_drop=function(){return(f.__sapp_emsc_drop=f.asm.Lb).apply(null,arguments)};var Pb=f.__sapp_emsc_end_drop=function(){return(Pb=f.__sapp_emsc_end_drop=f.asm.Mb).apply(null,arguments)};
f.__sapp_emsc_invoke_fetch_cb=function(){return(f.__sapp_emsc_invoke_fetch_cb=f.asm.Nb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Ob).apply(null,arguments)};var Rb=f.__saudio_emsc_pull=function(){return(Rb=f.__saudio_emsc_pull=f.asm.Pb).apply(null,arguments)};f.__sargs_add_kvp=function(){return(f.__sargs_add_kvp=f.asm.Qb).apply(null,arguments)};f.__sfetch_emsc_head_response=function(){return(f.__sfetch_emsc_head_response=f.asm.Rb).apply(null,arguments)};
f.__sfetch_emsc_get_response=function(){return(f.__sfetch_emsc_get_response=f.asm.Sb).apply(null,arguments)};f.__sfetch_emsc_failed_http_status=function(){return(f.__sfetch_emsc_failed_http_status=f.asm.Tb).apply(null,arguments)};f.__sfetch_emsc_failed_buffer_too_small=function(){return(f.__sfetch_emsc_failed_buffer_too_small=f.asm.Ub).apply(null,arguments)};
var O=f._malloc=function(){return(O=f._malloc=f.asm.Vb).apply(null,arguments)},oa=f.stackSave=function(){return(oa=f.stackSave=f.asm.Xb).apply(null,arguments)},pa=f.stackRestore=function(){return(pa=f.stackRestore=f.asm.Yb).apply(null,arguments)},A=f.stackAlloc=function(){return(A=f.stackAlloc=f.asm.Zb).apply(null,arguments)},Tb;function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}I=function Ub(){Tb||Vb();Tb||(I=Ub)};
function Vb(a){function b(){if(!Tb&&(Tb=!0,f.calledRun=!0,!la)){La(Ba);La(Ca);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Wb){var c=a,d=f._main;c=c||[];var e=c.length+1,h=A(4*(e+1));E[h>>2]=ta(ca);for(var g=1;g<e;g++)E[(h>>2)+g]=ta(c[g-1]);E[(h>>2)+e]=0;try{var m=d(e,h);if(!noExitRuntime){if(f.onExit)f.onExit(m);la=!0}k(m,new x(m))}catch(n){n instanceof x||"unwind"==n||k(1,n)}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),
Ea.unshift(c);La(Ea)}}a=a||ba;if(!(0<H)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Fa();La(Aa);0<H||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Vb;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Wb=!0;f.noInitialRun&&(Wb=!1);Vb();
