
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign,ba=aa({},e),ca=[],da="./this.program",k=(a,b)=>{throw b;},ea="object"===typeof window,l="function"===typeof importScripts,fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,q="",ha,u,v,fs,w,ia;
if(fa)q=l?require("path").dirname(q)+"/":__dirname+"/",ia=function(){w||(fs=require("fs"),w=require("path"))},ha=function(a,b){ia();a=w.normalize(a);return fs.readFileSync(a,b?null:"utf8")},v=function(a){a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a},u=function(a,b,c){ia();a=w.normalize(a);fs.readFile(a,function(d,f){d?c(d):b(f.buffer)})},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",
function(a){if(!(a instanceof x))throw a;}),process.on("unhandledRejection",function(a){throw a;}),k=(a,b)=>{if(noExitRuntime||0<ja)throw process.exitCode=a,b;b instanceof x||y("exiting due to exception: "+b);process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(ea||l)l?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ha=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(v=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ka=e.print||console.log.bind(console),y=e.printErr||console.warn.bind(console);aa(e,ba);
ba=null;e.arguments&&(ca=e.arguments);e.thisProgram&&(da=e.thisProgram);e.quit&&(k=e.quit);var z;e.wasmBinary&&(z=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var la,ma=!1;
function na(a,b,c){var d={string:function(n){var p=0;if(null!==n&&void 0!==n&&0!==n){var r=(n.length<<2)+1;p=B(r);C(n,D,p,r)}return p},array:function(n){var p=B(n.length);oa.set(n,p);return p}};a=e["_"+a];var f=[],h=0;if(c)for(var g=0;g<c.length;g++){var m=d[b[g]];m?(0===h&&(h=pa()),f[g]=m(c[g])):f[g]=c[g]}b=a.apply(null,f);b=function(n){0!==h&&qa(h);return n}(b)}var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var g=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|g:(f&7)<<18|h<<12|g<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function E(a,b){return a?sa(D,a,b):""}
function C(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ua(a){var b=ta(a)+1,c=B(b);C(a,oa,c,b);return c}var va,oa,D,wa,xa,F,ya,G,H;
function za(){var a=la.buffer;va=a;e.HEAP8=oa=new Int8Array(a);e.HEAP16=wa=new Int16Array(a);e.HEAP32=F=new Int32Array(a);e.HEAPU8=D=new Uint8Array(a);e.HEAPU16=xa=new Uint16Array(a);e.HEAPU32=ya=new Uint32Array(a);e.HEAPF32=G=new Float32Array(a);e.HEAPF64=H=new Float64Array(a)}var Aa,Ba=[],Ca=[],Da=[],Ea=[],Fa=[],ja=0;function Ga(){var a=e.preRun.shift();Ba.unshift(a)}var I=0,Ha=null,J=null;e.preloadedImages={};e.preloadedAudios={};
function A(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";y(a);ma=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ia(){return K.startsWith("data:application/octet-stream;base64,")}var K;K="pengo-ui.wasm";if(!Ia()){var Ja=K;K=e.locateFile?e.locateFile(Ja,q):q+Ja}function Ka(){var a=K;try{if(a==K&&z)return new Uint8Array(z);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function La(){if(!z&&(ea||l)){if("function"===typeof fetch&&!K.startsWith("file://"))return fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Ka()});if(u)return new Promise(function(a,b){u(K,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ka()})}
function L(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Kc;"number"===typeof c?void 0===b.jc?M(c)():M(c)(b.jc):c(void 0===b.jc?null:b.jc)}}}var Ma=[];function M(a){var b=Ma[a];b||(a>=Ma.length&&(Ma.length=a+1),Ma[a]=b=Aa.get(a));return b}var Na=[null,[],[]],Oa={},Pa=0;function Qa(){for(var a=N.length-1;0<=a;--a)Ra(a);N=[];Sa=[]}var Sa=[];function Ta(){if(Pa&&Ua.dc)for(var a=0;a<Sa.length;++a){var b=Sa[a];Sa.splice(a,1);--a;b.Tc.apply(null,b.Gc)}}var N=[];
function Ra(a){var b=N[a];b.target.removeEventListener(b.Xb,b.Bc,b.Yb);N.splice(a,1)}function O(a){function b(d){++Pa;Ua=a;Ta();a.$b(d);Ta();--Pa}if(a.Zb)a.Bc=b,a.target.addEventListener(a.Xb,b,a.Yb),N.push(a),Va||(Ea.push(Qa),Va=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Xb==a.Xb&&Ra(c--)}function Wa(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Va,Ua,Xa,Ya,Za,$a,ab,bb,cb,db=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function P(a){a=2<a?E(a):a;return db[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function eb(a){return 0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}var fb;fb=fa?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();
function gb(a,b,c,d,f,h){Xa||(Xa=Q(256));a={target:P(a),Xb:h,Zb:d,$b:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Xa;C(Wa(g.target),D,n+0,128);C(m,D,n+128,128);M(d)(f,n,b)&&g.preventDefault()},Yb:c};O(a)}
function hb(a,b,c,d,f,h){Ya||(Ya=Q(176));a={target:P(a),dc:!0,Xb:h,Zb:d,$b:function(g){var m=Ya;H[m>>3]=g.timeStamp;var n=m>>2;F[n+2]=g.location;F[n+3]=g.ctrlKey;F[n+4]=g.shiftKey;F[n+5]=g.altKey;F[n+6]=g.metaKey;F[n+7]=g.repeat;F[n+8]=g.charCode;F[n+9]=g.keyCode;F[n+10]=g.which;C(g.key||"",D,m+44,32);C(g.code||"",D,m+76,32);C(g.char||"",D,m+108,32);C(g.locale||"",D,m+140,32);M(d)(f,m,b)&&g.preventDefault()},Yb:c};O(a)}
function ib(a,b,c){H[a>>3]=b.timeStamp;a>>=2;F[a+2]=b.screenX;F[a+3]=b.screenY;F[a+4]=b.clientX;F[a+5]=b.clientY;F[a+6]=b.ctrlKey;F[a+7]=b.shiftKey;F[a+8]=b.altKey;F[a+9]=b.metaKey;wa[2*a+20]=b.button;wa[2*a+21]=b.buttons;F[a+11]=b.movementX;F[a+12]=b.movementY;c=eb(c);F[a+13]=b.clientX-c.left;F[a+14]=b.clientY-c.top}
function R(a,b,c,d,f,h){Za||(Za=Q(72));a=P(a);O({target:a,dc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Xb:h,Zb:d,$b:function(g){g=g||event;ib(Za,g,a);M(d)(f,Za,b)&&g.preventDefault()},Yb:c})}function jb(a,b,c,d,f){$a||($a=Q(260));O({target:a,Xb:f,Zb:d,$b:function(h){h=h||event;var g=$a,m=document.pointerLockElement||document.lc||document.nc||document.mc;F[g>>2]=!!m;var n=m&&m.id?m.id:"";C(Wa(m),D,g+4,128);C(n,D,g+132,128);M(d)(20,g,b)&&h.preventDefault()},Yb:c})}
function kb(a,b,c,d,f){O({target:a,Xb:f,Zb:d,$b:function(h){h=h||event;M(d)(38,0,b)&&h.preventDefault()},Yb:c})}
function lb(a,b,c,d){ab||(ab=Q(36));a=P(a);O({target:a,Xb:"resize",Zb:d,$b:function(f){f=f||event;if(f.target==a){var h=document.body;if(h){var g=ab;F[g>>2]=f.detail;F[g+4>>2]=h.clientWidth;F[g+8>>2]=h.clientHeight;F[g+12>>2]=innerWidth;F[g+16>>2]=innerHeight;F[g+20>>2]=outerWidth;F[g+24>>2]=outerHeight;F[g+28>>2]=pageXOffset;F[g+32>>2]=pageYOffset;M(d)(10,g,b)&&f.preventDefault()}}},Yb:c})}
function mb(a,b,c,d,f,h){bb||(bb=Q(1696));a=P(a);O({target:a,dc:"touchstart"==h||"touchend"==h,Xb:h,Zb:d,$b:function(g){for(var m,n={},p=g.touches,r=0;r<p.length;++r)m=p[r],m.qc=m.rc=0,n[m.identifier]=m;for(r=0;r<g.changedTouches.length;++r)m=g.changedTouches[r],m.qc=1,n[m.identifier]=m;for(r=0;r<g.targetTouches.length;++r)n[g.targetTouches[r].identifier].rc=1;p=bb;H[p>>3]=g.timeStamp;var t=p>>2;F[t+3]=g.ctrlKey;F[t+4]=g.shiftKey;F[t+5]=g.altKey;F[t+6]=g.metaKey;t+=7;var pb=eb(a),qb=0;for(r in n)if(m=
n[r],F[t]=m.identifier,F[t+1]=m.screenX,F[t+2]=m.screenY,F[t+3]=m.clientX,F[t+4]=m.clientY,F[t+5]=m.pageX,F[t+6]=m.pageY,F[t+7]=m.qc,F[t+8]=m.rc,F[t+9]=m.clientX-pb.left,F[t+10]=m.clientY-pb.top,t+=13,31<++qb)break;F[p+8>>2]=qb;M(d)(f,p,b)&&g.preventDefault()},Yb:c})}function nb(a,b,c,d,f,h){a={target:P(a),Xb:h,Zb:d,$b:function(g){g=g||event;M(d)(f,0,b)&&g.preventDefault()},Yb:c};O(a)}
function ob(a,b,c,d){cb||(cb=Q(104));O({target:a,dc:!0,Xb:"wheel",Zb:d,$b:function(f){f=f||event;var h=cb;ib(h,f,a);H[h+72>>3]=f.deltaX;H[h+80>>3]=f.deltaY;H[h+88>>3]=f.deltaZ;F[h+96>>2]=f.deltaMode;M(d)(9,h,b)&&f.preventDefault()},Yb:c})}
function rb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,h){b.drawArraysInstancedANGLE(c,d,f,h)},a.drawElementsInstanced=function(c,d,f,h,g){b.drawElementsInstancedANGLE(c,d,f,h,g)})}
function sb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function tb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function ub(a){a.Oc=a.getExtension("WEBGL_multi_draw")}
var vb=1,wb=[],S=[],xb=[],T=[],U=[],V=[],yb=[],zb={};function W(a){Ab||(Ab=a)}function Bb(a){for(var b=vb++,c=a.length;c<b;c++)a[c]=null;return b}function Cb(a,b){a.pc||(a.pc=a.getContext,a.getContext=function(d,f){f=a.pc(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?Db(c,b):0}function Db(a,b){var c=Bb(yb),d={Mc:c,attributes:b,version:b.Ec,ic:a};a.canvas&&(a.canvas.Fc=d);yb[c]=d;("undefined"===typeof b.oc||b.oc)&&Eb(d);return c}
function Eb(a){a||(a=Fb);if(!a.Dc){a.Dc=!0;var b=a.ic;rb(b);sb(b);tb(b);b.Ic=b.getExtension("EXT_disjoint_timer_query");ub(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Ab,Fb,Gb=["default","low-power","high-performance"];function Hb(a,b,c,d){for(var f=0;f<a;f++){var h=X[c](),g=h&&Bb(d);h?(h.name=g,d[g]=h):W(1282);F[b+4*f>>2]=g}}
function Ib(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=X.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=X.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:W(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)F[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){W(1280);y("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:W(1280);y("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}F[b>>2]=c}else W(1281)}function Jb(a){var b=ta(a)+1,c=Q(b);C(a,D,c,b);return c}
function Kb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Lb(a,b,c,d,f){a-=5120;a=1==a?D:4==a?F:6==a?G:5==a||28922==a?ya:xa;var h=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(f>>h,f+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<h)+4-1&-4)>>h)}function Y(a){var b=X.Ac;if(b){var c=b.cc[a];"number"===typeof c&&(b.cc[a]=c=X.getUniformLocation(b,b.yc[a]+(0<c?"["+c+"]":"")));return c}W(1282)}for(var Z=[],X,Mb=new Float32Array(288),Nb=0;288>Nb;++Nb)Z[Nb]=Mb.subarray(0,Nb+1);
var Tb={ka:function(){return 0},db:function(){return 0},eb:function(){},ab:function(){A("")},Q:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},U:function(a,b,c){a=P(a);if(!a)return-4;a=eb(a);H[b>>3]=a.width;H[c>>3]=a.height;return 0},x:fb,_a:function(a,b,c){D.copyWithin(a,b,b+c)},Ia:function(a,b){function c(d){M(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},$a:function(a){var b=D.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+
.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{la.grow(Math.min(2147483648,d)-va.byteLength+65535>>>16);za();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},V:function(a,b,c,d){gb(a,b,c,d,12,"blur");return 0},O:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},W:function(a,b,c,d){gb(a,b,c,d,13,"focus");return 0},da:function(a,b,c,d){hb(a,b,c,d,2,"keydown");return 0},ba:function(a,b,c,d){hb(a,b,c,d,1,"keypress");return 0},ca:function(a,
b,c,d){hb(a,b,c,d,3,"keyup");return 0},na:function(a,b,c,d){R(a,b,c,d,5,"mousedown");return 0},ga:function(a,b,c,d){R(a,b,c,d,33,"mouseenter");return 0},fa:function(a,b,c,d){R(a,b,c,d,34,"mouseleave");return 0},ha:function(a,b,c,d){R(a,b,c,d,8,"mousemove");return 0},ja:function(a,b,c,d){R(a,b,c,d,6,"mouseup");return 0},Y:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.lc||document.body.nc||document.body.mc))return-1;a=P(a);if(!a)return-4;jb(a,b,c,
d,"pointerlockchange");jb(a,b,c,d,"mozpointerlockchange");jb(a,b,c,d,"webkitpointerlockchange");jb(a,b,c,d,"mspointerlockchange");return 0},X:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.lc||document.body.nc||document.body.mc))return-1;a=P(a);if(!a)return-4;kb(a,b,c,d,"pointerlockerror");kb(a,b,c,d,"mozpointerlockerror");kb(a,b,c,d,"webkitpointerlockerror");kb(a,b,c,d,"mspointerlockerror");return 0},Sa:function(a,b,c,d){lb(a,b,c,d);return 0},Z:function(a,b,c,d){mb(a,
b,c,d,25,"touchcancel");return 0},_:function(a,b,c,d){mb(a,b,c,d,23,"touchend");return 0},$:function(a,b,c,d){mb(a,b,c,d,24,"touchmove");return 0},aa:function(a,b,c,d){mb(a,b,c,d,22,"touchstart");return 0},T:function(a,b,c,d){nb(a,b,c,d,31,"webglcontextlost");return 0},S:function(a,b,c,d){nb(a,b,c,d,32,"webglcontextrestored");return 0},ea:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(ob(a,b,c,d),0):-1},E:function(a,b){b>>=2;b={alpha:!!F[b],depth:!!F[b+1],stencil:!!F[b+2],antialias:!!F[b+
3],premultipliedAlpha:!!F[b+4],preserveDrawingBuffer:!!F[b+5],powerPreference:Gb[F[b+6]],failIfMajorPerformanceCaveat:!!F[b+7],Ec:F[b+8],Nc:F[b+9],oc:F[b+10],Cc:F[b+11],Pc:F[b+12],Qc:F[b+13]};a=P(a);return!a||b.Cc?0:Cb(a,b)},sb:function(a,b){a=yb[a];b=E(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&rb(X);"OES_vertex_array_object"==b&&sb(X);"WEBGL_draw_buffers"==b&&tb(X);"WEBGL_multi_draw"==b&&ub(X);return!!a.ic.getExtension(b)},za:function(a){a>>=2;for(var b=0;14>b;++b)F[a+
b]=0;F[a]=F[a+1]=F[a+3]=F[a+4]=F[a+8]=F[a+10]=1},zb:function(a){Fb=yb[a];e.Hc=X=Fb&&Fb.ic;return!a||X?0:-5},ia:function(){return 0},cb:function(a,b,c,d){a=Oa.Lc(a);b=Oa.Jc(a,b,c);F[d>>2]=b;return 0},Za:function(){},bb:function(a,b,c,d){for(var f=0,h=0;h<c;h++){var g=F[b>>2],m=F[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=D[g+n],r=Na[a];0===p||10===p?((1===a?ka:y)(sa(r,0)),r.length=0):r.push(p)}f+=m}F[d>>2]=f;return 0},b:function(a){X.activeTexture(a)},H:function(a,b){X.attachShader(S[a],V[b])},c:function(a,
b){X.bindBuffer(a,wb[b])},h:function(a,b){X.bindFramebuffer(a,xb[b])},Ea:function(a,b){X.bindRenderbuffer(a,T[b])},a:function(a,b){X.bindTexture(a,U[b])},L:function(a,b,c,d){X.blendColor(a,b,c,d)},M:function(a,b){X.blendEquationSeparate(a,b)},N:function(a,b,c,d){X.blendFuncSeparate(a,b,c,d)},Ga:function(a,b,c,d){X.bufferData(a,c?D.subarray(c,c+b):b,d)},l:function(a,b,c,d){X.bufferSubData(a,b,D.subarray(d,d+c))},o:function(a){return X.checkFramebufferStatus(a)},wb:function(a){X.clear(a)},yb:function(a,
b,c,d){X.clearColor(a,b,c,d)},qa:function(a){X.clearDepth(a)},xb:function(a){X.clearStencil(a)},q:function(a,b,c,d){X.colorMask(!!a,!!b,!!c,!!d)},ta:function(a){X.compileShader(V[a])},Ba:function(a,b,c,d,f,h,g,m){X.compressedTexImage2D(a,b,c,d,f,h,m?D.subarray(m,m+g):null)},ya:function(){var a=Bb(S),b=X.createProgram();b.name=a;b.hc=b.ec=b.fc=0;b.kc=1;S[a]=b;return a},va:function(a){var b=Bb(V);V[b]=X.createShader(a);return b},I:function(a){X.cullFace(a)},Ma:function(a,b){for(var c=0;c<a;c++){var d=
F[b+4*c>>2],f=wb[d];f&&(X.deleteBuffer(f),f.name=0,wb[d]=null)}},d:function(a,b){for(var c=0;c<a;++c){var d=F[b+4*c>>2],f=xb[d];f&&(X.deleteFramebuffer(f),f.name=0,xb[d]=null)}},r:function(a){if(a){var b=S[a];b?(X.deleteProgram(b),b.name=0,S[a]=null):W(1281)}},R:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],f=T[d];f&&(X.deleteRenderbuffer(f),f.name=0,T[d]=null)}},y:function(a){if(a){var b=V[a];b?(X.deleteShader(b),V[a]=null):W(1281)}},La:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],
f=U[d];f&&(X.deleteTexture(f),f.name=0,U[d]=null)}},B:function(a){X.depthFunc(a)},A:function(a){X.depthMask(!!a)},e:function(a){X.disable(a)},P:function(a){X.disableVertexAttribArray(a)},jb:function(a,b,c){X.drawArrays(a,b,c)},kb:function(a,b,c,d){X.drawArraysInstanced(a,b,c,d)},lb:function(a,b,c,d){X.drawElements(a,b,c,d)},mb:function(a,b,c,d,f){X.drawElementsInstanced(a,b,c,d,f)},i:function(a){X.enable(a)},tb:function(a){X.enableVertexAttribArray(a)},n:function(a,b,c,d){X.framebufferRenderbuffer(a,
b,c,T[d])},g:function(a,b,c,d,f){X.framebufferTexture2D(a,b,c,U[d],f)},J:function(a){X.frontFace(a)},Ha:function(a,b){Hb(a,b,"createBuffer",wb)},p:function(a,b){Hb(a,b,"createFramebuffer",xb)},Fa:function(a,b){Hb(a,b,"createRenderbuffer",T)},Ca:function(a,b){Hb(a,b,"createTexture",U)},ra:function(a,b){return X.getAttribLocation(S[a],E(b))},f:function(a,b){Ib(a,b)},wa:function(a,b,c,d){a=X.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,D,d,b):0;c&&(F[c>>2]=b)},G:function(a,b,
c){if(c)if(a>=vb)W(1281);else if(a=S[a],35716==b)a=X.getProgramInfoLog(a),null===a&&(a="(unknown error)"),F[c>>2]=a.length+1;else if(35719==b){if(!a.hc)for(b=0;b<X.getProgramParameter(a,35718);++b)a.hc=Math.max(a.hc,X.getActiveUniform(a,b).name.length+1);F[c>>2]=a.hc}else if(35722==b){if(!a.ec)for(b=0;b<X.getProgramParameter(a,35721);++b)a.ec=Math.max(a.ec,X.getActiveAttrib(a,b).name.length+1);F[c>>2]=a.ec}else if(35381==b){if(!a.fc)for(b=0;b<X.getProgramParameter(a,35382);++b)a.fc=Math.max(a.fc,
X.getActiveUniformBlockName(a,b).length+1);F[c>>2]=a.fc}else F[c>>2]=X.getProgramParameter(a,b);else W(1281)},sa:function(a,b,c,d){a=X.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,D,d,b):0;c&&(F[c>>2]=b)},D:function(a,b,c){c?35716==b?(a=X.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),F[c>>2]=a?a.length+1:0):35720==b?(a=X.getShaderSource(V[a]),F[c>>2]=a?a.length+1:0):F[c>>2]=X.getShaderParameter(V[a],b):W(1281)},Na:function(a){var b=zb[a];if(!b){switch(a){case 7939:b=
X.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Jb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=X.getParameter(a))||W(1280);b=b&&Jb(b);break;case 7938:b=Jb("OpenGL ES 2.0 ("+X.getParameter(7938)+")");break;case 35724:b=X.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Jb(b);break;default:W(1280)}zb[a]=b}return b},t:function(a,b){b=E(b);
if(a=S[a]){var c=a,d=c.cc,f=c.zc,h;if(!d)for(c.cc=d={},c.yc={},h=0;h<X.getProgramParameter(c,35718);++h){var g=X.getActiveUniform(c,h);var m=g.name;g=g.size;var n=Kb(m);n=0<n?m.slice(0,n):m;var p=c.kc;c.kc+=g;f[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.yc[p++]=n}c=a.cc;d=0;f=b;h=Kb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,f=b.slice(0,h));if((f=a.zc[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||X.getUniformLocation(a,b)))return d}else W(1281);return-1},xa:function(a){a=S[a];X.linkProgram(a);a.cc=0;a.zc={}},K:function(a,b){X.polygonOffset(a,
b)},Da:function(a,b,c,d){X.renderbufferStorage(a,b,c,d)},s:function(a,b,c,d){X.scissor(a,b,c,d)},ua:function(a,b,c,d){for(var f="",h=0;h<b;++h){var g=d?F[d+4*h>>2]:-1;f+=E(F[c+4*h>>2],0>g?void 0:g)}X.shaderSource(V[a],f)},Ka:function(a,b,c){X.stencilFunc(a,b,c)},pa:function(a,b,c,d){X.stencilFuncSeparate(a,b,c,d)},z:function(a){X.stencilMask(a)},Ja:function(a,b,c){X.stencilOp(a,b,c)},oa:function(a,b,c,d){X.stencilOpSeparate(a,b,c,d)},Aa:function(a,b,c,d,f,h,g,m,n){X.texImage2D(a,b,c,d,f,h,g,m,n?Lb(m,
g,d,f,n):null)},k:function(a,b,c){X.texParameteri(a,b,c)},ib:function(a,b,c,d,f,h,g,m,n){var p=null;n&&(p=Lb(m,g,f,h,n));X.texSubImage2D(a,b,c,d,f,h,g,m,p)},rb:function(a,b,c){if(288>=b)for(var d=Z[b-1],f=0;f<b;++f)d[f]=G[c+4*f>>2];else d=G.subarray(c>>2,c+4*b>>2);X.uniform1fv(Y(a),d)},F:function(a,b){X.uniform1i(Y(a),b)},qb:function(a,b,c){if(144>=b)for(var d=Z[2*b-1],f=0;f<2*b;f+=2)d[f]=G[c+4*f>>2],d[f+1]=G[c+(4*f+4)>>2];else d=G.subarray(c>>2,c+8*b>>2);X.uniform2fv(Y(a),d)},pb:function(a,b,c){if(96>=
b)for(var d=Z[3*b-1],f=0;f<3*b;f+=3)d[f]=G[c+4*f>>2],d[f+1]=G[c+(4*f+4)>>2],d[f+2]=G[c+(4*f+8)>>2];else d=G.subarray(c>>2,c+12*b>>2);X.uniform3fv(Y(a),d)},ob:function(a,b,c){if(72>=b){var d=Z[4*b-1],f=G;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=f[g];d[h+1]=f[g+1];d[h+2]=f[g+2];d[h+3]=f[g+3]}}else d=G.subarray(c>>2,c+16*b>>2);X.uniform4fv(Y(a),d)},nb:function(a,b,c,d){if(18>=b){var f=Z[16*b-1],h=G;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;f[g]=h[m];f[g+1]=h[m+1];f[g+2]=h[m+2];f[g+3]=h[m+3];f[g+
4]=h[m+4];f[g+5]=h[m+5];f[g+6]=h[m+6];f[g+7]=h[m+7];f[g+8]=h[m+8];f[g+9]=h[m+9];f[g+10]=h[m+10];f[g+11]=h[m+11];f[g+12]=h[m+12];f[g+13]=h[m+13];f[g+14]=h[m+14];f[g+15]=h[m+15]}}else f=G.subarray(d>>2,d+64*b>>2);X.uniformMatrix4fv(Y(a),!!c,f)},m:function(a){a=S[a];X.useProgram(a);X.Ac=a},ub:function(a,b){X.vertexAttribDivisor(a,b)},vb:function(a,b,c,d,f,h){X.vertexAttribPointer(a,b,c,!!d,f,h)},j:function(a,b,c,d){X.viewport(a,b,c,d)},Xa:function(){e.sc=function(a){0!=Ob()&&(a.preventDefault(),a.returnValue=
" ")};window.addEventListener("beforeunload",e.sc)},Wa:function(){e.xc=function(a){a=a.clipboardData.getData("text");na("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",e.xc)},Va:function(a){e.Rc=[];a=E(a);a=document.getElementById(a);e.tc=function(b){b.stopPropagation();b.preventDefault()};e.uc=function(b){b.stopPropagation();b.preventDefault()};e.vc=function(b){b.stopPropagation();b.preventDefault()};e.wc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;
e.Sc=c;Pb(c.length);var d;for(d=0;d<c.length;d++)na("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Qb(b.clientX,b.clientY)};a.addEventListener("dragenter",e.tc,!1);a.addEventListener("dragleave",e.uc,!1);a.addEventListener("dragover",e.vc,!1);a.addEventListener("drop",e.wc,!1)},Pa:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},w:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";
a.addEventListener("focusout",function(){Rb()});document.body.append(a)},v:function(){document.getElementById("_sokol_app_input_element").focus()},Ya:function(a){a=E(a);e.bc=document.getElementById(a);e.bc||console.log("sokol_app.h: invalid target:"+a);e.bc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Ua:function(){window.removeEventListener("beforeunload",e.sc)},Ta:function(){window.removeEventListener("paste",e.xc)},Ra:function(a){a=E(a);a=document.getElementById(a);
a.removeEventListener("dragenter",e.tc);a.removeEventListener("dragleave",e.uc);a.removeEventListener("dragover",e.vc);a.removeEventListener("drop",e.wc)},C:function(){e.bc&&e.bc.requestPointerLock&&e.bc.requestPointerLock()},Oa:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(D.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();
document.head.appendChild(a)},u:function(){document.getElementById("_sokol_app_input_element").blur()},Qa:function(a){a=E(a);var b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},fb:function(){return e.ac?
e.ac.bufferSize:0},hb:function(a,b,c){e.Wb=null;e.ac=null;"undefined"!==typeof AudioContext?e.Wb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?e.Wb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(e.Wb=null,console.log("sokol_audio.h: no WebAudio support"));return e.Wb?(console.log("sokol_audio.h: sample rate ",e.Wb.sampleRate),e.ac=e.Wb.createScriptProcessor(c,0,b),e.ac.onaudioprocess=function(d){var f=d.outputBuffer.length,h=
Sb(f);if(h)for(var g=d.outputBuffer.numberOfChannels,m=0;m<g;m++)for(var n=d.outputBuffer.getChannelData(m),p=0;p<f;p++)n[p]=G[(h>>2)+(g*p+m)]},e.ac.connect(e.Wb.destination),a=function(){e.Wb&&"suspended"===e.Wb.state&&e.Wb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},gb:function(){return e.Wb?e.Wb.sampleRate:0},ma:function(){null!==e.Wb&&(e.ac&&e.ac.disconnect(),e.Wb.close(),e.Wb=
null,e.ac=null)},Ab:function(){if(e.Wb)return"suspended"===e.Wb.state?1:0},la:function(){return navigator.userAgent.includes("Macintosh")?1:0}};
(function(){function a(f){e.asm=f.exports;la=e.asm.Bb;za();Aa=e.asm.Vb;Ca.unshift(e.asm.Cb);I--;e.monitorRunDependencies&&e.monitorRunDependencies(I);0==I&&(null!==Ha&&(clearInterval(Ha),Ha=null),J&&(f=J,J=null,f()))}function b(f){a(f.instance)}function c(f){return La().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(f,function(h){y("failed to asynchronously prepare wasm: "+h);A(h)})}var d={a:Tb};I++;e.monitorRunDependencies&&e.monitorRunDependencies(I);if(e.instantiateWasm)try{return e.instantiateWasm(d,
a)}catch(f){return y("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return z||"function"!==typeof WebAssembly.instantiateStreaming||Ia()||K.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(h){y("wasm streaming compile failed: "+h);y("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.Cb).apply(null,arguments)};var Rb=e.__sapp_emsc_notify_keyboard_hidden=function(){return(Rb=e.__sapp_emsc_notify_keyboard_hidden=e.asm.Db).apply(null,arguments)};e.__sapp_emsc_onpaste=function(){return(e.__sapp_emsc_onpaste=e.asm.Eb).apply(null,arguments)};
var Ob=e.__sapp_html5_get_ask_leave_site=function(){return(Ob=e.__sapp_html5_get_ask_leave_site=e.asm.Fb).apply(null,arguments)},Pb=e.__sapp_emsc_begin_drop=function(){return(Pb=e.__sapp_emsc_begin_drop=e.asm.Gb).apply(null,arguments)};e.__sapp_emsc_drop=function(){return(e.__sapp_emsc_drop=e.asm.Hb).apply(null,arguments)};var Qb=e.__sapp_emsc_end_drop=function(){return(Qb=e.__sapp_emsc_end_drop=e.asm.Ib).apply(null,arguments)};
e.__sapp_emsc_invoke_fetch_cb=function(){return(e.__sapp_emsc_invoke_fetch_cb=e.asm.Jb).apply(null,arguments)};e._main=function(){return(e._main=e.asm.Kb).apply(null,arguments)};var Sb=e.__saudio_emsc_pull=function(){return(Sb=e.__saudio_emsc_pull=e.asm.Lb).apply(null,arguments)};e.__sargs_add_kvp=function(){return(e.__sargs_add_kvp=e.asm.Mb).apply(null,arguments)};e.__sfetch_emsc_head_response=function(){return(e.__sfetch_emsc_head_response=e.asm.Nb).apply(null,arguments)};
e.__sfetch_emsc_get_response=function(){return(e.__sfetch_emsc_get_response=e.asm.Ob).apply(null,arguments)};e.__sfetch_emsc_failed_http_status=function(){return(e.__sfetch_emsc_failed_http_status=e.asm.Pb).apply(null,arguments)};e.__sfetch_emsc_failed_buffer_too_small=function(){return(e.__sfetch_emsc_failed_buffer_too_small=e.asm.Qb).apply(null,arguments)};
var Q=e._malloc=function(){return(Q=e._malloc=e.asm.Rb).apply(null,arguments)},pa=e.stackSave=function(){return(pa=e.stackSave=e.asm.Sb).apply(null,arguments)},qa=e.stackRestore=function(){return(qa=e.stackRestore=e.asm.Tb).apply(null,arguments)},B=e.stackAlloc=function(){return(B=e.stackAlloc=e.asm.Ub).apply(null,arguments)},Ub;function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}J=function Vb(){Ub||Wb();Ub||(J=Vb)};
function Wb(a){function b(){if(!Ub&&(Ub=!0,e.calledRun=!0,!ma)){L(Ca);L(Da);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Xb){var c=a,d=e._main;c=c||[];var f=c.length+1,h=B(4*(f+1));F[h>>2]=ua(da);for(var g=1;g<f;g++)F[(h>>2)+g]=ua(c[g-1]);F[(h>>2)+f]=0;try{var m=d(f,h);if(!(noExitRuntime||0<ja)){if(e.onExit)e.onExit(m);ma=!0}k(m,new x(m))}catch(n){n instanceof x||"unwind"==n||k(1,n)}finally{}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),
Fa.unshift(c);L(Fa)}}a=a||ca;if(!(0<I)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ga();L(Ba);0<I||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=Wb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Xb=!0;e.noInitialRun&&(Xb=!1);Wb();
