var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",h=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,ha,ia;
if(ea){var fs=require("fs"),ja=require("path");q=l?ja.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=ka(a)?new URL(a):ja.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ia=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};ha=(a,b,c,d=!0)=>{a=ka(a)?new URL(a):ja.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,k)=>{e?c(e):b(d?k.buffer:k)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof la||a.context instanceof la))throw a;});h=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);
b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};g.print||console.log.bind(console);var r=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(h=g.quit);var t;g.wasmBinary&&(t=g.wasmBinary);
"object"!=typeof WebAssembly&&ma("no native wasm support detected");var na,oa=!1,pa,w,qa,ra,x,sa,y,z;function ta(){var a=na.buffer;g.HEAP8=pa=new Int8Array(a);g.HEAP16=qa=new Int16Array(a);g.HEAPU8=w=new Uint8Array(a);g.HEAPU16=ra=new Uint16Array(a);g.HEAP32=x=new Int32Array(a);g.HEAPU32=sa=new Uint32Array(a);g.HEAPF32=y=new Float32Array(a);g.HEAPF64=z=new Float64Array(a)}var ua=[],va=[],wa=[],xa=[],ya=[];function za(){var a=g.preRun.shift();ua.unshift(a)}var A=0,Aa=null,B=null;
function ma(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";r(a);oa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ba=a=>a.startsWith("data:application/octet-stream;base64,"),ka=a=>a.startsWith("file://"),C;C="pengo.wasm";if(!Ba(C)){var Ca=C;C=g.locateFile?g.locateFile(Ca,q):q+Ca}function Da(a){if(a==C&&t)return new Uint8Array(t);if(ia)return ia(a);throw"both async and sync fetching of the wasm failed";}
function Ea(a){if(!t&&(da||l)){if("function"==typeof fetch&&!ka(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Da(a));if(ha)return new Promise((b,c)=>{ha(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Da(a))}function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{r(`failed to asynchronously prepare wasm: ${d}`);ma(d)})}
function Ga(a,b){var c=C;t||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||ka(c)||ea||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){r(`wasm streaming compile failed: ${e}`);r("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}function la(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ha=a=>{for(;0<a.length;)a.shift()(g)},Ia=g.noExitRuntime||!0,La=a=>{var b=Ja();a();Ka(b)},Ma=0;function Na(){for(var a=D.length-1;0<=a;--a)Oa(a);D=[];Pa=[]}var Pa=[];function Qa(){if(navigator.userActivation?navigator.userActivation.isActive:Ma&&Ra.uc)for(var a=0;a<Pa.length;++a){var b=Pa[a];Pa.splice(a,1);--a;b.ed.apply(null,b.Wc)}}var D=[];function Oa(a){var b=D[a];b.target.removeEventListener(b.lc,b.Rc,b.mc);D.splice(a,1)}
function E(a){function b(d){++Ma;Ra=a;Qa();a.oc(d);Qa();--Ma}if(!a.target)return-4;if(a.nc)a.Rc=b,a.target.addEventListener(a.lc,b,a.mc),D.push(a),Sa||(xa.push(Na),Sa=!0);else for(var c=0;c<D.length;++c)D[c].target==a.target&&D[c].lc==a.lc&&Oa(c--);return 0}function Ta(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Sa,Ra,Ua,Va,Wa,Xa,Ya,Za,$a,ab="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b)=>{var c=w,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&ab)return ab.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var k=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|k<<6|f:(e&7)<<18|k<<12|f<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],G=a=>{a=2<a?a?F(a):"":a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=[],eb,H=a=>{var b=db[a];b||(a>=db.length&&(db.length=a+1),db[a]=b=eb.get(a));return b},I=(a,b,c)=>{var d=w;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);if(55296<=f&&57343>=f){var m=a.charCodeAt(++k);f=65536+((f&
1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},fb=(a,b,c,d,e,k)=>{Ua||(Ua=J(256));a={target:G(a),lc:k,nc:d,oc:(f=event)=>{var m=f.target.id?f.target.id:"",n=Ua;I(Ta(f.target),n+0,128);I(m,n+128,128);H(d)(e,n,b)&&f.preventDefault()},mc:c};return E(a)},gb=(a,b,c,d,e,k)=>{Va||(Va=J(176));
a={target:G(a),uc:!0,lc:k,nc:d,oc:f=>{var m=Va;z[m>>3]=f.timeStamp;var n=m>>2;x[n+2]=f.location;x[n+3]=f.ctrlKey;x[n+4]=f.shiftKey;x[n+5]=f.altKey;x[n+6]=f.metaKey;x[n+7]=f.repeat;x[n+8]=f.charCode;x[n+9]=f.keyCode;x[n+10]=f.which;I(f.key||"",m+44,32);I(f.code||"",m+76,32);I(f.char||"",m+108,32);I(f.locale||"",m+140,32);H(d)(e,m,b)&&f.preventDefault()},mc:c};return E(a)},hb=(a,b,c)=>{z[a>>3]=b.timeStamp;a>>=2;x[a+2]=b.screenX;x[a+3]=b.screenY;x[a+4]=b.clientX;x[a+5]=b.clientY;x[a+6]=b.ctrlKey;x[a+
7]=b.shiftKey;x[a+8]=b.altKey;x[a+9]=b.metaKey;qa[2*a+20]=b.button;qa[2*a+21]=b.buttons;x[a+11]=b.movementX;x[a+12]=b.movementY;c=cb(c);x[a+13]=b.clientX-c.left;x[a+14]=b.clientY-c.top},K=(a,b,c,d,e,k)=>{Wa||(Wa=J(72));a=G(a);return E({target:a,uc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,lc:k,nc:d,oc:(f=event)=>{hb(Wa,f,a);H(d)(e,Wa,b)&&f.preventDefault()},mc:c})},ib=(a,b,c,d,e)=>{Xa||(Xa=J(260));return E({target:a,lc:e,nc:d,oc:(k=event)=>{var f=Xa,m=document.pointerLockElement||document.rc||
document.Gc||document.Ec;x[f>>2]=!!m;var n=m&&m.id?m.id:"";I(Ta(m),f+4,128);I(n,f+132,128);H(d)(20,f,b)&&k.preventDefault()},mc:c})},jb=(a,b,c,d,e)=>E({target:a,lc:e,nc:d,oc:(k=event)=>{H(d)(38,0,b)&&k.preventDefault()},mc:c}),kb=(a,b,c,d)=>{Ya||(Ya=J(36));a=G(a);return E({target:a,lc:"resize",nc:d,oc:(e=event)=>{if(e.target==a){var k=document.body;if(k){var f=Ya;x[f>>2]=e.detail;x[f+4>>2]=k.clientWidth;x[f+8>>2]=k.clientHeight;x[f+12>>2]=innerWidth;x[f+16>>2]=innerHeight;x[f+20>>2]=outerWidth;x[f+
24>>2]=outerHeight;x[f+28>>2]=pageXOffset;x[f+32>>2]=pageYOffset;H(d)(10,f,b)&&e.preventDefault()}}},mc:c})},lb=(a,b,c,d,e,k)=>{Za||(Za=J(1696));a=G(a);return E({target:a,uc:"touchstart"==k||"touchend"==k,lc:k,nc:d,oc:f=>{for(var m,n={},p=f.touches,u=0;u<p.length;++u)m=p[u],m.Dc=m.Hc=0,n[m.identifier]=m;for(u=0;u<f.changedTouches.length;++u)m=f.changedTouches[u],m.Dc=1,n[m.identifier]=m;for(u=0;u<f.targetTouches.length;++u)n[f.targetTouches[u].identifier].Hc=1;p=Za;z[p>>3]=f.timeStamp;var v=p>>2;
x[v+3]=f.ctrlKey;x[v+4]=f.shiftKey;x[v+5]=f.altKey;x[v+6]=f.metaKey;v+=7;var ob=cb(a),pb=0;for(u in n)if(m=n[u],x[v]=m.identifier,x[v+1]=m.screenX,x[v+2]=m.screenY,x[v+3]=m.clientX,x[v+4]=m.clientY,x[v+5]=m.pageX,x[v+6]=m.pageY,x[v+7]=m.Dc,x[v+8]=m.Hc,x[v+9]=m.clientX-ob.left,x[v+10]=m.clientY-ob.top,v+=13,31<++pb)break;x[p+8>>2]=pb;H(d)(e,p,b)&&f.preventDefault()},mc:c})},mb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=(c,d,e,k,f)=>b.drawElementsInstancedANGLE(c,d,e,k,f))},nb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},qb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},rb=a=>{a.Yc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
sb=a=>{a.Zc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},tb=1,ub=[],L=[],vb=[],M=[],N=[],O=[],wb=[],xb=[],P=[],yb={},zb=4;function Q(a){Ab||(Ab=a)}
for(var Bb=a=>{for(var b=tb++,c=a.length;c<b;c++)a[c]=null;return b},Db=(a,b)=>{a.rc||(a.rc=a.getContext,a.getContext=function(d,e){e=a.rc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Fc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Cb(c,b):0},Cb=(a,b)=>{var c=Bb(xb),d={handle:c,attributes:b,version:b.Fc,yc:a};a.canvas&&(a.canvas.Vc=d);xb[c]=d;("undefined"==typeof b.Cc||b.Cc)&&Eb(d);return c},Eb=a=>{a||(a=R);if(!a.Tc){a.Tc=!0;var b=a.yc;mb(b);nb(b);qb(b);
rb(b);sb(b);2<=a.version&&(b.Bc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Bc)b.Bc=b.getExtension("EXT_disjoint_timer_query");b.Uc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},Ab,R,Fb=(a,b,c,d,e,k)=>{a={target:G(a),lc:k,nc:d,oc:(f=event)=>{H(d)(e,0,b)&&f.preventDefault()},mc:c};E(a)},Gb=(a,b,c,d)=>{$a||($a=J(104));return E({target:a,uc:!0,lc:"wheel",nc:d,oc:(e=event)=>
{var k=$a;hb(k,e,a);z[k+72>>3]=e.deltaX;z[k+80>>3]=e.deltaY;z[k+88>>3]=e.deltaZ;x[k+96>>2]=e.deltaMode;H(d)(9,k,b)&&e.preventDefault()},mc:c})},Hb=["default","low-power","high-performance"],Ib=[],T=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=S[c](),f=k&&Bb(d);k?(k.name=f,d[f]=k):Q(1282);x[b+4*e>>2]=f}},Jb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>R.version){Q(1282);
return}c=2*(S.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>R.version){Q(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Q(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:Q(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)x[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Q(1280);r("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:Q(1280);r("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}x[b>>2]=c}else Q(1281)},Kb=a=>{for(var b=
0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Lb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),U=a=>{a-=5120;return 0==a?pa:1==a?w:2==a?qa:4==a?x:6==a?y:5==a||28922==a||28520==a||30779==a||30782==a?sa:ra},Mb=(a,b,c,d,e)=>{a=U(a);var k=31-Math.clz32(a.BYTES_PER_ELEMENT),f=zb;return a.subarray(e>>k,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<k)+f-1&-f)>>k)},V=a=>{var b=S.Qc;if(b){var c=b.tc[a];"number"==
typeof c&&(b.tc[a]=c=S.getUniformLocation(b,b.Oc[a]+(0<c?"["+c+"]":"")));return c}Q(1282)},W=[],X=[],Nb=a=>{if(!Ia){if(g.onExit)g.onExit(a);oa=!0}h(a,new la(a))},Pb=a=>{var b=Kb(a)+1,c=Ob(b);I(a,c,b);return c},S,Y=0;32>Y;++Y)Ib.push(Array(Y));var Qb=new Float32Array(288);for(Y=0;288>Y;++Y)W[Y]=Qb.subarray(0,Y+1);var Rb=new Int32Array(288);for(Y=0;288>Y;++Y)X[Y]=Rb.subarray(0,Y+1);
var cc={i:()=>{ma("")},ia:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ja:(a,b,c)=>{a=G(a);if(!a)return-4;a=cb(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},z:()=>performance.now(),hb:(a,b,c)=>w.copyWithin(a,b,b+c),bb:(a,b)=>{function c(d){H(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},gb:a=>{var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+
(65536-d%65536)%65536)-na.buffer.byteLength+65535)/65536;try{na.grow(e);ta();var k=1;break a}catch(f){}k=void 0}if(k)return!0}return!1},S:(a,b,c,d)=>fb(a,b,c,d,12,"blur"),ha:(a,b,c)=>{a=G(a);if(!a)return-4;a.width=b;a.height=c;return 0},T:(a,b,c,d)=>fb(a,b,c,d,13,"focus"),aa:(a,b,c,d)=>gb(a,b,c,d,2,"keydown"),_:(a,b,c,d)=>gb(a,b,c,d,1,"keypress"),$:(a,b,c,d)=>gb(a,b,c,d,3,"keyup"),ga:(a,b,c,d)=>K(a,b,c,d,5,"mousedown"),da:(a,b,c,d)=>K(a,b,c,d,33,"mouseenter"),ca:(a,b,c,d)=>K(a,b,c,d,34,"mouseleave"),
ea:(a,b,c,d)=>K(a,b,c,d,8,"mousemove"),fa:(a,b,c,d)=>K(a,b,c,d,6,"mouseup"),V:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.rc||document.body.Gc||document.body.Ec))return-1;a=G(a);if(!a)return-4;ib(a,b,c,d,"mozpointerlockchange");ib(a,b,c,d,"webkitpointerlockchange");ib(a,b,c,d,"mspointerlockchange");return ib(a,b,c,d,"pointerlockchange")},U:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.rc||document.body.Gc||document.body.Ec))return-1;
a=G(a);if(!a)return-4;jb(a,b,c,d,"mozpointerlockerror");jb(a,b,c,d,"webkitpointerlockerror");jb(a,b,c,d,"mspointerlockerror");return jb(a,b,c,d,"pointerlockerror")},cb:(a,b,c,d)=>kb(a,b,c,d),W:(a,b,c,d)=>lb(a,b,c,d,25,"touchcancel"),X:(a,b,c,d)=>lb(a,b,c,d,23,"touchend"),Y:(a,b,c,d)=>lb(a,b,c,d,24,"touchmove"),Z:(a,b,c,d)=>lb(a,b,c,d,22,"touchstart"),R:(a,b,c,d)=>{Fb(a,b,c,d,31,"webglcontextlost");return 0},Q:(a,b,c,d)=>{Fb(a,b,c,d,32,"webglcontextrestored");return 0},ba:(a,b,c,d)=>(a=G(a))?"undefined"!=
typeof a.onwheel?Gb(a,b,c,d):-1:-4,$a:(a,b)=>{b>>=2;b={alpha:!!x[b],depth:!!x[b+1],stencil:!!x[b+2],antialias:!!x[b+3],premultipliedAlpha:!!x[b+4],preserveDrawingBuffer:!!x[b+5],powerPreference:Hb[x[b+6]],failIfMajorPerformanceCaveat:!!x[b+7],Fc:x[b+8],$c:x[b+9],Cc:x[b+10],Sc:x[b+11],ad:x[b+12],bd:x[b+13]};a=G(a);return!a||b.Sc?0:Db(a,b)},Ya:(a,b)=>{a=xb[a];b=b?F(b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&mb(S);"OES_vertex_array_object"==b&&nb(S);"WEBGL_draw_buffers"==
b&&qb(S);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&rb(S);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&sb(S);"WEBGL_multi_draw"==b&&(S.Uc=S.getExtension("WEBGL_multi_draw"));return!!a.yc.getExtension(b)},ab:a=>{a>>=2;for(var b=0;14>b;++b)x[a+b]=0;x[a]=x[a+1]=x[a+3]=x[a+4]=x[a+8]=x[a+10]=1},Za:a=>{R=xb[a];g.Xc=S=R&&R.yc;return!a||S?0:-5},j:function(a){S.activeTexture(a)},D:(a,b)=>{S.attachShader(L[a],O[b])},a:(a,b)=>{35051==a?S.Ac=b:35052==a&&(S.qc=b);S.bindBuffer(a,ub[b])},
h:(a,b)=>{S.bindFramebuffer(a,vb[b])},Ia:(a,b)=>{S.bindRenderbuffer(a,M[b])},k:(a,b)=>{S.bindSampler(a,P[b])},c:(a,b)=>{S.bindTexture(a,N[b])},M:a=>{S.bindVertexArray(wb[a])},I:function(a,b,c,d){S.blendColor(a,b,c,d)},J:function(a,b){S.blendEquationSeparate(a,b)},K:function(a,b,c,d){S.blendFuncSeparate(a,b,c,d)},lb:function(a,b,c,d,e,k,f,m,n,p){S.blitFramebuffer(a,b,c,d,e,k,f,m,n,p)},Ka:(a,b,c,d)=>{2<=R.version?c&&b?S.bufferData(a,w,d,c,b):S.bufferData(a,b,d):S.bufferData(a,c?w.subarray(c,c+b):b,
d)},o:(a,b,c,d)=>{2<=R.version?c&&S.bufferSubData(a,b,w,d,c):S.bufferSubData(a,b,w.subarray(d,d+c))},sa:function(a){return S.checkFramebufferStatus(a)},Fb:function(a,b,c,d){S.clearBufferfi(a,b,c,d)},pa:(a,b,c)=>{S.clearBufferfv(a,b,y,c>>2)},Eb:(a,b,c)=>{S.clearBufferiv(a,b,x,c>>2)},m:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},Kb:a=>{S.compileShader(O[a])},Da:(a,b,c,d,e,k,f,m)=>{2<=R.version?S.qc||!f?S.compressedTexImage2D(a,b,c,d,e,k,f,m):S.compressedTexImage2D(a,b,c,d,e,k,w,m,f):S.compressedTexImage2D(a,
b,c,d,e,k,m?w.subarray(m,m+f):null)},Ba:(a,b,c,d,e,k,f,m,n)=>{S.qc?S.compressedTexImage3D(a,b,c,d,e,k,f,m,n):S.compressedTexImage3D(a,b,c,d,e,k,f,w,n,m)},ya:()=>{var a=Bb(L),b=S.createProgram();b.name=a;b.xc=b.vc=b.wc=0;b.zc=1;L[a]=b;return a},Mb:a=>{var b=Bb(O);O[b]=S.createShader(a);return b},F:function(a){S.cullFace(a)},Ua:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=ub[d];e&&(S.deleteBuffer(e),e.name=0,ub[d]=null,d==S.Ac&&(S.Ac=0),d==S.qc&&(S.qc=0))}},e:(a,b)=>{for(var c=0;c<a;++c){var d=
x[b+4*c>>2],e=vb[d];e&&(S.deleteFramebuffer(e),e.name=0,vb[d]=null)}},x:a=>{if(a){var b=L[a];b?(S.deleteProgram(b),b.name=0,L[a]=null):Q(1281)}},O:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=M[d];e&&(S.deleteRenderbuffer(e),e.name=0,M[d]=null)}},N:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=P[d];e&&(S.deleteSampler(e),e.name=0,P[d]=null)}},B:a=>{if(a){var b=O[a];b?(S.deleteShader(b),O[a]=null):Q(1281)}},P:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=N[d];e&&(S.deleteTexture(e),e.name=
0,N[d]=null)}},Sa:(a,b)=>{for(var c=0;c<a;c++){var d=x[b+4*c>>2];S.deleteVertexArray(wb[d]);wb[d]=null}},w:function(a){S.depthFunc(a)},v:a=>{S.depthMask(!!a)},d:function(a){S.disable(a)},L:a=>{S.disableVertexAttribArray(a)},nb:(a,b,c)=>{S.drawArrays(a,b,c)},ob:(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},ra:(a,b)=>{for(var c=Ib[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];S.drawBuffers(c)},qb:(a,b,c,d)=>{S.drawElements(a,b,c,d)},rb:(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},g:function(a){S.enable(a)},Bb:a=>
{S.enableVertexAttribArray(a)},ta:(a,b,c,d)=>{S.framebufferRenderbuffer(a,b,c,M[d])},l:(a,b,c,d,e)=>{S.framebufferTexture2D(a,b,c,N[d],e)},A:(a,b,c,d,e)=>{S.framebufferTextureLayer(a,b,N[c],d,e)},G:function(a){S.frontFace(a)},La:(a,b)=>{T(a,b,"createBuffer",ub)},ua:(a,b)=>{T(a,b,"createFramebuffer",vb)},Ja:(a,b)=>{T(a,b,"createRenderbuffer",M)},za:(a,b)=>{T(a,b,"createSampler",P)},Ga:(a,b)=>{T(a,b,"createTexture",N)},Ra:function(a,b){T(a,b,"createVertexArray",wb)},Hb:(a,b)=>S.getAttribLocation(L[a],
b?F(b):""),b:(a,b)=>{Jb(a,b)},Nb:(a,b,c,d)=>{a=S.getProgramInfoLog(L[a]);null===a&&(a="(unknown error)");b=0<b&&d?I(a,d,b):0;c&&(x[c>>2]=b)},xa:(a,b,c)=>{if(c)if(a>=tb)Q(1281);else if(a=L[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b){if(!a.xc)for(b=0;b<S.getProgramParameter(a,35718);++b)a.xc=Math.max(a.xc,S.getActiveUniform(a,b).name.length+1);x[c>>2]=a.xc}else if(35722==b){if(!a.vc)for(b=0;b<S.getProgramParameter(a,35721);++b)a.vc=Math.max(a.vc,
S.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.vc}else if(35381==b){if(!a.wc)for(b=0;b<S.getProgramParameter(a,35382);++b)a.wc=Math.max(a.wc,S.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.wc}else x[c>>2]=S.getProgramParameter(a,b);else Q(1281)},Ib:(a,b,c,d)=>{a=S.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?I(a,d,b):0;c&&(x[c>>2]=b)},va:(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(O[a]),
x[c>>2]=a?a.length+1:0):x[c>>2]=S.getShaderParameter(O[a],b):Q(1281)},Va:(a,b)=>{if(2>R.version)return Q(1282),0;var c=yb[a];if(c)return 0>b||b>=c.length?(Q(1281),0):c[b];switch(a){case 7939:return c=S.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){var e=Kb(d)+1,k=J(e);k&&I(d,k,e);return k}),c=yb[a]=c,0>b||b>=c.length?(Q(1281),0):c[b];default:return Q(1280),0}},r:(a,b)=>{b=b?F(b):"";if(a=L[a]){var c=a,d=c.tc,e=c.Pc,k;if(!d)for(c.tc=d={},c.Oc={},k=0;k<
S.getProgramParameter(c,35718);++k){var f=S.getActiveUniform(c,k);var m=f.name;f=f.size;var n=Lb(m);n=0<n?m.slice(0,n):m;var p=c.zc;c.zc+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.Oc[p++]=n}c=a.tc;d=0;e=b;k=Lb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.Pc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else Q(1281);return-1},kb:(a,b,c)=>{for(var d=Ib[b],e=0;e<b;e++)d[e]=x[c+4*e>>2];S.invalidateFramebuffer(a,d)},Ob:a=>{a=L[a];S.linkProgram(a);a.tc=0;a.Pc={}},Qa:(a,
b)=>{3317==a&&(zb=b);S.pixelStorei(a,b)},H:function(a,b){S.polygonOffset(a,b)},mb:function(a){S.readBuffer(a)},Ha:function(a,b,c,d,e){S.renderbufferStorageMultisample(a,b,c,d,e)},E:(a,b,c)=>{S.samplerParameterf(P[a],b,c)},f:(a,b,c)=>{S.samplerParameteri(P[a],b,c)},qa:function(a,b,c,d){S.scissor(a,b,c,d)},Lb:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var f=d?x[d+4*k>>2]:-1,m=x[c+4*k>>2];f=m?F(m,0>f?void 0:f):"";e+=f}S.shaderSource(O[a],e)},Oa:function(a,b,c){S.stencilFunc(a,b,c)},oa:function(a,b,c,d){S.stencilFuncSeparate(a,
b,c,d)},u:function(a){S.stencilMask(a)},Na:function(a,b,c){S.stencilOp(a,b,c)},na:function(a,b,c,d){S.stencilOpSeparate(a,b,c,d)},Ca:(a,b,c,d,e,k,f,m,n)=>{if(2<=R.version)if(S.qc)S.texImage2D(a,b,c,d,e,k,f,m,n);else if(n){var p=U(m);S.texImage2D(a,b,c,d,e,k,f,m,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else S.texImage2D(a,b,c,d,e,k,f,m,null);else S.texImage2D(a,b,c,d,e,k,f,m,n?Mb(m,f,d,e,n):null)},Aa:(a,b,c,d,e,k,f,m,n,p)=>{if(S.qc)S.texImage3D(a,b,c,d,e,k,f,m,n,p);else if(p){var u=U(n);S.texImage3D(a,
b,c,d,e,k,f,m,n,u,p>>31-Math.clz32(u.BYTES_PER_ELEMENT))}else S.texImage3D(a,b,c,d,e,k,f,m,n,null)},Ea:function(a,b,c){S.texParameteri(a,b,c)},jb:(a,b,c,d,e,k,f,m,n)=>{if(2<=R.version)if(S.qc)S.texSubImage2D(a,b,c,d,e,k,f,m,n);else if(n){var p=U(m);S.texSubImage2D(a,b,c,d,e,k,f,m,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else S.texSubImage2D(a,b,c,d,e,k,f,m,null);else p=null,n&&(p=Mb(m,f,e,k,n)),S.texSubImage2D(a,b,c,d,e,k,f,m,p)},ib:(a,b,c,d,e,k,f,m,n,p,u)=>{if(S.qc)S.texSubImage3D(a,b,c,d,e,k,f,
m,n,p,u);else if(u){var v=U(p);S.texSubImage3D(a,b,c,d,e,k,f,m,n,p,v,u>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else S.texSubImage3D(a,b,c,d,e,k,f,m,n,p,null)},Ab:(a,b,c)=>{if(2<=R.version)b&&S.uniform1fv(V(a),y,c>>2,b);else{if(288>=b)for(var d=W[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);S.uniform1fv(V(a),d)}},wa:(a,b)=>{S.uniform1i(V(a),b)},wb:(a,b,c)=>{if(2<=R.version)b&&S.uniform1iv(V(a),x,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>
2,c+4*b>>2);S.uniform1iv(V(a),d)}},zb:(a,b,c)=>{if(2<=R.version)b&&S.uniform2fv(V(a),y,c>>2,2*b);else{if(144>=b)for(var d=W[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);S.uniform2fv(V(a),d)}},vb:(a,b,c)=>{if(2<=R.version)b&&S.uniform2iv(V(a),x,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);S.uniform2iv(V(a),d)}},yb:(a,b,c)=>{if(2<=R.version)b&&S.uniform3fv(V(a),y,
c>>2,3*b);else{if(96>=b)for(var d=W[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);S.uniform3fv(V(a),d)}},ub:(a,b,c)=>{if(2<=R.version)b&&S.uniform3iv(V(a),x,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);S.uniform3iv(V(a),d)}},xb:(a,b,c)=>{if(2<=R.version)b&&S.uniform4fv(V(a),y,c>>2,4*b);else{if(72>=b){var d=W[4*b-1],e=
y;c>>=2;for(var k=0;k<4*b;k+=4){var f=c+k;d[k]=e[f];d[k+1]=e[f+1];d[k+2]=e[f+2];d[k+3]=e[f+3]}}else d=y.subarray(c>>2,c+16*b>>2);S.uniform4fv(V(a),d)}},tb:(a,b,c)=>{if(2<=R.version)b&&S.uniform4iv(V(a),x,c>>2,4*b);else{if(72>=b)for(var d=X[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*b>>2);S.uniform4iv(V(a),d)}},sb:(a,b,c,d)=>{if(2<=R.version)b&&S.uniformMatrix4fv(V(a),!!c,y,d>>2,16*b);else{if(18>=b){var e=
W[16*b-1],k=y;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=k[m];e[f+1]=k[m+1];e[f+2]=k[m+2];e[f+3]=k[m+3];e[f+4]=k[m+4];e[f+5]=k[m+5];e[f+6]=k[m+6];e[f+7]=k[m+7];e[f+8]=k[m+8];e[f+9]=k[m+9];e[f+10]=k[m+10];e[f+11]=k[m+11];e[f+12]=k[m+12];e[f+13]=k[m+13];e[f+14]=k[m+14];e[f+15]=k[m+15]}}else e=y.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(V(a),!!c,e)}},n:a=>{a=L[a];S.useProgram(a);S.Qc=a},Cb:(a,b)=>{S.vertexAttribDivisor(a,b)},Db:(a,b,c,d,e,k)=>{S.vertexAttribPointer(a,b,c,!!d,e,k)},q:function(a,
b,c,d){S.viewport(a,b,c,d)},_a:function(){g.Ic=a=>{0!=Sb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Ic)},Wa:function(){g.Nc=a=>{const b=a.clipboardData.getData("text");La(()=>{const c=Pb(b);Tb(c)})};window.addEventListener("paste",g.Nc)},Pa:function(a){g.cd=[];a=a?F(a):"";a=document.getElementById(a);g.Jc=b=>{b.stopPropagation();b.preventDefault()};g.Kc=b=>{b.stopPropagation();b.preventDefault()};g.Lc=b=>{b.stopPropagation();b.preventDefault()};g.Mc=b=>{b.stopPropagation();
b.preventDefault();const c=b.dataTransfer.files;g.dd=c;Ub(c.length);for(let e=0;e<c.length;e++)La(()=>{const k=Pb(c[e].name);Vb(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Wb(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.Jc,!1);a.addEventListener("dragleave",g.Kc,!1);a.addEventListener("dragover",g.Lc,!1);a.addEventListener("drop",g.Mc,!1)},Jb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},t:function(){const a=
document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Xb()});document.body.append(a)},s:function(){document.getElementById("_sokol_app_input_element").focus()},Fa:function(a){a=a?F(a):"";g.sc=document.getElementById(a);g.sc||console.log("sokol_app.h: invalid target:"+a);g.sc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Xa:function(){window.removeEventListener("beforeunload",
g.Ic)},Ta:function(){window.removeEventListener("paste",g.Nc)},Ma:function(a){a=a?F(a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.Jc);a.removeEventListener("dragleave",g.Kc);a.removeEventListener("dragover",g.Lc);a.removeEventListener("drop",g.Mc)},C:function(){g.sc&&g.sc.requestPointerLock&&g.sc.requestPointerLock()},Gb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(w.subarray(c,
c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},p:function(){document.getElementById("_sokol_app_input_element").blur()},eb:function(){return g.pc?g.pc.bufferSize:0},pb:function(a,b,c){g.kc=null;g.pc=null;"undefined"!==typeof AudioContext?g.kc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.kc=null,console.log("sokol_audio.h: no WebAudio support"));return g.kc?(console.log("sokol_audio.h: sample rate ",
g.kc.sampleRate),g.pc=g.kc.createScriptProcessor(c,0,b),g.pc.onaudioprocess=d=>{const e=d.outputBuffer.length,k=Yb(e);if(k){const f=d.outputBuffer.numberOfChannels;for(let m=0;m<f;m++){const n=d.outputBuffer.getChannelData(m);for(let p=0;p<e;p++)n[p]=y[(k>>2)+(f*p+m)]}}},g.pc.connect(g.kc.destination),a=()=>{g.kc&&"suspended"===g.kc.state&&g.kc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),
1):0},fb:function(){return g.kc?g.kc.sampleRate:0},ma:function(){const a=g.kc;null!==a&&(g.pc&&g.pc.disconnect(),a.close(),g.kc=null,g.pc=null)},db:function(){if(g.kc)return"suspended"===g.kc.state?1:0},y:function(a,b,c,d,e,k){b=b?F(b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const m=0<d;m&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!m){const n=new Uint8Array(f.response),
p=n.length;p<=k?(w.set(n,e),Zb(a,d,p)):$b(a)}else ac(a,f.status)};f.send()},la:function(a,b){b=b?F(b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");bc(a,d)}else ac(a,c.status)};c.send()},ka:function(a,b){b=b?F(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=
c.exports;na=Z.Pb;ta();eb=Z.gc;va.unshift(Z.Qb);A--;g.monitorRunDependencies&&g.monitorRunDependencies(A);0==A&&(null!==Aa&&(clearInterval(Aa),Aa=null),B&&(c=B,B=null,c()));return Z}var b={a:cc};A++;g.monitorRunDependencies&&g.monitorRunDependencies(A);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return r(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ga(b,function(c){a(c.instance)});return{}}();g._fs_emsc_alloc=a=>(g._fs_emsc_alloc=Z.Rb)(a);var J=a=>(J=Z.Sb)(a);
g._fs_emsc_load_snapshot_callback=(a,b,c)=>(g._fs_emsc_load_snapshot_callback=Z.Tb)(a,b,c);
var Xb=g.__sapp_emsc_notify_keyboard_hidden=()=>(Xb=g.__sapp_emsc_notify_keyboard_hidden=Z.Ub)(),Tb=g.__sapp_emsc_onpaste=a=>(Tb=g.__sapp_emsc_onpaste=Z.Vb)(a),Sb=g.__sapp_html5_get_ask_leave_site=()=>(Sb=g.__sapp_html5_get_ask_leave_site=Z.Wb)(),Ub=g.__sapp_emsc_begin_drop=a=>(Ub=g.__sapp_emsc_begin_drop=Z.Xb)(a),Vb=g.__sapp_emsc_drop=(a,b)=>(Vb=g.__sapp_emsc_drop=Z.Yb)(a,b),Wb=g.__sapp_emsc_end_drop=(a,b,c)=>(Wb=g.__sapp_emsc_end_drop=Z.Zb)(a,b,c);
g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,k,f,m)=>(g.__sapp_emsc_invoke_fetch_cb=Z._b)(a,b,c,d,e,k,f,m);var dc=g._main=(a,b)=>(dc=g._main=Z.$b)(a,b),Yb=g.__saudio_emsc_pull=a=>(Yb=g.__saudio_emsc_pull=Z.ac)(a);g.__sargs_add_kvp=(a,b)=>(g.__sargs_add_kvp=Z.bc)(a,b);
var bc=g.__sfetch_emsc_head_response=(a,b)=>(bc=g.__sfetch_emsc_head_response=Z.cc)(a,b),Zb=g.__sfetch_emsc_get_response=(a,b,c)=>(Zb=g.__sfetch_emsc_get_response=Z.dc)(a,b,c),ac=g.__sfetch_emsc_failed_http_status=(a,b)=>(ac=g.__sfetch_emsc_failed_http_status=Z.ec)(a,b),$b=g.__sfetch_emsc_failed_buffer_too_small=a=>($b=g.__sfetch_emsc_failed_buffer_too_small=Z.fc)(a),Ja=()=>(Ja=Z.hc)(),Ka=a=>(Ka=Z.ic)(a),Ob=a=>(Ob=Z.jc)(a);g.___start_em_js=66240;g.___stop_em_js=79290;var ec;
B=function fc(){ec||gc();ec||(B=fc)};function hc(a=[]){var b=dc;a.unshift(ca);var c=a.length,d=Ob(4*(c+1)),e=d;a.forEach(f=>{sa[e>>2]=Pb(f);e+=4});sa[e>>2]=0;try{var k=b(c,d);Nb(k)}catch(f){f instanceof la||"unwind"==f||h(1,f)}}
function gc(){var a=ba;function b(){if(!ec&&(ec=!0,g.calledRun=!0,!oa)){Ha(va);Ha(wa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();ic&&hc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();ya.unshift(c)}Ha(ya)}}if(!(0<A)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)za();Ha(ua);0<A||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var ic=!0;g.noInitialRun&&(ic=!1);gc();
