
var d;d||(d=typeof Module !== 'undefined' ? Module : {});var h={},l;for(l in d)d.hasOwnProperty(l)&&(h[l]=d[l]);var r=[],aa="./this.program";function t(a,b){throw b;}var ba=!1,u=!1,ca=!1,da=!1;ba="object"===typeof window;u="function"===typeof importScripts;ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;da=!ba&&!ca&&!u;var v="",ea,w,fa,ha;
if(ca)v=u?require("path").dirname(v)+"/":__dirname+"/",ea=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,b?null:"utf8")},w=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),r=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=d),process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;}),process.on("unhandledRejection",
x),t=function(a){process.exit(a)},d.inspect=function(){return"[Emscripten Module object]"};else if(da)"undefined"!=typeof read&&(ea=function(a){return read(a)}),w=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?r=scriptArgs:"undefined"!=typeof arguments&&(r=arguments),"function"===typeof quit&&(t=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ba||u)u?v=self.location.href:"undefined"!==typeof document&&document.currentScript&&(v=document.currentScript.src),v=0!==v.indexOf("blob:")?v.substr(0,v.lastIndexOf("/")+1):"",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(w=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
d.print||console.log.bind(console);var z=d.printErr||console.warn.bind(console);for(l in h)h.hasOwnProperty(l)&&(d[l]=h[l]);h=null;d.arguments&&(r=d.arguments);d.thisProgram&&(aa=d.thisProgram);d.quit&&(t=d.quit);var A;d.wasmBinary&&(A=d.wasmBinary);var noExitRuntime;d.noExitRuntime&&(noExitRuntime=d.noExitRuntime);"object"!==typeof WebAssembly&&x("no native wasm support detected");var B,ja=!1;function assert(a,b){a||x("Assertion failed: "+b)}
function ka(a){var b=d["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function C(a,b,c,e){var f={string:function(p){var q=0;if(null!==p&&void 0!==p&&0!==p){var U=(p.length<<2)+1;q=D(U);E(p,F,q,U)}return q},array:function(p){var q=D(p.length);la.set(p,q);return q}},k=ka(a),g=[];a=0;if(e)for(var m=0;m<e.length;m++){var n=f[c[m]];n?(0===a&&(a=ma()),g[m]=n(e[m])):g[m]=e[m]}c=k.apply(null,g);c=function(p){return"string"===b?G(p):"boolean"===b?!!p:p}(c);0!==a&&na(a);return c}var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function G(a,b){if(a){var c=F,e=a+b;for(b=a;c[b]&&!(b>=e);)++b;if(16<b-a&&c.subarray&&oa)a=oa.decode(c.subarray(a,b));else{for(e="";a<b;){var f=c[a++];if(f&128){var k=c[a++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|k);else{var g=c[a++]&63;f=224==(f&240)?(f&15)<<12|k<<6|g:(f&7)<<18|k<<12|g<<6|c[a++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}a=e}}else a="";return a}
function E(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var k=0;k<a.length;++k){var g=a.charCodeAt(k);if(55296<=g&&57343>=g){var m=a.charCodeAt(++k);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=e)break;b[c++]=g}else{if(2047>=g){if(c+1>=e)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=e)break;b[c++]=224|g>>12}else{if(c+3>=e)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}
function pa(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}function qa(a){var b=pa(a)+1,c=D(b);E(a,la,c,b);return c}var H,la,F,ra,sa,I,ta,ua,J;
function va(a){H=a;d.HEAP8=la=new Int8Array(a);d.HEAP16=ra=new Int16Array(a);d.HEAP32=I=new Int32Array(a);d.HEAPU8=F=new Uint8Array(a);d.HEAPU16=sa=new Uint16Array(a);d.HEAPU32=ta=new Uint32Array(a);d.HEAPF32=ua=new Float32Array(a);d.HEAPF64=J=new Float64Array(a)}var wa=d.INITIAL_MEMORY||33554432;d.wasmMemory?B=d.wasmMemory:B=new WebAssembly.Memory({initial:wa/65536,maximum:32768});B&&(H=B.buffer);wa=H.byteLength;va(H);var K,xa=[],ya=[],za=[],Aa=[],Ba=[];
function Ca(){var a=d.preRun.shift();xa.unshift(a)}var L=0,Da=null,M=null;d.preloadedImages={};d.preloadedAudios={};function x(a){if(d.onAbort)d.onAbort(a);z(a);ja=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ea(a){var b=N;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Fa(){return Ea("data:application/octet-stream;base64,")}var N="vic20.wasm";if(!Fa()){var Ga=N;N=d.locateFile?d.locateFile(Ga,v):v+Ga}
function Ha(){try{if(A)return new Uint8Array(A);if(w)return w(N);throw"both async and sync fetching of the wasm failed";}catch(a){x(a)}}function Ia(){return A||!ba&&!u||"function"!==typeof fetch||Ea("file://")?Promise.resolve().then(Ha):fetch(N,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+N+"'";return a.arrayBuffer()}).catch(function(){return Ha()})}
function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.xc;"number"===typeof c?void 0===b.ic?K.get(c)():K.get(c)(b.ic):c(void 0===b.ic?null:b.ic)}}}var Ka=0;function La(){for(var a=O.length-1;0<=a;--a)Ma(a);O=[];Na=[]}var Na=[];function Oa(){if(Ka&&Pa.fc)for(var a=0;a<Na.length;++a){var b=Na[a];Na.splice(a,1);--a;b.Nc.apply(null,b.Dc)}}var O=[];function Ma(a){var b=O[a];b.target.removeEventListener(b.Yb,b.vc,b.Zb);O.splice(a,1)}
function P(a){function b(e){++Ka;Pa=a;Oa();a.bc(e);Oa();--Ka}if(a.ac)a.vc=b,a.target.addEventListener(a.Yb,b,a.Zb),O.push(a),Qa||(Aa.push(La),Qa=!0);else for(var c=0;c<O.length;++c)O[c].target==a.target&&O[c].Yb==a.Yb&&Ma(c--)}var Qa,Pa,Ra,Sa,Ta,Ua,Va,Wa,Xa=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Q(a){a=2<a?G(a):a;return Xa[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Ya(a){return 0>Xa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function Za(a,b,c,e,f,k){Ra||(Ra=R(164));a={target:Q(a),fc:!0,Yb:k,ac:e,bc:function(g){var m=Ra,n=m>>2;I[n]=g.location;I[n+1]=g.ctrlKey;I[n+2]=g.shiftKey;I[n+3]=g.altKey;I[n+4]=g.metaKey;I[n+5]=g.repeat;I[n+6]=g.charCode;I[n+7]=g.keyCode;I[n+8]=g.which;E(g.key||"",F,m+36,32);E(g.code||"",F,m+68,32);E(g.char||"",F,m+100,32);E(g.locale||"",F,m+132,32);K.get(e)(f,m,b)&&g.preventDefault()},Zb:c};P(a)}
function $a(a,b,c){a>>=2;I[a]=b.screenX;I[a+1]=b.screenY;I[a+2]=b.clientX;I[a+3]=b.clientY;I[a+4]=b.ctrlKey;I[a+5]=b.shiftKey;I[a+6]=b.altKey;I[a+7]=b.metaKey;ra[2*a+16]=b.button;ra[2*a+17]=b.buttons;I[a+9]=b.movementX;I[a+10]=b.movementY;c=Ya(c);I[a+11]=b.clientX-c.left;I[a+12]=b.clientY-c.top}function S(a,b,c,e,f,k){Sa||(Sa=R(64));a=Q(a);P({target:a,fc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Yb:k,ac:e,bc:function(g){g=g||event;$a(Sa,g,a);K.get(e)(f,Sa,b)&&g.preventDefault()},Zb:c})}
function ab(a,b,c,e,f){Ta||(Ta=R(260));P({target:a,Yb:f,ac:e,bc:function(k){k=k||event;var g=Ta,m=document.pointerLockElement||document.kc||document.mc||document.lc;I[g>>2]=!!m;var n=m&&m.id?m.id:"";E(m?m==window?"#window":m==screen?"#screen":m&&m.nodeName?m.nodeName:"":"",F,g+4,128);E(n,F,g+132,128);K.get(e)(20,g,b)&&k.preventDefault()},Zb:c})}function bb(a,b,c,e,f){P({target:a,Yb:f,ac:e,bc:function(k){k=k||event;K.get(e)(38,0,b)&&k.preventDefault()},Zb:c})}
function cb(a,b,c,e){Ua||(Ua=R(36));a=Q(a);P({target:a,Yb:"resize",ac:e,bc:function(f){f=f||event;if(f.target==a){var k=document.body;if(k){var g=Ua;I[g>>2]=f.detail;I[g+4>>2]=k.clientWidth;I[g+8>>2]=k.clientHeight;I[g+12>>2]=innerWidth;I[g+16>>2]=innerHeight;I[g+20>>2]=outerWidth;I[g+24>>2]=outerHeight;I[g+28>>2]=pageXOffset;I[g+32>>2]=pageYOffset;K.get(e)(10,g,b)&&f.preventDefault()}}},Zb:c})}
function db(a,b,c,e,f,k){Va||(Va=R(1684));a=Q(a);P({target:a,fc:"touchstart"==k||"touchend"==k,Yb:k,ac:e,bc:function(g){for(var m={},n=g.touches,p=0;p<n.length;++p){var q=n[p];m[q.identifier]=q}n=g.changedTouches;for(p=0;p<n.length;++p)q=n[p],q.zc=1,m[q.identifier]=q;n=g.targetTouches;for(p=0;p<n.length;++p)m[n[p].identifier].Bc=1;n=Va;q=n>>2;I[q+1]=g.ctrlKey;I[q+2]=g.shiftKey;I[q+3]=g.altKey;I[q+4]=g.metaKey;q+=5;var U=Ya(a),jb=0;for(p in m){var y=m[p];I[q]=y.identifier;I[q+1]=y.screenX;I[q+2]=y.screenY;
I[q+3]=y.clientX;I[q+4]=y.clientY;I[q+5]=y.pageX;I[q+6]=y.pageY;I[q+7]=y.zc;I[q+8]=y.Bc;I[q+9]=y.clientX-U.left;I[q+10]=y.clientY-U.top;q+=13;if(31<++jb)break}I[n>>2]=jb;K.get(e)(f,n,b)&&g.preventDefault()},Zb:c})}function eb(a,b,c,e,f,k){a={target:Q(a),Yb:k,ac:e,bc:function(g){g=g||event;K.get(e)(f,0,b)&&g.preventDefault()},Zb:c};P(a)}
function fb(a,b,c,e){Wa||(Wa=R(96));P({target:a,fc:!0,Yb:"wheel",ac:e,bc:function(f){f=f||event;var k=Wa;$a(k,f,a);J[k+64>>3]=f.deltaX;J[k+72>>3]=f.deltaY;J[k+80>>3]=f.deltaZ;I[k+88>>2]=f.deltaMode;K.get(e)(9,k,b)&&f.preventDefault()},Zb:c})}
function gb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,e){b.vertexAttribDivisorANGLE(c,e)},a.drawArraysInstanced=function(c,e,f,k){b.drawArraysInstancedANGLE(c,e,f,k)},a.drawElementsInstanced=function(c,e,f,k,g){b.drawElementsInstancedANGLE(c,e,f,k,g)})}
function hb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function ib(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,e){b.drawBuffersWEBGL(c,e)})}function kb(a){a.Ic=a.getExtension("WEBGL_multi_draw")}
var lb=1,mb=[],T=[],nb=[],V=[],ob=[],pb=[],W=[],qb=[],rb={},sb={};function X(a){tb||(tb=a)}function Y(a){for(var b=lb++,c=a.length;c<b;c++)a[c]=null;return b}
function ub(a){a||(a=vb);if(!a.yc){a.yc=!0;var b=a.hc;gb(b);hb(b);ib(b);b.Fc=b.getExtension("EXT_disjoint_timer_query");kb(b);var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(e){-1!=c.indexOf(e)&&b.getExtension(e)})}}var tb,vb,wb=["default","low-power","high-performance"];function xb(a,b,c,e){for(var f=0;f<a;f++){var k=Z[c](),g=k&&Y(e);k?(k.name=g,e[g]=k):X(1282);I[b+4*f>>2]=g}}
function yb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var e=Z.getParameter(34467);c=e?e.length:0}if(void 0===c)switch(e=Z.getParameter(a),typeof e){case "number":c=e;break;case "boolean":c=e?1:0;break;case "string":X(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:X(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||
e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)I[b+4*a>>2]=e[a];return}try{c=e.name|0}catch(f){X(1280);z("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:X(1280);z("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+e+" of type "+typeof e+"!");return}I[b>>2]=c}else X(1281)}function zb(a){var b=pa(a)+1,c=R(b);E(a,F,c,b);return c}
function Ab(a,b,c,e,f){a-=5120;a=1==a?F:4==a?I:6==a?ua:5==a||28922==a?ta:sa;var k=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(f>>k,f+e*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<k)+4-1&-4)>>k)}var Z;ya.push({xc:function(){Bb()}});
var Hb={ib:function(){console.log("fs.h: registering Module['ccall']");d.ccall=C},sa:function(a){var b=G(a),c=new XMLHttpRequest;c.open("GET",b);c.responseType="arraybuffer";c.onload=function(){var e=new Uint8Array(c.response);C("emsc_load_data","int",["string","array","number"],[b,e,e.length])};c.send()},J:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},U:function(a,b,c){a=Q(a);if(!a)return-4;a=Ya(a);J[b>>3]=a.width;J[c>>3]=a.height;return 0},Za:function(a,b,c){F.copyWithin(a,
b,b+c)},xa:function(a,b){function c(e){K.get(a)(e,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},_a:function(a){a>>>=0;var b=F.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);e=Math.max(16777216,a,e);0<e%65536&&(e+=65536-e%65536);a:{try{B.grow(Math.min(2147483648,e)-H.byteLength+65535>>>16);va(B.buffer);var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},F:function(a,b,c){a=Q(a);if(!a)return-4;a.width=b;a.height=c;return 0},fa:function(a,
b,c,e){Za(a,b,c,e,2,"keydown");return 0},da:function(a,b,c,e){Za(a,b,c,e,1,"keypress");return 0},ea:function(a,b,c,e){Za(a,b,c,e,3,"keyup");return 0},la:function(a,b,c,e){S(a,b,c,e,5,"mousedown");return 0},ia:function(a,b,c,e){S(a,b,c,e,33,"mouseenter");return 0},ha:function(a,b,c,e){S(a,b,c,e,34,"mouseleave");return 0},ja:function(a,b,c,e){S(a,b,c,e,8,"mousemove");return 0},ka:function(a,b,c,e){S(a,b,c,e,6,"mouseup");return 0},_:function(a,b,c,e){if(!document||!document.body||!(document.body.requestPointerLock||
document.body.kc||document.body.mc||document.body.lc))return-1;a=Q(a);if(!a)return-4;ab(a,b,c,e,"pointerlockchange");ab(a,b,c,e,"mozpointerlockchange");ab(a,b,c,e,"webkitpointerlockchange");ab(a,b,c,e,"mspointerlockchange");return 0},Z:function(a,b,c,e){if(!document||!(document.body.requestPointerLock||document.body.kc||document.body.mc||document.body.lc))return-1;a=Q(a);if(!a)return-4;bb(a,b,c,e,"pointerlockerror");bb(a,b,c,e,"mozpointerlockerror");bb(a,b,c,e,"webkitpointerlockerror");bb(a,b,c,e,
"mspointerlockerror");return 0},Ja:function(a,b,c,e){cb(a,b,c,e);return 0},$:function(a,b,c,e){db(a,b,c,e,25,"touchcancel");return 0},aa:function(a,b,c,e){db(a,b,c,e,23,"touchend");return 0},ba:function(a,b,c,e){db(a,b,c,e,24,"touchmove");return 0},ca:function(a,b,c,e){db(a,b,c,e,22,"touchstart");return 0},Y:function(a,b,c,e){eb(a,b,c,e,31,"webglcontextlost");return 0},X:function(a,b,c,e){eb(a,b,c,e,32,"webglcontextrestored");return 0},ga:function(a,b,c,e){a=Q(a);return"undefined"!==typeof a.onwheel?
(fb(a,b,c,e),0):-1},na:function(a,b){b>>=2;b={alpha:!!I[b],depth:!!I[b+1],stencil:!!I[b+2],antialias:!!I[b+3],premultipliedAlpha:!!I[b+4],preserveDrawingBuffer:!!I[b+5],powerPreference:wb[I[b+6]],failIfMajorPerformanceCaveat:!!I[b+7],Ac:I[b+8],Hc:I[b+9],nc:I[b+10],wc:I[b+11],Jc:I[b+12],Kc:I[b+13]};a=Q(a);if(!a||b.wc)b=0;else if(a=a.getContext("webgl",b)){var c=Y(qb),e={Gc:c,attributes:b,version:b.Ac,hc:a};a.canvas&&(a.canvas.Cc=e);qb[c]=e;("undefined"===typeof b.nc||b.nc)&&ub(e);b=c}else b=0;return b},
Xa:function(a,b){a=qb[a];b=G(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&gb(Z);"OES_vertex_array_object"==b&&hb(Z);"WEBGL_draw_buffers"==b&&ib(Z);"WEBGL_multi_draw"==b&&kb(Z);return!!a.hc.getExtension(b)},hb:function(a){a>>=2;for(var b=0;14>b;++b)I[a+b]=0;I[a]=I[a+1]=I[a+3]=I[a+4]=I[a+8]=I[a+10]=1},Ya:function(a){vb=qb[a];d.Ec=Z=vb&&vb.hc;return!a||Z?0:-5},c:function(a){Z.activeTexture(a)},G:function(a,b){Z.attachShader(T[a],W[b])},f:function(a,b){Z.bindBuffer(a,mb[b])},h:function(a,
b){Z.bindFramebuffer(a,nb[b])},Ha:function(a,b){Z.bindRenderbuffer(a,V[b])},b:function(a,b){Z.bindTexture(a,ob[b])},Q:function(a,b,c,e){Z.blendColor(a,b,c,e)},R:function(a,b){Z.blendEquationSeparate(a,b)},S:function(a,b,c,e){Z.blendFuncSeparate(a,b,c,e)},L:function(a,b,c,e){Z.bufferData(a,c?F.subarray(c,c+b):b,e)},K:function(a,b,c,e){Z.bufferSubData(a,b,F.subarray(e,e+c))},n:function(a){return Z.checkFramebufferStatus(a)},fb:function(a){Z.clear(a)},ua:function(a,b,c,e){Z.clearColor(a,b,c,e)},ta:function(a){Z.clearDepth(a)},
gb:function(a){Z.clearStencil(a)},w:function(a,b,c,e){Z.colorMask(!!a,!!b,!!c,!!e)},za:function(a){Z.compileShader(W[a])},I:function(a,b,c,e,f,k,g,m){Z.compressedTexImage2D(a,b,c,e,f,k,m?F.subarray(m,m+g):null)},Ea:function(){var a=Y(T),b=Z.createProgram();b.name=a;T[a]=b;return a},Ba:function(a){var b=Y(W);W[b]=Z.createShader(a);return b},N:function(a){Z.cullFace(a)},Na:function(a,b){for(var c=0;c<a;c++){var e=I[b+4*c>>2],f=mb[e];f&&(Z.deleteBuffer(f),f.name=0,mb[e]=null)}},e:function(a,b){for(var c=
0;c<a;++c){var e=I[b+4*c>>2],f=nb[e];f&&(Z.deleteFramebuffer(f),f.name=0,nb[e]=null)}},V:function(a){if(a){var b=T[a];b?(Z.deleteProgram(b),b.name=0,T[a]=null,rb[a]=null):X(1281)}},W:function(a,b){for(var c=0;c<a;c++){var e=I[b+4*c>>2],f=V[e];f&&(Z.deleteRenderbuffer(f),f.name=0,V[e]=null)}},v:function(a){if(a){var b=W[a];b?(Z.deleteShader(b),W[a]=null):X(1281)}},Ma:function(a,b){for(var c=0;c<a;c++){var e=I[b+4*c>>2],f=ob[e];f&&(Z.deleteTexture(f),f.name=0,ob[e]=null)}},z:function(a){Z.depthFunc(a)},
y:function(a){Z.depthMask(!!a)},g:function(a){Z.disable(a)},T:function(a){Z.disableVertexAttribArray(a)},oa:function(a,b,c){Z.drawArrays(a,b,c)},pa:function(a,b,c,e){Z.drawElements(a,b,c,e)},j:function(a){Z.enable(a)},db:function(a){Z.enableVertexAttribArray(a)},l:function(a,b,c,e){Z.framebufferRenderbuffer(a,b,c,V[e])},d:function(a,b,c,e,f){Z.framebufferTexture2D(a,b,c,ob[e],f)},O:function(a){Z.frontFace(a)},M:function(a,b){xb(a,b,"createBuffer",mb)},o:function(a,b){xb(a,b,"createFramebuffer",nb)},
Ia:function(a,b){xb(a,b,"createRenderbuffer",V)},Fa:function(a,b){xb(a,b,"createTexture",ob)},wa:function(a,b){return Z.getAttribLocation(T[a],G(b))},i:function(a,b){yb(a,b)},Ca:function(a,b,c,e){a=Z.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&e?E(a,F,e,b):0;c&&(I[c>>2]=b)},E:function(a,b,c){if(c)if(a>=lb)X(1281);else{var e=rb[a];if(e)if(35716==b)a=Z.getProgramInfoLog(T[a]),null===a&&(a="(unknown error)"),I[c>>2]=a.length+1;else if(35719==b)I[c>>2]=e.jc;else if(35722==b){if(-1==
e.cc){a=T[a];var f=Z.getProgramParameter(a,35721);for(b=e.cc=0;b<f;++b)e.cc=Math.max(e.cc,Z.getActiveAttrib(a,b).name.length+1)}I[c>>2]=e.cc}else if(35381==b){if(-1==e.dc)for(a=T[a],f=Z.getProgramParameter(a,35382),b=e.dc=0;b<f;++b)e.dc=Math.max(e.dc,Z.getActiveUniformBlockName(a,b).length+1);I[c>>2]=e.dc}else I[c>>2]=Z.getProgramParameter(T[a],b);else X(1282)}else X(1281)},ya:function(a,b,c,e){a=Z.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");b=0<b&&e?E(a,F,e,b):0;c&&(I[c>>2]=b)},C:function(a,
b,c){c?35716==b?(a=Z.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),I[c>>2]=a?a.length+1:0):35720==b?(a=Z.getShaderSource(W[a]),I[c>>2]=a?a.length+1:0):I[c>>2]=Z.getShaderParameter(W[a],b):X(1281)},Oa:function(a){if(sb[a])return sb[a];switch(a){case 7939:var b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(e){return"GL_"+e}));b=zb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||X(1280);b=zb(b);break;case 7938:b=zb("OpenGL ES 2.0 ("+Z.getParameter(7938)+
")");break;case 35724:b=Z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=zb(b);break;default:return X(1280),0}return sb[a]=b},p:function(a,b){b=G(b);var c=0;if("]"==b[b.length-1]){var e=b.lastIndexOf("[");c="]"!=b[e+1]?parseInt(b.slice(e+1)):0;b=b.slice(0,e)}return(a=rb[a]&&rb[a].uc[b])&&0<=c&&c<a[0]?a[1]+c:-1},Da:function(a){Z.linkProgram(T[a]);var b=T[a];a=rb[a]={uc:{},jc:0,cc:-1,
dc:-1};for(var c=a.uc,e=Z.getProgramParameter(b,35718),f=0;f<e;++f){var k=Z.getActiveUniform(b,f),g=k.name;a.jc=Math.max(a.jc,g.length+1);"]"==g.slice(-1)&&(g=g.slice(0,g.lastIndexOf("[")));var m=Z.getUniformLocation(b,g);if(m){var n=Y(pb);c[g]=[k.size,n];pb[n]=m;for(var p=1;p<k.size;++p)m=Z.getUniformLocation(b,g+"["+p+"]"),n=Y(pb),pb[n]=m}}},P:function(a,b){Z.polygonOffset(a,b)},Ga:function(a,b,c,e){Z.renderbufferStorage(a,b,c,e)},va:function(a,b,c,e){Z.scissor(a,b,c,e)},Aa:function(a,b,c,e){for(var f=
"",k=0;k<b;++k){var g=e?I[e+4*k>>2]:-1;f+=G(I[c+4*k>>2],0>g?void 0:g)}Z.shaderSource(W[a],f)},La:function(a,b,c){Z.stencilFunc(a,b,c)},ra:function(a,b,c,e){Z.stencilFuncSeparate(a,b,c,e)},x:function(a){Z.stencilMask(a)},Ka:function(a,b,c){Z.stencilOp(a,b,c)},qa:function(a,b,c,e){Z.stencilOpSeparate(a,b,c,e)},H:function(a,b,c,e,f,k,g,m,n){Z.texImage2D(a,b,c,e,f,k,g,m,n?Ab(m,g,e,f,n):null)},k:function(a,b,c){Z.texParameteri(a,b,c)},m:function(a,b,c,e,f,k,g,m,n){var p=null;n&&(p=Ab(m,g,f,k,n));Z.texSubImage2D(a,
b,c,e,f,k,g,m,p)},D:function(a,b){Z.uniform1i(pb[a],b)},q:function(a){Z.useProgram(T[a])},$a:function(a,b){Z.vertexAttribDivisor(a,b)},eb:function(a,b,c,e,f,k){Z.vertexAttribPointer(a,b,c,!!e,f,k)},u:function(a,b,c,e){Z.viewport(a,b,c,e)},a:B,Wa:function(){d.oc=function(a){0!=Cb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",d.oc)},Ua:function(){d.tc=function(a){a=a.clipboardData.getData("text");C("_sapp_emsc_onpaste","void",["string"],[a])};window.addEventListener("paste",
d.tc)},Ta:function(a){d.Lc=[];a=G(a);a=document.getElementById(a);d.pc=function(b){b.stopPropagation();b.preventDefault()};d.qc=function(b){b.stopPropagation();b.preventDefault()};d.rc=function(b){b.stopPropagation();b.preventDefault()};d.sc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;d.Mc=c;Db(c.length);var e;for(e=0;e<c.length;e++)C("_sapp_emsc_drop","void",["number","string"],[e,c[e].name]);Eb(b.clientX,b.clientY)};a.addEventListener("dragenter",d.pc,!1);a.addEventListener("dragleave",
d.qc,!1);a.addEventListener("dragover",d.rc,!1);a.addEventListener("drop",d.sc,!1)},t:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Fb()});document.body.append(a)},s:function(){document.getElementById("_sokol_app_input_element").focus()},Qa:function(a){a=G(a);d.ec=document.getElementById(a);d.ec||console.log("sokol_app.h: invalid target:"+a);d.ec.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+
a)},Sa:function(){window.removeEventListener("beforeunload",d.oc)},Ra:function(){window.removeEventListener("paste",d.tc)},Pa:function(a){a=G(a);a=document.getElementById(a);a.removeEventListener("dragenter",d.pc);a.removeEventListener("dragleave",d.qc);a.removeEventListener("dragover",d.rc);a.removeEventListener("drop",d.sc)},A:function(){d.ec&&d.ec.requestPointerLock&&d.ec.requestPointerLock()},r:function(){document.getElementById("_sokol_app_input_element").blur()},Va:function(){for(var a=(new URLSearchParams(window.location.search)).entries(),
b=a.next();!b.done;b=a.next())C("_sargs_add_kvp","void",["string","string"],[b.value[0],b.value[1]])},ab:function(){return d.$b?d.$b.bufferSize:0},cb:function(a,b,c){d.Xb=null;d.$b=null;"undefined"!==typeof AudioContext?d.Xb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?d.Xb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(d.Xb=null,console.log("sokol_audio.h: no WebAudio support"));return d.Xb?(console.log("sokol_audio.h: sample rate ",
d.Xb.sampleRate),d.$b=d.Xb.createScriptProcessor(c,0,b),d.$b.onaudioprocess=function(e){var f=e.outputBuffer.length,k=Gb(f);if(k)for(var g=e.outputBuffer.numberOfChannels,m=0;m<g;m++)for(var n=e.outputBuffer.getChannelData(m),p=0;p<f;p++)n[p]=ua[(k>>2)+(g*p+m)]},d.$b.connect(d.Xb.destination),a=function(){d.Xb&&"suspended"===d.Xb.state&&d.Xb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),
1):0},bb:function(){return d.Xb?d.Xb.sampleRate:0},ma:function(){null!==d.Xb&&(d.$b&&d.$b.disconnect(),d.Xb.close(),d.Xb=null,d.$b=null)},B:function(){return performance.now()}};
(function(){function a(f){d.asm=f.exports;K=d.asm.jb;L--;d.monitorRunDependencies&&d.monitorRunDependencies(L);0==L&&(null!==Da&&(clearInterval(Da),Da=null),M&&(f=M,M=null,f()))}function b(f){a(f.instance)}function c(f){return Ia().then(function(k){return WebAssembly.instantiate(k,e)}).then(f,function(k){z("failed to asynchronously prepare wasm: "+k);x(k)})}var e={a:Hb};L++;d.monitorRunDependencies&&d.monitorRunDependencies(L);if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(f){return z("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){return A||"function"!==typeof WebAssembly.instantiateStreaming||Fa()||Ea("file://")||"function"!==typeof fetch?c(b):fetch(N,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(k){z("wasm streaming compile failed: "+k);z("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var Bb=d.___wasm_call_ctors=function(){return(Bb=d.___wasm_call_ctors=d.asm.kb).apply(null,arguments)};
d._emsc_load_data=function(){return(d._emsc_load_data=d.asm.lb).apply(null,arguments)};d.___em_js__emsc_fs_init=function(){return(d.___em_js__emsc_fs_init=d.asm.mb).apply(null,arguments)};d.___em_js__emsc_load_file=function(){return(d.___em_js__emsc_load_file=d.asm.nb).apply(null,arguments)};var Fb=d.__sapp_emsc_notify_keyboard_hidden=function(){return(Fb=d.__sapp_emsc_notify_keyboard_hidden=d.asm.ob).apply(null,arguments)};
d.__sapp_emsc_onpaste=function(){return(d.__sapp_emsc_onpaste=d.asm.pb).apply(null,arguments)};var Cb=d.__sapp_html5_get_ask_leave_site=function(){return(Cb=d.__sapp_html5_get_ask_leave_site=d.asm.qb).apply(null,arguments)},Db=d.__sapp_emsc_begin_drop=function(){return(Db=d.__sapp_emsc_begin_drop=d.asm.rb).apply(null,arguments)};d.__sapp_emsc_drop=function(){return(d.__sapp_emsc_drop=d.asm.sb).apply(null,arguments)};
var Eb=d.__sapp_emsc_end_drop=function(){return(Eb=d.__sapp_emsc_end_drop=d.asm.tb).apply(null,arguments)};d.__sapp_emsc_invoke_fetch_cb=function(){return(d.__sapp_emsc_invoke_fetch_cb=d.asm.ub).apply(null,arguments)};d.___em_js__sapp_js_create_textfield=function(){return(d.___em_js__sapp_js_create_textfield=d.asm.vb).apply(null,arguments)};d.___em_js__sapp_js_focus_textfield=function(){return(d.___em_js__sapp_js_focus_textfield=d.asm.wb).apply(null,arguments)};
d.___em_js__sapp_js_unfocus_textfield=function(){return(d.___em_js__sapp_js_unfocus_textfield=d.asm.xb).apply(null,arguments)};d.___em_js__sapp_js_add_beforeunload_listener=function(){return(d.___em_js__sapp_js_add_beforeunload_listener=d.asm.yb).apply(null,arguments)};d.___em_js__sapp_js_remove_beforeunload_listener=function(){return(d.___em_js__sapp_js_remove_beforeunload_listener=d.asm.zb).apply(null,arguments)};
d.___em_js__sapp_js_add_clipboard_listener=function(){return(d.___em_js__sapp_js_add_clipboard_listener=d.asm.Ab).apply(null,arguments)};d.___em_js__sapp_js_remove_clipboard_listener=function(){return(d.___em_js__sapp_js_remove_clipboard_listener=d.asm.Bb).apply(null,arguments)};d.___em_js__sapp_js_write_clipboard=function(){return(d.___em_js__sapp_js_write_clipboard=d.asm.Cb).apply(null,arguments)};
d.___em_js__sapp_js_add_dragndrop_listeners=function(){return(d.___em_js__sapp_js_add_dragndrop_listeners=d.asm.Db).apply(null,arguments)};d.___em_js__sapp_js_dropped_file_size=function(){return(d.___em_js__sapp_js_dropped_file_size=d.asm.Eb).apply(null,arguments)};d.___em_js__sapp_js_fetch_dropped_file=function(){return(d.___em_js__sapp_js_fetch_dropped_file=d.asm.Fb).apply(null,arguments)};
d.___em_js__sapp_js_remove_dragndrop_listeners=function(){return(d.___em_js__sapp_js_remove_dragndrop_listeners=d.asm.Gb).apply(null,arguments)};d.___em_js__sapp_js_pointer_init=function(){return(d.___em_js__sapp_js_pointer_init=d.asm.Hb).apply(null,arguments)};d.___em_js__sapp_js_request_pointerlock=function(){return(d.___em_js__sapp_js_request_pointerlock=d.asm.Ib).apply(null,arguments)};
d.___em_js__sapp_js_exit_pointerlock=function(){return(d.___em_js__sapp_js_exit_pointerlock=d.asm.Jb).apply(null,arguments)};d._main=function(){return(d._main=d.asm.Kb).apply(null,arguments)};d.___em_js__stm_js_perfnow=function(){return(d.___em_js__stm_js_perfnow=d.asm.Lb).apply(null,arguments)};var Gb=d.__saudio_emsc_pull=function(){return(Gb=d.__saudio_emsc_pull=d.asm.Mb).apply(null,arguments)};d.___em_js__saudio_js_init=function(){return(d.___em_js__saudio_js_init=d.asm.Nb).apply(null,arguments)};
d.___em_js__saudio_js_shutdown=function(){return(d.___em_js__saudio_js_shutdown=d.asm.Ob).apply(null,arguments)};d.___em_js__saudio_js_sample_rate=function(){return(d.___em_js__saudio_js_sample_rate=d.asm.Pb).apply(null,arguments)};d.___em_js__saudio_js_buffer_frames=function(){return(d.___em_js__saudio_js_buffer_frames=d.asm.Qb).apply(null,arguments)};d.__sargs_add_kvp=function(){return(d.__sargs_add_kvp=d.asm.Rb).apply(null,arguments)};
d.___em_js__sargs_js_parse_url=function(){return(d.___em_js__sargs_js_parse_url=d.asm.Sb).apply(null,arguments)};var R=d._malloc=function(){return(R=d._malloc=d.asm.Tb).apply(null,arguments)},ma=d.stackSave=function(){return(ma=d.stackSave=d.asm.Ub).apply(null,arguments)},na=d.stackRestore=function(){return(na=d.stackRestore=d.asm.Vb).apply(null,arguments)},D=d.stackAlloc=function(){return(D=d.stackAlloc=d.asm.Wb).apply(null,arguments)},Ib;
function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}M=function Jb(){Ib||Kb();Ib||(M=Jb)};
function Kb(a){function b(){if(!Ib&&(Ib=!0,d.calledRun=!0,!ja)){Ja(ya);Ja(za);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(Lb){var c=a,e=d._main;c=c||[];var f=c.length+1,k=D(4*(f+1));I[k>>2]=qa(aa);for(var g=1;g<f;g++)I[(k>>2)+g]=qa(c[g-1]);I[(k>>2)+f]=0;try{var m=e(f,k);if(!noExitRuntime||0!==m){if(!noExitRuntime){if(d.onExit)d.onExit(m);ja=!0}t(m,new ia(m))}}catch(n){n instanceof ia||("unwind"==n?noExitRuntime=!0:((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),z("exception thrown: "+
c),t(1,n)))}finally{}}if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;)c=d.postRun.shift(),Ba.unshift(c);Ja(Ba)}}a=a||r;if(!(0<L)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Ca();Ja(xa);0<L||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);b()},1)):b())}}d.run=Kb;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();
var Lb=!0;d.noInitialRun&&(Lb=!1);noExitRuntime=!0;Kb();
