var h;h||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),n,q=!1,na,la=a=>a.startsWith("file://"),r,t,oa,pa,v,w,x,y;
function qa(){var a=ra.buffer;r=new Int8Array(a);oa=new Int16Array(a);t=new Uint8Array(a);pa=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function sa(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!n)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&n)a=new Uint8Array(n);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!n&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(h)},za=[],Aa=[],Ba=()=>{var a=h.preRun.shift();Aa.push(a)},z=0,A=null,Ca=!0,Da=globalThis.TextDecoder&&new TextDecoder,B=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Da)return Da.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,
c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Ea=0,C={},Fa=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Ga=a=>{na=a;Ca||0<Ea||(h.onExit?.(a),q=!0);fa(a,new xa(a))},Ha=a=>{na=a;Ga(a)},Ia=()=>{if(!(Ca||0<Ea))try{var a=na;na=a;Ga(a)}catch(b){Fa(b)}},Ja=a=>{if(!q)try{a(),Ia()}catch(b){Fa(b)}},Qa=(a,b)=>{Ka=a;La=b;if(D)if(Ma||=!0,0==a)G=function(){setTimeout(H,Math.max(0,Na+b-performance.now())|0)};else if(1==a)G=function(){Oa(H)};else if(2==a){if(!Pa)if(globalThis.setImmediate)Pa=
setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Pa=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}G=function(){Pa(H)}}},Za=(a,b,c,d,e)=>{function g(){return f<Ra?(Ia(),!1):!0}D=a;Sa=d;var f=Ra;Ma=!1;H=function(){if(!q)if(0<Ta.length){var l=Ta.shift();l.Xd(l.Ld);if(Ua){var m=
Ua,p=0==m%1?m-1:Math.floor(m);Ua=l.Od?p:(8*m+(p+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",m=Ua??0,p=Va.Ud??0,m?m<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));g()&&setTimeout(H,0)}else if(g())if(Wa=Wa+1|0,1==Ka&&1<La&&0!=Wa%La)G();else{0==Ka&&(Na=performance.now());a:if(!q){for(l of Xa)if(!1===l())break a;Ja(a);for(m of Ya)m()}g()&&G()}};e||(0<b?Qa(0,1E3/b):Qa(1,1),G());if(c)throw"unwind";},Ma=!1,G=null,Ra=0,D=null,Sa=0,Ka=0,La=0,Wa=
0,Ta=[],Xa=[],Ya=[];function $a(){G=null;Ra++}var ab=0;function Oa(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ab)ab=b+1E3/60;else for(;b+2>=ab;)ab+=1E3/60;setTimeout(a,Math.max(ab-b,0))}}
var Va={},Na,H,Pa,Ua,bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],I=a=>{a=2<a?a?B(t,a):"":a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):null)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=[],J=a=>{var b=db[a];b||(db[a]=b=eb.get(a));return b};function fb(a){var b=K.Lc[a];b.target.removeEventListener(b.Kc,b.rd,b.Mc);K.Lc.splice(a,1)}
function gb(){if(navigator.userActivation?navigator.userActivation.isActive:K.bd&&K.Fd.Zc){var a=K.Rc;K.Rc=[];for(var b of a)b.ed(...b.nd)}}function L(a){if(!a.target)return-4;if(a.Nc)a.rd=function(c){++K.bd;K.Fd=a;gb();a.Oc(c);gb();--K.bd},a.target.addEventListener(a.Kc,a.rd,a.Mc),K.Lc.push(a);else for(var b=0;b<K.Lc.length;++b)K.Lc[b].target==a.target&&K.Lc[b].Kc==a.Kc&&fb(b--);return 0}function hb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var K={Md:0,Yd:0,cd:0,Xc:0,kd:0,hd:0,$c:0,Sd:0,ce:0,Rd:0,ad:0,dd:0,ke:0,gd:0,$d(a,b,c){r.set(r.subarray(b,b+c),a)},ee(){for(;K.Lc.length;)fb(K.Lc.length-1);K.Rc=[]},bd:0,Rc:[],Qd(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of K.Rc)if(e.ed==a&&d(e.nd,c))return;K.Rc.push({ed:a,vd:b,nd:c});K.Rc.sort((g,f)=>g.vd<f.vd)},ge(a){K.Rc=K.Rc.filter(b=>b.ed!=a)},Lc:[],fe:(a,b)=>{for(var c=0;c<K.Lc.length;++c)K.Lc[c].target!=a||b&&b!=K.Lc[c].Kc||
fb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},M=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.codePointAt(g);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;g++}}d[b]=0;return b-
e},ib=(a,b,c,d,e,g)=>{K.$c||(K.$c=N(256));a={target:I(a),Kc:g,Nc:d,Oc:(f=event)=>{var l=f.target.id?f.target.id:"",m=K.$c;M(hb(f.target),m+0,128);M(l,m+128,128);J(d)(e,m,b)&&f.preventDefault()},Mc:c};return L(a)},jb=(a,b,c,d,e)=>{K.ad||(K.ad=N(276));return L({target:a,Kc:e,Nc:d,Oc:(g=event)=>{var f=K.ad,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,m=!!l;r[f]=m;r[f+1]=K.fullscreenEnabled();
var p=m?l:K.Jd,u=p?.id||"";M(hb(p),f+2,128);M(u,f+130,128);v[f+260>>2]=p?p.clientWidth:0;v[f+264>>2]=p?p.clientHeight:0;v[f+268>>2]=screen.width;v[f+272>>2]=screen.height;m&&(K.Jd=l);J(d)(19,f,b)&&g.preventDefault()},Mc:c})},kb=(a,b,c,d,e,g)=>{K.cd||(K.cd=N(160));a={target:I(a),Kc:g,Nc:d,Oc:f=>{var l=K.cd;y[l>>3]=f.timeStamp;var m=l>>2;v[m+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;v[m+5]=f.charCode;v[m+6]=f.keyCode;v[m+7]=f.which;M(f.key||
"",l+32,32);M(f.code||"",l+64,32);M(f.char||"",l+96,32);M(f.locale||"",l+128,32);J(d)(e,l,b)&&f.preventDefault()},Mc:c};return L(a)},lb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=cb(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},mb=(a,b,c,d,e,g)=>{K.Xc||(K.Xc=N(64));a=
I(a);return L({target:a,Zc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,Kc:g,Nc:d,Oc:(f=event)=>{lb(K.Xc,f,a);J(d)(e,K.Xc,b)&&f.preventDefault()},Mc:c})},nb=(a,b,c,d)=>{K.dd||(K.dd=N(257));return L({target:a,Kc:"pointerlockchange",Nc:d,Oc:(e=event)=>{var g=K.dd,f=document.pointerLockElement;r[g]=!!f;var l=f?.id||"";M(hb(f),g+1,128);M(l,g+129,128);J(d)(20,g,b)&&e.preventDefault()},Mc:c})},ob=(a,b,c,d)=>L({target:a,Kc:"pointerlockerror",Nc:d,Oc:(e=event)=>{J(d)(38,0,b)&&e.preventDefault()},Mc:c}),
pb=(a,b,c,d)=>{K.hd||(K.hd=N(36));a=I(a);return L({target:a,Kc:"resize",Nc:d,Oc:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=K.hd;v[f>>2]=0;v[f+4>>2]=g.clientWidth;v[f+8>>2]=g.clientHeight;v[f+12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+20>>2]=outerWidth;v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|0;v[f+32>>2]=pageYOffset|0;J(d)(10,f,b)&&e.preventDefault()}}},Mc:c})},qb=(a,b,c,d,e,g)=>{K.gd||(K.gd=N(1552));a=I(a);return L({target:a,Zc:"touchstart"==g||"touchend"==g,Kc:g,Nc:d,Oc:f=>
{var l={},m=f.touches;for(var p of m)p.sd=p.ud=0,l[p.identifier]=p;for(var u of f.changedTouches)u.sd=1,l[u.identifier]=u;for(var E of f.targetTouches)l[E.identifier].ud=1;m=K.gd;y[m>>3]=f.timeStamp;r[m+12]=f.ctrlKey;r[m+13]=f.shiftKey;r[m+14]=f.altKey;r[m+15]=f.metaKey;p=m+16;u=cb(a);E=0;for(let F of Object.values(l))if(l=p>>2,v[l]=F.identifier,v[l+1]=F.screenX,v[l+2]=F.screenY,v[l+3]=F.clientX,v[l+4]=F.clientY,v[l+5]=F.pageX,v[l+6]=F.pageY,r[p+28]=F.sd,r[p+29]=F.ud,v[l+8]=F.clientX-(u.left|0),v[l+
9]=F.clientY-(u.top|0),p+=48,31<++E)break;v[m+8>>2]=E;J(d)(e,m,b)&&f.preventDefault()},Mc:c})},O,rb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},sb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},tb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},ub=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},vb=1,P=[],Q=[],wb=[],xb=[],R=[],S=[],yb=[],zb=[],T=[],Ab={},Bb=4,Cb=0,Db=a=>{for(var b=vb++,c=a.length;c<b;c++)a[c]=null;return b},V=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=O[c](),f=g&&Db(d);g?(g.name=f,d[f]=g):U||=1282;v[b+4*e>>2]=f}},Fb=(a,b)=>{a.md||(a.md=a.getContext,a.getContext=function(d,e){e=a.md(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.td?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Eb(c,b):0},Eb=(a,b)=>{var c=Db(zb),d={handle:c,attributes:b,version:b.td,ld:a};a.canvas&&(a.canvas.Kd=d);zb[c]=d;("undefined"==typeof b.qd||b.qd)&&Gb(d);return c},Gb=a=>{a||=W;if(!a.Id){a.Id=!0;var b=a.ld;b.be=b.getExtension("WEBGL_multi_draw");b.Wd=b.getExtension("EXT_polygon_offset_clamp");b.Vd=b.getExtension("EXT_clip_control");b.le=b.getExtension("WEBGL_polygon_mode");rb(b);sb(b);tb(b);b.Td=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Zd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.pd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.pd)b.pd=b.getExtension("EXT_disjoint_timer_query");ub(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},U,W,Hb=(a,b,c,d,e,g)=>{a={target:I(a),Kc:g,Nc:d,Oc:(f=event)=>{J(d)(e,0,b)&&f.preventDefault()},Mc:c};L(a)},Ib=(a,b,c,d)=>{K.kd||(K.kd=N(96));return L({target:a,Zc:!0,Kc:"wheel",Nc:d,Oc:(e=event)=>{var g=K.kd;lb(g,e,a);y[g+64>>3]=e.deltaX;y[g+72>>3]=e.deltaY;y[g+80>>3]=e.deltaZ;
v[g+88>>2]=e.deltaMode;J(d)(9,g,b)&&e.preventDefault()},Mc:c})},Jb=["default","low-power","high-performance"],Kb={},Mb=()=>{if(!Lb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Kb)void 0===Kb[b]?delete a[b]:a[b]=Kb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Lb=c}return Lb},Lb,Nb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=
d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ob=[null,[],[]],Pb=[],Qb=()=>{var a=ub(O);return a=a.concat(a.map(b=>"GL_"+b))},Rb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=O.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>W.version){U||=1282;return}c=Qb().length;break;case 33307:case 33308:if(2>W.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=O.getParameter(a),typeof d){case "number":c=
d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){U||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else U||=1281},Sb=a=>{var b=Nb(a)+1,c=N(b);c&&M(a,c,b);return c},Tb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ub=a=>{a-=5120;return 0==a?r:1==a?t:2==a?oa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==
a?w:pa},X=a=>{var b=O.Gd;if(b){var c=b.Tc[a];"number"==typeof c&&(b.Tc[a]=c=O.getUniformLocation(b,b.Dd[a]+(0<c?`[${c}]`:"")));return c}U||=1282},Y=[],Vb=[],Xb=a=>{var b=Nb(a)+1,c=Wb(b);M(a,c,b);return c},$b=a=>{var b=Yb();a();Zb(b)};h.requestAnimationFrame=Oa;h.pauseMainLoop=$a;h.resumeMainLoop=function(){Ra++;var a=Ka,b=La,c=D;D=null;Za(c,0,!1,Sa,!0);Qa(a,b);G()};h.preMainLoop&&Xa.push(h.preMainLoop);h.postMainLoop&&Ya.push(h.postMainLoop);for(let a=0;32>a;++a)Pb.push(Array(a));
for(var ac=new Float32Array(288),Z=0;288>=Z;++Z)Y[Z]=ac.subarray(0,Z);var bc=new Int32Array(288);for(Z=0;288>=Z;++Z)Vb[Z]=bc.subarray(0,Z);h.noExitRuntime&&(Ca=h.noExitRuntime);h.print&&(ma=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(n=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();
var N,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,Zb,Wb,Yb,ra,eb,tc={qa:function(){return 0},pb:function(){return 0},qb:function(){},tb:()=>sa(""),ib:()=>{Ca=!1;Ea=0},kb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ja(()=>sc(a,performance.now()))},b);C[a]={id:c,je:b};return 0},eb:function(a){if(void 0===window.localStorage)return 0;a=a?B(t,a):"";return(a=window.localStorage.getItem(a))?Sb(a):0},jc:function(a,b){void 0!==window.localStorage&&
(a=a?B(t,a):"",b=b?B(t,b):"",window.localStorage.setItem(a,b))},Sa:()=>{$a();D=null},ja:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,la:(a,b,c)=>{a=I(a);if(!a)return-4;a=cb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},y:()=>performance.now(),Ua:()=>performance.now(),Ya:(a,b)=>{function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},lb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=
(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ra.buffer.byteLength+65535)/65536|0;try{ra.grow(d);qa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},T:(a,b,c,d)=>ib(a,b,c,d,12,"blur"),ia:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},U:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),S:(a,b,c,d)=>{if(!K.fullscreenEnabled())return-1;a=I(a);if(!a)return-4;jb(a,b,c,d,"webkitfullscreenchange");return jb(a,b,c,d,"fullscreenchange")},ba:(a,b,c,d)=>kb(a,b,c,d,2,"keydown"),$:(a,
b,c,d)=>kb(a,b,c,d,1,"keypress"),aa:(a,b,c,d)=>kb(a,b,c,d,3,"keyup"),Za:(a,b,c)=>{a=J(a);Za(a,b,c)},ha:(a,b,c,d)=>mb(a,b,c,d,5,"mousedown"),ea:(a,b,c,d)=>mb(a,b,c,d,33,"mouseenter"),da:(a,b,c,d)=>mb(a,b,c,d,34,"mouseleave"),fa:(a,b,c,d)=>mb(a,b,c,d,8,"mousemove"),ga:(a,b,c,d)=>mb(a,b,c,d,6,"mouseup"),W:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?nb(a,b,c,d):-4:-1,V:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?ob(a,b,c,d):-4:-1,ka:(a,b,c,d)=>pb(a,b,c,d),X:(a,b,c,d)=>qb(a,b,c,d,25,
"touchcancel"),Y:(a,b,c,d)=>qb(a,b,c,d,23,"touchend"),Z:(a,b,c,d)=>qb(a,b,c,d,24,"touchmove"),_:(a,b,c,d)=>qb(a,b,c,d,22,"touchstart"),R:(a,b,c,d)=>{Hb(a,b,c,d,31,"webglcontextlost");return 0},Q:(a,b,c,d)=>{Hb(a,b,c,d,32,"webglcontextrestored");return 0},ca:(a,b,c,d)=>(a=I(a))?"undefined"!=typeof a.onwheel?Ib(a,b,c,d):-1:-4,Xa:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Jb[v[c+2]],
failIfMajorPerformanceCaveat:!!r[b+12],td:v[c+4],ae:v[c+5],qd:r[b+24],Hd:r[b+25],de:v[c+7],he:r[b+32]};a=I(a);return!a||b.Hd?0:Fb(a,b)},Wa:a=>{W=zb[a];h.ctx=O=W?.ld;return!a||O?0:-5},rb:(a,b)=>{var c=0,d=0,e;for(e of Mb()){var g=b+c;w[a+d>>2]=g;c+=M(e,g,Infinity)+1;d+=4}return 0},sb:(a,b)=>{var c=Mb();w[a>>2]=c.length;a=0;for(var d of c)a+=Nb(d)+1;w[b>>2]=a;return 0},pa:()=>52,ob:()=>52,mb:function(){return 70},nb:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=w[b>>2],l=w[b+4>>2];b+=8;for(var m=0;m<l;m++){var p=
a,u=t[f+m],E=Ob[p];0===u||10===u?((1===p?ma:k)(B(E)),E.length=0):E.push(u)}e+=l}w[d>>2]=e;return 0},g:function(a,b,c){const d=a?B(t,a):"";let e;try{e=window.indexedDB.open("chips",1)}catch(g){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+g)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");e.result.createObjectStore("store")};e.onsuccess=()=>{var g=e.result;let f;try{f=g.transaction(["store"],"readwrite")}catch(p){console.log("fs_js_load_snapshot: db.transaction failed with",
p);return}g=f.objectStore("store");const l=d+"_"+b,m=g.get(l);m.onsuccess=()=>{if(void 0!==m.result){const p=m.result.length;console.log("fs_js_load_snapshot:",l,"successfully loaded",p,"bytes");const u=cc(p);t.set(m.result,u);dc(c,u,p)}else dc(c,0,0)};m.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",l)};f.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},_a:function(a,b,c,d){const e=a?B(t,
a):"";console.log("fs_js_save_snapshot: called with",e,b);let g;try{g=window.indexedDB.open("chips",1)}catch(f){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+f);return}g.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");g.result.createObjectStore("store")};g.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");const f=g.result.transaction(["store"],"readwrite");var l=f.objectStore("store");const m=e+"_"+b;l=l.put(t.subarray(c,c+d),m);l.onsuccess=()=>
{console.log("fs_js_save_snapshot:",m,"successfully stored")};l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",m)};f.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};g.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},o:a=>O.activeTexture(a),B:(a,b)=>{O.attachShader(Q[a],S[b])},a:(a,b)=>{35051==a?O.od=b:35052==a&&(O.Sc=b);O.bindBuffer(a,P[b])},u:(a,b,c)=>{O.bindBufferBase(a,b,P[c])},Kb:(a,b,c,d,e)=>{O.bindBufferRange(a,b,P[c],d,e)},i:(a,
b)=>{O.bindFramebuffer(a,wb[b])},Vb:(a,b)=>{O.bindRenderbuffer(a,xb[b])},n:(a,b)=>{O.bindSampler(a,T[b])},c:(a,b)=>{O.bindTexture(a,R[b])},P:a=>{O.bindVertexArray(yb[a])},K:(a,b,c,d)=>O.blendColor(a,b,c,d),L:(a,b)=>O.blendEquationSeparate(a,b),M:(a,b,c,d)=>O.blendFuncSeparate(a,b,c,d),vb:(a,b,c,d,e,g,f,l,m,p)=>O.blitFramebuffer(a,b,c,d,e,g,f,l,m,p),Ga:(a,b,c,d)=>{2<=W.version?c&&b?O.bufferData(a,t,d,c,b):O.bufferData(a,b,d):O.bufferData(a,c?t.subarray(c,c+b):b,d)},E:(a,b,c,d)=>{2<=W.version?c&&O.bufferSubData(a,
b,t,d,c):O.bufferSubData(a,b,t.subarray(d,d+c))},Tb:a=>O.checkFramebufferStatus(a),Rb:(a,b,c,d)=>O.clearBufferfi(a,b,c,d),ua:(a,b,c)=>{O.clearBufferfv(a,b,x,c>>2)},Qb:(a,b,c)=>{O.clearBufferiv(a,b,v,c>>2)},p:(a,b,c,d)=>{O.colorMask(!!a,!!b,!!c,!!d)},_b:a=>{O.compileShader(S[a])},D:(a,b,c,d,e,g,f,l,m)=>{2<=W.version?O.Sc||!l?O.compressedTexSubImage2D(a,b,c,d,e,g,f,l,m):O.compressedTexSubImage2D(a,b,c,d,e,g,f,t,m,l):O.compressedTexSubImage2D(a,b,c,d,e,g,f,t.subarray(m,m+l))},hc:(a,b,c,d,e,g,f,l,m,p,
u)=>{O.Sc?O.compressedTexSubImage3D(a,b,c,d,e,g,f,l,m,p,u):O.compressedTexSubImage3D(a,b,c,d,e,g,f,l,m,t,u,p)},ec:()=>{var a=Db(Q),b=O.createProgram();b.name=a;b.Wc=b.Uc=b.Vc=0;b.jd=1;Q[a]=b;return a},ac:a=>{var b=Db(S);S[b]=O.createShader(a);return b},H:a=>O.cullFace(a),Ka:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=P[d];e&&(O.deleteBuffer(e),e.name=0,P[d]=null,d==O.od&&(O.od=0),d==O.Sc&&(O.Sc=0))}},t:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=wb[d];e&&(O.deleteFramebuffer(e),e.name=0,
wb[d]=null)}},m:a=>{if(a){var b=Q[a];b?(O.deleteProgram(b),b.name=0,Q[a]=null):U||=1281}},F:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=xb[d];e&&(O.deleteRenderbuffer(e),e.name=0,xb[d]=null)}},G:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=T[d];e&&(O.deleteSampler(e),e.name=0,T[d]=null)}},r:a=>{if(a){var b=S[a];b?(O.deleteShader(b),S[a]=null):U||=1281}},j:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=R[d];e&&(O.deleteTexture(e),e.name=0,R[d]=null)}},Ia:(a,b)=>{for(var c=0;c<a;c++){var d=
v[b+4*c>>2];O.deleteVertexArray(yb[d]);yb[d]=null}},w:a=>O.depthFunc(a),v:a=>{O.depthMask(!!a)},d:a=>O.disable(a),N:a=>{O.disableVertexAttribArray(a)},xb:(a,b,c)=>{O.drawArrays(a,b,c)},yb:(a,b,c,d)=>{O.drawArraysInstanced(a,b,c,d)},wa:(a,b)=>{for(var c=Pb[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];O.drawBuffers(c)},zb:(a,b,c,d)=>{O.drawElements(a,b,c,d)},Ab:(a,b,c,d,e)=>{O.drawElementsInstanced(a,b,c,d,e)},f:a=>O.enable(a),Lb:a=>{O.enableVertexAttribArray(a)},va:(a,b,c,d)=>{O.framebufferRenderbuffer(a,b,c,xb[d])},
k:(a,b,c,d,e)=>{O.framebufferTexture2D(a,b,c,R[d],e)},A:(a,b,c,d,e)=>{O.framebufferTextureLayer(a,b,R[c],d,e)},I:a=>O.frontFace(a),Ha:(a,b)=>{V(a,b,"createBuffer",P)},O:(a,b)=>{V(a,b,"createFramebuffer",wb)},Wb:(a,b)=>{V(a,b,"createRenderbuffer",xb)},fc:(a,b)=>{V(a,b,"createSampler",T)},Fa:(a,b)=>{V(a,b,"createTexture",R)},Ra:(a,b)=>{V(a,b,"createVertexArray",yb)},Xb:(a,b)=>O.getAttribLocation(Q[a],b?B(t,b):""),b:(a,b)=>Rb(a,b),cc:(a,b,c,d)=>{a=O.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");
b=0<b&&d?M(a,d,b):0;c&&(v[c>>2]=b)},za:(a,b,c)=>{if(c)if(a>=vb)U||=1281;else if(a=Q[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.Wc){var d=O.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Wc=Math.max(a.Wc,O.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.Wc}else if(35722==b){if(!a.Uc)for(d=O.getProgramParameter(a,35721),b=0;b<d;++b)a.Uc=Math.max(a.Uc,O.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.Uc}else if(35381==b){if(!a.Vc)for(d=
O.getProgramParameter(a,35382),b=0;b<d;++b)a.Vc=Math.max(a.Vc,O.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Vc}else v[c>>2]=O.getProgramParameter(a,b);else U||=1281},Zb:(a,b,c,d)=>{a=O.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(v[c>>2]=b)},xa:(a,b,c)=>{c?35716==b?(a=O.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(S[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=O.getShaderParameter(S[a],b):U||=1281},Pa:(a,
b)=>{if(2>W.version)return U||=1282,0;var c=Ab[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Qb().map(Sb),c=Ab[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},ya:(a,b)=>{b=b?B(t,b):"";if(a=Q[a]){var c=a,d=c.Tc,e=c.Ed,g;if(!d){c.Tc=d={};c.Dd={};var f=O.getProgramParameter(c,35718);for(g=0;g<f;++g){var l=O.getActiveUniform(c,g);var m=l.name;l=l.size;var p=Tb(m);p=0<p?m.slice(0,p):m;var u=c.jd;c.jd+=l;e[p]=[l,u];for(m=0;m<l;++m)d[u]=m,c.Dd[u++]=p}}c=
a.Tc;d=0;e=b;g=Tb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Ed[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else U||=1281;return-1},ub:(a,b,c)=>{for(var d=Pb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];O.invalidateFramebuffer(a,d)},Aa:a=>{a=Q[a];O.linkProgram(a);a.Tc=0;a.Ed={}},Qa:(a,b)=>{3317==a?Bb=b:3314==a&&(Cb=b);O.pixelStorei(a,b)},J:(a,b)=>O.polygonOffset(a,b),wb:a=>O.readBuffer(a),Ub:(a,b,c,d,e)=>O.renderbufferStorageMultisample(a,b,c,d,e),Ba:(a,b,c)=>{O.samplerParameterf(T[a],
b,c)},e:(a,b,c)=>{O.samplerParameteri(T[a],b,c)},q:(a,b,c,d)=>O.scissor(a,b,c,d),$b:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=w[c+4*g>>2])?B(t,f,d?w[d+4*g>>2]:void 0):"";e+=f}O.shaderSource(S[a],e)},Na:(a,b,c)=>O.stencilFunc(a,b,c),ta:(a,b,c,d)=>O.stencilFuncSeparate(a,b,c,d),s:a=>O.stencilMask(a),Ma:(a,b,c)=>O.stencilOp(a,b,c),sa:(a,b,c,d)=>O.stencilOpSeparate(a,b,c,d),Ea:(a,b,c,d,e)=>O.texStorage2D(a,b,c,d,e),Da:(a,b,c,d,e,g)=>O.texStorage3D(a,b,c,d,e,g),C:(a,b,c,d,e,g,f,l,m)=>{if(2<=W.version){if(O.Sc){O.texSubImage2D(a,
b,c,d,e,g,f,l,m);return}if(m){var p=Ub(l);O.texSubImage2D(a,b,c,d,e,g,f,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}if(m){p=Ub(l);var u=g*((Cb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*p.BYTES_PER_ELEMENT+Bb-1&-Bb);m=p.subarray(m>>>31-Math.clz32(p.BYTES_PER_ELEMENT),m+u>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else m=null;O.texSubImage2D(a,b,c,d,e,g,f,l,m)},gc:(a,b,c,d,e,g,f,l,m,p,u)=>{if(O.Sc)O.texSubImage3D(a,b,c,d,e,g,f,l,m,p,u);else if(u){var E=Ub(p);
O.texSubImage3D(a,b,c,d,e,g,f,l,m,p,E,u>>>31-Math.clz32(E.BYTES_PER_ELEMENT))}else O.texSubImage3D(a,b,c,d,e,g,f,l,m,p,null)},Jb:(a,b,c)=>{if(2<=W.version)b&&O.uniform1fv(X(a),x,c>>2,b);else{if(288>=b)for(var d=Y[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);O.uniform1fv(X(a),d)}},bc:(a,b)=>{O.uniform1i(X(a),b)},Fb:(a,b,c)=>{if(2<=W.version)b&&O.uniform1iv(X(a),v,c>>2,b);else{if(288>=b)for(var d=Vb[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);O.uniform1iv(X(a),
d)}},Ib:(a,b,c)=>{if(2<=W.version)b&&O.uniform2fv(X(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Y[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);O.uniform2fv(X(a),d)}},Eb:(a,b,c)=>{if(2<=W.version)b&&O.uniform2iv(X(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Vb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);O.uniform2iv(X(a),d)}},Hb:(a,b,c)=>{if(2<=W.version)b&&O.uniform3fv(X(a),x,c>>2,3*b);else{if(96>=b){b*=3;
for(var d=Y[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);O.uniform3fv(X(a),d)}},Db:(a,b,c)=>{if(2<=W.version)b&&O.uniform3iv(X(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Vb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);O.uniform3iv(X(a),d)}},Gb:(a,b,c)=>{if(2<=W.version)b&&O.uniform4fv(X(a),x,c>>2,4*b);else{if(72>=b){var d=Y[4*b],e=x;c>>=2;b*=4;for(var g=0;g<b;g+=
4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);O.uniform4fv(X(a),d)}},Cb:(a,b,c)=>{if(2<=W.version)b&&O.uniform4iv(X(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Vb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);O.uniform4iv(X(a),d)}},Bb:(a,b,c,d)=>{if(2<=W.version)b&&O.uniformMatrix4fv(X(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=Y[16*b],g=x;d>>=2;b*=16;for(var f=
0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(X(a),!!c,e)}},l:a=>{a=Q[a];O.useProgram(a);O.Gd=a},Nb:(a,b)=>{O.vertexAttribDivisor(a,b)},Ob:(a,b,c,d,e)=>{O.vertexAttribIPointer(a,b,c,d,e)},Pb:(a,b,c,d,e,g)=>{O.vertexAttribPointer(a,b,c,!!d,
e,g)},h:(a,b,c,d)=>O.viewport(a,b,c,d),hb:Ga,Va:function(){h.wd=a=>{0!=fc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.wd)},Oa:function(){h.Cd=a=>{const b=a.clipboardData.getData("text");$b(()=>{const c=Xb(b);ec(c)})};window.addEventListener("paste",h.Cd)},ic:function(){h.ie=[];h.xd=b=>{b.stopPropagation();b.preventDefault()};h.yd=b=>{b.stopPropagation();b.preventDefault()};h.zd=b=>{b.stopPropagation();b.preventDefault()};h.Ad=b=>{b.stopPropagation();b.preventDefault();
const c=b.dataTransfer.files;h.Bd=c;gc(c.length);for(let e=0;e<c.length;e++)$b(()=>{const g=Xb(c[e].name);hc(e,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);ic(b.clientX,b.clientY,d)};const a=h.Pc;a.addEventListener("dragenter",h.xd,!1);a.addEventListener("dragleave",h.yd,!1);a.addEventListener("dragover",h.zd,!1);a.addEventListener("drop",h.Ad,!1)},gb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},jb:function(a){h.Yc&&
(URL.revokeObjectURL(h.Yc[a].Nd),h.Yc[a]=null)},dc:function(a){const b=h.Bd;return 0>a||a>=b.length?0:b[a].size},Yb:function(a,b,c,d,e){const g=new FileReader;g.onload=f=>{f=f.target.result;f.byteLength>d?jc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(f),c),jc(a,1,0,b,f.byteLength,c,d,e))};g.onerror=()=>{jc(a,0,2,b,0,c,d,e)};g.readAsArrayBuffer(h.Bd[a])},Mb:function(a,b){0!==b&&(document.title=b?B(t,b):"");a=a?B(t,a):"";void 0!==h.canvas&&("object"===typeof h.canvas?bb[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
h.Pc=I(a);h.Pc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Pc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ta:function(){window.removeEventListener("beforeunload",h.wd)},La:function(){window.removeEventListener("paste",h.Cd)},Sb:function(){const a=h.Pc;a.removeEventListener("dragenter",h.xd);a.removeEventListener("dragleave",h.yd);a.removeEventListener("dragover",h.zd);a.removeEventListener("drop",h.Ad)},z:function(){h.Pc&&
h.Pc.requestPointerLock&&h.Pc.requestPointerLock()},ra:function(a,b,c){if(h.Pc){if(0===b)a="none";else if(0!=c)a=h.Yc[a].Pd;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.Pc.style.cursor=a}},fb:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,b);g.data.set(t.subarray(c,c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ja:function(a){a=a?B(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";
b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},$a:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];$b(()=>{const e=Xb(c),g=Xb(d);mc(e,g)})}},bb:function(){return h.Qc?h.Qc.bufferSize:0},db:function(a,b,c){h.Jc=null;h.Qc=null;"undefined"!==typeof AudioContext?h.Jc=new AudioContext({sampleRate:a,
latencyHint:"interactive"}):(h.Jc=null,console.log("sokol_audio.h: no WebAudio support"));return h.Jc?(console.log("sokol_audio.h: sample rate ",h.Jc.sampleRate),h.Qc=h.Jc.createScriptProcessor(c,0,b),h.Qc.onaudioprocess=d=>{const e=d.outputBuffer.length,g=lc(e);if(g){const f=d.outputBuffer.numberOfChannels;for(let l=0;l<f;l++){const m=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)m[p]=x[(g>>2)+(f*p+l)]}}},h.Qc.connect(h.Jc.destination),a=()=>{h.Jc&&"suspended"===h.Jc.state&&h.Jc.resume()},
document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},cb:function(){return h.Jc?h.Jc.sampleRate:0},oa:function(){const a=h.Jc;null!==a&&(h.Qc&&h.Qc.disconnect(),a.close(),h.Jc=null,h.Qc=null)},ab:function(){if(h.Jc)return"suspended"===h.Jc.state?1:0},x:function(a,b,c,d,e,g){const f=b?B(t,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(f,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>
{m=new Uint8Array(m);m.length<=g?(t.set(m,e),oc(a,d,m.length)):qc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,m);rc(a)}):pc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,l);rc(a)})},na:function(a,b){const c=b?B(t,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),rc(a)):nc(a,Number(d))):pc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,
d);rc(a)})},Ca:function(){return navigator.userAgent.includes("Macintosh")?1:0},ma:function(a,b){b=b?B(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function uc(a=[]){var b=kc;a.unshift(ea);var c=a.length,d=Wb(4*(c+1)),e=d;a.forEach(f=>{w[e>>2]=Xb(f);e+=4});w[e>>2]=0;try{var g=b(c,d);Ha(g)}catch(f){Fa(f)}}
function vc(a=da){function b(){h.calledRun=!0;if(!q){wc.lc();h.onRuntimeInitialized?.();h.noInitialRun||uc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();za.push(c)}ya(za)}}if(0<z)A=vc;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ba();ya(Aa);0<z?A=vc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var wc;
(async function(){function a(c){c=wc=c.exports;N=c.mc;cc=h._fs_emsc_alloc=c.nc;dc=h._fs_emsc_load_snapshot_callback=c.oc;ec=h.__sapp_emsc_onpaste=c.pc;fc=h.__sapp_html5_get_ask_leave_site=c.qc;gc=h.__sapp_emsc_begin_drop=c.rc;hc=h.__sapp_emsc_drop=c.sc;ic=h.__sapp_emsc_end_drop=c.tc;jc=h.__sapp_emsc_invoke_fetch_cb=c.uc;h.__sapp_emsc_set_fullscreen_flag=c.vc;kc=h._main=c.wc;lc=h.__saudio_emsc_pull=c.xc;mc=h.__sargs_add_kvp=c.yc;nc=h.__sfetch_emsc_head_response=c.zc;oc=h.__sfetch_emsc_get_response=
c.Ac;pc=h.__sfetch_emsc_failed_http_status=c.Bc;qc=h.__sfetch_emsc_failed_buffer_too_small=c.Cc;rc=h.__sfetch_emsc_failed_other=c.Dc;sc=c.Fc;Zb=c.Gc;Wb=c.Hc;Yb=c.Ic;ra=c.kc;eb=c.Ec;qa();z--;h.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return wc}z++;h.monitorRunDependencies?.(z);var b={a:tc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ta??=h.locateFile?h.locateFile("vic20-ui.wasm",ia):ia+"vic20-ui.wasm";return a((await wa(b)).instance)})();vc();
