var f;f||(f=typeof Module !== 'undefined' ? Module : {});var h={},k;for(k in f)f.hasOwnProperty(k)&&(h[k]=f[k]);f.arguments=[];f.thisProgram="./this.program";f.quit=function(a,b){throw b;};f.preRun=[];f.postRun=[];var m=!1,r=!1,aa=!1,ba=!1;m="object"===typeof window;r="function"===typeof importScripts;aa="object"===typeof process&&"function"===typeof require&&!m&&!r;ba=!m&&!aa&&!r;var u="";
if(aa){u=__dirname+"/";var ca,da;f.read=function(a,b){ca||(ca=require("fs"));da||(da=require("path"));a=da.normalize(a);a=ca.readFileSync(a);return b?a:a.toString()};f.readBinary=function(a){a=f.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(f.thisProgram=process.argv[1].replace(/\\/g,"/"));f.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=f);process.on("uncaughtException",function(a){if(!(a instanceof v))throw a;});process.on("unhandledRejection",
x);f.quit=function(a){process.exit(a)};f.inspect=function(){return"[Emscripten Module object]"}}else if(ba)"undefined"!=typeof read&&(f.read=function(a){return read(a)}),f.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?f.arguments=scriptArgs:"undefined"!=typeof arguments&&(f.arguments=arguments),"function"===typeof quit&&(f.quit=function(a){quit(a)});else if(m||r)r?
u=self.location.href:document.currentScript&&(u=document.currentScript.src),u=0!==u.indexOf("blob:")?u.substr(0,u.lastIndexOf("/")+1):"",f.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},r&&(f.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),f.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},f.setWindowTitle=function(a){document.title=a};var ea=f.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),y=f.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ea);for(k in h)h.hasOwnProperty(k)&&(f[k]=h[k]);h=void 0;"object"!==typeof WebAssembly&&y("no native wasm support detected");var fa,ha=!1;
function assert(a,b){a||x("Assertion failed: "+b)}function ia(a){var b=f["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function ja(a,b,c,d){var e={string:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=ka(c);z(a,A,b,c)}return b},array:function(a){var b=ka(a.length);la.set(a,b);return b}},g=ia(a),l=[];a=0;if(d)for(var n=0;n<d.length;n++){var t=e[c[n]];t?(0===a&&(a=ma()),l[n]=t(d[n])):l[n]=d[n]}c=g.apply(null,l);c=function(a){return"string"===b?B(a):"boolean"===b?!!a:a}(c);0!==a&&na(a);return c}var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function pa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&oa)return oa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|l:(e&7)<<18|g<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function B(a,b){return a?pa(A,a,b):""}
function z(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var n=a.charCodeAt(++g);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function qa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ra(a){var b=qa(a)+1,c=ka(b);z(a,la,c,b);return c}var buffer,la,A,sa,ta,C,ua,D,E,F=f.TOTAL_MEMORY||33554432;5242880>F&&y("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+F+"! (TOTAL_STACK=5242880)");
f.buffer?buffer=f.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(fa=new WebAssembly.Memory({initial:F/65536,maximum:F/65536}),buffer=fa.buffer):buffer=new ArrayBuffer(F);f.HEAP8=la=new Int8Array(buffer);f.HEAP16=sa=new Int16Array(buffer);f.HEAP32=C=new Int32Array(buffer);f.HEAPU8=A=new Uint8Array(buffer);f.HEAPU16=ta=new Uint16Array(buffer);f.HEAPU32=ua=new Uint32Array(buffer);f.HEAPF32=D=new Float32Array(buffer);f.HEAPF64=E=new Float64Array(buffer);C[1688332]=11996240;
function G(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Sb;"number"===typeof c?void 0===b.Jb?f.dynCall_v(c):f.dynCall_vi(c,b.Jb):c(void 0===b.Jb?null:b.Jb)}}}var va=[],wa=[],xa=[],ya=[],Aa=[],Ba=!1;function Ca(){var a=f.preRun.shift();va.unshift(a)}var Da=Math.abs,Ea=Math.sqrt,Fa=Math.floor,H=0,Ga=null,I=null;f.preloadedImages={};f.preloadedAudios={};
function Ha(){var a=J;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var J="z1013-ui.wasm";if(!Ha()){var Ia=J;J=f.locateFile?f.locateFile(Ia,u):u+Ia}function Ja(){try{if(f.wasmBinary)return new Uint8Array(f.wasmBinary);if(f.readBinary)return f.readBinary(J);throw"both async and sync fetching of the wasm failed";}catch(a){x(a)}}
function Ka(){return f.wasmBinary||!m&&!r||"function"!==typeof fetch?new Promise(function(a){a(Ja())}):fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Ja()})}
function La(a){function b(a){f.asm=a.exports;H--;f.monitorRunDependencies&&f.monitorRunDependencies(H);0==H&&(null!==Ga&&(clearInterval(Ga),Ga=null),I&&(a=I,I=null,a()))}function c(a){b(a.instance)}function d(a){return Ka().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){y("failed to asynchronously prepare wasm: "+a);x(a)})}var e={env:a};H++;f.monitorRunDependencies&&f.monitorRunDependencies(H);if(f.instantiateWasm)try{return f.instantiateWasm(e,b)}catch(g){return y("Module.instantiateWasm callback failed with error: "+
g),!1}(function(){return f.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Ha()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(J,{credentials:"same-origin"}),e).then(c,function(a){y("wasm streaming compile failed: "+a);y("falling back to ArrayBuffer instantiation");d(c)})})();return{}}f.asm=function(a,b){b.memory=fa;b.table=new WebAssembly.Table({initial:53,maximum:53,element:"anyfunc"});return La(b)};wa.push({Sb:function(){Ma()}});var Na=[null,[],[]],K=0;
function L(){K+=4;return C[K-4>>2]}var Oa={};function Pa(){f.___errno_location&&(C[f.___errno_location()>>2]=12)}var Qa=0,Ra=0,M=0,Sa=0,Ta=0,Ua=null,Va=null,Wa=!1;function Xa(){for(var a=N.length-1;0<=a;--a)Ya(a);N=[];Za=[]}var Za=[];function $a(){if(ab&&bb.Cb)for(var a=0;a<Za.length;++a){var b=Za[a];Za.splice(a,1);--a;b.dc.apply(this,b.Xb)}}var ab=0,bb=null,N=[];function cb(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}
function Ya(a){var b=N[a];b.target.removeEventListener(b.Bb,b.Qb,b.Db);N.splice(a,1)}function O(a){function b(b){++ab;bb=a;$a();a.Fb(b);$a();--ab}if(a.Eb)a.Qb=b,a.target.addEventListener(a.Bb,b,a.Db),N.push(a),Wa||(ya.push(Xa),Wa=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Bb==a.Bb&&Ya(c--)}var db=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function P(a){try{if(!a)return window;"number"===typeof a&&(a=db[a]||B(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?f.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function eb(a){"number"===typeof a&&(a=B(a));return a&&"#canvas"!==a?"undefined"!==typeof fb&&gb[a]?gb[a]:P(a):"undefined"!==typeof fb&&gb.canvas?gb.canvas:f.canvas}
function hb(a,b,c,d,e,g){Qa||(Qa=Q(164));a={target:P(a),Cb:cb()?!1:!0,Bb:g,Eb:d,Fb:function(a){a=a||window.event;var c=Qa;z(a.key?a.key:"",A,c+0,32);z(a.code?a.code:"",A,c+32,32);C[c+64>>2]=a.location;C[c+68>>2]=a.ctrlKey;C[c+72>>2]=a.shiftKey;C[c+76>>2]=a.altKey;C[c+80>>2]=a.metaKey;C[c+84>>2]=a.repeat;z(a.locale?a.locale:"",A,c+88,32);z(a.char?a.char:"",A,c+120,32);C[c+152>>2]=a.charCode;C[c+156>>2]=a.keyCode;C[c+160>>2]=a.which;R(d,e,c,b)&&a.preventDefault()},Db:c};O(a)}
function kb(a,b,c){E[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();C[a+8>>2]=b.screenX;C[a+12>>2]=b.screenY;C[a+16>>2]=b.clientX;C[a+20>>2]=b.clientY;C[a+24>>2]=b.ctrlKey;C[a+28>>2]=b.shiftKey;C[a+32>>2]=b.altKey;C[a+36>>2]=b.metaKey;sa[a+40>>1]=b.button;sa[a+42>>1]=b.buttons;C[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-Ua;C[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-Va;if(f.canvas){var d=f.canvas.getBoundingClientRect();
C[a+60>>2]=b.clientX-d.left;C[a+64>>2]=b.clientY-d.top}else C[a+60>>2]=0,C[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},C[a+52>>2]=b.clientX-d.left,C[a+56>>2]=b.clientY-d.top):(C[a+52>>2]=0,C[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(Ua=b.screenX,Va=b.screenY)}
function S(a,b,c,d,e,g){Ra||(Ra=Q(72));a=P(a);c={target:a,Cb:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,Bb:g,Eb:d,Fb:function(c){c=c||window.event;kb(Ra,c,a);R(d,e,Ra,b)&&c.preventDefault()},Db:c};cb()&&"mousedown"==g&&(c.Cb=!1);O(c)}
function lb(a,b,c,d){Sa||(Sa=Q(36));a=P(a);O({target:a,Cb:!1,Bb:"resize",Eb:d,Fb:function(c){c=c||window.event;if(c.target==a){var e=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],l=Sa;C[l>>2]=c.detail;C[l+4>>2]=document.body.clientWidth;
C[l+8>>2]=document.body.clientHeight;C[l+12>>2]=window.innerWidth;C[l+16>>2]=window.innerHeight;C[l+20>>2]=window.outerWidth;C[l+24>>2]=window.outerHeight;C[l+28>>2]=e[0];C[l+32>>2]=e[1];R(d,10,l,b)&&c.preventDefault()}},Db:c})}
function mb(a,b,c,d,e,g){Ta||(Ta=Q(1684));a=P(a);O({target:a,Cb:"touchstart"==g||"touchend"==g,Bb:g,Eb:d,Fb:function(c){c=c||window.event;for(var g={},l=0;l<c.touches.length;++l){var q=c.touches[l];g[q.identifier]=q}for(l=0;l<c.changedTouches.length;++l)q=c.changedTouches[l],g[q.identifier]=q,q.Pb=!0;for(l=0;l<c.targetTouches.length;++l)q=c.targetTouches[l],g[q.identifier].Vb=!0;var p=q=Ta;C[p+4>>2]=c.ctrlKey;C[p+8>>2]=c.shiftKey;C[p+12>>2]=c.altKey;C[p+16>>2]=c.metaKey;p+=20;var za=f.canvas?f.canvas.getBoundingClientRect():
void 0,ib=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},jb=0;for(l in g){var w=g[l];C[p>>2]=w.identifier;C[p+4>>2]=w.screenX;C[p+8>>2]=w.screenY;C[p+12>>2]=w.clientX;C[p+16>>2]=w.clientY;C[p+20>>2]=w.pageX;C[p+24>>2]=w.pageY;C[p+28>>2]=w.Pb;C[p+32>>2]=w.Vb;za?(C[p+44>>2]=w.clientX-za.left,C[p+48>>2]=w.clientY-za.top):(C[p+44>>2]=0,C[p+48>>2]=0);C[p+36>>2]=w.clientX-ib.left;C[p+40>>2]=w.clientY-ib.top;p+=52;if(32<=++jb)break}C[q>>2]=jb;R(d,e,q,b)&&c.preventDefault()},Db:c})}
function nb(a,b,c,d,e,g){a||(a=f.canvas);a={target:P(a),Cb:!1,Bb:g,Eb:d,Fb:function(a){a=a||window.event;R(d,e,0,b)&&a.preventDefault()},Db:c};O(a)}
function ob(a,b,c,d,e){function g(c){c=c||window.event;kb(M,c,a);E[M+72>>3]=c.wheelDeltaX||0;E[M+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);E[M+88>>3]=0;C[M+96>>2]=0;R(d,9,M,b)&&c.preventDefault()}function l(c){c=c||window.event;var e=M;kb(e,c,a);E[e+72>>3]=c.deltaX;E[e+80>>3]=c.deltaY;E[e+88>>3]=c.deltaZ;C[e+96>>2]=c.deltaMode;R(d,9,e,b)&&c.preventDefault()}M||(M=Q(104));O({target:a,Cb:!0,Bb:e,Eb:d,Fb:"wheel"==e?l:g,Db:c})}
var pb=1,qb=0,rb=[],T=[],sb=[],U=[],tb=[],V=[],W=[],ub={},vb=null,gb={},wb={},xb={};function X(a){qb||(qb=a)}function yb(a){for(var b=pb++,c=a.length;c<b;c++)a[c]=null;return b}var zb=null,Y=[0];
function Ab(a){a||(a=vb);if(!a.Tb){a.Tb=!0;var b=a.Lb;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,e){c.drawArraysInstancedANGLE(a,b,d,e)},b.drawElementsInstanced=function(a,b,d,e,g){c.drawElementsInstancedANGLE(a,b,d,e,g)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var e=b.getExtension("WEBGL_draw_buffers");e&&(b.drawBuffers=function(a,b){e.drawBuffersWEBGL(a,b)})}b.Zb=b.getExtension("EXT_disjoint_timer_query");var g="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=g.indexOf(a)&&b.getExtension(a)})}}var fb={},Bb,Cb,Db=["default","low-power","high-performance"];function Eb(a,b,c,d){for(var e=0;e<a;e++){var g=Z[c](),l=g&&yb(d);g?(g.name=l,d[l]=g):X(1282);C[b+4*e>>2]=l}}
function Fb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":X(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:X(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)C[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){X(1280);y("GL_INVALID_ENUM in glGetIntegerv: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:X(1280);return}C[b>>2]=c}else X(1281)}function Gb(a){var b=qa(a)+1,c=Q(b);z(a,A,c,b);return c}var Hb={6402:1,6406:1,6407:3,6408:4,6409:1,6410:2,35904:3,35906:4},Ib={5121:1,5123:2,5125:4,5126:4,32819:2,32820:2,33635:2,34042:4,36193:2};
function Jb(a,b,c,d,e){if(b=Hb[b]*Ib[a])switch(c=e+d*(c*b+4-1&-4),a){case 5121:return A.subarray(e,c);case 5126:return D.subarray(e>>2,c>>2);case 5125:case 34042:return ua.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return ta.subarray(e>>1,c>>1);default:X(1280)}else X(1280)}var Z;zb=new Float32Array(256);for(var Kb=0;256>Kb;Kb++)Y[Kb]=zb.subarray(0,Kb+1);
var Nb=f.asm({},{eb:function(){},gb:function(a,b){K=b;try{return Oa.Nb(),L(),L(),L(),L(),0}catch(c){return x(c),-c.Ib}},cb:function(a,b){K=b;try{var c=Oa.Nb(),d=L(),e=L();return Oa.$b(c,d,e)}catch(g){return x(g),-g.Ib}},ba:function(a,b){K=b;try{var c=L(),d=L(),e=L();for(b=a=0;b<e;b++){for(var g=C[d+8*b>>2],l=C[d+(8*b+4)>>2],n=0;n<l;n++){var t=A[g+n],q=Na[c];0===t||10===t?((1===c?ea:y)(pa(q,0)),q.length=0):q.push(t)}a+=l}return a}catch(p){return x(p),-p.Ib}},x:function(a,b){K=b;return 0},fb:function(a,
b){K=b;try{var c=B(L()),d=L(),e=L();return(void 0).open(c,d,e).fd}catch(g){return x(g),-g.Ib}},$:function(a,b){K=b;return 0},ca:function(a,b){K=b;try{return Oa.Nb(),0}catch(c){return x(c),-c.Ib}},D:function(){},kb:function(){console.log("fs.h: registering Module['ccall']");f.ccall=ja},lb:function(a){var b=B(a),c=new XMLHttpRequest;c.open("GET",b);c.responseType="arraybuffer";c.onload=function(){var a=new Uint8Array(c.response);ja("emsc_load_data","int",["string","array","number"],[b,a,a.length])};
c.send()},V:function(){return window.devicePixelRatio||1},_:function(a,b,c){a=a?P(a):f.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),E[b>>3]=a.right-a.left,E[c>>3]=a.bottom-a.top):(E[b>>3]=a.clientWidth,E[c>>3]=a.clientHeight);return 0},Ya:function(a,b,c){A.set(A.subarray(b,b+c),a)},La:function(a,b){function c(d){Lb(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Q:function(a,b,c){a=eb(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ua:function(a,b,
c,d){hb(a,b,c,d,2,"keydown");return 0},Sa:function(a,b,c,d){hb(a,b,c,d,1,"keypress");return 0},Ta:function(a,b,c,d){hb(a,b,c,d,3,"keyup");return 0},ja:function(a,b,c,d){S(a,b,c,d,5,"mousedown");return 0},Xa:function(a,b,c,d){S(a,b,c,d,33,"mouseenter");return 0},Wa:function(a,b,c,d){S(a,b,c,d,34,"mouseleave");return 0},db:function(a,b,c,d){S(a,b,c,d,8,"mousemove");return 0},jb:function(a,b,c,d){S(a,b,c,d,6,"mouseup");return 0},Ia:function(a,b,c,d){lb(a,b,c,d);return 0},Oa:function(a,b,c,d){mb(a,b,
c,d,25,"touchcancel");return 0},Pa:function(a,b,c,d){mb(a,b,c,d,23,"touchend");return 0},Qa:function(a,b,c,d){mb(a,b,c,d,24,"touchmove");return 0},Ra:function(a,b,c,d){mb(a,b,c,d,22,"touchstart");return 0},Na:function(a,b,c,d){nb(a,b,c,d,31,"webglcontextlost");return 0},Ma:function(a,b,c,d){nb(a,b,c,d,32,"webglcontextrestored");return 0},Va:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(ob(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(ob(a,b,c,d,"mousewheel"),0):-1},N:function(a,
b){var c={};b>>=2;c.alpha=!!C[b];c.depth=!!C[b+1];c.stencil=!!C[b+2];c.antialias=!!C[b+3];c.premultipliedAlpha=!!C[b+4];c.preserveDrawingBuffer=!!C[b+5];c.powerPreference=Db[C[b+6]];c.failIfMajorPerformanceCaveat=!!C[b+7];c.Ub=C[b+8];c.ac=C[b+9];c.Mb=C[b+10];c.Rb=C[b+11];c.bc=C[b+12];c.cc=C[b+13];a=eb(a);if(!a||c.Rb)c=0;else{if(b=a=a.getContext("webgl",c)||a.getContext("experimental-webgl",c)){b=Q(8);var d={handle:b,attributes:c,version:c.Ub,Lb:a};a.canvas&&(a.canvas.Wb=d);ub[b]=d;("undefined"===
typeof c.Mb||c.Mb)&&Ab(d)}c=b}return c},za:function(a){a>>=2;for(var b=0;14>b;++b)C[a+b]=0;C[a]=C[a+1]=C[a+3]=C[a+4]=C[a+8]=C[a+10]=1},ta:function(a){vb=ub[a];f.Yb=Z=vb&&vb.Lb;return!a||Z?0:-5},aa:Da,$a:Da,bb:Fa,i:function(a){Z.activeTexture(a)},S:function(a,b){Z.attachShader(T[a],W[b])},d:function(a,b){Z.bindBuffer(a,rb[b])},f:function(a,b){Z.bindFramebuffer(a,sb[b])},Ga:function(a,b){Z.bindRenderbuffer(a,U[b])},c:function(a,b){Z.bindTexture(a,tb[b])},I:function(a,b,c,d){Z.blendColor(a,b,c,d)},J:function(a,
b){Z.blendEquationSeparate(a,b)},K:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},W:function(a,b,c,d){Z.bufferData(a,c?A.subarray(c,c+b):b,d)},u:function(a,b,c,d){Z.bufferSubData(a,b,A.subarray(d,d+c))},n:function(a){return Z.checkFramebufferStatus(a)},va:function(a){Z.clear(a)},ya:function(a,b,c,d){Z.clearColor(a,b,c,d)},xa:function(a){Z.clearDepth(a)},wa:function(a){Z.clearStencil(a)},B:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},ib:function(a){Z.compileShader(W[a])},U:function(a,b,c,d,e,g,
l,n){Z.compressedTexImage2D(a,b,c,d,e,g,n?A.subarray(n,n+l):null)},Da:function(){var a=yb(T),b=Z.createProgram();b.name=a;T[a]=b;return a},fa:function(a){var b=yb(W);W[b]=Z.createShader(a);return b},H:function(a){Z.cullFace(a)},Ja:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=rb[d];e&&(Z.deleteBuffer(e),e.name=0,rb[d]=null,d==Bb&&(Bb=0),d==Cb&&(Cb=0))}},k:function(a,b){for(var c=0;c<a;++c){var d=C[b+4*c>>2],e=sb[d];e&&(Z.deleteFramebuffer(e),e.name=0,sb[d]=null)}},Y:function(a){if(a){var b=
T[a];b?(Z.deleteProgram(b),b.name=0,T[a]=null,wb[a]=null):X(1281)}},v:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=U[d];e&&(Z.deleteRenderbuffer(e),e.name=0,U[d]=null)}},C:function(a){if(a){var b=W[a];b?(Z.deleteShader(b),W[a]=null):X(1281)}},Z:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=tb[d];e&&(Z.deleteTexture(e),e.name=0,tb[d]=null)}},z:function(a){Z.depthFunc(a)},A:function(a){Z.depthMask(!!a)},e:function(a){Z.disable(a)},a:function(a){Z.disableVertexAttribArray(a)},ka:function(a,
b,c){Z.drawArrays(a,b,c)},la:function(a,b,c,d){Z.drawElements(a,b,c,d)},h:function(a){Z.enable(a)},ra:function(a){Z.enableVertexAttribArray(a)},l:function(a,b,c,d){Z.framebufferRenderbuffer(a,b,c,U[d])},b:function(a,b,c,d,e){Z.framebufferTexture2D(a,b,c,tb[d],e)},G:function(a){Z.frontFace(a)},X:function(a,b){Eb(a,b,"createBuffer",rb)},o:function(a,b){Eb(a,b,"createFramebuffer",sb)},Ha:function(a,b){Eb(a,b,"createRenderbuffer",U)},Ea:function(a,b){Eb(a,b,"createTexture",tb)},Aa:function(a,b){return Z.getAttribLocation(T[a],
B(b))},w:function(a,b){Fb(a,b)},Ba:function(a,b,c,d){a=Z.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");0<b&&d?(b=z(a,A,d,b),c&&(C[c>>2]=b)):c&&(C[c>>2]=0)},R:function(a,b,c){if(c)if(a>=pb)X(1281);else{var d=wb[a];if(d)if(35716==b)a=Z.getProgramInfoLog(T[a]),null===a&&(a="(unknown error)"),C[c>>2]=a.length+1;else if(35719==b)C[c>>2]=d.Kb;else if(35722==b){if(-1==d.Gb){a=T[a];var e=Z.getProgramParameter(a,35721);for(b=d.Gb=0;b<e;++b)d.Gb=Math.max(d.Gb,Z.getActiveAttrib(a,b).name.length+1)}C[c>>
2]=d.Gb}else if(35381==b){if(-1==d.Hb)for(a=T[a],e=Z.getProgramParameter(a,35382),b=d.Hb=0;b<e;++b)d.Hb=Math.max(d.Hb,Z.getActiveUniformBlockName(a,b).length+1);C[c>>2]=d.Hb}else C[c>>2]=Z.getProgramParameter(T[a],b);else X(1282)}else X(1281)},hb:function(a,b,c,d){a=Z.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");0<b&&d?(b=z(a,A,d,b),c&&(C[c>>2]=b)):c&&(C[c>>2]=0)},da:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),C[c>>2]=a.length+1):35720==b?(a=Z.getShaderSource(W[a]),
C[c>>2]=null===a||0==a.length?0:a.length+1):C[c>>2]=Z.getShaderParameter(W[a],b):X(1281)},Ka:function(a){if(xb[a])return xb[a];switch(a){case 7939:var b=Z.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=Gb(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||X(1280);b=Gb(b);break;case 7938:b=Gb("OpenGL ES 2.0 ("+Z.getParameter(Z.VERSION)+")");break;case 35724:b=Z.getParameter(Z.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Gb(b);break;default:return X(1280),0}return xb[a]=b},m:function(a,b){b=B(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=wb[a]&&wb[a].Ob[b])&&0<=c&&c<a[0]?a[1]+c:-1},Ca:function(a){Z.linkProgram(T[a]);var b=T[a];a=wb[a]={Ob:{},Kb:0,Gb:-1,Hb:-1};for(var c=a.Ob,d=Z.getProgramParameter(b,35718),e=0;e<d;++e){var g=Z.getActiveUniform(b,e),l=g.name;a.Kb=
Math.max(a.Kb,l.length+1);"]"==l.slice(-1)&&(l=l.slice(0,l.lastIndexOf("[")));var n=Z.getUniformLocation(b,l);if(n){var t=yb(V);c[l]=[g.size,t];V[t]=n;for(var q=1;q<g.size;++q)n=Z.getUniformLocation(b,l+"["+q+"]"),t=yb(V),V[t]=n}}},F:function(a,b){Z.polygonOffset(a,b)},Fa:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},O:function(a,b,c,d){Z.scissor(a,b,c,d)},ea:function(a,b,c,d){for(var e="",g=0;g<b;++g){var l=d?C[d+4*g>>2]:-1;e+=B(C[c+4*g>>2],0>l?void 0:l)}Z.shaderSource(W[a],e)},ia:function(a,
b,c){Z.stencilFunc(a,b,c)},M:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},y:function(a){Z.stencilMask(a)},ha:function(a,b,c){Z.stencilOp(a,b,c)},L:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},T:function(a,b,c,d,e,g,l,n,t){Z.texImage2D(a,b,c,d,e,g,l,n,t?Jb(n,l,d,e,t):null)},j:function(a,b,c){Z.texParameteri(a,b,c)},t:function(a,b,c,d,e,g,l,n,t){var q=null;t&&(q=Jb(n,l,e,g,t));Z.texSubImage2D(a,b,c,d,e,g,l,n,q)},qa:function(a,b,c){if(256>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=D[c+4*e>>2];else d=
D.subarray(c>>2,c+4*b>>2);Z.uniform1fv(V[a],d)},E:function(a,b){Z.uniform1i(V[a],b)},pa:function(a,b,c){if(256>=2*b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2];else d=D.subarray(c>>2,c+8*b>>2);Z.uniform2fv(V[a],d)},oa:function(a,b,c){if(256>=3*b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2],d[e+2]=D[c+(4*e+8)>>2];else d=D.subarray(c>>2,c+12*b>>2);Z.uniform3fv(V[a],d)},na:function(a,b,c){if(256>=4*b)for(var d=Y[4*b-1],e=0;e<4*b;e+=4)d[e]=D[c+
4*e>>2],d[e+1]=D[c+(4*e+4)>>2],d[e+2]=D[c+(4*e+8)>>2],d[e+3]=D[c+(4*e+12)>>2];else d=D.subarray(c>>2,c+16*b>>2);Z.uniform4fv(V[a],d)},ma:function(a,b,c,d){if(256>=16*b)for(var e=Y[16*b-1],g=0;g<16*b;g+=16)e[g]=D[d+4*g>>2],e[g+1]=D[d+(4*g+4)>>2],e[g+2]=D[d+(4*g+8)>>2],e[g+3]=D[d+(4*g+12)>>2],e[g+4]=D[d+(4*g+16)>>2],e[g+5]=D[d+(4*g+20)>>2],e[g+6]=D[d+(4*g+24)>>2],e[g+7]=D[d+(4*g+28)>>2],e[g+8]=D[d+(4*g+32)>>2],e[g+9]=D[d+(4*g+36)>>2],e[g+10]=D[d+(4*g+40)>>2],e[g+11]=D[d+(4*g+44)>>2],e[g+12]=D[d+(4*
g+48)>>2],e[g+13]=D[d+(4*g+52)>>2],e[g+14]=D[d+(4*g+56)>>2],e[g+15]=D[d+(4*g+60)>>2];else e=D.subarray(d>>2,d+64*b>>2);Z.uniformMatrix4fv(V[a],!!c,e)},ua:function(a){Z.useProgram(T[a])},Za:function(a,b){Z.vertexAttribDivisor(a,b)},sa:function(a,b,c,d,e,g){Z.vertexAttribPointer(a,b,c,!!d,e,g)},P:function(a,b,c,d){Z.viewport(a,b,c,d)},r:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Mb()});
document.body.append(a)},q:function(){document.getElementById("_sokol_app_input_element").focus()},p:function(){document.getElementById("_sokol_app_input_element").blur()},ga:function(){for(var a=(new URLSearchParams(window.location.search)).entries(),b=a.next();!b.done;b=a.next())ja("_sargs_add_kvp","void",["string","string"],[b.value[0],b.value[1]])},g:function(a){a|=0;var b=la.length|0;var c=C[1688332]|0;var d=c+a|0;if(0<(a|0)&(d|0)<(c|0)|0>(d|0))return x("OOM"),0,Pa(),-1;if(a=(d|0)>(b|0))x("OOM"),
a=!0;if(a)return Pa(),-1;C[1688332]=d|0;return c|0},_a:Ea,ab:Ea,s:function(){return performance.now()}},buffer);f.asm=Nb;var Ma=f.___wasm_call_ctors=function(){return f.asm.mb.apply(null,arguments)};f._emsc_load_data=function(){return f.asm.nb.apply(null,arguments)};var Mb=f.__sapp_emsc_notify_keyboard_hidden=function(){return f.asm.ob.apply(null,arguments)};f._main=function(){return f.asm.pb.apply(null,arguments)};var Q=f._malloc=function(){return f.asm.qb.apply(null,arguments)};
f._free=function(){return f.asm.rb.apply(null,arguments)};f.__saudio_emsc_pull=function(){return f.asm.sb.apply(null,arguments)};f.__sargs_add_kvp=function(){return f.asm.tb.apply(null,arguments)};var ma=f.stackSave=function(){return f.asm.ub.apply(null,arguments)},ka=f.stackAlloc=function(){return f.asm.vb.apply(null,arguments)},na=f.stackRestore=function(){return f.asm.wb.apply(null,arguments)};f.dynCall_vi=function(){return f.asm.xb.apply(null,arguments)};
f.dynCall_v=function(){return f.asm.yb.apply(null,arguments)};var R=f.dynCall_iiii=function(){return f.asm.zb.apply(null,arguments)},Lb=f.dynCall_idi=function(){return f.asm.Ab.apply(null,arguments)};f.asm=Nb;function v(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}v.prototype=Error();v.prototype.constructor=v;I=function Ob(){f.calledRun||Pb();f.calledRun||(I=Ob)};
f.callMain=function(a){a=a||[];Ba||(Ba=!0,G(wa));var b=a.length+1,c=ka(4*(b+1));C[c>>2]=ra(f.thisProgram);for(var d=1;d<b;d++)C[(c>>2)+d]=ra(a[d-1]);C[(c>>2)+b]=0;try{var e=f._main(b,c,0);if(!f.noExitRuntime||0!==e){if(!f.noExitRuntime&&(ha=!0,f.onExit))f.onExit(e);f.quit(e,new v(e))}}catch(g){g instanceof v||("SimulateInfiniteLoop"==g?f.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),y("exception thrown: "+a),f.quit(1,g)))}finally{}};
function Pb(a){function b(){if(!f.calledRun&&(f.calledRun=!0,!ha)){Ba||(Ba=!0,G(wa));G(xa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();f._main&&Qb&&f.callMain(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Aa.unshift(b)}G(Aa)}}a=a||f.arguments;if(!(0<H)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ca();G(va);0<H||f.calledRun||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},
1);b()},1)):b())}}f.run=Pb;function x(a){if(f.onAbort)f.onAbort(a);void 0!==a?(ea(a),y(a),a=JSON.stringify(a)):a="";ha=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}f.abort=x;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Qb=!0;f.noInitialRun&&(Qb=!1);f.noExitRuntime=!0;Pb();
