var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da={...h},ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs");require("path");k=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!h.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?
"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var la=h.print||console.log.bind(console),n=h.printErr||console.error.bind(console);Object.assign(h,da);da=null;h.arguments&&(ea=h.arguments);h.thisProgram&&(fa=h.thisProgram);var ma=h.wasmBinary,na,q=!1,oa,r,t,pa,qa,u,w,x,y,ka=a=>a.startsWith("file://");
function ra(){var a=na.buffer;h.HEAP8=r=new Int8Array(a);h.HEAP16=pa=new Int16Array(a);h.HEAPU8=t=new Uint8Array(a);h.HEAPU16=qa=new Uint16Array(a);h.HEAP32=u=new Int32Array(a);h.HEAPU32=w=new Uint32Array(a);h.HEAPF32=x=new Float32Array(a);h.HEAPF64=y=new Float64Array(a);h.HEAP64=new BigInt64Array(a);h.HEAPU64=new BigUint64Array(a)}var z=0,A=null;function sa(a){h.onAbort?.(a);a="Aborted("+a+")";n(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==ta&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!ma&&"function"==typeof WebAssembly.instantiateStreaming&&!ka(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(h)},za=[],Aa=[],Ba=()=>{var a=h.preRun.shift();Aa.unshift(a)},Ca=h.noExitRuntime||!0,Da="undefined"!=typeof TextDecoder?new TextDecoder:void 0,B=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Da)return Da.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):
(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ea=0,C={},Fa=a=>{a instanceof xa||"unwind"==a||ha(1,a)},Ga=a=>{oa=a;Ca||0<Ea||(h.onExit?.(a),q=!0);ha(a,new xa(a))},Ha=a=>{oa=a;Ga(a)},Ia=()=>{if(!(Ca||0<Ea))try{var a=oa;oa=a;Ga(a)}catch(b){Fa(b)}},Ja=a=>{if(!q)try{a(),Ia()}catch(b){Fa(b)}},Qa=(a,b)=>{Ka=a;La=b;if(D)if(Ma||=!0,0==a)E=function(){setTimeout(H,Math.max(0,Na+b-performance.now())|0)};else if(1==a)E=function(){Oa(H)};else if(2==a){if("undefined"==
typeof Pa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Pa=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Pa=setImmediate;E=function(){Pa(H)}}},Za=(a,b,c,d,e)=>{function g(){return f<Ra?(Ia(),!1):!0}D=a;Sa=d;var f=Ra;Ma=!1;H=function(){if(!q)if(0<Ta.length){var l=
Ta.shift();l.Pd(l.Ed);if(Ua){var m=Ua,p=0==m%1?m-1:Math.floor(m);Ua=l.Gd?p:(8*m+(p+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",m=Ua??0,p=Va.Ld??0,m?m<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));g()&&setTimeout(H,0)}else if(g())if(Wa=Wa+1|0,1==Ka&&1<La&&0!=Wa%La)E();else{0==Ka&&(Na=performance.now());a:if(!q){for(l of Xa)if(!1===l())break a;Ja(a);for(m of Ya)m()}g()&&E()}};e||(0<b?Qa(0,1E3/b):Qa(1,1),E());if(c)throw"unwind";},Ma=!1,E=
null,Ra=0,D=null,Sa=0,Ka=0,La=0,Wa=0,Ta=[],Xa=[],Ya=[];function $a(){E=null;Ra++}var ab=0;function Oa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ab)ab=b+1E3/60;else for(;b+2>=ab;)ab+=1E3/60;setTimeout(a,Math.max(ab-b,0))}}
var Va={},Na,H,Pa,Ua,bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],I=a=>{a=2<a?a?B(t,a):"":a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):null)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=[],eb,J=a=>{var b=db[a];b||(db[a]=b=eb.get(a));return b};function fb(a){var b=K.Fc[a];b.target.removeEventListener(b.Ec,b.kd,b.Gc);K.Fc.splice(a,1)}
function gb(){if(navigator.userActivation?navigator.userActivation.isActive:K.Uc&&K.zd.Sc){var a=K.Lc;K.Lc=[];for(var b of a)b.Xc(...b.ed)}}function L(a){if(!a.target)return-4;if(a.Hc)a.kd=function(c){++K.Uc;K.zd=a;gb();a.Ic(c);gb();--K.Uc},a.target.addEventListener(a.Ec,a.kd,a.Gc),K.Fc.push(a);else for(var b=0;b<K.Fc.length;++b)K.Fc[b].target==a.target&&K.Fc[b].Ec==a.Ec&&fb(b--);return 0}function hb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var K={Fd:0,Qd:0,Vc:0,Rc:0,ad:0,Zc:0,Tc:0,Jd:0,Vd:0,Id:0,Od:0,Wc:0,ce:0,Yc:0,Sd(a,b,c){r.set(r.subarray(b,b+c),a)},Xd(){for(;K.Fc.length;)fb(K.Fc.length-1);K.Lc=[]},Uc:0,Lc:[],Hd(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of K.Lc)if(e.Xc==a&&d(e.ed,c))return;K.Lc.push({Xc:a,od:b,ed:c});K.Lc.sort((g,f)=>g.od<f.od)},Zd(a){K.Lc=K.Lc.filter(b=>b.Xc!=a)},Fc:[],Yd:(a,b)=>{for(var c=0;c<K.Fc.length;++c)K.Fc[c].target!=a||b&&b!=K.Fc[c].Ec||
fb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},M=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var l=a.charCodeAt(++g);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|
f&63}}d[b]=0;return b-e},ib=(a,b,c,d,e,g)=>{K.Tc||(K.Tc=N(256));a={target:I(a),Ec:g,Hc:d,Ic:(f=event)=>{var l=f.target.id?f.target.id:"",m=K.Tc;M(hb(f.target),m+0,128);M(l,m+128,128);J(d)(e,m,b)&&f.preventDefault()},Gc:c};return L(a)},jb=(a,b,c,d,e,g)=>{K.Vc||(K.Vc=N(160));a={target:I(a),Ec:g,Hc:d,Ic:f=>{var l=K.Vc;y[l>>3]=f.timeStamp;var m=l>>2;u[m+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;u[m+5]=f.charCode;u[m+6]=f.keyCode;u[m+7]=f.which;
M(f.key||"",l+32,32);M(f.code||"",l+64,32);M(f.char||"",l+96,32);M(f.locale||"",l+128,32);J(d)(e,l,b)&&f.preventDefault()},Gc:c};return L(a)},kb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=cb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},lb=(a,b,c,d,e,g)=>{K.Rc||(K.Rc=
N(64));a=I(a);return L({target:a,Sc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,Ec:g,Hc:d,Ic:(f=event)=>{kb(K.Rc,f,a);J(d)(e,K.Rc,b)&&f.preventDefault()},Gc:c})},mb=(a,b,c,d,e)=>{K.Wc||(K.Wc=N(257));return L({target:a,Ec:e,Hc:d,Ic:(g=event)=>{var f=K.Wc,l=document.pointerLockElement||document.Mc||document.dd||document.bd;r[f]=!!l;var m=l?.id||"";M(hb(l),f+1,128);M(m,f+129,128);J(d)(20,f,b)&&g.preventDefault()},Gc:c})},nb=(a,b,c,d,e)=>L({target:a,Ec:e,Hc:d,Ic:(g=event)=>{J(d)(38,0,b)&&g.preventDefault()},
Gc:c}),ob=(a,b,c,d)=>{K.Zc||(K.Zc=N(36));a=I(a);return L({target:a,Ec:"resize",Hc:d,Ic:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=K.Zc;u[f>>2]=0;u[f+4>>2]=g.clientWidth;u[f+8>>2]=g.clientHeight;u[f+12>>2]=innerWidth;u[f+16>>2]=innerHeight;u[f+20>>2]=outerWidth;u[f+24>>2]=outerHeight;u[f+28>>2]=pageXOffset|0;u[f+32>>2]=pageYOffset|0;J(d)(10,f,b)&&e.preventDefault()}}},Gc:c})},pb=(a,b,c,d,e,g)=>{K.Yc||(K.Yc=N(1552));a=I(a);return L({target:a,Sc:"touchstart"==g||"touchend"==g,Ec:g,Hc:d,
Ic:f=>{var l={},m=f.touches;for(var p of m)p.ld=p.nd=0,l[p.identifier]=p;for(var v of f.changedTouches)v.ld=1,l[v.identifier]=v;for(var F of f.targetTouches)l[F.identifier].nd=1;m=K.Yc;y[m>>3]=f.timeStamp;r[m+12]=f.ctrlKey;r[m+13]=f.shiftKey;r[m+14]=f.altKey;r[m+15]=f.metaKey;p=m+16;v=cb(a);F=0;for(let G of Object.values(l))if(l=p>>2,u[l]=G.identifier,u[l+1]=G.screenX,u[l+2]=G.screenY,u[l+3]=G.clientX,u[l+4]=G.clientY,u[l+5]=G.pageX,u[l+6]=G.pageY,r[p+28]=G.ld,r[p+29]=G.nd,u[l+8]=G.clientX-(v.left|
0),u[l+9]=G.clientY-(v.top|0),p+=48,31<++F)break;u[m+8>>2]=F;J(d)(e,m,b)&&f.preventDefault()},Gc:c})},O,qb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},rb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>
b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},sb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},tb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},ub=1,vb=[],P=[],wb=[],xb=[],Q=[],R=[],yb=[],zb=[],S=[],Ab={},Bb=4,Cb=0,Db=a=>{for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=O[c](),f=g&&Db(d);g?(g.name=f,d[f]=g):T||=1282;u[b+4*e>>2]=f}},Fb=(a,b)=>{a.Mc||(a.Mc=a.getContext,a.getContext=function(d,e){e=a.Mc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.md?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Eb(c,b):0},Eb=(a,b)=>{var c=Db(zb),d={handle:c,attributes:b,version:b.md,cd:a};a.canvas&&(a.canvas.Dd=d);zb[c]=d;("undefined"==typeof b.jd||b.jd)&&Gb(d);return c},Gb=a=>{a||=V;if(!a.Cd){a.Cd=!0;var b=a.cd;b.Ud=b.getExtension("WEBGL_multi_draw");b.Nd=b.getExtension("EXT_polygon_offset_clamp");b.Md=b.getExtension("EXT_clip_control");b.de=b.getExtension("WEBGL_polygon_mode");qb(b);rb(b);sb(b);b.Kd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Rd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.hd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.hd)b.hd=b.getExtension("EXT_disjoint_timer_query");tb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Hb=(a,b,c,d,e,g)=>{a={target:I(a),Ec:g,Hc:d,Ic:(f=event)=>{J(d)(e,0,b)&&f.preventDefault()},Gc:c};L(a)},Ib=(a,b,c,d)=>{K.ad||(K.ad=N(96));return L({target:a,Sc:!0,Ec:"wheel",Hc:d,Ic:(e=event)=>{var g=K.ad;kb(g,e,a);y[g+64>>3]=e.deltaX;y[g+72>>3]=e.deltaY;y[g+80>>3]=e.deltaZ;
u[g+88>>2]=e.deltaMode;J(d)(9,g,b)&&e.preventDefault()},Gc:c})},Jb=["default","low-power","high-performance"],Kb={},Mb=()=>{if(!Lb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in Kb)void 0===Kb[b]?delete a[b]:a[b]=Kb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Lb=c}return Lb},Lb,Nb=[null,[],[]],Ob=[],Pb=()=>{var a=tb(O);
return a=a.concat(a.map(b=>"GL_"+b))},Qb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=O.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Pb().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=O.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else T||=1281},Rb=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Sb=a=>{var b=Rb(a)+1,c=N(b);c&&M(a,c,b);return c},Tb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ub=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?u:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?w:qa},Vb=(a,b,c,d,e)=>{a=Ub(a);b=d*((Cb||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Bb-1&-Bb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=O.Ad;if(b){var c=b.Nc[a];"number"==typeof c&&(b.Nc[a]=c=O.getUniformLocation(b,b.wd[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],Wb=[],Yb=a=>{var b=Rb(a)+1,c=Xb(b);M(a,c,b);return c},ac=a=>{var b=Zb();a();$b(b)};h.requestAnimationFrame=Oa;h.pauseMainLoop=$a;h.resumeMainLoop=function(){Ra++;var a=Ka,b=La,c=D;D=null;Za(c,0,!1,Sa,!0);Qa(a,b);E()};h.preMainLoop&&Xa.push(h.preMainLoop);h.postMainLoop&&Ya.push(h.postMainLoop);for(let a=0;32>a;++a)Ob.push(Array(a));
for(var bc=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=bc.subarray(0,Y);var cc=new Int32Array(288);for(Y=0;288>=Y;++Y)Wb[Y]=cc.subarray(0,Y);
var sc={la:function(){return 0},pb:function(){return 0},qb:function(){},tb:()=>sa(""),ib:()=>{Ca=!1;Ea=0},jb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ja(()=>dc(a,performance.now()))},b);C[a]={id:c,be:b};return 0},eb:function(a){if(void 0===window.localStorage)return 0;a=a?B(t,a):"";return(a=window.localStorage.getItem(a))?Sb(a):0},fc:function(a,b){void 0!==window.localStorage&&(a=a?B(t,a):"",b=b?B(t,b):"",window.localStorage.setItem(a,b))},
Wa:()=>{$a();D=null},fa:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ha:(a,b,c)=>{a=I(a);if(!a)return-4;a=cb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},y:()=>performance.now(),Xa:()=>performance.now(),$a:(a,b)=>{function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},kb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+
65535)/65536|0;try{na.grow(d);ra();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},P:(a,b,c,d)=>ib(a,b,c,d,12,"blur"),ea:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},Q:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),Z:(a,b,c,d)=>jb(a,b,c,d,2,"keydown"),X:(a,b,c,d)=>jb(a,b,c,d,1,"keypress"),Y:(a,b,c,d)=>jb(a,b,c,d,3,"keyup"),bb:(a,b,c)=>{a=J(a);Za(a,b,c)},da:(a,b,c,d)=>lb(a,b,c,d,5,"mousedown"),aa:(a,b,c,d)=>lb(a,b,c,d,33,"mouseenter"),$:(a,b,c,d)=>lb(a,b,c,d,34,"mouseleave"),ba:(a,
b,c,d)=>lb(a,b,c,d,8,"mousemove"),ca:(a,b,c,d)=>lb(a,b,c,d,6,"mouseup"),S:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Mc||document.body.dd||document.body.bd))return-1;a=I(a);if(!a)return-4;mb(a,b,c,d,"mozpointerlockchange");mb(a,b,c,d,"webkitpointerlockchange");mb(a,b,c,d,"mspointerlockchange");return mb(a,b,c,d,"pointerlockchange")},R:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.Mc||document.body.dd||document.body.bd))return-1;
a=I(a);if(!a)return-4;nb(a,b,c,d,"mozpointerlockerror");nb(a,b,c,d,"webkitpointerlockerror");nb(a,b,c,d,"mspointerlockerror");return nb(a,b,c,d,"pointerlockerror")},ga:(a,b,c,d)=>ob(a,b,c,d),T:(a,b,c,d)=>pb(a,b,c,d,25,"touchcancel"),U:(a,b,c,d)=>pb(a,b,c,d,23,"touchend"),V:(a,b,c,d)=>pb(a,b,c,d,24,"touchmove"),W:(a,b,c,d)=>pb(a,b,c,d,22,"touchstart"),O:(a,b,c,d)=>{Hb(a,b,c,d,31,"webglcontextlost");return 0},N:(a,b,c,d)=>{Hb(a,b,c,d,32,"webglcontextrestored");return 0},_:(a,b,c,d)=>(a=I(a))?"undefined"!=
typeof a.onwheel?Ib(a,b,c,d):-1:-4,_a:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Jb[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],md:u[c+4],Td:u[c+5],jd:r[b+24],Bd:r[b+25],Wd:u[c+7],$d:r[b+32]};a=I(a);return!a||b.Bd?0:Fb(a,b)},Za:a=>{V=zb[a];h.ctx=O=V?.cd;return!a||O?0:-5},rb:(a,b)=>{var c=0;Mb().forEach((d,e)=>{var g=b+c;e=w[a+4*e>>2]=g;for(g=0;g<d.length;++g)r[e++]=d.charCodeAt(g);
r[e]=0;c+=d.length+1});return 0},sb:(a,b)=>{var c=Mb();w[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);w[b>>2]=d;return 0},ka:()=>52,nb:()=>52,lb:function(){return 70},mb:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=w[b>>2],l=w[b+4>>2];b+=8;for(var m=0;m<l;m++){var p=a,v=t[f+m],F=Nb[p];0===v||10===v?((1===p?la:n)(B(F)),F.length=0):F.push(v)}e+=l}w[d>>2]=e;return 0},l:function(a,b,c){const d=a?B(t,a):"";let e;try{e=window.indexedDB.open("chips",1)}catch(g){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+
g)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");e.result.createObjectStore("store")};e.onsuccess=()=>{var g=e.result;let f;try{f=g.transaction(["store"],"readwrite")}catch(p){console.log("fs_js_load_snapshot: db.transaction failed with",p);return}g=f.objectStore("store");const l=d+"_"+b,m=g.get(l);m.onsuccess=()=>{if(void 0!==m.result){const p=m.result.length;console.log("fs_js_load_snapshot:",l,"successfully loaded",p,"bytes");const v=ec(p);t.set(m.result,v);fc(c,v,p)}else fc(c,
0,0)};m.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",l)};f.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},ab:function(a,b,c,d){const e=a?B(t,a):"";console.log("fs_js_save_snapshot: called with",e,b);let g;try{g=window.indexedDB.open("chips",1)}catch(f){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+f);return}g.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");
g.result.createObjectStore("store")};g.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");const f=g.result.transaction(["store"],"readwrite");var l=f.objectStore("store");const m=e+"_"+b;l=l.put(t.subarray(c,c+d),m);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",m,"successfully stored")};l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",m)};f.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};g.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},
q:a=>O.activeTexture(a),B:(a,b)=>{O.attachShader(P[a],R[b])},b:(a,b)=>{35051==a?O.gd=b:35052==a&&(O.Kc=b);O.bindBuffer(a,vb[b])},a:(a,b,c)=>{O.bindBufferBase(a,b,vb[c])},n:(a,b)=>{O.bindFramebuffer(a,wb[b])},Ha:(a,b)=>{O.bindRenderbuffer(a,xb[b])},p:(a,b)=>{O.bindSampler(a,S[b])},d:(a,b)=>{O.bindTexture(a,Q[b])},M:a=>{O.bindVertexArray(yb[a])},I:(a,b,c,d)=>O.blendColor(a,b,c,d),J:(a,b)=>O.blendEquationSeparate(a,b),K:(a,b,c,d)=>O.blendFuncSeparate(a,b,c,d),xb:(a,b,c,d,e,g,f,l,m,p)=>O.blitFramebuffer(a,
b,c,d,e,g,f,l,m,p),Ka:(a,b,c,d)=>{2<=V.version?c&&b?O.bufferData(a,t,d,c,b):O.bufferData(a,b,d):O.bufferData(a,c?t.subarray(c,c+b):b,d)},C:(a,b,c,d)=>{2<=V.version?c&&O.bufferSubData(a,b,t,d,c):O.bufferSubData(a,b,t.subarray(d,d+c))},qa:a=>O.checkFramebufferStatus(a),Tb:(a,b,c,d)=>O.clearBufferfi(a,b,c,d),oa:(a,b,c)=>{O.clearBufferfv(a,b,x,c>>2)},Sb:(a,b,c)=>{O.clearBufferiv(a,b,u,c>>2)},r:(a,b,c,d)=>{O.colorMask(!!a,!!b,!!c,!!d)},Xb:a=>{O.compileShader(R[a])},Ba:(a,b,c,d,e,g,f,l)=>{2<=V.version?
O.Kc||!f?O.compressedTexImage2D(a,b,c,d,e,g,f,l):O.compressedTexImage2D(a,b,c,d,e,g,t,l,f):O.compressedTexImage2D(a,b,c,d,e,g,t.subarray(l,l+f))},za:(a,b,c,d,e,g,f,l,m)=>{O.Kc?O.compressedTexImage3D(a,b,c,d,e,g,f,l,m):O.compressedTexImage3D(a,b,c,d,e,g,f,t,m,l)},bc:()=>{var a=Db(P),b=O.createProgram();b.name=a;b.Qc=b.Oc=b.Pc=0;b.$c=1;P[a]=b;return a},Zb:a=>{var b=Db(R);R[b]=O.createShader(a);return b},F:a=>O.cullFace(a),Oa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=vb[d];e&&(O.deleteBuffer(e),
e.name=0,vb[d]=null,d==O.gd&&(O.gd=0),d==O.Kc&&(O.Kc=0))}},f:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=wb[d];e&&(O.deleteFramebuffer(e),e.name=0,wb[d]=null)}},j:a=>{if(a){var b=P[a];b?(O.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},D:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=xb[d];e&&(O.deleteRenderbuffer(e),e.name=0,xb[d]=null)}},g:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=S[d];e&&(O.deleteSampler(e),e.name=0,S[d]=null)}},t:a=>{if(a){var b=R[a];b?(O.deleteShader(b),R[a]=null):
T||=1281}},E:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(O.deleteTexture(e),e.name=0,Q[d]=null)}},Ma:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];O.deleteVertexArray(yb[d]);yb[d]=null}},w:a=>O.depthFunc(a),v:a=>{O.depthMask(!!a)},e:a=>O.disable(a),L:a=>{O.disableVertexAttribArray(a)},zb:(a,b,c)=>{O.drawArrays(a,b,c)},Ab:(a,b,c,d)=>{O.drawArraysInstanced(a,b,c,d)},pa:(a,b)=>{for(var c=Ob[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];O.drawBuffers(c)},Bb:(a,b,c,d)=>{O.drawElements(a,b,c,d)},Cb:(a,
b,c,d,e)=>{O.drawElementsInstanced(a,b,c,d,e)},k:a=>O.enable(a),Nb:a=>{O.enableVertexAttribArray(a)},ra:(a,b,c,d)=>{O.framebufferRenderbuffer(a,b,c,xb[d])},o:(a,b,c,d,e)=>{O.framebufferTexture2D(a,b,c,Q[d],e)},A:(a,b,c,d,e)=>{O.framebufferTextureLayer(a,b,Q[c],d,e)},G:a=>O.frontFace(a),La:(a,b)=>{U(a,b,"createBuffer",vb)},sa:(a,b)=>{U(a,b,"createFramebuffer",wb)},Ia:(a,b)=>{U(a,b,"createRenderbuffer",xb)},cc:(a,b)=>{U(a,b,"createSampler",S)},Fa:(a,b)=>{U(a,b,"createTexture",Q)},Va:(a,b)=>{U(a,b,"createVertexArray",
yb)},Vb:(a,b)=>O.getAttribLocation(P[a],b?B(t,b):""),c:(a,b)=>Qb(a,b),ac:(a,b,c,d)=>{a=O.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},va:(a,b,c)=>{if(c)if(a>=ub)T||=1281;else if(a=P[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.Qc){var d=O.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Qc=Math.max(a.Qc,O.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.Qc}else if(35722==b){if(!a.Oc)for(d=
O.getProgramParameter(a,35721),b=0;b<d;++b)a.Oc=Math.max(a.Oc,O.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Oc}else if(35381==b){if(!a.Pc)for(d=O.getProgramParameter(a,35382),b=0;b<d;++b)a.Pc=Math.max(a.Pc,O.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Pc}else u[c>>2]=O.getProgramParameter(a,b);else T||=1281},Wb:(a,b,c,d)=>{a=O.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},ta:(a,b,c)=>{c?35716==b?(a=O.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),
u[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(R[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=O.getShaderParameter(R[a],b):T||=1281},Ta:(a,b)=>{if(2>V.version)return T||=1282,0;var c=Ab[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Pb().map(Sb),c=Ab[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},ua:(a,b)=>{b=b?B(t,b):"";if(a=P[a]){var c=a,d=c.Nc,e=c.xd,g;if(!d){c.Nc=d={};c.wd={};var f=O.getProgramParameter(c,35718);for(g=0;g<f;++g){var l=O.getActiveUniform(c,
g);var m=l.name;l=l.size;var p=Tb(m);p=0<p?m.slice(0,p):m;var v=c.$c;c.$c+=l;e[p]=[l,v];for(m=0;m<l;++m)d[v]=m,c.wd[v++]=p}}c=a.Nc;d=0;e=b;g=Tb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.xd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else T||=1281;return-1},wb:(a,b,c)=>{for(var d=Ob[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];O.invalidateFramebuffer(a,d)},wa:a=>{a=P[a];O.linkProgram(a);a.Nc=0;a.xd={}},Ua:(a,b)=>{3317==a?Bb=b:3314==a&&(Cb=b);O.pixelStorei(a,b)},H:(a,
b)=>O.polygonOffset(a,b),yb:a=>O.readBuffer(a),Ga:(a,b,c,d,e)=>O.renderbufferStorageMultisample(a,b,c,d,e),xa:(a,b,c)=>{O.samplerParameterf(S[a],b,c)},h:(a,b,c)=>{O.samplerParameteri(S[a],b,c)},s:(a,b,c,d)=>O.scissor(a,b,c,d),Yb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=w[c+4*g>>2])?B(t,f,d?w[d+4*g>>2]:void 0):"";e+=f}O.shaderSource(R[a],e)},Ra:(a,b,c)=>O.stencilFunc(a,b,c),na:(a,b,c,d)=>O.stencilFuncSeparate(a,b,c,d),u:a=>O.stencilMask(a),Qa:(a,b,c)=>O.stencilOp(a,b,c),ma:(a,b,c,d)=>O.stencilOpSeparate(a,
b,c,d),Aa:(a,b,c,d,e,g,f,l,m)=>{if(2<=V.version){if(O.Kc){O.texImage2D(a,b,c,d,e,g,f,l,m);return}if(m){var p=Ub(l);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);O.texImage2D(a,b,c,d,e,g,f,l,p,m);return}}p=m?Vb(l,f,d,e,m):null;O.texImage2D(a,b,c,d,e,g,f,l,p)},dc:(a,b,c,d,e,g,f,l,m,p)=>{if(O.Kc)O.texImage3D(a,b,c,d,e,g,f,l,m,p);else if(p){var v=Ub(m);O.texImage3D(a,b,c,d,e,g,f,l,m,v,p>>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else O.texImage3D(a,b,c,d,e,g,f,l,m,null)},Ea:(a,b,c)=>O.texParameteri(a,b,c),Da:(a,
b,c,d,e)=>O.texStorage2D(a,b,c,d,e),Ca:(a,b,c,d,e,g)=>O.texStorage3D(a,b,c,d,e,g),vb:(a,b,c,d,e,g,f,l,m)=>{if(2<=V.version){if(O.Kc){O.texSubImage2D(a,b,c,d,e,g,f,l,m);return}if(m){var p=Ub(l);O.texSubImage2D(a,b,c,d,e,g,f,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}m=m?Vb(l,f,e,g,m):null;O.texSubImage2D(a,b,c,d,e,g,f,l,m)},ub:(a,b,c,d,e,g,f,l,m,p,v)=>{if(O.Kc)O.texSubImage3D(a,b,c,d,e,g,f,l,m,p,v);else if(v){var F=Ub(p);O.texSubImage3D(a,b,c,d,e,g,f,l,m,p,F,v>>>31-Math.clz32(F.BYTES_PER_ELEMENT))}else O.texSubImage3D(a,
b,c,d,e,g,f,l,m,p,null)},Mb:(a,b,c)=>{if(2<=V.version)b&&O.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);O.uniform1fv(W(a),d)}},_b:(a,b)=>{O.uniform1i(W(a),b)},Hb:(a,b,c)=>{if(2<=V.version)b&&O.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=Wb[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);O.uniform1iv(W(a),d)}},Lb:(a,b,c)=>{if(2<=V.version)b&&O.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=
X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);O.uniform2fv(W(a),d)}},Gb:(a,b,c)=>{if(2<=V.version)b&&O.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Wb[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);O.uniform2iv(W(a),d)}},Kb:(a,b,c)=>{if(2<=V.version)b&&O.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=
x.subarray(c>>2,c+12*b>>2);O.uniform3fv(W(a),d)}},Fb:(a,b,c)=>{if(2<=V.version)b&&O.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Wb[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);O.uniform3iv(W(a),d)}},Jb:(a,b,c)=>{if(2<=V.version)b&&O.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>
2);O.uniform4fv(W(a),d)}},Eb:(a,b,c)=>{if(2<=V.version)b&&O.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Wb[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);O.uniform4iv(W(a),d)}},Db:(a,b,c,d)=>{if(2<=V.version)b&&O.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],g=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+
5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(W(a),!!c,e)}},i:a=>{a=P[a];O.useProgram(a);O.Ad=a},Ob:(a,b)=>{O.vertexAttribDivisor(a,b)},Pb:(a,b,c,d,e)=>{O.vertexAttribIPointer(a,b,c,d,e)},Qb:(a,b,c,d,e,g)=>{O.vertexAttribPointer(a,b,c,!!d,e,g)},m:(a,b,c,d)=>O.viewport(a,b,c,d),hb:Ga,Ya:function(){h.pd=a=>{0!=gc()&&(a.preventDefault(),
a.returnValue=" ")};window.addEventListener("beforeunload",h.pd)},Pa:function(){h.vd=a=>{const b=a.clipboardData.getData("text");ac(()=>{const c=Yb(b);hc(c)})};window.addEventListener("paste",h.vd)},ec:function(){h.ae=[];h.qd=b=>{b.stopPropagation();b.preventDefault()};h.rd=b=>{b.stopPropagation();b.preventDefault()};h.sd=b=>{b.stopPropagation();b.preventDefault()};h.td=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.ud=c;ic(c.length);for(let e=0;e<c.length;e++)ac(()=>{const g=
Yb(c[e].name);jc(e,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);kc(b.clientX,b.clientY,d)};const a=h.Jc;a.addEventListener("dragenter",h.qd,!1);a.addEventListener("dragleave",h.rd,!1);a.addEventListener("dragover",h.sd,!1);a.addEventListener("drop",h.td,!1)},gb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},$b:function(a){const b=h.ud;return 0>a||a>=b.length?0:b[a].size},Ub:function(a,b,c,d,e){const g=new FileReader;
g.onload=f=>{f=f.target.result;f.byteLength>d?lc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(f),c),lc(a,1,0,b,f.byteLength,c,d,e))};g.onerror=()=>{lc(a,0,2,b,0,c,d,e)};g.readAsArrayBuffer(h.ud[a])},Ib:function(a,b){0!==b&&(document.title=b?B(t,b):"");a=a?B(t,a):"";void 0!==h.canvas&&("object"===typeof h.canvas?bb[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.Jc=I(a);h.Jc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Jc.requestPointerLock||
console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Sa:function(){window.removeEventListener("beforeunload",h.pd)},Na:function(){window.removeEventListener("paste",h.vd)},Rb:function(){const a=h.Jc;a.removeEventListener("dragenter",h.qd);a.removeEventListener("dragleave",h.rd);a.removeEventListener("dragover",h.sd);a.removeEventListener("drop",h.td)},z:function(){h.Jc&&h.Jc.requestPointerLock&&h.Jc.requestPointerLock()},ob:function(a,b){if(h.Jc){if(0===b)a="none";else switch(a){case 0:a=
"auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.Jc.style.cursor=a}},fb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,b);g.data.set(t.subarray(c,c+a*b*4));e.putImageData(g,
0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ja:function(a){a=a?B(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");
document.body.removeChild(b)},cb:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];ac(()=>{const e=Yb(c),g=Yb(d);mc(e,g)})}},db:function(){if(h.yd)return"suspended"===h.yd.state?1:0},x:function(a,b,c,d,e,g){const f=b?B(t,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(f,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>{m=new Uint8Array(m);m.length<=g?(t.set(m,e),nc(a,
d,m.length)):oc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,m);pc(a)}):qc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,l);pc(a)})},ja:function(a,b){const c=b?B(t,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),pc(a)):rc(a,Number(d))):qc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);pc(a)})},ya:function(){return navigator.userAgent.includes("Macintosh")?
1:0},ia:function(a,b){b=b?B(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;na=Z.gc;ra();eb=Z.zc;z--;h.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;h.monitorRunDependencies?.(z);var b={a:sc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{a(d,e);c(d.exports)})});ta??=h.locateFile?h.locateFile("z1013-ui.wasm",k):k+"z1013-ui.wasm";return a((await wa(b)).instance)})();
var N=a=>(N=Z.ic)(a),ec=h._fs_emsc_alloc=a=>(ec=h._fs_emsc_alloc=Z.jc)(a),fc=h._fs_emsc_load_snapshot_callback=(a,b,c)=>(fc=h._fs_emsc_load_snapshot_callback=Z.kc)(a,b,c),hc=h.__sapp_emsc_onpaste=a=>(hc=h.__sapp_emsc_onpaste=Z.lc)(a),gc=h.__sapp_html5_get_ask_leave_site=()=>(gc=h.__sapp_html5_get_ask_leave_site=Z.mc)(),ic=h.__sapp_emsc_begin_drop=a=>(ic=h.__sapp_emsc_begin_drop=Z.nc)(a),jc=h.__sapp_emsc_drop=(a,b)=>(jc=h.__sapp_emsc_drop=Z.oc)(a,b),kc=h.__sapp_emsc_end_drop=(a,b,c)=>(kc=h.__sapp_emsc_end_drop=
Z.pc)(a,b,c),lc=h.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,g,f,l)=>(lc=h.__sapp_emsc_invoke_fetch_cb=Z.qc)(a,b,c,d,e,g,f,l),tc=h._main=(a,b)=>(tc=h._main=Z.rc)(a,b);h.__saudio_emsc_pull=a=>(h.__saudio_emsc_pull=Z.sc)(a);
var mc=h.__sargs_add_kvp=(a,b)=>(mc=h.__sargs_add_kvp=Z.tc)(a,b),rc=h.__sfetch_emsc_head_response=(a,b)=>(rc=h.__sfetch_emsc_head_response=Z.uc)(a,b),nc=h.__sfetch_emsc_get_response=(a,b,c)=>(nc=h.__sfetch_emsc_get_response=Z.vc)(a,b,c),qc=h.__sfetch_emsc_failed_http_status=(a,b)=>(qc=h.__sfetch_emsc_failed_http_status=Z.wc)(a,b),oc=h.__sfetch_emsc_failed_buffer_too_small=a=>(oc=h.__sfetch_emsc_failed_buffer_too_small=Z.xc)(a),pc=h.__sfetch_emsc_failed_other=a=>(pc=h.__sfetch_emsc_failed_other=Z.yc)(a),
dc=(a,b)=>(dc=Z.Ac)(a,b),$b=a=>($b=Z.Bc)(a),Xb=a=>(Xb=Z.Cc)(a),Zb=()=>(Zb=Z.Dc)();function uc(a=[]){var b=tc;a.unshift(fa);var c=a.length,d=Xb(4*(c+1)),e=d;a.forEach(f=>{w[e>>2]=Yb(f);e+=4});w[e>>2]=0;try{var g=b(c,d);Ha(g)}catch(f){Fa(f)}}
function vc(a=ea){function b(){h.calledRun=!0;if(!q){Z.hc();h.onRuntimeInitialized?.();h.noInitialRun||uc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();za.unshift(c)}ya(za)}}if(0<z)A=vc;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ba();ya(Aa);0<z?A=vc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();vc();
