var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da={...h},ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs");require("path");k=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!h.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?
"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var la=h.print||console.log.bind(console),n=h.printErr||console.error.bind(console);Object.assign(h,da);da=null;h.arguments&&(ea=h.arguments);h.thisProgram&&(fa=h.thisProgram);var ma=h.wasmBinary,na,q=!1,oa,r,t,pa,qa,u,w,x,y,ka=a=>a.startsWith("file://");
function ra(){var a=na.buffer;h.HEAP8=r=new Int8Array(a);h.HEAP16=pa=new Int16Array(a);h.HEAPU8=t=new Uint8Array(a);h.HEAPU16=qa=new Uint16Array(a);h.HEAP32=u=new Int32Array(a);h.HEAPU32=w=new Uint32Array(a);h.HEAPF32=x=new Float32Array(a);h.HEAPF64=y=new Float64Array(a);h.HEAP64=new BigInt64Array(a);h.HEAPU64=new BigUint64Array(a)}var z=0,A=null;function sa(a){h.onAbort?.(a);a="Aborted("+a+")";n(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==ta&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!ma&&"function"==typeof WebAssembly.instantiateStreaming&&!ka(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(h)},za=[],Aa=[],Ba=()=>{var a=h.preRun.shift();Aa.unshift(a)},Ca=h.noExitRuntime||!0,Da="undefined"!=typeof TextDecoder?new TextDecoder:void 0,B=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Da)return Da.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):
(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ea=0,C={},Fa=a=>{a instanceof xa||"unwind"==a||ha(1,a)},Ga=a=>{oa=a;Ca||0<Ea||(h.onExit?.(a),q=!0);ha(a,new xa(a))},Ha=a=>{oa=a;Ga(a)},Ia=()=>{if(!(Ca||0<Ea))try{var a=oa;oa=a;Ga(a)}catch(b){Fa(b)}},Ja=a=>{if(!q)try{a(),Ia()}catch(b){Fa(b)}},Qa=(a,b)=>{Ka=a;La=b;if(D)if(Ma||=!0,0==a)E=function(){setTimeout(G,Math.max(0,Na+b-performance.now())|0)};else if(1==a)E=function(){Oa(G)};else if(2==a){if("undefined"==
typeof Pa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Pa=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Pa=setImmediate;E=function(){Pa(G)}}},Za=(a,b,c,d,e)=>{function g(){return f<Ra?(Ia(),!1):!0}D=a;Sa=d;var f=Ra;Ma=!1;G=function(){if(!q)if(0<Ta.length){var l=
Ta.shift();l.Ud(l.Jd);if(Ua){var m=Ua,p=0==m%1?m-1:Math.floor(m);Ua=l.Ld?p:(8*m+(p+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",m=Ua??0,p=Va.Qd??0,m?m<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));g()&&setTimeout(G,0)}else if(g())if(Wa=Wa+1|0,1==Ka&&1<La&&0!=Wa%La)E();else{0==Ka&&(Na=performance.now());a:if(!q){for(l of Xa)if(!1===l())break a;Ja(a);for(m of Ya)m()}g()&&E()}};e||(0<b?Qa(0,1E3/b):Qa(1,1),E());if(c)throw"unwind";},Ma=!1,E=
null,Ra=0,D=null,Sa=0,Ka=0,La=0,Wa=0,Ta=[],Xa=[],Ya=[];function $a(){E=null;Ra++}var ab=0;function Oa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ab)ab=b+1E3/60;else for(;b+2>=ab;)ab+=1E3/60;setTimeout(a,Math.max(ab-b,0))}}
var Va={},Na,G,Pa,Ua,bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],H=a=>{a=2<a?a?B(t,a):"":a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):null)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=[],eb,I=a=>{var b=db[a];b||(db[a]=b=eb.get(a));return b};function fb(a){var b=J.Kc[a];b.target.removeEventListener(b.Jc,b.qd,b.Lc);J.Kc.splice(a,1)}
function gb(){if(navigator.userActivation?navigator.userActivation.isActive:J.$c&&J.Ed.Yc){var a=J.Rc;J.Rc=[];for(var b of a)b.cd(...b.md)}}function K(a){if(!a.target)return-4;if(a.Mc)a.qd=function(c){++J.$c;J.Ed=a;gb();a.Nc(c);gb();--J.$c},a.target.addEventListener(a.Jc,a.qd,a.Lc),J.Kc.push(a);else for(var b=0;b<J.Kc.length;++b)J.Kc[b].target==a.target&&J.Kc[b].Jc==a.Jc&&fb(b--);return 0}function hb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var J={Kd:0,Vd:0,ad:0,Xc:0,hd:0,ed:0,Zc:0,Od:0,$d:0,Nd:0,Td:0,bd:0,he:0,dd:0,Xd(a,b,c){r.set(r.subarray(b,b+c),a)},be(){for(;J.Kc.length;)fb(J.Kc.length-1);J.Rc=[]},$c:0,Rc:[],Md(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of J.Rc)if(e.cd==a&&d(e.md,c))return;J.Rc.push({cd:a,ud:b,md:c});J.Rc.sort((g,f)=>g.ud<f.ud)},de(a){J.Rc=J.Rc.filter(b=>b.cd!=a)},Kc:[],ce:(a,b)=>{for(var c=0;c<J.Kc.length;++c)J.Kc[c].target!=a||b&&b!=J.Kc[c].Jc||
fb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},L=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var l=a.charCodeAt(++g);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|
f&63}}d[b]=0;return b-e},ib=(a,b,c,d,e,g)=>{J.Zc||(J.Zc=M(256));a={target:H(a),Jc:g,Mc:d,Nc:(f=event)=>{var l=f.target.id?f.target.id:"",m=J.Zc;L(hb(f.target),m+0,128);L(l,m+128,128);I(d)(e,m,b)&&f.preventDefault()},Lc:c};return K(a)},jb=(a,b,c,d,e,g)=>{J.ad||(J.ad=M(160));a={target:H(a),Jc:g,Mc:d,Nc:f=>{var l=J.ad;y[l>>3]=f.timeStamp;var m=l>>2;u[m+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;u[m+5]=f.charCode;u[m+6]=f.keyCode;u[m+7]=f.which;
L(f.key||"",l+32,32);L(f.code||"",l+64,32);L(f.char||"",l+96,32);L(f.locale||"",l+128,32);I(d)(e,l,b)&&f.preventDefault()},Lc:c};return K(a)},kb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=cb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},lb=(a,b,c,d,e,g)=>{J.Xc||(J.Xc=
M(64));a=H(a);return K({target:a,Yc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,Jc:g,Mc:d,Nc:(f=event)=>{kb(J.Xc,f,a);I(d)(e,J.Xc,b)&&f.preventDefault()},Lc:c})},mb=(a,b,c,d,e)=>{J.bd||(J.bd=M(257));return K({target:a,Jc:e,Mc:d,Nc:(g=event)=>{var f=J.bd,l=document.pointerLockElement||document.Sc||document.ld||document.kd;r[f]=!!l;var m=l?.id||"";L(hb(l),f+1,128);L(m,f+129,128);I(d)(20,f,b)&&g.preventDefault()},Lc:c})},nb=(a,b,c,d,e)=>K({target:a,Jc:e,Mc:d,Nc:(g=event)=>{I(d)(38,0,b)&&g.preventDefault()},
Lc:c}),ob=(a,b,c,d)=>{J.ed||(J.ed=M(36));a=H(a);return K({target:a,Jc:"resize",Mc:d,Nc:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=J.ed;u[f>>2]=0;u[f+4>>2]=g.clientWidth;u[f+8>>2]=g.clientHeight;u[f+12>>2]=innerWidth;u[f+16>>2]=innerHeight;u[f+20>>2]=outerWidth;u[f+24>>2]=outerHeight;u[f+28>>2]=pageXOffset|0;u[f+32>>2]=pageYOffset|0;I(d)(10,f,b)&&e.preventDefault()}}},Lc:c})},pb=(a,b,c,d,e,g)=>{J.dd||(J.dd=M(1552));a=H(a);return K({target:a,Yc:"touchstart"==g||"touchend"==g,Jc:g,Mc:d,
Nc:f=>{var l={},m=f.touches;for(var p of m)p.rd=p.td=0,l[p.identifier]=p;for(var v of f.changedTouches)v.rd=1,l[v.identifier]=v;for(var Q of f.targetTouches)l[Q.identifier].td=1;m=J.dd;y[m>>3]=f.timeStamp;r[m+12]=f.ctrlKey;r[m+13]=f.shiftKey;r[m+14]=f.altKey;r[m+15]=f.metaKey;p=m+16;v=cb(a);Q=0;for(let F of Object.values(l))if(l=p>>2,u[l]=F.identifier,u[l+1]=F.screenX,u[l+2]=F.screenY,u[l+3]=F.clientX,u[l+4]=F.clientY,u[l+5]=F.pageX,u[l+6]=F.pageY,r[p+28]=F.rd,r[p+29]=F.td,u[l+8]=F.clientX-(v.left|
0),u[l+9]=F.clientY-(v.top|0),p+=48,31<++Q)break;u[m+8>>2]=Q;I(d)(e,m,b)&&f.preventDefault()},Lc:c})},N,qb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},rb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>
b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},sb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},tb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},ub=1,vb=[],O=[],wb=[],xb=[],P=[],R=[],yb=[],zb=[],S=[],Ab={},Bb=4,Cb=0,Db=a=>{for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=N[c](),f=g&&Db(d);g?(g.name=f,d[f]=g):T||=1282;u[b+4*e>>2]=f}},Fb=(a,b)=>{a.Sc||(a.Sc=a.getContext,a.getContext=function(d,e){e=a.Sc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.sd?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Eb(c,b):0},Eb=(a,b)=>{var c=Db(zb),d={handle:c,attributes:b,version:b.sd,jd:a};a.canvas&&(a.canvas.Id=d);zb[c]=d;("undefined"==typeof b.pd||b.pd)&&Gb(d);return c},Gb=a=>{a||=V;if(!a.Hd){a.Hd=!0;var b=a.jd;b.Zd=b.getExtension("WEBGL_multi_draw");b.Sd=b.getExtension("EXT_polygon_offset_clamp");b.Rd=b.getExtension("EXT_clip_control");b.ie=b.getExtension("WEBGL_polygon_mode");qb(b);rb(b);sb(b);b.Pd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Wd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.od=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.od)b.od=b.getExtension("EXT_disjoint_timer_query");tb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Hb=(a,b,c,d,e,g)=>{a={target:H(a),Jc:g,Mc:d,Nc:(f=event)=>{I(d)(e,0,b)&&f.preventDefault()},Lc:c};K(a)},Ib=(a,b,c,d)=>{J.hd||(J.hd=M(96));return K({target:a,Yc:!0,Jc:"wheel",Mc:d,Nc:(e=event)=>{var g=J.hd;kb(g,e,a);y[g+64>>3]=e.deltaX;y[g+72>>3]=e.deltaY;y[g+80>>3]=e.deltaZ;
u[g+88>>2]=e.deltaMode;I(d)(9,g,b)&&e.preventDefault()},Lc:c})},Jb=["default","low-power","high-performance"],Kb={},Mb=()=>{if(!Lb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in Kb)void 0===Kb[b]?delete a[b]:a[b]=Kb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Lb=c}return Lb},Lb,Nb=[null,[],[]],Ob=[],Pb=()=>{var a=tb(N);
return a=a.concat(a.map(b=>"GL_"+b))},Qb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=N.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Pb().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=N.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else T||=1281},Rb=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Sb=a=>{var b=Rb(a)+1,c=M(b);c&&L(a,c,b);return c},Tb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ub=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?u:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?w:qa},Vb=(a,b,c,d,e)=>{a=Ub(a);b=d*((Cb||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Bb-1&-Bb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=N.Fd;if(b){var c=b.Tc[a];"number"==typeof c&&(b.Tc[a]=c=N.getUniformLocation(b,b.Cd[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],Wb=[],Yb=a=>{var b=Rb(a)+1,c=Xb(b);L(a,c,b);return c},ac=a=>{var b=Zb();a();$b(b)};h.requestAnimationFrame=Oa;h.pauseMainLoop=$a;h.resumeMainLoop=function(){Ra++;var a=Ka,b=La,c=D;D=null;Za(c,0,!1,Sa,!0);Qa(a,b);E()};h.preMainLoop&&Xa.push(h.preMainLoop);h.postMainLoop&&Ya.push(h.postMainLoop);for(let a=0;32>a;++a)Ob.push(Array(a));
for(var bc=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=bc.subarray(0,Y);var cc=new Int32Array(288);for(Y=0;288>=Y;++Y)Wb[Y]=cc.subarray(0,Y);
var tc={ma:function(){return 0},ob:function(){return 0},pb:function(){},tb:()=>sa(""),hb:()=>{Ca=!1;Ea=0},jb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ja(()=>dc(a,performance.now()))},b);C[a]={id:c,ge:b};return 0},eb:function(a){if(void 0===window.localStorage)return 0;a=a?B(t,a):"";return(a=window.localStorage.getItem(a))?Sb(a):0},jc:function(a,b){void 0!==window.localStorage&&(a=a?B(t,a):"",b=b?B(t,b):"",window.localStorage.setItem(a,b))},
Ta:()=>{$a();D=null},fa:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ha:(a,b,c)=>{a=H(a);if(!a)return-4;a=cb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},y:()=>performance.now(),Ua:()=>performance.now(),Ya:(a,b)=>{function c(d){I(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},kb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+
65535)/65536|0;try{na.grow(d);ra();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},P:(a,b,c,d)=>ib(a,b,c,d,12,"blur"),ea:(a,b,c)=>{a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},Q:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),Z:(a,b,c,d)=>jb(a,b,c,d,2,"keydown"),X:(a,b,c,d)=>jb(a,b,c,d,1,"keypress"),Y:(a,b,c,d)=>jb(a,b,c,d,3,"keyup"),Za:(a,b,c)=>{a=I(a);Za(a,b,c)},da:(a,b,c,d)=>lb(a,b,c,d,5,"mousedown"),aa:(a,b,c,d)=>lb(a,b,c,d,33,"mouseenter"),$:(a,b,c,d)=>lb(a,b,c,d,34,"mouseleave"),ba:(a,
b,c,d)=>lb(a,b,c,d,8,"mousemove"),ca:(a,b,c,d)=>lb(a,b,c,d,6,"mouseup"),S:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Sc||document.body.ld||document.body.kd))return-1;a=H(a);if(!a)return-4;mb(a,b,c,d,"mozpointerlockchange");mb(a,b,c,d,"webkitpointerlockchange");mb(a,b,c,d,"mspointerlockchange");return mb(a,b,c,d,"pointerlockchange")},R:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.Sc||document.body.ld||document.body.kd))return-1;
a=H(a);if(!a)return-4;nb(a,b,c,d,"mozpointerlockerror");nb(a,b,c,d,"webkitpointerlockerror");nb(a,b,c,d,"mspointerlockerror");return nb(a,b,c,d,"pointerlockerror")},ga:(a,b,c,d)=>ob(a,b,c,d),T:(a,b,c,d)=>pb(a,b,c,d,25,"touchcancel"),U:(a,b,c,d)=>pb(a,b,c,d,23,"touchend"),V:(a,b,c,d)=>pb(a,b,c,d,24,"touchmove"),W:(a,b,c,d)=>pb(a,b,c,d,22,"touchstart"),O:(a,b,c,d)=>{Hb(a,b,c,d,31,"webglcontextlost");return 0},N:(a,b,c,d)=>{Hb(a,b,c,d,32,"webglcontextrestored");return 0},_:(a,b,c,d)=>(a=H(a))?"undefined"!=
typeof a.onwheel?Ib(a,b,c,d):-1:-4,Xa:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Jb[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],sd:u[c+4],Yd:u[c+5],pd:r[b+24],Gd:r[b+25],ae:u[c+7],ee:r[b+32]};a=H(a);return!a||b.Gd?0:Fb(a,b)},Wa:a=>{V=zb[a];h.ctx=N=V?.jd;return!a||N?0:-5},qb:(a,b)=>{var c=0;Mb().forEach((d,e)=>{var g=b+c;e=w[a+4*e>>2]=g;for(g=0;g<d.length;++g)r[e++]=d.charCodeAt(g);
r[e]=0;c+=d.length+1});return 0},sb:(a,b)=>{var c=Mb();w[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);w[b>>2]=d;return 0},la:()=>52,nb:()=>52,lb:function(){return 70},mb:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=w[b>>2],l=w[b+4>>2];b+=8;for(var m=0;m<l;m++){var p=t[f+m],v=Nb[a];0===p||10===p?((1===a?la:n)(B(v)),v.length=0):v.push(p)}e+=l}w[d>>2]=e;return 0},l:function(a,b,c){const d=a?B(t,a):"";let e;try{e=window.indexedDB.open("chips",1)}catch(g){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+
g)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");e.result.createObjectStore("store")};e.onsuccess=()=>{var g=e.result;let f;try{f=g.transaction(["store"],"readwrite")}catch(p){console.log("fs_js_load_snapshot: db.transaction failed with",p);return}g=f.objectStore("store");const l=d+"_"+b,m=g.get(l);m.onsuccess=()=>{if(void 0!==m.result){const p=m.result.length;console.log("fs_js_load_snapshot:",l,"successfully loaded",p,"bytes");const v=ec(p);t.set(m.result,v);fc(c,v,p)}else fc(c,
0,0)};m.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",l)};f.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},_a:function(a,b,c,d){const e=a?B(t,a):"";console.log("fs_js_save_snapshot: called with",e,b);let g;try{g=window.indexedDB.open("chips",1)}catch(f){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+f);return}g.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");
g.result.createObjectStore("store")};g.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");const f=g.result.transaction(["store"],"readwrite");var l=f.objectStore("store");const m=e+"_"+b;l=l.put(t.subarray(c,c+d),m);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",m,"successfully stored")};l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",m)};f.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};g.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},
q:a=>N.activeTexture(a),B:(a,b)=>{N.attachShader(O[a],R[b])},b:(a,b)=>{35051==a?N.nd=b:35052==a&&(N.Qc=b);N.bindBuffer(a,vb[b])},a:(a,b,c)=>{N.bindBufferBase(a,b,vb[c])},n:(a,b)=>{N.bindFramebuffer(a,wb[b])},Ea:(a,b)=>{N.bindRenderbuffer(a,xb[b])},p:(a,b)=>{N.bindSampler(a,S[b])},d:(a,b)=>{N.bindTexture(a,P[b])},M:a=>{N.bindVertexArray(yb[a])},I:(a,b,c,d)=>N.blendColor(a,b,c,d),J:(a,b)=>N.blendEquationSeparate(a,b),K:(a,b,c,d)=>N.blendFuncSeparate(a,b,c,d),xb:(a,b,c,d,e,g,f,l,m,p)=>N.blitFramebuffer(a,
b,c,d,e,g,f,l,m,p),Ga:(a,b,c,d)=>{2<=V.version?c&&b?N.bufferData(a,t,d,c,b):N.bufferData(a,b,d):N.bufferData(a,c?t.subarray(c,c+b):b,d)},C:(a,b,c,d)=>{2<=V.version?c&&N.bufferSubData(a,b,t,d,c):N.bufferSubData(a,b,t.subarray(d,d+c))},ra:a=>N.checkFramebufferStatus(a),Sb:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),pa:(a,b,c)=>{N.clearBufferfv(a,b,x,c>>2)},Rb:(a,b,c)=>{N.clearBufferiv(a,b,u,c>>2)},r:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},Xb:a=>{N.compileShader(R[a])},gc:(a,b,c,d,e,g,f,l)=>{2<=V.version?
N.Qc||!f?N.compressedTexImage2D(a,b,c,d,e,g,f,l):N.compressedTexImage2D(a,b,c,d,e,g,t,l,f):N.compressedTexImage2D(a,b,c,d,e,g,t.subarray(l,l+f))},ec:(a,b,c,d,e,g,f,l,m)=>{N.Qc?N.compressedTexImage3D(a,b,c,d,e,g,f,l,m):N.compressedTexImage3D(a,b,c,d,e,g,f,t,m,l)},bc:()=>{var a=Db(O),b=N.createProgram();b.name=a;b.Wc=b.Uc=b.Vc=0;b.gd=1;O[a]=b;return a},Zb:a=>{var b=Db(R);R[b]=N.createShader(a);return b},F:a=>N.cullFace(a),Ka:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=vb[d];e&&(N.deleteBuffer(e),
e.name=0,vb[d]=null,d==N.nd&&(N.nd=0),d==N.Qc&&(N.Qc=0))}},f:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=wb[d];e&&(N.deleteFramebuffer(e),e.name=0,wb[d]=null)}},j:a=>{if(a){var b=O[a];b?(N.deleteProgram(b),b.name=0,O[a]=null):T||=1281}},D:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=xb[d];e&&(N.deleteRenderbuffer(e),e.name=0,xb[d]=null)}},g:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=S[d];e&&(N.deleteSampler(e),e.name=0,S[d]=null)}},t:a=>{if(a){var b=R[a];b?(N.deleteShader(b),R[a]=null):
T||=1281}},E:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=P[d];e&&(N.deleteTexture(e),e.name=0,P[d]=null)}},Ia:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];N.deleteVertexArray(yb[d]);yb[d]=null}},w:a=>N.depthFunc(a),v:a=>{N.depthMask(!!a)},e:a=>N.disable(a),L:a=>{N.disableVertexAttribArray(a)},zb:(a,b,c)=>{N.drawArrays(a,b,c)},Ab:(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},qa:(a,b)=>{for(var c=Ob[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];N.drawBuffers(c)},Bb:(a,b,c,d)=>{N.drawElements(a,b,c,d)},Cb:(a,
b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},k:a=>N.enable(a),Nb:a=>{N.enableVertexAttribArray(a)},sa:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,xb[d])},o:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,P[d],e)},A:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,P[c],d,e)},G:a=>N.frontFace(a),Ha:(a,b)=>{U(a,b,"createBuffer",vb)},ta:(a,b)=>{U(a,b,"createFramebuffer",wb)},Fa:(a,b)=>{U(a,b,"createRenderbuffer",xb)},cc:(a,b)=>{U(a,b,"createSampler",S)},Ca:(a,b)=>{U(a,b,"createTexture",P)},Sa:(a,b)=>{U(a,b,"createVertexArray",
yb)},Ub:(a,b)=>N.getAttribLocation(O[a],b?B(t,b):""),c:(a,b)=>Qb(a,b),$b:(a,b,c,d)=>{a=N.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(u[c>>2]=b)},wa:(a,b,c)=>{if(c)if(a>=ub)T||=1281;else if(a=O[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.Wc){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Wc=Math.max(a.Wc,N.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.Wc}else if(35722==b){if(!a.Uc)for(d=
N.getProgramParameter(a,35721),b=0;b<d;++b)a.Uc=Math.max(a.Uc,N.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Uc}else if(35381==b){if(!a.Vc)for(d=N.getProgramParameter(a,35382),b=0;b<d;++b)a.Vc=Math.max(a.Vc,N.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Vc}else u[c>>2]=N.getProgramParameter(a,b);else T||=1281},Vb:(a,b,c,d)=>{a=N.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(u[c>>2]=b)},ua:(a,b,c)=>{c?35716==b?(a=N.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),
u[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(R[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=N.getShaderParameter(R[a],b):T||=1281},Pa:(a,b)=>{if(2>V.version)return T||=1282,0;var c=Ab[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Pb().map(Sb),c=Ab[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},va:(a,b)=>{b=b?B(t,b):"";if(a=O[a]){var c=a,d=c.Tc,e=c.Dd,g;if(!d){c.Tc=d={};c.Cd={};var f=N.getProgramParameter(c,35718);for(g=0;g<f;++g){var l=N.getActiveUniform(c,
g);var m=l.name;l=l.size;var p=Tb(m);p=0<p?m.slice(0,p):m;var v=c.gd;c.gd+=l;e[p]=[l,v];for(m=0;m<l;++m)d[v]=m,c.Cd[v++]=p}}c=a.Tc;d=0;e=b;g=Tb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Dd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T||=1281;return-1},wb:(a,b,c)=>{for(var d=Ob[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];N.invalidateFramebuffer(a,d)},xa:a=>{a=O[a];N.linkProgram(a);a.Tc=0;a.Dd={}},Qa:(a,b)=>{3317==a?Bb=b:3314==a&&(Cb=b);N.pixelStorei(a,b)},H:(a,
b)=>N.polygonOffset(a,b),yb:a=>N.readBuffer(a),Da:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,b,c,d,e),ya:(a,b,c)=>{N.samplerParameterf(S[a],b,c)},h:(a,b,c)=>{N.samplerParameteri(S[a],b,c)},s:(a,b,c,d)=>N.scissor(a,b,c,d),Yb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=w[c+4*g>>2])?B(t,f,d?w[d+4*g>>2]:void 0):"";e+=f}N.shaderSource(R[a],e)},Oa:(a,b,c)=>N.stencilFunc(a,b,c),oa:(a,b,c,d)=>N.stencilFuncSeparate(a,b,c,d),u:a=>N.stencilMask(a),Na:(a,b,c)=>N.stencilOp(a,b,c),na:(a,b,c,d)=>N.stencilOpSeparate(a,
b,c,d),fc:(a,b,c,d,e,g,f,l,m)=>{if(2<=V.version){if(N.Qc){N.texImage2D(a,b,c,d,e,g,f,l,m);return}if(m){var p=Ub(l);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);N.texImage2D(a,b,c,d,e,g,f,l,p,m);return}}p=m?Vb(l,f,d,e,m):null;N.texImage2D(a,b,c,d,e,g,f,l,p)},dc:(a,b,c,d,e,g,f,l,m,p)=>{if(N.Qc)N.texImage3D(a,b,c,d,e,g,f,l,m,p);else if(p){var v=Ub(m);N.texImage3D(a,b,c,d,e,g,f,l,m,v,p>>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else N.texImage3D(a,b,c,d,e,g,f,l,m,null)},Ba:(a,b,c)=>N.texParameteri(a,b,c),Aa:(a,
b,c,d,e)=>N.texStorage2D(a,b,c,d,e),hc:(a,b,c,d,e,g)=>N.texStorage3D(a,b,c,d,e,g),vb:(a,b,c,d,e,g,f,l,m)=>{if(2<=V.version){if(N.Qc){N.texSubImage2D(a,b,c,d,e,g,f,l,m);return}if(m){var p=Ub(l);N.texSubImage2D(a,b,c,d,e,g,f,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}m=m?Vb(l,f,e,g,m):null;N.texSubImage2D(a,b,c,d,e,g,f,l,m)},ub:(a,b,c,d,e,g,f,l,m,p,v)=>{if(N.Qc)N.texSubImage3D(a,b,c,d,e,g,f,l,m,p,v);else if(v){var Q=Ub(p);N.texSubImage3D(a,b,c,d,e,g,f,l,m,p,Q,v>>>31-Math.clz32(Q.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,
b,c,d,e,g,f,l,m,p,null)},Lb:(a,b,c)=>{if(2<=V.version)b&&N.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);N.uniform1fv(W(a),d)}},_b:(a,b)=>{N.uniform1i(W(a),b)},Hb:(a,b,c)=>{if(2<=V.version)b&&N.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=Wb[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);N.uniform1iv(W(a),d)}},Kb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=
X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);N.uniform2fv(W(a),d)}},Gb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Wb[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);N.uniform2iv(W(a),d)}},Jb:(a,b,c)=>{if(2<=V.version)b&&N.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=
x.subarray(c>>2,c+12*b>>2);N.uniform3fv(W(a),d)}},Fb:(a,b,c)=>{if(2<=V.version)b&&N.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Wb[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);N.uniform3iv(W(a),d)}},Ib:(a,b,c)=>{if(2<=V.version)b&&N.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>
2);N.uniform4fv(W(a),d)}},Eb:(a,b,c)=>{if(2<=V.version)b&&N.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Wb[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);N.uniform4iv(W(a),d)}},Db:(a,b,c,d)=>{if(2<=V.version)b&&N.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],g=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+
5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(W(a),!!c,e)}},i:a=>{a=O[a];N.useProgram(a);N.Fd=a},Ob:(a,b)=>{N.vertexAttribDivisor(a,b)},Pb:(a,b,c,d,e)=>{N.vertexAttribIPointer(a,b,c,d,e)},Qb:(a,b,c,d,e,g)=>{N.vertexAttribPointer(a,b,c,!!d,e,g)},m:(a,b,c,d)=>N.viewport(a,b,c,d),gb:Ga,Va:function(){h.vd=a=>{0!=gc()&&(a.preventDefault(),
a.returnValue=" ")};window.addEventListener("beforeunload",h.vd)},Ma:function(){h.Bd=a=>{const b=a.clipboardData.getData("text");ac(()=>{const c=Yb(b);hc(c)})};window.addEventListener("paste",h.Bd)},ic:function(){h.fe=[];h.wd=b=>{b.stopPropagation();b.preventDefault()};h.xd=b=>{b.stopPropagation();b.preventDefault()};h.yd=b=>{b.stopPropagation();b.preventDefault()};h.zd=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.Ad=c;ic(c.length);for(let e=0;e<c.length;e++)ac(()=>{const g=
Yb(c[e].name);jc(e,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);kc(b.clientX,b.clientY,d)};const a=h.Oc;a.addEventListener("dragenter",h.wd,!1);a.addEventListener("dragleave",h.xd,!1);a.addEventListener("dragover",h.yd,!1);a.addEventListener("drop",h.zd,!1)},ib:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},ac:function(a){const b=h.Ad;return 0>a||a>=b.length?0:b[a].size},Wb:function(a,b,c,d,e){const g=new FileReader;
g.onload=f=>{f=f.target.result;f.byteLength>d?lc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(f),c),lc(a,1,0,b,f.byteLength,c,d,e))};g.onerror=()=>{lc(a,0,2,b,0,c,d,e)};g.readAsArrayBuffer(h.Ad[a])},Mb:function(a,b){0!==b&&(document.title=b?B(t,b):"");a=a?B(t,a):"";void 0!==h.canvas&&("object"===typeof h.canvas?bb[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.Oc=H(a);h.Oc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Oc.requestPointerLock||
console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ra:function(){window.removeEventListener("beforeunload",h.vd)},La:function(){window.removeEventListener("paste",h.Bd)},Tb:function(){const a=h.Oc;a.removeEventListener("dragenter",h.wd);a.removeEventListener("dragleave",h.xd);a.removeEventListener("dragover",h.yd);a.removeEventListener("drop",h.zd)},z:function(){h.Oc&&h.Oc.requestPointerLock&&h.Oc.requestPointerLock()},rb:function(a,b){if(h.Oc){if(0===b)a="none";else switch(a){case 0:a=
"auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.Oc.style.cursor=a}},fb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,b);g.data.set(t.subarray(c,c+a*b*4));e.putImageData(g,
0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ja:function(a){a=a?B(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");
document.body.removeChild(b)},$a:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];ac(()=>{const e=Yb(c),g=Yb(d);mc(e,g)})}},bb:function(){return h.Pc?h.Pc.bufferSize:0},db:function(a,b,c){h.Ic=null;h.Pc=null;"undefined"!==typeof AudioContext?h.Ic=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(h.Ic=null,console.log("sokol_audio.h: no WebAudio support"));return h.Ic?(console.log("sokol_audio.h: sample rate ",
h.Ic.sampleRate),h.Pc=h.Ic.createScriptProcessor(c,0,b),h.Pc.onaudioprocess=d=>{const e=d.outputBuffer.length,g=nc(e);if(g){const f=d.outputBuffer.numberOfChannels;for(let l=0;l<f;l++){const m=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)m[p]=x[(g>>2)+(f*p+l)]}}},h.Pc.connect(h.Ic.destination),a=()=>{h.Ic&&"suspended"===h.Ic.state&&h.Ic.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),
1):0},cb:function(){return h.Ic?h.Ic.sampleRate:0},ka:function(){const a=h.Ic;null!==a&&(h.Pc&&h.Pc.disconnect(),a.close(),h.Ic=null,h.Pc=null)},ab:function(){if(h.Ic)return"suspended"===h.Ic.state?1:0},x:function(a,b,c,d,e,g){const f=b?B(t,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(f,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>{m=new Uint8Array(m);m.length<=g?(t.set(m,e),oc(a,d,m.length)):pc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,
m);qc(a)}):rc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,l);qc(a)})},ja:function(a,b){const c=b?B(t,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),qc(a)):sc(a,Number(d))):rc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);qc(a)})},za:function(){return navigator.userAgent.includes("Macintosh")?1:0},ia:function(a,b){b=
b?B(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;(async function(){function a(c){Z=c.exports;na=Z.kc;ra();eb=Z.Dc;z--;h.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;h.monitorRunDependencies?.(z);var b={a:tc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{a(d,e);c(d.exports)})});ta??=h.locateFile?h.locateFile("z9001-ui.wasm",k):k+"z9001-ui.wasm";return a((await wa(b)).instance)})();
var M=a=>(M=Z.mc)(a),ec=h._fs_emsc_alloc=a=>(ec=h._fs_emsc_alloc=Z.nc)(a),fc=h._fs_emsc_load_snapshot_callback=(a,b,c)=>(fc=h._fs_emsc_load_snapshot_callback=Z.oc)(a,b,c),hc=h.__sapp_emsc_onpaste=a=>(hc=h.__sapp_emsc_onpaste=Z.pc)(a),gc=h.__sapp_html5_get_ask_leave_site=()=>(gc=h.__sapp_html5_get_ask_leave_site=Z.qc)(),ic=h.__sapp_emsc_begin_drop=a=>(ic=h.__sapp_emsc_begin_drop=Z.rc)(a),jc=h.__sapp_emsc_drop=(a,b)=>(jc=h.__sapp_emsc_drop=Z.sc)(a,b),kc=h.__sapp_emsc_end_drop=(a,b,c)=>(kc=h.__sapp_emsc_end_drop=
Z.tc)(a,b,c),lc=h.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,g,f,l)=>(lc=h.__sapp_emsc_invoke_fetch_cb=Z.uc)(a,b,c,d,e,g,f,l),uc=h._main=(a,b)=>(uc=h._main=Z.vc)(a,b),nc=h.__saudio_emsc_pull=a=>(nc=h.__saudio_emsc_pull=Z.wc)(a),mc=h.__sargs_add_kvp=(a,b)=>(mc=h.__sargs_add_kvp=Z.xc)(a,b),sc=h.__sfetch_emsc_head_response=(a,b)=>(sc=h.__sfetch_emsc_head_response=Z.yc)(a,b),oc=h.__sfetch_emsc_get_response=(a,b,c)=>(oc=h.__sfetch_emsc_get_response=Z.zc)(a,b,c),rc=h.__sfetch_emsc_failed_http_status=(a,b)=>
(rc=h.__sfetch_emsc_failed_http_status=Z.Ac)(a,b),pc=h.__sfetch_emsc_failed_buffer_too_small=a=>(pc=h.__sfetch_emsc_failed_buffer_too_small=Z.Bc)(a),qc=h.__sfetch_emsc_failed_other=a=>(qc=h.__sfetch_emsc_failed_other=Z.Cc)(a),dc=(a,b)=>(dc=Z.Ec)(a,b),$b=a=>($b=Z.Fc)(a),Xb=a=>(Xb=Z.Gc)(a),Zb=()=>(Zb=Z.Hc)();function vc(a=[]){var b=uc;a.unshift(fa);var c=a.length,d=Xb(4*(c+1)),e=d;a.forEach(f=>{w[e>>2]=Yb(f);e+=4});w[e>>2]=0;try{var g=b(c,d);Ha(g)}catch(f){Fa(f)}}
function wc(a=ea){function b(){h.calledRun=!0;if(!q){Z.lc();h.onRuntimeInitialized?.();h.noInitialRun||vc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();za.unshift(c)}ya(za)}}if(0<z)A=wc;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ba();ya(Aa);0<z?A=wc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();wc();
