var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,h="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,l="",ha,ia,ja;
if(fa){var fs=require("fs"),ka=require("path");l=h?ka.dirname(l)+"/":__dirname+"/";ha=(a,b)=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ja=a=>{a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a};ia=(a,b,c,d=!0)=>{a=la(a)?new URL(a):ka.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,k)=>{e?c(e):b(d?k.buffer:k)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof ma||a.context instanceof ma))throw a;});da=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(ea||h)h?l=self.location.href:"undefined"!=typeof document&&document.currentScript&&(l=document.currentScript.src),l=0!==l.indexOf("blob:")?l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},h&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,
!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};g.print||console.log.bind(console);var q=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var r;g.wasmBinary&&(r=g.wasmBinary);
"object"!=typeof WebAssembly&&na("no native wasm support detected");var oa,pa=!1,qa,t,ra,sa,w,ta,x,y;function ua(){var a=oa.buffer;g.HEAP8=qa=new Int8Array(a);g.HEAP16=ra=new Int16Array(a);g.HEAPU8=t=new Uint8Array(a);g.HEAPU16=sa=new Uint16Array(a);g.HEAP32=w=new Int32Array(a);g.HEAPU32=ta=new Uint32Array(a);g.HEAPF32=x=new Float32Array(a);g.HEAPF64=y=new Float64Array(a)}var va=[],wa=[],xa=[],ya=[],za=[];function Aa(){var a=g.preRun.shift();va.unshift(a)}var z=0,Ba=null,A=null;
function na(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";q(a);pa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ca=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),B;B="z9001.wasm";if(!Ca(B)){var Da=B;B=g.locateFile?g.locateFile(Da,l):l+Da}function Ea(a){if(a==B&&r)return new Uint8Array(r);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}
function Fa(a){if(!r&&(ea||h)){if("function"==typeof fetch&&!la(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ea(a));if(ia)return new Promise((b,c)=>{ia(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ea(a))}function Ga(a,b,c){return Fa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{q(`failed to asynchronously prepare wasm: ${d}`);na(d)})}
function Ha(a,b){var c=B;r||"function"!=typeof WebAssembly.instantiateStreaming||Ca(c)||la(c)||fa||"function"!=typeof fetch?Ga(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){q(`wasm streaming compile failed: ${e}`);q("falling back to ArrayBuffer instantiation");return Ga(c,a,b)}))}function ma(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ia=a=>{for(;0<a.length;)a.shift()(g)},Ja=g.noExitRuntime||!0,Ma=a=>{var b=Ka();a();La(b)},Na=0;function Oa(){for(var a=C.length-1;0<=a;--a)Pa(a);C=[];Qa=[]}var Qa=[];function Ra(){if(navigator.userActivation?navigator.userActivation.isActive:Na&&Sa.xc)for(var a=0;a<Qa.length;++a){var b=Qa[a];Qa.splice(a,1);--a;b.jd.apply(null,b.$c)}}var C=[];function Pa(a){var b=C[a];b.target.removeEventListener(b.oc,b.Vc,b.pc);C.splice(a,1)}
function D(a){function b(d){++Na;Sa=a;Ra();a.rc(d);Ra();--Na}if(!a.target)return-4;if(a.qc)a.Vc=b,a.target.addEventListener(a.oc,b,a.pc),C.push(a),Ta||(ya.push(Oa),Ta=!0);else for(var c=0;c<C.length;++c)C[c].target==a.target&&C[c].oc==a.oc&&Pa(c--);return 0}function Ua(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Ta,Sa,Va,Wa,Xa,Ya,Za,$a,ab,bb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,E=(a,b)=>{var c=t,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&bb)return bb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var k=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|k<<6|f:(e&7)<<18|k<<12|f<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
cb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],F=a=>{a=2<a?a?E(a):"":a;return cb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},db=a=>0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},eb=[],fb,G=a=>{var b=eb[a];b||(a>=eb.length&&(eb.length=a+1),eb[a]=b=fb.get(a));return b},H=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);if(55296<=f&&57343>=f){var m=a.charCodeAt(++k);f=65536+((f&
1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},gb=(a,b,c,d,e,k)=>{Va||(Va=I(256));a={target:F(a),oc:k,qc:d,rc:(f=event)=>{var m=f.target.id?f.target.id:"",n=Va;H(Ua(f.target),n+0,128);H(m,n+128,128);G(d)(e,n,b)&&f.preventDefault()},pc:c};return D(a)},hb=(a,b,c,d,e,k)=>{Wa||(Wa=I(176));
a={target:F(a),xc:!0,oc:k,qc:d,rc:f=>{var m=Wa;y[m>>3]=f.timeStamp;var n=m>>2;w[n+2]=f.location;w[n+3]=f.ctrlKey;w[n+4]=f.shiftKey;w[n+5]=f.altKey;w[n+6]=f.metaKey;w[n+7]=f.repeat;w[n+8]=f.charCode;w[n+9]=f.keyCode;w[n+10]=f.which;H(f.key||"",m+44,32);H(f.code||"",m+76,32);H(f.char||"",m+108,32);H(f.locale||"",m+140,32);G(d)(e,m,b)&&f.preventDefault()},pc:c};return D(a)},ib=(a,b,c)=>{y[a>>3]=b.timeStamp;a>>=2;w[a+2]=b.screenX;w[a+3]=b.screenY;w[a+4]=b.clientX;w[a+5]=b.clientY;w[a+6]=b.ctrlKey;w[a+
7]=b.shiftKey;w[a+8]=b.altKey;w[a+9]=b.metaKey;ra[2*a+20]=b.button;ra[2*a+21]=b.buttons;w[a+11]=b.movementX;w[a+12]=b.movementY;c=db(c);w[a+13]=b.clientX-c.left;w[a+14]=b.clientY-c.top},J=(a,b,c,d,e,k)=>{Xa||(Xa=I(72));a=F(a);return D({target:a,xc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,oc:k,qc:d,rc:(f=event)=>{ib(Xa,f,a);G(d)(e,Xa,b)&&f.preventDefault()},pc:c})},jb=(a,b,c,d,e)=>{Ya||(Ya=I(260));return D({target:a,oc:e,qc:d,rc:(k=event)=>{var f=Ya,m=document.pointerLockElement||document.uc||
document.Kc||document.Ic;w[f>>2]=!!m;var n=m&&m.id?m.id:"";H(Ua(m),f+4,128);H(n,f+132,128);G(d)(20,f,b)&&k.preventDefault()},pc:c})},kb=(a,b,c,d,e)=>D({target:a,oc:e,qc:d,rc:(k=event)=>{G(d)(38,0,b)&&k.preventDefault()},pc:c}),lb=(a,b,c,d)=>{Za||(Za=I(36));a=F(a);return D({target:a,oc:"resize",qc:d,rc:(e=event)=>{if(e.target==a){var k=document.body;if(k){var f=Za;w[f>>2]=e.detail;w[f+4>>2]=k.clientWidth;w[f+8>>2]=k.clientHeight;w[f+12>>2]=innerWidth;w[f+16>>2]=innerHeight;w[f+20>>2]=outerWidth;w[f+
24>>2]=outerHeight;w[f+28>>2]=pageXOffset;w[f+32>>2]=pageYOffset;G(d)(10,f,b)&&e.preventDefault()}}},pc:c})},mb=(a,b,c,d,e,k)=>{$a||($a=I(1696));a=F(a);return D({target:a,xc:"touchstart"==k||"touchend"==k,oc:k,qc:d,rc:f=>{for(var m,n={},p=f.touches,u=0;u<p.length;++u)m=p[u],m.Gc=m.Jc=0,n[m.identifier]=m;for(u=0;u<f.changedTouches.length;++u)m=f.changedTouches[u],m.Gc=1,n[m.identifier]=m;for(u=0;u<f.targetTouches.length;++u)n[f.targetTouches[u].identifier].Jc=1;p=$a;y[p>>3]=f.timeStamp;var v=p>>2;
w[v+3]=f.ctrlKey;w[v+4]=f.shiftKey;w[v+5]=f.altKey;w[v+6]=f.metaKey;v+=7;var pb=db(a),qb=0;for(u in n)if(m=n[u],w[v]=m.identifier,w[v+1]=m.screenX,w[v+2]=m.screenY,w[v+3]=m.clientX,w[v+4]=m.clientY,w[v+5]=m.pageX,w[v+6]=m.pageY,w[v+7]=m.Gc,w[v+8]=m.Jc,w[v+9]=m.clientX-pb.left,w[v+10]=m.clientY-pb.top,v+=13,31<++qb)break;w[p+8>>2]=qb;G(d)(e,p,b)&&f.preventDefault()},pc:c})},nb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=(c,d,e,k,f)=>b.drawElementsInstancedANGLE(c,d,e,k,f))},ob=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},rb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},sb=a=>{a.bd=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
tb=a=>{a.cd=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},ub=1,vb=[],K=[],wb=[],L=[],M=[],N=[],xb=[],yb=[],O=[],zb={},Ab=4;function P(a){Bb||(Bb=a)}
for(var Cb=a=>{for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b},Eb=(a,b)=>{a.uc||(a.uc=a.getContext,a.getContext=function(d,e){e=a.uc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Hc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Db(c,b):0},Db=(a,b)=>{var c=Cb(yb),d={handle:c,attributes:b,version:b.Hc,Bc:a};a.canvas&&(a.canvas.Zc=d);yb[c]=d;("undefined"==typeof b.Fc||b.Fc)&&Fb(d);return c},Fb=a=>{a||(a=Q);if(!a.Xc){a.Xc=!0;var b=a.Bc;nb(b);ob(b);rb(b);
sb(b);tb(b);2<=a.version&&(b.Ec=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Ec)b.Ec=b.getExtension("EXT_disjoint_timer_query");b.Yc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},Bb,Q,Gb=(a,b,c,d,e,k)=>{a={target:F(a),oc:k,qc:d,rc:(f=event)=>{G(d)(e,0,b)&&f.preventDefault()},pc:c};D(a)},Hb=(a,b,c,d)=>{ab||(ab=I(104));return D({target:a,xc:!0,oc:"wheel",qc:d,rc:(e=event)=>
{var k=ab;ib(k,e,a);y[k+72>>3]=e.deltaX;y[k+80>>3]=e.deltaY;y[k+88>>3]=e.deltaZ;w[k+96>>2]=e.deltaMode;G(d)(9,k,b)&&e.preventDefault()},pc:c})},Ib=["default","low-power","high-performance"],Jb=[],S=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=R[c](),f=k&&Cb(d);k?(k.name=f,d[f]=k):P(1282);w[b+4*e>>2]=f}},Kb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=R.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Q.version){P(1282);
return}c=2*(R.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>Q.version){P(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=R.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":P(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:P(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){P(1280);q("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:P(1280);q("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}w[b>>2]=c}else P(1281)},Lb=a=>{for(var b=
0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Mb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),T=a=>{a-=5120;return 0==a?qa:1==a?t:2==a?ra:4==a?w:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?ta:sa},Nb=(a,b,c,d,e)=>{a=T(a);var k=31-Math.clz32(a.BYTES_PER_ELEMENT),f=Ab;return a.subarray(e>>k,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<k)+f-1&-f)>>k)},U=a=>{var b=R.Uc;if(b){var c=b.wc[a];"number"==
typeof c&&(b.wc[a]=c=R.getUniformLocation(b,b.Sc[a]+(0<c?"["+c+"]":"")));return c}P(1282)},V=[],W=[],Ob=a=>{if(!Ja){if(g.onExit)g.onExit(a);pa=!0}da(a,new ma(a))},X=a=>{var b=Lb(a)+1,c=Pb(b);H(a,c,b);return c},R,Y=0;32>Y;++Y)Jb.push(Array(Y));var Qb=new Float32Array(288);for(Y=0;288>Y;++Y)V[Y]=Qb.subarray(0,Y+1);var Rb=new Int32Array(288);for(Y=0;288>Y;++Y)W[Y]=Rb.subarray(0,Y+1);
var ec={i:()=>{na("")},ga:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ha:(a,b,c)=>{a=F(a);if(!a)return-4;a=db(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},z:()=>performance.now(),ib:(a,b,c)=>t.copyWithin(a,b,b+c),$a:(a,b)=>{function c(d){G(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},hb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+
(65536-d%65536)%65536)-oa.buffer.byteLength+65535)/65536;try{oa.grow(e);ua();var k=1;break a}catch(f){}k=void 0}if(k)return!0}return!1},Q:(a,b,c,d)=>gb(a,b,c,d,12,"blur"),fa:(a,b,c)=>{a=F(a);if(!a)return-4;a.width=b;a.height=c;return 0},R:(a,b,c,d)=>gb(a,b,c,d,13,"focus"),_:(a,b,c,d)=>hb(a,b,c,d,2,"keydown"),Y:(a,b,c,d)=>hb(a,b,c,d,1,"keypress"),Z:(a,b,c,d)=>hb(a,b,c,d,3,"keyup"),ea:(a,b,c,d)=>J(a,b,c,d,5,"mousedown"),ba:(a,b,c,d)=>J(a,b,c,d,33,"mouseenter"),aa:(a,b,c,d)=>J(a,b,c,d,34,"mouseleave"),
ca:(a,b,c,d)=>J(a,b,c,d,8,"mousemove"),da:(a,b,c,d)=>J(a,b,c,d,6,"mouseup"),T:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.uc||document.body.Kc||document.body.Ic))return-1;a=F(a);if(!a)return-4;jb(a,b,c,d,"mozpointerlockchange");jb(a,b,c,d,"webkitpointerlockchange");jb(a,b,c,d,"mspointerlockchange");return jb(a,b,c,d,"pointerlockchange")},S:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.uc||document.body.Kc||document.body.Ic))return-1;
a=F(a);if(!a)return-4;kb(a,b,c,d,"mozpointerlockerror");kb(a,b,c,d,"webkitpointerlockerror");kb(a,b,c,d,"mspointerlockerror");return kb(a,b,c,d,"pointerlockerror")},bb:(a,b,c,d)=>lb(a,b,c,d),U:(a,b,c,d)=>mb(a,b,c,d,25,"touchcancel"),V:(a,b,c,d)=>mb(a,b,c,d,23,"touchend"),W:(a,b,c,d)=>mb(a,b,c,d,24,"touchmove"),X:(a,b,c,d)=>mb(a,b,c,d,22,"touchstart"),P:(a,b,c,d)=>{Gb(a,b,c,d,31,"webglcontextlost");return 0},O:(a,b,c,d)=>{Gb(a,b,c,d,32,"webglcontextrestored");return 0},$:(a,b,c,d)=>(a=F(a))?"undefined"!=
typeof a.onwheel?Hb(a,b,c,d):-1:-4,Za:(a,b)=>{b>>=2;b={alpha:!!w[b],depth:!!w[b+1],stencil:!!w[b+2],antialias:!!w[b+3],premultipliedAlpha:!!w[b+4],preserveDrawingBuffer:!!w[b+5],powerPreference:Ib[w[b+6]],failIfMajorPerformanceCaveat:!!w[b+7],Hc:w[b+8],dd:w[b+9],Fc:w[b+10],Wc:w[b+11],ed:w[b+12],gd:w[b+13]};a=F(a);return!a||b.Wc?0:Eb(a,b)},Xa:(a,b)=>{a=yb[a];b=b?E(b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&nb(R);"OES_vertex_array_object"==b&&ob(R);"WEBGL_draw_buffers"==
b&&rb(R);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&sb(R);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&tb(R);"WEBGL_multi_draw"==b&&(R.Yc=R.getExtension("WEBGL_multi_draw"));return!!a.Bc.getExtension(b)},_a:a=>{a>>=2;for(var b=0;14>b;++b)w[a+b]=0;w[a]=w[a+1]=w[a+3]=w[a+4]=w[a+8]=w[a+10]=1},Ya:a=>{Q=yb[a];g.ad=R=Q&&Q.Bc;return!a||R?0:-5},j:function(a){R.activeTexture(a)},wa:(a,b)=>{R.attachShader(K[a],N[b])},a:(a,b)=>{35051==a?R.Dc=b:35052==a&&(R.tc=b);R.bindBuffer(a,vb[b])},
h:(a,b)=>{R.bindFramebuffer(a,wb[b])},Ga:(a,b)=>{R.bindRenderbuffer(a,L[b])},k:(a,b)=>{R.bindSampler(a,O[b])},c:(a,b)=>{R.bindTexture(a,M[b])},K:a=>{R.bindVertexArray(xb[a])},G:function(a,b,c,d){R.blendColor(a,b,c,d)},H:function(a,b){R.blendEquationSeparate(a,b)},I:function(a,b,c,d){R.blendFuncSeparate(a,b,c,d)},mb:function(a,b,c,d,e,k,f,m,n,p){R.blitFramebuffer(a,b,c,d,e,k,f,m,n,p)},Ja:(a,b,c,d)=>{2<=Q.version?c&&b?R.bufferData(a,t,d,c,b):R.bufferData(a,b,d):R.bufferData(a,c?t.subarray(c,c+b):b,
d)},o:(a,b,c,d)=>{2<=Q.version?c&&R.bufferSubData(a,b,t,d,c):R.bufferSubData(a,b,t.subarray(d,d+c))},qa:function(a){return R.checkFramebufferStatus(a)},Hb:function(a,b,c,d){R.clearBufferfi(a,b,c,d)},na:(a,b,c)=>{R.clearBufferfv(a,b,x,c>>2)},Gb:(a,b,c)=>{R.clearBufferiv(a,b,w,c>>2)},m:(a,b,c,d)=>{R.colorMask(!!a,!!b,!!c,!!d)},Kb:a=>{R.compileShader(N[a])},Ca:(a,b,c,d,e,k,f,m)=>{2<=Q.version?R.tc||!f?R.compressedTexImage2D(a,b,c,d,e,k,f,m):R.compressedTexImage2D(a,b,c,d,e,k,t,m,f):R.compressedTexImage2D(a,
b,c,d,e,k,m?t.subarray(m,m+f):null)},Aa:(a,b,c,d,e,k,f,m,n)=>{R.tc?R.compressedTexImage3D(a,b,c,d,e,k,f,m,n):R.compressedTexImage3D(a,b,c,d,e,k,f,t,n,m)},Qb:()=>{var a=Cb(K),b=R.createProgram();b.name=a;b.Ac=b.yc=b.zc=0;b.Cc=1;K[a]=b;return a},Nb:a=>{var b=Cb(N);N[b]=R.createShader(a);return b},D:function(a){R.cullFace(a)},Ta:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=vb[d];e&&(R.deleteBuffer(e),e.name=0,vb[d]=null,d==R.Dc&&(R.Dc=0),d==R.tc&&(R.tc=0))}},e:(a,b)=>{for(var c=0;c<a;++c){var d=
w[b+4*c>>2],e=wb[d];e&&(R.deleteFramebuffer(e),e.name=0,wb[d]=null)}},x:a=>{if(a){var b=K[a];b?(R.deleteProgram(b),b.name=0,K[a]=null):P(1281)}},M:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=L[d];e&&(R.deleteRenderbuffer(e),e.name=0,L[d]=null)}},L:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=O[d];e&&(R.deleteSampler(e),e.name=0,O[d]=null)}},C:a=>{if(a){var b=N[a];b?(R.deleteShader(b),N[a]=null):P(1281)}},N:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=M[d];e&&(R.deleteTexture(e),e.name=
0,M[d]=null)}},Ra:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2];R.deleteVertexArray(xb[d]);xb[d]=null}},w:function(a){R.depthFunc(a)},v:a=>{R.depthMask(!!a)},d:function(a){R.disable(a)},J:a=>{R.disableVertexAttribArray(a)},ob:(a,b,c)=>{R.drawArrays(a,b,c)},pb:(a,b,c,d)=>{R.drawArraysInstanced(a,b,c,d)},pa:(a,b)=>{for(var c=Jb[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];R.drawBuffers(c)},qb:(a,b,c,d)=>{R.drawElements(a,b,c,d)},rb:(a,b,c,d,e)=>{R.drawElementsInstanced(a,b,c,d,e)},g:function(a){R.enable(a)},Cb:a=>
{R.enableVertexAttribArray(a)},ra:(a,b,c,d)=>{R.framebufferRenderbuffer(a,b,c,L[d])},l:(a,b,c,d,e)=>{R.framebufferTexture2D(a,b,c,M[d],e)},A:(a,b,c,d,e)=>{R.framebufferTextureLayer(a,b,M[c],d,e)},E:function(a){R.frontFace(a)},Ka:(a,b)=>{S(a,b,"createBuffer",vb)},sa:(a,b)=>{S(a,b,"createFramebuffer",wb)},Ia:(a,b)=>{S(a,b,"createRenderbuffer",L)},ya:(a,b)=>{S(a,b,"createSampler",O)},Ea:(a,b)=>{S(a,b,"createTexture",M)},Qa:function(a,b){S(a,b,"createVertexArray",xb)},Ib:(a,b)=>R.getAttribLocation(K[a],
b?E(b):""),b:(a,b)=>{Kb(a,b)},Ob:(a,b,c,d)=>{a=R.getProgramInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?H(a,d,b):0;c&&(w[c>>2]=b)},va:(a,b,c)=>{if(c)if(a>=ub)P(1281);else if(a=K[a],35716==b)a=R.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.Ac)for(b=0;b<R.getProgramParameter(a,35718);++b)a.Ac=Math.max(a.Ac,R.getActiveUniform(a,b).name.length+1);w[c>>2]=a.Ac}else if(35722==b){if(!a.yc)for(b=0;b<R.getProgramParameter(a,35721);++b)a.yc=Math.max(a.yc,
R.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.yc}else if(35381==b){if(!a.zc)for(b=0;b<R.getProgramParameter(a,35382);++b)a.zc=Math.max(a.zc,R.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.zc}else w[c>>2]=R.getProgramParameter(a,b);else P(1281)},Jb:(a,b,c,d)=>{a=R.getShaderInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?H(a,d,b):0;c&&(w[c>>2]=b)},ta:(a,b,c)=>{c?35716==b?(a=R.getShaderInfoLog(N[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=R.getShaderSource(N[a]),
w[c>>2]=a?a.length+1:0):w[c>>2]=R.getShaderParameter(N[a],b):P(1281)},Ua:(a,b)=>{if(2>Q.version)return P(1282),0;var c=zb[a];if(c)return 0>b||b>=c.length?(P(1281),0):c[b];switch(a){case 7939:return c=R.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){var e=Lb(d)+1,k=I(e);k&&H(d,k,e);return k}),c=zb[a]=c,0>b||b>=c.length?(P(1281),0):c[b];default:return P(1280),0}},r:(a,b)=>{b=b?E(b):"";if(a=K[a]){var c=a,d=c.wc,e=c.Tc,k;if(!d)for(c.wc=d={},c.Sc={},k=0;k<
R.getProgramParameter(c,35718);++k){var f=R.getActiveUniform(c,k);var m=f.name;f=f.size;var n=Mb(m);n=0<n?m.slice(0,n):m;var p=c.Cc;c.Cc+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.Sc[p++]=n}c=a.wc;d=0;e=b;k=Mb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.Tc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||R.getUniformLocation(a,b)))return d}else P(1281);return-1},lb:(a,b,c)=>{for(var d=Jb[b],e=0;e<b;e++)d[e]=w[c+4*e>>2];R.invalidateFramebuffer(a,d)},Pb:a=>{a=K[a];R.linkProgram(a);a.wc=0;a.Tc={}},Oa:(a,
b)=>{3317==a&&(Ab=b);R.pixelStorei(a,b)},F:function(a,b){R.polygonOffset(a,b)},nb:function(a){R.readBuffer(a)},Fa:function(a,b,c,d,e){R.renderbufferStorageMultisample(a,b,c,d,e)},xa:(a,b,c)=>{R.samplerParameterf(O[a],b,c)},f:(a,b,c)=>{R.samplerParameteri(O[a],b,c)},oa:function(a,b,c,d){R.scissor(a,b,c,d)},Lb:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var f=d?w[d+4*k>>2]:-1,m=w[c+4*k>>2];f=m?E(m,0>f?void 0:f):"";e+=f}R.shaderSource(N[a],e)},Na:function(a,b,c){R.stencilFunc(a,b,c)},ma:function(a,b,c,d){R.stencilFuncSeparate(a,
b,c,d)},u:function(a){R.stencilMask(a)},Ma:function(a,b,c){R.stencilOp(a,b,c)},la:function(a,b,c,d){R.stencilOpSeparate(a,b,c,d)},Ba:(a,b,c,d,e,k,f,m,n)=>{if(2<=Q.version)if(R.tc)R.texImage2D(a,b,c,d,e,k,f,m,n);else if(n){var p=T(m);R.texImage2D(a,b,c,d,e,k,f,m,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else R.texImage2D(a,b,c,d,e,k,f,m,null);else R.texImage2D(a,b,c,d,e,k,f,m,n?Nb(m,f,d,e,n):null)},za:(a,b,c,d,e,k,f,m,n,p)=>{if(R.tc)R.texImage3D(a,b,c,d,e,k,f,m,n,p);else if(p){var u=T(n);R.texImage3D(a,
b,c,d,e,k,f,m,n,u,p>>31-Math.clz32(u.BYTES_PER_ELEMENT))}else R.texImage3D(a,b,c,d,e,k,f,m,n,null)},Da:function(a,b,c){R.texParameteri(a,b,c)},kb:(a,b,c,d,e,k,f,m,n)=>{if(2<=Q.version)if(R.tc)R.texSubImage2D(a,b,c,d,e,k,f,m,n);else if(n){var p=T(m);R.texSubImage2D(a,b,c,d,e,k,f,m,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else R.texSubImage2D(a,b,c,d,e,k,f,m,null);else p=null,n&&(p=Nb(m,f,e,k,n)),R.texSubImage2D(a,b,c,d,e,k,f,m,p)},jb:(a,b,c,d,e,k,f,m,n,p,u)=>{if(R.tc)R.texSubImage3D(a,b,c,d,e,k,f,
m,n,p,u);else if(u){var v=T(p);R.texSubImage3D(a,b,c,d,e,k,f,m,n,p,v,u>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else R.texSubImage3D(a,b,c,d,e,k,f,m,n,p,null)},Bb:(a,b,c)=>{if(2<=Q.version)b&&R.uniform1fv(U(a),x,c>>2,b);else{if(288>=b)for(var d=V[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);R.uniform1fv(U(a),d)}},ua:(a,b)=>{R.uniform1i(U(a),b)},xb:(a,b,c)=>{if(2<=Q.version)b&&R.uniform1iv(U(a),w,c>>2,b);else{if(288>=b)for(var d=W[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>
2,c+4*b>>2);R.uniform1iv(U(a),d)}},Ab:(a,b,c)=>{if(2<=Q.version)b&&R.uniform2fv(U(a),x,c>>2,2*b);else{if(144>=b)for(var d=V[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);R.uniform2fv(U(a),d)}},wb:(a,b,c)=>{if(2<=Q.version)b&&R.uniform2iv(U(a),w,c>>2,2*b);else{if(144>=b)for(var d=W[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);R.uniform2iv(U(a),d)}},zb:(a,b,c)=>{if(2<=Q.version)b&&R.uniform3fv(U(a),x,
c>>2,3*b);else{if(96>=b)for(var d=V[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);R.uniform3fv(U(a),d)}},vb:(a,b,c)=>{if(2<=Q.version)b&&R.uniform3iv(U(a),w,c>>2,3*b);else{if(96>=b)for(var d=W[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);R.uniform3iv(U(a),d)}},yb:(a,b,c)=>{if(2<=Q.version)b&&R.uniform4fv(U(a),x,c>>2,4*b);else{if(72>=b){var d=V[4*b-1],e=
x;c>>=2;for(var k=0;k<4*b;k+=4){var f=c+k;d[k]=e[f];d[k+1]=e[f+1];d[k+2]=e[f+2];d[k+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);R.uniform4fv(U(a),d)}},ub:(a,b,c)=>{if(2<=Q.version)b&&R.uniform4iv(U(a),w,c>>2,4*b);else{if(72>=b)for(var d=W[4*b-1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);R.uniform4iv(U(a),d)}},sb:(a,b,c,d)=>{if(2<=Q.version)b&&R.uniformMatrix4fv(U(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=
V[16*b-1],k=x;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=k[m];e[f+1]=k[m+1];e[f+2]=k[m+2];e[f+3]=k[m+3];e[f+4]=k[m+4];e[f+5]=k[m+5];e[f+6]=k[m+6];e[f+7]=k[m+7];e[f+8]=k[m+8];e[f+9]=k[m+9];e[f+10]=k[m+10];e[f+11]=k[m+11];e[f+12]=k[m+12];e[f+13]=k[m+13];e[f+14]=k[m+14];e[f+15]=k[m+15]}}else e=x.subarray(d>>2,d+64*b>>2);R.uniformMatrix4fv(U(a),!!c,e)}},n:a=>{a=K[a];R.useProgram(a);R.Uc=a},Db:(a,b)=>{R.vertexAttribDivisor(a,b)},Fb:(a,b,c,d,e,k)=>{R.vertexAttribPointer(a,b,c,!!d,e,k)},q:function(a,
b,c,d){R.viewport(a,b,c,d)},ab:function(){g.Lc=a=>{0!=Sb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Lc)},Va:function(){g.Rc=a=>{const b=a.clipboardData.getData("text");Ma(()=>{const c=X(b);Tb(c)})};window.addEventListener("paste",g.Rc)},Pa:function(a){g.hd=[];a=a?E(a):"";a=document.getElementById(a);g.Mc=b=>{b.stopPropagation();b.preventDefault()};g.Nc=b=>{b.stopPropagation();b.preventDefault()};g.Oc=b=>{b.stopPropagation();b.preventDefault()};g.Pc=b=>{b.stopPropagation();
b.preventDefault();const c=b.dataTransfer.files;g.Qc=c;Ub(c.length);for(let e=0;e<c.length;e++)Ma(()=>{const k=X(c[e].name);Vb(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Wb(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.Mc,!1);a.addEventListener("dragleave",g.Nc,!1);a.addEventListener("dragover",g.Oc,!1);a.addEventListener("drop",g.Pc,!1)},Eb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},t:function(){const a=
document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Xb()});document.body.append(a)},La:function(a){const b=g.Qc;return 0>a||a>=b.length?0:b[a].size},Ha:function(a,b,c,d,e){const k=new FileReader;k.onload=f=>{f=f.target.result;f.byteLength>d?Yb(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(f),c),Yb(a,1,0,b,f.byteLength,c,d,e))};k.onerror=()=>{Yb(a,0,2,b,0,c,d,e)};k.readAsArrayBuffer(g.Qc[a])},s:function(){document.getElementById("_sokol_app_input_element").focus()},
Mb:function(a){a=a?E(a):"";g.vc=document.getElementById(a);g.vc||console.log("sokol_app.h: invalid target:"+a);g.vc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Wa:function(){window.removeEventListener("beforeunload",g.Lc)},Sa:function(){window.removeEventListener("paste",g.Rc)},Rb:function(a){a=a?E(a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.Mc);a.removeEventListener("dragleave",g.Nc);a.removeEventListener("dragover",g.Oc);
a.removeEventListener("drop",g.Pc)},B:function(){g.vc&&g.vc.requestPointerLock&&g.vc.requestPointerLock()},tb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(t.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},p:function(){document.getElementById("_sokol_app_input_element").blur()},cb:function(){const a=
(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];Ma(()=>{const e=X(c),k=X(d);Zb(e,k)})}},eb:function(){return g.sc?g.sc.bufferSize:0},gb:function(a,b,c){g.nc=null;g.sc=null;"undefined"!==typeof AudioContext?g.nc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.nc=null,console.log("sokol_audio.h: no WebAudio support"));return g.nc?(console.log("sokol_audio.h: sample rate ",g.nc.sampleRate),g.sc=g.nc.createScriptProcessor(c,
0,b),g.sc.onaudioprocess=d=>{const e=d.outputBuffer.length,k=$b(e);if(k){const f=d.outputBuffer.numberOfChannels;for(let m=0;m<f;m++){const n=d.outputBuffer.getChannelData(m);for(let p=0;p<e;p++)n[p]=x[(k>>2)+(f*p+m)]}}},g.sc.connect(g.nc.destination),a=()=>{g.nc&&"suspended"===g.nc.state&&g.nc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},fb:function(){return g.nc?g.nc.sampleRate:0},
ka:function(){const a=g.nc;null!==a&&(g.sc&&g.sc.disconnect(),a.close(),g.nc=null,g.sc=null)},db:function(){if(g.nc)return"suspended"===g.nc.state?1:0},y:function(a,b,c,d,e,k){b=b?E(b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const m=0<d;m&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!m){const n=new Uint8Array(f.response),p=n.length;p<=k?(t.set(n,e),ac(a,d,
p)):bc(a)}else cc(a,f.status)};f.send()},ja:function(a,b){b=b?E(b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");dc(a,d)}else cc(a,c.status)};c.send()},ia:function(a,b){b=b?E(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;oa=Z.Sb;ua();fb=Z.jc;
wa.unshift(Z.Tb);z--;g.monitorRunDependencies&&g.monitorRunDependencies(z);0==z&&(null!==Ba&&(clearInterval(Ba),Ba=null),A&&(c=A,A=null,c()));return Z}var b={a:ec};z++;g.monitorRunDependencies&&g.monitorRunDependencies(z);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return q(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ha(b,function(c){a(c.instance)});return{}}();g._fs_emsc_alloc=a=>(g._fs_emsc_alloc=Z.Ub)(a);var I=a=>(I=Z.Vb)(a);
g._fs_emsc_load_snapshot_callback=(a,b,c)=>(g._fs_emsc_load_snapshot_callback=Z.Wb)(a,b,c);
var Xb=g.__sapp_emsc_notify_keyboard_hidden=()=>(Xb=g.__sapp_emsc_notify_keyboard_hidden=Z.Xb)(),Tb=g.__sapp_emsc_onpaste=a=>(Tb=g.__sapp_emsc_onpaste=Z.Yb)(a),Sb=g.__sapp_html5_get_ask_leave_site=()=>(Sb=g.__sapp_html5_get_ask_leave_site=Z.Zb)(),Ub=g.__sapp_emsc_begin_drop=a=>(Ub=g.__sapp_emsc_begin_drop=Z._b)(a),Vb=g.__sapp_emsc_drop=(a,b)=>(Vb=g.__sapp_emsc_drop=Z.$b)(a,b),Wb=g.__sapp_emsc_end_drop=(a,b,c)=>(Wb=g.__sapp_emsc_end_drop=Z.ac)(a,b,c),Yb=g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,k,f,
m)=>(Yb=g.__sapp_emsc_invoke_fetch_cb=Z.bc)(a,b,c,d,e,k,f,m),fc=g._main=(a,b)=>(fc=g._main=Z.cc)(a,b),$b=g.__saudio_emsc_pull=a=>($b=g.__saudio_emsc_pull=Z.dc)(a),Zb=g.__sargs_add_kvp=(a,b)=>(Zb=g.__sargs_add_kvp=Z.ec)(a,b),dc=g.__sfetch_emsc_head_response=(a,b)=>(dc=g.__sfetch_emsc_head_response=Z.fc)(a,b),ac=g.__sfetch_emsc_get_response=(a,b,c)=>(ac=g.__sfetch_emsc_get_response=Z.gc)(a,b,c),cc=g.__sfetch_emsc_failed_http_status=(a,b)=>(cc=g.__sfetch_emsc_failed_http_status=Z.hc)(a,b),bc=g.__sfetch_emsc_failed_buffer_too_small=
a=>(bc=g.__sfetch_emsc_failed_buffer_too_small=Z.ic)(a),Ka=()=>(Ka=Z.kc)(),La=a=>(La=Z.lc)(a),Pb=a=>(Pb=Z.mc)(a);g.___start_em_js=50480;g.___stop_em_js=63530;var gc;A=function hc(){gc||ic();gc||(A=hc)};function jc(a=[]){var b=fc;a.unshift(ca);var c=a.length,d=Pb(4*(c+1)),e=d;a.forEach(f=>{ta[e>>2]=X(f);e+=4});ta[e>>2]=0;try{var k=b(c,d);Ob(k)}catch(f){f instanceof ma||"unwind"==f||da(1,f)}}
function ic(){var a=ba;function b(){if(!gc&&(gc=!0,g.calledRun=!0,!pa)){Ia(wa);Ia(xa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();kc&&jc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();za.unshift(c)}Ia(za)}}if(!(0<z)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Aa();Ia(va);0<z||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var kc=!0;g.noInitialRun&&(kc=!1);ic();
