var h;h||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer",da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;typeof __filename!="undefined"?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.length>1&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);typeof module!="undefined"&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{e.status==200||e.status==0&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),l=console.error.bind(console),m=!1,na,la=a=>a.startsWith("file://");
function oa(){if(!p?.buffer?.resizable){var a=pa.buffer;p=new Int8Array(a);qa=new Int16Array(a);t=new Uint8Array(a);ra=new Uint16Array(a);u=new Int32Array(a);v=new Uint32Array(a);w=new Float32Array(a);x=new Float64Array(a)}}function sa(){var a=h.preRun;a&&(typeof a=="function"&&(a=[a]),ta.push(...a));for(a=ta;a.length>0;)a.shift()(h)}function ua(){var a=h.postRun;a&&(typeof a=="function"&&(a=[a]),va.push(...a));for(a=va;a.length>0;)a.shift()(h)}
function wa(a){h.onAbort?.(a);a=`Aborted(${a})`;l(a);m=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var xa;async function ya(a){try{var b=await ja(a);return new Uint8Array(b)}catch{}if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function za(a,b){try{var c=await ya(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),wa(d)}}
async function Aa(a){var b=xa;if(!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return za(b,a)}class Ba{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var p,va=[],ta=[],Ca=!0,Da=globalThis.TextDecoder&&new TextDecoder,y=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(d-b>16&&a.buffer&&Da)return Da.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=(e&240)==224?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},
t,z=(a,b)=>a?y(t,a,b):"",Ea=0,Fa=[0,31,60,91,121,152,182,213,244,274,305,335],Ga=[0,31,59,90,120,151,181,212,243,273,304,334],u,A={},Ha=a=>{a instanceof Ba||a=="unwind"||fa(1,a)},Ia=a=>{na=a;Ca||Ea>0||(h.onExit?.(a),m=!0);fa(a,new Ba(a))},Ja=()=>{if(!(Ca||Ea>0))try{var a=na;na=a;Ia(a)}catch(b){Ha(b)}},Ka=a=>{if(!m)try{a()}catch(b){Ha(b)}finally{Ja()}},B=(a,b,c)=>{var d=t;if(!(c>0))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(b>=c)break;d[b++]=g}else if(g<=
2047){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(g<=65535){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},v,Pa=(a,b)=>{La=a;Ma=b;if(C)if(a==0)F=function(){setTimeout(G,Math.max(0,Na+b-performance.now())|0)};else if(a==1)F=function(){Oa(G)};else{if(!H)if(globalThis.scheduler)H=scheduler.postTask.bind(scheduler);else if(globalThis.setImmediate)H=setImmediate;
else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);H=d=>{c.push(d);ba?postMessage("setimmediate"):postMessage("setimmediate","*")}}F=function(){H(G)}}},Ya=(a,b,c,d,e)=>{function f(){return g<Qa?(Ja(),!1):!0}C=a;Ra=d;var g=Qa;G=function(){if(!m)if(Sa.length>0){var k=Sa.shift();k.be(k.Qd);if(Ta){var n=Ta,q=n%1==0?n-1:Math.floor(n);Ta=k.Td?q:(8*n+(q+.5))/9}h.setStatus&&(k=h.statusMessage||"Please wait...",n=Ta??0,q=Ua.Zd??0,n?n<q?h.setStatus("{message} ({expected - remaining}/{expected})"):
h.setStatus(k):h.setStatus(""));f()&&setTimeout(G,0)}else if(f())if(Va=Va+1|0,La==1&&Ma>1&&Va%Ma!=0)F();else{La==0&&(Na=performance.now());a:if(!m){for(k of Wa)if(k()===!1)break a;Ka(a);for(n of Xa)n()}f()&&F()}};e||(b>0?Pa(0,1E3/b):Pa(1,1),F());if(c)throw"unwind";},C=null,F=null,Qa=0,Ra=0,La=0,Ma=0,Va=0,Sa=[],Wa=[],Xa=[];function Za(){F&&(F=null,Qa++)}var $a=0;
function Oa(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if($a)for(;b+2>=$a;)$a+=1E3/60;else $a=b+1E3/60;setTimeout(a,Math.max($a-b,0))}}var Ua={},Na,G,H,Ta,ab=[0,globalThis.document??0,globalThis.window??0],I=a=>{a=a>2?a?y(t,a):"":a;return ab[a]||globalThis.document?.querySelector(a)},bb=a=>ab.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},x,cb=[],J=a=>{var b=cb[a];b||(cb[a]=b=db.get(a));return b};
function eb(a){var b=K.Oc[a];b.target.removeEventListener(b.Nc,b.wd,b.Rc);K.Oc.splice(a,1)}function fb(){if(navigator.userActivation?navigator.userActivation.isActive:K.hd&&K.Kd.dd){var a=K.Wc;K.Wc=[];for(var b of a)b.ld(...b.sd)}}function L(a){if(!a.target)return-4;if(a.Pc)a.wd=function(c){++K.hd;K.Kd=a;fb();a.Tc(c);fb();--K.hd},a.target.addEventListener(a.Nc,a.wd,a.Rc),K.Oc.push(a);else for(var b=0;b<K.Oc.length;++b)K.Oc[b].target==a.target&&K.Oc[b].Nc==a.Nc&&eb(b--);return 0}
function gb(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var K={Rd:0,ce:0,jd:0,bd:0,pd:0,nd:0,ed:0,Xd:0,ge:0,Wd:0,gd:0,kd:0,pe:0,md:0,ie(){for(;K.Oc.length;)eb(K.Oc.length-1);K.Wc=[]},hd:0,Wc:[],Vd(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var k=0;k<f.length;k++)if(f[k]!=g[k])return!1;return!0}for(var e of K.Wc)if(e.ld==a&&d(e.sd,c))return;K.Wc.push({ld:a,Ad:b,sd:c});K.Wc.sort((f,g)=>f.Ad-g.Ad)},ke(a){K.Wc=K.Wc.filter(b=>b.ld!=a)},Oc:[],je:(a,b)=>{for(var c=0;c<K.Oc.length;++c)K.Oc[c].target!=a||b&&b!=K.Oc[c].Nc||eb(c--)},le(a){var b=!1;
for(let c=0;c<K.Oc.length;++c){let d=K.Oc[c];d.target===a.target&&d.Qc===a.Qc&&d.Pc===a.Pc&&d.Sc===a.Sc&&(eb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled??document.webkitFullscreenEnabled}},hb=(a,b,c,d,e,f)=>{K.ed||(K.ed=M(256));a={target:I(a),Nc:f,Qc:e,Sc:b,Pc:d,Tc:g=>{var k=g.target.id??"",n=K.ed;B(gb(g.target),n+0,128);B(k,n+128,128);J(d)(e,n,b)&&g.preventDefault()},Rc:c};return L(a)},ib=(a,b,c,d,e)=>{K.gd||(K.gd=M(276));return L({target:a,Nc:e,Qc:19,Sc:b,Pc:d,
Tc:f=>{var g=K.gd,k=document.fullscreenElement??document.webkitFullscreenElement,n=!!k;p[g]=n;p[g+1]=K.fullscreenEnabled();var q=n?k:K.Od,r=q?.id??"";B(gb(q),g+2,128);B(r,g+130,128);u[g+260>>2]=q?.clientWidth??0;u[g+264>>2]=q?.clientHeight??0;u[g+268>>2]=screen.width;u[g+272>>2]=screen.height;n&&(K.Od=k);J(d)(19,g,b)&&f.preventDefault()},Rc:c})},jb=(a,b,c,d,e,f)=>{K.jd||(K.jd=M(160));a={target:I(a),Nc:f,Qc:e,Sc:b,Pc:d,Tc:g=>{var k=K.jd;x[k>>3]=g.timeStamp;var n=k>>2;u[n+2]=g.location;p[k+12]=g.ctrlKey;
p[k+13]=g.shiftKey;p[k+14]=g.altKey;p[k+15]=g.metaKey;p[k+16]=g.repeat;u[n+5]=g.charCode;u[n+6]=g.keyCode;u[n+7]=g.which;B(g.key??"",k+32,32);B(g.code??"",k+64,32);B(g.char??"",k+96,32);B(g.locale??"",k+128,32);J(d)(e,k,b)&&g.preventDefault()},Rc:c};return L(a)},qa,kb=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;p[a+24]=b.ctrlKey;p[a+25]=b.shiftKey;p[a+26]=b.altKey;p[a+27]=b.metaKey;qa[d*2+14]=b.button;qa[d*2+15]=b.buttons;u[d+8]=b.movementX;
u[d+9]=b.movementY;a=bb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},lb=(a,b,c,d,e,f)=>{K.bd||(K.bd=M(64));a=I(a);return L({target:a,dd:f!="mousemove"&&f!="mouseenter"&&f!="mouseleave",Nc:f,Qc:e,Sc:b,Pc:d,Tc:g=>{kb(K.bd,g,a);J(d)(e,K.bd,b)&&g.preventDefault()},Rc:c})},mb=(a,b,c,d)=>{K.kd||(K.kd=M(257));return L({target:a,Nc:"pointerlockchange",Qc:20,Sc:b,Pc:d,Tc:e=>{var f=K.kd,g=document.pointerLockElement;p[f]=!!g;var k=g?.id??"";B(gb(g),f+1,128);B(k,f+129,128);J(d)(20,f,b)&&e.preventDefault()},
Rc:c})},nb=(a,b,c,d)=>L({target:a,Nc:"pointerlockerror",Qc:38,Sc:b,Pc:d,Tc:e=>{J(d)(38,0,b)&&e.preventDefault()},Rc:c}),ob=(a,b,c,d)=>{K.nd||(K.nd=M(36));a=I(a);return L({target:a,Nc:"resize",Qc:10,Sc:b,Pc:d,Tc:e=>{if(e.target==a){var f=document.body;if(f){var g=K.nd;u[g>>2]=0;u[g+4>>2]=f.clientWidth;u[g+8>>2]=f.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;J(d)(10,g,b)&&e.preventDefault()}}},
Rc:c})},pb=(a,b,c,d,e,f)=>{K.md||(K.md=M(1552));a=I(a);return L({target:a,dd:f=="touchstart"||f=="touchend",Nc:f,Qc:e,Sc:b,Pc:d,Tc:g=>{var k={},n=g.touches;for(var q of n)q.xd=q.zd=0,k[q.identifier]=q;for(var r of g.changedTouches)r.xd=1,k[r.identifier]=r;for(var D of g.targetTouches)k[D.identifier].zd=1;n=K.md;x[n>>3]=g.timeStamp;p[n+12]=g.ctrlKey;p[n+13]=g.shiftKey;p[n+14]=g.altKey;p[n+15]=g.metaKey;q=n+16;r=bb(a);D=0;for(let E of Object.values(k))if(k=q>>2,u[k]=E.identifier,u[k+1]=E.screenX,u[k+
2]=E.screenY,u[k+3]=E.clientX,u[k+4]=E.clientY,u[k+5]=E.pageX,u[k+6]=E.pageY,p[q+28]=E.xd,p[q+29]=E.zd,u[k+8]=E.clientX-(r.left|0),u[k+9]=E.clientY-(r.top|0),q+=48,++D>31)break;u[n+8>>2]=D;J(d)(e,n,b)&&g.preventDefault()},Rc:c})},N,qb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},rb=
a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},sb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},tb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},ub=1,O=[],P=[],vb=[],wb=[],Q=[],R=[],xb=[],yb=[],S=[],zb={},Ab=4,Bb=0,Cb=a=>{for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=N[c](),g=f&&Cb(d);f?(f.name=g,d[g]=f):T||=1282;u[b+e*4>>2]=g}},Eb=(a,b)=>{a.rd||(a.rd=a.getContext,a.getContext=function(d,e){e=a.rd(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=b.yd>1?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Db(c,b):0},Db=(a,b)=>{var c=Cb(yb),d={handle:c,attributes:b,version:b.yd,qd:a};a.canvas&&(a.canvas.Pd=d);yb[c]=d;if(typeof b.vd=="undefined"||b.vd)if((a=d)||(a=V),!a.Nd){a.Nd=!0;b=a.qd;b.fe=b.getExtension("WEBGL_multi_draw");b.ae=b.getExtension("EXT_polygon_offset_clamp");b.$d=b.getExtension("EXT_clip_control");b.qe=b.getExtension("WEBGL_polygon_mode");qb(b);rb(b);sb(b);b.Yd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.de=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
a.version>=2&&(b.ud=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(a.version<2||!b.ud)b.ud=b.getExtension("EXT_disjoint_timer_query");for(var e of tb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},T,V,Fb=(a,b,c,d,e,f)=>{a={target:I(a),Nc:f,Qc:e,Sc:b,Pc:d,Tc:g=>{J(d)(e,0,b)&&g.preventDefault()},Rc:c};L(a)},Gb=(a,b,c,d)=>{K.pd||(K.pd=M(96));return L({target:a,dd:!0,Nc:"wheel",Qc:9,Sc:b,Pc:d,Tc:e=>{var f=K.pd;kb(f,e,a);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+
80>>3]=e.deltaZ;u[f+88>>2]=e.deltaMode;J(d)(9,f,b)&&e.preventDefault()},Rc:c})},Hb=["default","low-power","high-performance"],Ib={},Kb=()=>{if(!Jb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea},b;for(b in Ib)Ib[b]===void 0?delete a[b]:a[b]=Ib[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Jb=c}return Jb},Jb,Lb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=
2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},Mb=[null,[],[]],w,Nb=[],Ob=()=>{var a=tb(N);return a=a.concat(a.map(b=>"GL_"+b))},Pb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=N.getParameter(34467);c=d?d.length:0;break;case 33309:if(V.version<2){T||=1282;return}c=Ob().length;break;case 33307:case 33308:if(V.version<2){T||=1280;return}c=a==33307?3:0}if(c===void 0)switch(d=N.getParameter(a),typeof d){case "number":c=d;
break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(d===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+a*4>>2]=d[a];return}try{c=
d.name|0}catch(e){T||=1280;l(`GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;l(`GL_INVALID_ENUM in glGet0v: Native code calling glGet0v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else T||=1281},Qb=a=>{var b=Lb(a)+1,c=M(b);c&&B(a,c,b);return c},Rb=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),ra,Sb=a=>{a-=5120;return a==0?p:a==1?t:a==2?qa:a==4?u:a==6?w:a==5||a==28922||a==28520||a==30779||a==30782?v:
ra},W=a=>{var b=N.Ld;if(b){var c=b.Yc[a];typeof c=="number"&&(b.Yc[a]=c=N.getUniformLocation(b,b.Id[a]+(c>0?`[${c}]`:"")));return c}T||=1282},X=[],Tb=[],Vb=a=>{var b=Lb(a)+1,c=Ub(b);B(a,c,b);return c},Yb=a=>{var b=Wb();a();Xb(b)};h.requestAnimationFrame=Oa;h.pauseMainLoop=Za;h.resumeMainLoop=function(){Qa++;var a=La,b=Ma,c=C;C=null;Ya(c,0,!1,Ra,!0);Pa(a,b);F()};for(let a=0;a<32;++a)Nb.push(Array(a));for(var Zb=new Float32Array(288),Y=0;Y<=288;++Y)X[Y]=Zb.subarray(0,Y);var $b=new Int32Array(288);
for(Y=0;Y<=288;++Y)Tb[Y]=$b.subarray(0,Y);h.noExitRuntime&&(Ca=h.noExitRuntime);h.print&&(ma=h.print);h.printErr&&(l=h.printErr);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);var Z=h.preInit;if(Z)for(typeof Z=="function"&&(h.preInit=Z=[Z]);Z.length>0;)Z.shift()();
var M,ac,bc,cc,dc,ec,fc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,Xb,Ub,Wb,pa,db,sc={ua:function(){return 0},rb:function(){return 0},sb:function(){},wb:()=>wa(""),kb:()=>{Ca=!1;Ea=0},lb:function(a,b){a=a<-9007199254740992||a>9007199254740992?NaN:Number(a);a=new Date(a*1E3);if(isNaN(a.getTime()))return 1;u[b>>2]=a.getSeconds();u[b+4>>2]=a.getMinutes();u[b+8>>2]=a.getHours();u[b+12>>2]=a.getDate();u[b+16>>2]=a.getMonth();u[b+20>>2]=a.getFullYear()-1900;u[b+24>>2]=a.getDay();var c=a.getFullYear();u[b+28>>2]=
(c%4!==0||c%100===0&&c%400!==0?Ga:Fa)[a.getMonth()]+a.getDate()-1|0;u[b+36>>2]=-(a.getTimezoneOffset()*60);c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();u[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;return 0},hb:(a,b)=>{A[a]&&(clearTimeout(A[a].id),delete A[a]);if(!b)return 0;var c=setTimeout(()=>{delete A[a];Ka(()=>rc(a,performance.now()))},b);A[a]={id:c,oe:b};return 0},nb:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,
0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();v[a>>2]=Math.max(f,e)*60;u[b>>2]=Number(f!=e);b=g=>{var k=Math.abs(g);return`UTC${g>=0?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(B(a,c,17),B(b,d,17)):(B(a,d,17),B(b,c,17))},yb:function(a){if(window.localStorage===void 0)return 0;a=a?y(t,a):"";return(a=window.localStorage.getItem(a))?Qb(a):0},zb:function(a,b){window.localStorage!==void 0&&(a=a?y(t,a):"",b=b?y(t,b):"",window.localStorage.setItem(a,
b))},Va:()=>{Za();C=null},vb:()=>Date.now(),na:()=>globalThis.devicePixelRatio??1,pa:(a,b,c)=>{a=I(a);if(!a)return-4;a=bb(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},C:()=>performance.now(),Wa:()=>performance.now(),$a:(a,b)=>{function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ib:a=>{var b=t.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-pa.buffer.byteLength+
65535)/65536|0;try{pa.grow(d);oa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},X:(a,b,c,d)=>hb(a,b,c,d,12,"blur"),ma:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},Y:(a,b,c,d)=>hb(a,b,c,d,13,"focus"),W:(a,b,c,d)=>{if(!K.fullscreenEnabled())return-1;a=I(a);if(!a)return-4;ib(a,b,c,d,"webkitfullscreenchange");return ib(a,b,c,d,"fullscreenchange")},fa:(a,b,c,d)=>jb(a,b,c,d,2,"keydown"),da:(a,b,c,d)=>jb(a,b,c,d,1,"keypress"),ea:(a,b,c,d)=>jb(a,b,c,d,3,"keyup"),ab:(a,b,c)=>
{a=J(a);Ya(a,b,c)},la:(a,b,c,d)=>lb(a,b,c,d,5,"mousedown"),ia:(a,b,c,d)=>lb(a,b,c,d,33,"mouseenter"),ha:(a,b,c,d)=>lb(a,b,c,d,34,"mouseleave"),ja:(a,b,c,d)=>lb(a,b,c,d,8,"mousemove"),ka:(a,b,c,d)=>lb(a,b,c,d,6,"mouseup"),_:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?mb(a,b,c,d):-4:-1,Z:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?nb(a,b,c,d):-4:-1,oa:(a,b,c,d)=>ob(a,b,c,d),$:(a,b,c,d)=>pb(a,b,c,d,25,"touchcancel"),aa:(a,b,c,d)=>pb(a,b,c,d,23,"touchend"),ba:(a,b,c,d)=>pb(a,b,c,d,
24,"touchmove"),ca:(a,b,c,d)=>pb(a,b,c,d,22,"touchstart"),V:(a,b,c,d)=>{Fb(a,b,c,d,31,"webglcontextlost");return 0},U:(a,b,c,d)=>{Fb(a,b,c,d,32,"webglcontextrestored");return 0},ga:(a,b,c,d)=>(a=I(a))?typeof a.onwheel!="undefined"?Gb(a,b,c,d):-1:-4,_a:(a,b)=>{var c=b>>2;b={alpha:!!p[b+0],depth:!!p[b+1],stencil:!!p[b+2],antialias:!!p[b+3],premultipliedAlpha:!!p[b+4],preserveDrawingBuffer:!!p[b+5],powerPreference:Hb[u[c+2]],failIfMajorPerformanceCaveat:!!p[b+12],desynchronized:!!p[b+33],yd:u[c+4],ee:u[c+
5],vd:p[b+24],Md:p[b+25],he:u[c+7],me:p[b+32]};a=I(a);return!a||b.Md?0:Eb(a,b)},Za:a=>{V=yb[a];h.ctx=N=V?.qd;return!a||N?0:-5},tb:(a,b)=>{var c=0,d=0,e;for(e of Kb()){var f=b+c;v[a+d>>2]=f;c+=B(e,f,Infinity)+1;d+=4}return 0},ub:(a,b)=>{var c=Kb();v[a>>2]=c.length;a=0;for(var d of c)a+=Lb(d)+1;v[b>>2]=a;return 0},ta:()=>52,qb:()=>52,ob:function(){return 70},pb:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=v[b>>2],k=v[b+4>>2];b+=8;for(var n=0;n<k;n++){var q=a,r=t[g+n],D=Mb[q];r&&r!==10?D.push(r):((q===
1?ma:l)(y(D)),D.length=0)}e+=k}v[d>>2]=e;return 0},h:function(a,b,c){var d=a?y(t,a):"";try{var e=window.indexedDB.open("chips",1)}catch(f){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+f)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");e.result.createObjectStore("store")};e.onsuccess=()=>{var f=e.result;try{var g=f.transaction(["store"],"readwrite")}catch(q){console.log("fs_js_load_snapshot: db.transaction failed with",q);return}f=g.objectStore("store");
var k=d+"_"+b,n=f.get(k);n.onsuccess=()=>{if(n.result!==void 0){let q=n.result.length;console.log("fs_js_load_snapshot:",k,"successfully loaded",q,"bytes");let r=pc(q);t.set(n.result,r);qc(c,r,q)}else qc(c,0,0)};n.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",k)};g.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},xb:function(a,b,c,d){var e=a?y(t,a):"";console.log("fs_js_save_snapshot: called with",
e,b);try{var f=window.indexedDB.open("chips",1)}catch(g){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+g);return}f.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");f.result.createObjectStore("store")};f.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");var g=f.result.transaction(["store"],"readwrite"),k=g.objectStore("store"),n=e+"_"+b;k=k.put(t.subarray(c,c+d),n);k.onsuccess=()=>{console.log("fs_js_save_snapshot:",n,"successfully stored")};k.onerror=
()=>{console.log("fs_js_save_snapshot: FAILED to store",n)};g.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};f.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},o:a=>N.activeTexture(a),F:(a,b)=>{N.attachShader(P[a],R[b])},a:(a,b)=>{a==35051?N.td=b:a==35052&&(N.Xc=b);N.bindBuffer(a,O[b])},y:(a,b,c)=>{N.bindBufferBase(a,b,O[c])},Sb:(a,b,c,d,e)=>{N.bindBufferRange(a,b,O[c],d,e)},j:(a,b)=>{N.bindFramebuffer(a,vb[b])},ac:(a,b)=>{N.bindRenderbuffer(a,wb[b])},
n:(a,b)=>{N.bindSampler(a,S[b])},c:(a,b)=>{N.bindTexture(a,Q[b])},T:a=>{N.bindVertexArray(xb[a])},O:(a,b,c,d)=>N.blendColor(a,b,c,d),P:(a,b)=>N.blendEquationSeparate(a,b),Q:(a,b,c,d)=>N.blendFuncSeparate(a,b,c,d),Bb:(a,b,c,d,e,f,g,k,n,q)=>N.blitFramebuffer(a,b,c,d,e,f,g,k,n,q),Ja:(a,b,c,d)=>{V.version>=2?c&&b?N.bufferData(a,t,d,c,b):N.bufferData(a,b,d):N.bufferData(a,c?t.subarray(c,c+b):b,d)},I:(a,b,c,d)=>{var e=t;V.version>=2?c&&N.bufferSubData(a,b,e,d,c):N.bufferSubData(a,b,e.subarray(d,d+c))},
_b:a=>N.checkFramebufferStatus(a),Zb:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),xa:(a,b,c)=>{N.clearBufferfv(a,b,w,c>>2)},Xb:(a,b,c)=>{N.clearBufferiv(a,b,u,c>>2)},p:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},ec:a=>{N.compileShader(R[a])},w:(a,b,c,d,e,f,g,k,n)=>{V.version>=2?N.Xc||!k?N.compressedTexSubImage2D(a,b,c,d,e,f,g,k,n):N.compressedTexSubImage2D(a,b,c,d,e,f,g,t,n,k):N.compressedTexSubImage2D(a,b,c,d,e,f,g,t.subarray(n,n+k))},H:(a,b,c,d,e,f,g,k,n,q,r)=>{N.Xc?N.compressedTexSubImage3D(a,b,c,d,e,f,g,
k,n,q,r):N.compressedTexSubImage3D(a,b,c,d,e,f,g,k,n,t,r,q)},jc:()=>{var a=Cb(P),b=N.createProgram();b.name=a;b.ad=b.Zc=b.$c=0;b.od=1;P[a]=b;return a},gc:a=>{var b=Cb(R);R[b]=N.createShader(a);return b},L:a=>N.cullFace(a),Na:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=O[d];e&&(N.deleteBuffer(e),e.name=0,O[d]=null,d==N.td&&(N.td=0),d==N.Xc&&(N.Xc=0))}},x:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+c*4>>2],e=vb[d];e&&(N.deleteFramebuffer(e),e.name=0,vb[d]=null)}},t:a=>{if(a){var b=P[a];b?(N.deleteProgram(b),
b.name=0,P[a]=null):T||=1281}},J:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=wb[d];e&&(N.deleteRenderbuffer(e),e.name=0,wb[d]=null)}},K:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=S[d];e&&(N.deleteSampler(e),e.name=0,S[d]=null)}},s:a=>{if(a){var b=R[a];b?(N.deleteShader(b),R[a]=null):T||=1281}},k:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=Q[d];e&&(N.deleteTexture(e),e.name=0,Q[d]=null)}},Ma:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2];N.deleteVertexArray(xb[d]);xb[d]=null}},A:a=>
N.depthFunc(a),z:a=>{N.depthMask(!!a)},d:a=>N.disable(a),R:a=>{N.disableVertexAttribArray(a)},Db:(a,b,c)=>{N.drawArrays(a,b,c)},Fb:(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},ya:(a,b)=>{for(var c=Nb[a],d=0;d<a;d++)c[d]=u[b+d*4>>2];N.drawBuffers(c)},Gb:(a,b,c,d)=>{N.drawElements(a,b,c,d)},Hb:(a,b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},g:a=>N.enable(a),Tb:a=>{N.enableVertexAttribArray(a)},l:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,wb[d])},e:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,Q[d],e)},
D:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,Q[c],d,e)},M:a=>N.frontFace(a),Ka:(a,b)=>{U(a,b,"createBuffer",O)},S:(a,b)=>{U(a,b,"createFramebuffer",vb)},bc:(a,b)=>{U(a,b,"createRenderbuffer",wb)},kc:(a,b)=>{U(a,b,"createSampler",S)},Ia:(a,b)=>{U(a,b,"createTexture",Q)},Ua:(a,b)=>{U(a,b,"createVertexArray",xb)},cc:(a,b)=>N.getAttribLocation(P[a],b?y(t,b):""),b:(a,b)=>Pb(a,b),ic:(a,b,c,d)=>{a=N.getProgramInfoLog(P[a]);a===null&&(a="(unknown error)");b=b>0&&d?B(a,d,b):0;c&&(u[c>>2]=b)},Ca:(a,b,c)=>
{if(c)if(a>=ub)T||=1281;else if(a=P[a],b==35716)a=N.getProgramInfoLog(a),a===null&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(b==35719){if(!a.ad){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.ad=Math.max(a.ad,N.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.ad}else if(b==35722){if(!a.Zc)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.Zc=Math.max(a.Zc,N.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Zc}else if(b==35381){if(!a.$c)for(d=N.getProgramParameter(a,35382),b=0;b<d;++b)a.$c=
Math.max(a.$c,N.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.$c}else u[c>>2]=N.getProgramParameter(a,b);else T||=1281},dc:(a,b,c,d)=>{a=N.getShaderInfoLog(R[a]);a===null&&(a="(unknown error)");b=b>0&&d?B(a,d,b):0;c&&(u[c>>2]=b)},Aa:(a,b,c)=>{c?b==35716?(a=N.getShaderInfoLog(R[a]),a===null&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):b==35720?(a=N.getShaderSource(R[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=N.getShaderParameter(R[a],b):T||=1281},Sa:(a,b)=>{if(V.version<2)return T||=1282,0;var c=zb[a];
if(c)return b<0||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Ob().map(Qb),c=zb[a]=c,b<0||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},Ba:(a,b)=>{b=b?y(t,b):"";if(a=P[a]){var c=a,d=c.Yc,e=c.Jd,f;if(!d){c.Yc=d={};c.Id={};var g=N.getProgramParameter(c,35718);for(f=0;f<g;++f){var k=N.getActiveUniform(c,f);var n=k.name;k=k.size;var q=Rb(n);q=q>0?n.slice(0,q):n;var r=c.od;c.od+=k;e[q]=[k,r];for(n=0;n<k;++n)d[r]=n,c.Id[r++]=q}}c=a.Yc;d=0;f=b;e=Rb(b);e>0&&(d=b.slice(e+1),d=parseInt(d)>>>
0,f=b.slice(0,e));if((e=a.Jd[f])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T||=1281;return-1},Ab:(a,b,c)=>{for(var d=Nb[b],e=0;e<b;e++)d[e]=u[c+e*4>>2];N.invalidateFramebuffer(a,d)},Da:a=>{a=P[a];N.linkProgram(a);a.Yc=0;a.Jd={}},q:(a,b)=>{a==3317?Ab=b:a==3314&&(Bb=b);N.pixelStorei(a,b)},N:(a,b)=>N.polygonOffset(a,b),Cb:a=>N.readBuffer(a),$b:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,b,c,d,e),Ea:(a,b,c)=>{N.samplerParameterf(S[a],b,c)},f:(a,b,c)=>{N.samplerParameteri(S[a],
b,c)},r:(a,b,c,d)=>N.scissor(a,b,c,d),fc:(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=z(v[c+f*4>>2],d?v[d+f*4>>2]:void 0);N.shaderSource(R[a],e)},Ra:(a,b,c)=>N.stencilFunc(a,b,c),wa:(a,b,c,d)=>N.stencilFuncSeparate(a,b,c,d),u:a=>N.stencilMask(a),Qa:(a,b,c)=>N.stencilOp(a,b,c),va:(a,b,c,d)=>N.stencilOpSeparate(a,b,c,d),Ha:(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),Ga:(a,b,c,d,e,f)=>N.texStorage3D(a,b,c,d,e,f),v:(a,b,c,d,e,f,g,k,n)=>{if(V.version>=2){if(N.Xc){N.texSubImage2D(a,b,c,d,e,f,g,k,n);return}if(n){var q=
Sb(k);N.texSubImage2D(a,b,c,d,e,f,g,k,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=Sb(k);var r=f*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT*(Bb||e)+Ab-1&-Ab);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+r>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;N.texSubImage2D(a,b,c,d,e,f,g,k,n)},G:(a,b,c,d,e,f,g,k,n,q,r)=>{if(N.Xc)N.texSubImage3D(a,b,c,d,e,f,g,k,n,q,r);else if(r){var D=Sb(q);N.texSubImage3D(a,b,c,d,e,f,g,k,n,q,D,
r>>>31-Math.clz32(D.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,b,c,d,e,f,g,k,n,q,null)},Rb:(a,b,c)=>{if(V.version>=2)b&&N.uniform1fv(W(a),w,c>>2,b);else{if(b<=288)for(var d=X[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+b*4>>2);N.uniform1fv(W(a),d)}},hc:(a,b)=>{N.uniform1i(W(a),b)},Mb:(a,b,c)=>{if(V.version>=2)b&&N.uniform1iv(W(a),u,c>>2,b);else{if(b<=288)for(var d=Tb[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+b*4>>2);N.uniform1iv(W(a),d)}},Qb:(a,b,c)=>{if(V.version>=2)b&&
N.uniform2fv(W(a),w,c>>2,b*2);else{if(b<=144){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+b*8>>2);N.uniform2fv(W(a),d)}},Lb:(a,b,c)=>{if(V.version>=2)b&&N.uniform2iv(W(a),u,c>>2,b*2);else{if(b<=144){b*=2;for(var d=Tb[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+b*8>>2);N.uniform2iv(W(a),d)}},Ob:(a,b,c)=>{if(V.version>=2)b&&N.uniform3fv(W(a),w,c>>2,b*3);else{if(b<=96){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=w[c+
4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+b*12>>2);N.uniform3fv(W(a),d)}},Kb:(a,b,c)=>{if(V.version>=2)b&&N.uniform3iv(W(a),u,c>>2,b*3);else{if(b<=96){b*=3;for(var d=Tb[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+b*12>>2);N.uniform3iv(W(a),d)}},Nb:(a,b,c)=>{if(V.version>=2)b&&N.uniform4fv(W(a),w,c>>2,b*4);else{if(b<=72){var d=X[4*b],e=w;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];
d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+b*16>>2);N.uniform4fv(W(a),d)}},Jb:(a,b,c)=>{if(V.version>=2)b&&N.uniform4iv(W(a),u,c>>2,b*4);else{if(b<=72){b*=4;for(var d=Tb[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+b*16>>2);N.uniform4iv(W(a),d)}},Ib:(a,b,c,d)=>{if(V.version>=2)b&&N.uniformMatrix4fv(W(a),!!c,w,d>>2,b*16);else{if(b<=18){var e=X[16*b],f=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var k=d+g;e[g]=f[k];
e[g+1]=f[k+1];e[g+2]=f[k+2];e[g+3]=f[k+3];e[g+4]=f[k+4];e[g+5]=f[k+5];e[g+6]=f[k+6];e[g+7]=f[k+7];e[g+8]=f[k+8];e[g+9]=f[k+9];e[g+10]=f[k+10];e[g+11]=f[k+11];e[g+12]=f[k+12];e[g+13]=f[k+13];e[g+14]=f[k+14];e[g+15]=f[k+15]}}else e=w.subarray(d>>2,d+b*64>>2);N.uniformMatrix4fv(W(a),!!c,e)}},m:a=>{a=P[a];N.useProgram(a);N.Ld=a},Ub:(a,b)=>{N.vertexAttribDivisor(a,b)},Vb:(a,b,c,d,e)=>{N.vertexAttribIPointer(a,b,c,d,e)},Wb:(a,b,c,d,e,f)=>{N.vertexAttribPointer(a,b,c,!!d,e,f)},i:(a,b,c,d)=>N.viewport(a,
b,c,d),jb:Ia,mc:function(){h.Bd=a=>{bc()!=0&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.Bd)},bb:function(){h.Hd=a=>{var b=a.clipboardData.getData("text");Yb(()=>{var c=Vb(b);ac(c)})};window.addEventListener("paste",h.Hd)},Ta:function(){h.ne=[];h.Cd=b=>{b.stopPropagation();b.preventDefault()};h.Dd=b=>{b.stopPropagation();b.preventDefault()};h.Ed=b=>{b.stopPropagation();b.preventDefault()};h.Fd=b=>{b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;
h.Gd=c;cc(c.length);for(let e=0;e<c.length;e++)Yb(()=>{var f=Vb(c[e].name);dc(e,f)});var d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);ec(b.clientX,b.clientY,d)};var a=h.Uc;a.addEventListener("dragenter",h.Cd,!1);a.addEventListener("dragleave",h.Dd,!1);a.addEventListener("dragover",h.Ed,!1);a.addEventListener("drop",h.Fd,!1)},Pb:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Yb:function(a){h.cd&&(URL.revokeObjectURL(h.cd[a].Sd),
h.cd[a]=null)},Pa:function(a){var b=h.Gd;return a<0||a>=b.length?0:b[a].size},Oa:function(a,b,c,d,e){var f=new FileReader;f.onload=g=>{g=g.target.result;g.byteLength>d?fc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(g),c),fc(a,1,0,b,g.byteLength,c,d,e))};f.onerror=()=>{fc(a,0,2,b,0,c,d,e)};f.readAsArrayBuffer(h.Gd[a])},lc:function(a,b){b!==0&&(document.title=z(Number(b)));a=z(Number(a));h.canvas!==void 0&&(typeof h.canvas==="object"?ab[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
h.Uc=I(a);h.Uc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Uc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},fb:function(){window.removeEventListener("beforeunload",h.Bd)},Ya:function(){window.removeEventListener("paste",h.Hd)},La:function(){var a=h.Uc;a.removeEventListener("dragenter",h.Cd);a.removeEventListener("dragleave",h.Dd);a.removeEventListener("dragover",h.Ed);a.removeEventListener("drop",h.Fd)},E:function(){h.Uc&&h.Uc.requestPointerLock&&
h.Uc.requestPointerLock()},za:function(a,b,c){if(h.Uc){if(b===0)a="none";else if(c!=0)a=h.cd[a].Ud;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.Uc.style.cursor=a}},Eb:function(a,b,c){var d=document.createElement("canvas");
d.width=a;d.height=b;var e=d.getContext("2d"),f=e.createImageData(a,b);f.data.set(t.subarray(c,c+a*b*4));e.putImageData(f,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Xa:function(a){a=z(Number(a));var b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top=
"-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},cb:function(){var a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){let c=b.value[0],d=b.value[1];Yb(()=>{var e=Vb(c),f=Vb(d);jc(e,f)})}},eb:function(){return h.Vc?h.Vc.bufferSize:0},mb:function(a,b,c){h.Mc=null;h.Vc=null;typeof AudioContext!=="undefined"?h.Mc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):
(h.Mc=null,console.log("sokol_audio.h: no WebAudio support"));if(h.Mc){console.log("sokol_audio.h: sample rate ",h.Mc.sampleRate);h.Vc=h.Mc.createScriptProcessor(c,0,b);h.Vc.onaudioprocess=e=>{var f=e.outputBuffer.length,g=ic(f);if(g){let k=e.outputBuffer.numberOfChannels;for(let n=0;n<k;n++){let q=e.outputBuffer.getChannelData(n);for(let r=0;r<f;r++)q[r]=w[(g>>2)+(k*r+n)]}}};h.Vc.connect(h.Mc.destination);let d=()=>{if(h.Mc){let e=h.Mc.state;e!=="suspended"&&e!=="interrupted"||h.Mc.resume().catch(()=>
{console.warn("sokol_audio.h: webaudio resume failed")})}};h.Mc.onstatechange=d;document.addEventListener("visibilitychange",()=>{document.visibilityState==="visible"&&d()});document.addEventListener("click",d,{once:!0});document.addEventListener("touchend",d,{once:!0});document.addEventListener("keydown",d,{once:!0});return 1}return 0},gb:function(){return h.Mc?h.Mc.sampleRate:0},sa:function(){var a=h.Mc;a!==null&&(h.Vc&&h.Vc.disconnect(),a.close(),h.Mc=null,h.Vc=null)},db:function(){if(h.Mc){let a=
h.Mc.state;return a==="suspended"||a==="interrupted"?1:0}return 0},B:function(a,b,c,d,e,f){var g=z(Number(b));b=new Headers;d>0&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(g,{method:"GET",headers:b}).then(k=>{k.ok?k.arrayBuffer().then(n=>{n=new Uint8Array(n);n.length<=f?(t.set(n,e),lc(a,d,n.length)):nc(a)}).catch(n=>{console.error(`sokol_fetch.h: GET ${g} failed with: `,n);oc(a)}):mc(a,k.status)}).catch(k=>{console.error(`sokol_fetch.h: GET ${g} failed with: `,k);oc(a)})},ra:function(a,b){var c=
z(Number(b));fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),d===null?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),oc(a)):kc(a,Number(d))):mc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);oc(a)})},Fa:function(){return navigator.userAgent.includes("Macintosh")?1:0},qa:function(a,b){b=z(Number(b));switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};
function tc(a=[]){var b=hc;a.unshift(ea);var c=a.length,d=Ub((c+1)*4),e=d,f;for(f of a)v[e>>2]=Vb(f),e+=4;v[e>>2]=0;try{var g=b(c,d);na=g;Ia(g)}catch(k){Ha(k)}}async function uc(){var a=da;sa();var b=h.setStatus;b&&(b("Running..."),await new Promise(c=>setTimeout(c,1)),setTimeout(b,1,""));m||(vc.oc(),h.onRuntimeInitialized?.(),h.noInitialRun||tc(a),ua())}var vc;
(async function(){function a(d){d=vc=d.exports;M=d.pc;ac=h.__sapp_emsc_onpaste=d.qc;bc=h.__sapp_html5_get_ask_leave_site=d.rc;cc=h.__sapp_emsc_begin_drop=d.sc;dc=h.__sapp_emsc_drop=d.tc;ec=h.__sapp_emsc_end_drop=d.uc;fc=h.__sapp_emsc_invoke_fetch_cb=d.vc;h.__sapp_emsc_set_fullscreen_flag=d.wc;hc=h._main=d.xc;ic=h.__saudio_emsc_pull=d.yc;jc=h.__sargs_add_kvp=d.zc;kc=h.__sfetch_emsc_head_response=d.Ac;lc=h.__sfetch_emsc_get_response=d.Bc;mc=h.__sfetch_emsc_failed_http_status=d.Cc;nc=h.__sfetch_emsc_failed_buffer_too_small=
d.Dc;oc=h.__sfetch_emsc_failed_other=d.Ec;pc=h._fs_emsc_alloc=d.Fc;qc=h._fs_emsc_load_snapshot_callback=d.Gc;rc=d.Ic;Xb=d.Jc;Ub=d.Kc;Wb=d.Lc;pa=d.nc;db=d.Hc;oa();return vc}var b={a:sc},c=h.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});xa??=h.locateFile?h.locateFile("z9001-ui.wasm",ia):ia+"z9001-ui.wasm";return function(d){return a(d.instance)}(await Aa(b))})().then(()=>uc());
