var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var k=console.error.bind(console),m,p=!1,ma,la=a=>a.startsWith("file://"),na,r,t,oa,pa,v,w,x,y;
function qa(){var a=na.buffer;r=new Int8Array(a);oa=new Int16Array(a);t=new Uint8Array(a);pa=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}var z=0,A=null;function ra(a){g.onAbort?.(a);a="Aborted("+a+")";k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var sa;
async function ta(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==sa&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function ua(a,b){try{var c=await ta(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ra(d)}}
async function va(a){var b=sa;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ua(b,a)}class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var xa=a=>{for(;0<a.length;)a.shift()(g)},ya=[],za=[],Aa=()=>{var a=g.preRun.shift();za.push(a)},Ba=!0,Ca=0,B={},Da=a=>{a instanceof wa||"unwind"==a||fa(1,a)},Ea=a=>{ma=a;Ba||0<Ca||(g.onExit?.(a),p=!0);fa(a,new wa(a))},Fa=a=>{ma=a;Ea(a)},Ga=()=>{if(!(Ba||0<Ca))try{var a=ma;ma=a;Ea(a)}catch(b){Da(b)}},Ha=a=>{if(!p)try{a(),Ga()}catch(b){Da(b)}},Pa=(a,b)=>{Ia=a;Ja=b;if(D)if(Ka||=!0,0==a)E=function(){setTimeout(La,Math.max(0,Ma+b-performance.now())|0)};else if(1==a)E=function(){Na(La)};else if(2==a){if("undefined"==
typeof Oa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Oa=d=>{c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Oa=setImmediate;E=function(){Oa(La)}}},Ya=(a,b,c,d,e)=>{function h(){return f<Qa?(Ga(),!1):!0}D=a;Ra=d;var f=Qa;Ka=!1;La=function(){if(!p)if(0<
Sa.length){var l=Sa.shift();l.Ad(l.pd);if(Ta){var n=Ta,q=0==n%1?n-1:Math.floor(n);Ta=l.rd?q:(8*n+(q+.5))/9}g.setStatus&&(l=g.statusMessage||"Please wait...",n=Ta??0,q=Ua.wd??0,n?n<q?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(l):g.setStatus(""));h()&&setTimeout(La,0)}else if(h())if(Va=Va+1|0,1==Ia&&1<Ja&&0!=Va%Ja)E();else{0==Ia&&(Ma=performance.now());a:if(!p){for(l of Wa)if(!1===l())break a;Ha(a);for(n of Xa)n()}h()&&E()}};e||(0<b?Pa(0,1E3/b):Pa(1,1),E());if(c)throw"unwind";
},Ka=!1,E=null,Qa=0,D=null,Ra=0,Ia=0,Ja=0,Va=0,Sa=[],Wa=[],Xa=[];function Za(){E=null;Qa++}var $a=0;function Na(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===$a)$a=b+1E3/60;else for(;b+2>=$a;)$a+=1E3/60;setTimeout(a,Math.max($a-b,0))}}
var Ua={},Ma,La,Oa,Ta,ab="undefined"!=typeof TextDecoder?new TextDecoder:void 0,F=(a=0,b)=>{var c=t;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(16<d-a&&c.buffer&&ab)return ab.decode(c.subarray(a,d));for(b="";a<d;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))b+=String.fromCharCode((e&31)<<6|h);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|c[a++]&63;65536>e?b+=String.fromCharCode(e):(e-=65536,b+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else b+=String.fromCharCode(e)}return b},
bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],G=a=>{a=2<a?a?F(a):"":a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):null)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=[],eb,H=a=>{var b=db[a];b||(db[a]=b=eb.get(a));return b};function fb(a){var b=I.sc[a];b.target.removeEventListener(b.rc,b.Uc,b.tc);I.sc.splice(a,1)}
function gb(){if(navigator.userActivation?navigator.userActivation.isActive:I.Hc&&I.kd.Fc){var a=I.xc;I.xc=[];for(var b of a)b.Kc(...b.Qc)}}function J(a){if(!a.target)return-4;if(a.uc)a.Uc=function(c){++I.Hc;I.kd=a;gb();a.vc(c);gb();--I.Hc},a.target.addEventListener(a.rc,a.Uc,a.tc),I.sc.push(a);else for(var b=0;b<I.sc.length;++b)I.sc[b].target==a.target&&I.sc[b].rc==a.rc&&fb(b--);return 0}function hb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var I={qd:0,Bd:0,Ic:0,Ec:0,Oc:0,Mc:0,Gc:0,ud:0,Gd:0,td:0,zd:0,Jc:0,Od:0,Lc:0,Dd(a,b,c){r.set(r.subarray(b,b+c),a)},Id(){for(;I.sc.length;)fb(I.sc.length-1);I.xc=[]},Hc:0,xc:[],sd(a,b,c){function d(h,f){if(h.length!=f.length)return!1;for(var l in h)if(h[l]!=f[l])return!1;return!0}for(var e of I.xc)if(e.Kc==a&&d(e.Qc,c))return;I.xc.push({Kc:a,Yc:b,Qc:c});I.xc.sort((h,f)=>h.Yc<f.Yc)},Kd(a){I.xc=I.xc.filter(b=>b.Kc!=a)},sc:[],Jd:(a,b)=>{for(var c=0;c<I.sc.length;++c)I.sc[c].target!=a||b&&b!=I.sc[c].rc||
fb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},K=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.codePointAt(h);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;h++}}d[b]=0;return b-
e},ib=(a,b,c,d,e,h)=>{I.Gc||(I.Gc=L(256));a={target:G(a),rc:h,uc:d,vc:(f=event)=>{var l=f.target.id?f.target.id:"",n=I.Gc;K(hb(f.target),n+0,128);K(l,n+128,128);H(d)(e,n,b)&&f.preventDefault()},tc:c};return J(a)},jb=(a,b,c,d,e,h)=>{I.Ic||(I.Ic=L(160));a={target:G(a),rc:h,uc:d,vc:f=>{var l=I.Ic;y[l>>3]=f.timeStamp;var n=l>>2;v[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;v[n+5]=f.charCode;v[n+6]=f.keyCode;v[n+7]=f.which;K(f.key||"",l+32,32);
K(f.code||"",l+64,32);K(f.char||"",l+96,32);K(f.locale||"",l+128,32);H(d)(e,l,b)&&f.preventDefault()},tc:c};return J(a)},kb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=cb(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},lb=(a,b,c,d,e,h)=>{I.Ec||(I.Ec=L(64));a=G(a);return J({target:a,
Fc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,rc:h,uc:d,vc:(f=event)=>{kb(I.Ec,f,a);H(d)(e,I.Ec,b)&&f.preventDefault()},tc:c})},mb=(a,b,c,d)=>{I.Jc||(I.Jc=L(257));return J({target:a,rc:"pointerlockchange",uc:d,vc:(e=event)=>{var h=I.Jc,f=document.pointerLockElement;r[h]=!!f;var l=f?.id||"";K(hb(f),h+1,128);K(l,h+129,128);H(d)(20,h,b)&&e.preventDefault()},tc:c})},nb=(a,b,c,d)=>J({target:a,rc:"pointerlockerror",uc:d,vc:(e=event)=>{H(d)(38,0,b)&&e.preventDefault()},tc:c}),ob=(a,b,c,d)=>{I.Mc||
(I.Mc=L(36));a=G(a);return J({target:a,rc:"resize",uc:d,vc:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=I.Mc;v[f>>2]=0;v[f+4>>2]=h.clientWidth;v[f+8>>2]=h.clientHeight;v[f+12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+20>>2]=outerWidth;v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|0;v[f+32>>2]=pageYOffset|0;H(d)(10,f,b)&&e.preventDefault()}}},tc:c})},pb=(a,b,c,d,e,h)=>{I.Lc||(I.Lc=L(1552));a=G(a);return J({target:a,Fc:"touchstart"==h||"touchend"==h,rc:h,uc:d,vc:f=>{var l={},n=f.touches;
for(var q of n)q.Vc=q.Xc=0,l[q.identifier]=q;for(var u of f.changedTouches)u.Vc=1,l[u.identifier]=u;for(var N of f.targetTouches)l[N.identifier].Xc=1;n=I.Lc;y[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=f.shiftKey;r[n+14]=f.altKey;r[n+15]=f.metaKey;q=n+16;u=cb(a);N=0;for(let C of Object.values(l))if(l=q>>2,v[l]=C.identifier,v[l+1]=C.screenX,v[l+2]=C.screenY,v[l+3]=C.clientX,v[l+4]=C.clientY,v[l+5]=C.pageX,v[l+6]=C.pageY,r[q+28]=C.Vc,r[q+29]=C.Xc,v[l+8]=C.clientX-(u.left|0),v[l+9]=C.clientY-(u.top|
0),q+=48,31<++N)break;v[n+8>>2]=N;H(d)(e,n,b)&&f.preventDefault()},tc:c})},M,qb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},rb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},sb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},tb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},ub=1,O=[],P=[],vb=[],wb=[],Q=[],R=[],xb=[],yb=[],S=[],zb={},Ab=4,Bb=0,Cb=a=>{for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=M[c](),f=h&&Cb(d);h?(h.name=f,d[f]=h):T||=1282;v[b+4*e>>2]=f}},Eb=(a,b)=>{a.Zc||(a.Zc=a.getContext,a.getContext=function(d,e){e=a.Zc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Wc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Db(c,b):0},Db=(a,b)=>{var c=Cb(yb),d={handle:c,attributes:b,version:b.Wc,Pc:a};a.canvas&&(a.canvas.od=d);yb[c]=d;("undefined"==typeof b.Tc||b.Tc)&&Fb(d);return c},Fb=a=>{a||=V;if(!a.nd){a.nd=!0;var b=a.Pc;b.Fd=b.getExtension("WEBGL_multi_draw");b.yd=b.getExtension("EXT_polygon_offset_clamp");b.xd=b.getExtension("EXT_clip_control");b.Pd=b.getExtension("WEBGL_polygon_mode");qb(b);rb(b);sb(b);b.vd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Cd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Sc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Sc)b.Sc=b.getExtension("EXT_disjoint_timer_query");tb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Gb=(a,b,c,d,e,h)=>{a={target:G(a),rc:h,uc:d,vc:(f=event)=>{H(d)(e,0,b)&&f.preventDefault()},tc:c};J(a)},Hb=(a,b,c,d)=>{I.Oc||(I.Oc=L(96));return J({target:a,Fc:!0,rc:"wheel",uc:d,vc:(e=event)=>{var h=I.Oc;kb(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+80>>3]=e.deltaZ;
v[h+88>>2]=e.deltaMode;H(d)(9,h,b)&&e.preventDefault()},tc:c})},Ib=["default","low-power","high-performance"],Jb=[],Kb=()=>{var a=tb(M);return a=a.concat(a.map(b=>"GL_"+b))},Lb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=M.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Kb().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=M.getParameter(a),
typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+
4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else T||=1281},Mb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Nb=a=>{var b=Mb(a)+1,c=L(b);c&&K(a,c,
b);return c},Ob=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Pb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?oa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?w:pa},W=a=>{var b=M.ld;if(b){var c=b.Ac[a];"number"==typeof c&&(b.Ac[a]=c=M.getUniformLocation(b,b.hd[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],Qb=[],Sb=a=>{var b=Mb(a)+1,c=Rb(b);K(a,c,b);return c},Vb=a=>{var b=Tb();a();Ub(b)};g.requestAnimationFrame=Na;g.pauseMainLoop=Za;
g.resumeMainLoop=function(){Qa++;var a=Ia,b=Ja,c=D;D=null;Ya(c,0,!1,Ra,!0);Pa(a,b);E()};g.preMainLoop&&Wa.push(g.preMainLoop);g.postMainLoop&&Xa.push(g.postMainLoop);for(let a=0;32>a;++a)Jb.push(Array(a));for(var Wb=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=Wb.subarray(0,Y);var Xb=new Int32Array(288);for(Y=0;288>=Y;++Y)Qb[Y]=Xb.subarray(0,Y);g.noExitRuntime&&(Ba=g.noExitRuntime);g.printErr&&(k=g.printErr);g.wasmBinary&&(m=g.wasmBinary);g.arguments&&(da=g.arguments);g.thisProgram&&(ea=g.thisProgram);
var L,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,Ub,Rb,Tb,mc={gb:()=>ra(""),cb:()=>{Ba=!1;Ca=0},db:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];Ha(()=>lc(a,performance.now()))},b);B[a]={id:c,Nd:b};return 0},Qa:()=>{Za();D=null},ha:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ja:(a,b,c)=>{a=G(a);if(!a)return-4;a=cb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},z:()=>performance.now(),Ra:()=>performance.now(),Xa:(a,b)=>{function c(d){H(a)(d,
b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},eb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);qa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},R:(a,b,c,d)=>ib(a,b,c,d,12,"blur"),ga:(a,b,c)=>{a=G(a);if(!a)return-4;a.width=b;a.height=c;return 0},S:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),$:(a,
b,c,d)=>jb(a,b,c,d,2,"keydown"),Z:(a,b,c,d)=>jb(a,b,c,d,1,"keypress"),_:(a,b,c,d)=>jb(a,b,c,d,3,"keyup"),Ya:(a,b,c)=>{a=H(a);Ya(a,b,c)},fa:(a,b,c,d)=>lb(a,b,c,d,5,"mousedown"),ca:(a,b,c,d)=>lb(a,b,c,d,33,"mouseenter"),ba:(a,b,c,d)=>lb(a,b,c,d,34,"mouseleave"),da:(a,b,c,d)=>lb(a,b,c,d,8,"mousemove"),ea:(a,b,c,d)=>lb(a,b,c,d,6,"mouseup"),U:(a,b,c,d)=>document.body?.requestPointerLock?(a=G(a))?mb(a,b,c,d):-4:-1,T:(a,b,c,d)=>document.body?.requestPointerLock?(a=G(a))?nb(a,b,c,d):-4:-1,ia:(a,b,c,d)=>ob(a,
b,c,d),V:(a,b,c,d)=>pb(a,b,c,d,25,"touchcancel"),W:(a,b,c,d)=>pb(a,b,c,d,23,"touchend"),X:(a,b,c,d)=>pb(a,b,c,d,24,"touchmove"),Y:(a,b,c,d)=>pb(a,b,c,d,22,"touchstart"),Q:(a,b,c,d)=>{Gb(a,b,c,d,31,"webglcontextlost");return 0},P:(a,b,c,d)=>{Gb(a,b,c,d,32,"webglcontextrestored");return 0},aa:(a,b,c,d)=>(a=G(a))?"undefined"!=typeof a.onwheel?Hb(a,b,c,d):-1:-4,Wa:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+
5],powerPreference:Ib[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Wc:v[c+4],Ed:v[c+5],Tc:r[b+24],md:r[b+25],Hd:v[c+7],Ld:r[b+32]};a=G(a);return!a||b.md?0:Eb(a,b)},Va:a=>{V=yb[a];g.ctx=M=V?.Pc;return!a||M?0:-5},q:a=>M.activeTexture(a),B:(a,b)=>{M.attachShader(P[a],R[b])},b:(a,b)=>{35051==a?M.Rc=b:35052==a&&(M.zc=b);M.bindBuffer(a,O[b])},a:(a,b,c)=>{M.bindBufferBase(a,b,O[c])},xb:(a,b,c,d,e)=>{M.bindBufferRange(a,b,O[c],d,e)},i:(a,b)=>{M.bindFramebuffer(a,vb[b])},Hb:(a,b)=>{M.bindRenderbuffer(a,
wb[b])},p:(a,b)=>{M.bindSampler(a,S[b])},d:(a,b)=>{M.bindTexture(a,Q[b])},O:a=>{M.bindVertexArray(xb[a])},J:(a,b,c,d)=>M.blendColor(a,b,c,d),K:(a,b)=>M.blendEquationSeparate(a,b),L:(a,b,c,d)=>M.blendFuncSeparate(a,b,c,d),ib:(a,b,c,d,e,h,f,l,n,q)=>M.blitFramebuffer(a,b,c,d,e,h,f,l,n,q),Ea:(a,b,c,d)=>{2<=V.version?c&&b?M.bufferData(a,t,d,c,b):M.bufferData(a,b,d):M.bufferData(a,c?t.subarray(c,c+b):b,d)},E:(a,b,c,d)=>{2<=V.version?c&&M.bufferSubData(a,b,t,d,c):M.bufferSubData(a,b,t.subarray(d,d+c))},
Fb:a=>M.checkFramebufferStatus(a),Eb:(a,b,c,d)=>M.clearBufferfi(a,b,c,d),pa:(a,b,c)=>{M.clearBufferfv(a,b,x,c>>2)},Db:(a,b,c)=>{M.clearBufferiv(a,b,v,c>>2)},r:(a,b,c,d)=>{M.colorMask(!!a,!!b,!!c,!!d)},Mb:a=>{M.compileShader(R[a])},Aa:(a,b,c,d,e,h,f,l,n)=>{2<=V.version?M.zc||!l?M.compressedTexSubImage2D(a,b,c,d,e,h,f,l,n):M.compressedTexSubImage2D(a,b,c,d,e,h,f,t,n,l):M.compressedTexSubImage2D(a,b,c,d,e,h,f,t.subarray(n,n+l))},za:(a,b,c,d,e,h,f,l,n,q,u)=>{M.zc?M.compressedTexSubImage3D(a,b,c,d,e,h,
f,l,n,q,u):M.compressedTexSubImage3D(a,b,c,d,e,h,f,l,n,t,u,q)},xa:()=>{var a=Cb(P),b=M.createProgram();b.name=a;b.Dc=b.Bc=b.Cc=0;b.Nc=1;P[a]=b;return a},Ob:a=>{var b=Cb(R);R[b]=M.createShader(a);return b},G:a=>M.cullFace(a),Ia:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=O[d];e&&(M.deleteBuffer(e),e.name=0,O[d]=null,d==M.Rc&&(M.Rc=0),d==M.zc&&(M.zc=0))}},v:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=vb[d];e&&(M.deleteFramebuffer(e),e.name=0,vb[d]=null)}},n:a=>{if(a){var b=P[a];b?(M.deleteProgram(b),
b.name=0,P[a]=null):T||=1281}},F:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=wb[d];e&&(M.deleteRenderbuffer(e),e.name=0,wb[d]=null)}},o:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(M.deleteSampler(e),e.name=0,S[d]=null)}},l:a=>{if(a){var b=R[a];b?(M.deleteShader(b),R[a]=null):T||=1281}},j:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(M.deleteTexture(e),e.name=0,Q[d]=null)}},Ga:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];M.deleteVertexArray(xb[d]);xb[d]=null}},x:a=>
M.depthFunc(a),w:a=>{M.depthMask(!!a)},e:a=>M.disable(a),M:a=>{M.disableVertexAttribArray(a)},kb:(a,b,c)=>{M.drawArrays(a,b,c)},lb:(a,b,c,d)=>{M.drawArraysInstanced(a,b,c,d)},sa:(a,b)=>{for(var c=Jb[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];M.drawBuffers(c)},mb:(a,b,c,d)=>{M.drawElements(a,b,c,d)},nb:(a,b,c,d,e)=>{M.drawElementsInstanced(a,b,c,d,e)},h:a=>M.enable(a),yb:a=>{M.enableVertexAttribArray(a)},ra:(a,b,c,d)=>{M.framebufferRenderbuffer(a,b,c,wb[d])},k:(a,b,c,d,e)=>{M.framebufferTexture2D(a,b,c,Q[d],
e)},A:(a,b,c,d,e)=>{M.framebufferTextureLayer(a,b,Q[c],d,e)},H:a=>M.frontFace(a),Fa:(a,b)=>{U(a,b,"createBuffer",O)},N:(a,b)=>{U(a,b,"createFramebuffer",vb)},Ib:(a,b)=>{U(a,b,"createRenderbuffer",wb)},ya:(a,b)=>{U(a,b,"createSampler",S)},Da:(a,b)=>{U(a,b,"createTexture",Q)},Pa:(a,b)=>{U(a,b,"createVertexArray",xb)},Jb:(a,b)=>M.getAttribLocation(P[a],b?F(b):""),c:(a,b)=>Lb(a,b),Qb:(a,b,c,d)=>{a=M.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(v[c>>2]=b)},va:(a,b,c)=>
{if(c)if(a>=ub)T||=1281;else if(a=P[a],35716==b)a=M.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.Dc){var d=M.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Dc=Math.max(a.Dc,M.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.Dc}else if(35722==b){if(!a.Bc)for(d=M.getProgramParameter(a,35721),b=0;b<d;++b)a.Bc=Math.max(a.Bc,M.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.Bc}else if(35381==b){if(!a.Cc)for(d=M.getProgramParameter(a,35382),b=0;b<d;++b)a.Cc=
Math.max(a.Cc,M.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Cc}else v[c>>2]=M.getProgramParameter(a,b);else T||=1281},Kb:(a,b,c,d)=>{a=M.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(v[c>>2]=b)},ta:(a,b,c)=>{c?35716==b?(a=M.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=M.getShaderSource(R[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=M.getShaderParameter(R[a],b):T||=1281},Na:(a,b)=>{if(2>V.version)return T||=1282,0;var c=zb[a];
if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Kb().map(Nb),c=zb[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},ua:(a,b)=>{b=b?F(b):"";if(a=P[a]){var c=a,d=c.Ac,e=c.jd,h;if(!d){c.Ac=d={};c.hd={};var f=M.getProgramParameter(c,35718);for(h=0;h<f;++h){var l=M.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Ob(n);q=0<q?n.slice(0,q):n;var u=c.Nc;c.Nc+=l;e[q]=[l,u];for(n=0;n<l;++n)d[u]=n,c.hd[u++]=q}}c=a.Ac;d=0;e=b;h=Ob(b);0<h&&(d=parseInt(b.slice(h+1))>>>
0,e=b.slice(0,h));if((e=a.jd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||M.getUniformLocation(a,b)))return d}else T||=1281;return-1},hb:(a,b,c)=>{for(var d=Jb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];M.invalidateFramebuffer(a,d)},wa:a=>{a=P[a];M.linkProgram(a);a.Ac=0;a.jd={}},Oa:(a,b)=>{3317==a?Ab=b:3314==a&&(Bb=b);M.pixelStorei(a,b)},I:(a,b)=>M.polygonOffset(a,b),jb:a=>M.readBuffer(a),Gb:(a,b,c,d,e)=>M.renderbufferStorageMultisample(a,b,c,d,e),C:(a,b,c)=>{M.samplerParameterf(S[a],b,c)},g:(a,b,c)=>{M.samplerParameteri(S[a],
b,c)},qa:(a,b,c,d)=>M.scissor(a,b,c,d),Nb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=w[c+4*h>>2])?F(f,d?w[d+4*h>>2]:void 0):"";e+=f}M.shaderSource(R[a],e)},La:(a,b,c)=>M.stencilFunc(a,b,c),oa:(a,b,c,d)=>M.stencilFuncSeparate(a,b,c,d),s:a=>M.stencilMask(a),Ka:(a,b,c)=>M.stencilOp(a,b,c),na:(a,b,c,d)=>M.stencilOpSeparate(a,b,c,d),Ca:(a,b,c,d,e)=>M.texStorage2D(a,b,c,d,e),Ba:(a,b,c,d,e,h)=>M.texStorage3D(a,b,c,d,e,h),f:(a,b,c,d,e,h,f,l,n)=>{if(2<=V.version){if(M.zc){M.texSubImage2D(a,b,c,d,e,h,f,
l,n);return}if(n){var q=Pb(l);M.texSubImage2D(a,b,c,d,e,h,f,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=Pb(l);var u=h*((Bb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*q.BYTES_PER_ELEMENT+Ab-1&-Ab);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+u>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;M.texSubImage2D(a,b,c,d,e,h,f,l,n)},D:(a,b,c,d,e,h,f,l,n,q,u)=>{if(M.zc)M.texSubImage3D(a,b,c,d,e,h,f,l,n,q,u);else if(u){var N=Pb(q);M.texSubImage3D(a,
b,c,d,e,h,f,l,n,q,N,u>>>31-Math.clz32(N.BYTES_PER_ELEMENT))}else M.texSubImage3D(a,b,c,d,e,h,f,l,n,q,null)},wb:(a,b,c)=>{if(2<=V.version)b&&M.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);M.uniform1fv(W(a),d)}},Pb:(a,b)=>{M.uniform1i(W(a),b)},sb:(a,b,c)=>{if(2<=V.version)b&&M.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=Qb[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);M.uniform1iv(W(a),d)}},vb:(a,b,c)=>
{if(2<=V.version)b&&M.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);M.uniform2fv(W(a),d)}},rb:(a,b,c)=>{if(2<=V.version)b&&M.uniform2iv(W(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Qb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);M.uniform2iv(W(a),d)}},ub:(a,b,c)=>{if(2<=V.version)b&&M.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=
0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);M.uniform3fv(W(a),d)}},qb:(a,b,c)=>{if(2<=V.version)b&&M.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Qb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);M.uniform3iv(W(a),d)}},tb:(a,b,c)=>{if(2<=V.version)b&&M.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var f=c+h;d[h]=
e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);M.uniform4fv(W(a),d)}},pb:(a,b,c)=>{if(2<=V.version)b&&M.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Qb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);M.uniform4iv(W(a),d)}},ob:(a,b,c,d)=>{if(2<=V.version)b&&M.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=
d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);M.uniformMatrix4fv(W(a),!!c,e)}},m:a=>{a=P[a];M.useProgram(a);M.ld=a},zb:(a,b)=>{M.vertexAttribDivisor(a,b)},Bb:(a,b,c,d,e)=>{M.vertexAttribIPointer(a,b,c,d,e)},Cb:(a,b,c,d,e,h)=>{M.vertexAttribPointer(a,b,c,!!d,e,h)},t:(a,b,c,d)=>
M.viewport(a,b,c,d),bb:Ea,Tb:function(){g.$c=a=>{0!=Zb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.$c)},Za:function(){g.gd=a=>{const b=a.clipboardData.getData("text");Vb(()=>{const c=Sb(b);Yb(c)})};window.addEventListener("paste",g.gd)},Ta:function(){g.Md=[];g.ad=b=>{b.stopPropagation();b.preventDefault()};g.bd=b=>{b.stopPropagation();b.preventDefault()};g.cd=b=>{b.stopPropagation();b.preventDefault()};g.dd=b=>{b.stopPropagation();b.preventDefault();const c=
b.dataTransfer.files;g.ed=c;$b(c.length);for(let e=0;e<c.length;e++)Vb(()=>{const h=Sb(c[e].name);ac(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);bc(b.clientX,b.clientY,d)};const a=g.yc;a.addEventListener("dragenter",g.ad,!1);a.addEventListener("dragleave",g.bd,!1);a.addEventListener("dragover",g.cd,!1);a.addEventListener("drop",g.dd,!1)},Rb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Sa:function(a){const b=
g.ed;return 0>a||a>=b.length?0:b[a].size},Ma:function(a,b,c,d,e){const h=new FileReader;h.onload=f=>{f=f.target.result;f.byteLength>d?cc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(f),c),cc(a,1,0,b,f.byteLength,c,d,e))};h.onerror=()=>{cc(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(g.ed[a])},Ha:function(a,b){0!==b&&(document.title=b?F(b):"");a=a?F(a):"";void 0!==g.canvas&&("object"===typeof g.canvas?bb[a]=g.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));g.yc=G(a);g.yc||console.warn("sokol_app.h: can't find html5_canvas_selector ",
a);g.yc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Sb:function(){window.removeEventListener("beforeunload",g.$c)},Ua:function(){window.removeEventListener("paste",g.gd)},Ja:function(){const a=g.yc;a.removeEventListener("dragenter",g.ad);a.removeEventListener("dragleave",g.bd);a.removeEventListener("dragover",g.cd);a.removeEventListener("drop",g.dd)},u:function(){g.yc&&g.yc.requestPointerLock&&g.yc.requestPointerLock()},Lb:function(a,b,c){const d=
document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(t.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},_a:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];Vb(()=>{const e=Sb(c),h=Sb(d);fc(e,h)})}},ab:function(){return g.wc?
g.wc.bufferSize:0},Ab:function(a,b,c){g.qc=null;g.wc=null;"undefined"!==typeof AudioContext?g.qc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.qc=null,console.log("sokol_audio.h: no WebAudio support"));return g.qc?(console.log("sokol_audio.h: sample rate ",g.qc.sampleRate),g.wc=g.qc.createScriptProcessor(c,0,b),g.wc.onaudioprocess=d=>{const e=d.outputBuffer.length,h=ec(e);if(h){const f=d.outputBuffer.numberOfChannels;for(let l=0;l<f;l++){const n=d.outputBuffer.getChannelData(l);for(let q=
0;q<e;q++)n[q]=x[(h>>2)+(f*q+l)]}}},g.wc.connect(g.qc.destination),a=()=>{g.qc&&"suspended"===g.qc.state&&g.qc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},fb:function(){return g.qc?g.qc.sampleRate:0},ma:function(){const a=g.qc;null!==a&&(g.wc&&g.wc.disconnect(),a.close(),g.qc=null,g.wc=null)},$a:function(){if(g.qc)return"suspended"===g.qc.state?1:0},y:function(a,b,c,d,e,h){const f=
b?F(b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(f,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(n=>{n=new Uint8Array(n);n.length<=h?(t.set(n,e),hc(a,d,n.length)):jc(a)}).catch(n=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,n);kc(a)}):ic(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,l);kc(a)})},la:function(a,b){const c=b?F(b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),
kc(a)):gc(a,Number(d))):ic(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);kc(a)})},ka:function(a,b){b=b?F(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;na=Z.Ub;qa();eb=Z.mc;c=Z;g._fs_emsc_alloc=c.Wb;L=c.Xb;g._fs_emsc_load_snapshot_callback=c.Yb;g.__sapp_emsc_onpaste=Yb=c.Zb;g.__sapp_html5_get_ask_leave_site=Zb=c._b;g.__sapp_emsc_begin_drop=$b=c.$b;g.__sapp_emsc_drop=ac=c.ac;g.__sapp_emsc_end_drop=bc=c.bc;g.__sapp_emsc_invoke_fetch_cb=cc=c.cc;g._main=dc=c.dc;g.__saudio_emsc_pull=ec=c.ec;g.__sargs_add_kvp=fc=c.fc;g.__sfetch_emsc_head_response=gc=c.gc;g.__sfetch_emsc_get_response=hc=c.hc;g.__sfetch_emsc_failed_http_status=
ic=c.ic;g.__sfetch_emsc_failed_buffer_too_small=jc=c.jc;g.__sfetch_emsc_failed_other=kc=c.kc;lc=c.lc;Ub=c.nc;Rb=c.oc;Tb=c.pc;z--;g.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;g.monitorRunDependencies?.(z);var b={a:mc};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});sa??=g.locateFile?g.locateFile("z9001.wasm",ia):ia+"z9001.wasm";return a((await va(b)).instance)})();
function nc(a=[]){var b=dc;a.unshift(ea);var c=a.length,d=Rb(4*(c+1)),e=d;a.forEach(f=>{w[e>>2]=Sb(f);e+=4});w[e>>2]=0;try{var h=b(c,d);Fa(h)}catch(f){Da(f)}}
function oc(a=da){function b(){g.calledRun=!0;if(!p){Z.Vb();g.onRuntimeInitialized?.();g.noInitialRun||nc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();ya.push(c)}xa(ya)}}if(0<z)A=oc;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Aa();xa(za);0<z?A=oc:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();oc();
