var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,k="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,m="",ha,ia,ja;
if(fa){var fs=require("fs"),ka=require("path");m=k?ka.dirname(m)+"/":__dirname+"/";ha=(a,b)=>{a=a.startsWith("file://")?new URL(a):ka.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ja=a=>{a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a};ia=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ka.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,h)=>{e?c(e):b(d?h.buffer:h)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=
typeof module&&(module.exports=g);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof la||a.context instanceof la))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",a=>{throw a;});da=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(ea||k)k?m=self.location.href:"undefined"!=typeof document&&document.currentScript&&(m=document.currentScript.src),m=0!==m.indexOf("blob:")?m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+
1):"",ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},k&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ma=g.print||console.log.bind(console),r=g.printErr||console.warn.bind(console);
Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var t;g.wasmBinary&&(t=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&na("no native wasm support detected");var oa,pa=!1,qa,v,ra,sa,w,x,y,z;
function ta(){var a=oa.buffer;g.HEAP8=qa=new Int8Array(a);g.HEAP16=ra=new Int16Array(a);g.HEAP32=w=new Int32Array(a);g.HEAPU8=v=new Uint8Array(a);g.HEAPU16=sa=new Uint16Array(a);g.HEAPU32=x=new Uint32Array(a);g.HEAPF32=y=new Float32Array(a);g.HEAPF64=z=new Float64Array(a)}var ua,va=[],wa=[],xa=[],ya=[],za=[];function Aa(){var a=g.preRun.shift();va.unshift(a)}var A=0,Ba=null,B=null;
function na(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";r(a);pa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ca(a){return a.startsWith("data:application/octet-stream;base64,")}var C;C="zx-ui.wasm";if(!Ca(C)){var Da=C;C=g.locateFile?g.locateFile(Da,m):m+Da}function Ea(a){try{if(a==C&&t)return new Uint8Array(t);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}catch(b){na(b)}}
function Fa(a){if(!t&&(ea||k)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ea(a));if(ia)return new Promise((b,c)=>{ia(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ea(a))}function Ga(a,b,c){return Fa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{r("failed to asynchronously prepare wasm: "+d);na(d)})}
function Ha(a,b){var c=C;t||"function"!=typeof WebAssembly.instantiateStreaming||Ca(c)||c.startsWith("file://")||fa||"function"!=typeof fetch?Ga(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){r("wasm streaming compile failed: "+e);r("falling back to ArrayBuffer instantiation");return Ga(c,a,b)}))}function la(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Ia(a){for(;0<a.length;)a.shift()(g)}var Ja="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ka(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ja)return Ja.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a,b){return a?Ka(v,a,b):""}
function La(a){var b=Ma();a();Na(b)}var Oa=0;function Pa(){for(var a=E.length-1;0<=a;--a)Qa(a);E=[];Ra=[]}var Ra=[];function Sa(){if(Oa&&Ta.Fc)for(var a=0;a<Ra.length;++a){var b=Ra[a];Ra.splice(a,1);--a;b.sd.apply(null,b.hd)}}var E=[];function Qa(a){var b=E[a];b.target.removeEventListener(b.wc,b.cd,b.xc);E.splice(a,1)}
function F(a){function b(d){++Oa;Ta=a;Sa();a.zc(d);Sa();--Oa}if(a.yc)a.cd=b,a.target.addEventListener(a.wc,b,a.xc),E.push(a),Ua||(ya.push(Pa),Ua=!0);else for(var c=0;c<E.length;++c)E[c].target==a.target&&E[c].wc==a.wc&&Qa(c--)}function Va(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var Ua,Ta,Wa,Xa,Ya,Za,$a,ab,bb,cb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];
function G(a){a=2<a?D(a):a;return cb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function db(a){return 0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}var eb;eb=fa?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var fb=[];function H(a){var b=fb[a];b||(a>=fb.length&&(fb.length=a+1),fb[a]=b=ua.get(a));return b}
function I(a,b,c){var d=v;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var l=a.charCodeAt(++h);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e}
function gb(a,b,c,d,e,h){Wa||(Wa=J(256));a={target:G(a),wc:h,yc:d,zc:function(f=event){var l=f.target.id?f.target.id:"",n=Wa;I(Va(f.target),n+0,128);I(l,n+128,128);H(d)(e,n,b)&&f.preventDefault()},xc:c};F(a)}
function hb(a,b,c,d,e,h){Xa||(Xa=J(176));a={target:G(a),Fc:!0,wc:h,yc:d,zc:function(f){var l=Xa;z[l>>3]=f.timeStamp;var n=l>>2;w[n+2]=f.location;w[n+3]=f.ctrlKey;w[n+4]=f.shiftKey;w[n+5]=f.altKey;w[n+6]=f.metaKey;w[n+7]=f.repeat;w[n+8]=f.charCode;w[n+9]=f.keyCode;w[n+10]=f.which;I(f.key||"",l+44,32);I(f.code||"",l+76,32);I(f.char||"",l+108,32);I(f.locale||"",l+140,32);H(d)(e,l,b)&&f.preventDefault()},xc:c};F(a)}
function ib(a,b,c){z[a>>3]=b.timeStamp;a>>=2;w[a+2]=b.screenX;w[a+3]=b.screenY;w[a+4]=b.clientX;w[a+5]=b.clientY;w[a+6]=b.ctrlKey;w[a+7]=b.shiftKey;w[a+8]=b.altKey;w[a+9]=b.metaKey;ra[2*a+20]=b.button;ra[2*a+21]=b.buttons;w[a+11]=b.movementX;w[a+12]=b.movementY;c=db(c);w[a+13]=b.clientX-c.left;w[a+14]=b.clientY-c.top}
function K(a,b,c,d,e,h){Ya||(Ya=J(72));a=G(a);F({target:a,Fc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,wc:h,yc:d,zc:function(f=event){ib(Ya,f,a);H(d)(e,Ya,b)&&f.preventDefault()},xc:c})}function jb(a,b,c,d,e){Za||(Za=J(260));F({target:a,wc:e,yc:d,zc:function(h=event){var f=Za,l=document.pointerLockElement||document.Ec||document.ad||document.$c;w[f>>2]=!!l;var n=l&&l.id?l.id:"";I(Va(l),f+4,128);I(n,f+132,128);H(d)(20,f,b)&&h.preventDefault()},xc:c})}
function kb(a,b,c,d,e){F({target:a,wc:e,yc:d,zc:function(h=event){H(d)(38,0,b)&&h.preventDefault()},xc:c})}function lb(a,b,c,d){$a||($a=J(36));a=G(a);F({target:a,wc:"resize",yc:d,zc:function(e=event){if(e.target==a){var h=document.body;if(h){var f=$a;w[f>>2]=e.detail;w[f+4>>2]=h.clientWidth;w[f+8>>2]=h.clientHeight;w[f+12>>2]=innerWidth;w[f+16>>2]=innerHeight;w[f+20>>2]=outerWidth;w[f+24>>2]=outerHeight;w[f+28>>2]=pageXOffset;w[f+32>>2]=pageYOffset;H(d)(10,f,b)&&e.preventDefault()}}},xc:c})}
function mb(a,b,c,d,e,h){ab||(ab=J(1696));a=G(a);F({target:a,Fc:"touchstart"==h||"touchend"==h,wc:h,yc:d,zc:function(f){for(var l,n={},p=f.touches,q=0;q<p.length;++q)l=p[q],l.Oc=l.Qc=0,n[l.identifier]=l;for(q=0;q<f.changedTouches.length;++q)l=f.changedTouches[q],l.Oc=1,n[l.identifier]=l;for(q=0;q<f.targetTouches.length;++q)n[f.targetTouches[q].identifier].Qc=1;p=ab;z[p>>3]=f.timeStamp;var u=p>>2;w[u+3]=f.ctrlKey;w[u+4]=f.shiftKey;w[u+5]=f.altKey;w[u+6]=f.metaKey;u+=7;var qb=db(a),rb=0;for(q in n)if(l=
n[q],w[u]=l.identifier,w[u+1]=l.screenX,w[u+2]=l.screenY,w[u+3]=l.clientX,w[u+4]=l.clientY,w[u+5]=l.pageX,w[u+6]=l.pageY,w[u+7]=l.Oc,w[u+8]=l.Qc,w[u+9]=l.clientX-qb.left,w[u+10]=l.clientY-qb.top,u+=13,31<++rb)break;w[p+8>>2]=rb;H(d)(e,p,b)&&f.preventDefault()},xc:c})}
function nb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,f){b.drawElementsInstancedANGLE(c,d,e,h,f)})}
function ob(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function pb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function sb(a){a.kd=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function tb(a){a.md=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function ub(a){a.od=a.getExtension("WEBGL_multi_draw")}var vb=1,wb=[],L=[],xb=[],M=[],N=[],O=[],yb=[],zb=[],Ab={},Bb=4;function P(a){Cb||(Cb=a)}function Db(a){for(var b=vb++,c=a.length;c<b;c++)a[c]=null;return b}
function Eb(a,b){a.Ec||(a.Ec=a.getContext,a.getContext=function(d,e){e=a.Ec(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Pc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Fb(c,b):0}function Fb(a,b){var c=Db(zb),d={ld:c,attributes:b,version:b.Pc,Jc:a};a.canvas&&(a.canvas.gd=d);zb[c]=d;("undefined"==typeof b.Nc||b.Nc)&&Gb(d);return c}
function Gb(a){a||(a=Q);if(!a.ed){a.ed=!0;var b=a.Jc;nb(b);ob(b);pb(b);sb(b);tb(b);2<=a.version&&(b.Mc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Mc)b.Mc=b.getExtension("EXT_disjoint_timer_query");ub(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Cb,Q;function Hb(a,b,c,d,e,h){a={target:G(a),wc:h,yc:d,zc:(f=event)=>{H(d)(e,0,b)&&f.preventDefault()},xc:c};F(a)}
function Ib(a,b,c,d){bb||(bb=J(104));F({target:a,Fc:!0,wc:"wheel",yc:d,zc:function(e=event){var h=bb;ib(h,e,a);z[h+72>>3]=e.deltaX;z[h+80>>3]=e.deltaY;z[h+88>>3]=e.deltaZ;w[h+96>>2]=e.deltaMode;H(d)(9,h,b)&&e.preventDefault()},xc:c})}var Jb=["default","low-power","high-performance"],Kb=[null,[],[]],Lb=[];function R(a,b,c,d){for(var e=0;e<a;e++){var h=S[c](),f=h&&Db(d);h?(h.name=f,d[f]=h):P(1282);w[b+4*e>>2]=f}}
function Mb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Q.version){P(1282);return}c=2*(S.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>Q.version){P(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":P(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:P(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){P(1280);r("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:P(1280);r("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}w[b>>2]=c}else P(1281)}
function Nb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}function Ob(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function T(a){a-=5120;return 0==a?qa:1==a?v:2==a?ra:4==a?w:6==a?y:5==a||28922==a||28520==a||30779==a||30782==a?x:sa}function U(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}
function Pb(a,b,c,d,e){a=T(a);var h=U(a),f=Bb;return a.subarray(e>>h,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<h)+f-1&-f)>>h)}function V(a){var b=S.bd;if(b){var c=b.Dc[a];"number"==typeof c&&(b.Dc[a]=c=S.getUniformLocation(b,b.Yc[a]+(0<c?"["+c+"]":"")));return c}P(1282)}var W=[],X=[];function Qb(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);pa=!0}da(a,new la(a))}function Y(a){var b=Nb(a)+1,c=Rb(b);I(a,c,b);return c}for(var S,Z=0;32>Z;++Z)Lb.push(Array(Z));
var Sb=new Float32Array(288);for(Z=0;288>Z;++Z)W[Z]=Sb.subarray(0,Z+1);var Tb=new Int32Array(288);for(Z=0;288>Z;++Z)X[Z]=Tb.subarray(0,Z+1);
var ic={na:function(){return 0},mb:function(){return 0},nb:function(){},g:function(){na("")},ha:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},ia:function(a,b,c){a=G(a);if(!a)return-4;a=db(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},A:eb,jb:function(a,b,c){v.copyWithin(a,b,b+c)},Za:function(a,b){function c(d){H(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ib:function(a){var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*
(1+.2/c);d=Math.min(d,a+100663296);var e=Math,h=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var f=oa.buffer;try{oa.grow(h.call(e,2147483648,d)-f.byteLength+65535>>>16);ta();var l=1;break a}catch(n){}l=void 0}if(l)return!0}return!1},R:function(a,b,c,d){gb(a,b,c,d,12,"blur");return 0},ga:function(a,b,c){a=G(a);if(!a)return-4;a.width=b;a.height=c;return 0},S:function(a,b,c,d){gb(a,b,c,d,13,"focus");return 0},$:function(a,b,c,d){hb(a,b,c,d,2,"keydown");return 0},Z:function(a,b,c,d){hb(a,b,c,d,1,
"keypress");return 0},_:function(a,b,c,d){hb(a,b,c,d,3,"keyup");return 0},fa:function(a,b,c,d){K(a,b,c,d,5,"mousedown");return 0},ca:function(a,b,c,d){K(a,b,c,d,33,"mouseenter");return 0},ba:function(a,b,c,d){K(a,b,c,d,34,"mouseleave");return 0},da:function(a,b,c,d){K(a,b,c,d,8,"mousemove");return 0},ea:function(a,b,c,d){K(a,b,c,d,6,"mouseup");return 0},U:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Ec||document.body.ad||document.body.$c))return-1;
a=G(a);if(!a)return-4;jb(a,b,c,d,"pointerlockchange");jb(a,b,c,d,"mozpointerlockchange");jb(a,b,c,d,"webkitpointerlockchange");jb(a,b,c,d,"mspointerlockchange");return 0},T:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Ec||document.body.ad||document.body.$c))return-1;a=G(a);if(!a)return-4;kb(a,b,c,d,"pointerlockerror");kb(a,b,c,d,"mozpointerlockerror");kb(a,b,c,d,"webkitpointerlockerror");kb(a,b,c,d,"mspointerlockerror");return 0},_a:function(a,b,c,d){lb(a,b,c,
d);return 0},V:function(a,b,c,d){mb(a,b,c,d,25,"touchcancel");return 0},W:function(a,b,c,d){mb(a,b,c,d,23,"touchend");return 0},X:function(a,b,c,d){mb(a,b,c,d,24,"touchmove");return 0},Y:function(a,b,c,d){mb(a,b,c,d,22,"touchstart");return 0},Q:function(a,b,c,d){Hb(a,b,c,d,31,"webglcontextlost");return 0},P:function(a,b,c,d){Hb(a,b,c,d,32,"webglcontextrestored");return 0},aa:function(a,b,c,d){a=G(a);return"undefined"!=typeof a.onwheel?(Ib(a,b,c,d),0):-1},Xa:function(a,b){b>>=2;b={alpha:!!w[b],depth:!!w[b+
1],stencil:!!w[b+2],antialias:!!w[b+3],premultipliedAlpha:!!w[b+4],preserveDrawingBuffer:!!w[b+5],powerPreference:Jb[w[b+6]],failIfMajorPerformanceCaveat:!!w[b+7],Pc:w[b+8],nd:w[b+9],Nc:w[b+10],dd:w[b+11],pd:w[b+12],qd:w[b+13]};a=G(a);return!a||b.dd?0:Eb(a,b)},Va:function(a,b){a=zb[a];b=D(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&nb(S);"OES_vertex_array_object"==b&&ob(S);"WEBGL_draw_buffers"==b&&pb(S);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&sb(S);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==
b&&tb(S);"WEBGL_multi_draw"==b&&ub(S);return!!a.Jc.getExtension(b)},Ya:function(a){a>>=2;for(var b=0;14>b;++b)w[a+b]=0;w[a]=w[a+1]=w[a+3]=w[a+4]=w[a+8]=w[a+10]=1},Wa:function(a){Q=zb[a];g.jd=S=Q&&Q.Jc;return!a||S?0:-5},ma:function(){return 52},lb:function(){return 52},hb:function(){return 70},kb:function(a,b,c,d){for(var e=0,h=0;h<c;h++){var f=x[b>>2],l=x[b+4>>2];b+=8;for(var n=0;n<l;n++){var p=v[f+n],q=Kb[a];0===p||10===p?((1===a?ma:r)(Ka(q,0)),q.length=0):q.push(p)}e+=l}x[d>>2]=e;return 0},j:function(a,
b,c){const d=D(a);console.log("fs_js_load_snapshot: called with",d,b);let e;try{e=window.indexedDB.open("chips",1)}catch(h){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+h)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");e.result.createObjectStore("store")};e.onsuccess=()=>{var h=e.result;let f;try{f=h.transaction(["store"],"readwrite")}catch(p){console.log("fs_js_load_snapshot: db.transaction failed with",p);return}h=f.objectStore("store");let l=d+"_"+b,
n=h.get(l);n.onsuccess=()=>{if(void 0!==n.result){let p=n.result.length;console.log("fs_js_load_snapshot:",l,"successfully loaded",p,"bytes");let q=Ub(p);v.set(n.result,q);Vb(c,q,p)}else console.log("fs_js_load_snapshot:",l,"does not exist"),Vb(c,0,0)};n.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",l)};f.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},Zb:function(a,b,c,d){const e=D(a);
console.log("fs_js_save_snapshot: called with",e,b);let h;try{h=window.indexedDB.open("chips",1)}catch(f){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+f);return}h.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");h.result.createObjectStore("store")};h.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");let f=h.result.transaction(["store"],"readwrite");var l=f.objectStore("store");let n=e+"_"+b;l=l.put(v.subarray(c,c+d),n);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",
n,"successfully stored")};l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",n)};f.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};h.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},f:function(a){S.activeTexture(a)},za:function(a,b){S.attachShader(L[a],O[b])},b:function(a,b){35051==a?S.Lc=b:35052==a&&(S.Bc=b);S.bindBuffer(a,wb[b])},l:function(a,b){S.bindFramebuffer(a,xb[b])},Fa:function(a,b){S.bindRenderbuffer(a,M[b])},a:function(a,b){S.bindTexture(a,
N[b])},M:function(a){S.bindVertexArray(yb[a])},I:function(a,b,c,d){S.blendColor(a,b,c,d)},J:function(a,b){S.blendEquationSeparate(a,b)},K:function(a,b,c,d){S.blendFuncSeparate(a,b,c,d)},rb:function(a,b,c,d,e,h,f,l,n,p){S.blitFramebuffer(a,b,c,d,e,h,f,l,n,p)},Ia:function(a,b,c,d){2<=Q.version?c&&b?S.bufferData(a,v,d,c,b):S.bufferData(a,b,d):S.bufferData(a,c?v.subarray(c,c+b):b,d)},q:function(a,b,c,d){2<=Q.version?c&&S.bufferSubData(a,b,v,d,c):S.bufferSubData(a,b,v.subarray(d,d+c))},ta:function(a){return S.checkFramebufferStatus(a)},
Mb:function(a,b,c,d){S.clearBufferfi(a,b,c,d)},ra:function(a,b,c){S.clearBufferfv(a,b,y,c>>2)},Lb:function(a,b,c){S.clearBufferiv(a,b,w,c>>2)},n:function(a,b,c,d){S.colorMask(!!a,!!b,!!c,!!d)},Qb:function(a){S.compileShader(O[a])},Ca:function(a,b,c,d,e,h,f,l){2<=Q.version?S.Bc||!f?S.compressedTexImage2D(a,b,c,d,e,h,f,l):S.compressedTexImage2D(a,b,c,d,e,h,v,l,f):S.compressedTexImage2D(a,b,c,d,e,h,l?v.subarray(l,l+f):null)},Aa:function(a,b,c,d,e,h,f,l,n){S.Bc?S.compressedTexImage3D(a,b,c,d,e,h,f,l,
n):S.compressedTexImage3D(a,b,c,d,e,h,f,v,n,l)},Wb:function(){var a=Db(L),b=S.createProgram();b.name=a;b.Ic=b.Gc=b.Hc=0;b.Kc=1;L[a]=b;return a},Tb:function(a){var b=Db(O);O[b]=S.createShader(a);return b},F:function(a){S.cullFace(a)},Ra:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=wb[d];e&&(S.deleteBuffer(e),e.name=0,wb[d]=null,d==S.Lc&&(S.Lc=0),d==S.Bc&&(S.Bc=0))}},d:function(a,b){for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=xb[d];e&&(S.deleteFramebuffer(e),e.name=0,xb[d]=null)}},y:function(a){if(a){var b=
L[a];b?(S.deleteProgram(b),b.name=0,L[a]=null):P(1281)}},N:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=M[d];e&&(S.deleteRenderbuffer(e),e.name=0,M[d]=null)}},D:function(a){if(a){var b=O[a];b?(S.deleteShader(b),O[a]=null):P(1281)}},O:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=N[d];e&&(S.deleteTexture(e),e.name=0,N[d]=null)}},Qa:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2];S.deleteVertexArray(yb[d]);yb[d]=null}},x:function(a){S.depthFunc(a)},w:function(a){S.depthMask(!!a)},
e:function(a){S.disable(a)},L:function(a){S.disableVertexAttribArray(a)},tb:function(a,b,c){S.drawArrays(a,b,c)},ub:function(a,b,c,d){S.drawArraysInstanced(a,b,c,d)},sa:function(a,b){for(var c=Lb[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];S.drawBuffers(c)},vb:function(a,b,c,d){S.drawElements(a,b,c,d)},wb:function(a,b,c,d,e){S.drawElementsInstanced(a,b,c,d,e)},i:function(a){S.enable(a)},Hb:function(a){S.enableVertexAttribArray(a)},ua:function(a,b,c,d){S.framebufferRenderbuffer(a,b,c,M[d])},m:function(a,b,c,d,
e){S.framebufferTexture2D(a,b,c,N[d],e)},C:function(a,b,c,d,e){S.framebufferTextureLayer(a,b,N[c],d,e)},G:function(a){S.frontFace(a)},Ja:function(a,b){R(a,b,"createBuffer",wb)},va:function(a,b){R(a,b,"createFramebuffer",xb)},Ga:function(a,b){R(a,b,"createRenderbuffer",M)},Da:function(a,b){R(a,b,"createTexture",N)},Oa:function(a,b){R(a,b,"createVertexArray",yb)},Ob:function(a,b){return S.getAttribLocation(L[a],D(b))},c:function(a,b){Mb(a,b)},Ub:function(a,b,c,d){a=S.getProgramInfoLog(L[a]);null===
a&&(a="(unknown error)");b=0<b&&d?I(a,d,b):0;c&&(w[c>>2]=b)},ya:function(a,b,c){if(c)if(a>=vb)P(1281);else if(a=L[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.Ic)for(b=0;b<S.getProgramParameter(a,35718);++b)a.Ic=Math.max(a.Ic,S.getActiveUniform(a,b).name.length+1);w[c>>2]=a.Ic}else if(35722==b){if(!a.Gc)for(b=0;b<S.getProgramParameter(a,35721);++b)a.Gc=Math.max(a.Gc,S.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.Gc}else if(35381==
b){if(!a.Hc)for(b=0;b<S.getProgramParameter(a,35382);++b)a.Hc=Math.max(a.Hc,S.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.Hc}else w[c>>2]=S.getProgramParameter(a,b);else P(1281)},Pb:function(a,b,c,d){a=S.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?I(a,d,b):0;c&&(w[c>>2]=b)},wa:function(a,b,c){c?35716==b?(a=S.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(O[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=S.getShaderParameter(O[a],
b):P(1281)},Ta:function(a,b){if(2>Q.version)return P(1282),0;var c=Ab[a];if(c)return 0>b||b>=c.length?(P(1281),0):c[b];switch(a){case 7939:return c=S.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){var e=Nb(d)+1,h=J(e);h&&I(d,h,e);return h}),c=Ab[a]=c,0>b||b>=c.length?(P(1281),0):c[b];default:return P(1280),0}},u:function(a,b){b=D(b);if(a=L[a]){var c=a,d=c.Dc,e=c.Zc,h;if(!d)for(c.Dc=d={},c.Yc={},h=0;h<S.getProgramParameter(c,35718);++h){var f=S.getActiveUniform(c,
h);var l=f.name;f=f.size;var n=Ob(l);n=0<n?l.slice(0,n):l;var p=c.Kc;c.Kc+=f;e[n]=[f,p];for(l=0;l<f;++l)d[p]=l,c.Yc[p++]=n}c=a.Dc;d=0;e=b;h=Ob(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Zc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else P(1281);return-1},qb:function(a,b,c){for(var d=Lb[b],e=0;e<b;e++)d[e]=w[c+4*e>>2];S.invalidateFramebuffer(a,d)},Vb:function(a){a=L[a];S.linkProgram(a);a.Dc=0;a.Zc={}},Na:function(a,b){3317==a&&(Bb=b);S.pixelStorei(a,b)},
H:function(a,b){S.polygonOffset(a,b)},sb:function(a){S.readBuffer(a)},Ea:function(a,b,c,d,e){S.renderbufferStorageMultisample(a,b,c,d,e)},p:function(a,b,c,d){S.scissor(a,b,c,d)},Rb:function(a,b,c,d){for(var e="",h=0;h<b;++h){var f=d?w[d+4*h>>2]:-1;e+=D(w[c+4*h>>2],0>f?void 0:f)}S.shaderSource(O[a],e)},Ma:function(a,b,c){S.stencilFunc(a,b,c)},qa:function(a,b,c,d){S.stencilFuncSeparate(a,b,c,d)},v:function(a){S.stencilMask(a)},La:function(a,b,c){S.stencilOp(a,b,c)},pa:function(a,b,c,d){S.stencilOpSeparate(a,
b,c,d)},Ba:function(a,b,c,d,e,h,f,l,n){if(2<=Q.version)if(S.Bc)S.texImage2D(a,b,c,d,e,h,f,l,n);else if(n){var p=T(l);S.texImage2D(a,b,c,d,e,h,f,l,p,n>>U(p))}else S.texImage2D(a,b,c,d,e,h,f,l,null);else S.texImage2D(a,b,c,d,e,h,f,l,n?Pb(l,f,d,e,n):null)},Xb:function(a,b,c,d,e,h,f,l,n,p){if(S.Bc)S.texImage3D(a,b,c,d,e,h,f,l,n,p);else if(p){var q=T(n);S.texImage3D(a,b,c,d,e,h,f,l,n,q,p>>U(q))}else S.texImage3D(a,b,c,d,e,h,f,l,n,null)},E:function(a,b,c){S.texParameterf(a,b,c)},h:function(a,b,c){S.texParameteri(a,
b,c)},pb:function(a,b,c,d,e,h,f,l,n){if(2<=Q.version)if(S.Bc)S.texSubImage2D(a,b,c,d,e,h,f,l,n);else if(n){var p=T(l);S.texSubImage2D(a,b,c,d,e,h,f,l,p,n>>U(p))}else S.texSubImage2D(a,b,c,d,e,h,f,l,null);else p=null,n&&(p=Pb(l,f,e,h,n)),S.texSubImage2D(a,b,c,d,e,h,f,l,p)},ob:function(a,b,c,d,e,h,f,l,n,p,q){if(S.Bc)S.texSubImage3D(a,b,c,d,e,h,f,l,n,p,q);else if(q){var u=T(p);S.texSubImage3D(a,b,c,d,e,h,f,l,n,p,u,q>>U(u))}else S.texSubImage3D(a,b,c,d,e,h,f,l,n,p,null)},Gb:function(a,b,c){if(2<=Q.version)b&&
S.uniform1fv(V(a),y,c>>2,b);else{if(288>=b)for(var d=W[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);S.uniform1fv(V(a),d)}},xa:function(a,b){S.uniform1i(V(a),b)},Cb:function(a,b,c){if(2<=Q.version)b&&S.uniform1iv(V(a),w,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);S.uniform1iv(V(a),d)}},Fb:function(a,b,c){if(2<=Q.version)b&&S.uniform2fv(V(a),y,c>>2,2*b);else{if(144>=b)for(var d=W[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+
1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);S.uniform2fv(V(a),d)}},Bb:function(a,b,c){if(2<=Q.version)b&&S.uniform2iv(V(a),w,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);S.uniform2iv(V(a),d)}},Eb:function(a,b,c){if(2<=Q.version)b&&S.uniform3fv(V(a),y,c>>2,3*b);else{if(96>=b)for(var d=W[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);
S.uniform3fv(V(a),d)}},Ab:function(a,b,c){if(2<=Q.version)b&&S.uniform3iv(V(a),w,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);S.uniform3iv(V(a),d)}},Db:function(a,b,c){if(2<=Q.version)b&&S.uniform4fv(V(a),y,c>>2,4*b);else{if(72>=b){var d=W[4*b-1],e=y;c>>=2;for(var h=0;h<4*b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=y.subarray(c>>2,c+16*b>>2);S.uniform4fv(V(a),
d)}},zb:function(a,b,c){if(2<=Q.version)b&&S.uniform4iv(V(a),w,c>>2,4*b);else{if(72>=b)for(var d=X[4*b-1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);S.uniform4iv(V(a),d)}},xb:function(a,b,c,d){if(2<=Q.version)b&&S.uniformMatrix4fv(V(a),!!c,y,d>>2,16*b);else{if(18>=b){var e=W[16*b-1],h=y;d>>=2;for(var f=0;f<16*b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];
e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=y.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(V(a),!!c,e)}},o:function(a){a=L[a];S.useProgram(a);S.bd=a},Ib:function(a,b){S.vertexAttribDivisor(a,b)},Kb:function(a,b,c,d,e,h){S.vertexAttribPointer(a,b,c,!!d,e,h)},k:function(a,b,c,d){S.viewport(a,b,c,d)},Ua:function(){g.Rc=a=>{0!=Wb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",
g.Rc)},Pa:function(){g.Xc=a=>{const b=a.clipboardData.getData("text");La(()=>{const c=Y(b);Xb(c)})};window.addEventListener("paste",g.Xc)},Yb:function(a){g.rd=[];a=D(a);a=document.getElementById(a);g.Sc=b=>{b.stopPropagation();b.preventDefault()};g.Tc=b=>{b.stopPropagation();b.preventDefault()};g.Uc=b=>{b.stopPropagation();b.preventDefault()};g.Vc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Wc=c;Yb(c.length);for(let d=0;d<c.length;d++)La(()=>{const e=Y(c[d].name);Zb(d,
e)});$b(b.clientX,b.clientY)};a.addEventListener("dragenter",g.Sc,!1);a.addEventListener("dragleave",g.Tc,!1);a.addEventListener("dragover",g.Uc,!1);a.addEventListener("drop",g.Vc,!1)},fb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},t:function(){const a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){ac()});document.body.append(a)},Sb:function(a){const b=
g.Wc;return 0>a||a>=b.length?0:b[a].size},Nb:function(a,b,c,d,e){const h=new FileReader;h.onload=f=>{f=f.target.result;f.byteLength>d?bc(a,0,1,b,0,c,d,e):(v.set(new Uint8Array(f),c),bc(a,1,0,b,f.byteLength,c,d,e))};h.onerror=()=>{bc(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(g.Wc[a])},s:function(){document.getElementById("_sokol_app_input_element").focus()},yb:function(a){a=D(a);g.Cc=document.getElementById(a);g.Cc||console.log("sokol_app.h: invalid target:"+a);g.Cc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+
a)},Sa:function(){window.removeEventListener("beforeunload",g.Rc)},Ka:function(){window.removeEventListener("paste",g.Xc)},Jb:function(a){a=D(a);a=document.getElementById(a);a.removeEventListener("dragenter",g.Sc);a.removeEventListener("dragleave",g.Tc);a.removeEventListener("dragover",g.Uc);a.removeEventListener("drop",g.Vc)},B:function(){g.Cc&&g.Cc.requestPointerLock&&g.Cc.requestPointerLock()},gb:function(a,b){if(g.Cc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;
case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.Cc.style.cursor=a}},eb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(v.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");
a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},r:function(){document.getElementById("_sokol_app_input_element").blur()},Ha:function(a){a=D(a);const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();
document.execCommand("copy");document.body.removeChild(b)},$a:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];La(()=>{const e=Y(c),h=Y(d);cc(e,h)})}},bb:function(){return g.Ac?g.Ac.bufferSize:0},db:function(a,b,c){g.vc=null;g.Ac=null;"undefined"!==typeof AudioContext?g.vc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.vc=null,console.log("sokol_audio.h: no WebAudio support"));return g.vc?
(console.log("sokol_audio.h: sample rate ",g.vc.sampleRate),g.Ac=g.vc.createScriptProcessor(c,0,b),g.Ac.onaudioprocess=d=>{const e=d.outputBuffer.length,h=dc(e);if(h){const f=d.outputBuffer.numberOfChannels;for(let l=0;l<f;l++){const n=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)n[p]=y[(h>>2)+(f*p+l)]}}},g.Ac.connect(g.vc.destination),a=()=>{g.vc&&"suspended"===g.vc.state&&g.vc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",
a,{once:!0}),1):0},cb:function(){return g.vc?g.vc.sampleRate:0},la:function(){const a=g.vc;null!==a&&(g.Ac&&g.Ac.disconnect(),a.close(),g.vc=null,g.Ac=null)},ab:function(){if(g.vc)return"suspended"===g.vc.state?1:0},z:function(a,b,c,d,e,h){b=D(b);const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const l=0<d;l&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!l){const n=new Uint8Array(f.response),
p=n.length;p<=h?(v.set(n,e),ec(a,d,p)):fc(a)}else gc(a,f.status)};f.send()},ka:function(a,b){b=D(b);const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");hc(a,d)}else gc(a,c.status)};c.send()},oa:function(){return navigator.userAgent.includes("Macintosh")?1:0},ja:function(a,b){b=D(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);
break;default:console.info(b)}}};
(function(){function a(c){c=c.exports;g.asm=c;oa=g.asm._b;ta();ua=g.asm.rc;wa.unshift(g.asm.$b);A--;g.monitorRunDependencies&&g.monitorRunDependencies(A);if(0==A&&(null!==Ba&&(clearInterval(Ba),Ba=null),B)){var d=B;B=null;d()}return c}var b={a:ic};A++;g.monitorRunDependencies&&g.monitorRunDependencies(A);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return r("Module.instantiateWasm callback failed with error: "+c),!1}Ha(b,function(c){a(c.instance)});return{}})();
var Ub=g._fs_emsc_alloc=function(){return(Ub=g._fs_emsc_alloc=g.asm.ac).apply(null,arguments)};function J(){return(J=g.asm.bc).apply(null,arguments)}
var Vb=g._fs_emsc_load_snapshot_callback=function(){return(Vb=g._fs_emsc_load_snapshot_callback=g.asm.cc).apply(null,arguments)},ac=g.__sapp_emsc_notify_keyboard_hidden=function(){return(ac=g.__sapp_emsc_notify_keyboard_hidden=g.asm.dc).apply(null,arguments)},Xb=g.__sapp_emsc_onpaste=function(){return(Xb=g.__sapp_emsc_onpaste=g.asm.ec).apply(null,arguments)},Wb=g.__sapp_html5_get_ask_leave_site=function(){return(Wb=g.__sapp_html5_get_ask_leave_site=g.asm.fc).apply(null,arguments)},Yb=g.__sapp_emsc_begin_drop=
function(){return(Yb=g.__sapp_emsc_begin_drop=g.asm.gc).apply(null,arguments)},Zb=g.__sapp_emsc_drop=function(){return(Zb=g.__sapp_emsc_drop=g.asm.hc).apply(null,arguments)},$b=g.__sapp_emsc_end_drop=function(){return($b=g.__sapp_emsc_end_drop=g.asm.ic).apply(null,arguments)},bc=g.__sapp_emsc_invoke_fetch_cb=function(){return(bc=g.__sapp_emsc_invoke_fetch_cb=g.asm.jc).apply(null,arguments)},jc=g._main=function(){return(jc=g._main=g.asm.kc).apply(null,arguments)},dc=g.__saudio_emsc_pull=function(){return(dc=
g.__saudio_emsc_pull=g.asm.lc).apply(null,arguments)},cc=g.__sargs_add_kvp=function(){return(cc=g.__sargs_add_kvp=g.asm.mc).apply(null,arguments)},hc=g.__sfetch_emsc_head_response=function(){return(hc=g.__sfetch_emsc_head_response=g.asm.nc).apply(null,arguments)},ec=g.__sfetch_emsc_get_response=function(){return(ec=g.__sfetch_emsc_get_response=g.asm.oc).apply(null,arguments)},gc=g.__sfetch_emsc_failed_http_status=function(){return(gc=g.__sfetch_emsc_failed_http_status=g.asm.pc).apply(null,arguments)},
fc=g.__sfetch_emsc_failed_buffer_too_small=function(){return(fc=g.__sfetch_emsc_failed_buffer_too_small=g.asm.qc).apply(null,arguments)};function Ma(){return(Ma=g.asm.sc).apply(null,arguments)}function Na(){return(Na=g.asm.tc).apply(null,arguments)}function Rb(){return(Rb=g.asm.uc).apply(null,arguments)}g.___start_em_js=94996;g.___stop_em_js=107984;var kc;B=function lc(){kc||mc();kc||(B=lc)};
function nc(a=[]){var b=jc;a.unshift(ca);var c=a.length,d=Rb(4*(c+1)),e=d>>2;a.forEach(f=>{w[e++]=Y(f)});w[e]=0;try{var h=b(c,d);Qb(h)}catch(f){f instanceof la||"unwind"==f||da(1,f)}}
function mc(){var a=ba;function b(){if(!kc&&(kc=!0,g.calledRun=!0,!pa)){Ia(wa);Ia(xa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();oc&&nc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();za.unshift(c)}Ia(za)}}if(!(0<A)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Aa();Ia(va);0<A||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var oc=!0;g.noInitialRun&&(oc=!1);mc();
