var f;f||(f=typeof Module !== 'undefined' ? Module : {});var g={},k;for(k in f)f.hasOwnProperty(k)&&(g[k]=f[k]);var n=[],aa="./this.program";function r(a,b){throw b;}var t=!1,v=!1,ba=!1,ca=!1,da=!1;t="object"===typeof window;v="function"===typeof importScripts;ba=(ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!t&&!v;da=!t&&!ba&&!v;var x="",ea,y;
if(ba){x=__dirname+"/";var fa,ha;ea=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);a=fa.readFileSync(a);return b?a:a.toString()};y=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/"));n=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=f);process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;});process.on("unhandledRejection",z);r=function(a){process.exit(a)};
f.inspect=function(){return"[Emscripten Module object]"}}else if(da)"undefined"!=typeof read&&(ea=function(a){return read(a)}),y=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?n=scriptArgs:"undefined"!=typeof arguments&&(n=arguments),"function"===typeof quit&&(r=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=
console.error="undefined"!==typeof printErr?printErr:print);else if(t||v)v?x=self.location.href:document.currentScript&&(x=document.currentScript.src),x=0!==x.indexOf("blob:")?x.substr(0,x.lastIndexOf("/")+1):"",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(y=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var ja=f.print||console.log.bind(console),A=f.printErr||console.warn.bind(console);for(k in g)g.hasOwnProperty(k)&&(f[k]=g[k]);g=null;f.arguments&&(n=f.arguments);f.thisProgram&&(aa=f.thisProgram);f.quit&&(r=f.quit);var B;f.wasmBinary&&(B=f.wasmBinary);"object"!==typeof WebAssembly&&A("no native wasm support detected");var C,ka=!1;function assert(a,b){a||z("Assertion failed: "+b)}function la(a){var b=f["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function ma(a,b,c,d){var e={string:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=na(c);D(a,E,b,c)}return b},array:function(a){var b=na(a.length);F.set(a,b);return b}},h=la(a),l=[];a=0;if(d)for(var m=0;m<d.length;m++){var u=e[c[m]];u?(0===a&&(a=oa()),l[m]=u(d[m])):l[m]=d[m]}c=h.apply(null,l);c=function(a){return"string"===b?G(a):"boolean"===b?!!a:a}(c);0!==a&&pa(a);return c}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function G(a,b){if(a){var c=E,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&qa)a=qa.decode(c.subarray(a,b));else{for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var l=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|l:(e&7)<<18|h<<12|l<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}a=d}}else a="";return a}
function D(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var l=a.charCodeAt(h);if(55296<=l&&57343>=l){var m=a.charCodeAt(++h);l=65536+((l&1023)<<10)|m&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function ra(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function sa(a){var b=ra(a)+1,c=na(b);D(a,F,c,b);return c}function ta(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,F,E,ua,va,H,wa,I,J;
function xa(){f.HEAP8=F=new Int8Array(buffer);f.HEAP16=ua=new Int16Array(buffer);f.HEAP32=H=new Int32Array(buffer);f.HEAPU8=E=new Uint8Array(buffer);f.HEAPU16=va=new Uint16Array(buffer);f.HEAPU32=wa=new Uint32Array(buffer);f.HEAPF32=I=new Float32Array(buffer);f.HEAPF64=J=new Float64Array(buffer)}var ya=f.TOTAL_MEMORY||33554432;f.wasmMemory?C=f.wasmMemory:C=new WebAssembly.Memory({initial:ya/65536});C&&(buffer=C.buffer);ya=buffer.byteLength;xa();H[1393184]=10815632;
function Aa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Kb;"number"===typeof c?void 0===b.Db?f.dynCall_v(c):f.dynCall_vi(c,b.Db):c(void 0===b.Db?null:b.Db)}}}var Ba=[],Ca=[],Da=[],Ea=[],Fa=[];function Ga(){var a=f.preRun.shift();Ba.unshift(a)}var K=0,Ha=null,L=null;f.preloadedImages={};f.preloadedAudios={};
function Ia(){var a=M;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var M="zx.wasm";if(!Ia()){var Ja=M;M=f.locateFile?f.locateFile(Ja,x):x+Ja}function Ka(){try{if(B)return new Uint8Array(B);if(y)return y(M);throw"both async and sync fetching of the wasm failed";}catch(a){z(a)}}
function La(){return B||!t&&!v||"function"!==typeof fetch?new Promise(function(a){a(Ka())}):fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ka()})}
function Ma(a){function b(a){f.asm=a.exports;K--;f.monitorRunDependencies&&f.monitorRunDependencies(K);0==K&&(null!==Ha&&(clearInterval(Ha),Ha=null),L&&(a=L,L=null,a()))}function c(a){b(a.instance)}function d(a){return La().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){A("failed to asynchronously prepare wasm: "+a);z(a)})}var e={env:a};K++;f.monitorRunDependencies&&f.monitorRunDependencies(K);if(f.instantiateWasm)try{return f.instantiateWasm(e,b)}catch(h){return A("Module.instantiateWasm callback failed with error: "+
h),!1}(function(){if(B||"function"!==typeof WebAssembly.instantiateStreaming||Ia()||"function"!==typeof fetch)return d(c);fetch(M,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,e).then(c,function(a){A("wasm streaming compile failed: "+a);A("falling back to ArrayBuffer instantiation");d(c)})})})();return{}}f.asm=function(a,b){b.memory=C;b.table=new WebAssembly.Table({initial:18,maximum:18,element:"anyfunc"});return Ma(b)};Ca.push({Kb:function(){Na()}});
var Oa=0,Pa=0,N=0,Qa=0,Ra=0,Sa=null,Ta=null,Ua=!1;function Va(){for(var a=O.length-1;0<=a;--a)Wa(a);O=[];Xa=[]}var Xa=[];function Ya(){if(Za&&$a.vb)for(var a=0;a<Xa.length;++a){var b=Xa[a];Xa.splice(a,1);--a;b.Vb.apply(this,b.Pb)}}var Za=0,$a=null,O=[];function ab(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function Wa(a){var b=O[a];b.target.removeEventListener(b.ub,b.Ib,b.wb);O.splice(a,1)}
function P(a){function b(b){++Za;$a=a;Ya();a.yb(b);Ya();--Za}if(a.xb)a.Ib=b,a.target.addEventListener(a.ub,b,a.wb),O.push(a),Ua||(Ea.push(Va),Ua=!0);else for(var c=0;c<O.length;++c)O[c].target==a.target&&O[c].ub==a.ub&&Wa(c--)}var bb=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function Q(a){try{if(!a)return window;"number"===typeof a&&(a=bb[a]||G(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?f.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function cb(a){"number"===typeof a&&(a=G(a));return a&&"#canvas"!==a?"undefined"!==typeof db&&eb[a]?eb[a]:Q(a):"undefined"!==typeof db&&eb.canvas?eb.canvas:f.canvas}
function fb(a,b,c,d,e,h){Oa||(Oa=R(164));a={target:Q(a),vb:ab()?!1:!0,ub:h,xb:d,yb:function(a){a=a||event;var c=Oa;D(a.key?a.key:"",E,c+0,32);D(a.code?a.code:"",E,c+32,32);H[c+64>>2]=a.location;H[c+68>>2]=a.ctrlKey;H[c+72>>2]=a.shiftKey;H[c+76>>2]=a.altKey;H[c+80>>2]=a.metaKey;H[c+84>>2]=a.repeat;D(a.locale?a.locale:"",E,c+88,32);D(a.char?a.char:"",E,c+120,32);H[c+152>>2]=a.charCode;H[c+156>>2]=a.keyCode;H[c+160>>2]=a.which;S(d,e,c,b)&&a.preventDefault()},wb:c};P(a)}
function gb(a,b,c){J[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();H[a+8>>2]=b.screenX;H[a+12>>2]=b.screenY;H[a+16>>2]=b.clientX;H[a+20>>2]=b.clientY;H[a+24>>2]=b.ctrlKey;H[a+28>>2]=b.shiftKey;H[a+32>>2]=b.altKey;H[a+36>>2]=b.metaKey;ua[a+40>>1]=b.button;ua[a+42>>1]=b.buttons;H[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-Sa;H[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-Ta;if(f.canvas){var d=f.canvas.getBoundingClientRect();
H[a+60>>2]=b.clientX-d.left;H[a+64>>2]=b.clientY-d.top}else H[a+60>>2]=0,H[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},H[a+52>>2]=b.clientX-d.left,H[a+56>>2]=b.clientY-d.top):(H[a+52>>2]=0,H[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(Sa=b.screenX,Ta=b.screenY)}
function T(a,b,c,d,e,h){Pa||(Pa=R(72));a=Q(a);c={target:a,vb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ub:h,xb:d,yb:function(c){c=c||event;gb(Pa,c,a);S(d,e,Pa,b)&&c.preventDefault()},wb:c};ab()&&"mousedown"==h&&(c.vb=!1);P(c)}
function hb(a,b,c,d){Qa||(Qa=R(36));a=Q(a);P({target:a,vb:!1,ub:"resize",xb:d,yb:function(c){c=c||event;if(c.target==a){var e=0<pageXOffset||0<pageYOffset?[pageXOffset,pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],l=Qa;H[l>>2]=c.detail;H[l+4>>2]=document.body.clientWidth;H[l+8>>2]=document.body.clientHeight;
H[l+12>>2]=innerWidth;H[l+16>>2]=innerHeight;H[l+20>>2]=outerWidth;H[l+24>>2]=outerHeight;H[l+28>>2]=e[0];H[l+32>>2]=e[1];S(d,10,l,b)&&c.preventDefault()}},wb:c})}
function kb(a,b,c,d,e,h){Ra||(Ra=R(1684));a=Q(a);P({target:a,vb:"touchstart"==h||"touchend"==h,ub:h,xb:d,yb:function(c){c=c||event;for(var h={},l=0;l<c.touches.length;++l){var p=c.touches[l];p.Fb=!1;h[p.identifier]=p}for(l=0;l<c.changedTouches.length;++l)p=c.changedTouches[l],h[p.identifier]=p,p.Fb=!0;for(l=0;l<c.targetTouches.length;++l)p=c.targetTouches[l],h[p.identifier].Nb=!0;var q=p=Ra;H[q+4>>2]=c.ctrlKey;H[q+8>>2]=c.shiftKey;H[q+12>>2]=c.altKey;H[q+16>>2]=c.metaKey;q+=20;var za=f.canvas?f.canvas.getBoundingClientRect():
void 0,ib=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},jb=0;for(l in h){var w=h[l];H[q>>2]=w.identifier;H[q+4>>2]=w.screenX;H[q+8>>2]=w.screenY;H[q+12>>2]=w.clientX;H[q+16>>2]=w.clientY;H[q+20>>2]=w.pageX;H[q+24>>2]=w.pageY;H[q+28>>2]=w.Fb;H[q+32>>2]=w.Nb;za?(H[q+44>>2]=w.clientX-za.left,H[q+48>>2]=w.clientY-za.top):(H[q+44>>2]=0,H[q+48>>2]=0);H[q+36>>2]=w.clientX-ib.left;H[q+40>>2]=w.clientY-ib.top;q+=52;if(32<=++jb)break}H[p>>2]=jb;S(d,e,p,b)&&c.preventDefault()},wb:c})}
function lb(a,b,c,d,e,h){a||(a=f.canvas);a={target:Q(a),vb:!1,ub:h,xb:d,yb:function(a){a=a||event;S(d,e,0,b)&&a.preventDefault()},wb:c};P(a)}
function mb(a,b,c,d,e){function h(c){c=c||event;gb(N,c,a);J[N+72>>3]=c.wheelDeltaX||0;J[N+80>>3]=-(c.wheelDeltaY||c.wheelDelta);J[N+88>>3]=0;H[N+96>>2]=0;S(d,9,N,b)&&c.preventDefault()}function l(c){c=c||event;var e=N;gb(e,c,a);J[e+72>>3]=c.deltaX;J[e+80>>3]=c.deltaY;J[e+88>>3]=c.deltaZ;H[e+96>>2]=c.deltaMode;S(d,9,e,b)&&c.preventDefault()}N||(N=R(104));P({target:a,vb:!0,ub:e,xb:d,yb:"wheel"==e?l:h,wb:c})}var nb=1,ob=0,pb=[],U=[],qb=[],rb=[],sb=[],V=[],W=[],tb={},ub=null,eb={},vb={},wb={};
function X(a){ob||(ob=a)}function xb(a){for(var b=nb++,c=a.length;c<b;c++)a[c]=null;return b}var yb=null,Y=[0];function zb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(a,d){b.vertexAttribDivisorANGLE(a,d)},a.drawArraysInstanced=function(a,d,e,h){b.drawArraysInstancedANGLE(a,d,e,h)},a.drawElementsInstanced=function(a,d,e,h,l){b.drawElementsInstancedANGLE(a,d,e,h,l)})}
function Ab(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(a){b.deleteVertexArrayOES(a)},a.bindVertexArray=function(a){b.bindVertexArrayOES(a)},a.isVertexArray=function(a){return b.isVertexArrayOES(a)})}function Bb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(a,d){b.drawBuffersWEBGL(a,d)})}
function Cb(a){a||(a=ub);if(!a.Lb){a.Lb=!0;var b=a.Cb;2>a.version&&(zb(b),Ab(b),Bb(b));b.Rb=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=c.indexOf(a)&&b.getExtension(a)})}}var db={},Db,Eb,Fb=["default","low-power","high-performance"];function Gb(a,b,c,d){for(var e=0;e<a;e++){var h=Z[c](),l=h&&xb(d);h?(h.name=l,d[l]=h):X(1282);H[b+4*e>>2]=l}}
function Hb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":X(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:X(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)H[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){X(1280);A("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:X(1280);A("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}H[b>>2]=c}else X(1281)}function Ib(a){var b=ra(a)+1,c=R(b);D(a,E,c,b);return c}
var Jb={6402:1,6406:1,6407:3,6408:4,6409:1,6410:2,35904:3,35906:4},Kb={5121:1,5123:2,5125:4,5126:4,32819:2,32820:2,33635:2,34042:4,36193:2};function Lb(a,b,c,d,e){if(b=Jb[b]*Kb[a])switch(c=e+d*(c*b+4-1&-4),a){case 5121:return E.subarray(e,c);case 5126:return I.subarray(e>>2,c>>2);case 5125:case 34042:return wa.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return va.subarray(e>>1,c>>1);default:X(1280)}else X(1280)}
function Mb(){f.___errno_location&&(H[f.___errno_location()>>2]=12)}function Nb(a){a=ta(a);var b=buffer.byteLength;try{return-1!==C.grow((a-b)/65536)?(buffer=C.buffer,!0):!1}catch(c){return!1}}var Z;yb=new Float32Array(256);for(var Ob=0;256>Ob;Ob++)Y[Ob]=yb.subarray(0,Ob+1);
var Tb=f.asm({},{bb:function(){console.log("fs.h: registering Module['ccall']");f.ccall=ma},cb:function(a){var b=G(a),c=new XMLHttpRequest;c.open("GET",b);c.responseType="arraybuffer";c.onload=function(){var a=new Uint8Array(c.response);ma("emsc_load_data","int",["string","array","number"],[b,a,a.length])};c.send()},R:function(){return devicePixelRatio||1},X:function(a,b,c){a=a?Q(a):f.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),J[b>>3]=a.right-a.left,J[c>>3]=a.bottom-
a.top):(J[b>>3]=a.clientWidth,J[c>>3]=a.clientHeight);return 0},Va:function(a,b,c){E.set(E.subarray(b,b+c),a)},Ha:function(a,b){function c(d){Pb(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},N:function(a,b,c){a=cb(a);if(!a)return-4;a.width=b;a.height=c;return 0},Qa:function(a,b,c,d){fb(a,b,c,d,2,"keydown");return 0},Oa:function(a,b,c,d){fb(a,b,c,d,1,"keypress");return 0},Pa:function(a,b,c,d){fb(a,b,c,d,3,"keyup");return 0},ab:function(a,b,c,d){T(a,b,c,d,5,"mousedown");return 0},
Ta:function(a,b,c,d){T(a,b,c,d,33,"mouseenter");return 0},Sa:function(a,b,c,d){T(a,b,c,d,34,"mouseleave");return 0},Ua:function(a,b,c,d){T(a,b,c,d,8,"mousemove");return 0},Wa:function(a,b,c,d){T(a,b,c,d,6,"mouseup");return 0},Da:function(a,b,c,d){hb(a,b,c,d);return 0},Ka:function(a,b,c,d){kb(a,b,c,d,25,"touchcancel");return 0},La:function(a,b,c,d){kb(a,b,c,d,23,"touchend");return 0},Ma:function(a,b,c,d){kb(a,b,c,d,24,"touchmove");return 0},Na:function(a,b,c,d){kb(a,b,c,d,22,"touchstart");return 0},
Ja:function(a,b,c,d){lb(a,b,c,d,31,"webglcontextlost");return 0},Ia:function(a,b,c,d){lb(a,b,c,d,32,"webglcontextrestored");return 0},Ra:function(a,b,c,d){a=Q(a);return"undefined"!==typeof a.onwheel?(mb(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(mb(a,b,c,d,"mousewheel"),0):-1},K:function(a,b){var c={};b>>=2;c.alpha=!!H[b];c.depth=!!H[b+1];c.stencil=!!H[b+2];c.antialias=!!H[b+3];c.premultipliedAlpha=!!H[b+4];c.preserveDrawingBuffer=!!H[b+5];c.powerPreference=Fb[H[b+6]];c.failIfMajorPerformanceCaveat=
!!H[b+7];c.Mb=H[b+8];c.Sb=H[b+9];c.Gb=H[b+10];c.Jb=H[b+11];c.Tb=H[b+12];c.Ub=H[b+13];a=cb(a);if(!a||c.Jb)c=0;else if(a=a.getContext("webgl",c)||a.getContext("experimental-webgl",c)){b=R(8);var d={handle:b,attributes:c,version:c.Mb,Cb:a};a.canvas&&(a.canvas.Ob=d);tb[b]=d;("undefined"===typeof c.Gb||c.Gb)&&Cb(d);c=b}else c=0;return c},fa:function(a,b){a=tb[a];b=G(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b?zb(Z):"OES_vertex_array_object"==b?Ab(Z):"WEBGL_draw_buffers"==b&&Bb(Z);
return!!a.Cb.getExtension(b)},ua:function(a){a>>=2;for(var b=0;14>b;++b)H[a+b]=0;H[a]=H[a+1]=H[a+3]=H[a+4]=H[a+8]=H[a+10]=1},oa:function(a){ub=tb[a];f.Qb=Z=ub&&ub.Cb;return!a||Z?0:-5},h:function(a){Z.activeTexture(a)},O:function(a,b){Z.attachShader(U[a],W[b])},e:function(a,b){Z.bindBuffer(a,pb[b])},g:function(a,b){Z.bindFramebuffer(a,qb[b])},Ba:function(a,b){Z.bindRenderbuffer(a,rb[b])},b:function(a,b){Z.bindTexture(a,sb[b])},F:function(a,b,c,d){Z.blendColor(a,b,c,d)},G:function(a,b){Z.blendEquationSeparate(a,
b)},H:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},T:function(a,b,c,d){Z.bufferData(a,c?E.subarray(c,c+b):b,d)},S:function(a,b,c,d){Z.bufferSubData(a,b,E.subarray(d,d+c))},m:function(a){return Z.checkFramebufferStatus(a)},pa:function(a){Z.clear(a)},sa:function(a,b,c,d){Z.clearColor(a,b,c,d)},ra:function(a){Z.clearDepth(a)},qa:function(a){Z.clearStencil(a)},z:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},Za:function(a){Z.compileShader(W[a])},Q:function(a,b,c,d,e,h,l,m){Z.compressedTexImage2D(a,
b,c,d,e,h,m?E.subarray(m,m+l):null)},ya:function(){var a=xb(U),b=Z.createProgram();b.name=a;U[a]=b;return a},$a:function(a){var b=xb(W);W[b]=Z.createShader(a);return b},E:function(a){Z.cullFace(a)},Ea:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],e=pb[d];e&&(Z.deleteBuffer(e),e.name=0,pb[d]=null,d==Db&&(Db=0),d==Eb&&(Eb=0))}},j:function(a,b){for(var c=0;c<a;++c){var d=H[b+4*c>>2],e=qb[d];e&&(Z.deleteFramebuffer(e),e.name=0,qb[d]=null)}},V:function(a){if(a){var b=U[a];b?(Z.deleteProgram(b),
b.name=0,U[a]=null,vb[a]=null):X(1281)}},q:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],e=rb[d];e&&(Z.deleteRenderbuffer(e),e.name=0,rb[d]=null)}},A:function(a){if(a){var b=W[a];b?(Z.deleteShader(b),W[a]=null):X(1281)}},W:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],e=sb[d];e&&(Z.deleteTexture(e),e.name=0,sb[d]=null)}},x:function(a){Z.depthFunc(a)},y:function(a){Z.depthMask(!!a)},d:function(a){Z.disable(a)},a:function(a){Z.disableVertexAttribArray(a)},da:function(a,b,c){Z.drawArrays(a,
b,c)},ea:function(a,b,c,d){Z.drawElements(a,b,c,d)},f:function(a){Z.enable(a)},la:function(a){Z.enableVertexAttribArray(a)},k:function(a,b,c,d){Z.framebufferRenderbuffer(a,b,c,rb[d])},c:function(a,b,c,d,e){Z.framebufferTexture2D(a,b,c,sb[d],e)},D:function(a){Z.frontFace(a)},U:function(a,b){Gb(a,b,"createBuffer",pb)},n:function(a,b){Gb(a,b,"createFramebuffer",qb)},Ca:function(a,b){Gb(a,b,"createRenderbuffer",rb)},za:function(a,b){Gb(a,b,"createTexture",sb)},va:function(a,b){return Z.getAttribLocation(U[a],
G(b))},r:function(a,b){Hb(a,b)},wa:function(a,b,c,d){a=Z.getProgramInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(H[c>>2]=b)},M:function(a,b,c){if(c)if(a>=nb)X(1281);else{var d=vb[a];if(d)if(35716==b)a=Z.getProgramInfoLog(U[a]),null===a&&(a="(unknown error)"),H[c>>2]=a.length+1;else if(35719==b)H[c>>2]=d.Eb;else if(35722==b){if(-1==d.Ab){a=U[a];var e=Z.getProgramParameter(a,35721);for(b=d.Ab=0;b<e;++b)d.Ab=Math.max(d.Ab,Z.getActiveAttrib(a,b).name.length+1)}H[c>>2]=d.Ab}else if(35381==
b){if(-1==d.Bb)for(a=U[a],e=Z.getProgramParameter(a,35382),b=d.Bb=0;b<e;++b)d.Bb=Math.max(d.Bb,Z.getActiveUniformBlockName(a,b).length+1);H[c>>2]=d.Bb}else H[c>>2]=Z.getProgramParameter(U[a],b);else X(1282)}else X(1281)},Ya:function(a,b,c,d){a=Z.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(H[c>>2]=b)},Y:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),H[c>>2]=a.length+1):35720==b?(a=Z.getShaderSource(W[a]),H[c>>2]=null===a||
0==a.length?0:a.length+1):H[c>>2]=Z.getShaderParameter(W[a],b):X(1281)},Fa:function(a){if(wb[a])return wb[a];switch(a){case 7939:var b=Z.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=Ib(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||X(1280);b=Ib(b);break;case 7938:b=Ib("OpenGL ES 2.0 ("+Z.getParameter(Z.VERSION)+")");break;case 35724:b=Z.getParameter(Z.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Ib(b);break;default:return X(1280),0}return wb[a]=b},l:function(a,b){b=G(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=vb[a]&&vb[a].Hb[b])&&0<=c&&c<a[0]?a[1]+c:-1},xa:function(a){Z.linkProgram(U[a]);var b=U[a];a=vb[a]={Hb:{},Eb:0,Ab:-1,Bb:-1};for(var c=a.Hb,d=Z.getProgramParameter(b,35718),e=0;e<d;++e){var h=Z.getActiveUniform(b,e),l=h.name;a.Eb=
Math.max(a.Eb,l.length+1);"]"==l.slice(-1)&&(l=l.slice(0,l.lastIndexOf("[")));var m=Z.getUniformLocation(b,l);if(m){var u=xb(V);c[l]=[h.size,u];V[u]=m;for(var p=1;p<h.size;++p)m=Z.getUniformLocation(b,l+"["+p+"]"),u=xb(V),V[u]=m}}},C:function(a,b){Z.polygonOffset(a,b)},Aa:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},ta:function(a,b,c,d){Z.scissor(a,b,c,d)},_a:function(a,b,c,d){for(var e="",h=0;h<b;++h){var l=d?H[d+4*h>>2]:-1;e+=G(H[c+4*h>>2],0>l?void 0:l)}Z.shaderSource(W[a],e)},ca:function(a,
b,c){Z.stencilFunc(a,b,c)},J:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},w:function(a){Z.stencilMask(a)},ba:function(a,b,c){Z.stencilOp(a,b,c)},I:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},P:function(a,b,c,d,e,h,l,m,u){Z.texImage2D(a,b,c,d,e,h,l,m,u?Lb(m,l,d,e,u):null)},i:function(a,b,c){Z.texParameteri(a,b,c)},p:function(a,b,c,d,e,h,l,m,u){var p=null;u&&(p=Lb(m,l,e,h,u));Z.texSubImage2D(a,b,c,d,e,h,l,m,p)},ka:function(a,b,c){if(256>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=I[c+4*e>>2];else d=
I.subarray(c>>2,c+4*b>>2);Z.uniform1fv(V[a],d)},B:function(a,b){Z.uniform1i(V[a],b)},ja:function(a,b,c){if(256>=2*b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=I[c+4*e>>2],d[e+1]=I[c+(4*e+4)>>2];else d=I.subarray(c>>2,c+8*b>>2);Z.uniform2fv(V[a],d)},ia:function(a,b,c){if(256>=3*b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=I[c+4*e>>2],d[e+1]=I[c+(4*e+4)>>2],d[e+2]=I[c+(4*e+8)>>2];else d=I.subarray(c>>2,c+12*b>>2);Z.uniform3fv(V[a],d)},ha:function(a,b,c){if(256>=4*b)for(var d=Y[4*b-1],e=0;e<4*b;e+=4)d[e]=I[c+
4*e>>2],d[e+1]=I[c+(4*e+4)>>2],d[e+2]=I[c+(4*e+8)>>2],d[e+3]=I[c+(4*e+12)>>2];else d=I.subarray(c>>2,c+16*b>>2);Z.uniform4fv(V[a],d)},ga:function(a,b,c,d){if(256>=16*b)for(var e=Y[16*b-1],h=0;h<16*b;h+=16)e[h]=I[d+4*h>>2],e[h+1]=I[d+(4*h+4)>>2],e[h+2]=I[d+(4*h+8)>>2],e[h+3]=I[d+(4*h+12)>>2],e[h+4]=I[d+(4*h+16)>>2],e[h+5]=I[d+(4*h+20)>>2],e[h+6]=I[d+(4*h+24)>>2],e[h+7]=I[d+(4*h+28)>>2],e[h+8]=I[d+(4*h+32)>>2],e[h+9]=I[d+(4*h+36)>>2],e[h+10]=I[d+(4*h+40)>>2],e[h+11]=I[d+(4*h+44)>>2],e[h+12]=I[d+(4*
h+48)>>2],e[h+13]=I[d+(4*h+52)>>2],e[h+14]=I[d+(4*h+56)>>2],e[h+15]=I[d+(4*h+60)>>2];else e=I.subarray(d>>2,d+64*b>>2);Z.uniformMatrix4fv(V[a],!!c,e)},na:function(a){Z.useProgram(U[a])},Xa:function(a,b){Z.vertexAttribDivisor(a,b)},ma:function(a,b,c,d,e,h){Z.vertexAttribPointer(a,b,c,!!d,e,h)},L:function(a,b,c,d){Z.viewport(a,b,c,d)},u:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Qb()});
document.body.append(a)},t:function(){document.getElementById("_sokol_app_input_element").focus()},Ga:function(){window.addEventListener("beforeunload",function(a){0!=Rb()&&(a.preventDefault(),a.returnValue=" ")})},s:function(){document.getElementById("_sokol_app_input_element").blur()},Z:function(){for(var a=(new URLSearchParams(window.location.search)).entries(),b=a.next();!b.done;b=a.next())ma("_sargs_add_kvp","void",["string","string"],[b.value[0],b.value[1]])},_:function(){return f.zb?f.zb.bufferSize:
0},aa:function(a,b,c){f.tb=null;f.zb=null;"undefined"!==typeof AudioContext?(f.tb=new AudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created AudioContext")):"undefined"!==typeof webkitAudioContext?(f.tb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created webkitAudioContext")):(f.tb=null,console.log("sokol_audio.h: no WebAudio support"));return f.tb?(console.log("sokol_audio.h: sample rate ",f.tb.sampleRate),f.zb=
f.tb.createScriptProcessor(c,0,b),f.zb.onaudioprocess=function(a){var b=a.outputBuffer.length,c=Sb(b);if(c)for(var d=a.outputBuffer.numberOfChannels,m=0;m<d;m++)for(var u=a.outputBuffer.getChannelData(m),p=0;p<b;p++)u[p]=I[(c>>2)+(d*p+m)]},f.zb.connect(f.tb.destination),a=function(){f.tb&&"suspended"===f.tb.state&&f.tb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},$:function(){return f.tb?
f.tb.sampleRate:0},o:function(a){a|=0;var b=F.length|0;var c=H[1393184]|0;var d=c+a|0;if(0<(a|0)&(d|0)<(c|0)|0>(d|0))return z("OOM"),0,Mb(),-1;if(a=(d|0)>(b|0)){a=d|0;if(2147418112<a)a=!1;else{for(b=Math.max(F.length,16777216);b<a;)536870912>=b?b=ta(2*b):b=Math.min(ta((3*b+2147483648)/4),2147418112);Nb(b)?(xa(),a=!0):a=!1}a=!(a|0)}if(a)return Mb(),-1;H[1393184]=d|0;return c|0},v:function(){return performance.now()}},buffer);f.asm=Tb;
var Na=f.___wasm_call_ctors=function(){return f.asm.db.apply(null,arguments)};f._emsc_load_data=function(){return f.asm.eb.apply(null,arguments)};var Qb=f.__sapp_emsc_notify_keyboard_hidden=function(){return f.asm.fb.apply(null,arguments)},Rb=f.__sapp_html5_get_ask_leave_site=function(){return f.asm.gb.apply(null,arguments)};f._main=function(){return f.asm.hb.apply(null,arguments)};var R=f._malloc=function(){return f.asm.ib.apply(null,arguments)};f._free=function(){return f.asm.jb.apply(null,arguments)};
var Sb=f.__saudio_emsc_pull=function(){return f.asm.kb.apply(null,arguments)};f.__sargs_add_kvp=function(){return f.asm.lb.apply(null,arguments)};var oa=f.stackSave=function(){return f.asm.mb.apply(null,arguments)},na=f.stackAlloc=function(){return f.asm.nb.apply(null,arguments)},pa=f.stackRestore=function(){return f.asm.ob.apply(null,arguments)};f.dynCall_vi=function(){return f.asm.pb.apply(null,arguments)};f.dynCall_v=function(){return f.asm.qb.apply(null,arguments)};
var S=f.dynCall_iiii=function(){return f.asm.rb.apply(null,arguments)},Pb=f.dynCall_idi=function(){return f.asm.sb.apply(null,arguments)};f.asm=Tb;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}L=function Ub(){f.calledRun||Vb();f.calledRun||(L=Ub)};
function Vb(a){function b(){if(!f.calledRun&&(f.calledRun=!0,!ka)){Aa(Ca);Aa(Da);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Wb){var b=a;b=b||[];var d=b.length+1,e=na(4*(d+1));H[e>>2]=sa(aa);for(var h=1;h<d;h++)H[(e>>2)+h]=sa(b[h-1]);H[(e>>2)+d]=0;try{var l=f._main(d,e);if(!f.noExitRuntime||0!==l){if(!f.noExitRuntime&&(ka=!0,f.onExit))f.onExit(l);r(l,new ia(l))}}catch(m){m instanceof ia||("SimulateInfiniteLoop"==m?f.noExitRuntime=!0:((b=m)&&"object"===typeof m&&m.stack&&(b=[m,m.stack]),
A("exception thrown: "+b),r(1,m)))}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=f.postRun.shift(),Fa.unshift(b);Aa(Fa)}}a=a||n;if(!(0<K)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ga();Aa(Ba);0<K||f.calledRun||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Vb;
function z(a){if(f.onAbort)f.onAbort(a);ja(a);A(a);ka=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}f.abort=z;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Wb=!0;f.noInitialRun&&(Wb=!1);f.noExitRuntime=!0;Vb();
