var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa={},g;for(g in e)e.hasOwnProperty(g)&&(aa[g]=e[g]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var p=!1,q=!1,ba=!1,ca=!1;p="object"===typeof window;q="function"===typeof importScripts;ba="object"===typeof process&&"function"===typeof require&&!p&&!q;ca=!p&&!ba&&!q;
if(ba){var da,ea;e.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof r))throw a;});process.on("unhandledRejection",
function(){process.exit(1)});e.quit=function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});
else if(p||q)e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},q&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=
a};var fa=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),t=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||fa);for(g in aa)aa.hasOwnProperty(g)&&(e[g]=aa[g]);aa=void 0;function ha(a){var b=v;v=v+a+15&-16;return b}function ia(a){var b;b||(b=16);return Math.ceil(a/b)*b}function ja(a){ka||(ka={});ka[a]||(ka[a]=1,t(a))}
var ka,la={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},w=0;function assert(a,b){a||y("Assertion failed: "+b)}function ma(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=("function"===typeof z?z:ha)(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)B[a>>2]=0;for(b=d+c;a<b;)na[a++>>0]=0;return d}a.subarray||a.slice?C.set(a,d):C.set(new Uint8Array(a),d);return d}
function D(a,b){if(0===b||!a)return"";for(var c=0,d,f=0;;){d=C[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,C.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}a:{b=C;for(c=a;b[c];)++c;if(16<c-a&&b.subarray&&oa)a=oa.decode(b.subarray(a,c));else for(c="";;){d=b[a++];if(!d){a=c;break a}if(d&128)if(f=b[a++]&63,192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var h=b[a++]&63;if(224==(d&240))d=(d&15)<<12|
f<<6|h;else{var k=b[a++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|h<<6|k;else{var n=b[a++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|h<<12|k<<6|n;else{var m=b[a++]&63;d=(d&1)<<30|f<<24|h<<18|k<<12|n<<6|m}}}65536>d?c+=String.fromCharCode(d):(d-=65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}else c+=String.fromCharCode(d)}}return a}var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function E(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);55296<=k&&57343>=k&&(k=65536+((k&1023)<<10)|a.charCodeAt(++h)&1023);if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(2097151>=k){if(c+3>=d)break;b[c++]=240|k>>18}else{if(67108863>=k){if(c+4>=d)break;b[c++]=248|k>>24}else{if(c+5>=d)break;b[c++]=252|k>>30;b[c++]=128|k>>24&63}b[c++]=128|k>>18&63}b[c++]=128|
k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}function pa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function qa(a){var b=pa(a)+1,c=ra(b);E(a,na,c,b);return c}var buffer,na,C,sa,ta,B,ua,va,F;
function wa(){e.HEAP8=na=new Int8Array(buffer);e.HEAP16=sa=new Int16Array(buffer);e.HEAP32=B=new Int32Array(buffer);e.HEAPU8=C=new Uint8Array(buffer);e.HEAPU16=ta=new Uint16Array(buffer);e.HEAPU32=ua=new Uint32Array(buffer);e.HEAPF32=va=new Float32Array(buffer);e.HEAPF64=F=new Float64Array(buffer)}var xa,v,ya,za,Aa,Ba,Ca;xa=v=ya=za=Aa=Ba=Ca=0;
function Da(){y("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+G+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Ea=e.TOTAL_STACK||5242880,G=e.TOTAL_MEMORY||33554432;G<Ea&&t("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+G+"! (TOTAL_STACK="+Ea+")");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:G/65536,maximum:G/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(G),e.buffer=buffer);wa();function H(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.B;"number"===typeof c?void 0===b.j?e.dynCall_v(c):e.dynCall_vi(c,b.j):c(void 0===b.j?null:b.j)}}}var Fa=[],Ga=[],Ha=[],Ia=[],Ja=[],Ka=!1;
function La(){var a=e.preRun.shift();Fa.unshift(a)}var I=0,Ma=null,Na=null;e.preloadedImages={};e.preloadedAudios={};function Oa(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(x){y(x)}}function b(){return e.wasmBinary||!p&&!q||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){n=a.exports;if(n.memory){a=n.memory;var b=e.buffer;a.byteLength<b.byteLength&&t("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;wa()}e.asm=n;e.usingWasm=!0;I--;e.monitorRunDependencies&&e.monitorRunDependencies(I);0==I&&(null!==Ma&&(clearInterval(Ma),Ma=null),Na&&(a=Na,Na=null,a()))}function d(a){c(a.instance)}
function h(a){b().then(function(a){return WebAssembly.instantiate(a,k)}).then(a).catch(function(a){t("failed to asynchronously prepare wasm: "+a);y(a)})}if("object"!==typeof WebAssembly)return t("no native wasm support detected"),!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return t("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;k.global={NaN:NaN,Infinity:Infinity};k["global.Math"]=Math;k.env=a;I++;e.monitorRunDependencies&&e.monitorRunDependencies(I);if(e.instantiateWasm)try{return e.instantiateWasm(k,
c)}catch(cc){return t("Module.instantiateWasm callback failed with error: "+cc),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Oa(f)||"function"!==typeof fetch?h(d):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),k).then(d).catch(function(a){t("wasm streaming compile failed: "+a);t("falling back to ArrayBuffer instantiation");h(d)});return{}}var d="zx128k.wast",f="zx128k.wasm",h="zx128k.temp.asm.js";"function"===typeof e.locateFile&&(Oa(d)||(d=e.locateFile(d)),
Oa(f)||(f=e.locateFile(f)),Oa(h)||(h=e.locateFile(h)));var k={global:null,env:null,asm2wasm:la,parent:e},n=null;e.asmPreload=e.asm;var m=e.reallocBuffer;e.reallocBuffer=function(a){if("asmjs"===l)var b=m(a);else a:{var c=e.usingWasm?65536:16777216;0<a%c&&(a+=c-a%c);c=e.buffer.byteLength;if(e.usingWasm)try{b=-1!==e.wasmMemory.grow((a-c)/65536)?e.buffer=e.wasmMemory.buffer:null;break a}catch(u){b=null;break a}b=void 0}return b};var l="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&
(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.memoryBase||(b.memoryBase=e.STATIC_BASE);b.tableBase||(b.tableBase=0);b=c(b);assert(b,"no binaryen method succeeded.");return b}})();xa=1024;v=xa+4371584;Ga.push();e.STATIC_BASE=xa;e.STATIC_BUMP=4371584;v+=16;function J(){y()}
function Pa(a){e.___errno_location&&(B[e.___errno_location()>>2]=a);return a}
function Qa(a,b){Ra=a;Sa=b;if(!Ta)return 1;if(0==a)K=function(){var a=Math.max(0,Ua+b-J())|0;setTimeout(Va,a)},Wa="timeout";else if(1==a)K=function(){Xa(Va)},Wa="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);q?(void 0===e.setImmediates&&(e.setImmediates=[]),e.setImmediates.push(a),postMessage({target:"setimmediate"})):
postMessage("setimmediate","*")}}K=function(){setImmediate(Va)};Wa="immediate"}return 0}
function Ya(a,b,c,d,f){e.noExitRuntime=!0;assert(!Ta,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Ta=a;Za=d;var h="undefined"!==typeof d?function(){e.dynCall_vi(a,d)}:function(){e.dynCall_v(a)};var k=L;Va=function(){if(!w)if(0<$a.length){var a=Date.now(),b=$a.shift();b.B(b.j);if(ab){var c=ab,d=0==c%1?c-1:Math.floor(c);ab=b.L?d:(8*c+(d+.5))/9}console.log('main loop blocker "'+
b.name+'" took '+(Date.now()-a)+" ms");e.setStatus&&(a=e.statusMessage||"Please wait...",b=ab,c=bb.N,b?b<c?e.setStatus(a+" ("+(c-b)+"/"+c+")"):e.setStatus(a):e.setStatus(""));k<L||setTimeout(Va,0)}else if(!(k<L))if(cb=cb+1|0,1==Ra&&1<Sa&&0!=cb%Sa)K();else{0==Ra&&(Ua=J());"timeout"===Wa&&e.l&&(t("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
Wa="");a:if(!(w||e.preMainLoop&&!1===e.preMainLoop())){try{h()}catch(A){if(A instanceof r)break a;A&&"object"===typeof A&&A.stack&&t("exception thrown: "+[A,A.stack]);throw A;}e.postMainLoop&&e.postMainLoop()}k<L||("object"===typeof SDL&&SDL.audio&&SDL.audio.G&&SDL.audio.G(),K())}};f||(b&&0<b?Qa(0,1E3/b):Qa(1,1),K());if(c)throw"SimulateInfiniteLoop";}var K=null,Wa="",L=0,Ta=null,Za=0,Ra=0,Sa=0,cb=0,$a=[],bb={},Ua,Va,ab,db=!1,eb=!1,fb=[];
function gb(){function a(){eb=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}e.preloadPlugins||(e.preloadPlugins=[]);if(!hb){hb=!0;try{ib=!0}catch(c){ib=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}jb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:ib?null:console.log("warning: no BlobBuilder");
kb="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;e.o||"undefined"!==typeof kb||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),e.o=!0);e.preloadPlugins.push({canHandle:function(a){return!e.o&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,f,h){var c=null;if(ib)try{c=new Blob([a],{type:lb(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:lb(b)}))}catch(l){ja("Blob constructor present but fails: "+
l+"; falling back to blob builder")}c||(c=new jb,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=kb.createObjectURL(c),m=new Image;m.onload=function(){assert(m.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=m.width;c.height=m.height;c.getContext("2d").drawImage(m,0,0);e.preloadedImages[b]=c;kb.revokeObjectURL(d);f&&f(a)};m.onerror=function(){console.log("Image "+d+" could not be decoded");h&&h()};m.src=d}});e.preloadPlugins.push({canHandle:function(a){return!e.R&&
a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,f,h){function c(c){m||(m=!0,e.preloadedAudios[b]=c,f&&f(a))}function d(){m||(m=!0,e.preloadedAudios[b]=new Audio,h&&h())}var m=!1;if(ib){try{var l=new Blob([a],{type:lb(b)})}catch(A){return d()}l=kb.createObjectURL(l);var x=new Audio;x.addEventListener("canplaythrough",function(){c(x)},!1);x.onerror=function(){if(!m){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",f=0,k=0,
h=0;h<a.length;h++)for(f=f<<8|a[h],k+=8;6<=k;){var n=f>>k-6&63;k-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[n]}2==k?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&3)<<4],d+="=="):4==k&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&15)<<2],d+="=");x.src="data:audio/x-"+b.substr(-3)+";base64,"+d;c(x)}};x.src=l;mb(function(){c(x)})}else return d()}});var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&
b.addEventListener("click",function(a){!eb&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),a.preventDefault())},!1))}}
function nb(a,b,c,d){if(b&&e.l&&a==e.canvas)return e.l;if(b){var f={antialias:!1,alpha:!1};if(d)for(var h in d)f[h]=d[h];if(f=ob(a,f))var k=pb[f].GLctx}else k=a.getContext("2d");if(!k)return null;c&&(b||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),e.l=k,b&&qb(f),e.T=b,fb.forEach(function(a){a()}),gb());return k}var rb=!1,sb=void 0,M=void 0;
function ub(a,b,c){function d(){db=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){},f.exitFullscreen=f.exitFullscreen.bind(document),sb&&f.requestPointerLock(),db=!0,M?("undefined"!=typeof SDL&&
(B[SDL.screen>>2]=ua[SDL.screen>>2]|8388608),vb(e.canvas),wb()):vb(f)):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),M?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=ua[SDL.screen>>2]&-8388609),vb(e.canvas),wb()):vb(f));if(e.onFullScreen)e.onFullScreen(db);if(e.onFullscreen)e.onFullscreen(db)}sb=a;M=b;xb=c;"undefined"===typeof sb&&(sb=!0);"undefined"===typeof M&&(M=!1);"undefined"===typeof xb&&(xb=null);var f=e.canvas;rb||(rb=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",
d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var h=document.createElement("div");f.parentNode.insertBefore(h,f);h.appendChild(f);h.requestFullscreen=h.requestFullscreen||h.mozRequestFullScreen||h.msRequestFullscreen||(h.webkitRequestFullscreen?function(){h.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(h.webkitRequestFullScreen?function(){h.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?h.requestFullscreen({U:c}):
h.requestFullscreen()}function yb(a,b,c){t("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");yb=function(a,b,c){return ub(a,b,c)};return ub(a,b,c)}var zb=0;function Ab(a){var b=Date.now();if(0===zb)zb=b+1E3/60;else for(;b+2>=zb;)zb+=1E3/60;setTimeout(a,Math.max(zb-b,0))}
function Xa(a){"undefined"===typeof window?Ab(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||Ab),window.requestAnimationFrame(a))}function mb(a){e.noExitRuntime=!0;setTimeout(function(){w||a()},1E4)}
function lb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Bb=[];function wb(){var a=e.canvas;Bb.forEach(function(b){b(a.width,a.height)})}
function vb(a,b,c){b&&c?(a.H=b,a.C=c):(b=a.H,c=a.C);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var h=Math.min(screen.width/d,screen.height/f);d=Math.round(d*h);f=Math.round(f*h)}M?
(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var hb,ib,jb,kb,xb,N=0,Cb=0,O=0,P=0,Db=0,Eb=0,Fb=null,Gb=null,Hb=!1;
function Ib(){Hb||(Ia.push(function(){for(var a=Q.length-1;0<=a;--a)Jb(a)}),Hb=!0)}function R(a){return a?("number"==typeof a&&(a=D(a)),"#window"==a?window:"#document"==a?document:"#screen"==a?window.screen:"#canvas"==a?e.canvas:"string"==typeof a?document.getElementById(a):a):window}var Kb=[];function Lb(){if(Mb&&Nb.b)for(var a=0;a<Kb.length;++a){var b=Kb[a];Kb.splice(a,1);--a;b.S.apply(this,b.K)}}var Mb=0,Nb=null,Q=[];
function Ob(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function Jb(a){var b=Q[a];b.target.removeEventListener(b.a,b.A,b.c);Q.splice(a,1)}function Pb(a){function b(b){++Mb;Nb=a;Lb();a.g(b);Lb();--Mb}if(a.f)a.A=b,a.target.addEventListener(a.a,b,a.c),Q.push(a),Ib();else for(var c=0;c<Q.length;++c)Q[c].target==a.target&&Q[c].a==a.a&&Jb(c--)}
function Qb(a,b,c,d,f,h){N||(N=z(164));a={target:R(a),b:Ob()?!1:!0,a:h,f:d,g:function(a){a=a||window.event;E(a.key?a.key:"",C,N+0,32);E(a.code?a.code:"",C,N+32,32);B[N+64>>2]=a.location;B[N+68>>2]=a.ctrlKey;B[N+72>>2]=a.shiftKey;B[N+76>>2]=a.altKey;B[N+80>>2]=a.metaKey;B[N+84>>2]=a.repeat;E(a.locale?a.locale:"",C,N+88,32);E(a.char?a.char:"",C,N+120,32);B[N+152>>2]=a.charCode;B[N+156>>2]=a.keyCode;B[N+160>>2]=a.which;e.dynCall_iiii(d,f,N,b)&&a.preventDefault()},c:c};Pb(a)}
function Rb(a,b,c){F[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();B[a+8>>2]=b.screenX;B[a+12>>2]=b.screenY;B[a+16>>2]=b.clientX;B[a+20>>2]=b.clientY;B[a+24>>2]=b.ctrlKey;B[a+28>>2]=b.shiftKey;B[a+32>>2]=b.altKey;B[a+36>>2]=b.metaKey;sa[a+40>>1]=b.button;sa[a+42>>1]=b.buttons;B[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-Fb;B[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-Gb;if(e.canvas){var d=e.canvas.getBoundingClientRect();
B[a+60>>2]=b.clientX-d.left;B[a+64>>2]=b.clientY-d.top}else B[a+60>>2]=0,B[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},B[a+52>>2]=b.clientX-d.left,B[a+56>>2]=b.clientY-d.top):(B[a+52>>2]=0,B[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(Fb=b.screenX,Gb=b.screenY)}
function Sb(a,b,c,d,f,h){Cb||(Cb=z(72));a=R(a);c={target:a,b:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,a:h,f:d,g:function(c){c=c||window.event;Rb(Cb,c,a);e.dynCall_iiii(d,f,Cb,b)&&c.preventDefault()},c:c};Ob()&&"mousedown"==h&&(c.b=!1);Pb(c)}
function Tb(a,b,c,d,f){function h(c){c=c||window.event;Rb(O,c,a);F[O+72>>3]=c.wheelDeltaX||0;F[O+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);F[O+88>>3]=0;B[O+96>>2]=0;e.dynCall_iiii(d,9,O,b)&&c.preventDefault()}function k(c){c=c||window.event;Rb(O,c,a);F[O+72>>3]=c.deltaX;F[O+80>>3]=c.deltaY;F[O+88>>3]=c.deltaZ;B[O+96>>2]=c.deltaMode;e.dynCall_iiii(d,9,O,b)&&c.preventDefault()}O||(O=z(104));a=R(a);Pb({target:a,b:!0,a:f,f:d,g:"wheel"==f?k:h,c:c})}
function Ub(a,b,c,d){P||(P=z(36));a=R(a);Pb({target:a,b:!1,a:"resize",f:d,g:function(c){c=c||window.event;if(c.target==a){var f=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0];B[P>>2]=c.detail;B[P+4>>2]=document.body.clientWidth;
B[P+8>>2]=document.body.clientHeight;B[P+12>>2]=window.innerWidth;B[P+16>>2]=window.innerHeight;B[P+20>>2]=window.outerWidth;B[P+24>>2]=window.outerHeight;B[P+28>>2]=f[0];B[P+32>>2]=f[1];e.dynCall_iiii(d,10,P,b)&&c.preventDefault()}},c:c})}
function Vb(a,b,c,d,f,h){Db||(Db=z(1684));a=R(a);Pb({target:a,b:"touchstart"==h||"touchend"==h,a:h,f:d,g:function(c){c=c||window.event;for(var h={},k=0;k<c.touches.length;++k){var l=c.touches[k];h[l.identifier]=l}for(k=0;k<c.changedTouches.length;++k)l=c.changedTouches[k],h[l.identifier]=l,l.w=!0;for(k=0;k<c.targetTouches.length;++k)l=c.targetTouches[k],h[l.identifier].F=!0;l=Db;B[l+4>>2]=c.ctrlKey;B[l+8>>2]=c.shiftKey;B[l+12>>2]=c.altKey;B[l+16>>2]=c.metaKey;l+=20;var x=e.canvas?e.canvas.getBoundingClientRect():
void 0,A=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},tb=0;for(k in h){var u=h[k];B[l>>2]=u.identifier;B[l+4>>2]=u.screenX;B[l+8>>2]=u.screenY;B[l+12>>2]=u.clientX;B[l+16>>2]=u.clientY;B[l+20>>2]=u.pageX;B[l+24>>2]=u.pageY;B[l+28>>2]=u.w;B[l+32>>2]=u.F;x?(B[l+44>>2]=u.clientX-x.left,B[l+48>>2]=u.clientY-x.top):(B[l+44>>2]=0,B[l+48>>2]=0);B[l+36>>2]=u.clientX-A.left;B[l+40>>2]=u.clientY-A.top;l+=52;if(32<=++tb)break}B[Db>>2]=tb;e.dynCall_iiii(d,f,Db,b)&&c.preventDefault()},c:c})}
var Wb=1,Xb=0,Yb=[],S=[],Zb=[],T=[],U=[],$b=[],V=[],pb=[],ac=null,bc={},W={},dc={},ec=[];function X(a){Xb||(Xb=a)}function Y(a){for(var b=Wb++,c=a.length;c<b;c++)a[c]=null;return b}
function ob(a,b){function c(a){d=a.statusMessage||d}"undefined"===typeof b.majorVersion&&"undefined"===typeof b.minorVersion&&(b.majorVersion=1,b.minorVersion=0);var d="?";try{a.addEventListener("webglcontextcreationerror",c,!1);try{if(1==b.majorVersion&&0==b.minorVersion)var f=a.getContext("webgl",b)||a.getContext("experimental-webgl",b);else if(2==b.majorVersion&&0==b.minorVersion)f=a.getContext("webgl2",b);else throw"Unsupported WebGL context version "+majorVersion+"."+minorVersion+"!";}finally{a.removeEventListener("webglcontextcreationerror",
c,!1)}if(!f)throw":(";}catch(h){return fa("Could not create canvas: "+[d,h,JSON.stringify(b)]),0}return f?fc(f,b):0}function fc(a,b){var c=Y(pb),d={handle:c,attributes:b,version:b.majorVersion,GLctx:a};a.canvas&&(a.canvas.J=d);pb[c]=d;("undefined"===typeof b.enableExtensionsByDefault||b.enableExtensionsByDefault)&&hc(d);return c}function qb(a){a=pb[a];if(!a)return!1;GLctx=e.l=a.GLctx;ac=a;return!0}
function hc(a){a||(a=ac);if(!a.D){a.D=!0;var b=a.GLctx;a.P=b.getParameter(b.MAX_VERTEX_ATTRIBS);if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,f){c.drawArraysInstancedANGLE(a,b,d,f)},b.drawElementsInstanced=function(a,b,d,f,h){c.drawElementsInstancedANGLE(a,b,d,f,h)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},
b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var f=b.getExtension("WEBGL_draw_buffers");f&&(b.drawBuffers=function(a,b){f.drawBuffersWEBGL(a,b)})}b.M=b.getExtension("EXT_disjoint_timer_query");var h="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear WEBGL_compressed_texture_atc WEBKIT_WEBGL_compressed_texture_pvrtc WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_frag_depth EXT_sRGB WEBGL_draw_buffers WEBGL_shared_resources EXT_shader_texture_lod EXT_color_buffer_float".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=h.indexOf(a)&&b.getExtension(a)})}}var ic,jc;function _glDrawArrays(a,b,c){GLctx.drawArrays(a,b,c)}function _glDrawElements(a,b,c,d){GLctx.drawElements(a,b,c,d)}
function kc(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:c=GLctx.getParameter(34467).length}if(void 0===c)switch(c=GLctx.getParameter(a),typeof c){case "number":break;case "boolean":c=c?1:0;break;case "string":X(1280);return;case "object":if(null===c)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34068:c=0;break;default:X(1280);return}else{if(c instanceof Float32Array||c instanceof Uint32Array||c instanceof
Int32Array||c instanceof Array){for(a=0;a<c.length;++a)B[b+4*a>>2]=c[a];return}if(c instanceof WebGLBuffer||c instanceof WebGLProgram||c instanceof WebGLFramebuffer||c instanceof WebGLRenderbuffer||c instanceof WebGLTexture)c=c.name|0;else{X(1280);return}}break;default:X(1280);return}B[b>>2]=c}else X(1281)}
function lc(a,b,c,d,f){switch(b){case 6406:case 6409:case 6402:b=1;break;case 6410:b=2;break;case 6407:case 35904:b=3;break;case 6408:case 35906:b=4;break;default:return X(1280),null}switch(a){case 5121:b*=1;break;case 5123:case 36193:b*=2;break;case 5125:case 5126:b*=4;break;case 34042:b=4;break;case 33635:case 32819:case 32820:b=2;break;default:return X(1280),null}c*=b;b=4*Math.floor((c+4-1)/4);d=0>=d?0:(d-1)*b+c;switch(a){case 5121:return C.subarray(f,f+d);case 5126:return va.subarray(f>>2,f+d>>
2);case 5125:case 34042:return ua.subarray(f>>2,f+d>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return ta.subarray(f>>1,f+d>>1);default:return X(1280),null}}
ba?J=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?J=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?J=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?J=function(){return performance.now()}:J=Date.now;
e.requestFullScreen=function(a,b,c){t("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");e.requestFullScreen=e.requestFullscreen;yb(a,b,c)};e.requestFullscreen=function(a,b,c){ub(a,b,c)};e.requestAnimationFrame=function(a){Xa(a)};e.setCanvasSize=function(a,b,c){vb(e.canvas,a,b);c||wb()};e.pauseMainLoop=function(){K=null;L++};e.resumeMainLoop=function(){L++;var a=Ra,b=Sa,c=Ta;Ta=null;Ya(c,0,!1,Za,!0);Qa(a,b);K()};
e.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};e.createContext=function(a,b,c,d){return nb(a,b,c,d)};(function(){if("undefined"!==typeof window){window.addEventListener("gamepadconnected",function(){++Eb});window.addEventListener("gamepaddisconnected",function(){--Eb});var a=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null;a&&(Eb=a.length)}})();
for(var GLctx,Z=0;256>Z;Z++);for(Z=0;32>Z;Z++)ec.push(Array(Z));Ca=ha(4);ya=za=ia(v);Aa=ya+Ea;Ba=ia(Aa);B[Ca>>2]=Ba;function mc(a){var b=Array(pa(a)+1);E(a,b,0,b.length);return b}e.wasmTableSize=23;e.wasmMaxTableSize=23;e.u={};
e.v={abort:y,enlargeMemory:function(){Da()},getTotalMemory:function(){return G},abortOnCannotGrowMemory:Da,___setErrNo:Pa,__sapp_js_create_textfield:function(){var a=document.createElement("INPUT");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){nc()});document.body.append(a)},__sapp_js_focus_textfield:function(){document.getElementById("_sokol_app_input_element").focus()},_clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===
a&&(ba||"undefined"!==typeof dateNow||(p||q)&&self.performance&&self.performance.now))a=J();else return Pa(22),-1;B[b>>2]=a/1E3|0;B[b+4>>2]=a%1E3*1E6|0;return 0},_emscripten_get_device_pixel_ratio:function(){return window.devicePixelRatio||1},_emscripten_get_element_css_size:function(a,b,c){a=a?R(a):e.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),F[b>>3]=a.right-a.left,F[c>>3]=a.bottom-a.top):(F[b>>3]=a.clientWidth,F[c>>3]=a.clientHeight);return 0},_emscripten_set_canvas_element_size:function(a,
b,c){a=a?R(a):e.canvas;if(!a)return-4;a.width=b;a.height=c;return 0},_emscripten_set_keydown_callback:function(a,b,c,d){Qb(a,b,c,d,2,"keydown");return 0},_emscripten_set_keypress_callback:function(a,b,c,d){Qb(a,b,c,d,1,"keypress");return 0},_emscripten_set_keyup_callback:function(a,b,c,d){Qb(a,b,c,d,3,"keyup");return 0},_emscripten_set_main_loop:Ya,_emscripten_set_main_loop_timing:Qa,_emscripten_set_mousedown_callback:function(a,b,c,d){Sb(a,b,c,d,5,"mousedown");return 0},_emscripten_set_mouseenter_callback:function(a,
b,c,d){Sb(a,b,c,d,33,"mouseenter");return 0},_emscripten_set_mouseleave_callback:function(a,b,c,d){Sb(a,b,c,d,34,"mouseleave");return 0},_emscripten_set_mousemove_callback:function(a,b,c,d){Sb(a,b,c,d,8,"mousemove");return 0},_emscripten_set_mouseup_callback:function(a,b,c,d){Sb(a,b,c,d,6,"mouseup");return 0},_emscripten_set_resize_callback:function(a,b,c,d){Ub(a,b,c,d);return 0},_emscripten_set_touchcancel_callback:function(a,b,c,d){Vb(a,b,c,d,25,"touchcancel");return 0},_emscripten_set_touchend_callback:function(a,
b,c,d){Vb(a,b,c,d,23,"touchend");return 0},_emscripten_set_touchmove_callback:function(a,b,c,d){Vb(a,b,c,d,24,"touchmove");return 0},_emscripten_set_touchstart_callback:function(a,b,c,d){Vb(a,b,c,d,22,"touchstart");return 0},_emscripten_set_wheel_callback:function(a,b,c,d){a=R(a);return"undefined"!==typeof a.onwheel?(Tb(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(Tb(a,b,c,d,"mousewheel"),0):-1},_emscripten_webgl_create_context:function(a,b){var c={};c.alpha=!!B[b>>2];c.depth=!!B[b+4>>
2];c.stencil=!!B[b+8>>2];c.antialias=!!B[b+12>>2];c.premultipliedAlpha=!!B[b+16>>2];c.preserveDrawingBuffer=!!B[b+20>>2];c.preferLowPowerToHighPerformance=!!B[b+24>>2];c.failIfMajorPerformanceCaveat=!!B[b+28>>2];c.majorVersion=B[b+32>>2];c.minorVersion=B[b+36>>2];c.explicitSwapControl=B[b+44>>2];a=(a=D(a))&&"#canvas"!==a||!e.canvas?bc[a]||R(a):e.canvas.id?bc[e.canvas.id]||R(e.canvas.id):e.canvas;return a?c.explicitSwapControl?(console.error("emscripten_webgl_create_context failed: explicitSwapControl is not supported, please rebuild with -s OFFSCREENCANVAS_SUPPORT=1 to enable targeting the experimental OffscreenCanvas specification!"),
0):ob(a,c):0},_emscripten_webgl_init_context_attributes:function(a){B[a>>2]=1;B[a+4>>2]=1;B[a+8>>2]=0;B[a+12>>2]=1;B[a+16>>2]=1;B[a+20>>2]=0;B[a+24>>2]=0;B[a+28>>2]=0;B[a+32>>2]=1;B[a+36>>2]=0;B[a+40>>2]=1;B[a+44>>2]=0},_emscripten_webgl_make_context_current:function(a){return qb(a)?0:-5},_glActiveTexture:function(a){GLctx.activeTexture(a)},_glAttachShader:function(a,b){GLctx.attachShader(S[a],V[b])},_glBindBuffer:function(a,b){GLctx.bindBuffer(a,b?Yb[b]:null)},_glBindFramebuffer:function(a,b){GLctx.bindFramebuffer(a,
b?Zb[b]:null)},_glBindRenderbuffer:function(a,b){GLctx.bindRenderbuffer(a,b?T[b]:null)},_glBindTexture:function(a,b){GLctx.bindTexture(a,b?U[b]:null)},_glBlendColor:function(a,b,c,d){GLctx.blendColor(a,b,c,d)},_glBlendEquationSeparate:function(a,b){GLctx.blendEquationSeparate(a,b)},_glBlendFuncSeparate:function(a,b,c,d){GLctx.blendFuncSeparate(a,b,c,d)},_glBufferData:function(a,b,c,d){c?GLctx.bufferData(a,C.subarray(c,c+b),d):GLctx.bufferData(a,b,d)},_glBufferSubData:function(a,b,c,d){GLctx.bufferSubData(a,
b,C.subarray(d,d+c))},_glCheckFramebufferStatus:function(a){return GLctx.checkFramebufferStatus(a)},_glClear:function(a){GLctx.clear(a)},_glClearColor:function(a,b,c,d){GLctx.clearColor(a,b,c,d)},_glClearDepthf:function(a){GLctx.clearDepth(a)},_glClearStencil:function(a){GLctx.clearStencil(a)},_glColorMask:function(a,b,c,d){GLctx.colorMask(!!a,!!b,!!c,!!d)},_glCompileShader:function(a){GLctx.compileShader(V[a])},_glCompressedTexImage2D:function(a,b,c,d,f,h,k,n){GLctx.compressedTexImage2D(a,b,c,d,
f,h,n?C.subarray(n,n+k):null)},_glCreateProgram:function(){var a=Y(S),b=GLctx.createProgram();b.name=a;S[a]=b;return a},_glCreateShader:function(a){var b=Y(V);V[b]=GLctx.createShader(a);return b},_glCullFace:function(a){GLctx.cullFace(a)},_glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],f=Yb[d];f&&(GLctx.deleteBuffer(f),f.name=0,Yb[d]=null,d==ic&&(ic=0),d==jc&&(jc=0))}},_glDeleteFramebuffers:function(a,b){for(var c=0;c<a;++c){var d=B[b+4*c>>2],f=Zb[d];f&&(GLctx.deleteFramebuffer(f),
f.name=0,Zb[d]=null)}},_glDeleteProgram:function(a){if(a){var b=S[a];b?(GLctx.deleteProgram(b),b.name=0,S[a]=null,W[a]=null):X(1281)}},_glDeleteRenderbuffers:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],f=T[d];f&&(GLctx.deleteRenderbuffer(f),f.name=0,T[d]=null)}},_glDeleteShader:function(a){if(a){var b=V[a];b?(GLctx.deleteShader(b),V[a]=null):X(1281)}},_glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],f=U[d];f&&(GLctx.deleteTexture(f),f.name=0,U[d]=null)}},_glDepthFunc:function(a){GLctx.depthFunc(a)},
_glDepthMask:function(a){GLctx.depthMask(!!a)},_glDisable:function(a){GLctx.disable(a)},_glDisableVertexAttribArray:function(a){GLctx.disableVertexAttribArray(a)},_glDrawArrays:_glDrawArrays,_glDrawElements:_glDrawElements,_glEnable:function(a){GLctx.enable(a)},_glEnableVertexAttribArray:function(a){GLctx.enableVertexAttribArray(a)},_glFramebufferRenderbuffer:function(a,b,c,d){GLctx.framebufferRenderbuffer(a,b,c,T[d])},_glFramebufferTexture2D:function(a,b,c,d,f){GLctx.framebufferTexture2D(a,b,c,U[d],
f)},_glFrontFace:function(a){GLctx.frontFace(a)},_glGenBuffers:function(a,b){for(var c=0;c<a;c++){var d=GLctx.createBuffer();if(!d){for(X(1282);c<a;)B[b+4*c++>>2]=0;break}var f=Y(Yb);d.name=f;Yb[f]=d;B[b+4*c>>2]=f}},_glGenFramebuffers:function(a,b){for(var c=0;c<a;++c){var d=GLctx.createFramebuffer();if(!d){for(X(1282);c<a;)B[b+4*c++>>2]=0;break}var f=Y(Zb);d.name=f;Zb[f]=d;B[b+4*c>>2]=f}},_glGenRenderbuffers:function(a,b){for(var c=0;c<a;c++){var d=GLctx.createRenderbuffer();if(!d){for(X(1282);c<
a;)B[b+4*c++>>2]=0;break}var f=Y(T);d.name=f;T[f]=d;B[b+4*c>>2]=f}},_glGenTextures:function(a,b){for(var c=0;c<a;c++){var d=GLctx.createTexture();if(!d){for(X(1282);c<a;)B[b+4*c++>>2]=0;break}var f=Y(U);d.name=f;U[f]=d;B[b+4*c>>2]=f}},_glGetAttribLocation:function(a,b){a=S[a];b=D(b);return GLctx.getAttribLocation(a,b)},_glGetIntegerv:function(a,b){kc(a,b)},_glGetProgramInfoLog:function(a,b,c,d){a=GLctx.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");0<b&&d?(b=E(a,C,d,b),c&&(B[c>>2]=b)):c&&
(B[c>>2]=0)},_glGetProgramiv:function(a,b,c){if(c)if(a>=Wb)X(1281);else{var d=W[a];if(d)if(35716==b)a=GLctx.getProgramInfoLog(S[a]),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b)B[c>>2]=d.m;else if(35722==b){if(-1==d.h){a=S[a];var f=GLctx.getProgramParameter(a,GLctx.ACTIVE_ATTRIBUTES);for(b=d.h=0;b<f;++b)d.h=Math.max(d.h,GLctx.getActiveAttrib(a,b).name.length+1)}B[c>>2]=d.h}else if(35381==b){if(-1==d.i)for(a=S[a],f=GLctx.getProgramParameter(a,GLctx.I),b=d.i=0;b<f;++b){var h=
GLctx.O(a,b);d.i=Math.max(d.i,h.length+1)}B[c>>2]=d.i}else B[c>>2]=GLctx.getProgramParameter(S[a],b);else X(1282)}else X(1281)},_glGetShaderInfoLog:function(a,b,c,d){a=GLctx.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");0<b&&d?(b=E(a,C,d,b),c&&(B[c>>2]=b)):c&&(B[c>>2]=0)},_glGetShaderiv:function(a,b,c){c?35716==b?(a=GLctx.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1):35720==b?(a=GLctx.getShaderSource(V[a]),B[c>>2]=null===a||0==a.length?0:a.length+1):B[c>>2]=GLctx.getShaderParameter(V[a],
b):X(1281)},_glGetString:function(a){if(dc[a])return dc[a];switch(a){case 7936:case 7937:case 37445:case 37446:var b=ma(mc(GLctx.getParameter(a)));break;case 7938:b=ma(mc("OpenGL ES 2.0 ("+GLctx.getParameter(GLctx.VERSION)+")"));break;case 7939:b=GLctx.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=ma(mc(c.join(" ")));break;case 35724:b=GLctx.getParameter(GLctx.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&
(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ma(mc(b));break;default:return X(1280),0}return dc[a]=b},_glGetUniformLocation:function(a,b){b=D(b);var c=0;if(-1!==b.indexOf("]",b.length-1)){var d=b.lastIndexOf("["),f=b.slice(d+1,-1);if(0<f.length&&(c=parseInt(f),0>c))return-1;b=b.slice(0,d)}a=W[a];return a?(b=a.s[b])&&c<b[0]?b[1]+c:-1:-1},_glLinkProgram:function(a){GLctx.linkProgram(S[a]);W[a]=null;var b=S[a];W[a]={s:{},m:0,h:-1,i:-1};a=W[a];for(var c=a.s,d=GLctx.getProgramParameter(b,
GLctx.ACTIVE_UNIFORMS),f=0;f<d;++f){var h=GLctx.getActiveUniform(b,f),k=h.name;a.m=Math.max(a.m,k.length+1);-1!==k.indexOf("]",k.length-1)&&(k=k.slice(0,k.lastIndexOf("[")));var n=GLctx.getUniformLocation(b,k);if(null!=n){var m=Y($b);c[k]=[h.size,m];$b[m]=n;for(var l=1;l<h.size;++l)n=GLctx.getUniformLocation(b,k+"["+l+"]"),m=Y($b),$b[m]=n}}},_glPolygonOffset:function(a,b){GLctx.polygonOffset(a,b)},_glRenderbufferStorage:function(a,b,c,d){GLctx.renderbufferStorage(a,b,c,d)},_glScissor:function(a,b,
c,d){GLctx.scissor(a,b,c,d)},_glShaderSource:function(a,b,c,d){for(var f="",h=0;h<b;++h){if(d){var k=B[d+4*h>>2];k=0>k?D(B[c+4*h>>2]):D(B[c+4*h>>2],k)}else k=D(B[c+4*h>>2]);f+=k}GLctx.shaderSource(V[a],f)},_glStencilFunc:function(a,b,c){GLctx.stencilFunc(a,b,c)},_glStencilFuncSeparate:function(a,b,c,d){GLctx.stencilFuncSeparate(a,b,c,d)},_glStencilMask:function(a){GLctx.stencilMask(a)},_glStencilOp:function(a,b,c){GLctx.stencilOp(a,b,c)},_glStencilOpSeparate:function(a,b,c,d){GLctx.stencilOpSeparate(a,
b,c,d)},_glTexImage2D:function(a,b,c,d,f,h,k,n,m){var l=null;m&&(l=lc(n,k,d,f,m));GLctx.texImage2D(a,b,c,d,f,h,k,n,l)},_glTexParameteri:function(a,b,c){GLctx.texParameteri(a,b,c)},_glTexSubImage2D:function(a,b,c,d,f,h,k,n,m){var l=null;m&&(l=lc(n,k,f,h,m));GLctx.texSubImage2D(a,b,c,d,f,h,k,n,l)},_glUniform1i:function(a,b){GLctx.uniform1i($b[a],b)},_glUseProgram:function(a){GLctx.useProgram(a?S[a]:null)},_glVertexAttribDivisorEXT:function(a,b){GLctx.vertexAttribDivisor(a,b)},_glVertexAttribPointer:function(a,
b,c,d,f,h){GLctx.vertexAttribPointer(a,b,c,!!d,f,h)},_glViewport:function(a,b,c,d){GLctx.viewport(a,b,c,d)},DYNAMICTOP_PTR:Ca,STACKTOP:za};var oc=e.asm(e.u,e.v,buffer);e.asm=oc;e.___em_js___sapp_js_create_textfield=function(){return e.asm.___em_js___sapp_js_create_textfield.apply(null,arguments)};e.___em_js___sapp_js_focus_textfield=function(){return e.asm.___em_js___sapp_js_focus_textfield.apply(null,arguments)};
e.___em_js___sapp_js_unfocus_textfield=function(){return e.asm.___em_js___sapp_js_unfocus_textfield.apply(null,arguments)};var nc=e.__sapp_emsc_notify_keyboard_hidden=function(){return e.asm.__sapp_emsc_notify_keyboard_hidden.apply(null,arguments)};e._main=function(){return e.asm._main.apply(null,arguments)};var z=e._malloc=function(){return e.asm._malloc.apply(null,arguments)},ra=e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)};
e.dynCall_iiii=function(){return e.asm.dynCall_iiii.apply(null,arguments)};e.dynCall_v=function(){return e.asm.dynCall_v.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.dynCall_vi.apply(null,arguments)};e.asm=oc;function r(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}r.prototype=Error();r.prototype.constructor=r;Na=function pc(){e.calledRun||qc();e.calledRun||(Na=pc)};
e.callMain=function(a){a=a||[];Ka||(Ka=!0,H(Ga));var b=a.length+1,c=ra(4*(b+1));B[c>>2]=qa(e.thisProgram);for(var d=1;d<b;d++)B[(c>>2)+d]=qa(a[d-1]);B[(c>>2)+b]=0;try{var f=e._main(b,c,0);if(!e.noExitRuntime||0!==f){if(!e.noExitRuntime&&(w=!0,za=void 0,H(Ia),e.onExit))e.onExit(f);e.quit(f,new r(f))}}catch(h){h instanceof r||("SimulateInfiniteLoop"==h?e.noExitRuntime=!0:((a=h)&&"object"===typeof h&&h.stack&&(a=[h,h.stack]),t("exception thrown: "+a),e.quit(1,h)))}finally{}};
function qc(a){function b(){if(!e.calledRun&&(e.calledRun=!0,!w)){Ka||(Ka=!0,H(Ga));H(Ha);if(e.onRuntimeInitialized)e.onRuntimeInitialized();e._main&&rc&&e.callMain(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Ja.unshift(b)}H(Ja)}}a=a||e.arguments;if(!(0<I)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)La();H(Fa);0<I||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);b()},1)):b())}}e.run=qc;function y(a){if(e.onAbort)e.onAbort(a);void 0!==a?(fa(a),t(a),a=JSON.stringify(a)):a="";w=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=y;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var rc=!0;e.noInitialRun&&(rc=!1);e.noExitRuntime=!0;qc();
